### ISSUE TITLE
creating an empty Filter() ?

### ISSUE THREAD

**Issue by pcompassion** [elastic/elasticsearch-dsl-py#100]
Just for programming easiness,

    f = F()

    if condition:
       f = f & F(..)

Something like above is possible?

**Comment by HonzaKral** [comment]
Good idea - you can currently use `F('match_all')` that will behave exactly as you want (`f == f & F('match_all')`)

Do you (or anyone else) think that's enough or we should make it a default for `F()`?

The same works for queries btw - `Q('match_all')`

**Comment by njoannin** [comment]
Hmm, I'm not sure to grasp. Is it like this:

```
f = F('match_all')
if condition:
    f = f & F(...)
```

Correct, or did I misunderstand?
And that should work the same with Q...

**Comment by HonzaKral** [comment]
Yes, `F('match_all')` is an empty filter - it doesn't filter out anything and so there is a tiny piece of code in the `&` operator that makes sure that if you add it to another filter the result is just the other filter - https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_query.py#L86-L91

**Comment by njoannin** [comment]
OK, cool. Works for me!

**Comment by pcompassion** [comment]
so F('match_all') === F() conceptually and  computationally at the moment?

**Comment by HonzaKral** [comment]
Yes, at the moment `F('match_all')` is an empty filter - it also exists as an instance: 

    from elasticsearch_dsl.filter import EMPTY_FILTER

**Comment by apandita** [comment]
Sorry to bug here, but i fail to understand the need of an empty filter.
Can anyone elaborate the need for using an empty filter ?

**Comment by HonzaKral** [comment]
@apandita some people might prefer to always have a filter instead of conditional statements, imagine:

    filter = None
    if cat:
        filter = F('term', category=cat)
    if type:
        if filter:
            filter &= F('term', type=type)
        else:
            filter = F('term', type=type)

with an empty filter you can do:

    filter = F('match_all')
    if cat:
        filter &= F('term', category=cat)
    if type:
        filter &= F('term', type=type)

so it's much more straightforward

**Comment by runwithranvit** [comment]
Here's my way of achieving this

```python3
>>> empty_q = Q("bool")
Bool() # I prefer this

>>> empty_q_2 = Q()
MatchAll() # Same search response, but this adds "match_all" queries to the search request object
```

The benefit is that when combining many `must`/`must_not` queries, `Q("bool")` will not add anything to query, whereas `Q()` will add a `match_all` that is just annoying to look at. I think performance would be identical based on the above discussion.
