### ISSUE TITLE
Bad type: `CharFilter.to_dict` returns a string

### ISSUE THREAD

**Issue by tliu30** [elastic/elasticsearch-dsl-py#1002]
Hello,

It doesn't seem like `CharFilter.to_dict` does what is intended - in particular, it returns a string, not a dict.

```
>>> from elasticsearch_dsl import char_filter
>>> z = char_filter('filter_name', type='mapping', mappings=['& => and'])
>>> type(z.to_dict())
str
>>> z.to_dict()
'filter_name'
```

Happy to try to patch if this isn't the intended behavior (what is the intended behavior of `to_dict` in this case)?

Tony

**Comment by HonzaKral** [comment]
This is the proper behavior. `to_dict` is badly named, better name would be `to_json` - it is used to serialize things for use in the body, in this case, when you want to use a char filter you expect to just use the name.

Hope this helps!
