### ISSUE TITLE
Q: how to add normalizers, char_filters, etc to 'base' Index?

### ISSUE THREAD

**Issue by jaddison** [elastic/elasticsearch-dsl-py#1008]
I'm looking to create a _base_ `Index` with common settings, so I can clone it for each of my actual `Index`es. `Index` has a `.analyzer(...)` method to add a custom analyzer, but I don't see any:

- `.normalizer(...)`
- `.tokenizer(...)`
- `.char_filter(...)`
- `.filter(...)`
- others?

I suppose that since `tokenizer`, `char_filter`, and `filter` are used in the creation of the other elements, associated methods don't need to exist on `Index` - but perhaps `Index.normalizer(...)`?

For example, I'm moving from these old settings from [a django->elasticsearch package](https://github.com/jaddison/django-simple-elasticsearch; which is not es-dsl-py based) a new es-dsl-py based package I'm building.  Each of my indexes would have these settings merged in:
```
ELASTICSEARCH_DEFAULT_INDEX_SETTINGS = {
    "settings": {
        "index": {
            "number_of_replicas": 1,
            "number_of_shards": 9
        },
        "analysis": {
            "normalizer": {
                "sorting": {
                    "type": "custom",
                    # TODO: consider stripping html tags/leading non-alphanum chars manually;
                    # elasticsearch 'normalizers' don't support
                    # "char_filter": ["html_strip", "remove_leading_non_alphanum"],
                    "filter": ["lowercase", "asciifolding"]
                },
            },
            "analyzer": {
                "default": {
                    "type": "custom",
                    "tokenizer": "standard",
                    "filter": ["standard", "lowercase", "asciifolding", "stop", "snowball"],
                    "char_filter": ["html_strip"]
                },
                "nostop": {
                    "type": "custom",
                    "tokenizer": "standard",
                    "filter": ["standard", "lowercase", "asciifolding"],
                    "stopwords": [],
                    "char_filter": ["html_strip", "remove_leading_non_alphanum"]
                },
                "autocomplete": {
                    "type": "custom",
                    "tokenizer": "standard",
                    "filter": ["standard", "lowercase", "asciifolding", "autocomplete"],
                    "stopwords": [],
                    "char_filter": ["html_strip", "remove_leading_non_alphanum"]
                }
            },
            "filter": {
                "autocomplete": {
                    "type": "edgeNGram",
                    "min_gram": 1,
                    "max_gram": 20
                }
            },
            "char_filter": {
                "remove_leading_non_alphanum": {
                    "type": "pattern_replace",
                    "pattern": "^(\W|_)+",
                    "replacement": ""
                }
            }
        }
    }
}
```

How would I best go about 'converting' the above to an Index that I can clone?
- use `Index.settings(...)` to pass in the above?
- use es-dsl-py's `normalizer()`, `filter()`, `char_filter()`, etc to create reusable instances of those elements and apply them at the field level?

Thanks! As always, let me know if I am missing something.

**Comment by HonzaKral** [comment]
The easiest way is of course to assign the `analyzer` and `normalizer` objects directly to the `Text` fields, no need to assign them to the index manually - all the custom analyzers and normalizers defined on fields will automatically be included in the `Index` body when it's being created.

That is also why there is no `normalizer` method - while there is a reason to define an `analyzer` on an `Index` without it being used on a field (for example if it's to be used as a search analyzer at query time) there is no such reason for a `normalizer` to be added as it cannot be used outside of a field.

Does that make sense?

Thank you!

**Comment by jaddison** [comment]
It does, thanks for taking the time to clarify best practices on this!

**Comment by sdiez** [comment]
Hello, I know this is a closed issue, but there is a use case for having a `normalizer` method for the `Index` class. 

If you are using dynamic templates and you want to use a `normalizer` for a `Keyword` field, the normalizer won't be available on index creation. The only workaround I can imagine is to use a "dummy" `Keyword` field on the document definition where the normalizer is declared. This is not an elegant solution and having access to a `normalizer` method will make this way easier.

Also I know that this might not be the better place, but thank you for all your work. This is an amazing library.
