### ISSUE TITLE
Normalizers, Analyzers, etc aren't copied from fields when cloning Index

### ISSUE THREAD

**Issue by jaddison** [elastic/elasticsearch-dsl-py#1009]
Maybe related to #957?

My definitions of the 'base' `Index` along with all filters, analyzers, normalizers:
```python
from elasticsearch_dsl import Index, normalizer, analyzer, char_filter, token_filter

autocomplete_filter = token_filter(
    'autocomplete', 'edgeNGram',
    min_gram=1,
    max_gram=20)

remove_leading_non_alphanum_char_filter = char_filter(
    'remove_leading_non_alphanum', 'pattern_replace',
    pattern="^(\W|_)+",
    replacement="")

sorting_normalizer = normalizer(
    'sorting',
    filter=["lowercase", "asciifolding"])

default_analyzer = analyzer(
    'default',
    tokenizer="standard",
    filter=["standard", "lowercase", "asciifolding", "stop", "snowball"],
    char_filter=["html_strip"])

nostop_analyzer = analyzer(
    'nostop',
    tokenizer="standard",
    filter=["standard", "lowercase", "asciifolding"],
    stopwords=[],
    char_filter=["html_strip", remove_leading_non_alphanum_char_filter])

autocomplete_analyzer = analyzer(
    'autocomplete',
    tokenizer="standard",
    filter=["standard", "lowercase", "asciifolding", autocomplete_filter],
    stopwords=[],
    char_filter=["html_strip", remove_leading_non_alphanum_char_filter])

base_index = Index('base')
base_index.analyzer(default_analyzer)
```

A simple sample `Index` and `Document` that will generate the error that follows:
```python
# this clone is NOT an issue, the default analyzer settings etc all transfer correctly
i = base_index.clone('user-related')

@i.document
class UserDoc(Document):
    name = field.Keyword(
        normalizer=sorting_normalizer,
        fields={"autocomplete": field.Text(
            analyzer=autocomplete_analyzer,
            search_analyzer=nostop_analyzer)
        })
```
`i.to_dict()` **correctly** yields the following:
```JSON
{
  "mappings": {
    "doc": {
      "properties": {
        "name": {
          "fields": {
            "autocomplete": {
              "analyzer": "autocomplete",
              "search_analyzer": "nostop",
              "type": "text"
            }
          },
          "normalizer": "sorting",
          "type": "keyword"
        }
      }
    }
  },
  "settings": {
    "analysis": {
      "analyzer": {
        "autocomplete": {
          "type": "custom",
          "tokenizer": "standard",
          "stopwords": [],
          "filter": [
            "standard",
            "lowercase",
            "asciifolding",
            "autocomplete"
          ],
          "char_filter": [
            "html_strip",
            "remove_leading_non_alphanum"
          ]
        },
        "default": {
          "tokenizer": "standard",
          "type": "custom",
          "filter": [
            "standard",
            "lowercase",
            "asciifolding",
            "stop",
            "snowball"
          ],
          "char_filter": [
            "html_strip"
          ]
        },
        "nostop": {
          "type": "custom",
          "tokenizer": "standard",
          "stopwords": [],
          "filter": [
            "standard",
            "lowercase",
            "asciifolding"
          ],
          "char_filter": [
            "html_strip",
            "remove_leading_non_alphanum"
          ]
        }
      },
      "normalizer": {
        "sorting": {
          "type": "custom",
          "filter": [
            "lowercase",
            "asciifolding"
          ]
        }
      },
      "filter": {
        "autocomplete": {
          "min_gram": 1,
          "max_gram": 20,
          "type": "edgeNGram"
        }
      },
      "char_filter": {
        "remove_leading_non_alphanum": {
          "replacement": "",
          "type": "pattern_replace",
          "pattern": "^(\\W|_)+"
        }
      }
    }
  }
}
```
But after cloning, the important elements are (**incorrectly**, I think?) missing; `i.clone('user-related-20180905').to_dict()` outputs (note it does keep my default analyzer I added to `base_index`):
```
{
  "mappings": {
    "doc": {
      "properties": {
        "name": {
          "type": "keyword",
          "normalizer": "sorting",
          "fields": {
            "autocomplete": {
              "type": "text",
              "search_analyzer": "nostop",
              "analyzer": "autocomplete"
            }
          }
        }
      }
    }
  },
  "settings": {
    "analysis": {
      "analyzer": {
        "default": {
          "type": "custom",
          "tokenizer": "standard",
          "filter": [
            "standard",
            "lowercase",
            "asciifolding",
            "stop",
            "snowball"
          ],
          "char_filter": [
            "html_strip"
          ]
        }
      }
    }
  }
}
```
To further illustrate, this the output from a cloned index `.create()` is:
```
PUT http://localhost:9200/user-related-20180905-064032 [status:400 request:0.013s]
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/vagrant/esdocs/contrib/esdjango/run.py", line 25, in <module>
    run(DjangoController)
  File "/vagrant/esdocs/utils.py", line 101, in run
    controller.run_operation(cmd_parser=parser, **options)
  File "/vagrant/esdocs/controller.py", line 85, in run_operation
    getattr(self, "index_{}".format(action))(**options)
  File "/vagrant/esdocs/controller.py", line 122, in index_rebuild
    self._index_create(index, name, set_alias=False)
  File "/vagrant/esdocs/controller.py", line 169, in _index_create
    index.create(using=self.using)
  File "/home/ubuntu/.virtualenvs/myproject/lib/python3.5/site-packages/elasticsearch_dsl/index.py", line 220, in create
    self._get_connection(using).indices.create(index=self._name, body=self.to_dict(), **kwargs)
  File "/home/ubuntu/.virtualenvs/myproject/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/ubuntu/.virtualenvs/myproject/lib/python3.5/site-packages/elasticsearch/client/indices.py", line 88, in create
    params=params, body=body)
  File "/home/ubuntu/.virtualenvs/myproject/lib/python3.5/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/ubuntu/.virtualenvs/myproject/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/ubuntu/.virtualenvs/myproject/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'analyzer [nostop] not found for field [autocomplete]')
```

**Comment by jaddison** [comment]
Apologies for the ping, @HonzaKral and other maintainers - just wondering if this is something to be fixed or not. Seems weird to copy over the field mapping, but not the analyzer/normalizer settings.

**Comment by HonzaKral** [comment]
Could you please verify that this wasn't fixed by https://github.com/elastic/elasticsearch-dsl-py/commit/cffaab452080064b3ba06d6bb6f8c466f414e25a? Thanks!

**Comment by jaddison** [comment]
@HonzaKral Thanks - it looks like that is addressed, but I'm now noticing that the index set on the document class in the metaclass initialization remains named `'*'` after the `@i.document` decorator. So, stealing from above:

```
base_index = Index('base')
i = base_index.clone('user-related')

@i.document
class UserDoc(Document):
    id=field.Long()
```

`i._name` will be 'user-related', as expected.
`i._doc_types[0]` will be `UserDoc`, as expected.
`i._doc_types[0]._index._name` will be `'*'` - not expected.

**Comment by jaddison** [comment]
If I do the following modification to the above code (note the last line), things work as desired:
```
base_index = Index('base')
i = base_index.clone('user-related')

@i.document
class UserDoc(Document):
    id=field.Long()

# obviously undesired, makes things work
UserDoc._index = i
```

Note that my use case is somewhat elaborate: from the (many!) lessons I've learned from making/maintaining [django-simple-elasticsearch (DSE)](https://github.com/jaddison/django-simple-elasticsearch), I'm creating a new serialization package. My plan is for it to 

* have a Django contrib module, yet not be Django-specific
* support real-time individual index/delete operations (as is common using Django signals, for example)
* support multiprocessing-based parallel bulk indexing, with alias support to avoid downtime

DSE supported much of the above, but used the low-level ES client. Obviously, I'm building the new package to use ES-dsl-py - yay!  A simplified view of my code:

```
# my base class that users must subclass and fill out
class Serializer:
    document = None
    ...
    @classmethod
    def fetch_data(cls):
        raise NotImplementedError

# project-specific 
class UserSerializer(Serializer):
    document = UserDoc
    ...
    @classmethod
    def fetch_data(cls):
        return <list of stuff, generator, queryset, etc>
```

Using metaclasses, I've got a 'registry' of `Serializer`-based subclasses. Through the `.document` attribute, I can access the `.document._index` object, which I use to:

1. `.clone(...)` to a timestamped name like `user-related-20180811-091756`
1. initialize it to create it in ES
1. bulk index all of the `Serializer`-based subclass' data from `.fetch_data()`
1. create/replace alias; ie `user-related` to `user-related-20180811-091756`

Having `'*'` as the `UserSerializer.document._index._name` doesn't allow this to work. Hopefully that was at least somewhat clear enough to demonstrate why I think this is incorrect? Apologies if it isn't.

**Comment by jaddison** [comment]
@HonzaKral Again, apologies for the ping. I'm wondering if I'm off-base on this or not? It seems intuitive to me that after using `@i.document` i._doc_types[0]._index would be the same as `i`.

**Comment by HonzaKral** [comment]
the idea is that you either use an `Index` object (`i` in your case) and then you just use that and you don't want to set the index name on the `Document` since you will be using the `Index` object, or you use the `class Index` part of the `Document` definition.

**Comment by jaddison** [comment]
Thanks for the response. I understand what you're saying. 

So for my use case, I need to pick between:

- ~having a base `Index` with default settings all my indexes should inherit~ (doesn't work for my case)
- duplicating the default index settings for each of my documents (via the `Document`'s `class Index` attribute)
- kludging things to work (as mentioned above, but copying below for clarity)

```
base_index = Index('base')
i = base_index.clone('user-related')

@i.document
class UserDoc(Document):
    id=field.Long()

# obviously undesired, makes things work
UserDoc._index = i
```

Is it possible to 'set' the `class Index` attribute to a base `Index` at all? Like:
```
class UserDoc(Document):
    id = field.Long()
    ...

    Index = base_index.clone('user-related')
```

I don't think it's possible, but that would provide the necessary flexibility to reuse a base index in all scenarios.

Thanks again!

**Comment by jaddison** [comment]
Unless I'm mistaken, I believe that this doesn't just affect my use case - it's much more broad and is a bug:

`Document` specific functionality cannot work when decorating a `Document` subclass with `@i.document` because of the 'invalid internal' `._index`. 

For example (unless I'm mistaken, wouldn't be the first time), there's no way that `UserDoc`'s `.save()` method can work. Neither does `UserDoc.search(...)`.

**Comment by HonzaKral** [comment]
Any method on `Document` that operates on an index accepts an index name as a parameter, like `search`, `save`, or `init`. You can also use a template to control the mappings.

For a collection of indices using versions and an alias to reindex please see the provided example that does just that - https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/alias_migration.py

**Comment by jaddison** [comment]
Thanks @HonzaKral. Again, I understand what you're saying (although I'll admit I'd glossed over the ability to pass in an index on Document operations). 

That said - and ignoring my use case for now - is it reasonable to expect someone who uses the `@<index>.document` decorator to have to keep that index around to do operations elsewhere in code?

```
# in app/search_base.py
base_index = Index('base')
base_index.settings(...)

------------------

# in users/search.py:
from app.search_base import base_index
user_index = base_index.clone('user-related')
user_index.settings(...)  # user specific index settings

@user_index.document
class UserDoc(Document):
    id=field.Long()

------------------

# in users/views.py
from .search import user_index, UserDoc

def user_list(request):
  users = UserDoc.search(index=user_index._name).query(...).execute()
  # OR hardcoding
  users = UserDoc.search(index='user-related').query(...).execute()


def user_details(request, pk):
  users = UserDoc.get(pk, index=user_index._name)
  # OR hardcoding
  users = UserDoc.get(pk, index='user-related')
```
Where the same code without the decorator is more intuitive and less fragile:
```
# in search.py:
class UserDoc(Document):
    id=field.Long()

    class Index:
        name = 'user-related'

------------------

# in views.py
from .search import UserDoc

def user_list(request):
  users = UserDoc.search().query(...).execute()

def user_details(request, pk):
  users = UserDoc.get(pk)
```

**If you still disagree, then by all means, please close this ticket**. I may not understand _why_ it is this way, but I'm willing to accept that it's like that for a specific reason (although I would obviously still like to understand why, and why my suggestion isn't valid - still, it's your project, it's of course your call).

The user must pick between:
- having a base index (no settings repetition, etc) but repetition of the index name everywhere
- copying common index settings, etc to all `Document` `class Index` and convenience of ignoring what the index name is throughout application code

Honestly, I won't be too upset if you just close this ticket without replying. You've put up with a lot of my pushback. Cheers - and **thanks for all the effort on the Python bindings!**

**Comment by HonzaKral** [comment]
`@i.document` is about assigning the `Dcoument` to the `Index` not the other way around. We should certainly make it clearer in the docs. It is only useful when working with an `Index` object and, with types going away, there is no real reason to do that unless you are doing something very specific.

For your use case, please, again, look at the example with alias migration, that is what I would recommend - no ambiguity, no extra decorators, works out of the box with the decorators without the need to redeploy your application when a new index is introduced. Settings are governed by the template and can be changed any time as well. If there is something missing from that example, please let me know.

Thank you!
