### ISSUE TITLE
[API docs] Referring deprecated execute_suggest()

### ISSUE THREAD

**Issue by shiouming** [elastic/elasticsearch-dsl-py#1011]
The instruction under **Search section** uses `execute_suggest()` for completion suggester. However, this method seems to be deprecated according to https://github.com/elastic/elasticsearch-dsl-py/issues/903#issuecomment-390419791
Document: https://github.com/elastic/elasticsearch-dsl-py/blob/master/docs/persistence.rst

If this is confirmed unintentional, I can help to patch the document. Let me know.

**Comment by HonzaKral** [comment]
Thank you for the issue, good catch!
