### ISSUE TITLE
Docs: refer to non-existent search_type: count

### ISSUE THREAD

**Issue by jaddison** [elastic/elasticsearch-dsl-py#1013]
[The docs for `Search().params(...)`](https://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#extra-properties-and-parameters) refer to functionality that has been removed from Elasticsearch.

1. to get `search_type=count` behaviour, use a `0` as the page size, like `Search().query(...)[:0]` (if you want it in a `MultiSearch`) or just use `Search().query(...).count()` to execute and get the total returned
1. for the docs, perhaps use `routing` as the example?

**Comment by HonzaKral** [comment]
Thank you for the report, good catch. Changed it to `routing="42"` which is both valid and useful.
