### ISSUE TITLE
Faceted search improvements 

### ISSUE THREAD

**Issue by clement-tourriere** [elastic/elasticsearch-dsl-py#1014]
Hello,
Faceted search is a really great functionnality in elasticsearch-dsl, it allows to easily create faceted results. However, I think it lacks of consistency and some functionnalities.

In the first place, I think faceted navigation lies on two main principles:

 - facets computation
 - facet filtering

Although this two parts are close related, one can be called without the other. 
Imagine an API entry-point for computing aggregation, or another API entry-point for a geo service, these entry-points don't need the results of facetting (the different values and counts), but only need the filtering aspect of facetting.

Considering this, the FacetedSearch object must be merged into the basic Search object. This new object could be able to handle facets computation or facet filtering or both. 

One important limitation is to forbid aggregations request in a facet search query (to avoid some messy cases when building the request).

Facet filtering must be allow in all queries.

Considering facet filtering, the current implentation lacks of two "major" features.

The first one is the possibility to perform an "AND" filter and not only an "OR" (checkbox facetting only). 

The second one is a third state/action "EXCLUDED" to a facet. For the moment a facet can only be selected or not. A great alternative could be 3 states: DISPLAYED, RESTRICTED and EXCLUDED.

I really don't know if you are working on these kind of features, but I have a working implementation for all these points, and it would be a pleasure to contribute with a PR.

With best regards.

**Comment by HonzaKral** [comment]
Hi @clement-tourriere, thank you for opening the issue!

I have to admit I am not 100% sure what exactly it is you are asking for but I would be super happy to have a look at the PR and have a concrete discussion over code if it's not too much work for you.

Overall I am fairly happy with `FacetedSearch` having just the basic functionality while allowing people to extend it for some extra steps they might need. Ultimately though, for more advanced use cases, people should just construct the `Search` request themselves, maybe looking at the `FacetedSearch` for inspiration.

That is my idea of usage but I am more than happy to hear feedback on what would actually be useful to most people.

**Comment by clement-tourriere** [comment]
Hi @HonzaKral, thank you for your quick answer.
I am working on a PR to share my ideas, but in fact it is exactly what you mentioned at the end of your comment: overloading the `Search` object to move the facet logic in it. 

There is an additional parameter `facet_filtering_only`, that if `True` and with a facet dict configured will only apply facet filters on the query, without building aggregations for the facets.

For the moment the PR is quite hard to release in a proper state since it moves some code from `FacetedSearch` to `Search` object, but if you don't mind, I can share it.

**Comment by HonzaKral** [comment]
I would always be happy to look at the code but honestly I don't believe the code from `FacetedSearch` belongs to `Search` as it is highly specialized whereas `Search` is very generic.

For `facet_filtering_only` all you have to do is override the `aggregate` method and just leave it empty, that is not more code then setting a configuration option:
```python
class MySearch(FacetedSearch):
    ...
    def aggregate(self, search): pass
```

Would that be enough? Again the reasoning here is that you should feel free to override any of the methods to change the logic directly with code without us having to support all the different flags and settings.

**Comment by Rafalonso** [comment]
I actually also need the exclusion clause in faceted search, to circumvent this I had to add override init to take a exclusion dict and change search.

```
def __init__(self, excluded=None, *args, **kwargs):
        self.excluded = excluded or {}
        super(GameSearch, self).__init__(*args, **kwargs)

def search(self):
        s = super(GameSearch, self).search()
        for key, value in iteritems(self.excluded):
            s = s.exclude(name_or_query='match', **{key: value})
        return s
```

**Comment by sethmlarson** [comment]
Closing this as solved / stale
