### ISSUE TITLE
Should 'collapse' cause the targeted field to become a list value?

### ISSUE THREAD

**Issue by jaddison** [elastic/elasticsearch-dsl-py#1015]
```
query.extra(collapse={
                'field': 'activity_id',
                'inner_hits': {
                    'name': 'additional',
                    'size': 1,
                    'sort': ['date_sort']
                }})
```
In my query results, **without** using the above `extra` `collapse` clause, my `activity_id` in each hit is a `long` value, as expected.

However, when using `collapse` as above, `activity_id` gets converted to a list with the original `activity_id` value as the only item in the list.

I believe it is due to the following `Hit` class code:
```
class Hit(AttrDict):
    def __init__(self, document):
        data = {}
        if '_source' in document:
            data = document['_source']
        if 'fields' in document:
            data.update(document['fields'])

        ...
```
Should this happen for `collapse` functionality?

**Comment by jaddison** [comment]
I did notice from the [ES docs for collapse](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-collapse.html) that the response includes the field as a list - I suppose that's just the way the cookie crumbles, but unless I'm mistaking things, collapsing will only ever returning a single value, no?
```
{
            "_index": "twitter",
            "_type": "_doc",
            "_id": "1",
            "_score": ..,
            "_source": {...},
            "fields": {"country": ["Canada"]},
            "inner_hits":{
                ...
}
```

I suppose this isn't going to change, and I need to work around it? Thanks again!

**Comment by HonzaKral** [comment]
Thank you for raising the issue, @jaddison! 

In this case I think we should only override the values in `_source` from `fields` if they are not already present - since the `_source` already has a field called `country` it should not be overriden by `fields`. That way we fulfill our promise to keep `_source` untouched.

Does that make sense to you?

**Comment by jaddison** [comment]
While I certainly do like that approach, I need to make sure: is it possible to have a scripted field or other way to 'redefine' an existing `_source` field that the user would expect and want to have happen?

**Comment by jaddison** [comment]
Can I provide any additional information on this? It would be good to know if this might be fixed or if the scenario I raised in my previous comment invalidated the possibility of addressing this.

**Comment by jaddison** [comment]
I think that what you propose makes sense!

**Comment by HonzaKral** [comment]
I decided to go with option `1.` for `7.0` release and will leave current code untouched as it is a breaking change.

Thank you again for the discussion, much appreciated!

**Comment by vineetphillips** [comment]
Hi @HonzaKral 
I was confused about why we are over-riding the `_source` dict with the values from `fields`. If we want to access the `field` values we can easily do that using `hit.meta`, after your last change. I have a similar issue and want to access the original value from `_source`.
