### ISSUE TITLE
Could Document support ignore fields?

### ISSUE THREAD

**Issue by foolcage** [elastic/elasticsearch-dsl-py#1016]
for example
```
class Post(Document):
    title = Text()
    title_suggest = Completion()
    created_at = Date()
    published = Boolean()
    
    ignore='ignore me'
```

So when saving the doc,we don't include the ignore fields in the json.
Maybe use @annotation for it?

**Comment by HonzaKral** [comment]
Can I ask what would be the use case for ignore fields? I guess we could do something like:

```python
class Meta:
    ignore_fields = ['fields', 'to', 'ignore']
```

but I am not 100% sure about the need for such API.

**Comment by foolcage** [comment]
I think this's related the programing style,someone just use the model as "bean" and it just contain the data could be serialized and use anothter object called "service" to manipulated the "bean",someone just want to encapsulate them in the "model".

**Comment by HonzaKral** [comment]
@foolcage to me at that point they should just wrap the actual Document class and just use composition to hide the complexities of it.

Also what you can do is to store any non-field variables in `self.meta` like it can be seen in the example at (0). Do you think that's an OK approach or you believe that having `ignore_attrs` on `class Meta` would be cleaner?

Thank you for the input!

0 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/parent_child.py#L159-L163

**Comment by foolcage** [comment]
@HonzaKral 
providing configurable ignore is better
 
I think two possible ways
1)ignore_attrs is ok
2)provide one keyword for save() method
doc.save(ignore_non_mapping=True)

https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/utils.py#L431:9

when calling to_dict(ignore_non_mapping=True)

just ignore them

Thanks a lot!

**Comment by rholloway** [comment]
I could also make use of this given how our code is written. Sometimes there are fields or references on our instances that are not part of the actual document but required for business logic aspects (utilized in save() for example which we override to provide some additional functionality)

**Comment by sethmlarson** [comment]
Agreeing with Honza here, this sounds like a good case for wrapping the document in your own class. Closing this.
