### ISSUE TITLE
Edit configuration.rst doc to improve user helpfulness

### ISSUE THREAD

**Issue by willingc** [elastic/elasticsearch-dsl-py#102]
@HonzaKral Nice meeting you at Elasticon. I thought as I learned the DSL that I would make a few edits to the documentation files to help future users.

Suggested changes for `configuration.rst` would be to put the `default configuration` before the `manual configuration` text. General grammar and readability edits too.

**Comment by GlenRSmith** [comment]
[closed by 103](https://github.com/elastic/elasticsearch-dsl-py/pull/103)
