### ISSUE TITLE
Should clauses go to must

### ISSUE THREAD

**Issue by chemiron** [elastic/elasticsearch-dsl-py#1021]
Hello,

I'm trying to join a few `should` clauses but the final query pushes them all to the `must`.
<img width="775" alt="2018-09-23 12 25 07" src="https://user-images.githubusercontent.com/7299611/45926524-ee75da00-bf2b-11e8-9d9d-d31994ad93c5.png">

I guess the code the does that is here: https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/query.py#L160

**Comment by HonzaKral** [comment]
If you have a `bool` query that only has `should` clause with a single query then that query is required. When `and`ing such query to another we then treat it as if it were in `must` since that is the proper behavior of `and`.

Hope this helps!
