### ISSUE TITLE
Recursive mapping

### ISSUE THREAD

**Issue by nefarioustim** [elastic/elasticsearch-dsl-py#1022]
Hi all,

I currently have a complicated set of SQLAlchemy models I wish to replicate in Elasticsearch. In one of my models I am using a self-referencing one-to-many relationship. This is probably best understood through code:

```python
class Location(InnerDoc):
    name = Text()
    country = Text()

Location.locations = Nested(Location)


class Vendor(Document):
  name = Text()
  country = Text()
  registration_id = Text()
  tax_id = Text()

  locations = Nested(Location)
```

Unfortunately, as you can imagine, this recursion causes infinite nesting in the mapping which means it is impossible to explicitly set the mapping for my index.

With this in mind, is there anything you can suggest to either make the mapping for my index dynamic (so that it only ever tries to deal with the levels of nesting required in the data), or to limit the levels of nesting generated in the mapping when dealing with this sort of recursion (i.e. like the `index.mapping.depth.limit` configuration value for ES)?

Thanks in advance!

**Comment by HonzaKral** [comment]
Hi @nefarioustim,

i am afraid I do not understand what data model you with to have in elasticsearch. You have one `Vendor` object that has several locations where each location has a `name` and a `country`. What else do you need to capture? Could you maybe provide a sample document that you'd like to store?

Thank you!

**Comment by nefarioustim** [comment]
Hi @HonzaKral 

Apologies for the delay in responding, and apologies for the confusing request/issue. I was attempting to simplify my models to illustrate what I meant, but obviously fell short. Ultimately, I can show what I mean using only a differing name for each location.

In data terms, I need a variable depth taxonomy for Locations within a Vendor. So I might have variations similar to the following differing datasets:

```
Vendor 1:
  - Location: Office

Vendor 2:
  - Location: London Office
  - Location: Manchester Office
  - Location: Glasgow Office

Vendor 3:
  - Location: UK
    - Location: London Office
        - Location: Finance Team
        - Location: Procurement Team
    - Location: Bristol Office
  - Location: AU
    - Location: Sydney Office
  - Location: JP Office

Vendor 4:
  - Location: California Office
    - Location: Building 1
      - Location: Finance
      - Location: Legal
    - Location: Building 2
      - Location: Product Development
  - Location: Head Office
    - Location: Corporate IT
```

Currently, I do not foresee needing a depth of more than 5 layers of taxonomy, but it would be better if I can configure that somehow. I do, however, foresee all sorts of different taxonomies of locations within those 5 layers.

I hope this helps clarify my problem. Let me know if I can give you any more information to help.

**Comment by HonzaKral** [comment]
I am sorry but this is not supported, nor is it a super useful pattern since you would be unable to query any of the nested fields without previously knowing the structure of that particular document.

What I would recommend instead is a `nested` field with additional metadata.
