### ISSUE TITLE
Idea: add upper/lower attributes for range fields

### ISSUE THREAD

**Issue by jaddison** [elastic/elasticsearch-dsl-py#1023]
in `elasticsearch_dsl.fields`:
```
class IntegerRange(Field):
    name = 'integer_range'

class FloatRange(Field):
    name = 'float_range'

class LongRange(Field):
    name = 'long_range'

class DoubleRange(Field):
    name = 'double_ranged'

class DateRange(Field):
    name = 'date_range'
```
It would be convenient to have
```
class RangeField(Field):
    @property
    def upper(self)
         upper = getattr(self, 'lt', None)
         if upper is None:
              upper = getattr(self, 'lte', None)
         return upper

    @property
    def lower(self)
         upper = getattr(self, 'gt', None)
         if upper is None:
              upper = getattr(self, 'gte', None)
         return upper

class IntegerRange(RangeField):
    name = 'integer_range'

class FloatRange(RangeField):
    name = 'float_range'

class LongRange(RangeField):
    name = 'long_range'

class DoubleRange(RangeField):
    name = 'double_ranged'

class DateRange(RangeField):
    name = 'date_range'
```

Untested code (obviously?). Having this would make it more convenient to use the field's bound values in application code, rather than just for querying purposes.

I have a Django template tag that performs this for me:
```
@register.simple_tag
def range_values(_range):
    lower = getattr(_range, 'gt', None)
    if lower is None:
        lower = getattr(_range, 'gte', None)
    upper = getattr(_range, 'lt', None)
    if upper is None:
        upper = getattr(_range, 'lte', None)
    return lower, upper
```

**Comment by HonzaKral** [comment]
Hi, thanks for the suggestion! What I would propose would be to add a `Range` object that `*_range` fields will deserialize into so that you could do (assiming `dr` is a `date_range` field):

```python
from datetime import datetime, timedelta

now = datetime.now()
doc = MyDocument(dr=Range(gte=now - timedelta(seconds=60)))

assert now in doc.dr
assert now - timedelta(seconds=61) not in doc.dr
```

We could also have a method like `limits` on the `Range` object that would return the upper/lower including a bool flag whether they are inclusive/exclusive.

What do you think?

**Comment by HonzaKral** [comment]
Thank you for the idea, I implemented it in  bb596d4. Any feedback would be more than welcome!

**Comment by jaddison** [comment]
@HonzaKral - I haven't tried this, but I'm not sure how I see it addresses my original issue as submitted? I'm looking to be able to simply get the `upper` and `lower` bounds from the range value, regardless of whether they're inclusive/exclusive bounds.

So rather than having to check for `lt` and `lte` to retrieve the upper bound, I was just looking to do `r.upper`

```
{
  "lte": 42",
  "gt": 35
```

`r.upper` would yield `42`

Not sure if that makes sense or not? That said, thanks for what you have added - makes other things easier!

**Comment by HonzaKral** [comment]
Oh, right! I got carried away a bit, will add `upper` and `lower` properties to the `Range` class. My thinking is it will return a value and a boolean whether it is inclusive or exclusive:

```python
r = Range(lt=42, gte=0)
r.lower == 0, True
r.upper == 42, False
```

Does that make more sense now?

**Comment by HonzaKral** [comment]
pushed as 2471cea427f4f18b5aa933f0724c27c2c6fe216e

**Comment by jaddison** [comment]
Yep, that makes sense! Thanks!
