### ISSUE TITLE
Using dots in fieldnames while subclassing Document

### ISSUE THREAD

**Issue by rschwiebert** [elastic/elasticsearch-dsl-py#1024]
Hi,

I'm in the process of storing the Document structures in code. To be consistent with existing indices, I need to use fieldnames with dots in them.  I've been looking around at the code to see how that might be done when subclassing Document and defining the field names, but I haven't gotten anything to work.

What do you recommend?

**Comment by HonzaKral** [comment]
Hi!

This is currently not supported with `Document`. You can use the underlying `Mapping` class to define the mapping as you can use strings there to refer to fields but for `Document` the fields need to be valid python identifiers. That means that dots won't work. Also attribute access won't work on the returned `Hit` and you will have to use item access (`hit['field.subfield']`) instead.

I am sorry I couldn't be of more help but this is definitely not a recommended way to structure documents in elasticsearch.
