### ISSUE TITLE
TypeError when trying to use HistogramFacet

### ISSUE THREAD

**Issue by cguardia** [elastic/elasticsearch-dsl-py#1025]
Hi, the faceted search works nicely. However, I think there is a bug with the HistogramFacet. If I pass in a numeric interval (as per the example in the docs), I get a TypeError here:

https://github.com/elastic/elasticsearch-dsl-py/blob/d744f7ec2c027ac1c9b0976a60552b7d8c9ce2e3/elasticsearch_dsl/faceted_search.py#L126

I think we could convert that to string, since we know it will be an int?

I can submit a PR if you think I'm correct. Thanks for all the work!

**Comment by HonzaKral** [comment]
Can you please share the code that leads to this error? It really shouldn't be a string and both values should be `int`s, if you specified `interval` as a string it could cause this.

Thank you!

**Comment by cguardia** [comment]
I specified it as an integer, but it turns out some other code was converting the filter value to string. Sorry about the noise.
