### ISSUE TITLE
Percolate query not working with join field

### ISSUE THREAD

**Issue by jaddison** [elastic/elasticsearch-dsl-py#1027]
I've hacked around this problem (see below), but I thought I would bring it up as an issue anyway:

- in one index, using a join field to establish a parent/child relationship between two `Documents` (as in the example in this repo)
- a separate index to store percolate queries (I'm percolating the child doc, specifically)
- I 'reuse' (ie. inherit from) the `ChildDoc` class to create `MyPercolateDoc` class (with its own `class Index` attribute set to put it in its own index)
- percolating a child document (not doc ID) against the percolate index with the percolate query causes an error on the search `.execute()`

```
{
  'reason': '[routing] is missing for join field [relation]', 
  'type': 'illegal_argument_exception'
}
```
**The hack:** If I pop the `relation` value out of my document before executing the query, it proceeds and functions correctly (ie. yields the expected percolated results).

**Comment by HonzaKral** [comment]
> percolating a child document (not doc ID) against the percolate index with the percolate query causes an error on the search .execute()

can you please share the code of how you are doing this? When I try I cannot even create a percolate query in the index because of the `join` field requiring a `routing` value on `save()`.

I believe that the cleanest solution would be to make sure the index with the percolators doesn't have the `join` field defined as it really doesn't belong there, especially since `percolator` only works on a per-document basis so cannot rely on p/c functionality anyways.

**Comment by jaddison** [comment]
Hmmm, my code's evolved past this point already. I'll see if I can conjure up something to demonstrate...

```
class BaseDoc(Document):
    id = field.Long()
    description = field.Text()
    relation = field.Join(relations={'parent': 'child'})

    class Index:
        name = 'my-index'

    @classmethod
    def _matches(cls, hit):
        return False


class ParentDoc(BaseDoc):
    info = field.Text()
    disable_map = field.Boolean()

    @classmethod
    def _matches(cls, hit):
        return hit['_source']['relation'] == 'parent'

    @classmethod
    def search(cls, **kwargs):
        return cls._index.search(**kwargs).filter('term', relation='parent')

    def save(self, **kwargs):
        self.relation = 'parent'
        return super(ParentDoc, self).save(**kwargs)


class ChildDoc(BaseDoc):
    code = field.Keyword()

    @classmethod
    def _matches(cls, hit):
        return hit['_source']['relation'] == 'child'

    @classmethod
    def search(cls, **kwargs):
        return cls._index.search(**kwargs).filter('term', relation='child')


class PercolatorDoc(ChildDoc):
    query = field.Percolator()

    class Index:
        name = 'perc-index'

    @classmethod
    def search(cls, **kwargs):
        # hacky way to avoid the parent class overrides of this method
        return Document.search.__func__(cls, **kwargs)

    @classmethod
    def _matches(cls, hit):
        # hacky way to avoid the parent class overrides of this method
        return Document._matches.__func__(cls, hit)
```

The only reason `PercolatorDoc` inherits from `ChildDoc` is that percolators need the document mapping matching any document data you want to percolate; when I 'save' a percolate query document via `PercolatorDoc`, the only field data being submitted is the `query` field.

I haven't verified that the above triggers the problem, but it roughly matches the document layout/relationship I've got.

**Comment by HonzaKral** [comment]
I am sorry but I have to close this ticket - `join` type is not supported in percolator queries and this is not supposed to work.
