### ISSUE TITLE
Automatically set "type": "nested" when requested in Document definition

### ISSUE THREAD

**Issue by vaidsu** [elastic/elasticsearch-dsl-py#1032]
Today, unless I am wrong, when I have  a definition like this:

```python
class Parent(Document):
    a = Text()
    child = Nested(Child)

class Child(InnerDoc):
    b = Text(type="raw")
```

I see the data is being pushed, but not sure if this is expected, but the "type": "nested" is not set in the mapping for child property in Parent. 

However, after I change the mapping and create the index myself, it works. 

1. Is that expected to avoid having "nested" types by default?
2. If that is the case, may we allow a change where we can specify something like this:

```python
class Parent(Document):
    a = Text()
    child = Nested(Child, type="nested")
```

Which automatically creates the "type": "nested" in the mapping? 

Or is it already available in the library? 

Please help.
Thanks in advance.

**Comment by HonzaKral** [comment]
This should not be needed and out tests verify that using `Nested` is just enough. Can you please share the code to reproduce this issue? You can verify what the mappings look like by doing `Parent._index.to_dict()`.
