### ISSUE TITLE
Convert bucket metric to facet

### ISSUE THREAD

**Issue by jaywhy13** [elastic/elasticsearch-dsl-py#1035]
This is a great library. Thanks! I came across the `FacetedSearch` class in an attempt to optimize a search query that got very long and started to look very quickly like faceting. I'm trying to do a `TermsFacet` that also uses `metric` to do some calculations.

An example from my very long query...
```
hits.aggs.bucket(
                'category_count',
                A('terms', field='category.name.raw')).\
                metric('stats', 'stats', field='amount')
```
Is this something that could be accomplished with the `NestedFacet` or would that need to be added?  The documentation for `NestedFacet` was pretty short and I couldn't clearly determine if this was right for what I needed. 

If this is something that needs to be implemented, I'm willing to take a shot at it!

**Comment by HonzaKral** [comment]
`NestedFaced` works on `nested` fields so it is not suitable for this use case, this would be a new feature that allows users to specify their own `metric` aggregation for their facets, it is a good idea and I will add it to the list. Thank you!
