### ISSUE TITLE
Completion Suggester questions (how to add weights + how to complete multi-word text)

### ISSUE THREAD

**Issue by K-Niu** [elastic/elasticsearch-dsl-py#1039]
I have a working version of the completion suggester for a suggesting names:

```
from elasticsearch_dsl import Document
from elasticsearch_dsl import Keyword, Completion

class Person(Document):
    person_id = Keyword()
    name = Keyword()
    name_suggestion = Completion()

    class Index:
        name = 'people'

Person.init()

Person(person_id='1', name='Bob Jones', name_suggestion='Bob Jones').save()
Person(person_id='2', name='Joe Smith', name_suggestion='Joe Smith').save()

person_search = Person.search()
query = 'Bo'
suggestions = person_search.suggest('name_suggestions', query, completion={'field': 'name_suggestion'}).execute()
```

Now, I would like to weight suggestions by a popularity metric. I have computed a popularity score for each person -- how would I incorporate this popularity weight into the resulting name suggestions?

---

My second question has to do with completing multi-word text. In the above, example Person 1's name consist of multiple word tokens: 'Bob' and 'Jones'. When completing queries, 'Bob Jones' will be suggested for 'Bo' but not 'Jone'. How do I configure the completion suggester to complete for both 'Bo' and 'Jone'?

**Comment by HonzaKral** [comment]
I added an example for `completion` suggester in 7f3271f6f3fcb9422db2289cef858112188bd24c, please let me know if it answers your questions or if there is anything else I should include.

Thank you for raising the issue!

**Comment by K-Niu** [comment]
Thank you, just tried this out and it works! Exactly what I was looking for
