### ISSUE TITLE
single match boost dsl not working

### ISSUE THREAD

**Issue by AlJohri** [elastic/elasticsearch-dsl-py#1040]
hi @HonzaKral, I'm running into the following issue:

#### does not work

```python
    query = (Q('match', headlines__basic=topic, boost=10) &
             Q('match', content_elements__content=topic, boost=1) &
             Q('match', taxonomy__keywords__keyword=topic, boost=1))
    print(query.to_dict())
```

resulting in:

```python
{'bool': {'must': [{'match': {'headlines.basic': 'trump', 'boost': 10}}, {'match': {'content_elements.content': 'trump', 'boost': 1}}, {'match': {'taxonomy.keywords.keyword': 'trump', 'boost': 1}}]}}
```

which gives this error:

>elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', "[match] query parsed in simplified form, with direct field name, but included more options than just the field name, possibly use its 'options' form, with 'query' element?")

--------------------------------------------------

#### works

```python
    query = (Q('match', headlines__basic={'query': topic, 'boost': 10}) &
             Q('match', content_elements__content={'query': topic, 'boost': 1}) &
             Q('match', taxonomy__keywords__keyword={'query': topic, 'boost': 1}))
    print(query.to_dict())
```

resulting in:

```python
{'bool': {'must': [{'match': {'headlines.basic': {'query': 'trump', 'boost': 10}}}, {'match': {'content_elements.content': {'query': 'trump', 'boost': 1}}}, {'match': {'taxonomy.keywords.keyword': {'query': 'trump', 'boost': 1}}}]}}
```

which yields the proper results

**Comment by HonzaKral** [comment]
Yes, this is correct and it is due to the first query structure is not supported by elasticsearch. This is not related to this library since it doesn't modify the structure of the queries you define.

**Comment by AlJohri** [comment]
@HonzaKral That makes sense, I didn't realize the error comes straight from elasticsearch. I must have misinterpreted this syntax:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html

>A boost parameter can be specified to give this term query a higher relevance score than another query, for instance:
>```
>          "term": {
>            "status": {
>              "value": "urgent",
>              "boost": 2.0 
>            }
>          }
>```
> The urgent query clause has a boost of 2.0, meaning it is twice as important as the query clause for normal.
