### ISSUE TITLE
custom hit class? (doc_class)

### ISSUE THREAD

**Issue by AlJohri** [elastic/elasticsearch-dsl-py#1041]
is there anyway to specify a custom hit class? I'm defining a function like:

```python
def search(query, limit=10):
    gen = (Search(using=client, index="myindex", doc_type='mydoc')
                .filter(base_filter)
                .query(query))[0:limit]
    logging.debug(f"querying: {json.dumps(gen.to_dict())}")
    return (Content(x) for x in gen)
```

the problem with this approach is that I can no longer access `gen.to_dict()` outside this function. I want to instead just return `gen` directly and have it automatically convert the response hits to my `Content` class.

the returned data structure from ES is fairly hairy and I want to normalize it in the wrapper class for ease of use. currently looks like this for example:

```python
@dataclass
class Content:
    id: str
    headline: str
    text: str
    publish_date: str

    def __init__(self, hit):
        self.id = hit.meta.id
        self.headline = hit['headlines']['basic']
        self.text = get_text(hit['content_elements'])
        self.publish_date = arrow.get(hit['publish_date']).date().isoformat()
    
    def __str__(self):
        return f'{self.publish_date} | {self.headline}'
    
    def to_dict(self):
        return self.__dict__
```

I considered just adding property descriptors right into the Hit class but that seemed less elegant.

any recommendations here? @HonzaKral

**Comment by AlJohri** [comment]
I'm not running into another issue with the hit class as I'm trying to serialize it into JSON and then deserialize. Naturally, I try to do `json.dumps(hit.to_dict())`. Unfortunately, now I've lost the metadata information (particularly, the `id` of the document). I think a custom Hit class would solve this issue again.

Preferably the `to_dict` method has an include_meta argument or some way to just regenerate the same format as the original input with `_source`.

**Comment by AlJohri** [comment]
nevermind, I missed to see the [response_class](https://elasticsearch-dsl.readthedocs.io/en/latest/api.html#elasticsearch_dsl.Search.response_class)

**Comment by AlJohri** [comment]
wow, this was much easier than I thought:

```python
class SimpleResponse(dict):

    def __init__(self, search, response):
        self.search = search
        self.response = response
        super().__init__(**response)
    
    def __iter__(self):
        yield from self['hits']['hits']

(Search(using=client, index="myindex", doc_type='mydoctype')
                .filter(base_filter)
                .query(query)
                .response_class(SimpleResponse))
```

**Comment by CarMoreno** [comment]
@AlJohri How could you get `total` hints (`self['hints]['total']`), if you are yielding just `self['hits']['hits']`?
