### ISSUE TITLE
https://elasticsearch-py.readthedocs.io/en/master/index.html

### ISSUE THREAD

**Issue by sbnajardhane** [elastic/elasticsearch-dsl-py#1042]
Hi @HonzaKral 
I am getting this error while connecting to elasticsearch nodes using es-dsl
```
options = {
        'sniff_on_start': True,
        'hosts': ['es_node'],
        'sniffer_timeout': 60,
        'sniff_on_connection_fail': True,
        'sniff_timeout': 10
}
connections.create_connection(**options)

```
and getting the below error 
I am running ubuntu 14.04 python version 2.7.6
```
/home/velocita/env/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:352: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/home/velocita/env/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:150: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
```

I am unbale to connect when "sniff_on_start": True, otherwise it is working fine. I guess sniff on start is a good option to know whether es is working or not. I have read about the solution [here](https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2 ). But not sure. (I have disabled the urllib3 warnings to avoid the above warnings)
Please suggest any solution or any other workaround.

**Comment by HonzaKral** [comment]
This is unfortunately an issue with your environment where your version of python does not support `ssl` adequately. The solution is to upgrade. If `sniff_on_start` doesn't work but then the client works there is something else going wrong and I would advise you to open an issue in the https://github.com/elastic/elasticsearch-py repository.

Sorry I couldn't be of more help
