### ISSUE TITLE
What query method could replace 'terms' for analyzing?

### ISSUE THREAD

**Issue by wangsiheaaaa** [elastic/elasticsearch-dsl-py#1045]
I have a should query with a list of strings like ['a', 'b', 'c', ..] and I want to use it to match my data. The "terms" method could give me very close result but it misses the case like 'A' or 'B'.

I know that the "match" does this work but it does not accept list. So i hope to know if there is a "matches" like method that solves this in one second or i should just add the "match"s one by one.

**Comment by wangsiheaaaa** [comment]
Find a solution which is a bit ugly:
`rawlist = ['a', 'b', 'c', ..]
querystr = ' OR '.join(['(%s)' % i for i in rawlist])
query('string_match', query=querystr)
`
The querystr is a string like '(a) OR (b) OR (c)', then using this to make a 'string_match' provides me good results. At least I don't need to manully add 'match' queries.

**Comment by jaddison** [comment]
> I have a should query with a list of strings like ['a', 'b', 'c', ..] and I want to use it to match my data. The "terms" method could give me very close result but it misses the case like 'A' or 'B'.

Unless I'm misunderstanding your problem, if you index/search your data using lowercase only, the above ought to work. You can create custom analyzers for your index to do this:
```
default_analyzer = analyzer(
    'default',
    tokenizer="standard",
    filter=["standard", "lowercase", "asciifolding", "stop", "snowball"],
    char_filter=["html_strip"])
```
Note the `lowercase` filter.

**Comment by wangsiheaaaa** [comment]
Great, but mapping the docs is not maintain by me so I can only work on query. The default analyzer is enough when using 'string_match' for my case.
