### ISSUE TITLE
query-time search as you type

### ISSUE THREAD

**Issue by candycrusher** [elastic/elasticsearch-dsl-py#1053]
I've found that there is some information in Elastic official documentation about query-time search as you type: [https://www.elastic.co/guide/en/elasticsearch/guide/current/_query_time_search_as_you_type.html](url)

Is this functionality also supported in elasticsearch-ds-pyl?

**Comment by HonzaKral** [comment]
Yes, it is, see the `completion.py` in examples - https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/completion.py

Hope this helps!

**Comment by candycrusher** [comment]
@HonzaKral I really appreciate your advice. You are always there and so helpful.
