### ISSUE TITLE
Saving documents to indices based on an index template

### ISSUE THREAD

**Issue by annawinkler** [elastic/elasticsearch-dsl-py#1057]
Hi there,

I created an index template based on the example I saw (`alias_migration.py`) and I'm confused about the next step. My Document object has mappings, and I used the `_index.as_template` method to create the template. I'd like the indices to have the form: `document-myID-YYYY-MM-DD`, and for the alias to be `document`. If I were to do this with a POST, I'd specify the index in the request, but I'm not sure how to do this with the DSL and I would appreciate feedback.

When I save documents into an index, I'm confused about when I specify the index as the full version (e.g., `document-myID-YYYY-MM-DD`) and when I use the alias. I'm thinking that I will need to check to see if the specific index for the day exists, create it if not, save the documents to that new index, and add an alias. Is that the recommended way to proceed with the DSL?

Thanks very much!
Anna

**Comment by HonzaKral** [comment]
There are two way to do this - the `alias_migration.py` example is set up to use the alias for writing so just calling `save()` on `BlogPost` will correctly write to the latest index.

If your alias points to multiple indices, you can instead do this in your `save()` method, for example if you are using time-based indices:
```python
def save(self, index=None, **kwargs):
    if index is None:
        index = self.timestamp.strftime('my-index-%Y-%m-%d')
    return super().save(index=index, **kwargs)
```

Hope this helps!
