### ISSUE TITLE
Slice Results After Scan

### ISSUE THREAD

**Issue by infosisio** [elastic/elasticsearch-dsl-py#1059]
Right now I do:

```
s = Search(using=es, index='index')
s = s[start_from:end_to].query("multi_match", query=query, operator="and", fields=['title', 'content'])
```

I would like to do exactly the same thing but with using scan in the Search. 

Trying to do that does not work, an error gets thrown:

`TypeError: 'generator' object is not subscriptable`

What is the workaround ? Thanks a lot in advance.

**Comment by HonzaKral** [comment]
I am wondering why would you be using `scan` if you only want a subset of the results?

If you'd apply pythonic slicing on the results of `scan()` then all the documents would be fetched from elasticsearch and then some thrown away which is not super efficient. If you still want to do this you can user `itertools.islice` or first create a `list` and then slice that as usual `list(s.scan())[start:end]`

Hope this helps!

**Comment by infosisio** [comment]
@HonzaKral The idea was to be able to request the very last page of results out of a very large data set without doing a deep request. from/end requests the entire thing in a way that ES can't handle if the limit is not maxed out.

**Comment by HonzaKral** [comment]
then `islice` is the way to go but you need to be aware of the overhead where you are actually requesting all the documents from elasticsearch and throwing a portion of them away.
