### ISSUE TITLE
Bug when calling Document.init() more than once

### ISSUE THREAD

**Issue by kobymeir** [elastic/elasticsearch-dsl-py#1060]
Using
```
elasticsearch==6.3.1
elasticsearch-dsl==6.2.1
```
Against an Elastic Search cluster: `6.3.2`

Using this Document to persist data:
```python
class Data(Document):
    some_field = Text()
    
    class Meta:
        doc_type = 'data_doc_type'
    
    class Index:
        name = 'data'
        doc_type = 'data_doc_type'
        settings = {
            "number_of_shards": 60,
            "number_of_replicas": 1
        }
```

When i call init `Data.init()` for the first time it actually works ok and creates the index and mapping correctly within ElasticSearch, but when i need to call it again to apply new mapping to that index i come accross this exception:
```text
File "data.py", line ***, in init
    Data.init()
  File "elasticsearch_dsl/document.py", line 128, in init
    i.save(using=using)
  File "elasticsearch_dsl/index.py", line 260, in save
    self.put_settings(using=using, body=settings)
  File "elasticsearch_dsl/index.py", line 430, in put_settings
    return self._get_connection(using).indices.put_settings(index=self._name, **kwargs)
  File "elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "elasticsearch/client/indices.py", line 547, in put_settings
    '_settings'), params=params, body=body)
  File "elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
```

And this is the actual reponse from elastic:
```json
{
    "error": {
        "root_cause": [
            {
                "type": "remote_transport_exception",
                "reason": "[1-*****][x.x.x.x:9300][indices:admin/settings/update]"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "Can't update non dynamic settings [[index.number_of_shards]] for open indices [[data/***]]"
    },
    "status": 400
}
```

The problem seems to be that you're trying to apply the settings more than once to settings that are not writable.

The problem is that in now i don't know how to just update the mapping on that index.

**Comment by HonzaKral** [comment]
`init` is creating the index, once an index has been created a lot of it's settings cannot be changed, that is a limitation of elasticsearch unfortunately.

That said, I wil have a look if the experience can be improved (as in if we can detect some changes are no-op and not ask elasticsearch to do them) but it will never be 100% supported by definition.

Typically, to evolve your mappings and index structure we recommend you just create a new index and move the data into it. There is an example of how this would look with elasticsearch-dsl in [0], including the use of aliases to make this change transparent.

btw I also noticed you are setting your `number_of_shards` to `60` which is suspicious for anything but the largest indices that are expected to store multiple terabytes of data and would typically not be recommended. It depends on the use case, cluster size, hardware, and many other parameters but typically we find the ideal shard utilization around lower tens of gigabytes per shard.

0 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/alias_migration.py

**Comment by kobymeir** [comment]
@HonzaKral thanks for the reply
1. The number of shards is just a mock number as of the rest of the example (and has nothing to do with my actual system)
2. Moving data around using `reindex` just when all i did was added some fields is pointless and time consuming especially when the indexes are fairly large, Also the process is very disruptive and error prone to production environments.
3. Your examples from the documentation [0] suggest to define the number of shards/replicas in the same manner that i showed in the example
4. Any other suggestion on how to update the mapping using the dsl?

0 - https://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#indextemplate

**Comment by HonzaKral** [comment]
I provided a hotfix in  a991fae, I will add some more tests around the functionality and, while this is not a guaranteed solution for all settings, for your use case this should now be fixed with the next release that should be coming soon.

**Comment by notfol** [comment]
Anything wrong with adding a class method something like below to update the mappings?

```
    @classmethod
    def update_mapping(cls, params=None):
        idx = cls.Index.name
        doc_type = cls._doc_type.name
        es = cls._get_connection()
        t = cls._index.as_template(idx).to_dict()
        return es.transport.perform_request(
            "PUT",
            _make_path(idx, '_mapping', doc_type),
            params=params,
            body=copy.deepcopy(t["mappings"][doc_type])
        )
```

**Comment by burritoIand** [comment]
@HonzaKral I just ran into this exact issue on latest when I mistakenly thought `Post.init()` was idempotent. Is this supposed to be fixed?

Is it safe to do this instead?
```
if not index := Index('posts').exists():
    Post.init()
```

I received error:
```
RequestError(400, 'illegal_argument_exception', "Can't update non dynamic settings [[index.number_of_shards]] for open indices [[posts-staging/sOmqF5m3RymtcVj2-2vflA]]")
```

```
elasticsearch==7.6.0
elasticsearch-dsl==7.1.0
```
