### ISSUE TITLE
Can't understand "word_delimeter" token filter

### ISSUE THREAD

**Issue by scherbakovx** [elastic/elasticsearch-dsl-py#1061]
elasticsearch-dsl==6.2.1
elasticsearch==6.3.1

I have analyzer:
```
test_analyzer = analyzer(
    'test_analyzer',
    tokenizer=tokenizer('trigram', 'edge_ngram', min_gram=3, max_gram=10),
    filter=['lowercase', 'word_delimiter']
)
```

This analyzer used in Document:
```
class TestIndex(Document):
    name = Text(analyzer=test_analyzer)
    id = Integer()

    class Index:
        name = 'test-index'
```

Objects in my Index have next pattern in name:

> word1:word2:word3:word4

 (there a lot of ":" in name)

As I understood ES docs, with this analyzer I can search my objects by sub-words (like `word2` from my example), but really search works only with almost-full-name in query.

My Search request is:
```
search = Search(
    index='test-index'
).query(
    "multi_match",
    query="word2",
    fields=['name'],
    fuzziness='AUTO'
)
```
(returns nothing)

**Comment by HonzaKral** [comment]
The problem is with your `tokenizer` which produces just edge ngrams of length 3-10 from the original input (`word1:word2:word3`), in your case:
```

**Comment by scherbakovx** [comment]
**1.** I created this analyzer with `simple_pattern_split`
<img width="378" alt="screenshot 2018-11-19 at 23 27 27" src="https://user-images.githubusercontent.com/9437117/48733235-0da29680-ec53-11e8-91f8-1bd298c144dc.png">

**2.** Then I insert object with ':'
<img width="365" alt="screenshot 2018-11-19 at 23 27 57" src="https://user-images.githubusercontent.com/9437117/48733265-2dd25580-ec53-11e8-8a8e-6190197ced25.png">

**3.** Try `_analyze` with my analyzer and, I suppose, it works.
<img width="373" alt="screenshot 2018-11-19 at 23 28 19" src="https://user-images.githubusercontent.com/9437117/48733293-46427000-ec53-11e8-97f2-99ab82dbcddb.png">

**4.** But when I try to search for object by its second part, I got nothing.
<img width="371" alt="screenshot 2018-11-19 at 23 28 40" src="https://user-images.githubusercontent.com/9437117/48733316-59edd680-ec53-11e8-8e2f-a755309fa001.png">

**5.** Maybe I am wrong with search part and it's impossible to combine `fuziness` with such analyzer?

**Comment by HonzaKral** [comment]
It is very much possible, in fact it is impossible to use `fuzziness` without an analyzer.

This works just fine for me:
```python
from elasticsearch_dsl import analyzer, tokenizer, connections, Document, Text

# connect
connections.create_connection()

test_analyzer = analyzer(
    'testing-1061',
    tokenizer=tokenizer('split_words', 'simple_pattern_split', pattern=':'),
    filter=['lowercase']
)

class D(Document):
    content = Text(analyzer=test_analyzer)
    class Index:
        name = 'test-1061'

# create the index
D.init()

D(content='word1:word2:word3').save(refresh=True)

assert 1 == D.search().query('match', content='word2').count()
assert 0 == D.search().query('match', content='wordX').count()
assert 1 == D.search().query('multi_match', query='wordX', fields=['content'], fuzziness=1).count()
```

Can you perhaps share your complete code? Are you creating your mappings and attaching the correct analyzer?

**Comment by scherbakovx** [comment]
Oh, after posting comment I've understood that I haven't created mapping. Now it works, at least in Postman, now I'll try to use this in Python. Thank you so much, you've saved me a day! <3

**Comment by scherbakovx** [comment]
Sorry for re-opening, but it still strange in Python...

I've fully copy-paste your code, except connection, I have `connections.create_connection(hosts=['localhost:32770'], timeout=20)` with ES (6.4.3) in Docker and the first test is failing... I've even deleted index with `DELETE localhost:32770/test-1061*`, after this I run Django and this is what I get in console `AssertionError` on `assert 1 == D.search().query('match', content='word2').count()`

**Comment by HonzaKral** [comment]
can you just `print` out the result instead of the `assert`? My guess would be that the code is accidentally run twice so the document is duplicated. Or just print out the hits instead of just a `count()`.

**Comment by scherbakovx** [comment]
You are right about duplicates, sorry :( Now everything is fine in Python too.
