### ISSUE TITLE
Unable to import UpdateByQuery from elasticsearch_dsl

### ISSUE THREAD

**Issue by OswinNathanial** [elastic/elasticsearch-dsl-py#1064]
Hi, I am unable to import UpdateByQuery while following the documentation at https://elasticsearch-dsl.readthedocs.io/en/latest/update_by_query.html

```
$ pip freeze | grep elastic
elasticsearch==6.3.1
elasticsearch-dsl==6.2.1

$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from elasticsearch_dsl import UpdateByQuery
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name UpdateByQuery
```
After checking the source in package of latest ver`6.2.1`, I understand that this module is not included.
If possible, could you please release a new version or let us know by when can we expect a new release?
Thank you.

**Comment by HonzaKral** [comment]
I am working on a release right now, hoping to get it all done by tomorrow.

Hope this helps!

**Comment by OswinNathanial** [comment]
@HonzaKral Thank you for your quick response. Its a big help. Waiting for the release.

**Comment by HonzaKral** [comment]
wait no more then - https://pypi.org/project/elasticsearch-dsl/ :)

**Comment by OswinNathanial** [comment]
Wow! That was real quick. Thanks a lot!

**Comment by OswinNathanial** [comment]
@HonzaKral You prefer if I create a new ticket for this?

**Comment by OswinNathanial** [comment]
Figured it out finally.
The cause is size of top_hits metric aggregation. Based on my testing, any size over 100, results in the `aggregations` missing and even the hits being empty, although `s.count()` gives the count of documents matching the query.
I could not find this max size of 100 for top_hits aggregation anywhere in the documents.
Probably, a relevant warning message, that may help in debugging the cause of such behavior, might be useful.
@HonzaKral How do you think?

**Comment by HonzaKral** [comment]
When I try this I get an exception saying:
`TransportError(400, 'search_phase_execution_exception', "Top hits result window is too large, the top hits aggregator [th]'s from + size must be less than or equal to: [100] but was [1000]. This limit can be set by changing the [index.max_inner_result_window] index level setting.")` 

Which is not ideal, but definitely informative.

Can you please paste the code that led to the error being ignored? That would definitely be a bug. If so please open another issue as it is unrelated to the original topic.

Thank you!
