### ISSUE TITLE
Please merge 6.3.0 into master

### ISSUE THREAD

**Issue by mozz100** [elastic/elasticsearch-dsl-py#1067]
Weird one... I came to read the changelog to see what's new in 6.3.0.  On `master`, that release is prominently labelled "dev".  But the tag called `6.3.0` is _ahead_ of `master` (somehow).

Please could you merge https://github.com/elastic/elasticsearch-dsl-py/commit/ed7f5e1b8840981cc6264920aca78394a94c7b1d into `master`?  There doesn't seem to be a corresponding branch at the moment...

**Comment by HonzaKral** [comment]
Just pushed, sorry about that.
