### ISSUE TITLE
One-to-Many Mapping without inheritance

### ISSUE THREAD

**Issue by Patralos** [elastic/elasticsearch-dsl-py#1070]
Hey,

i have two different objects:

class A(Document):
  name = Text()
  ...other data...
  
class B(Document):
    ...data...
   a = Join()

in the example, both A and B inherit from the same class, but is this mapping also possible without inheritance?

I cant used Nested, as the A:B ratio is 1:128 000, which is too much overhead.

**Comment by HonzaKral** [comment]
Absolutely, the inhertance is only in the example to make it simpler, you can simply have multiple `Document` classes and then use an `Index` object to create an index with their merged mappings:

```python
from elasticsearch_dsl import Document, Keyword, Index

class A(Document):
    a_field = Keyword()

class B(Document):
    b_field = Keyword()

i = Index('i')
i.document(A)
i.document(B)

# now you can see that the index includes both the mappings
i.to_dict()
```

The rest of the example (`_matches` classmethod etc) will remain the same.

Hope this helps!
