### ISSUE TITLE
How to call methods on Nested InnerDoc objects?

### ISSUE THREAD

**Issue by annawinkler** [elastic/elasticsearch-dsl-py#1075]
I have a Document class with Nested objects, and I'd like to call validation methods on those Nested objects. What's the best way to do that? Here is a simple example that shows what I am trying to do:

```
class AddressParts(InnerDoc):
  house_number = Integer(required=True)
  street_name = Keyword(required=True)
  city_name = Keyword(required=True)

  def validate(self):
    if house_number < 0:
	  raise RuntimeError('Ooops this isn't a valid house number!')

class AddressData(InnerDoc):
  address = Nested(AddressParts, required=True)
  def validate(self):
    address.validate()

class House(Document):
  address_data = Nested(AddressData, required=True)

  def validate(self):
    address_data.validate()
```

Because the fields are dicts, I then tried converting them to their objects like this:
```
  def validate(self):
    AddressData(address_data.to_dict()).validate()
```
I get an error though `AttributeError: 'list' object has no attribute 'to_dict'` ... so I'm curious what the best approach is for what I'm trying to do?

Thanks!
Anna

**Comment by HonzaKral** [comment]
`address` is a list of nested objects, so you should be doing:

```python
for a in self.address:
    a.validate()
```

Then it should work just fine, can you please verify? Thank you!

**Comment by annawinkler** [comment]
When I try that, I get the error: `AttributeError: 'str' object has no attribute 'validate'`

**Comment by annawinkler** [comment]
Yes - I'll need to put together an example to share. I'll post that when I have it ready. Thanks!

**Comment by annawinkler** [comment]
I've come down with a cold so my progress is slower on this ... sorry 😬 🤧

**Comment by annawinkler** [comment]
@HonzaKral I created this example (https://github.com/annawinkler/es_address_book) that shows the error. If you run `python ./driver.py` you'll see the error. I added in commented out lines the version that does work.

```
python ./driver.py                                                                                                                                                                                                                                                                [9:34:56]
Validating my house...
Traceback (most recent call last):
  File "/Users/awinkler/virtualenvs/es_address_book/lib/python3.7/site-packages/elasticsearch_dsl/utils.py", line 127, in __getattr__
    return self.__getitem__(attr_name)
  File "/Users/awinkler/virtualenvs/es_address_book/lib/python3.7/site-packages/elasticsearch_dsl/utils.py", line 140, in __getitem__
    return _wrap(self._d_[key])
KeyError: 'validate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./driver.py", line 13, in <module>
    main()
  File "./driver.py", line 11, in main
    my_house.validate()
  File "/Users/awinkler/dev/es_address_book/models.py", line 33, in validate
    self.address.validate()
  File "/Users/awinkler/virtualenvs/es_address_book/lib/python3.7/site-packages/elasticsearch_dsl/utils.py", line 130, in __getattr__
    '%r object has no attribute %r' % (self.__class__.__name__, attr_name))
AttributeError: 'AttrDict' object has no attribute 'validate'
(es_address_book)
```

What are your thoughts?

**Comment by HonzaKral** [comment]
I created a PR in your repo which shows the API how it works in https://github.com/annawinkler/es_address_book/pull/1

Also note that `Nested` is meant to be used only when a `list` of objects is expected, if you expect to only have one `address` use `Object` instead and then you can skip the list in the example (just `House(address=AddressData(...))`)

I also implemented a `clean` method which is a built-in (undocumented, my bad!) hook for users to add their own validation logic like you have done.

Hope this helps!

**Comment by annawinkler** [comment]
@HonzaKral I'm happy to contribute to the docs then :)
