### ISSUE TITLE
Error on persist document: type object 'Document' has no attribute '_index'

### ISSUE THREAD

**Issue by Sphinxs** [elastic/elasticsearch-dsl-py#1077]
I have try to persist a document in an index by `Document().save(index=index_name, doc_type=doc_type_name, body=body)` and I had received this message: `type object 'Document' has no attribute '_index'`, but I don't use the `__repr__` like it's said [here](https://github.com/elastic/elasticsearch-dsl-py/issues/431)...

**Comment by HonzaKral** [comment]
I am sorry, but this is not supported API, the `Document` class is supposed to be subclassed to define your own class which can then use the `.save()` method:

```python
class MyDoc(Document):
    class Index:
        name = index_name

d = MyDoc(**body)
d.save()
```

Hope this helps!
