### ISSUE TITLE
Aggregate order not formatting correctly

### ISSUE THREAD

**Issue by sgerlach** [elastic/elasticsearch-dsl-py#108]
Pardon my ignorance if this is intended but when adding an order to an agg bucket the resulting query does not encapsulate the order statement correctly and end up in a parse error

s = Search(using=client, index="myindex")\
   .query("match", message="stuff")
s.aggs.bucket('myagg', 'terms', field='somefield', size=0, order='hitcount')
s.aggs['myagg'].metric('hitcount', 'sum' field='some_int_field')

print(s.to_dict())
{
	"query": {
		"bool": {
			"must": [
				{"match": {
					"message": "stuff"}
				}				
			]
		}
	},
	"aggs": {
		"myagg": {
			"terms": {
				"field": "somfield",
				"order": "hitcount",  <----
				"size": 0
			},
			 "aggs": {
			 	"hitcount": {
			 		"sum": {
			 			"field": "some_int_field"
			 		}
			 	}
			 }
		}
	}
}

and seems like it should be
{
	"query": {
		"bool": {
			"must": [
				{"match": {
					"message": "stuff"}
				}				
			]
		}
	},
	"aggs": {
		"myagg": {
			"terms": {
				"field": "somfield",
				"order": { "hitcount": "desc" }    <--------
				"size": 0
			},
			 "aggs": {
			 	"hitcount": {
			 		"sum": {
			 			"field": "some_int_field"
			 		}
			 	}
			 }
		}
	}
}

Again apologies if I read or am doing something wrong :)

**Comment by HonzaKral** [comment]
Hi, the DSL matches the json structure very closely, so in this case you should do:

    s = Search(using=client, index="myindex")\
        .query("match", message="stuff")
    s.aggs.bucket('myagg', 'terms', field='somefield', size=0, order={'hitcount': 'desc'})
    s.aggs['myagg'].metric('hitcount', 'sum' field='some_int_field')

It is possible that we might implement a shortcut for this later allowing for just specifying the order field, but for now just stick to the json dsl and you should be good to go.

**Comment by sgerlach** [comment]
Great! That one was a little tricky! Thanks Honza

**Comment by HonzaKral** [comment]
closing this question since it has been answered.

**Comment by EricMWalton** [comment]
I personally would like to see a syntax similar to that for sorting the query results.  If you can do:

```
s = Search().sort('category')
```

You should be able to do:

```
s.aggs.bucket('tags_per_category', 'terms', field='tags').sort('_count')
```

To be consistent with the other aggs methods, I'd expect  ```sort()``` to modify the bucket object in place and return the bucket.

**Comment by Greyvend** [comment]
Are there any updates on this syntax? I've found myself trying to do exactly what @EricMWalton described, so I guess it's really intuitive and probably should be implemented.
