### ISSUE TITLE
How to just get json of a single doc? to_dict() does not format Datetime to string format

### ISSUE THREAD

**Issue by kavink** [elastic/elasticsearch-dsl-py#1081]
I am having issue where when I use do_dict() to convert 1 document to a dict/json , the Datetime field in dictionary is Datetime object instead of String formatted. How can I get the doc just as its in ES  ? 

Is it possible to provide format string , so when I do `to_dict()` I get a string ? I basically just want the isoformat back.

**Comment by HonzaKral** [comment]
`.to_dict()` is what we send to `elasticsearch-py`, just serialize that with the `serializer` shipped with `elasticsearch-dsl` to see the actual json string if needed:

```python
from elasticsearch_dsl.serializer import serializer
serializer.dumps(doc.to_dict())
```

Hope this helps!
