### ISSUE TITLE
looking for advice on Tokenizer for Chinese character 

### ISSUE THREAD

**Issue by candycrusher** [elastic/elasticsearch-dsl-py#1083]
I am aware that this question is about the specific area. In fact, the Chinese tokenization process has made lots of developer of application in Chinese feel frustrated. Certainly, there is some solution like Jieba and ik-smart can make the life a little easier. However, there is still some scenario related to Chinese language that may need the work and advice from Elastic community. Is there some good alternative solution or some tentative plan from which Chinese language application developer can learn? 

You know, for search. ES is a masterpiece.

**Comment by candycrusher** [comment]
Does  token_filter('ascii_fold', 'asciifolding') support Chinese? I think Chinese is a non-ascii language.

**Comment by HonzaKral** [comment]
I am sorry but I don't have much experience with Chinese characters either. From my research it looks like you might want to look into two analysis plugins - ICU (0) and Smart Chinese (1).

Ince you have them installed in elasticsearch you can use them from the dsl by using their name, for example you can try:

```python
from elasticsearch_dsl import connections, analyzer
connections.create_connection()
tokens = my_analyzer = analyzer('testing_simplecn', tokenizer='simplecn').simultae('你好')
for t in tokens.tokens:
    print(t)
```

Hope this helps!

0 - https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu.html
1 - https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-smartcn.html

**Comment by candycrusher** [comment]
That really broaden my perspective on Chinese search! 👍 Really appreciate the effort made by all community. Really wish I can make some output to Elastic World very soon. I am making the preparation for this brilliant journey.  👍
