### ISSUE TITLE
Hit objects are not pickleable

### ISSUE THREAD

**Issue by eli314** [elastic/elasticsearch-dsl-py#1084]
`Hit` obejcts are not properly serialized when using `pickle` because the `meta` member is not available after loading the object using `pickle.load`. This happens because of the [way ](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/response/hit.py#L13) the `meta` member of the `Hit` class is added in the `__init__` method. Anyways, I have fixed it by adding `__getstate__` and `__setstate__` methods to `Hit` that make sure we don't lose the metadata. I have the fix on a local fork and would like to open a PR :)

**Comment by HonzaKral** [comment]
Thank you for the report, a PR wold be most welcome @eli314 !
