### ISSUE TITLE
README.rst info about aggregations

### ISSUE THREAD

**Issue by sgerlach** [elastic/elasticsearch-dsl-py#109]
The example about accessing aggregations looks to be incorrect in the README

```
for tag in response['aggregations']['per_tag']['buckets']:
    print(tag['key'], tag['max_lines']['value'])
```

should be 
```
for tag in response.aggregations['per_tag']['buckets']:
    print(tag['key'], tag['max_lines']['value'])
```

**Comment by HonzaKral** [comment]
This example in the README shows how this would be done without the dsl library. There an attribute access won't work. The same example, with the use of this library can be found in the next section:

    for tag in response.aggregations.per_tag.buckets:
        print(tag.key, tag.max_lines.value)

**Comment by sgerlach** [comment]
Well... now I feel silly. Thanks :)
