### ISSUE TITLE
InnerDoc does not add "type" : "nested" in document mapping #2

### ISSUE THREAD

**Issue by scherbakovx** [elastic/elasticsearch-dsl-py#1092]
Same problem as in [https://github.com/elastic/elasticsearch-dsl-py/issues/1080](1080) but I really can't understand solution...

```
class TestNested(InnerDoc):
    name = Text(analyzer=standart_analyzer)

class TestIndex(Document):

    nesteds = Nested(TestNested)

    def add_synonym(self, name):
        self.nesteds.append(TestNested(name=name))

    class Index:
        name = 'test-index'
```

I have such index setup and I start to use it with these lines of code:
```
TestIndex.init()
index_template = TestIndex._index.as_template('base')
index_template.save()
```

But when I watch mapping, I still got `"type": "text"` (instead of `"type": "nested"`) for name-field in TestNested. What can be wrong..? It also worked previously, but in one moment broke :(

**Comment by HonzaKral** [comment]
but name is text in your mapping, just the nesteds field in your definition should be type nested. Can you please supply the whole mapping as it is stored in elasticsearch? Thanks!

**Comment by HonzaKral** [comment]
closing since there is no additional information
