### ISSUE TITLE
Search.aggs doesn't allow .pipeline()

### ISSUE THREAD

**Issue by RafaelFMori** [elastic/elasticsearch-dsl-py#1097]
Hello, I'm trying to write this piece of my query on dsl-py

``` "aggs": {
           "product_bucket_sort": {
             "bucket_sort": {
               "sort": [
                 {
                   "seller_qtt": {
                     "order": "desc"
                   }
                 }
               ]
             }
           },
           "seller_qtt": {
             "cardinality": {
               "field": "seller_code"
             }
           },
           "max_score": {
             "max": {
               "script": "_score"
             }
           }
         }
```

I've tried to build it like that:

`q.aggs.metric("product_bucket_sort","bucket_sort",sort=[{"seller_qtt": {"order": "desc"}}], product_bucket_sort={"cardinality": {"field": "seller_code"}},size=10000)`

returning:

```'aggs': {
        'produtos_bucket_sort': {
          'bucket_sort': {
            'sort': [
              {
                'quantidade_de_vendedores': {
                  'order': 'desc'
                }
              }
            ],
            'produtos_bucket_sort': {
              'cardinality': {
                'field': 'vendedor_codigo'
              }
            },
            'size': 10000
          }
        }
      }
```

the problem is that this will set the cardinality option inside the bucket_sort and I need it outside.

Can anyone help me? I cannot seem to find a way to do it

**Comment by RafaelFMori** [comment]
Thanks but I've tried it as well, but I get an attribute error:

AttributeError: 'Search' object has no attribute 'pipeline'

to clarify the example of what I'm doing:

`from elasticsearch-dsl import Search
s = Search()
s.aggs.metric('seller_qtt', 'cardinality', field='seller_code').pipeline('product_bucket_sort', 'bucket_sort', sort=[{'seller_qtt': 'desc'}])`

**Comment by HonzaKral** [comment]
My bad, sorry about that!

You need to define the `cardinality` and `bucket_sort` aggregation *inside* a `bucket` aggregation, like:

```
s = Search()
s.aggs.bucket('tags', 'terms', field='category')\
    .metric('seller_qtt', 'cardinality', field='seller_code')\
    .pipeline('product_bucket_sort', 'bucket_sort', sort=[{'seller_qtt': 'desc'}])
```

You cannot have a `bucket_sort` as a top-level aggregation.

That said there is still a bug where there are some pipeline aggregations that can be as top level and we currently don't allow that, I will reopen the issue to track it
