### ISSUE TITLE
Search object (using Document) searching all indices, not using index pattern

### ISSUE THREAD

**Issue by TeodorIvanov** [elastic/elasticsearch-dsl-py#1106]
I have this Document class:

```python
class Item(Document):
    class Index:
        name = 'items_*'
   created_on = Date()
   source_id = Keyword()

```
Note: I am using latest elasticsearch-py and elasticsearch-dsl versions (6.3.1).

When executing the following query:
```json
query = {
    "aggs": {
        "max_created_on_by_source": {
            "terms": {
                "field": "source_id",
                "size": 1000000
            },
            "aggs": {
                "max_created_on": {
                    "max": {
                        "field": "created_on"
                    }
                },
                "max_created_on_filter": {
                    "bucket_selector": {
                        "buckets_path": {
                            "max_created_on": "max_created_on"
                        },
                        "script": "params.max_created_on < 1541030400000L"
                    }
                }
            }
        }
    }
}
```
the query does not raise any errors when executed in Kibana over the `items_*` index pattern.
But it raises a 503 TransportError when executed with python using the elasticsearch_dsl:
```python
search = Item.search()
response = search.from_dict(query).execute()
```
stating that:
```Merging/Reducing the aggregations failed when computing the aggregation [max_created_on_by_source] because the field you gave in the aggregation query existed as two different types in two different indices```.

All of the indices in the `items_*` index pattern have the same mapping for the `created_on` field.

I've debugged this for a while and found out the inherited [Request class'](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L98)  `__init__` method is executed twice.
The two calls being [1](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/document.py#L159) and [2](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L363).
The second time around [called the __init__ method](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L305) with no `_index` argument in my case,
thus searching all indices in the cluster and not only the `items_*` index pattern.

Is this an error on my end (should I pass some kwarg when initializing the Search instance) or is this some unwanted behaviour?

**Comment by TeodorIvanov** [comment]
The above behavior is equivalent to:
```python
>>> from elasticsearch_dsl import connections                                                                                                                                                                    
>>> con = connections.get_connection()                                                                                                                                                                           
>>> con
<Elasticsearch([{'host': '**.**.**.**'}])>
>>> res = es.search(body=query)
*** elasticsearch.exceptions.TransportError: TransportError(503, 'search_phase_execution_exception')
>>> res = es.search(body=query, index='items_*')
>>> 
```
I would expect that the Document index name would be passed by default when using DSL Document classes.

**Comment by HonzaKral** [comment]
The problem is that `from_dict` is a classmethod that constructs a new `Search` object that doesn't share anything with the original object. If you want to modify the current object you should be using the `update_from_dict` method instead.

Hope this helps!

**Comment by TeodorIvanov** [comment]
Thank you @HonzaKral. I will try it out.
