### ISSUE TITLE
inner_hits are getting overwritten

### ISSUE THREAD

**Issue by doctorBeast** [elastic/elasticsearch-dsl-py#1110]
**INPUT QUERY**
`GET index/_search`
```
{
  "query": {
    "bool": {
      "should": [
        {
          "bool": {
            "must": [
              {
                "match": {
                  "field1": <value>
                }
              },
              {
                "has_child": {
                  "type": "child_type",
                  "query": {
                    "match": {
                      "field2": <value>
                    }
                  },
                  "inner_hits": {}
                }
              }
            ]
          }
        },
        {
          "bool": {
            "must": [
              {
                "match": {
                  "field1": <value>
                }
              },
              {
                "has_child": {
                  "type": "child_type",
                  "query": {
                    "match": {
                      "field2": <value>
                    }
                  },
                  "inner_hits": {}
                }
              }
            ]
          }
        }
      ]
    }
  }
```

**OUTPUT**
```
[
 {
 <second_parent_data>,
  "inner_hits":{
                     <child_data_is_given>
                     }
 },
 {
  <first_parent_data>
  "inner_hits":{
                     <no_child_data_is_given> 
                     } 
  }
]

```

In the above query, I don't know why but I am getting data according to any one of the inner_hits. If I use only one has_child query with inner_hits, I am getting the data of the child objects but if I use another has_child query with inner_hits I am getting data of the other documents child in the respective documents inner_hits and no child data in the inner_hits of the document for which I made the first has_child query.  May be they are getting overwritten or what. 

Could any one help me with why this is happening and what could I do to get the inner_hits for both of the has_child queries in their respective documents.

Thanks

**Comment by HonzaKral** [comment]
If you have multiple `inner_hits` clauses than you need to define the `name` option to be able to address them, see https://www.elastic.co/guide/en/elasticsearch/reference/6.5/search-request-inner-hits.html#_options for details

Also this is a repository for the python elasticsearch dsl library so I am going to close this issue as it is unrelated, please ask generic elasticsearch questions at discuss.elastic.co

Hope this helps!
