### ISSUE TITLE
How to use the "typed keys" parameter using MultiSearch?

### ISSUE THREAD

**Issue by mrxkollo** [elastic/elasticsearch-dsl-py#1118]
How does one use "typed_keys" parameter along with MultiSearch for adding aggregation types to the bucket names as explained [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/returning-aggregation-type.html)?

When using a normal search, it works like this (these are just cutouts from my code):
```python
search = elasticsearch_dsl.Search.from_dict(query_body).index(index).using(elasticsearch).params(typed_keys=True, size=0)
```
However, the same does not apply when using MultiSearch, this does not return the aggregation types and doesn't limit the hits being returned (only interested in aggregations):
```python
ms = MultiSearch()
search = elasticsearch_dsl.Search.from_dict(query_body).index(index).using(elasticsearch).params(typed_keys=True, size=0)
ms = ms.add(search)
ms.execute()
```
From what I've read from another issue, adding the size parameter with .extra works, but the same does not apply for "typed_keys" because it runs into a validation error on .execute().

Since "typed_keys" doesn't work with params and extra for MultiSearch, am I just missing something important or is it some kind of oversight?

**Comment by HonzaKral** [comment]
You can specify any parameters on a search object with the `.params` method as you are doing. When I try it it works very well for me. Can you please attach the error message you are getting back?

Thank you

**Comment by mrxkollo** [comment]
Made together a quick example of the issue in a Jupyter notebook.
Single Search with .params works well but the moment you add it to MultiSearch it doesn't change anything. Wanted to try it with .extra too just to be sure I am not misunderstanding anything.


```python
from elasticsearch import Elasticsearch
from elasticsearch_dsl import MultiSearch, Search
```


```python

```


```python
e = Elasticsearch('192.168.99.100:9200')
```


```python

```


```python
# Using a normal Search with params.
s = Search().using(e).index("bank").params(typed_keys=True)
```


```python
s.aggs.bucket("sampleAgg", "terms", field="employer.keyword")
```




    Terms(field='employer.keyword')




```python
r = s.execute()
```


```python
r.aggs
```




    {'sterms#sampleAgg': {'doc_count_error_upper_bound': 5, 'sum...}




```python

```


```python
# Using the working Search example in MultiSearch.
ms_with_params = MultiSearch().using(e)
```


```python
ms_with_params = ms_with_params.add(s)
```


```python
r = ms_with_params.execute()
```


```python
r[0].aggs
```




    {'sampleAgg': {'doc_count_error_upper_bound': 5, 'sum_other_...}




```python

```


```python
# Trying it out with extra.
s = Search().extra(typed_keys=True)
```


```python
ms = MultiSearch().using(e).index("bank")
```


```python
ms = ms.add(s)
```


```python
ms.execute()
```

    GET http://192.168.99.100:9200/bank/_msearch [status:400 request:0.003s]
    


    ---------------------------------------------------------------------------

    RequestError                              Traceback (most recent call last)

    <ipython-input-14-a0b6380c1d7f> in <module>
    ----> 1 ms.execute()
    

    ~\AppData\Roaming\Python\Python37\site-packages\elasticsearch_dsl\search.py in execute(self, ignore_cache, raise_on_error)
        803                 doc_type=self._get_doc_type(),
        804                 body=self.to_dict(),
    --> 805                 **self._params
        806             )
        807 
    

    ~\AppData\Roaming\Python\Python37\site-packages\elasticsearch\client\utils.py in _wrapped(*args, **kwargs)
         74                 if p in kwargs:
         75                     params[p] = kwargs.pop(p)
    ---> 76             return func(*args, params=params, **kwargs)
         77         return _wrapped
         78     return _wrapper
    

    ~\AppData\Roaming\Python\Python37\site-packages\elasticsearch\client\__init__.py in msearch(self, body, index, doc_type, params)
       1186         return self.transport.perform_request('GET', _make_path(index,
       1187             doc_type, '_msearch'), params=params, body=self._bulk_body(body),
    -> 1188             headers={'content-type': 'application/x-ndjson'})
       1189 
       1190     @query_params('field_statistics', 'fields', 'offsets', 'parent', 'payloads',
    

    ~\AppData\Roaming\Python\Python37\site-packages\elasticsearch\transport.py in perform_request(self, method, url, headers, params, body)
        316                 delay = 2**attempt - 1
        317                 time.sleep(delay)
    --> 318                 status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
        319 
        320             except TransportError as e:
    

    ~\AppData\Roaming\Python\Python37\site-packages\elasticsearch\connection\http_urllib3.py in perform_request(self, method, url, params, body, timeout, ignore, headers)
        184         if not (200 <= response.status < 300) and response.status not in ignore:
        185             self.log_request_fail(method, full_url, url, body, duration, response.status, raw_data)
    --> 186             self._raise_error(response.status, raw_data)
        187 
        188         self.log_request_success(method, full_url, url, body, response.status,
    

    ~\AppData\Roaming\Python\Python37\site-packages\elasticsearch\connection\base.py in _raise_error(self, status_code, raw_data)
        123             logger.warning('Undecodable raw error response from server: %s', err)
        124 
    --> 125         raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
        126 
        127 
    

    RequestError: RequestError(400, 'parsing_exception', 'Unknown key for a VALUE_BOOLEAN in [typed_keys].')

**Comment by HonzaKral** [comment]
I see, that is my bad - `msearch` actually doesn't support setting `typed_keys` for individual search requests but it needs to be set globally for the whole `MultiSearch`:
```python
ms_with_params = ms_with_params.params(typed_keys=True)
```

This is an issue in elasticsearch itself, not the library since we are sending the parameter as part of the msearch body as expected.

Note however, that this means that the dsl won't be able to properly deserialize the response since the returned data won't match the aggregations' definitions so it is not recommended.

Hope this helps, sorry about the confusion!
