### ISSUE TITLE
Iteration on Bucket Filters Aggregations Return String

### ISSUE THREAD

**Issue by NurFaizin** [elastic/elasticsearch-dsl-py#1119]
I have an issue on iterating on response buckets of filters aggregations:

```python
sentiment_filters = {
    'positive': Q('term', sentiment='positive'),
    'negative': Q('term', sentiment='negative'),
    'neutral': Q('term', sentiment='neutral')
}

search.aggs.bucket('sum_sentiments', 'filters', filters=sentiment_filters)
```

When I am trying to iterate on this buckets:

```python
response = search.execute()
for sentiment in response.aggs.sum_sentiments.buckets:
    print(sentiment)
    print(type(sentiment))
```
its just returns strings:

```python
negative
<class 'str'>
neutral
<class 'str'>
positive
<class 'str'>
```

**Comment by HonzaKral** [comment]
When you are using named filter in filters aggregations, the response is indeed a `dict`, not a `list` so iterating over it gives you the keys. This is as designed where it mimics the behavior of elasticsearch itself

**Comment by HonzaKral** [comment]
to access the individual buckets, use their names, for example: `response.aggs.dum_sentiments.buckets.negative`
