### ISSUE TITLE
doctype, a field not being indexed

### ISSUE THREAD

**Issue by brizzbane** [elastic/elasticsearch-dsl-py#112]
For some reason there is a field that is not being indexed.  I thought that it may be an issue w/elasticsearch and the type of the field..  but it is indexing other fields of the same type (boolean).

Here is the mapping from KOPF:

https://gist.github.com/brizzbane/276c7a54fe8e82cc516d

I have added ******missing next to the field that is not indexed.

Is this possibly an issue with DocType?

**Comment by HonzaKral** [comment]
Thank you for trying out the library, unfortunately I don't understand what seems to be an issue - what value or field isn't being indexed? Thanks!

**Comment by brizzbane** [comment]
line 89,90,91 is value that is in a json response that I am indexing,  but for some reason it's not indexed.  everything else is.

so:
"isNew":{
  "type":"boolean"
}
doesn't exist in the indexed document, even though its part of the json response.  I've not had issues w/anything not being indexed up until this point.  I've worked w/your module quite a bit over the past couple of weeks.

another example if you aren't following what I'm saying.  I index this:

		"messages": [{
			"body": "Hi, how are you?",
			"preview": "Hi, how are you? ",
			"senderId": 75712821,
			"timestamp": 1427577558.035,
			"receivedAt": 1427577558.054,
			"headerId": "7c320dc0-7ed5-4281-9a46-dd020f9bb94f",
			"type": "text",
			"isNew": true
		}],

everything is indexed except for "isNew": true.

is it possible maybe 'isNew' is part of the module?  Also, if it helps, I'm not creating a mapping before hand.  I let elasticsearch determine when it indexes the document.

**Comment by HonzaKral** [comment]
Can you post an example of how you index it and how you find it's actually missing? I must be missing something. Thanks

**Comment by brizzbane** [comment]
yep!.  https://gist.github.com/brizzbane/bdd6245c90a5df65d40f

line 14's value is the messages example in my previous post.  thanks for looking into it..

**Comment by brizzbane** [comment]
Check this out, I just set up a minimalist test:

https://gist.github.com/brizzbane/e77323190792d5510041

I'm wondering if maybe it's an issue w/Python's boolean 'type' is capitalized, and the json response is lower cased?

When I save with capitalized, the above example works.  I just wonder why I wouldn't have seen any exception errors anywhere.

**Comment by HonzaKral** [comment]
I am able to run your minimalist test just fine - the only problem there is that you have 'messages' listed there twice - once in the name of the field and second time inside the dict you are assigning. However I end up with this document in Elasticsearch after running it:

    {
        "_id": "AUxm-Jmvdk7yYP5WD3cq",
        "_index": "test",
        "_score": 1.0,
        "_source": {
            "messages": {
                "messages": [
                    {
                        "body": "Hi, how are you?",
                        "headerId": "7c320dc0-7ed5-4281-9a46-dd020f9bb94f",
                        "isNew": true,
                        "preview": "Hi, how are you? ",
                        "receivedAt": 1427577558.054,
                        "senderId": 75712821,
                        "timestamp": 1427577558.035,
                        "type": "text"
                    }
                ]
            }
        },
        "_type": "test"
    }

and can correctly access the `isNew` field:

    test_save.messages.messages[0].isNew

**Comment by brizzbane** [comment]
Ok.  I'm not sure what the issue was :\.  Sorry for time you spent looking over.

awesome module btw.  really changing the way I work with a lot of different things.
