### ISSUE TITLE
got an unexpected keyword argument 'data_only

### ISSUE THREAD

**Issue by littlehome-eugene** [elastic/elasticsearch-dsl-py#1122]
https://github.com/elastic/elasticsearch-dsl-py/issues/936 
I'm copying the question here, because the issue is closed and not sure if it will be noticed..

elasticsearch==6.3.1
elasticsearch-dsl==6.3.1

```
 class ReviewMeta(InnerDoc):

     id = Integer()
     name = Keyword()
     tags = Keyword()
     location = GeoPoint()
     area_names = Keyword()


 class ReviewMetaSearchClickLogDoc(DocType):

     id = Integer()
     created_at = Date()
     search_log_id = Integer()
     review_meta = Object(ReviewMeta)
     position = Integer()

     class Index:
         name = REVIEWMETA_SEARCH_CLICK_LOG_INDEX


 class ReviewMetaSearchLogDoc(DocType):

     id = Integer()
     created_at = Date()
     user = Object(User)
     result_count = Integer()
     search_data = Object(dynamic=True)
     clicks = Nested(ReviewMetaSearchClickLogDoc, include_in_parent=True)

     class Index:
         name = REVIEWMETA_SEARCH_LOG_INDEX
```
I guess the problem is `Nested(ReviewMetaSearchClickLogDoc, include_in_parent=True)` , why is it a problametic, and how can I fix it?

**Comment by HonzaKral** [comment]
`ReviewMetaSearchClickLogDoc` should be extending `InnerDoc` instead of `DocType` since it is not a standalone document, just used in `Nested` field. Same like `ReviewMeta`.

Hope this helps!
