### ISSUE TITLE
Retrieve single document

### ISSUE THREAD

**Issue by vruchtvet** [elastic/elasticsearch-dsl-py#1133]
Hi,

I'm trying to read a single document from an elasticsearch index. I'am using elasticsearch-dsl 6.1.0 and django 2.1.7, python 3.6.7

```
def detail(request):
    client = Elasticsearch()
    q = request.GET.get('q')
    s=DocType.get(q, using=client, index="theses")
    result = s.execute()
    context = {
        'result': result,
        'section': 'detail'
    }
    return render(request, 'search/detail.html', context)
```

This give ma an error: 
`NotFoundError(404, '{"_index":"theses","_type":"doc","_id":"c7IUNGkBsscSf7uNEV4l","found":false}')`

Apparently, I must give it a type to search (in my case 'these'). But how?

Regards,
Hans Scholte

**Comment by HonzaKral** [comment]
`DocType` is just an abstract class that is meant to be extended to provide your own functionality (just like Django's `Model`), then in that definition you can provide the document type and other attributes like the mapping. see [0] for details.

Also not that you should not be creating a connection to elasticsearch inside your views as you want to have a persistent connections that will survive between requests, you can see in [1] some of the recommended approaches.

Hope this helps!

0 - https://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html
1 - https://elasticsearch-dsl.readthedocs.io/en/latest/configuration.html#default-connection
