### ISSUE TITLE
readthedocs site out of sync with GitHub source.

### ISSUE THREAD

**Issue by rkomorn** [elastic/elasticsearch-dsl-py#1134]
Looks like the readthedocs site isn't quite synced up with the source in GitHub:

GitHub's index.rst says: "For Elasticsearch 6.0 and later, use the major version 6 (6.x.y) of the library."

https://elasticsearch-dsl.readthedocs.io/en/latest/ says "For Elasticsearch 6.0 and later, use the major version 5 (6.x.y) of the library."

**Comment by HonzaKral** [comment]
Thank you for the report, a webhook was missing, added back.
