### ISSUE TITLE
ModuleNotFoundError: No module named 'elasticsearch.helpers'

### ISSUE THREAD

**Issue by mr-bjerre** [elastic/elasticsearch-dsl-py#1137]
I am getting a strange error when importing `elasticsearch_dsl` in pytest.

    Traceback:
    elasticsearch/test_model.py:1: in <module>
    ../util/elasticsearch/__init__.py:1: in <module>
        from elasticsearch_dsl.connections import configure
    ../venv/lib/python3.6/site-packages/elasticsearch_dsl/__init__.py:4: in <module>
        from .search import Search, MultiSearch
    ../venv/lib/python3.6/site-packages/elasticsearch_dsl/search.py:10: in <module>
        from elasticsearch.helpers import scan
    E   ModuleNotFoundError: No module named 'elasticsearch.helpers'

If I run python interactively then I have no issues. Any suggestions?

**Comment by HonzaKral** [comment]
It looks like `elasticsearch` is not installed properly or it is only installed in a (virtual) environment that `pytest` doesn't have access to. I'd recommend looking at your setup to check where everything is.

it is definitely the missing dependency, question is where is the difference between pytest and just running python

**Comment by mr-bjerre** [comment]
You are right. I had a package called `elasticsearch` in my `tests` folder. Gosh.
