### ISSUE TITLE
Make `_doc_type` attribute on `DocType` classes public and expose important metadata about the type

### ISSUE THREAD

**Issue by pipoun** [elastic/elasticsearch-dsl-py#114]
I am wondering if there would be an idiomatic way to get the meta fields values directly from the `DocType` subclass.

```python
class Blog(DocType):
    description = String()

    class Meta:
        index = 'my_index'


class Post(DocType):
    class Meta:
        index = 'my_index'
        mapping = Mapping('post')
        mapping.meta('_parent', type='blog')
```
When constructing a search with the `has_parent` filter, I would like to use the `Post` class directly to get its parent type.

```python
blog_id = 42
parent_doctype = Post._doc_type.mapping._meta['_parent']['type']
search = Post.search()
parent_filter = F('has_parent', parent_type=parent_doctype,
                  filter=F('term', _id=blog_id))
response = search.filter(parent_filter).execute()
```

Is there another way to get the parent type? I haven't found anything else than `._doc_type.mapping._meta['_parent']['type']`.
But should it be done this way? As `_doc_type` is a pseudo protected variable, should it be accessed directly in the first place?
Moreover, the `_meta` instance variable of class `Mapping` is a dictionary, so it "breaks" the get-by-attribute coding style.

**Comment by HonzaKral** [comment]
Those are very good points I didn't anticipate - I thought people won't have any use for accessing the mappings and other meta information once the `DocType` is defined - that is also the reason why it's not the get-by-attribute since I always considered it just internal.

We could expose some of these information via properties on the `_doc_type` (and possibly rename it to `doc_type` to make it public). If it is only `parent` and other few values I would prefer it that way instead of exposing the whole of `Mapping` and supporting that.

What do you think?

btw now you can do:

    class Post(DocType):
        class Meta:
            index = 'my_index'
            parent = MetaField(type='blog')

instead of defining your own mapping instance in `Meta`

**Comment by pipoun** [comment]
Actually I'm only aware of my own use case, and I don't know if there would be many needs for some other `_doc_type` properties.
I can see the presence of the `name` property, so adding a 'parent' property wouldn't break the initial design.
What's bothering me is that `_doc_type` attribute was not aimed to be public, so as I you said, exposing mapping information outside of the `DocType` subclasses is not something you want.
As a comparison, sqlalchemy exposes this kind of information with `__table__` and `__mapper__` class attributes.

--
I was aware of the `MetaField` use, but I made my example with v0.0.3 compliant code. Thanks for the heads-up anyway!

**Comment by HonzaKral** [comment]
That mirrors how I think about the problem.

I will rename `_doc_type` to `doc_type` in the next release and create a `parent` property (maybe `parent_doc_type` that would even work with the `DocType` classes if I can make it work).

Thanks again for the feedback and patience with the library, issues like this help us make it better.

**Comment by HonzaKral** [comment]
In the end I decided not to rename `_doc_type` to just `doc_type`. I did however create a property to access the parent mapping in ec36d25 and documented the interface in 07dc9ad to make a statement about it being public.

having it without the leading underscore just, in my mind, created too much noise in both the code and the interface for the few use cases.
