### ISSUE TITLE
datetime convert for elastic broken

### ISSUE THREAD

**Issue by Wolfeg** [elastic/elasticsearch-dsl-py#1140]
trying to use python datetime and getting error ```RequestError: RequestError(400, 'search_phase_execution_exception', 'failed to parse date field [2019-03-19T01:00:00] with format [yyyy-MM-dd HH:mm:ss.SSS]')```

**Comment by mr-bjerre** [comment]
I have the same issue with `20190214T070000+0100`

**Comment by HonzaKral** [comment]
Unfortunately the python library only works with the default, iso-8601, date format. If you want to specify your own format you need to also supply the code to serialize python `datetime` into the format.You can always configure your mappings to accept both formats to make it work if needed.

Sorry for the inconvenience.

**Comment by mr-bjerre** [comment]
Do you have a suggestion on how to implement the serialization and where?

**Comment by HonzaKral** [comment]
> Do I need to convert datetime to the corresponding string, i.e. .strftime('%Y%m%dT%H%M%S%z') somewhere?

that is already happening. The problem is that you need to serialize it into a different format as you have overridden the default in elasticsearch.

The solution would be to implement a custom field like https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_document.py#L48-L57

I would really recommend changing your mappings instead though, either to just use the default or to accept both formats, both the iso (with `T`) and the custom format you are using now (with a space).

Hope this helps!

**Comment by mr-bjerre** [comment]
Cool thanks a lot. I really like this library! 

I am using [migration](https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/alias_migration.py) but the copy data breaks with this change and I can't figure out why exactly. Any suggestions how to best change the mapping without losing the data?

**Comment by HonzaKral** [comment]
I am really glad you like it, it means a lot!

The way is to transform the data during the migration. You can do it in elastic using an ingest pipeline (0) or (if your dataset isn't too big) just use the combination of the `scan` and `bulk` helpers (1) from `elasticsearch-py` to grab all the data, fix the format, and load them back in. You can even see the `reindex` helper (2) in the same module to see the integration, all that is missing is the format-fixing part.

0 - https://www.elastic.co/guide/en/elasticsearch/reference/6.6/ingest.html
1 - http://elasticsearch-py.readthedocs.io/en/master/helpers.html#bulk-helpers
2 - https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/helpers/actions.py#L404-L460

**Comment by mr-bjerre** [comment]
Once again thanks!

I actually ended up creating a `reindex()` method on my `Document`. Each document has a field of the original `xml` content which are then transformed into `elasticsearch/json` format. So I just have to keep the `id` from the documents.

**Comment by deniz-dilaverler** [comment]
> > Do I need to convert datetime to the corresponding string, i.e. .strftime('%Y%m%dT%H%M%S%z') somewhere?
> 
> that is already happening. The problem is that you need to serialize it into a different format as you have overridden the default in elasticsearch.
> 
> The solution would be to implement a custom field like https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_document.py#L48-L57
> 
> I would really recommend changing your mappings instead though, either to just use the default or to accept both formats, both the iso (with `T`) and the custom format you are using now (with a space).
> 
> Hope this helps!

Hi, this link no longer works, is there a way that I can access it?

**Comment by pquentin** [comment]
Not sure if this still applies, but here's the link:

https://github.com/elastic/elasticsearch-dsl-py/blob/28b4a16645318b22599a7e1c8739f520a95da322/test_elasticsearch_dsl/test_document.py#L48-L57
