### ISSUE TITLE
Adding parameters to search query

### ISSUE THREAD

**Issue by mr-bjerre** [elastic/elasticsearch-dsl-py#1145]
How do I create a query like [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-common-terms-query.html#_examples_6)? Is that possible in the current library?

**Comment by HonzaKral** [comment]
Absolutely, the rule of thumb is to use the name of the query as first parameter for `query()` and then any parameters as kwargs, so the first example would look like:

```python
s = Search()
s = s.query('common', query"="this is bonsai cool", cutoff_frequency=0.001)
```

Hope this helps!
