### ISSUE TITLE
scan() does not give me all hits

### ISSUE THREAD

**Issue by helmersl** [elastic/elasticsearch-dsl-py#1147]
Hi!
I'm using the scan method to retrieve a large number of search results
```
s = Search(using=connection, index=index, doc_type="doc")
q = Q({"multi_match": {"query": 'example_search', "fields": ['title', 'body'], "type":"phrase",
                  "minimum_should_match":"100%", "analyzer":'standard'}})
s = s.query(q)
hits = []
for hit in s.scan():
     hits.append({"doc_id": hit.doc_id, "found_term": 'example_search'})
```
I currently have the impression that the scan search is not returning all hits from my index. I had a look at the documentation of elasticsearch_dsl and elasticsearch but I don't really understand if there is a parameter I should change or pass (maybe the scrolling parameter?) in order to assure that all hits in all documents will be returned... Any ideas on what might cause the problem?

**Comment by HonzaKral** [comment]
What gives you the impression that not all hits are returned? The code is correct for retrieving all hits.

**Comment by helmersl** [comment]
I get inconsistent results. If I perform the search on the same index twice, the output is not exactly the same. I also don't get a connection error or anything similar so I'm wondering what is going wrong. But it's good to know that in general, scan should retrieve all hits without setting additional comments. Thanks!

**Comment by HonzaKral** [comment]
When you call a `scan()` you get documents in random order and also as they existed when you started the iteration, so if there is any active indexing or any other operations though would not be visible.

**Comment by davidgacc** [comment]
@HonzaKral I'm using `Search()` and using `scan()` inside a function that is returning a result of the records. When I'm trying to iterate for the second time in the result, I'm not getting a result. Only for the first time works. Any ideas?

**Comment by HonzaKral** [comment]
You can only iterate on the returned object once, if you want to iterate again you need to call `scan` again.
