### ISSUE TITLE
Perplexed by timetamps

### ISSUE THREAD

**Issue by NetwarSystem** [elastic/elasticsearch-dsl-py#1152]
I have spent several hours today reading threads about DSL and timestamps. I am utterly perplexed and don't feel this issue is well addressed in the questions here - perhaps there is some underlying bit of knowledge I lack, so I'm going to try to be neat & complete.

I have Elasticsearch 6.5.4, Python 3.6.7, and pip freeze shows elasticsearch/elasticsearch_dsl 6.3.1.

This is a fragment from the map from one of a number of indices I keep - in this case a stream of tweets related to Brexit. The additions to the curl statement are due to the presence of Search Guard as our multitenant security system.

`curl -s -H 'Content-Type: application/json' --insecure -u admin:admin  -XGET https://localhost:9200/_mapping/$1?pretty

>   "twbrexit" : {
>     "mappings" : {
>       "tweets" : {
>         "_all" : {
>           "enabled" : false
>         },
>           "created_at" : {
>             "type" : "date",
>             "format" : "EEE MMM dd HH:mm:ss Z YYYY"
>           },

A query with no constraints produces hits that have strings representing the Twitter date format and timestamp_ms.

`s = Search(using=client, index="twbrexit").query("match", text="Brexit")`
> ['created_at', 'entities', 'filter_level', 'geo', 'id', 'id_str', 'lang', 'meta', 'place', 'quote_count', 'reply_count', 'retweeted_status', 'source', 'text', 'timestamp_ms', 'truncated', 'user']
> <class 'str'>
> 1553036149544
> <class 'str'>
> Tue Mar 19 22:55:49 +0000 2019

This seems like it should work, but does not for created_at or timestamp_ms.
```
s = Search(using=client, index="twbrexit")
.filter('range', created_at='{"from": "Sun Mar 03 00:00:00 +0000 2019" }')
.query("match", text="Brexit")
elasticsearch.exceptions.RequestError: RequestError(400, 'parsing_exception', 
'[range] query does not support [created_at]')
```

The following DSL snippet was created within the Kibana Discovery tab and it filters dates as expected.

> { "range": {
>     "created_at": {
>       "gte": "now-2w",
>       "lt": "now"}}}

'''
timefilt = '{"range": { "created_at": { "gte": "now-2w", "lt": "now"}}}'
s = Search(using=client).filter("range",timefilt).query("match", text="Brexit")
'''

>  File "/usr/local/lib/python3.6/dist-packages/elasticsearch_dsl/search.py", line 319, in filter
>     return self.query(Bool(filter=[Q(*args, **kwargs)]))
> TypeError: Q() takes from 0 to 1 positional arguments but 2 were given
> 
'''s = Search(using=client).filter(timefilt).query("match", text="Brexit")

> elasticsearch_dsl.exceptions.UnknownDslObject: DSL class `{"range": { "created_at": { "gte": "now-2w", "lt": "now"}}}` does not exist in query.

So ... this **SEEMS** like it should be really straightforward, but it is not. How does one query with a time based filter using the Python client?

**Comment by HonzaKral** [comment]
just pass in a `datetime` object and also don't pass in the value for `created_at` as a string but instead as a `dict`:
```python
s = Search(using=client, index="twbrexit")
.filter('range', created_at={"from": datetime.now() })
.query("match", text="Brexit")
```

If you are using a special, non standard, date format you might have to format the datetime yourself to match or configure elasticsearch to allow both your custom and the default iso-based format.

Hope this helps!

**Comment by NetwarSystem** [comment]
This is what I actually got to work first. Still using a string, but on the right path now. Thanks.

```
#!/usr/bin/python
import datetime

# Python strftime reference
# http://strftime.org/
#
# Elasticsearch Twitter timestamp mapping as a single line of JSON
# "created_at" : {"type" : "date",  "format" : "EEE MMM dd HH:mm:ss Z YYYY"},
#
# Example timestamp: Sun Mar 24 05:20:06 +0000 2019

# Twitter timestamp of the now
now = datetime.datetime.now()
print(now.strftime("%a %b %d %X +0000 %Y"))

# 24 hours ago
last24 = now - datetime.timedelta(days=1)
print(last24.strftime("%a %b %d %X +0000 %Y"))

# This specific query works against Twitter data
#s = Search(using=client, index="twbrexit").filter('range', created_at={"from": last24.strftime("%a %b %d %X +0000 %Y") }).query("match", text="Brexit")

```
