### ISSUE TITLE
query with character "-"

### ISSUE THREAD

**Issue by Idriel** [elastic/elasticsearch-dsl-py#1153]
I dont get good results when query have "-" in filed like:
must=[Q('match', EventID="4624"), Q('match',**{"WorkstationName":"XX-ABCDE"})])
It will return all results starting with XX, it'll not match XX-ABCDE. I tried also esacaping " like "\"XX-ABCDE\""

Or when I have - in name
must=[Q('match',access_type="VPN"), Q('match',Framed-IP-Address="192.168.0.1")])
SyntaxError: keyword can't be an expression

**Comment by HonzaKral** [comment]
When the name of the field is not a valid identifier in python you need to use the `**{}` syntax as you have in the first example.

For matching on values with `-` character you need to specify which analyzer is being used - by default elasticsearch will split it into two tokens ans search for them separately which might not be what you are looking for. In your case you might prefer a `keyword` datatype to `text` as those values are really identifiers. If you are using default mappings then just matching on `WorkstationName.keyword` should do the trick as it will perform an exact lookup

Hope this helps!
