### ISSUE TITLE
Search using script

### ISSUE THREAD

**Issue by NimJ** [elastic/elasticsearch-dsl-py#1154]
I Couldn't find this example anywhere, so thought this might be useful in examples.
Sample Query to return search results from calculated field rather than creating a new field using using script-fields.
`from elasticsearch_dsl import Search`
`s = Search(using=es, index="index_name")`
            `.filter({"match":{"Col1":"Val1"}})`
            `.filter({"match":{"Col2":"Val2"}})`
            `.query({"script":{"script":{"inline": "doc['col3'].value - doc['col4'].value == 1"}}})`
`response = s.execute()`
`print("Got %d Hits:" % response.hits.total)`

**Comment by HonzaKral** [comment]
Thank you for the example, for completeness just note that you can also just write:
`s.query('script', script="doc['col3'].value - doc['col4'].value == 1")`

Hope this helps!

**Comment by bukosabino** [comment]
Finally, I find a good example to filter results using 'script'.

You should include it in the documentation!

Thank you.
