### ISSUE TITLE
Best way to search variable field

### ISSUE THREAD

**Issue by micromaker60** [elastic/elasticsearch-dsl-py#1155]
I am looking to search a variable field i.e. instead of searching for dog1, dog2, dog3, etc. I want it to find dogX and therefore find all of them. I have an instance of Kibana doing this using a "query_string" operation, but I have not been able to get "query_string" to work with the "query" parameter of es.Search(). What would be the best way to accomplish this?

**Comment by HonzaKral** [comment]
There is an option to do a `query_string` query (0):
```python
s = Search().query('query_string', query="...")
```
but a better approach might be using a `multi_match` (1):
```python
s = Search().query('multi_match', query='...', fields=["dog*"])
```
Hope this helps!

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html
1 - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html

**Comment by micromaker60** [comment]
Thanks for the quick response! It's actually in the query itself that I looking to find the items. So a better example is "animals" would be my field and "dogx" would be the response. Would I put "animals" in query referring to your second approach?
