### ISSUE TITLE
How to get list of Document fields ?

### ISSUE THREAD

**Issue by ArtemBernatskyy** [elastic/elasticsearch-dsl-py#1157]
Hi, awesome library 

but how to get list of Document fields ?

for example
```
class TimeStampedModel(Document):
    modified_date = Date()
    created_date = Date()
```

How can i get this list `['modified_date', 'created_date']` ?

Thx in advance.

**Comment by HonzaKral** [comment]
Hi, you can always iterate on `._doc_type.mapping` to get the field names, if you would like to get all fields recursively (in case you have `Object` and/or `Nested` fields) use `._doc_type.mapping.properties._collect_fields()`

Hope this helps!

**Comment by ArtemBernatskyy** [comment]
Thx @HonzaKral , perfectly solves the problem !
