### ISSUE TITLE
Define a field with a dash in the field name

### ISSUE THREAD

**Issue by SteveAndrewArcher** [elastic/elasticsearch-dsl-py#1159]
Hi,
I'm trying to convert a bunch of existing mappings that currently just exist as json documents to use elasticsearch_dsl. In these existing mappings, there are some field names that contain `-`. Since this character is allowed in elasticsearch field names, but not in python identifiers, just doing
```
class MyDocument(Document):
    field-with-a-dash = Object(MyInnerDoc)
```
won't work.

I found some code floating around that did:
```
class MyDocument(Document):
    fieldWithADash = Object(MyInnerDoc, name="field-with-a-dash")
```
but `name` came up as an unknown parameter when attempting to apply this to an index, (and I couldn't see any reference to this parameter in any docs) so I dunno if this is a red herring.

I noticed a suggestion here in the issues for querying a field like this ( [755](https://github.com/elastic/elasticsearch-dsl-py/issues/755) ), so I was wondering if there's any way to define one of these fields using elasticsearch_dsl? Not having to change the field names would save a lot of headaches in the other areas of the project...

**Comment by HonzaKral** [comment]
I am sorry but there is currently no convenient way to do this with `Document` as it is primarily a python object and python identifies cannot have dashes in them.

You can use a workaround by doing:
`MyDocument._doc_type.mapping.field('field-with-a-dash', Object(...))` after you have defined `MyDocument` but you will still have trouble addressing that field in the document instance where you will have to use `d['field-with-a-dash]` notation and would not benefit from the automatic (de)serialization in some cases.

Hope this helps!
