### ISSUE TITLE
0.0.4 Release

### ISSUE THREAD

**Issue by millerjo** [elastic/elasticsearch-dsl-py#116]
@HonzaKral This isn't as much of an issue as it is just a general question, but is there any tentative plans on a release date for elasticsearch_dsl 0.0.4?

I am currently developing against 0.0.3 and have ran into an issue that has been fixed since the release. Ideally, I would like to continue using the released version of elasticsearch_dsl but it kind of depends on how far out the next version is. Any additional info would be much appreciated.

Thanks

**Comment by HonzaKral** [comment]
Yes, there are tentative plans for "soon" :) I hope that in the next week or so there should be a new release with all the fixes and advancements.

**Comment by millerjo** [comment]
That's a lot sooner than I was expecting! Thanks for the info.

**Comment by HonzaKral** [comment]
https://pypi.python.org/pypi/elasticsearch-dsl
