### ISSUE TITLE
Persistence, two level deep nested object?

### ISSUE THREAD

**Issue by littlehome-eugene** [elastic/elasticsearch-dsl-py#1160]
** Edit **
I found that changing `Object` to `Nested` makes it work. although I don't get why even after looking at the source.. :(

Product has ReviewMeta and ReviewMeta has Area.

So I did use `Object` and `InnerDoc` twice as below, but the fields in AreaWrapper are not indexed to ES. 

ProductES().to_dict() looks like the following

`{'review_meta': {'id': 6041, 'name': 'BEOLS', 'location': {'lat': Decimal('37.477680419312000'), 'lon': Decimal('126.962628216304000')}, 'area_locality_level_1': {'id': 2852, 'locality_level': 110, 'name': '서울'}, 'area_locality_level_2': {'id': 2993, 'locality_level': 120, 'name': 'abc'}}}`

```
class AreaWrapper(InnerDoc):

     id = Integer()
     locality_level = Integer()
     name = Text(
         analyzer="korean_analyzer",
         fields={
             'raw': Keyword()
         }
     )


 class ReviewMetaWrapper(InnerDoc):

     id = Integer()

     name = Text(
         analyzer="korean_analyzer",
         fields={
             'raw': Keyword()
         }
     )
     location = GeoPoint()

     # changing Object => Nested works...
     area_locality_level_1 = Object(AreaWrapper)
     area_locality_level_2 = Object(AreaWrapper)


 class ProductES(DocType):
     review_meta = Object(ReviewMetaWrapper)
```

**Comment by HonzaKral** [comment]
Can you describe the error or the code you are using to save it to ES? Thanks!

**Comment by littlehome-eugene** [comment]
Oh, once I changed `area_locality_level_1 = Object(AreaWrapper)` to `area_locality_level_1 = Nested(AreaWrapper)`, it works fine, just wonder what is difference. Thanks.

**Comment by HonzaKral** [comment]
There is no difference between `Object` and `Nested` on the code level so I am having trouble reproducing it, can you please show the code that doesn't work? Not just the definition of the document class but also the usage of it that results in unexpected results. Thanks!

**Comment by HonzaKral** [comment]
Closing this issue as there is no additional information. Please feel free to reopen with more data. Thank you!
