### ISSUE TITLE
How to define batch size in bulk query

### ISSUE THREAD

**Issue by shivam05011996** [elastic/elasticsearch-dsl-py#1161]
I have the following bulk operation defined - 
```python
bulk(client=es_client,
   actions=(obj.indexing() for obj in X.objects.exclude(id__in=[<some list of items>]).iterator()))
```
This is a one by one bulk insertion, how do I define a bulk_size parameter. I am aware that lower level client supports this. But I could not find anything in the docs of elasticsearch-dsl-py

**Comment by HonzaKral** [comment]
That helper is from the `elasticsearch-py` library, you can see the docs at [0]. The parameter you are looking for is `chunk_size` which defaults to 500.

Hope this helps!

0 - https://elasticsearch-py.readthedocs.io/en/master/helpers.html#bulk-helpers
