### ISSUE TITLE
DocType inheritance keeps settings of parent fields

### ISSUE THREAD

**Issue by candale** [elastic/elasticsearch-dsl-py#1162]
I have the following code

```
In [1]: from elasticsearch_dsl import DocType, Object
In [2]: class First(DocType):
   ...: 
   ...:     extra = Object(dynamic=True)
   ...: 
   ...: 
In [3]: class Second(First):
   ...: 
   ...:     extra = Object(dynamic='strict')
   ...: 
   ...: 
In [4]: Second._doc_type.mapping.to_dict()
Out[4]: {'doc': {'properties': {'extra': {'dynamic': True, 'type': 'object'}}}}
```
My expectation is that the field `extra` should have `dynamic = 'strict'` in the mapping of `Second`, not the setting that was originally set in `First`.

I think the problem comes from the method [Mapping.update](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/mapping.py#L162): 
```
    def update(self, mapping, update_only=False):
        for name in mapping:
            if update_only and name in self:
                # nested and inner objects, merge recursively
                if hasattr(self[name], 'update'):
                    self[name].update(mapping[name])
                continue
            self.field(name, mapping[name])

        if update_only:
            for name in mapping._meta:
                if name not in self._meta:
                    self._meta[name] = mapping._meta[name]
        else:
            self._meta.update(mapping._meta)
```

I believe that the parameter `update_only` should propagate to the subsequent calls to `.update`; otherwise we call `.update` on a field mapping and the the field's `._meta` gets overwritten with the mapping from the base class field.

**Comment by HonzaKral** [comment]
When inheriting documents it is assumed that they will live in the same index where you cannot have different mappings for different fields, that is why we do the `update_only` to just "append" fields to the mapping. Does that make sense?

**Comment by candale** [comment]
Ahh, I see. Alright.

How would you recommend I go around this assumption when I need to have a base Document and overwrite its fields in a child class? Or is this something I should not try to do but rather rewrite the entire thing?

Thank you for the quick response, I appreciate it!

**Comment by HonzaKral** [comment]
I am sorry, I read your original issue wrong and this is indeed a bug as we do override normal fields but not `Object` fields, my apologies

**Comment by HonzaKral** [comment]
Fixed in master, my apologies again for the confusion, I didn't understand properly the first time. It should work as expected this time.

**Comment by candale** [comment]
Alright, awesome! No problem!
