### ISSUE TITLE
MyDocument._index and MyDocument.init()

### ISSUE THREAD

**Issue by peterbe** [elastic/elasticsearch-dsl-py#1164]
This might be two questions/issues in one and if that's the case let's morph it accordingly. 

I have a document that looks like this:

```python
class MyDocument(Document):
    title = Text(required=True, analyzer=text_analyzer)
    class Index:
        name = "myindex"
        settings = settings.MyDocumentSettings
```

This works:

```python
# Inside reindex-everything.py
if recreate:
    index = BlogItemDoc._index
    index.delete(ignore=404)
    index.create()
```

What bothers me is that accessing `_index` is a **private** attribute. Hence [not in the documentation](https://elasticsearch-dsl.readthedocs.io/en/latest/api.html#document) and it makes me nervous. 

Can there be a `Document.get_index()` instead? Or, just `Document.index`.

I see it's [used in the examples too](https://github.com/elastic/elasticsearch-dsl-py/blob/c60ef38c12b1bf0e07fe6b3353cf5ca38ef57480/examples/completion.py#L72) so I don't feel *too* bad.

Secondly, I use that pattern of `index.delete(ignore=404); index.create()` but I get the impression that I'm supposed to use `MyDocument.init()` instead. However, that throws me this error:

```
Traceback (most recent call last):
...
  File "/Users/peterbe/virtualenvs/django-peterbecom/lib/python3.5/site-packages/elasticsearch_dsl/document.py", line 138, in init
    i.save(using=using)
  File "/Users/peterbe/virtualenvs/django-peterbecom/lib/python3.5/site-packages/elasticsearch_dsl/index.py", line 305, in save
    'You cannot update analysis configuration on an open index, you need to close index %s first.' % self._name)
elasticsearch_dsl.exceptions.IllegalOperation: You cannot update analysis configuration on an open index, you need to close index blog_item first.
```

[The API documentation for `Document.init`](https://elasticsearch-dsl.readthedocs.io/en/latest/api.html#elasticsearch_dsl.Document.init) doesn't mention anything along the lines that I have to close the index first. 

[Here's an example using `.init`](https://github.com/elastic/elasticsearch-dsl-py/blob/c60ef38c12b1bf0e07fe6b3353cf5ca38ef57480/examples/completion.py#L61-L62) but I don't see where it does the index closing dance first. 

If you're supposed to close the index first (if so, how??) it should be mentioned [in the user guide](https://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#document-life-cycle) or at least it should mention that this only works when you've never created the index before.

**Comment by HonzaKral** [comment]
Thanks for raising these issues!

I agree that we should probably document `_index` just as we do `_doc_type` as I view it as part of the API. The underscore is more to not pollute the namespace of `Document` and thus restrict what fields people can have on their documents.

As for the second question that is due to #1065 and the fact that you cannot change an existing index in elasticsearch.

To add more options I would greatly recommend that you have a loot at the `alias_migration` example (0) which provides a better way to reindex your data and evolve your schema without any downtime and without running into these issues (well, except accessing `._index` of course)

Hope this helps!


0 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/alias_migration.py

**Comment by peterbe** [comment]
> I agree that we should probably document _index just as we do _doc_type as I view it as part of the API. 

Then why close the issue? Mind you, I don't see `_doc_type` being in the API documentation either. 

That alias migration looks fancy and equally confusing. I'll make a mental note to remember it exists next time I need to a reindex without accepting downtime. So much to learn!

**Comment by HonzaKral** [comment]
I am sorry for closing the issue right away and for the confusion. I was answering on a phone and failed to notice my mistake, my apologies. `_doc_type` is indeed not documented, `_index` is however, it is just an issue of our docs being out of sync (#1134). You can see the documentation of `_index` at [0]:

> The index associated with the Document is accessible via the _index class property which gives you access to the :ref:`index` class.

> That alias migration looks fancy and equally confusing.

It is an advanced pattern with some complex logic, if you had any pointers to what specifically made it confusing or how it can be improved I would be extremely happy to help clarify it and improve the documentation, thank you!

0 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/docs/persistence.rst
