### ISSUE TITLE
Change doc_type validation

### ISSUE THREAD

**Issue by ArnonMarcus** [elastic/elasticsearch-dsl-py#1165]
The current validation in Index.document() raises if the document type has a different name than the index, but according to the official documentation of ElasticSearch 6.x there can be only one type per index, but it can actually have any name.

**Comment by HonzaKral** [comment]
Yes, it is possible to have a different name, but only if the `Index` doesn't already have a document type defined which is named differently. The validation logic follows the documentation as you mentioned, for example:

```python
from elasticsearch_dsl import Index, Document, Text
class D(Document):
    name = Text()
    class Meta:
        doc_type = 'not-doc'
i = Index('i')
i.document(D)
i.to_dict()
# {'mappings': {'not-doc': {'properties': {'name': {'type': 'text'}}}}}
```

Hope this helps!

**Comment by ArnonMarcus** [comment]
Hmm, so - this was kind of a gotcha - it was because I was still using the old way of defining metadata:
Let's say I have gone and created an index in ElasticSearch using Kibana's concole.
The index name is 'my_index' and the document type (mapping) is 'my_doc_type'.
Now, in python, I do this:
`
from elasticsearch_dsl import Document
class MyDocument(Document):
    class Meta:
        index = 'my_index'
        doc_type = 'my_doc_type'
`
I get this:
> IllegalOperation: Index object cannot have multiple types, doc already set, trying to asign 'my_doc_type'

It's bewildering, as what's defined in ElasticSearch and what is 'seemingly' being defined here, are aligned - index name and doc-type, all of it.

This fixes the problem:
`
from elasticsearch_dsl import Document
class MyDocument(Document):
    class Meta:
        doc_type = 'my_doc_type'

    class Index:
        doc_type = 'my_doc_type'
        name = 'my_index'
`
