### ISSUE TITLE
In 7.x, AttributeError: 'Index' object has no attribute 'doc_type'

### ISSUE THREAD

**Issue by brainix** [elastic/elasticsearch-dsl-py#1166]
Hello, folks!

Locally, I've upgraded Elasticsearch to 7.0, and I'm working off of the `7.x` branch of `elasticsearch-dsl-py`.

I have code like so:

```
from elasticsearch_dsl import Index

_index = Index('spool')

@_index.doc_type
class Video:
    ...
```

And it's started resulting in:
`AttributeError: 'Index' object has no attribute 'doc_type'`

Am I doing something boneheaded?

Thanks in advance!

**Comment by HonzaKral** [comment]
Please use `document` instead of doc_type which has been deprecated and now removed.

Thank you!

**Comment by brainix** [comment]
That worked!  Thanks as always for your help, @HonzaKral.
