### ISSUE TITLE
ES 7.0 support

### ISSUE THREAD

**Issue by takaomag** [elastic/elasticsearch-dsl-py#1167]
Is there any plan or schedule to support ES 7.0 ?

**Comment by HonzaKral** [comment]
Yes, absolutely. There is a `7.0` branch that has all tests passing since yesterday. I want to do another pass over all the issues and PRs here and do a release soon. 

Any feedback would be appreciated, thank you!

**Comment by HonzaKral** [comment]
`7.0.0` has just been released - https://pypi.org/project/elasticsearch-dsl/

**Comment by takaomag** [comment]
Thank you so much!
