### ISSUE TITLE
Paginating a suggest search

### ISSUE THREAD

**Issue by knewman-chownow** [elastic/elasticsearch-dsl-py#1169]
**Elasticsearch DSL version**: 5.4.0
**Elasticsearch-Py version**: 5.5.1

 I'm rendering a page of results based on a suggest search. However, the number of results may end up being more than can fit on a single page. In those cases, I need to paginate the results. I've tried using array slices but it just keeps returning the same items. Here is an example of my implementation:
```
def autocomplete(cls, query, size=10, filter_params=None, offset=0):
    fuzziness = len(query) // 5 if query else 0

    completion = {
        'field': cls.AUTOCOMPLETE_FIELD,
        'size': size,
        'fuzzy': {'fuzziness': fuzziness}
    }

    search_query = cls.search()
    search_query = search_query.suggest('autocomplete', query, 
    completion=completion).extra(size=0)
    search_query = search_query[offset:offset + size]
    result = search_query.execute()

    return [r._source for r in result.suggest.autocomplete[0].options]
```

When I do this, it just keeps repeating the same items over and over again. So if I pass in a size of 3, I just get the same 3 items each time, regardless of the value of my `offset` parameter.

The only way I've been able to get it to work is by making the following 2 changes:
1. Change the `size` field in my `completion` dict to be `'size': size + offset` so that it can hold increasingly more items as I go into deeper pages
1. Do an additional slice after I execute the query, so that I am returning this:
```
return [r._source for r in result.suggest.autocomplete[0].options][offset:offset + size]
```

However, this feels a bit hacky and poorly performing, as the further I go into the pages, the more unnecessary "pages" of items I will be removing from my last slice. When I do a normal search like this, the slicing works as expected:
```
search_query = cls.search()
search_query = search_query[offset:offset + size]
result = search_query.execute()
return result
```

Am I don't something wrong? Do I need to upgrade my versions for one of my libraries? Or is it a limitation of suggest searches that they don't work with from/size slicing?

**Comment by HonzaKral** [comment]
Thank you for the question. Unfortunately there really isn't a better solution than to retrieve `offset+size` items and then discard some. The auto-complete functionality is really not meant for exhaustive search and/or pagination, it is really more about presenting just the top results and it has also been optimized for that use case.

If you want pagination I am afraid you will have to use a query instead, something like `match_phrase_prefix` query on a `text` field. You can find more approaches and examples in https://www.elastic.co/guide/en/elasticsearch/guide/master/_index_time_search_as_you_type.html

I am sorry I couldn't be of more help.

**Comment by knewman-chownow** [comment]
Thank you for the quick response! I'll take a look at that documentation and see what works best for my use case.
