### ISSUE TITLE
Filter Aggregation not working

### ISSUE THREAD

**Issue by john-parton** [elastic/elasticsearch-dsl-py#117]
I'm trying to create an aggregation like the one described here: http://www.elastic.co/guide/en/elasticsearch/reference/1.x/search-aggregations-bucket-filter-aggregation.html

```python
agg = A({
    "filter" : { "range" : { "stock" : { "gt" : 0 } } },
    "aggs" : {
        "avg_price" : { "avg" : { "field" : "price" } }
    }
})
agg.to_dict()
{
    "filter": { "range": { "stock": { "gt": 0 } }, 
        "aggs": {
            "avg_price": { "avg": { "field": "price" } }
        }
    }
}
```
The `"aggs"` block is moved inside of the `"filter"` block.

I tried to circumvent `A` like this:
```python
query.aggs.bucket('in_stock_products', {
            "filter" : { "range" : { "stock" : { "gt" : 0 } } },
            "aggs" : {
                "avg_price" : { "avg" : { "field" : "price" } }
            }
        })
query.to_dict()
{
    "query": {
        ...
    }, 
    "aggs": {
        "in_stock_products": {
            "filter": { "range": { "stock": { "gt": 0 } }, 
                "aggs": { "avg_price": { "avg": { "field": "price" } } }
            }
        }
    }
}
```
but it still moved the `"aggs"` block inside of the `"filter"` block. (Probably because the `dict` is converted to the `A` class internally.)

If you try to execute the query, you'll get an error like `QueryParsingException[[catalogue] No filter registered for [aggs]`

I'm using a clone of master.

`0.0.3` doesn't appear to have this problem, but I need support for `Search.suggest`.

I cloned master and did a git revert on this commit: https://github.com/elastic/elasticsearch-dsl-py/commit/856801a8c553adf4f34fe353f6f63cd6cd596126

And it went back to the `0.0.3` (correct) behavior.

**Comment by john-parton** [comment]
I would recommend adding a new test case as well. Something like this:

```python
# test_elasticsearch_dsl.test_aggs
def test_aggregate_filter_invariant():
    d = {
        "filter" : { "range" : { "stock" : { "gt" : 0 } } },
        "aggs" : {
            "avg_price" : { "avg" : { "field" : "price" } }
        }
    }
    a = aggs.A(d)
    assert d == a.to_dict()
```

**Comment by ourlord** [comment]
I guess I am having the same issue with this.
The json query should look like this:

	{
		"query": {
			"query_string": {
				"query": "tags:ticket"
			}
		},
		"filter": {
			"range": {
				"timestamp": {
					"gte": "2015/04/02 09:26:00.1427",
					"lte": "2015/04/02 09:27:00.1427"
				}
			}
		},
		"aggs": {
			"tickets": {
				"terms": {
					"field": "ticketid",
					"size": 10000
				}
			}
		}
	}

I try this query in both REST and elasticsearch-py. The result should be in total 292 hits.
And I rewrite the same query into elasticsearch-dsl-py. The query is like this:

	s = Search(using = ..., index = ...)
		.query('query_string', query = 'tags:ticket')
		.filter('range', timestamp = { 'gte' : "2015/04/02 09:26:00.1427", 'lte' : "2015/04/02 09:27:00.1427"})
	s.aggs.bucket('tickets', 'terms', field = 'ticketid', size = 10000)

I believe this two query should act the same but the fact is this one returns total more than 3000 hits I don't know why.
Also, I tried the `from_dict` with my original JSON query. But it also returned a weird number of results.
So I tried a `s.to_dict()` and it returns

    {'query': {'query_string': {'query': 'tags:ticket'}}, 'aggs': {'tickets': {'terms': {'field': 'ticketid', 'size': 10000}}}}

The filter seems missing which makes sense to return that a lot of amount of results.

**Comment by jaywhy13** [comment]
Hi, I've read this issue and looked at the tests that exists, but I'm still not clear on how I would do an aggs query with a nested filter and aggs side by side. See what I'm trying to do below.

```
{
  "aggs": {
    "gas-budget": {
      "filter": {
        "terms": {
          "category.name.raw": ["Fuel"]
        }
      },
      "aggs": {
          "stats": {
            "stats": {
              "field": "amount"
            }
          }
        }
    },
    "clothing-budget": {
      "filter": {
        "term": {
          "category.name.raw": "Clothing"
        }
      },
      "aggs": {
        "stats": {
          "stats": {
            "field": "amount"
          }
        }
      }
    }
  }
}
```

**Comment by jaywhy13** [comment]
Got it. I had to add it to a top level search like so...

```
# Declare search
s = Search()

# Do aggregation for fuel
fuel_agg = Filter(Q('terms', category=["Fuel"]))
fuel_agg.bucket('fuel_stats', 'stats', field="amount")
# Add it to search
s.aggs.bucket('fuel_budget', fuel_agg)

# Do aggregation for clothing
clothing_agg = Filter(Q('terms', category=["Clothing"]))
clothing_agg.bucket('clothing_stats', 'stats', field="amount")
# Add it
s.aggs.bucket('clothing_budget', clothing_agg)

pprint(s.to_dict())

>>> {'aggs': {'clothing_budget': {'aggs': {'clothing_stats': {'stats': {'field': 'amount'}}},
                              'filter': {'terms': {'category': ['Clothing']}}},
          'fuel_budget': {'aggs': {'fuel_stats': {'stats': {'field': 'amount'}}},
                          'filter': {'terms': {'category': ['Fuel']}}}},
 'query': {'match_all': {}}}
```
