### ISSUE TITLE
Upgrading from 6.3.1 to 7.0.0 causes illegal argument exception on Document.save()

### ISSUE THREAD

**Issue by shivam05011996** [elastic/elasticsearch-dsl-py#1171]
I recently upgraded, I have no change in the definitions of my mapping specified in the Django application but still the following error is being raised -

```
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Rejecting mapping update to [shivam-index] as the final mapping would have more than 1 type: [_doc, doc]') 
```

I am not to figure out whats messing up here.

**Comment by HonzaKral** [comment]
What is the version of the Elasticsearch server you are running against?

**Comment by shivam05011996** [comment]
@HonzaKral 6.6.0

**Comment by HonzaKral** [comment]
If you are using Elasticsearch 6.x you cannot be using the 7.x version of the library, please use 6.4.0 instead.

Thank you

**Comment by shivam05011996** [comment]
Thanks For the quick response. And it works perfectly.
