### ISSUE TITLE
Response.hits.total is an AttrDict instead of an int

### ISSUE THREAD

**Issue by federicotdn** [elastic/elasticsearch-dsl-py#1172]
On `elasticsearch-dsl` version `6.X.Y`, the total number of hits (`int`) after executing a `Search` could be accessed through the `.hits.total` property of the `Response` class. On `7.0.0`, this property is no longer an `int`, but an `AttrDict`. To reproduce:

Index a document:
```bash
$ curl -X PUT "localhost:9200/twitter/_doc/1" -H 'Content-Type: application/json' -d'
{
    "user" : "kimchy",
    "post_date" : "2009-11-15T14:12:12",
    "message" : "trying out Elasticsearch"
}
'
```

Then, on Python:
```python
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search

es = Elasticsearch()
s = Search(using=es).index('twitter')

response = s.execute()
print('Total %d hits found.' % response.hits.total)
```

Will yield:
```python
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    print('Total %d hits found.' % response.hits.total)
TypeError: %d format: a number is required, not AttrDict
```

The `AttrDict` contains `{'value': 1, 'relation': 'eq'}`, in this case.

**Comment by HonzaKral** [comment]
Yes, this is a change in elasticsearch that is important (see https://github.com/elastic/elasticsearch/issues/33028 for details) so we didn't want to hide it from the user by maintaining the old interface which might return incorrect results.

Unfortunately with major version there can be breaking changes.

**Comment by federicotdn** [comment]
Thanks for the information. This change implies that [this section](https://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#hits) should be updated, as `print('Total %d hits found.' % response.hits.total)` assumes that `.hits.total` is an `int`.

**Comment by HonzaKral** [comment]
Thank you for the catch, @federicotdn. Updated in 43c71ce6a22ed8ac0e44be6fa27dd680375a8b0a, good catch!

**Comment by Kaligule** [comment]
@honzakral  This is still wrong in the documentation. 
![still wrong in the official documentation](https://user-images.githubusercontent.com/3586246/229778684-2eedc63a-bd85-46f9-bff1-f0228e7c97cc.png)

**Comment by honzakral** [comment]
Thanks, @Kaligule! I am no longer with Elastic and working on the library unfortunately. That is now @sethmlarson
