### ISSUE TITLE
Specifying type of Object subfield?

### ISSUE THREAD

**Issue by rgov** [elastic/elasticsearch-dsl-py#1174]
I have a Document which contains an Object field, which I populate with a JSON deserialized object from another part of my application.

The object winds up in Elasticsearch just fine, but I do have some lon/lat points that are indexed separately `foo.position.lat` and `foo.position.lon` whereas I'd rather just have a geopoint `foo.position`.

Is it possible to override how subfields of my Object are handled, without modeling the whole structure as a Document or InnerDoc subclass?

**Comment by HonzaKral** [comment]
You can always have a `Document` or `InnerDoc` class specifying just the fields you wish to control, the rest of the fields will remain as the defaults but will still work as expected.

If you don't want to define an `InnerDoc` class explicitly you can also just pass in a `dict` containing `properties` as seed in [0].

Hope this helps!

0 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_field.py#L80
