### ISSUE TITLE
Unsupported parameters in 7.0.0

### ISSUE THREAD

**Issue by bergerr** [elastic/elasticsearch-dsl-py#1177]
I'm trying to upgrade to the 7.0.0 version but I keep running into the same error. Whenever I run `Form.init()` it gives me back 

```
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [name : {type=keyword}] [breedCode : {type=keyword}] [id : {type=integer}] [transaction : {relations={form=transaction}, type=join}]')
```

Here is the code I'm working with:
```
class Form(Document):
    id = Integer(required=True)
    breedCode = Keyword(required=True)
    name = Keyword(required=True)
    transaction = Join(relations={'form': 'transaction'})

    class Index:
        name = 'txn-forms'
        settings = {
            "number_of_shards": 5,
            "number_of_replicas": 1,
        }

class Transaction(Document):
    id = Integer(required=True)
    transactionNumber = Text(required=True)

def main():
    Form.init()
```

It works fine in 6.3.1 so I feel like the problem has something to do with the removal of doc_types.

**Comment by shivam05011996** [comment]
Please check if your Elasticsearch server version is running is 7.x, I have
faced this situation earlier. If you have 6.x please use 6.4.0 version of
elasticsearch_dsl.

**Comment by bergerr** [comment]
Yep that would be it, homebrew only has up to version 6.4.2 so that's what I'm using. Thanks!
