### ISSUE TITLE
Publish new version of branch 2.x to PyPI

### ISSUE THREAD

**Issue by d2207197** [elastic/elasticsearch-dsl-py#1179]
The latest version of branch 2.x in PyPI is 2.2.0 which was uploaded on Nov 4, 2016.
However, after Nov 4, 2016, there were three more commits for fixing bugs in branch 2.x. 

I just encountered one of them (https://github.com/elastic/elasticsearch-dsl-py/commit/a455fdd51a8cfa9f4b9ce7733f7a91b5e5d41ca1).

Please publish new version of branch 2.x to PyPI.

**Comment by sethmlarson** [comment]
2.x is no longer supported, if desired you can install from github directory like so:

`$ python -m pip install git+https://github.com/elastic/elasticsearch-dsl-py@2.x`
