### ISSUE TITLE
Best way to represent a multidimensional array

### ISSUE THREAD

**Issue by rkomorn** [elastic/elasticsearch-dsl-py#1180]
I'm storing a list of X,Y coordinates as a field in a document and I'm trying to find the best way to use the DSL to do it. It's worth noting that I'm not particularly interested in being able to search on these X,Y coordinates, so I'm not very concerned about the arrays getting flattened as long as my source reflects what I want.

I looked at https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html and my takeaway was that there isn't really a "native" way to prescriptively represent arrays in ES, so I tried the most naive approach:

```
class My2dDoc(Document):
    my_2d_float = Float()
```

That handles a single-value float as expected, and handles a list of float also as expected (returning a `<class 'elasticsearch_dsl.utils.AttrList'>` type). Any attempt to use a 2D list, however, returns a `TypeError: float() argument must be a string or a number, not 'list'` error. This is all in line with what I expect from the bits of googling I've been doing.

My solution was to store the coordinates as a raw Object, but that has basically forced me to add a layer in my data model that feels like it will be mistake-confusion prone:
```
class My2dDoc(Document):
    my_2d_float = Object()
```
but since my object is a dictionary, I end up with something like:
```
my_doc = My2dDoc()
my_doc.my_2d_float = Object({"2d_float": [[0.1, 2.3], [4.5, 6.7]]}
```
That stores my data properly, but it feels kludgy. Instead of accessing `my_doc.my_2d_float`, I end up needing to access `my_doc.my_2d_float["2d_float"]`. If anything, for anyone other than me looking at the code, it at least raises an eyebrow.

I could conceivably just look at my object's source, but I'm using `dynamic = MetaField("strict")` because I do want to make sure that the documents I index are properly formatted (and I'd rather use native DSL ways to do so than add my own layer of validation around the objects).

One thing I did consider was to create an InnerDoc, something like:
```
class MyXYPoint(InnerDoc):
    x = Float()
    y = Float()
```
and then just having `my_2d_float = Object(MyXYPoint)`, and allow that to be a list. It seems a little cumbersome, but that actually kind of seems like the best solution? The "cumbersome" part is basically needing to materialize a list of MyXYPoint objects (eg: `my_doc.my_2d_float = [MyXYPoint(x, y) for x, y in my_list_of_xy_points]` instead of `my_doc.my_2d_float = my_list_of_xy_points`).

**Comment by HonzaKral** [comment]
If you are not interested in searching through those fields I would suggest not indexing the field at all and then just leave whatever dicts in that field and it will be returned to you unchanged:

```python
from elasticsearch_dsl import Document, Object, connections
connections.create_connection()

class D(Document):
    points = Object(enabled=False, multi=True)
    class Index:
        name = 'i'

D.init()
D(_id=42, points=[{"x": 12, "y": 42}]).save()
D.get(id=42).points
```

The "proper" way to index it assuming you want to query it would be to use the `MyXYPoint` inside a `Nested` field.

Another alternative, the most flexible, is to turn off dynamic mappings and then unknown fields will get ignored:
```python
from elasticsearch_dsl import Document, connections, MetaField
connections.create_connection()

class D(Document):
    class Index:
        name = 'i'
    class Meta:
        dynamic = MetaField(False)
D.init()
D(_id=42, points=[[1, 2], [3, 4]]).save()
D.get(42).points
```

You can combine the two approaches by having `dynamic` set to false on an `Object` field and then have your `points` values on that field.

Hope this helps!

**Comment by rkomorn** [comment]
Thanks. I think using Nested field would end up costing me a lot of document IDs. My understanding is that each XY point would then count towards Lucene's max of ~2B per shard. Given that I'm storing 16+ points per document, that feels like conceding a lot of "space" (ie: available IDs).

Then again, maybe I shouldn't be so concerned. My shards may not be so manageable with 2B "full" documents anyway.

**Comment by HonzaKral** [comment]
Yes, nested will be counted as documents towards the 2B limit in a shard. But it is also the only way to search for things like "x coordinate is 12 and y is between 40 and 47" - without nested you'd be able to craft a query like that but it would do a different thing - "one of the x coordinates is 12 and one y coordinate is between 40 and 47, but not necessarily in the same point".
