### ISSUE TITLE
Breaking change on Date type between 6.3.1 to 6.4.0?

### ISSUE THREAD

**Issue by di** [elastic/elasticsearch-dsl-py#1181]
Over at https://github.com/pypa/warehouse/issues/5796 we're seeing a breaking change between 6.3.1 to 6.4.0, where a `Document` with a `Date` field is now a `str` in the result when it used to be a `datetime.datetime`.

It also seems like we're not getting the actual `Document` subclass we defined anymore, and instead we're getting a `elasticsearch_dsl.response.hit.Hit` instance instead.

6.3.1:
```
>>> item
Project(index='development-c915f430bb', doc_type='doc', id='pyfilemaker2')
>>> type(item)
<class 'warehouse.packaging.search.Project'>
>>> item.created
2018-11-20 20:23:48.581347
>>> type(item.created)
<class 'datetime.datetime'>
```

6.4.0:
```
>>> item
<Hit(development-c915f430bb/doc/pyfilemaker2): {'name': 'pyfilemaker2', 'normalized_name': 'pyfilemaker2', ...}>
>>> type(item)
<class 'elasticsearch_dsl.response.hit.Hit'>
>>> item.created
2018-11-20T20:23:48.581347
>>> type(item.created)
<class 'str'>
```

Is this expected? I see this line in the changelog:

> Do not change data in place when (de)serializing

Is it related? Also, @HonzaKral are you still at PyCon?

**Comment by HonzaKral** [comment]
This should not be related to the change you mention in the changelog but I cannot find any likely suspect. Can you please share the code responsible for creating the `Search` request?

Unfortunately I am not at PyCon any more so I cannot help in person

**Comment by di** [comment]
We're not using `Search`, we're using `Q`. Our query is a bit complicated due to supporting pagination, but it starts here:

https://github.com/pypa/warehouse/blob/6cbaf8407b371e39defd9654b6c540e468d148a2/warehouse/views.py#L419-L442

More here:

https://github.com/pypa/warehouse/blob/6cbaf8407b371e39defd9654b6c540e468d148a2/warehouse/views.py#L252-L359

**Comment by HonzaKral** [comment]
The problem was related to the `Document` not having a proper `Index.name` defined (see https://github.com/pypa/warehouse/pull/5814). Closing this issue.

**Comment by m3talstorm** [comment]
Just lost a few hours on this as well :(
