### ISSUE TITLE
How to use track_total_hits ?

### ISSUE THREAD

**Issue by RaphaelGillet** [elastic/elasticsearch-dsl-py#1183]
The `track_total_hits` is in ES 7, and so is in this lib doc, but I can’t figure out to use it

    Search(track_total_hit=True)

Throws : `Super(Search,self).__init__(**kwargs)`  got en unexpected keyword 

I think it’s because the super init has no kwargs and only 3 required param but how to use it so ?

**Comment by RaphaelGillet** [comment]
Ow I think I get it, I brain myself between elastic and elastic-dsl docs, it's in the basic one that track_total_hit is implemented, I'll try it tomorrow ^^

**Comment by HonzaKral** [comment]
the proper solution is:
```python
s = Search()
s = s.extra(track_total_hits=True)
```

Hope this helps!

**Comment by miff2000** [comment]
This should really be mentioned [in the docs here](https://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html?highlight=pagination#pagination). We spend much too much time wondering why we were only getting a max 10,000 hits

**Comment by sethmlarson** [comment]
@miff2000 I would accept a PR documenting this.

**Comment by miff2000** [comment]
I've put in the PR mentioned above. I added under the Hits section instead as it's the hit total that's affected by it
