### ISSUE TITLE
Allow specifying "order" in IndexTemplate class

### ISSUE THREAD

**Issue by dan-blanchard** [elastic/elasticsearch-dsl-py#1186]
Currently there does not appear to be a way to use the DSL to specify the `order` parameter when an `IndexTemplate` is saved, so if you're using hierarchical templates, you've got to save it as a dict and write it to ES outside of the DSL.

**Comment by HonzaKral** [comment]
Thank you for catching that, support for `order` has been added and will be part of the next release!
