### ISSUE TITLE
Extend function not implemented for AttrList

### ISSUE THREAD

**Issue by passwordleak** [elastic/elasticsearch-dsl-py#1187]
Normally, lists can be concatenated using the extend function, however, I get a null when I try to extend a AttrList with a regular list. How else would I concatenate an AttrList and a list without manually implementing it?

**Comment by passwordleak** [comment]
Found a way to do this using itertools.chain

**Comment by HonzaKral** [comment]
Where do you get `null`? I just tried this and it works as expected:

```python
from elasticsearch_dsl.utils import AttrList
l = AttrList([])
l.extend([1, 2, 3])
```
Could you please share the code that is failing for you? Thanks!

**Comment by passwordleak** [comment]
I think it's because the elements contain dots because they're filenames? Or maybe I'm just doing something weird. 
```
b = ["a.txt","b.txt"]
results = s.execute()
for result in results:
    a2 = result.a.extend(b)
    result.update(a=a2)
```
