### ISSUE TITLE
The completion.py example does not work with ES 7

### ISSUE THREAD

**Issue by codingforpleasure** [elastic/elasticsearch-dsl-py#1191]
Mapping types has been removed in ES 7,
therefore the code example in **completion.py** fails.
Can anybody suggest a solution?

Thank you in advance

**Comment by ArtemBernatskyy** [comment]
![image](https://user-images.githubusercontent.com/13070119/57761339-faeeb300-7705-11e9-80d4-96666c11846c.png)

Are you sure you are using the correct one ?

**Comment by codingforpleasure** [comment]
my mistake!! thank you
