### ISSUE TITLE
I don't find moving function (moving_fn). Is it supported?

### ISSUE THREAD

**Issue by wtwong316** [elastic/elasticsearch-dsl-py#1195]
According to the Elasticsearch reference (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-movavg-aggregation.html), Moving Average was deprecated in 6.4.0. The Moving Average aggregation has been deprecated in favor of the more general Moving Function Aggregation. The new Moving Function aggregation provides all the same functionality as the Moving Average aggregation.

I don't find it in the file. Is it supported?

**Comment by HonzaKral** [comment]
Thank you for the report, it was not supported. I added it to the code and it will be part of the next release. In the meantime you can work around the problem by specifying the class in your own code:
```python
from elasticsearch.aggs import Pipeline
class MovingFn(Pipeline):
    name = 'moving_fn'
```

That should be all that is needed.

**Comment by wtwong316** [comment]
Thanks HonzaKral.
Wai Tak.
