### ISSUE TITLE
List properties class

### ISSUE THREAD

**Issue by tombka** [elastic/elasticsearch-dsl-py#1196]
Hi,
I would like to know if there is a way to list the properties/attributes of my Document/InnerDoc classes ?
I already tried \__dict_\_ and dir(myObj) but the fields returned are not what i'm looking for...

**Comment by HonzaKral** [comment]
Hi, unfortunately I am not sure what you are looking for. Doing a `dir(myObj)` lists all the fields for me. What would be the expected output that you'd like to see?

**Comment by tombka** [comment]
I mean if i have an innerDoc with a name and a surname attributes they dont appear in my dir(obj)Le 20 mai 2019 19:58, Honza Král <notifications@github.com> a écrit :Hi, unfortunately I am not sure what you are looking for. Doing a dir(myObj) lists all the fields for me. What would be the expected output that you'd like to see?

**Comment by HonzaKral** [comment]
I cannot replicate that as I can see all my attributes in the `dir` function:
```python
from elasticsearch_dsl import Document, Text, InnerDoc, Nested
class FileDiff(InnerDoc):
        filename = Text(analyzer=a)
        patch = Text()
class FileDiff(InnerDoc):
    filename = Text()
    patch = Text()
class Commit(Document):
    file_diffs = Nested(FileDiff)
    
c = Commit(file_diffs=[FileDiff(filename='f', patch='abcdef')])
dir(c) == ['file_diffs']
dir(c.file_diffs[0]) == ['filename', 'patch']
```

Please provide a sample of code that does not work for you. Thanks!

**Comment by tombka** [comment]
Seems weird, I do this asap unfortunately im not able to provide you a sample atm give you one tomorrow morning.Le 20 mai 2019 20:44, Honza Král <notifications@github.com> a écrit :I cannot replicate that as I can see all my attributes in the dir function:
from elasticsearch_dsl import Document, Text, InnerDoc, Nested
class FileDiff(InnerDoc):
        filename = Text(analyzer=a)
        patch = Text()
class FileDiff(InnerDoc):
    filename = Text()
    patch = Text()
class Commit(Document):
    file_diffs = Nested(FileDiff)
    
c = Commit(file_diffs=[FileDiff(filename='f', patch='abcdef')])
dir(c) == ['file_diffs']
dir(c.file_diffs[0]) == ['filename', 'patch']
Please provide a sample of code that does not work for you. Thanks!

**Comment by tombka** [comment]
Ok so after I just checked my code and as you said i can list my attributes if i initialize my attributes with the constructor eg : FileDiff(filename='f', patch'abcdef'), but I try to use default constructor like : FileDiff() my dir result is empty.

class Data (Document):
    base = Object(BaseDocument)
    raw = Object(DataCrawl)
    processed = Object(DataTraitees)
    analyzed = Object(DataAnalysees)

d = Data(base=None, raw=raw, processed=None, analyzed=None)
d2 = Data()
print(dir(d)) --- Output : ['analyzed', 'base', 'processed', 'raw']
print(dir(d2)) --- Output : []

**Comment by HonzaKral** [comment]
So the `dir` shows you the properties are defined on that particular document, which is as expected.

You can always retrieve the defined mappings by accessing the mappings in `_doc_type.mappings` where you can iterate on the field. Does this work for your use case?

**Comment by tombka** [comment]
This is exactly what i was looking for !!!
Thanks a lot !
This issue is solved ! 👍
