### ISSUE TITLE
Terms query with boost

### ISSUE THREAD

**Issue by RadJamesway** [elastic/elasticsearch-dsl-py#1199]
using 7.0.0

How do you implement this?  In this case the value "user" is arbitrary and could be any string.  I tried using `Q('term', Q('user', value="Kimchy", boost=1.0))`  But that doesn't seem correct.
```
GET /_search
{
    "query": {
        "term": {
            "user": {
                "value": "Kimchy",
                "boost": 1.0
            }
        }
    }
}
```
Reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html

**Comment by RadJamesway** [comment]
Looks like you can `query.Term(contact_emails__raw={'value': name, 'boost': 1})`
or you can convert that into a dict and unpack it.

**Comment by HonzaKral** [comment]
exactly, all `kwargs` are converted to keys in the json so the approach you described will work.
