### ISSUE TITLE
[Question(s)] proper way add meta attributes in subclass of DocType  

### ISSUE THREAD

**Issue by jxstanford** [elastic/elasticsearch-dsl-py#120]
I read through issue #114 and I think this is similar, but perhaps not exactly the same theme.  As background, I've been writing a library that combines functionality from this project and Django Rest Framework.  I've subclassed DocType to create a DailyIndexDocType class that allows someone to specify an index prefix.  Searching will occur against all indices with that prefix, and saving will go to the most recent one.

Happy to work up a pull request for the related code if you're interested.    

One of the things I didn't quite get right was how to add attributes to the Meta class, and access them in further subclasses of DailyIndexDocType.  I eventually ended up subclassing DocTypeMeta and adding additional attributes there, but it exhibits some behavior that seems strange to me.  Here's some example code:

```python
class DailyIndexDocTypeMeta(DocTypeMeta):
    """Metaclass for DailyIndexDocType"""

    def __new__(mcs, name, bases, attrs):
        """Based on DocTypeMeta, filters attrs in place."""

        attrs['_doc_type'] = DocTypeOptions(name, bases, attrs)
        attrs['_index_prefix'] = DocTypeOptions(name, bases, attrs)
        attrs['default_sort'] = DocTypeOptions(name,bases, attrs)
        return super(DailyIndexDocTypeMeta, mcs).__new__(mcs, name, bases,
                                                         attrs)

@add_metaclass(DailyIndexDocTypeMeta)
class DailyIndexDocType(DocType):
    """A model that searches a set of daily indices."""

    class Meta:
        doc_type = 'syslog'
        index_prefix = 'logstash-'
        default_sort = '@-timestamp'
....

class LogData(DailyIndexDocType):
    """Logstash log entry model (intended to be read-only)."""

    class Meta:
        doc_type = 'syslog'
```

Finally, a concrete questions...

I sort of expected to be able to set and reference LogData.Meta.index_prefix.  Is that a realistic expectation, or did I just plain get that wrong :-) ?

When I instantiate LogData, I can see the attributes, but they return values for doc_type.  So, LogData._doc_type.name and LogData.default_sort.name return 'log_data' .  That's probably just  a type problem on my declaration of default_sort, but when I set it to None, I can't override it in the subclass.

Happy to clarify anything, and to work with you to get this incorporated if it aligns with the project goals.

Regards,
John

I can

**Comment by HonzaKral** [comment]
Hi John,
currently the `class Meta` is used only to capture some information and feed it into `DocTypeOptions` by `DocTypeMeta`, so there isn't any support for defining custom things there.

I am just wondering why you are doing this - you can define the `index` as `'logstash-*'` and in the document's `save()` method just supply the index to `super().save()` explicitly. That should be enough. Obviously `.get()` won't work without supplying a value for index either, but you can again just override that.

I don't understand what's is the need for the extra values in `class Meta`.

hope this helps,
Honza

**Comment by jxstanford** [comment]
Thanks for the clarification.  I thought I had tried sending a wildcard for the index, but apparently not.  I’ll give it a try!

John

jxstanford@gmail.com
@jxstanford

**Comment by HonzaKral** [comment]
I assume this was resolved, closing.

Please feel free to reopen if the solution didn't work. Thanks

**Comment by jxstanford** [comment]
Yes, all set.  Thanks...

John
