### ISSUE TITLE
Is there a way to find all available fields in an index?

### ISSUE THREAD

**Issue by jocech99** [elastic/elasticsearch-dsl-py#1200]
This might be a basic question, sorry about that, could not find other info about this.  Our indices contain a pretty large variability in the fields present in an index.  Unfortunately, this causes problem when trying to manage this dataset downstream.
So my question is about a query returning all available fields, as shown in kibana.  It seems that elasticsearch allows this through the GET mapping API (https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html).  How would  you go about it with elasticsearch_dsl?
Thanks!

**Comment by shivam05011996** [comment]
@jocech99 Assuming you have already defined an Index class you can obtain the mapping in the following way - 

```
YourIndexClass._index.get_mapping()
```

For example -
DatasetIndex._index.get_mapping()

```
{
  "shivam-pre-dev.kwikui.com-view-index": {
    "mappings": {
      "doc": {
        "properties": {
          "logo_color": {
            "type": "text"
          },
          "dt_update": {
            "type": "date"
          },
          "description": {
            "search_analyzer": "standard_token_analyzer",
            "analyzer": "ngram_token_analyser",
            "type": "text"
          },
          "dt_updated": {
            "type": "date"
          },
          "logo": {
            "type": "text"
          },
          "slug": {
            "type": "text"
          },
          "title": {
            "search_analyzer": "standard_token_analyzer",
            "analyzer": "ngram_token_analyser",
            "type": "text"
          },
          "accessibility": {
            "type": "text"
          },
          "owner_id": {
            "type": "text"
          }
        }
      }
    }
  }
}

```

**Comment by shivam05011996** [comment]
@jocech99 Assuming you have already defined an Index class you can obtain the mapping in the following way - 

```
YourIndexClass._index.get_mapping()
```

For example -
DatasetIndex._index.get_mapping()

```
{
  "shivam-dataset-index": {
    "mappings": {
      "doc": {
        "properties": {
          "logo_color": {
            "type": "text"
          },
          "dt_update": {
            "type": "date"
          },
          "description": {
            "search_analyzer": "standard_token_analyzer",
            "analyzer": "ngram_token_analyser",
            "type": "text"
          },
          "dt_updated": {
            "type": "date"
          },
          "logo": {
            "type": "text"
          },
          "slug": {
            "type": "text"
          },
          "title": {
            "search_analyzer": "standard_token_analyzer",
            "analyzer": "ngram_token_analyser",
            "type": "text"
          },
          "accessibility": {
            "type": "text"
          },
          "owner_id": {
            "type": "text"
          }
        }
      }
    }
  }
}

```

**Comment by jocech99** [comment]
Thanks for pointing me in the right direction so quickly!  I will play with this.

**Comment by shivam05011996** [comment]
There is a lot to play with the Index class. Enjoy.

**Comment by HonzaKral** [comment]
`get_mapping` is indeed exposed via the `Index` class, you can also use `Index.load_mappings` to fetch the mappings which can then be explored in -dsl format in `._mapping` attribute of the `Index` instance.

Hope this helps!
