### ISSUE TITLE
AttributeError: 'RoomBooking' object has no attribute 'lower'

### ISSUE THREAD

**Issue by jasonqiao36** [elastic/elasticsearch-dsl-py#1201]
https://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#data-types

```python
rb.lower # datetime(2018, 11, 17, 9, 0, 0), True
rb.upper # datetime(2018, 11, 17, 10, 0, 0), False
```
will raise `AttributeError: 'RoomBooking' object has no attribute 'lower'`.
It seems that we can use `rb.dates.lower`

**Comment by HonzaKral** [comment]
thanks for the catch!
