### ISSUE TITLE
How to use ‘slices’ in a delete query ?

### ISSUE THREAD

**Issue by RaphaelGillet** [elastic/elasticsearch-dsl-py#1202]
With elastic-py I can do :
   
    delete_by_query(idxname, asearch.to_dict(), slices=4)

But how could I do it directly with Search from elastic-dsl ? I tried with `extra` method but not working 

    asearch.extra(slices=4).delete()

**Comment by HonzaKral** [comment]
`extra` is for adding additional keys to the `body` of the request. If you want to add additional parameters you should use `params`:
```python
asearch.params(slices=4).delete()
```

Hope this helps!
