### ISSUE TITLE
doc_type not being set

### ISSUE THREAD

**Issue by danielrc14** [elastic/elasticsearch-dsl-py#1204]
Hey, I'm using version 7.0.0 and I have the following document:

```
class EventDocument(Document):
    id = Integer()
    name = Text()
    start_date = Date()
    end_date = Date()
    free = Boolean()
    commune = Text()
    region = Text()
    main_discipline = Text()
    disciplines = Nested(
        properties={
            'name': Text(),
        }
    )
    types = Nested(
        properties={
            'name': Text(),
        }
    )
    image = Text()

    class Index:
        name = 'searches'
        doc_type = 'event'

    class Meta:
        doc_type = 'event'
```
I set `doc_type` in both the `Index` and `Meta` classes as it says on the documentation (https://elasticsearch-dsl.readthedocs.io/en/7.0.0/persistence.html#class-index-options), but when I make a search the hits have `_doc` as their type.

Thanks.

**Comment by danielrc14** [comment]
For now I changed my elasticsearch version to 6.8.0, and my elasticsearch-dsl version to 6.4.0, and it works.

**Comment by HonzaKral** [comment]
Document types are not supported in Elasticsearch 7.x and so support for setting it has been removed from the library. Thanks for the heads up, I removed the mention from the docs.
