### ISSUE TITLE
Can't add filter to nested aggregation

### ISSUE THREAD

**Issue by extesy** [elastic/elasticsearch-dsl-py#121]
I'm trying to do something like this:

    request.aggs.bucket('project', 'terms', field='project.name', min_doc_count=5, size=10, shard_size=100) \
                .bucket('submitter', 'percentiles', field='project.age', percents=[50]) \
                .filter('range', last_updated={'gte': '2015-01-01'})

The code above doesn't work because Bucket doesn't have filter method. I need to construct this query:

    {
        "aggs": {
            "project": {
                "terms": {
                    "field": "project.name",
                    "min_doc_count": 5,
                    "size": 10,
                    "shard_size": 100,
                    "order": {
                        "filtered>submitter.50": "asc"
                    }
                },
                "aggs": {
                    "filtered": {
                        "filter": {
                            "range": {
                                "last_updated": {
                                    "gte": "2015-01-01"
                                }
                            }
                        },
                        "aggs": {
                            "submitter": {
                                "percentiles": {
                                    "field": "project.age",
                                    "percents": [
                                        50
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
    }

How can I do this using dsl?

**Comment by HonzaKral** [comment]
You have to explicitly add a filter aggregation, which is a bucket aggregation. Note #117 that there might be some issues currently with it.

**Comment by extesy** [comment]
@HonzaKral Ok, I tried adding filter as aggregation but it generates incorrect nesting:

    request.aggs.bucket('project', 'terms', field='project.name', min_doc_count=5, size=10, shard_size=100, order={'filtered>submitter.50': 'asc'}) \
                .bucket('filtered', 'filter', range={'last_updated': {'gte': '2015-01-01'}}) \
                .bucket('submitter', 'percentiles', field='project.age', percents=[50])

This creates a request where filter has "aggs" under it, but it should have "aggs" on the same level. This is a wrong result that causes a parsing error from elasticsearch:

    'aggs': {
        'project': {
            'aggs': {
                'filtered': {
                    'filter': {
                        'aggs': {
                            'submitter': {
                                'percentiles': {
                                    'field': 'project.age',
                                    'percents': [50]
                                }
                            }
                        },
                        'range': {
                            'last_updated': {
                                'gte': '2015-01-01'
                            }
                        }
                    }
                }
            },
            'terms': {
                'field': 'project.name',
                'min_doc_count': 5,
                'order': {
                    'filtered>submitter.50': 'asc'
                },
                'shard_size': 100,
                'size': 10
            }
        }
    }

Is this the same issue as in #117?

**Comment by HonzaKral** [comment]
This have been fixed as #117
