### ISSUE TITLE
How can I override meta Index in Document

### ISSUE THREAD

**Issue by tombka** [elastic/elasticsearch-dsl-py#1210]
Hi,

Probably an easy problem to solve but i can't find a solution :

```python
class Data (Document):
    base = Object(BaseDocument)
    class Index:
        name = 'toto'
```
how can i change the index nameand sticking with this class Index (i have read the doc but the others alternatives don't match with my project)
```python
# override default index
post.meta.index = 'my-blog'
```
this one is not working for me

**Comment by AaronZhangL** [comment]
@tombka I have the same issue, Could you share your solution?
