### ISSUE TITLE
Deal with multiplexer token_filter

### ISSUE THREAD

**Issue by inkhey** [elastic/elasticsearch-dsl-py#1212]
Hello and thank of this useful program.

I just got a trouble because i want my edge_ngram_tokenizer to store full word as token too.
I found something interesting in elasticsearch documentation called multiplexer and that seems to do what i need : https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-multiplexer-tokenfilter.html

So i try this with elasticsearch-dsl-py : 
```
edge_ngram_token_filter = analysis.token_filter(
    "edge_ngram_filter", type="edge_ngram", min_ngram=2, max_gram=20
)
# INFO - G.M - 2019-06-24 - Store 
multiplexed_edge_ngram_token_filter = analysis.token_filter(
    'multiplexed_edge_ngram_token_filter', type="multiplexer", filters=[edge_ngram_token_filter]
)
edge_ngram_folding = analyzer(
    "edge_ngram_folding",
    tokenizer="standard",
    filter=["lowercase", "asciifolding", multiplexed_edge_ngram_token_filter],

class IndexedContent(Document):
    """
    ElasticSearch Content Models.
    Used for index creation.
    """

    content_id = Integer()
    label = Text(analyzer=edge_ngram_folding, search_analyzer=folding)
```

Problem is that thats doesn't work.
I get this kind of error : 
`
TypeError: Unable to serialize CustomTokenFilter(max_gram=20, min_ngram=2) (type: <class 'elasticsearch_dsl.analysis.CustomTokenFilter'>)
`
That's logical in fact, as `multiplexed_edge_ngram_token_filter` doesn't know what to do with `edge_ngram_token_filter`, support for object is done in analyzer not in token_filter.

So i try to use name but it also doesn't work as named `edge_ngram_token_filter` doesn't exist when we call to create `multiplexed_edge_ngram_token_filter`.

One solution will be creating this by hand with elasticsearch base api but that's not really nice. is it possible to add support for such thing or does it exist something to easily use edge_ngram_token_filter and force him to be created in elasticsearch before any mapping ?

**Comment by HonzaKral** [comment]
Thank you for raising this issue, this should now be fixed in `master` via d77ee3b
