### ISSUE TITLE
Add configuration support to pre_tags and post_tags for highlighting

### ISSUE THREAD

**Issue by codingforpleasure** [elastic/elasticsearch-dsl-py#1216]
I'd like to configure the pre_tags and post_tags in elasticsearch_dsl, for example:

> GET /my_index/my_doc_search
{
    "query": {
        "multi_match" : {
            "query" : "example_name",
            "fields" : ["name"]
        }
    },
    "highlight":{
		"pre_tags" : ["<strong>"],
		"post_tags" : ["</strong>"],
		"fields":{
			"name":{}
		  }
    }
}

But I have searched and didn't find this capability.

**Comment by HonzaKral** [comment]
Just like you specify `fragment_size` you can also specify any other parameters to be specified in that section, see https://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#highlighting for details.
