### ISSUE TITLE
Get status or progress update over execution of large sets

### ISSUE THREAD

**Issue by bakztfuture** [elastic/elasticsearch-dsl-py#1219]
Is there a way to see the "status" or "progress bar/percentage" of a query over a large set?

Current setup:
```python
    s = s[0:100]

    # start the search operation
    response = s.execute()
```

For large sets (10K+ rows), I plan on updating the user in realtime as it's compiling the data from ES about how far the job is done.

Ideally, I'm looking for something which can tell me how many results have been compiled so far so that I can calculate a percentage about how much of the compilation process is left (%).

Thanks would appreciate any help or feedback

**Comment by HonzaKral** [comment]
If you want to get back a lot of documents from elasticsearch you should use the `scan` endpoint/helper on the `Search` object. This will stream data from elasticsearch in batches and return to you an iterator. That way you can report in real time how many documents you have received/processed, just keep in mind that while the iterator is returning individual documents the documents are returned from the server in batches based on the `size` parameter, by default `1000` which will be retrieved from every shard.

Hope this helps!
