### ISSUE TITLE
Where to define the analyzers? which you would define in body.settings

### ISSUE THREAD

**Issue by ideallical** [elastic/elasticsearch-dsl-py#122]
Hi,
I'm slowly moving from haystrack to elasticsearch-dsl. However, I haven't found a way to add custom analysers with es-dsl.

elasticsearch_dsl.Doctype.init() creates the mapping directly, hence it breaks, because my mapping refers to analysers that haven't been added to the index settings.

I can create the index and put the settings like so:

    from elasticsearch import Elasticsearch 
    
    es = Elasticsearch()
    es.indices.create(index='myindex', body=dict(settings=my_custom_settings, ignore=400))
    # now load the mapping (SearchArticle is subclass from elasticsearch_dsl.DocType)
    SearchArticle.init()

But if I want to create the mapping after the creation of the index with SearchArticle.init(), it breaks, because the index already exists.

Is it even possible with this library to setup your index with custom settings (analysers)?

**Comment by ideallical** [comment]
Found it, I misplaced ignore=400 :)

Correct way:

    from elasticsearch import Elasticsearch 
    
    es = Elasticsearch()
    es.indices.create(index='myindex', body=dict(settings=my_custom_settings), ignore=400)
    SearchArticle.init()

**Comment by HonzaKral** [comment]
There is also a new feature (not yet 100% complete) that allows you to create analyzers via the dsl - see https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_integration/test_index.py#L3-L5 for example. There is still no docs though, will work on it, along with more complete examples, next week.

thanks
