### ISSUE TITLE
SQL Support.

### ISSUE THREAD

**Issue by G-K-Patel** [elastic/elasticsearch-dsl-py#1225]
Hi dsl team, 

Is there any plan to support SQL queries, 

https://www.elastic.co/guide/en/elasticsearch/reference/6.8/xpack-sql.html

that would be a nice addition to the library. 

Thanks for your reply and consideration.

**Comment by HonzaKral** [comment]
Hi, I am sorry but this is out of scope of this library.

There are already plenty tools for python and SQL that you can use. More importantly this library is to allow people to use the full power of Elasticsearch and its DSL which is more powerful than the SQL while also very dissimilar not allowing for much shared functionality.

**Comment by G-K-Patel** [comment]
Is there a possibility to normalize ES response into a CSV ? 

This logic already exists in Kibana. For example, in each Visualization, under Inspect, one can find a tab where the Response JSON is converted into a CSV file, 

![image](https://user-images.githubusercontent.com/42677721/62612712-3b765b00-b908-11e9-8bbd-e5d87abe387d.png)

Is it possible to have the similar logic implemented here? i.e. converting JSON output into other easily digestable formats. 

Thanks for your reply and consideration.

**Comment by HonzaKral** [comment]
You can use the `scan()` helper on a `Search` object or the low level helper (0) that will stream hits back from ES that you can easily plug into `csv.DictWriter` or some other tool.

If you are interested in capturing aggregation results across large sets of documents have a look at the composite agg example at (1)

0 - https://elasticsearch-py.readthedocs.io/en/master/helpers.html#scan
1 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/composite_agg.py

**Comment by jonwhittlestone** [comment]
Hi - slightly off topic, but related to SQL

Does this package support reading/parsing a JSON encoded query, into a `dict`.

My use case is that I'd like a way to convert the ES query to a key:value (for eventual use in SQL)

So the below JSON would get turned into python: Eg.

```

{
  "query": { "match": { "address": "mill lane" } }
}

```
becomes
```
$ python
>>> print(matches['address'] )
>>> "mill lane"
```
