### ISSUE TITLE
how to apply multi search on Nested Object

### ISSUE THREAD

**Issue by unifiedsaad** [elastic/elasticsearch-dsl-py#1226]
i am trying to decrease redudancy in my code
`booking_client_email = BookingDocument.search().query("nested", path='client',
                                                          query=Q("match", client__email=query))
    booking_client_name = BookingDocument.search().query("nested", path='client',
                                                         query=Q("match", client__name=query))
    booking_client_contact = BookingDocument.search().query("nested", path='client',
                                                            query=Q("match", client__contact=query))`

When i try to apply multi search here, like we apply for normal columns, it gives error

**Comment by HonzaKral** [comment]
Can you please give an example of the multi search, the error you are getting, and generally what is it that you want the code to do? There are many valid options that would result in different code.

**Comment by HonzaKral** [comment]
Closing this issue as there is no additional info. Feel free to reopen with the information needed, thanks!

**Comment by unifiedsaad** [comment]
well, i want to search in nested fields also with the present model attribute, all in one query.
For Example, i have a model which have id, name, company, a number where the company is a relational attribute. I want to search name, number and company name also
