### ISSUE TITLE
failed to find geopoint field

### ISSUE THREAD

**Issue by prayag1740** [elastic/elasticsearch-dsl-py#1229]
I have seperate fields of latitude and longitude (lat and lng) in my django model. I want to use GeoPoint field but getting **error failed to find geopoint field.**

In my models file , I have added function:
`@property
    def type_to_string(self):
        return {
            'lat': self.lat,
            'lon': self.lng
        }`

Created GeoPointField in documents.py
loc1 = fields.GeoPointField(attr='type_to_string')

Now when I run the query 
s1 = LocationDocument.search().filter( 'geo_distance', distance='1000m', loc1={"lat": "40", "lon": "-74"} )    
s1 = s1.execute()

I get error here. Any help where I am going wrong.

**Comment by HonzaKral** [comment]
What kind of error are you getting? Also are you sure you are using just `elasticsearch-dsl`? It looks like you might be using `django-elasticsarch-dsl` which can behave a little differently and you should probably ask your questions there then.

**Comment by prayag1740** [comment]
Yeah , I am actually using django-elasticsearch-dsl.

**Comment by prayag1740** [comment]
Can this type of error rectified my elasticsearch-dsl ?

**Comment by HonzaKral** [comment]
That is impossible to say without knowing the error, can you please share the whole error you are getting? Thank you

**Comment by prayag1740** [comment]
RequestError: RequestError(400, 'search_phase_execution_exception', 'failed to find geo_point field [loc1]')

**Comment by HonzaKral** [comment]
This looks like your index wasn't created with proper mappings in place, you need to explicitly create the index before indexing any data into it.

In elasticsearch dsl you do it by calling the `init()` classmethod on your `Document` subclass.

Hope this helps!
