### ISSUE TITLE
Update Document.save documentation (<= 6.4.0)

### ISSUE THREAD

**Issue by nicolascarbone** [elastic/elasticsearch-dsl-py#1230]
save method can also update a document passing in `id` as a keyword, just like this:
`my_document.save(id='an-id-here')`, this `id` will be passed in to `es.index` here https://github.com/elastic/elasticsearch-dsl-py/blob/6.4.0/elasticsearch_dsl/document.py#L441 and `elasticsearch-py` will handle it as a `POST` here https://github.com/elastic/elasticsearch-py/commit/8e92b857bcb91fcfcb2c37f8525c39d434406620#diff-2696ade2db2bc9506566dc21df9e00e8L358

**Comment by miguelgrinberg** [comment]
I'm going to close this as I feel it might be out of date after so long has passed. The `Document.save()` method will create or update documents as necessary. For a new document, an `id` is autogenerated, or you can pass the `id` keyword argument in the call if you want. When updating a document the existing `id` is used.
