### ISSUE TITLE
How to use "must_not" ? 

### ISSUE THREAD

**Issue by Karamhaj1995** [elastic/elasticsearch-dsl-py#1231]
Hello, I am trying to create a task that match results from es by query "match" and "must_not", when I execute the task I get the following error message: 

> **DSL class `must_not` does not exist in query**

And here is my code:

`for key in self.query["must_not"]:
self.results = self.results.query('must_not', **{ key: self.query["must_not"][key] })`

As I understood I need to use it as a filter but there was no example that show the way to use.

any help please ?

**Comment by HonzaKral** [comment]
The easiest way is to use python's negate operator (`~`) if you want just the query or use the `exclude` method if you want to use it in a search:

```python
s = Search()
s =s.exclude('match', ...)
```

Hope this helps!

**Comment by Karamhaj1995** [comment]
Testing... I can say it is the right way
