### ISSUE TITLE
Convert to geopoint field in elasticsearch

### ISSUE THREAD

**Issue by prayag1740** [elastic/elasticsearch-dsl-py#1232]
I have lat and long fields in my django model and I want to use geopoint in elasticsearch. How can I convert my lat and long fields to geopoint .

**Comment by HonzaKral** [comment]
I am sorry, this issue is unrelated to this library as this is not the django integration. The problem you are facing is caused by the index not being properly created before populated. Please refer to the library you are using for proper procedure on creating an index. Thank you!
