### ISSUE TITLE
not_analyzed flag on a Text field not supported?

### ISSUE THREAD

**Issue by yarothetimble** [elastic/elasticsearch-dsl-py#1238]
I've been trying to create an Index with a `not_analyzed` flag, however failed to initialize this index. What am I doing wrong?:

```
from elasticsearch_dsl import Document, Index, Text

class TestIndex(Document):
    pk = Text(index="not_analyzed")

    class Index:
        name = "test"
```

and 

`TestIndex.init()`

gives this exception:
`line 181, in _raise_error\n    status_code, error_message, additional_info\nmapper_parsing_exception"`

**Comment by HonzaKral** [comment]
if you are interested in having a string field that is not analyzer used a `Keyword` instead of `Text` that is by default not analyzer and should be what you are looking for.

Hope this helps!
