### ISSUE TITLE
Duplicated results when using geo_distance with sorted results

### ISSUE THREAD

**Issue by bonjour-residences** [elastic/elasticsearch-dsl-py#1239]
I tried to get nearest records of longitude and latitude in my database. I tried first with the GeoDistance

```python
from elasticsearch_dsl.query import GeoDistance
from apps.residences.search_index import ResidenceFr

geo = GeoDistance(distance='10km', lat_lon={'lat': 45.6024258, 'lon': -73.7114946})
res = ResidenceFr()

search = res.search()
search = search.filter(geo)
for result in search.execute()
    print(result.name)
```
I get all results in the radius of 10 km, but I want to get results sorted by distance. 

I found a working example working from ElasticSearch json code.  

```json
{
   "query":{
      "bool":{
         "must":[
            {
               "geo_distance":{
                  "distance":"10km",
                  "lat_lon":{
                     "lat":45.6024258,
                     "lon":-73.7114946
                  }
               }
            }
         ]
      }
   },
   "sort":{
      "_geo_distance":{
         "lat_lon":"45.6024258,-73.7114946",
         "order":"asc"
      }
   }
}
```

I tried this code with the from_dict function, but when I get results each result are duplicated 4 times. I tried the same query with curl directly to the server, and it works without duplicated records. 

I would like to find a way to be able to get these works. I was using from_dict function because I save query in the database. But make it works properly from the package directly  is my first objective.

**Comment by HonzaKral** [comment]
Can you please share the code that you used to run the query, I cannot replicate the issue on my part. 

also just adding for completeness that the geo distance sorting can be accomplished by adding the following to your code:

```python
s = s.sort({
  "_geo_distance":{
    "lat_lon":"45.6024258,-73.7114946",
    "order":"asc"
  }
})
```

Hope this helps!

**Comment by bonjour-residences** [comment]
@HonzaKral, it works. But I need to save my queries to reuse it. I made my query. save dict and reuse it. 

```python
from elasticsearch_dsl.query import GeoDistance
from apps.residences.search_index import ResidenceFr

geo = GeoDistance(distance='10km', lat_lon={'lat': 45.6024258, 'lon': -73.7114946})
res = ResidenceFr()

search = res.search()
search = search.filter(geo)
search = search.sort({"_geo_distance":{"lat_lon":"45.6024258,-73.7114946","order":"asc"}})
for result in search.execute():
  print(result.name)
```

I get the right results

But if I do that

```python
search.to_dict()
{'query': {'bool': {'filter': [{'geo_distance': {'distance': '10km', 'lat_lon': {'lon': -73.7114946, 'lat': 45.6024258}}}]}}, 'sort': [{'_geo_distance': {'lat_lon': '45.6024258,-73.7114946', 'order': 'asc'}}]}
```

and I reuse it :
```python
from apps.residences.search_index import ResidenceFr
search = res.search()
search = search.from_dict({'query': {'bool': {'filter': [{'geo_distance': {'distance': '10km', 'lat_lon': {'lon': -73.7114946, 'lat': 45.6024258}}}]}}, 'sort': [{'_geo_distance': {'lat_lon': '45.6024258,-73.7114946', 'order': 'asc'}}]})
for result in search.execute():
  print(result.name)
```

All results appear four times.

**Comment by HonzaKral** [comment]
That seems to be a duplicate issue to https://github.com/elastic/elasticsearch-dsl-py/issues/1244 - `from_dict` is creating new `Search` object so that it searches all indices, not just those associated with `ResidenceFr`, could you verify that is it indeed so?

**Comment by bonjour-residences** [comment]
@HonzaKral it works with update_from_dict thanks.
