### ISSUE TITLE
Can't access my_doctype.meta anymore :(

### ISSUE THREAD

**Issue by njoannin** [elastic/elasticsearch-dsl-py#124]
I've just created a new virtualenv and loaded it up with my requirements.txt file.
In it, I list elasticsearch-dsl==0.0.4.dev0.

With my previous virtualenv (with 0.0.4.dev0 installed March 25th), I have no problems:

```
>>> from elasticsearch_dsl import DocType, String
>>> class Test(DocType):
...     test=String()
...     class Meta:
...         index="test"
... 
>>> t=Test(test="test")
>>> t
{'test': 'test'}
>>> t.meta
{}

```

But with the latest dev version I do have a problem:

```
>>> from elasticsearch_dsl import DocType, String
>>> class Test(DocType):
...    test=String()
...    class Meta:
...       index="test"
... 
>>> t=Test(test="test")
>>> t
{'test': 'test'}
>>> t.meta
Traceback (most recent call last):
  File "/Users/Nicolas/myproject/test/env/lib/python3.3/site-packages/elasticsearch_dsl/utils.py", line 103, in __getattr__
    return _wrap(self._d_[attr_name])
KeyError: 'meta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Nicolas/myproject/test/env/lib/python3.3/site-packages/elasticsearch_dsl/document.py", line 164, in __getattr__
    return super(DocType, self).__getattr__(name)
  File "/Users/Nicolas/myproject/test/env/lib/python3.3/site-packages/elasticsearch_dsl/utils.py", line 399, in __getattr__
    return super(ObjectBase, self).__getattr__(name)
  File "/Users/Nicolas/myproject/test/env/lib/python3.3/site-packages/elasticsearch_dsl/utils.py", line 106, in __getattr__
    '%r object has no attribute %r' % (self.__class__.__name__, attr_name))
AttributeError: 'Test' object has no attribute 'meta'
```

This doesn't prevent the object from saving to ES with this simple example. However, any code that accesses the meta attribute before saving will obviously fail, which is probably why I'm noticing the problem ;)

Anybody else having this problem?

**Comment by HonzaKral** [comment]
I cannot see to replicate it - I added a test for it in e7237ab2969cb2069f059d9af84ecfc2ef3c68dd and it works fine.

What version are you using exactly? Can you try upgrading to master? Thanks!

**Comment by njoannin** [comment]
Hmm, indeed, upgrading fixed it.
Not quite sure why the initial install (which I did just a few hours ago) didn't work out...
Sorry for the waste of time!
