### ISSUE TITLE
Parent aggregation missing

### ISSUE THREAD

**Issue by justinian336** [elastic/elasticsearch-dsl-py#1240]
The Parent bucket aggregation doesn't seem to be available in `aggs.py`, although the Children aggregation is. Any plan to add it?

**Comment by HonzaKral** [comment]
thank you for the heads up, added the aggregation. As a workaround you can add this to your code and then the `parent` aggregation will be available:

```python
from elasticsearch_dsl.aggs import Bucket
class Parent(Bucket):
    name = 'parent'
```

**Comment by justinian336** [comment]
Thanks for the fast fix!
