### ISSUE TITLE
I use the mapping example, but it error

### ISSUE THREAD

**Issue by Aimoy** [elastic/elasticsearch-dsl-py#1242]
```
class Article(Document):
    title = Text(analyzer='snowball', fields={'raw': Keyword()})
    body = Text(analyzer='snowball')
    tags = Keyword()
    published_from = Date()
    lines = Integer()

    class Index:
        name = 'blog'
        settings = {
          "number_of_shards": 2,
        }

    def save(self, ** kwargs):
        self.lines = len(self.body.split())
        return super(Article, self).save(** kwargs)

    def is_published(self):
        return datetime.now() > self.published_from
Article.init()
```
the error info:
```
elasticsearch.exceptions.RequestError: RequestError(400, u'mapper_parsing_exception', u'Root mapping definition has unsupported parameters:  [published_from : {type=date}] [body : {analyzer=snowball, type=text}] [lines : {type=integer}] [title : {analyzer=snowball, fields={raw={type=keyword}}, type=text}] [tags : {type=keyword}]')
```
 i don't konw why i can't use ,i don't modify anything with the example,  my python version = 2.7 and elasticsearch version =6.4.0, how should i modify?

**Comment by HonzaKral** [comment]
What version of the library are you using? It looks like you are using `elasticsearch-dsl` version 7 and above which does not work with elasticsearcg 6.x, you need to use the same major version.

**Comment by Aimoy** [comment]
> What version of the library are you using? It looks like you are using `elasticsearch-dsl` version 7 and above which does not work with elasticsearcg 6.x, you need to use the same major version.

May I ask another question?
I query one
