### ISSUE TITLE
from_dict method giving double the results as compared to the high level analogy of the same query

### ISSUE THREAD

**Issue by Shivendra2407** [elastic/elasticsearch-dsl-py#1244]
in my py file I have:

from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
client = Elasticsearch()

Please find below my iPython shell statements:

In [90]: s = Search(using=client, index='institutes')

In [91]: s = s.filter('match_phrase',country__uri='canada').filter("nested", path="institutecourse_set", query=Q("match_phrase", **{'institutecourse_set.stream.uri': 'sciences'}))

In [92]: di = s.to_dict()

In [93]: s1 = Search(using=client, index='institutes')

In [94]: s1 = s1.from_dict(di)

In [95]: s1.count()

**Out[95]: 84**

In [96]: s.count()

**Out[96]: 42**

The count 42 is correct as per the database from which I indexed the "institutes" data. Even if I construct the "di" dict independently :

di = {'query': {'bool': {'filter': [{'match_phrase': {'country.uri': 'canada'}}, {'nested': {'path': 'institutecourse_set', 'query': {'match_phrase': {'institutecourse_set.stream.uri': 'sciences'}}}}]}}}

it gives me same number of results(84) when I use it with s.from_dict(). Can you explain what is happening?

**Comment by HonzaKral** [comment]
`from_dict` is a class method that constructs a new `Search` object which is then not associated with any index so that is why you are getting more results - it is searching across all indices.

I will change the code to throw an exception in this case as it is confusing, thank you for raising the issue!

**Comment by Shivendra2407** [comment]
@HonzaKral Thanks so much for the reply.
Can you also tell me what can I do in this case, like I have to use a dictionary form of query (di object as in the question) to get my 42 results that match instead of 84.

**Comment by HonzaKral** [comment]
oh, sorry. There are two options: use `update_from_dict` instead of `from_dict` which will do exactly what you want. Or use `Search.fom_dict(di).index('institutes').using(client)` to (re)set the parameters on the new object.

Hope this helps!

**Comment by Shivendra2407** [comment]
@HonzaKral That worked like a charm! Thank you so much..
