### ISSUE TITLE
Support for rank_feature field/query for search

### ISSUE THREAD

**Issue by inkhey** [elastic/elasticsearch-dsl-py#1245]
It's will be nice to support properly rank_feature (and rank_features) field and query for search.
see https://www.elastic.co/guide/en/elasticsearch/reference/master/rank-features.html

Currently i use some small code to be able to handle them simply:

```
class RankFeatureFloat(Float):
    name = 'rank_feature'

class IndexedProducts(Document):
    product_rank = RankFeatureFloat()

class RankFeatureQuery(Query):
    name = 'rank_feature'

search = Search(...).query(...)
search.query = Q('bool', must=search.query, should=Q('rank_feature', field='product_rank', boost=2))
res = search.execute()
```

**Comment by HonzaKral** [comment]
implemented in 2c099d5

Thank you for raising the issue!
