### ISSUE TITLE
Similarity Module

### ISSUE THREAD

**Issue by khairul89** [elastic/elasticsearch-dsl-py#1249]
Hi,

I am sorry if this is not the correct place to ask this question.
I am using Python Elasticsearch DSL library and I will need to integrate it with Similarity Module in Elasticsearch.
 My question is do Elasticsearch DSL support the Elasticsearch Similarity Module such as BM25 and scripted similarity? I have tried to search any information regarding this but no avail. Really appreciate on the respond or any pointers given.

**Comment by HonzaKral** [comment]
Right now you can pass any configuration that is not supported directly, such as similarity, into your mappings and settings manually, to implement the first two examples from https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-similarity.html you can use the following code

```python
from elasticsearch_dsl import Document, Text

class MyDoc(Document):
    text_field = Text(similarity='my_similarity')
    class Index:
        settings = {
        "index" : {
            "similarity" : {
              "my_similarity" : {
                "type" : "DFR",
                "basic_model" : "g",
                "after_effect" : "l",
                "normalization" : "h2",
                "normalization.h2.c" : "3.0"
              }
            }
        }
    }
```

hope this helps!

**Comment by ilknurCakir** [comment]
Hi,

I want to do the same thing; changing default similarity in elasticsearch dsl. I tried the code above but it does not work. It gives parsing exception.

elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Unknown Similarity type [my_similarity] for field [keywords]')

Any idea what the issue might be here?
