### ISSUE TITLE
Marshmallow 3+ compatibility

### ISSUE THREAD

**Issue by nixjdm** [elastic/elasticsearch-dsl-py#1250]
Marshmallow version 3 and up rely on AttrDicts to be a little more dict-like. In particular, it relies on having the `.keys` and `.items` methods that behave in a similar way as the normal `dict` methods.

The following will reproduce the error, assuming up-to-date marshmallow (currently 3.2):

```python
from elasticsearch_dsl import Document, Nested, Integer
from marshmallow import Schema, fields

class TestModel(Document):
    i = Integer()
    n = Nested()

class TestModelSchema(Schema):
    i = fields.Integer()
    n = fields.List(fields.Dict(values=fields.Float(), keys=fields.Str()))

tm = TestModel(**{"i": 4, "n": [{"key": 0.05}]})
tms = TestModelSchema()
tms.dump(tm)
```

So far as I can tell this issue effects elasticsearch_dsl version 2.x and above, including master. To test down to version 2.x you'll need to modify the above to use `DocType` instead of `Document`.

I'll post a PR to fix this shortly.

**Comment by HonzaKral** [comment]
My question is why do you need marshmallow? You can define (de)serialization logic, as well as validation, on the `Document` itself.

I am afraid we cannot justify adding 2 methods and limiting the namespace to cooperate with a library that provides a functionality we already have baked in.

If you want to user `marshmallow` for other reasons all you have to do is specify `tm.to_dict()` which has very tiny overhead (it just returns the underlying `dict`) and you will have a full fledged `dict` to work with.

Hope this helps!

**Comment by nixjdm** [comment]
> If you want to user marshmallow for other reasons all you have to do is specify tm.to_dict() which has very tiny overhead (it just returns the underlying dict) and you will have a full fledged dict to work with.

Of course! Thanks!

**Comment by HonzaKral** [comment]
Glad this works for you, if there is anything else we can do, without blocking the namespace (many elasticsearch documents I have seen have fields like `keys` or `items` so we really try to avoid limiting the namespace) to make the use of ther libraries easier, just let us know.
