### ISSUE TITLE
 AuthenticationException(401, u'security_exception', u'missing authentication credentials for REST request [/elastalert_status/

### ISSUE THREAD

**Issue by meriem-ux** [elastic/elasticsearch-dsl-py#1253]
plllzzz any one help me i run elastalert in dokcer and i have this issue:

15:04:47.844Z ERROR elastalert-server:
    ProcessController:  ERROR:root:Error finding recent pending alerts: AuthenticationException(401, u'security_exception', u'missing authentication credentials for REST request [/elastalert_status/_search?size=1000]') {'sort': {'alert_time': {'order': 'asc'}}, 'query': {'bool': {'filter': {'range': {'alert_time': {'to': '2019-10-08T15:04:47.840009Z', 'from': '2019-10-06T15:04:47.839984Z'}}}, 'must': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}}}}
    Traceback (most recent call last):
      File "/opt/elastalert/elastalert/elastalert.py", line 1604, in find_recent_pending_alerts
        res = self.writeback_es.search(index=self.writeback_index, body=query, size=1000)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
        return func(*args, params=params, **kwargs)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/__init__.py", line 818, in search
        "GET", _make_path(index, "_search"), params=params, body=body
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/transport.py", line 353, in perform_request
        timeout=timeout,
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/connection/http_requests.py", line 143, in perform_request
        self._raise_error(response.status_code, raw_data)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/connection/base.py", line 168, in _raise_error
        status_code, error_message, additional_info
    AuthenticationException: AuthenticationException(401, u'security_exception', u'missing authentication credentials for REST request [/elastalert_status/_search?size=1000]')

**Comment by HonzaKral** [comment]
It looks like the cluster you have set up uses authentication and you are not supplying valid credentials. When you are configuring the connection to Elasticsearch you need to supply `http_auth` parameter set to `('USERNAME', 'PASSWORD')`

hope this helps!

**Comment by meriem-ux** [comment]
@HonzaKral i just add username and password at elastalert.yml and config.json

**Comment by HonzaKral** [comment]
I am sorry, but elastalert is a third party application and I do not know how it works or how it controls permissions. For that question you'd have to open an issue on the `elastalert` project.

All I can tell you that the error is telling you you haven't supplied username/password where it is required. It is also not related to this repository at all - it is an error with elastalert which is using `elasticsearch-py`, the low level python client for elasticsearch.

The problem, however, doesn't lie in the libraries used but in configuration of elastalert itself

**Comment by meriem-ux** [comment]
@HonzaKral  thnx for your time

**Comment by meriem-ux** [comment]
@ubersol can u help me plz?u had a same problem

**Comment by assaabriiii** [comment]
@meriem-ux Hi, i know it's a bit late but just making sure that no one will face the same issue as us:

so elasticsearch changed basic_auth param to http_auth and so if you add these both to your it would cause the authentications errors as well as not including any of that would cause the same issue 

so for fixing this you can use ENV variables to just play around or you can do this instead:
```python 
import elasticsearch

ELASTIC_PASSWORD = "<password>"
ELASTIC_URL = "https://127.0.0.1:9200"
ELASTIC_USER = "<username:elastic>"

es = Elasticsearch(
    ELASTIC_URL,
    ca_certs="http_ca.crt",
    http_auth=(ELASTIC_USER, ELASTIC_PASSWORD),
    verify_certs=True
)
```

also note that i was holding the `http_ca.crt` in the same directory usually it's been located in the elasticsearch directory>config>certs

**Comment by pquentin** [comment]
Starting from elasticsearch-py 8.x, please only use `http_auth` if you have a requests authentication object. For simple (user, password) pairs, you should use `basic_auth`. `http_auth` will work but emit a warning.
