### ISSUE TITLE
How to use distance_feature?

### ISSUE THREAD

**Issue by RaminJolfaei** [elastic/elasticsearch-dsl-py#1254]
Hi,
Acording to  [https://www.elastic.co/guide/en/elasticsearch/reference/7.x/query-dsl-distance-feature-query.html]
we can add distance_feature to query in should section. but I can't do this.
I couldn't find any documentation about this.

thanks

**Comment by HonzaKral** [comment]
I just implemented this via 38f2f5e552b6ca20a828d73551f3d80a1f81121c

My apologies for the delay!

**Comment by RaminJolfaei** [comment]
Thanks a lot
