### ISSUE TITLE
is there a API set corresponding to the all kibana operation?

### ISSUE THREAD

**Issue by loveJasmine** [elastic/elasticsearch-dsl-py#1259]

**Comment by HonzaKral** [comment]
I am sorry, but I don't understand the question, if you mean whether we support the [Kibana APIs](https://www.elastic.co/guide/en/kibana/master/api.html) then the answer is no. If not, could you please provide some clarification or examples of what you are looking for?

Thank you!

**Comment by loveJasmine** [comment]
I think if there is some API like kibana REST will be useful.

**Comment by HonzaKral** [comment]
I understand, but unfortunately that is out of scope of this project
