### ISSUE TITLE
Return the error message from execute() function of MultiSearch object

### ISSUE THREAD

**Issue by phuchle2** [elastic/elasticsearch-dsl-py#1260]
Hi, I'm currently working on msearch function which requires to return error if some entries of the batch we send to Elasticsearch have problems. 

However, looking at the source code, I found that elasticsearch-dsl only allows to either raise an error and exit the problem or totally skip the error of that entry in the response object. 

May I know are there any ways we can return those errors in the response object?

Thanks.

```
class MultiSearch(Request):
    ...
    def execute(self, ignore_cache=False, raise_on_error=True):
            ...
            out = []
            for s, r in zip(self._searches, responses['responses']):
                if r.get('error', False):
                    if raise_on_error:
                        raise TransportError('N/A', r['error']['type'], r['error'])
                    r = None
                else:
                    r = Response(s, r)
                out.append(r)

            self._response = out

        return self._response
```

**Comment by HonzaKral** [comment]
Good point, right now it is unfortunately not possible. What we could do is have a special value for `raise_on_error` so you could do something like: `execute(raise_on_error="ignore")` which would cause the error bodies to be returned instead of `None`. Do you think that would work?

Thanks for raising the issue!

**Comment by phuchle2** [comment]
Yeah, I agree. It would definitely be a good idea to have an option to return the error body But I think using special value is a bit harder to track compared to boolean value. Do you think that returning the error body by default when `raise_on_error=False` is a good idea? Users will decide how to use the response themselves?

**Comment by virtosubogdan** [comment]
Hi

An exception handler could also be an option.
`ms.execute(raise_on_error=False, exception_handler=user_handler)`  from  https://github.com/spyoungtech/grequests#usage

It's not great, but it would give the users more flexibility and still be backwards compatible because it does not break checks for `None`.

Something like:
```
def execute(self, ignore_cache=False, raise_on_error=True, exception_handler=None):
        """
        Execute the multi search request and return a list of search results.
        """
        if raise_on_error and exception_handler:
            raise ValueError('You cannot specify exception_handler if raise_on_error is True.')
        if ignore_cache or not hasattr(self, '_response'):
            es = get_connection(self._using)

            responses = es.msearch(
                index=self._index,
                body=self.to_dict(),
                **self._params
            )

            out = []
            for s, r in zip(self._searches, responses['responses']):
                if r.get('error', False):
                    if exception_handler:
                        r = exception_handler(s, r['error']['type'], r['error'])
                    elif raise_on_error:
                        raise TransportError('N/A', r['error']['type'], r['error'])
                    else:
                        r = None
                else:
                    r = Response(s, r)
                out.append(r)

            self._response = out

        return self._response
```

**Comment by sethmlarson** [comment]
I think we're going to pass on custom error handling logic aside from raising or not raising. A solution for this would be to send requests with special logic in different requests.

**Comment by roxanebellot** [comment]
Hi hello.

Why is this issue closed ? If a search embeded in a multisearch fails and do not raise, we still have to need to access the error message. 

Maybe we could create a sub-class of Response, "ErrorResponse", or add a flag in Response indicating if the search failed ? 

If you are interested, I may be able to allocate some time :slightly_smiling_face:
