### ISSUE TITLE
Question about refining a search with a second query

### ISSUE THREAD

**Issue by montao** [elastic/elasticsearch-dsl-py#1264]
I can make a quite interesting query which works like the following:

`res = es.search(index="foo-index", body={"from": start, "size": size, "query": {"bool": {"filter": {"term": {"published": True}}}}, "sort": [{"milliseconds": {"order": "desc"}}]})`

But would it be possible to refine (restrict) the query object once it is done? I mean if I defined a query, and then want to reuse it, would it be possible to "inherit" the aforementioned query and define another restriction i.e. `query42.filter"(category"="programming")`  while keeping all conditions from the original query with a new query? It would make it easier to write new queries which build old queries.

**Comment by HonzaKral** [comment]
Absolutely, you can do, in your case:
```python
from elasticsearch_dsl import Search, connections
connections.add_connection(es)

s = Search(index='foo-index')[start:start+size]
s = s.sort('-milliseconds')
s = s.filter('term', published=True)

for hit in s.execute():
    print(hit.title, ...)
```

Now you still have the `Search` object which you can keep modifying:

```python
s = s.filter('range', ...)
for hit in s.execute():
    print(hit.title, ...)
```

Is this what you were looking for?

**Comment by montao** [comment]
> 
> 
> Absolutely, you can do, in your case:
> 
> ```python
> from elasticsearch_dsl import Search, connections
> connections.add_connection(es)
> 
> s = Search(index='foo-index')[start:start+size]
> s = s.sort('-milliseconds')
> s = s.filter('term', published=True)
> 
> for hit in s.execute():
>     print(hit.title, ...)
> ```
> 
> Now you still have the `Search` object which you can keep modifying:
> 
> ```python
> s = s.filter('range', ...)
> for hit in s.execute():
>     print(hit.title, ...)
> ```
> 
> Is this what you were looking for?

Yes, that is awesome! Thanks...
