### ISSUE TITLE
question on document update

### ISSUE THREAD

**Issue by littlehome-eugene** [elastic/elasticsearch-dsl-py#1265]
I have two api servers. 

One of them has Elasticsearch-dsl Document definition.   
And it creates and updates the document data. 

Now 2nd api server needs update the document, it only needs to update one field (or few fields at most) given a document id.  

Since the two api server code has two separate code repository, Document definition is currently only defined in the first api server.  

Can I define simple document with simplified fields (id and the fields that 2nd server need to update) in the 2nd server repo with same index name and use the Document?

Or should I somehow share the Document definition among the two servers and use them?

```
class RoomBooking(Document):
    id = Keyword()
    dates = DateRange()
   class Index:
        name = 'room'   # same index name as defined previously in the 1st api server
```

1st server has more fields
```
class RoomBooking(Document):
    id = Keyword()
   dates = DateRange()
   customer = Customer()
   room_number = Keyword()

   class Index:
        name = 'room'   # same index name as defined previously in the 1st api server
```

**Comment by HonzaKral** [comment]
> Can I define simple document with simplified fields (id and the fields that 2nd server need to update) in the 2nd server repo with same index name and use the Document?

You can, this will work just fine.

> Or should I somehow share the Document definition among the two servers and use them?

This would be ideal, to have a library that both your projects will depend on and which will store the common code.

As a third option I can present an option where just one project has the field definitions and the other one uses:

```python
class RoomBooking(Document):
    class Index:
        name = 'room'

RoomBooking._index.load_mappings()
```

That will actually pull the mappings as they exist in Elasticsearch and update the Document class.

Hope this helps!
