### ISSUE TITLE
Is there any way to add some field doc in document definitions.

### ISSUE THREAD

**Issue by hackrole** [elastic/elasticsearch-dsl-py#1267]
maybe something like this:
```
class Event(Document):
     class Index:
            name = "event"
      sid = keyword(help_doc="shop id')
      uid = keyword(help_doc="user id')
```

**Comment by HonzaKral** [comment]
Unfortunately that is not possible right now. We can add it of course, but what would be the use case for it? Right now there is no place where it could be used so we assumed code comments would be enough.

**Comment by hackrole** [comment]
It maybe just style question, I think this is a better way than comment.
