### ISSUE TITLE
how do I specify a host so that my "manage.py search_index --rebuild" command would create indexing on that specified host. and search would run on that host.

### ISSUE THREAD

**Issue by Shivendra2407** [elastic/elasticsearch-dsl-py#1268]
@HonzaKral 
1.I want to know where do we specify the host for creating index?
Is it inside the document.py file(This file has my code for the structure of document from model, I dont know how the rebuild command detects this file. Please enlighten on this.)
I use the below line in my document.py file, I assumed earlier that this is where the host is speicfied. Is it not so? I specified a different ip here but it still makes indexing on localhost.
connections.create_connection(hosts=['localhost'])

2. I have a file as search.py where in I have all the query creation and searching functions, 
I use:
from elasticsearch import Elasticsearch
client = Elasticsearch()
s = Search(using=client, index='<index_name>')
How do I specify on what host will this search be executed?
as per the manual I see s = Search(using=Elasticsearch('localhost')) should work, but it doesn't.

Thanks. Beginner still, please help.

**Comment by HonzaKral** [comment]
The client needs to point to a host, initiating an empty one will default
to using localhost.
