### ISSUE TITLE
Explanation serialization

### ISSUE THREAD

**Issue by avrahamkam** [elastic/elasticsearch-dsl-py#1270]
When calling `.to_dict()` on the response object, the `explanation` attribute doesn't seem to be serializing correctly.
Specifically, the `ConstanctScore` values aren't showing numbers correctly. (I am not sure how to decode this...)
```
{'description': 'ConstantScore(+ConstantScore(instance: '
                '\x01\x00\x00\x00\x00\x00\x00\x01>\x03) +ConstantScore(id: '
                "\x01\x00\x00\x00\x00\x00\x00\x05'\x0b"
                ')), product of:',
 'details': [{'description': 'boost', 'details': [], 'value': 0.0},
             {'description': 'queryNorm', 'details': [], 'value': 1.0}],
```

**Comment by HonzaKral** [comment]
This is just the value returned by Elasticsearch, untouched. There is no need to decode that, it is a valid string already. The characters you are seeing are non printable, if you actually go and `print` the string you get a more proper representation. Either way there is nothing special the library is doing to the reply, the `to_dict` method actually returns the raw deserialized `json` as returned from the cluster.

Hope this helps!
