### ISSUE TITLE
doc_type doesn't work in Search

### ISSUE THREAD

**Issue by qzhqzh** [elastic/elasticsearch-dsl-py#1271]
Hi,

After 7.x compatibility, at least a string type `doc_type` seems doesn't work.

Our test elasticsearch version is 5.5.1 and

elasticsearch-7.0.5
elasticsearch-dsl-7.1.0

We found

        Search(using=client, index='myindex', doc_type='mydoc').count()
equal

        Search(using=client, index='myindex').count()

`doc_type` doesn't work, I think it is caused by

elasticsearch_dsl\search.py
```
        es = cls._get_connection(using)
        doc = es.get(
            index=cls._default_index(index),
            # doc_type=cls._doc_type.name,    # it has been removed in 7.x compatibility
            id=id,
            **kwargs
        )
```

and other methods like `execute` etc have the same problem.
<br>

however, if I pass parameters by `params` method, it works!  like this

        Search(using=client, index='myindex').params(doc_type='mydoc').count()
<br>

But, using `doc_type` without an error message in the `Search` method may be mislead and get an unexpected error.

**Comment by peterbe** [comment]
Do you get an exception thrown? Or, is your point that it should but it doesn't?

**Comment by sethmlarson** [comment]
Use .params(doc_type="my-type") to accomplish this for now. doc_type is deprecated and will be removed in v8.0.
