### ISSUE TITLE
ImportError: cannot import name 'DocType'

### ISSUE THREAD

**Issue by Action8686** [elastic/elasticsearch-dsl-py#1273]
use pip3 install elasticsearch-dsl 
ImportError: cannot import name 'DocType'
How to fix this error？

**Comment by HonzaKral** [comment]
`DocType` has been renamed to `Document ` in newer versions. Hope this helps!

**Comment by abhayananda-navsoft** [comment]
yes

**Comment by abhayananda-navsoft** [comment]
DocType has been renamed to Document in newer versions.
