### ISSUE TITLE
A better technique to capture all opertional exceptions

### ISSUE THREAD

**Issue by peterbe** [elastic/elasticsearch-dsl-py#1275]
I wanted to implement my own little retry loop with `time.sleep()`. So I tried this:
```python
from elasticsearch.exceptions import ConnectionError
...
while 1:
    try:
        return search.execute()
    except ConnectionError:
        time.sleep(5)   
```
The problem is that not all operational errors are `ConnectionError`. For example, `elasticsearch/connection/base.py` might throw:
```python
# in _raise_error in elasticsearch/connection/base.py
raise TransportError(503, 'no_shard_available_action_exception', ...)
```
503 is an operational error in my book. 

So here's how I captured all operational errors:

```python
from elasticsearch.exceptions import TransportError
...
while 1:
    try:
        return search.execute()
    except TransportError:
        if exception.status_code != 'N/A' and exception.status_code < 500:
             raise
        time.sleep(5)   
```

Now, if an `NotFoundError` is thrown from `search.execute()` it's actually a `TransportError(404, ...)` so it raises immediately. 

Is there really not a better way to capture all recoverable operational errors?

I'd love it if there was an exception class called something like `ElasticInternalServerError` which is used for all status codes >=500.

**Comment by peterbe** [comment]
Basically, I think this'd look the best as an API
```python
from elasticsearch.exceptions import ConnectionError, ElasticInternalServerError
...
while 1:
    try:
        return search.execute()
    except (ConnectionError, ElasticInternalServerError):
        time.sleep(5) 
```

Better than messing around with that `.status_code` property that jumps between being an integer and hardcoded string. 

Naming is hard. `ElasticInternalServerError` isn't great but it's better than `Elastisearch50xError`.

**Comment by davidgacc** [comment]
@HonzaKral calling `Search()` it possible that this call recover by itself due to timeout or some other error, and what about `scan()` after calling `Search()`. Thanks

**Comment by sethmlarson** [comment]
You can configure your connection class options via `elasticsearch_dsl.connections.create_connection(...)` to retry on statuses and timeouts, etc.
