### ISSUE TITLE
Multi-version Elasticsearch clusters

### ISSUE THREAD

**Issue by cockcrow** [elastic/elasticsearch-dsl-py#1276]
There is `elasticsearch6` for elasticsearch 6.x clusters. What about `elasticsearch6-dsl` package with `elasticsearch6` as requires? Then we can access both elasticsearch 6.x and 7.x in one project.

**Comment by zachgoulet** [comment]
It appears as though [`elasticsearch7-dsl` ](https://pypi.org/project/elasticsearch7-dsl/) exist in pypi, but [`elasticsearch6-dsl`](https://pypi.org/project/elasticsearch6-dsl/) does not. Can an `elasticsearch6-dsl` be uploaded, as well?

**Comment by sethmlarson** [comment]
Sure I can do that.

**Comment by sethmlarson** [comment]
Done: https://pypi.org/project/elasticsearch6-dsl
