### ISSUE TITLE
Scan hit result does not support blankspace if the doc has attribute which contains blankspace like "target name"

### ISSUE THREAD

**Issue by dhutsj** [elastic/elasticsearch-dsl-py#1277]
![image](https://user-images.githubusercontent.com/13284538/69404666-c9037c80-0d38-11ea-9be5-213e757d2367.png)
![image](https://user-images.githubusercontent.com/13284538/69404690-d6b90200-0d38-11ea-8961-accdc8522985.png)
You can see that the hit doc has an attribute called "Issue key", but how can I get it?
![image](https://user-images.githubusercontent.com/13284538/69404797-17b11680-0d39-11ea-8fbe-e3a4a35e4866.png)

**Comment by HonzaKral** [comment]
You can always use the dict-like access: `hit["Issue key"]`

hope this helps!

**Comment by dhutsj** [comment]
Cool! It worked & thanks!
