### ISSUE TITLE
Need help to integrate Vector field.

### ISSUE THREAD

**Issue by Rjtsahu** [elastic/elasticsearch-dsl-py#1278]
#### I am trying to create a field of type dense_vector but as it is not available in current releases.

so had created a VectorField class which extends CustomFields , with it's base_type as :
```python 
class VectorField(CustomField):
    name = 'dense_vector'
    builtin_type = 'dense_vector'

class MyDocument(Document):
    vector_data = VectorField()

MyDocument.init()
```
but when i am running this code i am getting mapping error:
`RequestError(400, 'mapper_parsing_exception', 'The [dims] property must be specified for field [vector].')`

#### This is because the properties doesn't have dims specified.

Mapping : 
```python

"mappings": {
    "properties": {
      "vector_data": {
        "type": "dense_vector",
        "dims": 3
      }
    }
  }

```
can some one suggest how to pass [dims] in field property ?

**Comment by ksrivatsa** [comment]
This should work!

`class DenseVector(Field):
    name = 'dense_vector'

    def __init__(self, dims):
        super(DenseVector, self).__init__(dims=dims)
`

**Comment by Rjtsahu** [comment]
cool, i ll check this
