### ISSUE TITLE
help speed up bulk indexing

### ISSUE THREAD

**Issue by littlehome-eugene** [elastic/elasticsearch-dsl-py#1279]
I'm doing something like

```
         es = Elasticsearch(settings.ES_URLS)
         bulk(client=es,
              actions=(b.indexing(save=False) for b in review_meta_objs.iterator()))
```

for 5000 documents, it takes about 5 min, 

the `indexing()` part does perform multiple related query to fetch related fields.. 

well I guess I need to optimze the related field look up.. :(

Or is there other obvious flaw in what I'm doing?

**Comment by HonzaKral** [comment]
from the point of view of elasticsearch this looks good. 5 minutes seem high for just the indexing part (of course depends on configuration, HW etc) so I am suspecting that it's actually reading from `review_meta_objs` and composing the objects that takes a long time. You might want to try investigate the use of `select_related` or similar functionality to prefetch related fields.

Hope this helps!
