### ISSUE TITLE
problems with celery, maximum recursion depth exceeded (DocType cannot be unpickled)

### ISSUE THREAD

**Issue by brizzbane** [elastic/elasticsearch-dsl-py#128]
issue is with DocTypes.   Code works fine w/out using celery, but once I start using celery I get an error from elasticsearch_dsl that the maximum recursion depth has been exceeded.

**Comment by brizzbane** [comment]
I'm gonna close this for a min.

Another thing I'm doing in Bot is:

self.Account       = Account(self.Document)

With Account just being another object.  That might be whats causing issue.

**Comment by brizzbane** [comment]
that unfortunately wasn't it.  any ideas?  Is what I'm trying to do possible?

**Comment by brizzbane** [comment]
this likely isn't an issue w/elasticsearch_dsl, but from a lack of understanding on decorators.  Closing, and will comment when I figure out.

**Comment by brizzbane** [comment]
sorry.  reopening this.  can't seem to figure out a way to get celery to work with a doctype.

the issue I *think* is with pickle and circular imports.  will either get an error of maximum recursion depth, or celery complaining of not being able to find the module named Document (the doctype)

**Comment by brizzbane** [comment]
Have actually opened an SO ticket too.  Don't know if the 'solution' to this problem would be w/the DocType, or Celery:

http://stackoverflow.com/questions/29686363/celery-circular-imports-module-not-found-or-maximum-recursion-depth-exceeded

**Comment by brizzbane** [comment]
I've thought of a possible workaround.  You could just pass the 'id' of the document, and then .get() the document by id once inside the function.

Would be curious to hear from you tho and see if there is a way to pass the objects around w/out querying again.

**Comment by brizzbane** [comment]
according to this page:

https://denibertovic.com/posts/celery-best-practices/

maybe that should be what I should be doing anyway.  from the page:

No.7: Don't pass Database/ORM objects to tasks

After giving this talk at a local Python meetup a few people suggested I add this to the list. What's it all about? You shouldn't pass Database objects (for instance your User model) to a background task because the serialized object might contain stale data. What you want to do is feed the task the User id and have the task ask the database for a fresh User object.

**Comment by gkirkpatrick** [comment]
Yeah, passing objects by ID is a good practice for passing objects to celery. I’ve had it bite me a few times. The main issues: 1. as mentioned stale data. with an ORM like django, and a task queue, it’s really easy to cause tasks to be running with bad data. This is so hard to debug that it’s worth just never passing objects for that reason. 2. The objects that you pickle might be much bigger than you’d want. Imagine having a huge dict you’re serializing.

I’m not 100% sure what would be getting serialized that would cause your issues, but if you can pass an ID and get the object and it works, then definitely do that.

There is a way to get into a debugger in celery as well to see exactly what is going on. That isn’t a good idea on a production environment obviously, but it can help debug these kinds of problems. http://celery.readthedocs.org/en/latest/tutorials/debugging.html

Hope this helps,
gk

**Comment by brizzbane** [comment]
getting object by ID is what I'm doing at the moment and it IS working.  glad I am at least going with something.  so for working w/DocType  and celery, maybe this is how it should be done.

**Comment by HonzaKral** [comment]
@brizzbane this is really hard to debug without the exact stack trace, could you perhaps paste somewhere the max recursion depth exceeded error?

Also make sure your distinguish between the `Document` as a class and an instance - it is customary in python (very strong convention) to name all variables in lower case - on your original code sample you are using `Document` for both variables, attributes and the class itself. It might then be easy to confuse the interpreter as to what it should be.

**Comment by brizzbane** [comment]
@HonzaKral I was using the same name as the class as a variable (still learning).  Have gone through my code and replaced all the instances where I was doing that and have switched to lowercase variables.  (Thanks for educating me on good practices!).  I'm still having issues passing/accessing the document in any worker method (@app.task def do_work(a_doctype).  I will put together a very stripped down code.

Right now as a solution (as stated above--and maybe what I should be doing anyways), I'm just accessing the document by ID once inside of the @app.task

**Comment by HonzaKral** [comment]
I have found the issue - DocType objects cannot be unpickled correctly. Thanks for your patience, fix is coming.

**Comment by brizzbane** [comment]
Thanks for fixing this.  Absolutely love this module!
