### ISSUE TITLE
Can I set Index name?

### ISSUE THREAD

**Issue by ChunYuan0930** [elastic/elasticsearch-dsl-py#1280]
Can I add some code like article.Index.name="test" to change index?
I don't want to set it in the Index class like below.
class Index:
        name = "blog"

Persistence Example:
....
article = Article(meta={'id': 42}, title='Hello world!', tags=['test'])
**article.Index.name="test"**
article.body = ''' looong text '''
article.published_from = datetime.now()
article.save()

**Comment by HonzaKral** [comment]
Every time you call `save` you can override the index, you can see an example in the tests:

https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_integration/test_document.py#L305

Hope this helps!
