### ISSUE TITLE
Getting all the data after aggregation.

### ISSUE THREAD

**Issue by rjsnh1522** [elastic/elasticsearch-dsl-py#1281]
Hi,
I am using search and aggregation of dsl. Search and aggregation is working fine for me.
But I need to include more data in aggregation. 
suppose i have data like 

```
[{"name": 'abc',  'type': 'file', 'count':1},
{"name": 'abc',  'type': 'file', 'count':2},
{"name": 'abc',  'type': 'file', 'count':5},
{"name": 'abcd',  'type': 'file', 'count':10}, 
{"name": 'abcd',  'type': 'file', 'count':12}, 
{'name': 'xyz', 'type': 'domain', 'count': 30}]
```

when I am aggregating it is giving me correct result but result includes only 
```
[{'name': 'abc', 'count': 8}, 
{'name': 'abcd', 'count': 22},
{'name': 'xyz',  'count': 30}]
```

but my expectation is to get result like 
```
[{'name': 'abc', 'count': 8, 'type': 'file'},
{'name': 'abcd',  'count': 22, 'type': 'file'},
{'name': 'xyz', 'count': 30, 'type': 'domain'} ]
```

My query is like 
```
search.aggs.bucket('timeIOCS', 'nested', 
path='timeIOCS').bucket('aggs_data', 'terms', 
field='timeIOCS.name',
size="100000").metric('count', 'sum', 
field='timeIOCS.count')
```

**Comment by HonzaKral** [comment]
That query should give you your data broken down by `timeIOCS.name` and for each value of that field you will get the number of (nested) documents containing that value and also the `sum` of the `timeIOCS.count` field.

You didn't ask for any aggregation to be done on the `type` field so it is not calculated nor returned.

Hope this helps!

**Comment by rjsnh1522** [comment]
Is there any way to get the associated type also .?? I know it's working fine. I am asking that how to associate related data. if I do the count on type it will aggregated type and give its count.
which is not my requirement.
sorry I was not able to explain properly.

My problem is I want to get the count of unique names and their type .
can I aggregate using multiple fields ?

**Comment by HonzaKral** [comment]
Oh, I see. Yes, there are multiple ways, the easiest is to also include an aggregation on type:

```python
search.aggs\
  .bucket('timeIOCS', 'nested', path='timeIOCS')\
  .bucket('aggs_data', 'terms', field='timeIOCS.name', size="100000")\
  .bucket("types", "terms", field="timeIOCS.type")\
  .metric('count', 'sum', field='timeIOCS.count')
```

**Comment by pilmus** [comment]
Hi! Is there an easy way to do this through the `FacetedSearch`-related classes? Or would you recommend I make two `TermsFacet`s, one for `fieldname.type` and one for `fieldname.name`?
