### ISSUE TITLE
indexing child document does not work with python client but curl works

### ISSUE THREAD

**Issue by mchari** [elastic/elasticsearch-dsl-py#1282]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.3.0

**Plugins installed**: [ingest_attachment]

**JVM version** (`java -version`):12.0.1

**OS version** (`uname -a` if on a Unix-like system): Darwin Kernel Version 17.7.0

**Description of the problem including expected versus actual behavior**:
When I try to index a child document using ES's python client interface, has_parent query is unable to find the child document. If I use curl to index a similar child document, has_parent query returns this child document.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create mapping and index using es.indices.create() in attached file
 2. Index parent document using es.index()
 3. Index a child document using curl 
 4. Query has_parent - works !
 5. Index a child document using es.index()
 6. Query has_parent - doesn't retrieve child document indexed in 5

[parent-child-py-bug.txt](https://github.com/elastic/elasticsearch/files/3935417/parent-child-py-bug.txt)

**Provide logs (if relevant)**:

**Comment by HonzaKral** [comment]
You are using `my-join-field` in the child document whereas you should be using `my_join_field` - underscores instead of hyphens. If you fix that typo everything works fine.

Hope this helps!

**Comment by mchari** [comment]
This is embarassing ! Thanks for the find, though I wish the software had reported that there is no parent-child relation with the name with my-join-field.
Thanks again!

**Comment by HonzaKral** [comment]
No worries, happens to me daily :)

A small tip to avoid these mistakes is to use `strict` dynamic setting where any unknown field, like in this case, will cause an exception - https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic.html

**Comment by mchari** [comment]
Thanks for the tip. I will definitely use it to prevent future mishaps.
Appreciate the fast responses.
