### ISSUE TITLE
mutable content of an Object field | index population from dynamic json

### ISSUE THREAD

**Issue by titovanton** [elastic/elasticsearch-dsl-py#1283]
Hello, may be I do not understand something, but hope there is a solution for my case. I have few fields, which I've specified in the Document. One of them regular Keyword, another I've set as `data = Object(dynamic=True)` with the purpose to store there scheema-less object data. If I POST such documents with Kibana, it works and _search lookup inside as well, giving me documents I'm searching. But doing the same via elasticsearch-dsl, I got data field like that: 
```         
 "data" : [
            { },
            { },
            { },
            { }
          ],
```
And that is not even an array of objects... 
What is the best way to implement such functionality? I can not specify the list of properties for the Object field, while the content of data field is mutable.

**Comment by HonzaKral** [comment]
`Object` or `Nested` field is indeed the way to go and works with `elasticsearch-dsl`. you can see some complex examples in the repo (0). Can you please attach some code reproducing the issues you are seeing? I am having trouble understanding what you mean, thank you!

0 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/parent_child.py

**Comment by titovanton** [comment]
```
# models.py

class Car(models.Model):
    TYPE_SEDAN = 1
    TYPE_TRUCK = 2
    TYPE_SUV = 4
    TYPE_CHOICES = [
        (TYPE_SEDAN, 'Sedan'),
        (TYPE_TRUCK, 'Truck'),
        (TYPE_SUV, 'SUV'),
    ]

    name = models.CharField(max_length=256)
    color = models.CharField(max_length=256)
    description = models.TextField()
    type = models.IntegerField(choices=TYPE_CHOICES, default=1)
    data = JSONField(default=dict)

    def type_to_string(self):
        return dict(self.TYPE_CHOICES)[self.type]
```
```
# documents.py

@registry.register_document
class CarDocument(Document):
    type = fields.TextField(attr='type_to_string')
    data = fields.ObjectField(dynamic=True)

    class Index:
        # Name of the Elasticsearch index
        name = 'cars'
        # See Elasticsearch Indices API reference for available settings
        settings = {'number_of_shards': 1,
                    'number_of_replicas': 0}

    class Django:
        model = Car

        fields = [
            'name',
            'color',
            'description',
        ]
```

```
# population management command

class Command(BaseCommand):
    def handle(self, *args, **options):
        fake = Faker()
        for x in range(10):
            Car.objects.create(
                name=fake.first_name,
                color=fake.safe_color_name(),
                description='with data dyn',
                type=random.choice(list(dict(Car.TYPE_CHOICES).keys())),
                data={
                    'country': fake.country(),
                    'contact_person': fake.first_name(),
                    'info': {'word': fake.word()},
                    'items': [{'name': fake.company(), 'address': fake.address()} for x in range(5)]
                }
            )
```

**Comment by titovanton** [comment]
As you can see, I'm trying to make the tutorial example solving my purpose. Also I'm using the "django elasticsearch dsl" with their field, but it maps to Object field from "elasticsearch dsl". I've read the code and found "dynamic" parameter with the description, found the premise from ES documentation(as you can see, I'm not familiar with ES as well). Thought this param would make it working for me :)

**Comment by titovanton** [comment]
```
# this request from the Kibana console, returns the original "data" list of empties

GET /cars/_search
{
  "query": {
    "multi_match": {
      "query": "with data dyn",
      "fields": ["*"]
    }
  }
}
```

**Comment by HonzaKral** [comment]
I am sorry, but this code is not using the `elasticsearch-dsl` library and I cannot help you since I don't know what is going on. Please consider opening an issue with `django-elasticsearch-dsl`. Thank you
