### ISSUE TITLE
ELastic Search Geo Point mapping

### ISSUE THREAD

**Issue by Shivendra2407** [elastic/elasticsearch-dsl-py#1286]
Hi @HonzaKral and others who can help me please,

I have a model of Location which has the following fields:

```
class Location(models.Model):
    latitude = models.CharField(max_length=255, null=True, blank=True)
    longitude = models.CharField(max_length=255, null=True, blank=True)
    how_to_reach = models.TextField(default='', null=True, blank=True)

    class Meta:
        abstract = True

```
And another model City that inherits Location

```
class City(Location):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, null=True, blank=True)

```
I am using elasticsearch 6.3.2 and accordingly using elasticsearch-dsl-py and elasticsearch library versions, I have already used in another project so I know it is not compatibility issue of libraries and elasticsearch version.
My question in how to use GeoPoint() field. In my document.py file I have:

```
from .models import City
from django_elasticsearch_dsl import Document, fields, GeoPoint
from django_elasticsearch_dsl.registries import registry


@registry.register_document
class CityDocument(Document):
    location = GeoPoint()
    class Index:
        name = 'cities'
        settings = {'number_of_shards': 1,
                    'number_of_replicas': 0}
    class Django:
        model = City
        fields = [
            'name',
            'slug',
            'id'
        ]
```
The latitude and longitude fields I have in model, how will I get them indexed when I use:

>>> python manage.py search_index --rebuild

from terminal. Currently if I do this, only textual fields 'name', 'slug' and 'id' get indexed with each City doc, no location field is there in those docs.

Also, how would I query this using Search object from elasticsearch_dsl .
 
Appreciate all the help, thanks in advance!

**Comment by HonzaKral** [comment]
This is not a functionality that is provided by this library, please open an issue with `django-elasticsearch-dsl` instead. Thank you
