### ISSUE TITLE
Name Query MultiSearch

### ISSUE THREAD

**Issue by Universemul** [elastic/elasticsearch-dsl-py#1287]
Hi!
I'm currently working with MultiSearch object to compute data from different filters (on two differents index). I have an index where each document has 2 fields : month and year.
For some reasons, I need to do multiple query (one for each month).

Is there any possibilities to name each query with a MultiSearch object?

Thanks!

**Comment by HonzaKral** [comment]
There is no possibility to name queries in `MultiSearch` but also `MultiSearch` should not be needed based on your description. Can you please provide a sample of what you'd like to achieve, maybe there is a way. Thank you!
