### ISSUE TITLE
Is version 6.3.0 or 6.3.1 fully compatible with ES 6.2.3?

### ISSUE THREAD

**Issue by omkar-dsd** [elastic/elasticsearch-dsl-py#1289]
Just need to know whether v6.3.0 or v6.3.1 of the library fully compatible with ES 6.2.3?

What I have already checked in docs:

> For Elasticsearch 6.0 and later, use the major version 6 (6.x.y) of the library.

**Comment by HonzaKral** [comment]
Hi, it should be compatible, please open an issue if you find anything missing from the library. Thank you!
