### ISSUE TITLE
Connection Pools?

### ISSUE THREAD

**Issue by royrusso** [elastic/elasticsearch-dsl-py#129]
The underlying elasticsearch lib supports connection pooling. Curious if that concept carries forward with this lib, as I don't see a mention in the config section of the docs: http://elasticsearch-dsl.readthedocs.org/en/latest/configuration.html

**Comment by HonzaKral** [comment]
We mention in http://elasticsearch-dsl.readthedocs.org/en/latest/configuration.html#default-connection that all kwargs will be passed to the low level client. So if you want to configure connection pooling you can.

But even without any configuration we will use connection pooling and persistent connections to all the nodes you configure.

Hope this helps
