### ISSUE TITLE
Store term vectors in class

### ISSUE THREAD

**Issue by MattesR** [elastic/elasticsearch-dsl-py#1291]
Hi,

I have a pretty simple class:
```
class TextUnit(InnerDoc):
    content = Text()
    position = Integer()
```
I want to also store the term vectors of `content`, similar to how elasticsearch suggests:
```
      "text": {
        "type":        "text",
        "term_vector": "with_positions_offsets"
      }
```
I wanted to use  `"term_vector": "yes"`, but the issue remains the same.

How can I store term vectors in documents which were created with elasticsearch_dsl?

Thanks in advance.

**Comment by HonzaKral** [comment]
instead of `Text()` just specify `Text(term_vector="with_positions_offset")`

Hope this helps!

**Comment by MattesR** [comment]
> instead of `Text()` just specify `Text(term_vector="with_positions_offset")`
> 
> Hope this helps!

It did help, thank you.  
I guess I did not read the docs careful enough:
> By default any keyword arguments, beyond the parameters of the API, will be considered fields with new values  

Is generally true for all parts of `elasticsearch-dsl-py`, I suppose.
