### ISSUE TITLE
Implementation of search_as_you_type field mapping and query

### ISSUE THREAD

**Issue by dpasqualin** [elastic/elasticsearch-dsl-py#1292]
I've noticed that the recently added [search_as_you_type](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-as-you-type.html) field is not implemented in this package. Would it be of interest of the community to add it? I'd be happy to try and create a PR for it.

Also, elasticsearch itself doesn't provide a specific search query for this field and suggests the use of multi_match, as follows:

```
{
  "query": {
    "multi_match": {
      "query": "brown f",
      "type": "bool_prefix",
      "fields": [
        "my_field",
        "my_field._2gram",
        "my_field._3gram"
      ]
    }
  }
}
```
Would it be nice to have a SearchAsYouType query class in elasticsearch-dsl that generates this multi_match query?

**Comment by HonzaKral** [comment]
Hi, it would be great if you created a PR for the field!

As for the query itself I am not sure we need that, so far the package follows 1-to-1 policy where our queries and other objects map 1-to-1 to the resulting json which this would break. Maybe we can just add it as an example in the documentation where we talk about how the DSL object works?

What do you think?

**Comment by dpasqualin** [comment]
Pull request created.
