### ISSUE TITLE
Fields which have __  are automatically converted to .field. No way to ignore this

### ISSUE THREAD

**Issue by haneefarkin** [elastic/elasticsearch-dsl-py#1293]
q = Q("match", ** { "__cid" : customer_id })
print(q.to_dict())

Output is : {'match': {'.cid': '10374'}}.  
There is no way to query for the field which has "__"

**Comment by HonzaKral** [comment]
There is a way to ignore this by passing `_expand__to_dot=False`:
`q = Q("match", __cid=customer_id, _expand__to_dot=False)`

Hope this helps!
