### ISSUE TITLE
manage.py search_index --rebuild does not take PORT from settings.py file instead only looks for 9200 port on its own

### ISSUE THREAD

**Issue by Shivendra2407** [elastic/elasticsearch-dsl-py#1294]
I have elasticsearch version 6.3.2 and am running two separate servers on my localhost itself, one on 9200 port and other on 9202 port.
In my django project settings file I have
```
ELASTICSEARCH_DSL={
    'default': {
        'hosts': "localhost",
        'ports': "9202",
        'timeout': 240
    },
}
```
Even then on running manage.py --rebuild it looks for elasticsearch running at 9200 port ?
Can anyone explain why this is happening and what to do if I want to index on some other port of ES server.

PS. I am doing this on my local machine itself, i.e. my django and elastic search servers are on same computer.

**Comment by HonzaKral** [comment]
I am sorry but this is not a functionality that is provided by `elasticsearch-dsl` it looks like you need to open an issue on `django-elasticsearch-dsl` instead. My guess would be though that you are using plural `ports` instead of just `port` also try `localhostL9200` instead of that.
