### ISSUE TITLE
search object with nested query seems malformed and doesn't return expected results

### ISSUE THREAD

**Issue by MattesR** [elastic/elasticsearch-dsl-py#1299]
Hi,
There must be something wrong with my code but I can't find any issue with it. Here's the curl that I want to translate to elastic-dsl:
```
curl -X GET "localhost:9200/<my_index>_search?pretty" -H 'Content-Type: application/json' -d'
{
  "_source": {
    "includes": [ "*" ],
    "excludes": [ "body" ]
  },
  "query": {
    "nested": {
      "path": "body",
      "inner_hits": {       

      },
    "query": {
       "more_like_this" : {
           "fields" : ["body.content"],
           "like" : [<my custom query>],
           "min_term_freq" : 1,
           "min_doc_freq":1
           
       }
   }
    }
  },
  "size" : 10
}
'
```

It returns the nested objects which have the highest MLT-Score relative to `<my custom query>`.
I want to translate that to elasticsearch-dsl. Here's my approach:

```
def create_nested_search(query, index):
    s = Search(using=client, index=index)
    s.source(includes=["*"], excludes=["body"])
    mlt_match = MoreLikeThis(fields=["body.content"],
                             like=[query],
                             min_term_freq=1,
                             min_doc_freq=1)
    nested_query = Nested(path="body", inner_hits={}, query=mlt_match)
    s.query(nested_query)
    return s
```
In order to validate that It works. I used `s.to_dict()` but it always returns an empty dictionary. Executing `nested_query.to_dict()` returns:
```
{'nested': {'path': 'body', 'inner_hits': {}, 'query': {'more_like_this': {'fields': ['body.content'], 'like': ['you owe me'], 'min_term_freq': 1, 'min_doc_freq': 1}}}}
```
which is exactly what I expected.
I'm doing all these tests in a python console inside PyCharm, so I tried to inspect the search object `s`. It looks wrong. IDK how to describe it better, so I have attached an image of the inspection.

![s inspection](https://user-images.githubusercontent.com/42345537/72432598-be44f100-3797-11ea-871f-b042b8b420cb.png)

Is it supposed to look like this?What am I doing wrong? 

Moreover, executing the search query (for a specific string) results in a response which contains documents which have a MLT-Score of 1. The top 10 hits are just starting by an ID (190, no idea why) and going up from there (199). 
Executing the curl results in a top hit with a score of 19.  So there has to be an error somewhere.

Thanks in advance for any suggestions.

**Comment by HonzaKral** [comment]
You need to assign back to `s` as `s.query` returns a copy:
`s = s.query(...)`

Hope this helps!
