### ISSUE TITLE
Query into nested list of objects

### ISSUE THREAD

**Issue by raisulkutumbita** [elastic/elasticsearch-dsl-py#1300]
Hi

Actually I am not new in Elastic search but I have no idea how to query into nested list of objects.

       nested" : {
             "path" : "factory",
             "query" : {
                "match" : {"factory.uuid" : "767605f4-b229-43bf-bca0-2d3ad0cb7db8"},
                "match" : {"factory.uuid" : "7e1897a0-04af-405f-904c-19fe07360b91"}
             }
        }

This works for me fine. But I need dsl query.
Is there any solution that I have missed ?

Thanks

**Comment by HonzaKral** [comment]
unfortunately the query you have there is not valid as it contains multiple matches. To properly query for `factory.uuid` being one of those values you should use the `terms` query instead:

```python
s = Search()
s = s.query("nested", query=Q("term", factory__uuid=["7e1...", "767..."]))
```

Hope this helps!
