### ISSUE TITLE
Possible To Update Mappings When Using IndexTemplate?

### ISSUE THREAD

**Issue by rholloway** [elastic/elasticsearch-dsl-py#1304]
If I create a DocType and initialize it using index template, ie `MyDocType._index.as_template('template_name').save()`, everything is good initially, as soon as I insert documents all the types are detected correctly.

However, if I add 3 new fields to the DocType definition, I can't figure out how to get all the new fields added to the existing index. I tried `MyDocType._index.init()` and `MyDocType._index.save()` but both lead to an error because it tries to update settings such as number of shards, which I also have defined so the IndexTemplate picks it up.

Is there a way to get all the new mappings updated but not try to update things like index settings? I understand elasticsearch won't let you update things like shards on an open index, or modify mapping type of an existing attribute, but we should be able to add the new field mappings to the existing open index.

This is more problematic if you are using dynamic = False to disable dynamic mappings. I could probably manually add each new field using ES-DSL when I add a new field, but it would be nice if there was a way similar to `init()` or `save()` that would try and update just the mappings separate from the settings, which would enable automatically updating/adding new mappings on application init/start, for example.

For what it's worth, here is my current solution that I think can run on application startup and more or less maintain the template as well as update mappings as needed. Note this is on 6.x but looking at source for 7.x it seems something similar would still be required (minor difference, such as name not needed on Mapping).

```
# cls is my DocType, I provide get_index() and get_doc_type() functions that just return the strings respectively.

cls._index.as_template(cls.get_index()).save()

# update field mappings if index already created to align with the current template mapping
template_mappings = cls._index.as_template('randomname').to_dict()['mappings']
mapping = Mapping.from_es(cls.get_index(), cls.get_doc_type())
mapping._update_from_dict(template_mappings)
mapping.save(cls.get_index())
```

**Comment by HonzaKral** [comment]
Index templates are only applied when an index is created. When using `IndexTemplate` to manage your mappings (which is definitely a recommended way to do it) you need to make sure you recreate the index. You can have a look at the migration example (0) to see how that workflow can be executed.

Hope this helps!

0 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/alias_migration.py
