### ISSUE TITLE
How to use retry_on_conflict in UpdateByQuery

### ISSUE THREAD

**Issue by omkar-dsd** [elastic/elasticsearch-dsl-py#1306]
To perform something similar to: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-update

How can the `retry_on_conflict` param be passed?

1. Tried passing in in client's `update()` method, it passes it as query param in` _update` request, not in `_update_by_query`
2. Tried passing it in `.query()`, method, that's some dumb thing to do
3. Tried passing in `.params()`, not supported.

**Comment by omkar-dsd** [comment]
Looks like this clarifies it:
https://github.com/elastic/elasticsearch/issues/22723

It is not supported for the bulk queries. Please once confirm, is there any way I can proceed without failure and without partial update?

**Comment by HonzaKral** [comment]
the `delete_by_query` API doesn't support `retry_on_conflict`, any parameter supported by the API (0) you can set via the `params()` method.

Hope this helps!

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html

**Comment by omkar-dsd** [comment]
What are your views on retrying at application level?
