### ISSUE TITLE
Add a query.Filter class or filter support to query.Q

### ISSUE THREAD

**Issue by nkakouros** [elastic/elasticsearch-dsl-py#1308]
I am a new user of elasticsearch and the library, apologies if what I write
below is wrong.

I have built a library of queries for my application. The library contains functions that return an object of type `Query`. The users of the library use `es.Search().query(q)` where q is a returned query.

Due to the above, I cannot use `es.Search().filter` directly. To add filters to
my queries, I use `Q('bool', filter=a_filter_here, ...)`.

I find this a bit cumbersome. it would be great if there were support to write
sth like `q = F('match', ...) & Q('match', ...)`.

Perhaps filters have some restriction that I am not familiar with, but if not,
could that be a feature request?

**Comment by HonzaKral** [comment]
There is a method called `filter` which you can use to add filters to a search body: `es.Search().filter(q)`

Hope this helps!
