### ISSUE TITLE
Get the count of results in scan/search

### ISSUE THREAD

**Issue by drakerc** [elastic/elasticsearch-dsl-py#1309]
I'm using the scan/search function of elasticsearch-dsl to fetch all records matching my query from Elasticsearch.
I don't know how to properly get the count of results when using the scan function. 
Right now, my current way of doing it is to create the Search object and then use the count method, and then start iterating on the scan() generator.
Unfortunately, according to the logs, it makes two requests to the Elasticsearch: first request is the .count() request and then it starts making the scan request, so it's not optimal.

When I use the normal querying, it's easy and it's done using just one query:
```
response = search.execute()
count = response.hits.total
results = response.hits
```

However, with the scanning, here's what I have to do (two requests):
```
search = Search \
            .from_dict(self.query) \
            .using(self.es) \
            .index(self.index) \
            .doc_type(self.doc_type)
count = search.count()  # one request
results = search.params(scroll=self.scroll_time, size=1000).scan()
for index, result in enumerate(results):  # another request
    result_dict = result.to_dict()
```
and that creates two queries to Elastic.
Is there any way to get the amount of result count during scanning, without having to create a separate query? It seems wasteful to make another query (and as far as I remember, in normal elasticsearch-py, the record count is available during scrolling). In my case, I need to know the amount of results before scanning (or during first iteration), because I'm pushing the results to a Numpy array and need to declare its size beforehand to make it optimal.

**Comment by HonzaKral** [comment]
Hi, thank you for the question!

Right now it is not possible with the `scan` helper in `elasticsearch-py` but it is (part of) a requested feature which would allow us to return parts of the body on top of just the iterator. You can monitor https://github.com/elastic/elasticsearch-dsl-py/issues/580 for any progress on that.
