### ISSUE TITLE
Add a link to rtd in README.rst

### ISSUE THREAD

**Issue by willingc** [elastic/elasticsearch-dsl-py#131]
@HonzaKral I was talking with someone on IRC and suggested that the docs had good examples. They didn't notice the link in the GitHub repo description to Read The Docs. It would be helpful to mention the docs and provide the link in the README too.

I'm happy to make the fix if you agree. Thanks.

**Comment by HonzaKral** [comment]
That would be definitely super useful, defintiely my fault for not including the link properly.

If you want to send a PR I would happily merge it or I can do the change myself.

Thanks!

**Comment by willingc** [comment]
Happy to send a PR later today :)

**Comment by HonzaKral** [comment]
This was fixed by #132, Thanks!
