### ISSUE TITLE
Datetimes saved as UTC are returned as tzlocal when retreived

### ISSUE THREAD

**Issue by macdjord** [elastic/elasticsearch-dsl-py#1311]
# How to reproduce:

```python
import datetime as _dt
import logging

import elasticsearch_dsl as _es_dsl

import es_connect as _es_connect

logging.getLogger().setLevel(logging.WARNING)


class TestIndex(_es_dsl.Document):
    class Index:
        name = 'test_index'
        using = _es_connect.ES_ALIAS

    some_time: _dt.datetime = _es_dsl.Date(required=True)


TestIndex.init()

test_doc = TestIndex(some_time=_dt.datetime(2020, 1, 1, 12, tzinfo=_dt.timezone.utc))
test_doc.save()
print(f'Original object, post-save: {test_doc.some_time!r}')
test_doc_fetched = TestIndex.get(test_doc.meta.id)
print(f'Fetched back: {test_doc_fetched.some_time!r}')
```

# Expected result:

* If a document is saved with a UTC timestamp, fetching that document back returns the timestamp still in UTC

# Actual result:

```
Original object, post-save: datetime.datetime(2020, 1, 1, 12, 0, tzinfo=datetime.timezone.utc)
Fetched back: datetime.datetime(2020, 1, 1, 12, 0, tzinfo=tzlocal())
```

# Versions:

* Python 3.7.6
  * elasticsearch==6.3.1
  * elasticsearch-dsl==6.4.0
  * python-dateutil==2.8.1
* Elasticsearch 6.4.0

# Notes:

* Also happens if the `datetime` is created with `tzinfo=dateutil.zoneinfo.tzfile('/usr/share/zoneinfo/UTC')` or if the `datetime` is naive but the `some_time` field is declared with `default_timezone='UTC'`
* Does not happen if the `datetime` is naive and no default timezone is set or if the `datetime` is set to a timezone other than UTC

# Related:

* See also #77

**Comment by miguelgrinberg** [comment]
This must have gotten fixed at some point, because I cannot reproduce using your script:

```
Original object, post-save: datetime.datetime(2020, 1, 1, 12, 0, tzinfo=datetime.timezone.utc)
Fetched back: datetime.datetime(2020, 1, 1, 12, 0, tzinfo=tzutc())
```
