### ISSUE TITLE
Document.to_dict() doesn't contain values created by clean() method

### ISSUE THREAD

**Issue by dpasqualin** [elastic/elasticsearch-dsl-py#1314]
I was trying to apply the "completion" example from https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/completion.py on my data set while using bulk insert to import the data to ElasticSearch, but I noticed that the values generated in the `clean()` method are not exported by the `to_dict(include_meta=True)` method, required to perform bulk insert. The solution is to manually execute `clean` before `to_dict`, but that seems counter intuitive.

Is this a bug or expected behavior? If it is a bug I could try to create a PR.

**Comment by michael-robbins** [comment]
I've just ensured my clean and to_dict both do the same thing, seems to work for me, but it could be better I guess?

```
    def clean(self):
        suggestions = self.string2tokens(self.name)

        if self.acronyms:
          suggestions.extend(self.acronyms)

        self.suggest = {"input": suggestions, "weight": 1}

    def to_dict(self, **kwargs):
        suggestions = self.string2tokens(self.name)

        if self.acronyms:
          suggestions.extend(self.acronyms)

        self.suggest = {"input": suggestions, "weight": 1}
        return super().to_dict(**kwargs)
```

**Comment by dpasqualin** [comment]
Nice suggestion @michael-robbins, maybe you could just call `clean` from inside `to_dict`?

```python
def clean(self):
    suggestions = self.string2tokens(self.name)
    if self.acronyms:
      suggestions.extend(self.acronyms)
    self.suggest = {"input": suggestions, "weight": 1}

def to_dict(self, **kwargs):
    self.clean()
    return super().to_dict(**kwargs)
```

Bur regardless, it seems that `self.clean` should always be called from `to_dict` in the upstream code. Also it would be nice to have some documentation about the uses of this `clean` method, I just found by chance looking at the examples.

**Comment by michael-robbins** [comment]
Yep that would make perfect sense, I don't remember why I chose to duplicate the code, maybe before clean was calling it's own super().clean().

Either way, yes, I'd prefer this to be implemented upstream :D

**Comment by miguelgrinberg** [comment]
Even though this can be considered a bug, changing `to_dict()` to invoke `clean()` may cause existing applications to break. Given that the workaround is fairly simple for now we'll keep the current behavior. If there are situations in which this causes big problems I'm open to revisiting this decision.
