### ISSUE TITLE
how to use retry_on_conflict on update

### ISSUE THREAD

**Issue by zoebraiyan** [elastic/elasticsearch-dsl-py#1316]
retry_on_conflict cannot be used if version number is passed. How to not pass the version number when calling update method on document.

**Comment by burritoIand** [comment]
would like to know as well

**Comment by burritoIand** [comment]
@zoebraiyan I ended up using elasticsearch-py connection.update() directly and retry_on_conflict works properly

**Comment by zhangjustin** [comment]
> @zoebraiyan I ended up using elasticsearch-py connection.update() directly and retry_on_conflict works properly

can you give more details? i quite don't understand, when i use `retry_on_conflict`, always get
```
'action_request_validation_exception', "Validation Failed: 1: can't provide both retry_on_conflict and a specific version;"
```

**Comment by rholloway** [comment]
same issue here. Although retry_on_conflict parameter was added to Document.update() in this library, it seems that version is always passed as well so the problem actually isn't resolved and retry doesn't occur.

**Comment by armando1793** [comment]
I managed to work around this https://github.com/elastic/elasticsearch-dsl-py/issues/1432 by overriding `doc.meta["version"]` but this seems safe only for my use-case
