### ISSUE TITLE
how can I add after-key in my composite aggregation.

### ISSUE THREAD

**Issue by rishi1804** [elastic/elasticsearch-dsl-py#1320]
'aggs': {
    'class': {
      'composite': {
        'size': 1000,
        'sources': [
          {
            'class': {
              'terms': {
                'field': 'class.raw'
              }
            }
          }
        ]
      },

I want to add after-key in this code after the 'sources' in python(elasticsearch_dsl)

**Comment by sethmlarson** [comment]
There's an example on how to scan a composite aggregation: https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/composite_agg.py

**Comment by altaysaid** [comment]
You can do that by using the aggs function on top of the Search function from the elasticsearch_dsl.

Something in the lines of
s = Search(..)
and once you are ready with the query, you can add the composite aggregation in this with:
```
class_statement = A('terms', field ='class.raw')
source = [{'class': class_statement}]
s.aggs.bucket('new_bucket',"composite",sources=source, size=10, after={'class':after_parameter})
```
