### ISSUE TITLE
How do I use retry_on_conflict to resolve error "ConflictError 409" with update()?

### ISSUE THREAD

**Issue by burritoIand** [elastic/elasticsearch-dsl-py#1326]
I noticed that if I send too many requests in a short period, my elasticsearch update code throws a 409 ConflictError. Reading a bit into it, I noticed there is a param for [update()](https://elasticsearch-dsl.readthedocs.io/en/latest/api.html#elasticsearch_dsl.Document.update) to set the number of retry attempts, however when I tried using it, I get another error:
```
RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: compare and write operations can not be retried;')
```

How can I handle 409 ConflictError during frequent updates and/or use the retry_on_conflict param?
```
    thing = Thing.get(id=thing_id, ignore=404)

    if thing:
            return post.update(
                script=update_func,
                refresh=True,
                retry_on_conflict=ES_UPDATE_RETRY_COUNT,
                now=arrow.utcnow().float_timestamp,
            )
```

```
ConflictError: ConflictError(409, 'version_conflict_engine_exception', '[TtWP-la58FPHbw]: version conflict, required seqNo [8], primary term [1]. current document has seqNo [9] and primary term [1]')
(2 additional frame(s) were not displaye
```

**Comment by burritoIand** [comment]
@HonzaKral greetings, just curious if you had any thoughts on how to handle retries or get retry_on_conflict working? thanks

**Comment by burritoIand** [comment]
using elasticsearch-py directly seems to work...
```
            return post._get_connection().update(
                Post.Index().name,
                post_id,
                body,
                refresh=True,
                retry_on_conflict=10,
            )
```

**Comment by 549982170** [comment]
I have the same problem.

**Comment by smurf-U** [comment]
> I have the same problem.

Any update?

**Comment by burritoIand** [comment]
@smurf-U I ended up using above solution

**Comment by smurf-U** [comment]
Hi @burritoIand 

Then how did you handle this scenario?

**Comment by burritoIand** [comment]
@smurf-U 
```
post.update(
                script=update_func,
                refresh=True,
                retry_on_conflict=ES_UPDATE_RETRY_COUNT,
                now=arrow.utcnow().float_timestamp,
            )
```

**Comment by ryonakamura** [comment]
This error seems to occur when adding `if_seq_no` and `if_primary_term` to the `update` arguments.

https://github.com/elastic/elasticsearch-dsl-py/blob/7.3.0/elasticsearch_dsl/document.py#L407

Here's a temporary solution:

```python
del post.meta['seq_no']
del post.meta['primary_term']
post.update(
    retry_on_conflict=10,
    date=datetime.utcnow(),
)
```
