### ISSUE TITLE
scan method returning only 1 record at a time

### ISSUE THREAD

**Issue by agujrathi** [elastic/elasticsearch-dsl-py#1335]
I am using scan method to fetch records. I have given size to 10,000 , still always only 1 record is returned by scan.

Will this speed, its not possible to achieve my moto. 1 record per scan call... not getting where I am doing wrong..

Below is my relevant code.. I dont see any issue in code as such but something nasty is been done.

Also tried with below code..

```
data = []
for hit in s.params(size=1000).scan():
        #print (len(hit.to_dict()))
        data.append(hit.to_dict())
       
```
Also tried below code, still not benifit

```
s = s.params(size=10000)
data = []

  for hit in s.scan(): 
         data.append(hit.to_dict())        
           #print  (hit.to_dict())
```

I am fed up... Suppose I have 1 lakh records.. It goes in loop, 1 lakh time.. Ideally it should go in loop 10 times by fetching 10,000 records each time..
This is going nasty.. Please help guys if its an issue with my code or its a bug ??
Appreciate urgent help on the same..

**Comment by sethmlarson** [comment]
From the Python code perspective the records are returned one at a time in the iterator, `size` determines the number of records that are sent over the wire per HTTP request. So if you set size to 1 or 10000 the function will return one at a time to make writing code with the `scan()` function easier.

**Comment by agujrathi** [comment]
Thanks Sethmlarson for correcting my assumption of scan() .
It helped me..
