### ISSUE TITLE
Unable to use a password for connecting to elasticsearch

### ISSUE THREAD

**Issue by venomone** [elastic/elasticsearch-dsl-py#1338]
I want my Django application to use a password for connecting to the elasticsearch container.
Therefor I set a connection string in my settings.py which was working fine until I setup password authentication for elasticsearch. Currently I get the following error from Django:

>  elasticsearch.exceptions.AuthenticationException:
> AuthenticationException(401, '')

Using curl like this is working fine inside the container:

    curl -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}" "${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT"

But if I set the same env. vars. for the ELASTICSEARCH_DSL config at my settings.py, I simply fail and cannot establish a connection to elasticsearch due to  the auth. failure mentioned above:

    ELASTICSEARCH_DSL = {
        'default': {
            'hosts': env.str('ELASTICSEARCH_USERNAME') + str(':') + env.str('ELASTICSEARCH_PASSWORD') + str('@') + env.str('ELASTICSEARCH_HOST') + str(':') + env.str('ELASTICSEARCH_PORT')
        },
    }

or:

    ELASTICSEARCH_DSL = {
        'default': {
            'http_auth': str('http://') + env.str('ELASTICSEARCH_USERNAME') + str(':') + env.str('ELASTICSEARCH_PASSWORD'),
            'hosts': env.str('ELASTICSEARCH_HOST') + str(':') + env.str('ELASTICSEARCH_PORT'),
        },
    }

or

    ELASTICSEARCH_DSL = {
        'default': {
            'hosts': str('http://') + env.str('ELASTICSEARCH_USERNAME') + str(':') + env.str('ELASTICSEARCH_PASSWORD') + str('@') + env.str('ELASTICSEARCH_HOST') + str(':') + env.str('ELASTICSEARCH_PORT'),
        },
    }

Is the syntax here maybe wrong for : or @ at the connection string? I already searched the docs and web on this but was not able to find a solution till now.

**Comment by cj564932957** [comment]
connections.create_connection(hosts='localhost', http_auth=("admin", "admin"))
or 
client=Elasticsearch(host="localhost",http_auth) #by elasticsearch-py

**Comment by venomone** [comment]
Okay and where did you placed this code? Sorry if this question might seem stupid.

**Comment by quiin** [comment]
If you're using django, probably the best place to put it is on your `settings.py` file.
Alternatively , there's a wrapper around this library written for django. Here's the [link](https://github.com/sabricot/django-elasticsearch-dsl) in case you wanna take a look at it.

**Comment by cj564932957** [comment]
The simplest example is use connection.configure in your django's settings.py ,because 
class Connections(object):
    """
    Class responsible for holding connections to different clusters. Used as a
    singleton in this module.
    """ 


eg:
in settiings.py
connections.configure(**{
    'default': {
        'hosts': 'localhost:9200',
        'http_auth': ("admin", 'admin')
    },
})

**Comment by venomone** [comment]
Sorry but I still don't understand how to adopt this, your current example results in:

`TypeError: configure() argument after ** must be a mapping, not NoneType`


I Also tried the following with no success as this makes the most sense to me at the moment:

```
elastic_connection = 'elasticsearch://{user_name}:{password}@{host_ip}:{host_port}'.format(user_name=env.str('ELASTICSEARCH_USERNAME'),
password=env.str('ELASTICSEARCH_PASSWORD'),
host_ip=env.str('ELASTICSEARCH_HOST'),
host_port=env.str('ELASTICSEARCH_PORT')),

ELASTICSEARCH_DSL = {
    'default': {
        'hosts': [elastic_connection]
    },
}
```

**Comment by quiin** [comment]
Try this:
```python
#  settings.py
...
es_user = env.str('ELASTICSEARCH_USERNAME')
es_pass = env.str('ELASTICSEARCH_PASSWORD')

ELASTICSEARCH_DSL = {
    'default': {
        'host':  env.str('ELASTICSEARCH_HOST'),
        'port': env.str('ELASTICSEARCH_PORT'),
        'http_ath': (es_user, es_pass)
  }
}
```
After all, what the ELASTICSEARCH_DSL variable in `settings.py` represents is the arguments to create a low-level [elasticsearch client ](https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch). These arguments may vary between the connection classes used (default: [Urllib3HttpConnection](https://elasticsearch-py.readthedocs.io/en/master/connection.html#elasticsearch.Urllib3HttpConnection))

**Comment by venomone** [comment]
Still resulting in `elasticsearch.exceptions.AuthenticationException: AuthenticationException(401, '')`
Really I don't get this. Is http_auth simply not passed or what ?!

**Comment by quiin** [comment]
I doubt it's an issue with the wrapper since all of the connection details are delegated to the low-level client. Unless you are you indeed able to create a low-level [elasticsearch client ](https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch)

Some other things that might help troobleshooting are:
- The env. variables are set in place and available from python
- The container or environment can indeed access the elasticsearch cluster
- If you're trying to connect to an AWS elasticsearch cluster: [check this out](https://gist.github.com/simonw/f99c70588f4d7447a223)
- If you disable authentication on your server (i.e no username/password are needed), can you stablish a connection? If you can't, maybe the hostname is the error

**Comment by venomone** [comment]
If I disable auth I can use elasticsearch as expected with the DSL wrapper, its really just about the authentication mechanism it seems. I'm on docker not AWS (local Linux Workstation) running everything from docker-compose.yml
I'm using elasticsearch 7.6.1 like so:

```
  elasticsearch:
    image: elasticsearch:7.6.1
    container_name: ${ELASTICSEARCH_HOST}
    hostname: ${ELASTICSEARCH_HOST}
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200
    networks:
      - backend
    labels:
      - "traefik.enable=false"
```

And as already mentioned, with curl I can access the elasticsearch container with no problems using a password.

**Comment by quiin** [comment]
I see. It does look like it's just a matter of authentication as you mention.
Can you give this a shot?
```python
#  settings.py
from elasticsearch import RequestsHttpConnection
...
es_user = env.str('ELASTICSEARCH_USERNAME')
es_pass = env.str('ELASTICSEARCH_PASSWORD')

ELASTICSEARCH_DSL = {
    'default': {
        'host':  env.str('ELASTICSEARCH_HOST'),
        'port': env.str('ELASTICSEARCH_PORT'),
        'http_ath': (es_user, es_pass),
        'connection_class': RequestsHttpConnection
  }
}
```

As a side-note: you can create the low-level client by doing:
```python
from elasticsearch import Elasticsearch, RequestsHttpConnection

config = {
    'host': XXX,
    'port': YYY,
    'http_auth': (UUU, PPP),
    'connection_class': RequestsHttpConnection  # Try it with and without this parameter
}

client = Elasticsearch(**config)
```

**Comment by quiin** [comment]
I believe you're also allowed to provide a full url and not just a hostname

```python
es_host = env.str('ELASTICSEARCH_HOST')
es_port = env.str('ELASTICSEARCH_PORT')
es_user = env.str('ELASTICSEARCH_USERNAME')
es_pass = env.str('ELASTICSEARCH_PASSWORD')

ELASTICSEARCH_DSL = {
    'default': {host':   f'http://{es_user}:{es_pass}@{es_host}:{es_port}'}
}
```

**Comment by jerinpetergeorge** [comment]
@venomone 
from the discussion in [SO thread](https://stackoverflow.com/questions/61120781/django-setup-elasticsearch-client-with-password-auth), he (or you) experienced the **`AuthenticationException(401, '')`** exception, which indicates the *credentials mismatch*. I strongly suggest you to check the *generated URL value* and make sure it is correct.

I have used the below settings and it works.
```python
elk_base_url = 'elasticsearch://{user_name}:{password}@{host_ip}:{host_port}'
elastic_search_url = elk_base_url.format(user_name='my_username',
                                         password='mysecret_password',
                                         host_ip='my-elastic-host-ip',
                                         host_port=9200)
ELASTICSEARCH_DSL = {
    'default': {
        'hosts': [elastic_search_url]
    },
}
```

**Comment by venomone** [comment]
Hello everybody,

first of all thanks for all your time on helping me out here, really appreciate that!
I was now able to test out all solution, I also tired inserting the variables values directly instead of getting them from a env var. Sadly this still results in the 401 behaviour for no reason, I already rebuild all my containers with no effect (read on!).

I tried the following at settings.py so far:

1. Solution
```
es_user = env.str('ELASTICSEARCH_USERNAME')
es_pass = env.str('ELASTICSEARCH_PASSWORD')

ELASTICSEARCH_DSL = {
    'default': {
        'host':  env.str('ELASTICSEARCH_HOST'),
        'port': env.str('ELASTICSEARCH_PORT'),
        'http_ath': (es_user, es_pass),
        'connection_class': RequestsHttpConnection
  }
}
```
2. Solution

```
es_host = env.str('ELASTICSEARCH_HOST')
es_port = env.str('ELASTICSEARCH_PORT')
es_user = env.str('ELASTICSEARCH_USERNAME')
es_pass = env.str('ELASTICSEARCH_PASSWORD')

ELASTICSEARCH_DSL = {
    'default': {'host':   f'http://{es_user}:{es_pass}@{es_host}:{es_port}'}
}

# @quiin: There was a typo error at you code, I corrected.
```

3. Solution

```
elk_base_url = 'elasticsearch://{user_name}:{password}@{host_ip}:{host_port}'
elastic_search_url = elk_base_url.format(user_name='my_username',
                                         password=urlquote('mysecret_password'),
                                         # password may contain special characters
                                         host_ip='my-elastic-host-ip',
                                         host_port=9200)
ELASTICSEARCH_DSL = {
    'default': {
        'hosts': [elastic_search_url]
    },
}
```

This happens while the application starts!

I came to the point that this Issue might also be related to the index itself as I check for the Index on application startup like so:

Step 1 - check if instance is reachable (working with auth)

echo "Checking if Elasticsearch is up"
```
{
until (curl -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}"  "${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"); do
    printf "App - Waiting for elasticsearch to be available"
    sleep 5
done
}

Step 2 - Check if Index is available (Not working with auth)
```
echo "Checking if Elasticsearch index is setup" -> Here we actually failing it seems, with the same trace as shown above.
{
```
cat <<EOF | python /app/manage.py shell
from elasticsearch import Elasticsearch
HOST_URLS = ["${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}@$ELASTICSEARCH_HOST:$ELASTICSEARCH_PORT"]
es_conn = Elasticsearch(HOST_URLS)
INDEX_NAME = "posts"
res = es_conn.indices.exists(index=INDEX_NAME)

if res == True:
  print("Elasicsearch index seems already setup, skipping")
else:
  print("Elasicsearch index not setup yet, creating ...")
  import subprocess
  subprocess.Popen("python manage.py search_index --create", shell=True, stdout=subprocess.PIPE).communicate()[
                0].decode('utf-8').strip()
EOF
}
```
To me it seems that im running into this issue because the connection already fails on start-up at my second step where I want to create the index. Seems i'm not passing the vaiables right here to establish a authenticated connection.
I guess after this is fixed all the stuff at settings.py will work.
Any sugestions for the last code snipped and how to peroperly pass the authentication there?

Sorry for this stupid misunderstanding but to me it first has looked like it came from settings.py.

Interpreter version

- python:3.8.2

Package versions:

- Django==3.0.5
- django-elasticsearch-dsl==7.1.1
- elasticsearch==7.6.0
- elasticsearch-dsl==7.1.0

Full trace:


```
app              | Traceback (most recent call last):
app              |   File "/app/manage.py", line 17, in <module>
app              |     execute_from_command_line(sys.argv)
app              |   File "/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
app              |     utility.execute()
app              |   File "/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
app              |     self.fetch_command(subcommand).run_from_argv(self.argv)
app              |   File "/venv/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
app              |     self.execute(*args, **cmd_options)
app              |   File "/venv/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
app              |     output = self.handle(*args, **options)
app              |   File "/venv/lib/python3.8/site-packages/django/core/management/commands/shell.py", line 92, in handle
app              |     exec(sys.stdin.read())
app              |   File "<string>", line 5, in <module>
app              |   File "/venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
app              |     return func(*args, params=params, headers=headers, **kwargs)
app              |   File "/venv/lib/python3.8/site-packages/elasticsearch/client/indices.py", line 304, in exists
app              |     return self.transport.perform_request(
app              |   File "/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 355, in perform_request
app              |     status, headers_response, data = connection.perform_request(
app              |   File "/venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 248, in perform_request
app              |     self._raise_error(response.status, raw_data)
app              |   File "/venv/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 243, in _raise_error
app              |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
app              | elasticsearch.exceptions.AuthenticationException: AuthenticationException(401, '')

```

**Comment by cj564932957** [comment]
You need to use connections.configure(**kwargs)  in your settings.py to instantiate a connection object,
connections.configure(**ELASTICSEARCH_DSL)

eg：
# settings.py 
ELASTICSEARCH_DSL = {
    'default': {
        'hosts': '192.168.0.50:80/es',
        'http_auth': ("admin", 'admin')
    },
}
from elasticsearch_dsl.connections import connections
connections.configure(**ELASTICSEARCH_DSL)

**Comment by cj564932957** [comment]
You can take a look at the connection.py file of elasticsearch_dsl, here will generate a connection object in singleton mode

**Comment by venomone** [comment]
@cj564932957: finally, that has worked! My code at settings.py now looks like:

```
ELASTICSEARCH_DSL = {
    'default': {
        'hosts': env.str('ELASTICSEARCH_HOST') + ':' + env.str('ELASTICSEARCH_PORT'),
        'http_auth': (env.str('ELASTICSEARCH_USERNAME') + ':' + env.str('ELASTICSEARCH_PASSWORD'))
    }
}

connections.configure(**ELASTICSEARCH_DSL)
```
My startup checks now look like:

```
echo "Checking if Elasticsearch is up"
{
until (curl -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}" --output /dev/null --silent --head --fail "${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"); do
    printf "App - Waiting for elasticsearch to be available"
    sleep 5
done
}

echo "Checking if Elasticsearch index is setup"
{
cat <<EOF | python /echo/manage.py shell
from elasticsearch import Elasticsearch
HOST_URLS = ["$ELASTICSEARCH_USERNAME:$ELASTICSEARCH_PASSWORD@$ELASTICSEARCH_HOST:$ELASTICSEARCH_PORT"]
es_conn = Elasticsearch(HOST_URLS)
INDEX_NAME = "posts"
res = es_conn.indices.exists(index=INDEX_NAME)

if res == True:
  print("Elasicsearch index seems already setup, skipping")
else:
  print("Elasicsearch index not setup yet, creating ...")
  import subprocess
  subprocess.Popen("python manage.py search_index --create", shell=True, stdout=subprocess.PIPE).communicate()[
                0].decode('utf-8').strip()
EOF
}

```
Thank you all very very much!

**Comment by tofbang** [comment]
Very usefull solution
