### ISSUE TITLE
TypeError: type() argument 1 must be string, not unicode

### ISSUE THREAD

**Issue by sim0nx** [elastic/elasticsearch-dsl-py#134]
Hi,

The latest master revision does not work anymore on python2.
Simply importing modules fails:
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from elasticsearch_dsl import Search, Q
<type 'unicode'>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "elasticsearch_dsl/__init__.py", line 1, in <module>
    from .query import Q
  File "elasticsearch_dsl/query.py", line 120, in <module>
    qclass = _make_dsl_class(Query, qname, params_def)
  File "elasticsearch_dsl/utils.py", line 24, in _make_dsl_class
    return type(cls_name, (base, ), attrs)
TypeError: type() argument 1 must be string, not unicode

The problem is on line 23 in the file "elasticsearch_dsl/utils.py". Here the first part of the string is converted to "str", but suffix is a unicode.
Thus the proposed fix would be to convert suffix to "str" as well, which does fix the issue.

If you agree I can make a pull request.

**Comment by sim0nx** [comment]
I just see that there is already a pull request for this #133

**Comment by HonzaKral** [comment]
This was indeed fixed in #133 by @benjaminrigaud, thanks!
