### ISSUE TITLE
Multiple OR cases with multiple AND

### ISSUE THREAD

**Issue by Shivendra2407** [elastic/elasticsearch-dsl-py#1340]
I have a document whose fields are as below:
field1 = [1,2,3,4,5]
field2 = [a,b,x,y]
field3 = [alpha, beta]
I have to query something like :
(field1 = 1 OR field1 = 2) AND (field2 = a) AND (field3 = alpha OR field3 = beta)

I am using elasticsearch-dsl-py 6.2 version, elasticsearch 6.3.2 version.

I am not able to wrap my head around how I would use this query build up in python library elasticsearch-dsl-py. Any help is appreciated.

**Comment by sethmlarson** [comment]
Use `elasticsearch_dsl.Q(name, **parameters)` to create a single filter, then combine them using `&` (AND) and `|` (OR)
