### ISSUE TITLE
Autodoc for Document fields

### ISSUE THREAD

**Issue by quiin** [elastic/elasticsearch-dsl-py#1341]
I'm trying to generate documentation for my documents with autodoc & sphinx; unfortunately I'm stuck with it. For some reason pretty much all other classes/values work just fine except for `Field` descendants

```python
import elasticsearch_dsl
class Foo(elasticsearch_dsl.Document):
    bar = elasticsearch_dsl.Text()  # Not generated; descendant of `Field`
    baz = elasticsearch_dsl.field.DslBase('baz')  # Does generate documentation
```
Has somebody been able to generate documentation for their documents?

**Comment by sethmlarson** [comment]
Try this:

```
class MyDoc(Document):
    #: This is the docstring for 'bar'
    bar = field.Text()
```

See Sphinx docs below here: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-autoattribute
