### ISSUE TITLE
Supporting script_score Query in DSL (not FunctionScore)

### ISSUE THREAD

**Issue by mhnamaki** [elastic/elasticsearch-dsl-py#1344]
Hey,
I have checked both [docs ](https://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html) and [tests ](https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_query.py) available for the project. However, I couldn't find a way to formulate a `script_query` that does not have any `function_score`.

Indeed, let's assume I have the following desired query packed in a dictionary, how could I'd written it using `elasticsearch_dsl`?

```
query_dict = {
            "query": {
                "script_score": {
                    "query": Q(...)
                },
                "script": {
                    "source": "..."
                }
            }
        }
```

[Link to `script_score `query in ElasticSearch that does not use`function_score`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-script-score-query.html)

**Comment by ronaktanna1** [comment]
Is there any update on this?

**Comment by sethmlarson** [comment]
Closed in https://github.com/elastic/elasticsearch-dsl-py/pull/1464
