### ISSUE TITLE
Does this project follow semantic versioning?

### ISSUE THREAD

**Issue by alvassin** [elastic/elasticsearch-dsl-py#1348]
Can i use this project with `~=` operator?
 
```
elasticsearch-dsl~=7.1.0
```

Does it follow [Semantic versioning](https://semver.org)?

**Comment by sethmlarson** [comment]
This project follows the Elastic Stack version as it's major but also follows semantic versioning. So the `7` is the Elastic Stack major version and there also won't be any breaking changes across all of 7.x.

Does that answer your question?

**Comment by alvassin** [comment]
Yes, thank you very much.
