### ISSUE TITLE
Add support for geotile_grid aggregations

### ISSUE THREAD

**Issue by owrcasstevens** [elastic/elasticsearch-dsl-py#1349]
Currently using version 7.1 of elasticsearch-dsl, but `geotile_grid` aggregations do not seem to be supported.  When I do:

`grid_agg = search.aggs.bucket("grid", "geotile_grid", field="centroid", precision=2)`

I am getting:
```
raise UnknownDslObject('DSL class `{}` does not exist in {}.'.format(name, cls._type_name))
```

Digging into the code a bit, it seems that the following aggs are supported:
```
filter
filters
children
parent
date_histogram
auto_date_histogram
date_range
geo_distance
geohash_grid
geo_centroid
global
histogram
ip_range
missing
nested
range
reverse_nested
significant_terms
significant_text
terms
sampler
diversified_sampler
composite
top_hits
avg
weighted_avg
cardinality
extended_stats
geo_bounds
max
min
percentiles
percentile_ranks
scripted_metric
stats
sum
value_count
avg_bucket
bucket_script
bucket_selector
cumulative_sum
derivative
extended_stats_bucket
max_bucket
min_bucket
moving_fn
moving_avg
percentiles_bucket
serial_diff
stats_bucket
sum_bucket
bucket_sort
```

But `geotile_grid` is not in there, which is surprising since Kibana switched to using `geotile_grid` aggs for maps:
https://github.com/elastic/kibana/issues/30417

**Comment by sethmlarson** [comment]
Agreed this would be great to add. My dev time is being spent elsewhere currently but eventually I'll get to this.

In the meantime if you're up to it I can review a submitted PR :)

**Comment by mbarretta** [comment]
@owrcasstevens is the lower-level [elasticsearch-py](https://github.com/elastic/elasticsearch-py) and option? I'm not a python guy, but it seems you could use the [search](https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.search) method to form up the `geotile_grid` agg in json.
