### ISSUE TITLE
Search "from_dict" function resets the index

### ISSUE THREAD

**Issue by shashankparewar** [elastic/elasticsearch-dsl-py#1351]
I am using the "from_dict" function for creating a new search object.

I do it like this:
```
from elasticsearch_dsl import Search
s = Search(index=["local-products"])      
s.from_dict({"query": { 
                        "bool": { 
                            "must": [] 
                        } 
                    }, 
                    "aggs": {} 
               }) 
```

The issue is the index name is reset to None which is causing the search to expand to all indices.
The code issue is in **elasticsearch_dsl/search.py** line:375
```
s = cls()
s.update_from_dict(d)
return s
```
the new initialization should atleast pass the index name. I can raise a PR for this if you think the use case is valid.
Or suggest a good workaround for this.

**Comment by sethmlarson** [comment]
`Search.from_dict()` is a `classmethod` so should be used via `Search.from_dict()` not `Search().from_dict()`

**Comment by shashankparewar** [comment]
ok can we provision to pass index to this function - 
I am not getting how to use the Search object returned by from_dict and then assign an index to it

**Comment by nepython** [comment]
@shashankparewar, I navigated around this issue by directly using [Search(index=['your-index']).update_from_dict](https://elasticsearch-dsl.readthedocs.io/en/latest/api.html?highlight=update_from_dict#elasticsearch_dsl.Search.update_from_dict) which is ultimately used by `Search.from_dict`. Besides being unable to pass **index**, another limitation is inability to pass **using** when using the classmethod `from_dict`. Hope that helps :smile:
