### ISSUE TITLE
RequestError: Fuzziness not allowed for type [phrase]

### ISSUE THREAD

**Issue by helmersl** [elastic/elasticsearch-dsl-py#1354]
I'm trying to use fuzziness with a multi_match query but it gives me the following error:

`RequestError: RequestError(400, 'parsing_exception', 'Fuzziness not allowed for type [phrase]')`

I'm using ElasticSearch version 6.3.1
`elasticsearch_dsl.__version__` gives `(6, 3, 1)`

This is how I'm implementing the query:

`s = Search(using=connection, index=index, doc_type="doc")
    q = Q({"multi_match": {"query": search_term, "fields": search_fields, "type":"phrase",
                           "slop":slop ,"fuzziness": 2,"minimum_should_match":minimum_should_match, "analyzer":analyzer}})
    s = s.query(q)`

Is there a way to implement fuzziness in the multi_match query?
Thanks in advance!

**Comment by sethmlarson** [comment]
I don't think the `fuzziness` parameter is support for `phrase` matches, don't think this is a defect in elasticsearch-dsl.
