### ISSUE TITLE
can i use multi_match in nested 

### ISSUE THREAD

**Issue by poetL** [elastic/elasticsearch-dsl-py#1361]
```filter('multi_match', query='test_nested', fields=["title", "check_form.title", 'check_form.desc','check_form.tags'])```

I can't use a filter like this to query that the results don't exist

```    title = Text(fields={'keyword': Keyword()})
    type = Text(fields={'keyword': Keyword()}, required=True)  
    check_form = Nested()
```

**Comment by chiemerieokorie** [comment]
How was this resolved?
