### ISSUE TITLE
Python-run query returns less documents that the same query in Kibana

### ISSUE THREAD

**Issue by nkakouros** [elastic/elasticsearch-dsl-py#1363]
This is very weird. I have 6 indexes named 'filebeat-2020.05.10' to 'filebeat-2020-05-15'. There are 18 docs in those indexes that interest me. Only indexes on the 10th, 11th, 13th, 14th contain these docs The other two (12, 15), do not.

I create a query using the dsl library, execute it (with the `execute()` method) and get back 10 of those, while I am expecting all 18 back.

I use `to_dict()` to print the search object right before execution and I get this:

```
{'query': {'bool': {'filter': [{'bool': {'minimum_should_match': 1,
 'must': [{'term': {'agent.type': {'value': 'filebeat'}}},
			{'term': {'openvpn.common_name': {'value': 'common-name'}}}],
'should': [{'term': {'openvpn.event': {'value': 'client-connected'}}},
			{'term': {'openvpn.event': {'value': 'client-disconnected'}}}]}}]}}}
```

I copy the query string, replace single quotes with double quotes:

```json
GET _search
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "minimum_should_match": 1,
            "must": [
              {
                "term": {
                  "agent.type": {
                    "value": "filebeat"
                  }
                }
              },
              {
                "term": {
                  "openvpn.common_name": {
                    "value": "blueprint-s7"
                  }
                }
              }
            ],
            "should": [
              {
                "term": {
                  "openvpn.event": {
                    "value": "client-connected"
                  }
                }
              },
              {
                "term": {
                  "openvpn.event": {
                    "value": "client-disconnected"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

and run the query in Kibana's debug tools (at `_search`). There I get all 18 docs back! The python-run query ignores the docs in the `2020-05-14` index (`2020-05-15` contains no relevant docs). But, unless I miss something, it is the exact same query.

I check that in my python app I do not set a weird index pattern, I also check if setting the index to `*` fixes this but it doesn't. 

I also try with each of the indexes one by one. In this case, I get back the docs correctly! When querying the index of `2020-05-14` I get back the 8 docs it contains. 

I clear the elasticsearch cache (`GET _cache/clear`), try again, the same thing happens. I also set `ignore_cache=True` to `execute()`, it doesn't help.

I use kibana's discover page and get back all 18 documents.

I delete all indexes before the 14th, re-run my python app and I get back the 8 docs the `2020-05-14` index contains.

All indexes have been created using the same index template, I didn't change or upgrade anything. Also, the same user is used by both Kibana and the python app.

Has anyone experiences sth similar? What can this behavior be due to?

**Comment by sethmlarson** [comment]
10 is the default amount returned by a query. If you want all matching documents to be returned you can use `.scan()` or you can receive more documents by changing `size`.
