### ISSUE TITLE
How to add source filtering when paginating using scroll

### ISSUE THREAD

**Issue by 7xMind** [elastic/elasticsearch-dsl-py#1371]
There's this nice support when building the search object which allows for source filtering (including or excluding specific field results) as such:

```
# only return the selected fields
s = s.source(['title', 'body'])
# don't return any fields, just the metadata
s = s.source(False)
# explicitly include/exclude fields
s = s.source(includes=["title"], excludes=["user.*"])
# reset the field selection
s = s.source(None)
```

But, I'm executing my queries through `client.search `and `client.scroll` for subsequent requests as follows:

```
query = Q()
response = client.search(index='index_name', body=query, scroll='5m')

```
and for subsequent requests:

`response = client.scroll(scroll_id='some scroll id', scroll='5m')
`
Is there any ways to use the include exclude feature with the scrolling?

**Comment by sethmlarson** [comment]
`Document.scan()` implements this I believe, you shouldn't need to change the `_source` once the scan has started.
