### ISSUE TITLE
Support for constant_keyword

### ISSUE THREAD

**Issue by beanaroo** [elastic/elasticsearch-dsl-py#1373]
When trying to add a field of type [constant_keyword](https://www.elastic.co/guide/en/elasticsearch/reference/7.7/constant-keyword.html) to a Mapping, an exception is returned:

```
DSL class `constant_keyword` does not exist in field.
```

**Comment by beanaroo** [comment]
Creating a custom field using:
```python
class ConstantKeyword(Keyword):
    name = 'constant_keyword'
```
and then 

```python
mapping.field('service_name', ConstantKeyword(value=svc_name))
```
Seems to result in the correct mapping being applied. Not sure if this is the right way to do it.

From https://github.com/elastic/kibana/issues/52635, it turns out Kibana does not yet support the type either, so it is not that useful to us at the moment.

**Comment by sethmlarson** [comment]
Thanks for identifying this, would you be up to creating a PR with the feature and a test case?

**Comment by beanaroo** [comment]
@sethmlarson I'm definitely willing to contribute! I'll try to find some time this week.

**Comment by brainix** [comment]
@beanaroo - I'm also willing to help! It's your find, so I'll let you take the lead on this. But if you want my help (or if you can't find time to whip up a PR), feel free to ping me.

**Comment by 1Mark** [comment]
would be nice to have some documentation for this field
