### ISSUE TITLE
highlight meta is not available in response

### ISSUE THREAD

**Issue by sachindixit** [elastic/elasticsearch-dsl-py#1376]
response = Search_Dsl(index=index_name).query(q).highlight('fieldName',fragment_size=50).source(includes=self.source_includes,excludes=self.source_excludes)[start_counter:end_counter].execute()

for hit in response:
    for fragment in hit.meta.highlight.fieldName:
        print(fragment)

this gives error message --
'HitMeta' object has no attribute 'highlight'

**Comment by sachindixit** [comment]
I followed this issues --
https://github.com/elastic/elasticsearch-dsl-py/issues/259

and this doc -- 
https://elasticsearch-dsl.readthedocs.io/en/latest/api.html?highlight=highlight#elasticsearch_dsl.Search.highlight

but that did not help.
code is still throwing error :
'HitMeta' object has no attribute 'highlight'

**Comment by sethmlarson** [comment]
Thanks for opening this! Could you provide more information about your environment like Python version, Elasticsearch-DSL version, Elasticsearch cluster version etc?

**Comment by sachindixit** [comment]
**Python 3.7.3**

Django==3.0.3
django-elasticsearch-dsl==7.1.1
django-elasticsearch-dsl-drf==0.20.5
elasticsearch==7.5.1
elasticsearch-dsl==7.1.0

**Comment by sachindixit** [comment]
**Elasticsearch cluster version  v 7.4.2**

**Comment by sachindixit** [comment]
While testing this with devtools on kibana, I can see the **highlight** meta.
Only when i use Elastic Search DSL library with Python code this **highlight**  meta is not available in response.

**Comment by sachindixit** [comment]
Identified the issue. 
highlight works only if we pass the search fieldname string exactly as per the search performed.

just **fieldName** will not work if we do search using  **fieldName.normalize**  or  **fieldName.keyword**

**Comment by sethmlarson** [comment]
@sachindixit Glad you found a resolution here, thank you for posting for others to find as well!

**Comment by sachindixit** [comment]
I was using keyword search so then new code is 

`response = Search_Dsl(index=index_name).query(q).highlight('fieldName.keyword',fragment_size=50).source(includes=self.source_includes,excludes=self.source_excludes)[start_counter:end_counter].execute()`
