### ISSUE TITLE
http_auth is expiring, cannot find a way to update the creds periodically

### ISSUE THREAD

**Issue by kurtwheeler** [elastic/elasticsearch-dsl-py#1377]
I'm configuring the default configuration for the elasticsearch_dsl like so: https://github.com/AlexsLemonade/resources-portal/pull/214/files#diff-3c54954fe0a7a46c5c9d115d3186e54cR57

However whenever I deploy this to AWS, it works only until that authentication token expires. I believe that what I am supposed to do is get a new one and update it. However I cannot figure out a way to refresh the token periodically. Is there a recommended approach for doing so?

Thank you!

**Comment by sethmlarson** [comment]
This seems like more of an Amazon authentication question than something relevant to Elasticsearch-DSL itself, is that correct? If so I don't think I'm the authority to answer that question. Going to close this for now, I will reopen if this is actually an issue with the library.

**Comment by kurtwheeler** [comment]
I would not agree with that assessment. It seems like a good security practice for authentication tokens to expire. I don't want amazon to give me a token that doesn't expire, seems like a bad idea.

What I do want is a mechanism within Elasticsearch-DSL where I can handle the case when the tokens do expire and set a new one. As far as I can tell, once I configure my elasticsearch settings, they're stuck like that for the lifetime of my app.

Ideally this would work by setting some kind of handler for when the token does expire or maybe by allowing me to provide a function that will be called on a periodic basis to refresh the authentication token before it expires.
