### ISSUE TITLE
Search Execute method is bringing some documents with out any query

### ISSUE THREAD

**Issue by srijiths** [elastic/elasticsearch-dsl-py#1384]
I have simply created a connection using Search and with out specifying any queries , its bringing some documents from elasticsearch index.

```
search_req = Search(using=es, index=meta_content_index)
response = search_req.execute()

results = []
for hit in response:
    try:
        result_json = {}
        result_json = hit.to_dict()
        results.append(json.dumps(result_json))
    except Exception as e:
        print('Eception in hit')
print("Results Length : ", len(results))
```
This gives me the result lenght as "Results Length :  10"

**Comment by sethmlarson** [comment]
An empty search uses the `match_all` query by default so this seems expected. Let me know if you have additional information that points to this being a defect.

**Comment by srijiths** [comment]
@sethmlarson Currenly i have validation checks to make sure search request is not empty. If you have that in the application, then this is fine.
