### ISSUE TITLE
No max_input_length in Completion

### ISSUE THREAD

**Issue by aninda052** [elastic/elasticsearch-dsl-py#1385]
As there is no max_input_length field for Completion, it's always use default value for max_input_length,which in 50 .
But i need to increase that value .

**Comment by sethmlarson** [comment]
Tried the following and seemed to give the correct result:

```python
from elasticsearch_dsl import Completion
field = Completion(max_input_length=50)
print(field.to_dict())
# {'max_input_length': 50, 'type': 'completion'}
```

is this also what you're seeing? Closing this for now
