### ISSUE TITLE
buckets_path aggregation does not exist for aggregation

### ISSUE THREAD

**Issue by sorted78** [elastic/elasticsearch-dsl-py#1386]
Hi, I have a basic aggregation query which failing with this error 

elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'buckets_path aggregation does not exist for aggregation [TPS_max]: TPS_temp>TPS')

The aggregation query is this 

`                body = '{   
                    "size":0,
                      "query": {
                        "bool": {   
                          "must":[ {"range": {"@timestamp":{"gt":"now-10m","lte":"now"}}},
                                   {"query_string":{"query":"host.keyword:%s"}}]
                        }
                      },
                    "aggs":{
                      "TPS_temp": {
                        "date_histogram":{ 
                          "field":"@timestamp","interval":"1s","min_doc_count":1},
                    "aggs":{
                      "TPS":{
                        "value_count":{ 
                          "field":"@timestamp"}
                          }
                        }
                    },
                    "TPS_max":{ 
                      "stats_bucket":{
                        "buckets_path":"TPS_temp>TPS"}
                        }
                      }
                    }'`

And my code is this - what I'm I doing wrong?

`a = A('date_histogram', field='@timestamp', interval='1s', min_doc_count=1)
b = A('value_count', field='@timestamp')
c = A('stats_bucket', buckets_path='TPS_temp>TPS')

s = Search(using=es, index=_index) \
    .filter('range', **{ '@timestamp': { 'gt':'now-1m', 'lte':'now' }} ) \
    .query('match', host=host)

s = s[:0]

s.aggs.bucket('TPS_temp',a) \
    .bucket('TPS',b) \
    .pipeline('TPS_max', c) \`

**Comment by sethmlarson** [comment]
Your code provided doesn't work because `value_count` isn't a bucketing aggregation.

Is this more what you're looking for?

```python
a = A('date_histogram', field='@timestamp', interval='1s', min_doc_count=1)
b = A('value_count', field='@timestamp')
c = A('stats_bucket', buckets_path='TPS_temp>TPS')

s = Search().filter('range', **{'@timestamp': {'gt': 'now-1m', 'lte': 'now'}}).query('match', host="google.com")
s = s[:0]

bucket = s.aggs.bucket('TPS_temp', a)
bucket.metric('TPS', b)
bucket.pipeline('TPS_max', c)
```
