### ISSUE TITLE
Cannot add document with empty list

### ISSUE THREAD

**Issue by JerzySpendel** [elastic/elasticsearch-dsl-py#1388]
I have a schema of a document like this:
```
class Product(Document):
    name = Text()
    skus = Keyword()
    price = Float()
    weight = Text()
    ingredients = Text()
    additive = Nested()
```

Later on I create a bunch of instances of that class like:

```
products = [Product(name=element["name"],
                    skus=(),
                    price=element["price"],
                    weight=element['weight'],
                    ingredients=element['raw_ingredients'] or '',
                    additive=()) for element in data]
```

Later I save each of these products and I have no `additive` property, but on the other hand it works fine for `skus` property. If I change additive to be `Keyword()` instead of `Nested()` it works fine, but why I shouldn't be able to set empty list on a Nested field?

**Comment by JerzySpendel** [comment]
Could you confirm that either I do something incorrectly or it's a bug?

**Comment by JerzySpendel** [comment]
I've tried using `[]` instead of `()` but then it works even worse, then it stops working even for `skus` key

**Comment by sethmlarson** [comment]
I was able to get both of these instances to work with `skip_empty=False`:

```python
from elasticsearch_dsl import Document, field, connections
connections.create_connection(hosts="localhost:9200")

class Product(Document):
    skus = field.Keyword()
    additive = field.Nested()

    class Index:
        name = "test-products"

Product.init()

p = Product(skus=[], additive=[])
p.save(skip_empty=False)

p = Product(skus=(), additive=())
p.save(skip_empty=False)
```
