### ISSUE TITLE
possible to make doctype 'aware' of its version, and increment on save()?

### ISSUE THREAD

**Issue by brizzbane** [elastic/elasticsearch-dsl-py#139]
I don't know how version'ing works with elasticsearch, but if its just an 'id' in _source, would you consider maybe increment on save()?  

My use case is this.  I currently pass a DocType to a class, and in __init__, I do document.in_use = True, document.save()

So I am getting exceptions of the version being one off.  The alternative for me right now is to just .get() the document right after save.

**Comment by HonzaKral** [comment]
Version is automatically tracked - when calling save it is sent to elasticsearch, if present, and as part of the save the new version is set to the `meta` attribute.

I added a bunch of tests in 5da24f35c79123178a949dfefcb0ab440ebf434a to demonstrate this behavior.

From what I understand the library already does what you are looking for. Or am I missing something?

**Comment by brizzbane** [comment]
I'm calling save() on __exit__, but I'm also using it with celery, so I guess thats probably the issue.  Have been getting really odd behavior at times when using with celery :\.

**Comment by HonzaKral** [comment]
I am afraid I don't understand exactly what it is you are looking for, could you explain your use case, or some examples of how you'd want it to behave?

Thanks!

**Comment by brizzbane** [comment]
It sounds like it already supports what I was thinking it needed.

Where I'm getting exceptions now is when using celery (@app.task def a _function(doctype_document).  and I save the document in_use = True() on init, and on exit in_use = False()

if I don't .get() the document after I save it (on __init__--saying its in use), will get exceptions @ __exit__ (in_use = False()) saying the version is off.  So I thought maybe module needed what I proposed. 

I think maybe this behavior is because of how celery works. 

also can't .save() the document anywhere inside the celery task besides __exit__ or will get an exception @ __exit__.  

Here is example code as above probably isn't very clear.  https://gist.github.com/brizzbane/cce5bbcc792254f43bd2

This is just an issue w/celery.  Don't know a whole lot about how celery works, but pretty sure its issues related to pickling.  Maybe reason I'm getting exception if I don't .get() the DocType immediately after save in init--is because what 'celery' *thinks* the DocType it has is the original version passed to __init__? (BigProgram in example).

**Comment by HonzaKral** [comment]
I cannot seem to replicate this. Is it possible that you have a race condition somwhere in your code? `.save()` explicitly updates the version and it really shouldn't be needed. There is now even a test that verifies that.

I am not sure what's going on, but the easiest way to debug this would probably for you to add some logging - specifically log the version before and after each `save()` to make sure nothing else is going on.

**Comment by brizzbane** [comment]
Hey sorry, realized before I saw you reply that I was missing an important part of it.  Check the updated code.

**Comment by HonzaKral** [comment]
This doesn't change anything, could you please add the logging and see what the versions number are?

**Comment by brizzbane** [comment]
how do you print version?  from looking at test docs thought it looked like document.meta.version,

AttributeError: 'ResultMeta' object has no attribute 'version' w/that tho.

**Comment by HonzaKral** [comment]
Yeah, the dosument doesn't have a version from search, you need to do: `print(getattr(doc.meta, 'version', 'No version'))`

**Comment by brizzbane** [comment]
thanks.  so I slowed things down to processing one document at a time, its working! so race condition I'm guessing is what the problem for me is.  going to increase volume and will report back at what I figure out.

**Comment by brizzbane** [comment]
closing this for now.  haven't had issues since being aware doctypes should know it's own version #, and making sure race conditions don't happen.

**Comment by brizzbane** [comment]
is this still how you get version?  I'm getting no version for everything.

running into this issue again, and pretty certain its not a race condition.  may have to do something w/me passing the doc around to different modules.  would be really helpful to know where the verison goes wrong, but I'm always showing 'no version'

**Comment by HonzaKral** [comment]
Can you please post some code that can replicate this issue? We have passing tests that work with versions so it shouldn't be happening.

Relevant test - https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_integration/test_document.py#L67-L71

Thanks

**Comment by HonzaKral** [comment]
Note that search doesn't return version by default, only `get` operation does.

**Comment by brizzbane** [comment]
It's really odd--its happening when using with statement.  

Something thats *super* weird, is that I'll watch the data I'm having issues w/in kibana, and it will be being updated, but I have a log handler for elasticsearch.trace--set it to debug, and it's showing no requests to elasticsearch.

could maybe having a connection to elasticsearch in more than one place be causing this?

**Comment by HonzaKral** [comment]
Yes, if you configured the logging then all requests should show up. To me that means that, most likely, there is something else writing to elasticsearch.

Unfortunately it still looks like a race condition somewhere in your code or infrastructure. I cannot help you without a code I can reproduce or a description of steps to that effect, especially since everything works fine for me and in tests.

**Comment by brizzbane** [comment]
I will try and reproduce and provide w/code. the info about version only for get was helpful

Thx
