### ISSUE TITLE
KeyError: 'result' when executing parallel uploads

### ISSUE THREAD

**Issue by datavistics** [elastic/elasticsearch-dsl-py#1393]
https://github.com/elastic/elasticsearch-dsl-py/blob/744211bfab707c922c08da14b756c19301dd9e68/elasticsearch_dsl/document.py#L463

Im working on an app with _flask_ running on top of _uwsgi_ with **20 workers** all running in a _docker-compose env_.

```
def create_app():
    ...
    es_conn = Elasticsearch(host=base_url, port=9200,
                            timeout=int(os.environ.get('ELASTIC_TIME_OUT', 30)), maxsize=20)
    # es_conn = connections.create_connection(host=base_url, port=9200,
    #                                         timeout=int(os.environ.get('ELASTIC_TIME_OUT', 30)), maxsize=20)
    connections.add_connection('default', es_conn)
    ...
```

```
class Metadata(Document):
    my_id = Text(fields={'raw': Keyword()})
    other_field = Nested(Otherdata)
    def save(self, **kwargs):
        self.meta.id = self.my_id
        return super(Metadata, self).save(**kwargs)
```

When I try to make _multiple requests in parallel_ to **update**, I get an error
docker |     metadata_es.update(other_field=d, )
docker |   File "/opt/conda/lib/python3.7/site-packages/elasticsearch_dsl/document.py", line 415, in update
docker |     return meta['result']
docker | KeyError: 'result'

This also happens when I try create a new document and save it.

I have no problems when I make a single upload.

**Comment by laventy** [comment]
I have a similar issue where one document is being saved with refresh=True and at the same time, another document is being saved as well.

 File "/app/project/models/document.py", line 235, in save
    return super().save(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch_dsl/document.py", line 455, in save
    return meta['result']
KeyError: 'result'

I guess in my case, using refresh=True will cause the refreshing of the whole index which causes another concurrent save failed due to index being busy?

**Comment by sethmlarson** [comment]
Would be very helpful to get the response that's causing this error to happen. Any non-2XX HTTP response should be raising an exception but I don't know the conditions where `result` isn't returned.

**Comment by miguelgrinberg** [comment]
I'm unable to reproduce this with 8.x clients and stack. It has been a long while, if anyone continues to see this issue and is able to provide the additional information requested above we can revisit.
