### ISSUE TITLE
delete_by_query from Search.delete()

### ISSUE THREAD

**Issue by jdratlif** [elastic/elasticsearch-dsl-py#1395]
I am trying to run a delete_by_query by using the delete() method of my Search object, but it times out.

What can I do to make sure it keeps running until completion?

This is the exception I get
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPSConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=300)) 

Trying to add a `request_timeout` parameter led me to a 

    search.delete(request_timeout=0)
TypeError: delete() got an unexpected keyword argument 'request_timeout'

TypeError exception.

The docs for the delete_by_query call say that by default it keeps running until it is finished, so there must be something I need to do with timeout to make sure it does.

Thanks.

**Comment by sethmlarson** [comment]
To set `request_timeout=0` you have to use `Search.params()` like so: `Search.params(request_timeout=0).delete()`

or if you want to [execute the query asynchronously](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html#docs-delete-by-query-task-api) you can call with `Search.params(wait_for_completion=False).delete()`. This will respond with a Task which you can check the status of using the [`Elasticsearch.tasks.*` APIs](https://elasticsearch-py.readthedocs.io/en/7.10.0/api.html#tasks).

Let me know if this doesn't solve your problem
