### ISSUE TITLE
Memory leak Search.scan()

### ISSUE THREAD

**Issue by bogdan-zs** [elastic/elasticsearch-dsl-py#1397]
Elastic Search v7

elasticsearch==6.3.0
elasticsearch_dsl==6.4.0

Hello, I have a problem with using a lot of memory by celery task which retrieves elasticsearch document, transform it and push to storage like a file. I rewrite scroll to using request lib and have different results of using memory by docker.
### elasticsearch_dsl
before start - 264.9MiB
after running - 603.4MiB

### using request
before start - 264.9MiB
after running - 375.4 MiB

## Code
```
# celery task
def generate_google_shopping_feed_task() -> None:
    product_item_keys = (...)
    products = get_google_shopping_products()
    product_items = get_google_shopping_items(products)
    upload_product_feed_file(
        product_items,
        keys=product_item_keys,
        storage_key=STORAGE_KEY,
    )

def get_products() -> t.Generator[Hit, None, None]:
    query = ProductItem.search()
    batch: t.List[Hit] = []
    for index, product in enumerate(query.scan()):
        # product = Hit(doc)
        # collect products to batch for reducing count of calls to service
        if len(batch) < 5_000:
            batch.append(product)
        else:
            yield from _get_returnable_products(batch)

            batch = []

    if batch:
        yield from _get_returnable_products(batch)
#####################
#
# using request lib
def get_google_shopping_products() -> t.Generator[Hit, None, None]:
    query = ProductItem.search()[:5_000]
    import requests
    es_conf = settings.ES_SETTING["main"]
    url = f'http://{es_conf["host"]}/{es_conf["product_index"]}/_search'
    resp = requests.post(url, params={'scroll': '5m'}, json=query.to_dict())
    data = resp.json()
    scroll_id = data.get('_scroll_id')
    while scroll_id and data['hits']['hits']:
        batch: t.List[Hit] = []
        for index, doc in enumerate(data['hits']['hits']):
            product = Hit(doc)
            # collect products to batch for reducing count of calls to service
            if len(batch) < 5_000:
                batch.append(product)
            else:
                yield from _get_returnable_products(batch)
                batch = []
        if batch:
            yield from _get_returnable_products(batch)
        print(scroll_id)
        url = f'http://{es_conf["host"]}/_search/scroll'
        resp = requests.post(url, json={'scroll': '5m', 'scroll_id': scroll_id})
        data = resp.json()
        scroll_id = data.get('_scroll_id')
```

Help find a problem and reduce memory usage. Thank you

**Comment by bogdan-zs** [comment]
memory usage of the container was reduced when I use this connection class
```
class Connection(RequestsHttpConnection):
    def log_request_success(self, method, full_url, path, body, status_code, response, duration):
        pass


# clients
es_client = Elasticsearch(hosts=ES_MAIN['host'], timeout=5, max_retries=0, connection_class=Connection)
```

**Comment by sethmlarson** [comment]
Quick question: you mention both elasticsearch v7 and libraries that are v6. Your library major version should match your Elasticsearch cluster major version.

**Comment by bogdan-zs** [comment]
Ok, but this not fix my problem, on production we have elasticsearch 5 and the problem is reproduced

**Comment by kongklw** [comment]
Have you solved this problem？my code also has memory leak .Look forward to your reply，thank you.

**Comment by bogdan-zs** [comment]
Problem was not in elasticsearch-dsl-py library.

**Comment by kongklw** [comment]
> Problem was not in elasticsearch-dsl-py library.

`import gc
import time
import psutil
import elasticsearch
from elasticsearch import Elasticsearch, helpers

print('elasticsearch version: ', elasticsearch.version)
print('start mem: {:.4f} gb'.format(psutil.virtual_memory().used / 1024 / 1024 / 1024))
es = Elasticsearch(hosts='192.168.83.222:9200')
query = {'query':{'term':{'ORG_NO':'3140201'}}}
repl = helpers.scan(client=es, query=query, index='hb_mp_info-3140201-2020.10.10', size=10000)
l = [ele for ele in repl]
del l
gc.collect()
time.sleep(5)
print('end mem: {:.4f} gb'.format(psutil.virtual_memory().used / 1024 / 1024 / 1024))`

Run the above code, we can see:
start mem: 6.3883 gb
end mem: 7.2465 gb
I feel that 0.86 gb memory ware leaking.
