### ISSUE TITLE
sorted by sub aggregation 

### ISSUE THREAD

**Issue by Catelemmon** [elastic/elasticsearch-dsl-py#1403]
I'd execute  elasticsearch query like follow:
```
  "aggs": {
    "core_hour_rank": {
      "terms": {
        "field": "username.keyword",
        "size": 10,
        "order": {
          "user_age_agg": "desc"
        }
      },
      "aggs": {
        "user_age_agg": {
          "sum": {
            "field": "age"
          }
        }
      }
    }
  }
}
``` 
as  you see, I wanna order result by sub aggregation result, But when construct searcher by `searcher.from_dict()`, I'll get `user_age_agg is unknow errorr`, what should I do?

**Comment by sethmlarson** [comment]
I'm not receiving that error in the latest version. Try again and update your bug report.
