### ISSUE TITLE
Flattened Data Type

### ISSUE THREAD

**Issue by mgresko** [elastic/elasticsearch-dsl-py#1405]
https://www.elastic.co/guide/en/elasticsearch/reference/current/flattened.html

How would I define a flattened datatype on a Document model?

Thanks!

**Comment by benrudolph** [comment]
Also have this question, were you able to resolve this?

**Comment by feigenblatt** [comment]
Same here.
Either of you got a solution?
Thanks.

**Comment by pySilver** [comment]
@beantoast @feigenblatt solution is simple - create this field as any other in your own codebase.

**Comment by valerino** [comment]
@pySilver may you be a little more clear ? just stumbled on this and i have the same exact question....

**Comment by pySilver** [comment]
@valerino 

```python
from django_elasticsearch_dsl import DEDField
from elasticsearch_dsl.field import Field


class Flattened(Field):
    name = "flattened"
    _coerce = True


class FlattenedField(DEDField, Flattened):
    pass
````
