### ISSUE TITLE
0.0.4: query became fquery

### ISSUE THREAD

**Issue by pquentin** [elastic/elasticsearch-dsl-py#141]
https://github.com/elastic/elasticsearch-dsl-py/commit/ea37a0dcefb0f3738a9796a5095f3d93796df259 from https://github.com/elastic/elasticsearch-dsl-py/issues/61 broke 'query' which worked fine for us in 0.0.3. We had to change `F('query', **value_query)` to `F('fquery', query=value_query)`. We might be using your library incorrectly, and we understand that 0.x means 'no promises', but https://elasticsearch-py.readthedocs.org/en/master/ recommends elasticsearch-dsl so we would have expected the changes to be documented.

Is it possible to add a 'breaking changes' section in the docs? Thanks!

**Comment by pquentin** [comment]
Additionally, it looks like elasticsearch supports both fquery and query. Those two examples seem inconsistent: http://www.elastic.co/guide/en/elasticsearch/reference/1.5/query-dsl-query-filter.html

**Comment by HonzaKral** [comment]
Hi @pquentin, you are absolutely correct, both are supported so the fix for #61 was wrong. I verified that `'query'` works and didn't verify that `'fquery'` was indeed wrong. My bad.

It is not a problem with your usage of the library.

Thanks for the report!

**Comment by HonzaKral** [comment]
There is still a slight difference between query and fquery, fix forthcoming

**Comment by HonzaKral** [comment]
fixed in 334b5a57021c13e4cbc26c85e48936ae94e1addb, that was also the original cause of #61
