### ISSUE TITLE
Support split index API

### ISSUE THREAD

**Issue by aviau** [elastic/elasticsearch-dsl-py#1414]
It would be great if this library supported the split index API!

**Comment by sethmlarson** [comment]
@aviau Can you accomplish this via passing the index name into the low-level Elasticsearch client via `client.indices.split()`?

**Comment by aviau** [comment]
I thing yes. But since the Index object has shrink() I would think it would also have split()

**Comment by sethmlarson** [comment]
I'm open reviewing a PR which adds this support along with test cases.

**Comment by sethmlarson** [comment]
I think we're going to decline this feature request since it's rare to need this API from an ORM context and can be accomplished using the base client.
