### ISSUE TITLE
Elasticsearch_dsl doesn't parse results correctly while using Alias

### ISSUE THREAD

**Issue by GabrielBlondeau-Kirby** [elastic/elasticsearch-dsl-py#1426]
Hello guys,

In my Elastic deployement I have multiple Indexes (tables?). For a reason, I want to use the Alias on those Indexes.

When I'm targetting an Index with is original Title/name, the result is correctly parsed, which means every "hit" becomes a proper object. So I can do, Object.name or Object.to_json().

BUT, when I give an Alias to the same Index and then do the same query by using the Alias instead the origin name, the result it is not parsed correctly. All the hits still a Hit object.

Query example (very simple):
```
{
    "bool":{
        "must":[
            {
                "match":{
                    "store":"Id",
                    "active":True
                }
            }
        }
    ]
}
```
----

- Elasticsearch-dsl Version: **7.1.0**
- Deployment version: **7.8.0**

My current model (document):
```
from elasticsearch_dsl import Document, Boolean, Text, Float, InnerDoc, Nested, Keyword
from utils.date_time_util import now, ESArrowDateTimeField


class Product(Document):
    created = ESArrowDateTimeField(required=True)
    modified = ESArrowDateTimeField(required=True)

    active = Boolean(required=True)
    deleted = Boolean(required=True)

    store = Keyword(required=True)

    title = Text(required=True)
    description = Text()
    link = Text()

    external_id = Keyword()

    # Pricing
    price = Float()
    sale_price = Float()

    vat = Float()
    currency = Text(required=True)

    # Variant group
    item_group_id = Text()

    # From XML Standard SS2 - Google: https://support.google.com/merchants/answer/7052112
    adult = Boolean()
    age_group = Text()
    brand = Text()
    color = Text()
    condition = Text()
    gender = Keyword()
    category = Text()
    material = Text()
    kind = Text(multi=True)

    # Product identifiers - SKU
    gtin = Text()
    mpn = Text()

    @property
    def id(self):
        return self.meta.id

    def initialize_defaults(self):
        if not self.created:
            self.created = now()
        self.modified = now()
        if self.active is None:
            self.active = True
        if self.deleted is None:
            self.deleted = False
        if self.description is None:
            self.description = ''
        if self.link is None:
            self.link = '/'
        if self.vat is None:
            self.vat = 0.0
        if self.currency is None:
            self.currency = 'NOK'
        if self.additional_image_links is None:
            self.additional_image_links = []
        if self.kind is None:
            self.kind = []

    def reload(self):
        product = Product.get(id=self.id)
        self = product
        return product

    def to_json(self):
        del self['created']
        del self['modified']
        res = self.to_dict()
        res['id'] = self.id
        res['_id'] = {
            '$oid': self.id
        }
        return res
```

**Comment by sethmlarson** [comment]
Noticed your elasticsearch-dsl version isn't the latest for 7.x, can you try on the latest as well?

**Comment by GabrielBlondeau-Kirby** [comment]
> Noticed your elasticsearch-dsl version isn't the latest for 7.x, can you try on the latest as well?

Sure I'll try :)

**Comment by GabrielBlondeau-Kirby** [comment]
Hi @sethmlarson ,

I tested with the lastest version: **7.3.0**

Here are the results of the tests:  
## By using ALIAS
```
```

## By using NAME of the Index
```
```

**Comment by florianvazelle** [comment]
Hi @GabrielBlondeau-Kirby 
Try to implement the _matches classmethod, [like this](https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/alias_migration.py#L57) ([ref](https://github.com/elastic/elasticsearch-dsl-py/issues/1176#issuecomment-496135860)), it's work for me !

**Comment by GabrielBlondeau-Kirby** [comment]
> Hi @GabrielBlondeau-Kirby
> Try to implement the `_matches` classmethod, [like this](https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/alias_migration.py#L57) ([ref](https://github.com/elastic/elasticsearch-dsl-py/issues/1176#issuecomment-496135860)), it's work for me !

Thx man, I'll try :)

**Comment by GabrielBlondeau-Kirby** [comment]
Hey @florianvazelle , it works !! awesome dude, thank you a lot ;) !!
