### ISSUE TITLE
Add version and version_type to utils.DOC_META_FIELDS

### ISSUE THREAD

**Issue by lijok** [elastic/elasticsearch-dsl-py#1432]
That way I can index something like this

```
FileDocument(
    id=3000,
    alive=True,
    access_level=1,
    caption='test',
    meta={
        'id': 3000,
        'version_type': 'external',
        'version': 99,
    }
)
```

using bulk helper and utilize versioning

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-versioning

**Comment by armando1793** [comment]
@lijok  I did

```
doc = Document.get(id=somevalue)
// manipulate doc values
doc.meta["version"] = None
```

I think version in `meta` should be overridden when `retry_on_conflict` is not `None`
