### ISSUE TITLE
Any way to use the Explain API with this library?

### ISSUE THREAD

**Issue by eelkeh** [elastic/elasticsearch-dsl-py#1440]
It it possible to use the Explain API (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-explain.html) and if not what would be the best way to use an existing query defined with this library for an explain call?
Any pointers in the right direction, would be greatly appreciated!

**Comment by brainix** [comment]
I use [`.explain()`](https://elasticsearch-py.readthedocs.io/en/7.9.1/api.html?highlight=explain#elasticsearch.Elasticsearch.explain) provided by the lower level [elasticsearch-py](https://elasticsearch-py.readthedocs.io/en/7.9.1/) library, which this higher level [elasticsearch-dsl-py](https://elasticsearch-dsl.readthedocs.io/en/7.3.0/) builds upon. Assuming that you have an [elasticsearch-py client](https://elasticsearch-py.readthedocs.io/en/7.9.1/api.html#elasticsearch) called `es` and an [elasticseach-dsl-py query](https://elasticsearch-dsl.readthedocs.io/en/latest/#migration-from-elasticsearch-py) called `s`, you can get the query explanation like so: `explanation = es.explain(my_index_name, some_doc_id, body=s.to_dict())`

Hope that helps! 😄

**Comment by sethmlarson** [comment]
Thanks for answering the question @brainix. My only recommendation to add to your answer is to use keyword arguments within `es.explain()`:

```python
explanation = es.explain(index=my_index_name, id=some_doc_id, body=s.to_dict())
```
