### ISSUE TITLE
Output an index as a field.

### ISSUE THREAD

**Issue by rocket-ops** [elastic/elasticsearch-dsl-py#1448]
Is it possible to output into a dataframe the _index field? When I conduct a search and then use to_dict() to create the df, I can't find anyway to have index as a part of that dataframe.  Thanks.

**Comment by sethmlarson** [comment]
If you're working with DataFrames and Elasticsearch I suggest you take a look at [Eland](https://github.com/elastic/eland). If this doesn't solve your problem could you provide extra information about what you're trying to do and I'll reopen.

**Comment by rocket-ops** [comment]
I am not sure I understand how Eland helps with what I am trying to accomplish. 

Typically, when querying elastic using elasticsearch-dsl I will query numerous indexes at once.  An example would be we have a client who has 50 different locations.  Each locations data populates their own unique index.  So a query would be generic to include all the indexes for that client.  index:"*client_x_data*".  The problem occurs that the searches return all fields but _index isn't a returned field. The _index is key to knowing where the data in that line comes from as there is nothing in the fields to identify that particular location.  So, how do I get _index to return as a field in dataframe?

**Comment by sethmlarson** [comment]
How are you querying for data with elasticsearch-dsl? If you're using `Search.execute()` you can grab the index from `Hit.meta.index`:

```python
from elasticsearch_dsl import Search

for hit in Search(index="*").execute():
    print(hit.meta.index)
```

**Comment by rocket71** [comment]
Thanks. That does work, however what I need is for it to be attached to each associated document/record. 

Here is an example of my full base search.  It is usually ran against numerious indexes. I am  not sure how to concatonate two searches and ensure they are placed with the correct record. 

s = searchContext.query('query_string', query='event_identifier:"7045"') \
    .filter('range', datetime={'gte': start_date, 'lte': stop_date})
response = s.execute()
if response.success():
    services_df = pd.DataFrame((d.to_dict() for d in s.scan()))
services["datetime"]=pd.to_datetime(services["datetime"])
services["datetime"]=services["datetime"].dt.tz_localize(None)

**Comment by sethmlarson** [comment]
You can do this transformation yourself?

```python
def to_dict_with_index(x):
    dct = x.to_dict()
    dct["index"] = x.meta.index
    return dct

pd.DataFrame((to_dict_with_index(d) for d in s.scan()))
```

**Comment by rocket-ops** [comment]
That works! Thank you.
