### ISSUE TITLE
How to add a geo_boundary_box filter in FacetedSearch

### ISSUE THREAD

**Issue by SmartDataCode** [elastic/elasticsearch-dsl-py#1449]
Hi,

I'm struggling to add a **geo_boundary_box** filter in my code that is using FacetedSearch. Can anyone give some pointers? I've tried to add the filter through a `.query()`, but can't get it to work.
Any help is highly appreciated

**Comment by sethmlarson** [comment]
[See the example in the FacetedSearch documentation](https://elasticsearch-dsl.readthedocs.io/en/latest/faceted_search.html#example) about how to add custom filters at search time:

```python
class CustomFacetedSearch(FacetedSearch):
    ...

    def search(self):
        # override methods to add custom pieces
        s = super().search()
        return s.filter(
            "geo_bounding_box",
            location={
                "top_left": {"lat": 40.73, "lon": -74.1},
                "bottom_right": {"lat": 40.01, "lon": -71.12},
            },
        )
```
