### ISSUE TITLE
__and__ operator fails for Bool with minimum_should_match in percentage

### ISSUE THREAD

**Issue by mmoriniere** [elastic/elasticsearch-dsl-py#1451]
Hello,

I ran into on an error when trying to chain two such queries :
```python
MyDocument.search().query(
    Bool(filter=Term(disabled=False))
).query(
    Bool(should=[my_should_clauses], minimum_should_match="-10%")
)
```
(where MyDocument derives from the Document class of django_elasticsearch_dsl).

The error happens [here](
https://github.com/elastic/elasticsearch-dsl-py/blob/8a9c374a59928abdbc6b1117d54852bda021c4ad/elasticsearch_dsl/query.py#L213), and there actually is a TODO three lines above suggesting that this problem is known and ought to be fixed.

Is there any plan to support such a feature ?

Note: I already found two workarounds to avoid this issue :
1. Refactor my code to use just one query,
2. Make the second query look like this `Bool(filter=Bool(should=[my_should_clauses], minimum_should_match="-10%"))`.

**Comment by miguelgrinberg** [comment]
A more explicit error message is now shown, indicating that only positive integers are currently supported for `minimum_should_match`.
