### ISSUE TITLE
more_like_this_field example query

### ISSUE THREAD

**Issue by pcompassion** [elastic/elasticsearch-dsl-py#147]
How can I build a Q object for the following (http://stackoverflow.com/a/15320512/433570)

```
{
    "bool" : {
        "must" : {
          {"match_all" : { }}
        },
        "should" : [
            {
              "more_like_this_field" : {
                "tags" : {
                  "like_text" : "here go the tags extracted from the current document!",
                  "boost" : 2.0
                }
              }
            },
            {
              "more_like_this_field" : {
                "content" : {
                  "like_text" : "here goes the content extracted from the current document!"
                }
              }
            }
        ],
        "minimum_number_should_match" : 1
    }
}
```

**Comment by HonzaKral** [comment]
The easiest way to find out is to wrap the dict in a `Q` function and then inspect the result:

    q = Q({...})
    print(repr(q))

will then give you (minus the formatting):

    Bool(
        minimum_number_should_match=1,
        must=[MatchAll()],
        should=[
            MoreLikeThisField(
                tags={
                    'boost': 2.0,
                    'like_text': 'here go the tags extracted from the current document!'
              }
            ),
            MoreLikeThisField(
                content={
                    'like_text': 'here goes the content extracted from the current document!'
                }
            )
        ]
    )

this can also be written more easily as:

    Q('more_like_this_field', tags={...}) | Q('more_like_this_field', content={...})

Hope this helps.
