### ISSUE TITLE
slice of 0 [0:0]

### ISSUE THREAD

**Issue by dblado** [elastic/elasticsearch-dsl-py#148]
Just started working w/ the dsl today and loving it! Nice work!

I'm doing a simple aggregation where I don't need any results but the aggs. I noticed that if I use:

```
s = Search(using=es_conn, index='vendop', doc_type='review').fields([])[0:0]
```
The size parameter in the query will be 10. Why is the underlying ES library substituting the default when I specified 0? If I do [0:1] I see "size": 1 in s.to_dict

**Comment by HonzaKral** [comment]
The why is simple - it was a bug, an error on my part. Thanks for the report!
