### ISSUE TITLE
Scan method of elasticsearch dsl bad performance

### ISSUE THREAD

**Issue by Horatius9756** [elastic/elasticsearch-dsl-py#1484]
I tried the scan method, because i use elasticsearch dsl to upload data, this works fine. In addition i use the request module to retrieve data(only up to 10000 hits). I tried the scan method also, but this takes much more time, am i doing something wrong?

5660 hits take about 25sec that makes no sense to me.. Mabe i have to process data in 10.000 packages with the request module to get a solid performance? This is my code
`t0 = time.time()

_s = Search(using=_get_elasticsearch_access(), index="maksim_measurements") \
    .query("match", gateway_name="Gateway-1") \
    .query("match", measured_value_definition="uBuck_BME680_temperature")
count = s.count()

response = s.params(size=1000).scan()

for index, result in enumerate(response):  
    result_dict = result.to_dict()
    neuerDF = neuerDF.append(pd.DataFrame(result_dict, index=[index]))

t1 = time.time()_`

t1=26.635444402694702

**Comment by NeverBehave** [comment]
For anyone search and bumped into similar problem: use [elasticsearch-py](https://github.com/elastic/elasticsearch-py) for fast/batch data processing. dsl has lots of wrapping/mapping and copying for quick access and these would be pretty slow. In my case it is an instant 5x boost and 100x for nested data

Code Example:

```python
from elasticsearch import Elasticsearch, helpers

es = Elasticsearch("http://somehost")
sc = helpers.scan(es, index="some-index", query={"query": { "match": { 'some-field': "some-value} }, "_source": {
    'include': [
        "fields-you-need-only-for-fast-json-processing"
    ]}})

for item in sc:
  doc = sc['_source']
  print(doc)
```
