### ISSUE TITLE
How to use scroll_id?

### ISSUE THREAD

**Issue by spitfiredd** [elastic/elasticsearch-dsl-py#1486]
So I've implimented a search where I can add scrolling and it will return a scroll ID, 

```
search = Search(using=es, index=index).query(query)
search = search.params(scroll='5m').extra(size=10)
response = search.execute()
scroll_id = response['scroll_id']
```

How do I use the `scroll_id` to get more results?  

I did end up making a subclass,

```
class SearchWithScrolling(Search):
    def __init__(self, *args, **kwargs):
        super(SearchWithScrolling, self).__init__(*args, **kwargs)
    def scroll(self, scroll_id, scroll='5m'):
        if not hasattr(self, "_response"):
            
            es = get_connection(self._using)
            self._response = self._response_class(self, es.scroll(scroll_id=scroll_id, scroll=scroll))
        return self._response
```

However, if I do something like,

```
search = SearchWithScrolling(using=es, index=index).query(query)
search = search.params(scroll='5m').extra(size=10)
response = search.execute()
scroll_id = response['scroll_id']

page_2 = search.scroll(scroll_id=scroll_id)
```

This doesn't clear out `self_response` and just returns the existing data, and I end up having to `_clone` the search object like, `page_2 = search._clone().scroll(scroll_id=scroll_id`

Also in my `scroll` method if try to delete the `_response` attribuete (e.g. delattr(self, "_response")`); I get a NoneType error when I iterate through the results e.g. `page_2.hits.hits` e.g.

```
def scroll(self, scroll_id, scroll='5m'):
        if  hasattr(self, "_response"):
            delattr(self, "_response")
            es = get_connection(self._using)
            self._response = self._response_class(self, es.scroll(scroll_id=scroll_id, scroll=scroll))

```
Questions:

1. How do I delete `self._response`?  OR
2. How would I correctly implement my `SearchWithScrolling` subclass?

**Comment by spitfiredd** [comment]
This works,

```
def scroll(self, scroll_id, scroll='5m'):
    self = self._clone()
    if not hasattr(self, "_response"):
        # rest of code
```

I guess please refer to question 2?

**Comment by sethmlarson** [comment]
You can already use `Search.scan()` to paginate all hits in a response. Closing this for now, let me know if this doesn't cover your use-case.
