### ISSUE TITLE
Unable to replicate post_filter query

### ISSUE THREAD

**Issue by aksbond** [elastic/elasticsearch-dsl-py#1495]
The query I would like to replicate in DSL is as below: 

<pre>
GET /_search
{
  "query": { 
    "bool": { 
      "must": [
        {"term": { "destination":   "singapore"}},
        {"terms": { "tag_ids":   ["tag_luxury"]}}
      ]
    }
  }, 
  "aggs": {
    "max_price": { "max": { "field": "price_range_from.SGD" } },
    "min_price": { "min": { "field": "price_range_from.SGD" } }
  },
  "post_filter": {
          "range": {  "price_range_from.SGD": { "gte": 0.0, "lte": 100.0  } }
  }
    
}
</pre>

The above query 

1. Matches certain terms - `destination` and `tags_ids` 
2. Aggregates to result to find the max price from field `price_range_from.SGD`
3. Applies another post_filter to subset the result set within price limits

**It works perfectly well in the Elastic console.**

I replicated the above query in elasticsearch-dsl as below:

<pre>
es_query = []
es_query.append(Q("term", destination="singapore"))
es_query.append(Q("terms", tag_ids=["tag_luxury"]))
final_query = Q("bool", must=es_query)

es_conn = ElasticSearch.instance().get_client()
dsl_client = DSLSearch(using=es_conn, index=index).get_dsl_client()
dsl_client.query = final_query
dsl_client.aggs.metric("min_price", "min", field="price_range_from.SGD")
dsl_client.aggs.metric("max_price", "max", field="price_range_from.SGD")
q = Q("range", **{"price_range_from.SGD":{"gte": 0.0, "lte": price_limit}})
dsl_client.post_filter(q)

print(dsl_client.to_dict())
response = dsl_client.execute()
print(response.to_dict().get("hits", {}))

</pre>

However, although the aggregations are correct, **products beyond the price range are also being returned**. 

I dived in the `dsl_client` object to see whether my query is being captured correctly, but I see only the `query` and `aggs` BUT don't see the `post_filter` part in the object. 

`{'query': {'bool': {'must': [{'term': {'destination': 'singapore'}}, {'terms': {'tag_ids': ['tag_luxury']}}]}}, 'aggs': {'min_price': {'min': {'field': 'price_range_from.SGD'}}, 'max_price': {'max': {'field': 'price_range_from.SGD'}}}}`

Please let me know if I am missing something. Thanks.

**Comment by keshavfz** [comment]
Any update on this??
experiencing the same issue

**Comment by miguelgrinberg** [comment]
Unable to reproduce with current release.

```python
import json
from elasticsearch_dsl import Search, Q

s = Search(index="foo")
s = s.query('bool', must=[
    Q('term', destination='singapore'),
    Q('terms', tag_ids=['tag_luxury']),
])
s.aggs.metric("min_price", "min", field="price_range_from.SGD")
s.aggs.metric("max_price", "max", field="price_range_from.SGD")
s = s.post_filter('range', **{'price_range_from.SGD': {'gte': 0.0, 'lte': 100.0}})

print(json.dumps(s.to_dict(), indent=4))
```

Output:

```json
{
    "query": {
        "bool": {
            "must": [
                {
                    "term": {
                        "destination": "singapore"
                    }
                },
                {
                    "terms": {
                        "tag_ids": [
                            "tag_luxury"
                        ]
                    }
                }
            ]
        }
    },
    "post_filter": {
        "range": {
            "price_range_from.SGD": {
                "gte": 0.0,
                "lte": 100.0
            }
        }
    },
    "aggs": {
        "min_price": {
            "min": {
                "field": "price_range_from.SGD"
            }
        },
        "max_price": {
            "max": {
                "field": "price_range_from.SGD"
            }
        }
    }
}
```
