### ISSUE TITLE
Deleting attributes?

### ISSUE THREAD

**Issue by njoannin** [elastic/elasticsearch-dsl-py#150]
Is it possible to delete an attribute?

I've tried with ```del obj.attr``` but that doesn't work:

```
>>> class Test(DocType):
...     test_attr = String()
... 
>>> t = Test()
>>> t.test_attr = "test"
>>> t
{'test_attr': 'test'}
>>> del t.test_attr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: test_attr
```

Is there another way I'm missing?

**Comment by njoannin** [comment]
The only way I see for doing this is:

```
del obj._d_["attr"]
```

But (1) I'm not sure this doesn't affect something else, and (2) it uses a private attribute, which one should not do...

Is this a non-issue, and one should just use the private _d_?

**Comment by HonzaKral** [comment]
This is an issue, a bug and I will fix it, it should be as simple as (famous last words) implementing `__delattr__`.

Thanks for the report and sorry for the delay.

**Comment by njoannin** [comment]
OK
Thanks!
