### ISSUE TITLE
Suggestion for result.rget('@badpyname.thisotherthing.thatotherthing')

### ISSUE THREAD

**Issue by kputland** [elastic/elasticsearch-dsl-py#151]
```python
def rget(d, key, default=None):
    if type(key) == type(''):
        key = key.split('.')
    a = key.pop(0)
    v = d.get(a,None)
    if not v:
        keys = d.keys()
        keys.sort()
        k = [ x for x in keys if x.lower() == a.lower() ]
        vl = [ d.get(x,None) for x in k ]
        v = [ x for x in vl if x ]
        v = v and v[0] or None
    if v and type(v) == type(d) and key:
        return rget(v, key, default)
    elif v and key:
        # Nothing exists deeper yet there are still names to find
        # short curcuit the recursion and return None as there
        # is nothing to find
        return None
    else:
        return v

def test():
    d={
        'a': {
            'c': {'d': 'D'},
            'b': 'B'
        },
        'l': [
            'a',
            'b',
            'c'
        ],
        'L': 'foo',
        'ab':'ab',
        'aB':'aB',
    }
    tests=[
        ('a', 'a exists and is correct case', {'c':{'d':'D'},'b':'B'}),
        ('A', 'A exists as a - match case insensitive', {'c':{'d':'D'},'b':'B'}),
        ('b', 'b does not exist return None', None),
        ('a.b', 'a.b exists and is correct case', 'B'),
        ('a.B', 'a.B exists as a.b - match case insesitive', 'B'),
        ('l', 'l exists as l', ['a','b','c']),
        ('L', 'L exists as L', 'foo'),
        ('L', 'L exists as l should FAIL', ['a','b','c']),
        ('ab', 'ab exists and is correct', 'ab'),
        ('aB', 'aB esists and is correct', 'aB'),
        ('AB', 'AB does not exist return aB as caps sort before lower', 'aB'),
        ('Ab', 'Ab does not exist return aB as caps sort before lower', 'aB'),
        ('a.b.c.d.e.f', 'deep non existant name past a.b which exists', None),
        ('b.c.d.e.f', 'deep non existant name with no existint parent', None),
    ]
    for a,t,r in tests:
        v = rget(d,a)
        sys.stderr.write('{:60s}: rget(d, \'{}\'): {}\n'.format(t, a, v == r and 'PASS' or 'FAIL'))
        if v != r:
            sys.stderr.write('\texpected: {}\n\treceived: {}\n'.format(r,v))

test()
```

**Comment by HonzaKral** [comment]
This is an interesting idea, thanks for bringing it up. I have been playing with a similar one for a while. I was also considering supporting this for settings the fields since it will make a lot of things easier. I was leaning towards just supporting the dotted path in `__[g/s]etitem__` so in the `doc['the.path.goes.here']` notation. Does that make sense?

**Comment by kputland** [comment]
I don't have a problem with ```__[g|s]etitem__``` as long as things don't break, though that needs improvement right now to wrap DictType in Result so that something like 

```python
fields = result['@fields']
fields.fieldname
```

would work too. Currently it returns the raw dict and you have to use dict key access. Which was part of the reason I went with the recursive dotpath route... so that I could get all the way to the value on one line.

It would also be good for result to play nice with string.format

```python
'{foo.name} {foo[@badname].otherfieldname}'.format(result)
```

**Comment by kputland** [comment]
I guess too that 

```python
'{foo[@this.is.a.long.bad.name]}'.format(foo=result)
```
should probably work too if you're overriding ```__getattr___```

I think that would work well.

**Comment by HonzaKral** [comment]
Ah, yes - my assumption there was that if people use the `d["field"]` approach they just want raw dicts. I didn't thikn of the special fields and my assumption was wrong, will fix this.

Thanks

**Comment by HonzaKral** [comment]
I am sorry, the longer I look at this issue the more I doubt we should do anything like that.

Now you can do `f['@this'].is.a.long.bad.name` and that ought to be enough - if we tried to implement more things would get very messy. I am closing this issue.

**Comment by kputland** [comment]
Ok. As long as the __getitem__ returns a wrapped value then that works. I
hacked quite a bit on this for another project and it breaks down when you
start introducing digit indexes to lists in the string for a recursive
getitem

**Comment by HonzaKral** [comment]
That is exactly when my trial implementation broke down too + I also tried to implement the setters with similar semantics.

Thanks!

**Comment by kputland** [comment]
The only other thing I would suggest is using OrderedDict everywhere
instead of dict. Especially if coming from/to xml, order is important. I
don't know if elasticsearch will maintain the order on store/retrieve yet,
but the library should if possible support maintaining order.

 json.loads(json_string, ordered_pairs_hook=OrderedDict)

Karl Putland
Senior Engineer
*SimpleSignal*
Anywhere: 303-242-8608
<http://www.simplesignal.com/explainer_video.php>

**Comment by HonzaKral** [comment]
I am sorry, but I have to disagree again - the overhead of OrderedDict is not worth it. Not to mention that json itself doesn't guarantee the order of items in an object (from the RFC): 

   > An object is an unordered collection of zero or more name/value pairs, where a name is a string and a value is a string, number,  boolean, null, object, or array.

If you need to support serialization into XML which requires specific order of elements I am afraid you will have to handle it in the serialization layer yourself.
