### ISSUE TITLE
Add support for the multi_terms aggregation

### ISSUE THREAD

**Issue by bralbral** [elastic/elasticsearch-dsl-py#1512]
Good day!

How can i use [multu-terms aggregation](https://www.elastic.co/guide/en/elasticsearch//reference/master/search-aggregations-bucket-multi-terms-aggregation.html#:~:text=Multi%20Terms%20aggregationedit,and%20will%20consume%20more%20memory.) ?

I have got : `elasticsearch_dsl.exceptions.UnknownDslObject: DSL class `multi_terms` does not exist in agg.`
Is there a method implemented?

**Comment by sethmlarson** [comment]
This aggregation is new in Elasticsearch 7.12 and hasn't been implemented in Elasticsearch-DSL natively yet.

**Comment by sethmlarson** [comment]
No need to close this until it's implemented.

**Comment by robindierckx** [comment]
same problem with `combined_fields` (new in elastic_search 7.13):

```
elasticsearch_dsl.exceptions.UnknownDslObject: DSL class `combined_fields` does not exist in query.
```

While waiting for it to be implemented, is there a workaround to tell DSL "don't bother, just add the parameter in the elastic search request"

**Comment by snowwhitehat** [comment]
Any idea on timeline for the 'multi_terms' aggregation being natively supported in the elasticsearch dsl? Cheers!

**Comment by Telomeraz** [comment]
I've just sent a pr for this issue, could you please review it and add "hacktoberfest" label to the issue? @sethmlarson 

Also, should i create a new issue to implement "combined_fields" query?

**Comment by EvieGillie** [comment]
Is there a workaround in the meantime?

**Comment by Telomeraz** [comment]
I think there isn't. You can write it natively. @EvieGillie

**Comment by vipulg13** [comment]
please consider adding support to the "combined_fields" query. @Telomeraz

**Comment by vipulg13** [comment]
@Telomeraz should I create a new issue for combined_fields, as this one is closed?

**Comment by Telomeraz** [comment]
@vipulg13 Yes, you can create a new one.
