### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by nrsimha** [elastic/elasticsearch-dsl-py#1514]
Hi, 

Seems there is no commits or pull merges going on.

Is this project alive or is it replaced by something else?

**Comment by sethmlarson** [comment]
Yes it is alive, however I as the sole maintainer have been busy so haven't had time to contribute myself.

Is there something pressing that spurred this issue being opened?

**Comment by nrsimha** [comment]
"Is there something pressing that spurred this issue being opened?"

I am using this library from version 5.x, and is very good, but there is missing year interval in DateHistogramFacet facet. Previously there was opened issue for old version, but was never committed and it was closed.

I have opened new issue for 7.x version 2 months ago, but didn't get any response.

Year range can be quite usefull to have as it allows narrow results by years, you can see it used here: 
https://vedabase.io/en/library/transcripts/ (second filter block "Filter by year")

Can I somehow help to get it committed?
