### ISSUE TITLE
Field type for approximate k-NN Search

### ISSUE THREAD

**Issue by snthibaud** [elastic/elasticsearch-dsl-py#1515]
Hello! I am very happy using the elasticsearch-dsl library, but was unsure how to use the knn-search plugin with it (see https://opendistro.github.io/for-elasticsearch-docs/docs/knn/approximate-knn/). Specifically, I am trying to create a new document and save it, but noticed the 'knn_vector' field type does not exist. How could I define this type? Any ideas?

**Comment by moshfrid** [comment]
+1

**Comment by sethmlarson** [comment]
This feature isn't a part of Elasticsearch so we won't be implementing it. Elasticsearch supports dense_vector and knn_search for this use-case.
