### ISSUE TITLE
to_dict() doesn't convert inner_hits

### ISSUE THREAD

**Issue by command-tab** [elastic/elasticsearch-dsl-py#1520]
Maybe related to https://github.com/elastic/elasticsearch-dsl-py/issues/291, I'm attempting to dump my elasticsearch-dsl response by calling `to_dict()`, but it doesn't appear to walk the entire structure. `inner_hits` appear to be `Response` instances, but calling `to_dict()` on the top-level response doesn't convert them. Why does it convert hits but not inner_hits? Is there a simple way to convert the _entire_ response without having to pick apart the structure and manually call `to_dict()` as needed?

I'm using Python 3.8 and elasticsearch-dsl 7.4.0.

Thanks so much for this library! ❤️ It's incredibly useful.

**Comment by miguelgrinberg** [comment]
With this fix, you can use `response.to_dict(recursive=True)` to ensure that the entire tree is converted to dict.
