### ISSUE TITLE
Missing values from DocType spec

### ISSUE THREAD

**Issue by emanuelvianna** [elastic/elasticsearch-dsl-py#153]
Hi,

I'm a little unsatisfied with the fact that elasticsearch-dsl don't treat missing value from DocType spec.

Let me show an example to clarify my issue:

```python
>>> from elasticsearch_dsl import DocType, String
>>> from elasticsearch_dsl.connections import connections

>>> connections.create_connection(hosts=['localhost'])

>>> class Article(DocType):
>>>     title = String(index='not_analyzed')
>>>     class Meta:
>>>         index = 'blog'

>>> Article.init()
>>> Article(id=42).save()
>>> Article.get(id=42).title

Traceback (most recent call last)
.. 
AttributeError: 'Article' object has no attribute 'title'
```
The lack of a non initialized attribute forces me to treat it with some boilerplate code (such as ```hasattr```). 

One approach, which I suggest, is the same applied by Mongoengine (correct if I'm wrong please). Since MongoDB is schema free, they don't write the None fields in the collection. Rather, they overwrite ```__getattr__``` to check if the field is in the Document spec. If the field was found, than they do a get(field, None) to be able to deal with missing values.

I can make a fork and submit a PR of this proposal. But first I wanna know what do you guys think about it. Does that change affect any other assumption of your code.

**Comment by HonzaKral** [comment]
As a reaction to #145 I implemented a feature when you can set a field to `blank` and then it will behave as you wish. I am not happy about the naming and am wondering what should be the default.

the implementation is in https://github.com/elastic/elasticsearch-dsl-py/compare/blank?expand=1#diff-34d6bbb6c1bc63e482787fa540c41a53R76

**Comment by HonzaKral** [comment]
This has now be merged to master, just specify `blank=True` and it should work.

**Comment by hakanw** [comment]
Thanks Honza!!

2015-06-11 2:41 GMT+02:00 Honza Král <notifications@github.com>:
