### ISSUE TITLE
Allow for the use of `set`s in search request index declaration

### ISSUE THREAD

**Issue by elkirby** [elastic/elasticsearch-dsl-py#1532]
if a `set` type is sent to the `Search` keyword argument instantiation for `index`, it is wrapped in a list like so:
```python
>>> s = Search(index={'wagtail__wagtaildocs_document', 'wagtail__wagtailcore_page'})
>>> s._index
[{'wagtail__wagtaildocs_document', 'wagtail__wagtailcore_page'}]
```

I would like to contribute a change for all of the type coercion to lists across the `Request` object to be handled in a single place, so that the following pieces of code use a single helper function `_to_list` (that also allows for `set`s) to return a list version of the input:
* [`_index` instantiation](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L121-L124)
* [`_doc_type` instantiation (directly following `_index`)](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L128-L134)
* [`index(self, *index, **kwargs)` input coercion](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L179-L191)
* [`doc_type(self, *doc_type, **kwargs)` input coercion](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L264-L270)

--------
If a smaller change is desired, I would alternatively like to add `set` to the list of types checked for [in the _index instantiation](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L121-L124):
```python
        self._index = None
        if isinstance(index, (tuple, list, set)):
            self._index = list(index)
```

and in the [index() method](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L183-L189)

```python
            for i in index:
                if isinstance(i, string_types):
                    indexes.append(i)
                elif isinstance(i, list):
                    indexes += i
                elif isinstance(i, (tuple, set)):
                    indexes += list(i)
```

**Comment by sethmlarson** [comment]
Sets aren't supported because they're unordered. I know in the circumstances you list that order doesn't matter but in some places order does matter so we've taken the stance of not natively supporting sets. If you want to use sets you can call `list(...)` right before passing the value to elasticsearch-dsl.

Going to close this one for now.
