### ISSUE TITLE
add type annotations

### ISSUE THREAD

**Issue by chdsbd** [elastic/elasticsearch-dsl-py#1533]
Hi!

Adding type annotations to this library would allow for better auto complete and type checking with tools like mypy and pyright.

Would you accept a PR that adds type annotations?

**Comment by heinrichreimer** [comment]
This would be incredibly useful for the Elasticsearch DSL, as it would mean truly type-safe access to Elasticsearch from Python!

**Comment by heinrichreimer** [comment]
Ideally, the package should then also be declared as a [PEP 561 compliant stub package](https://mypy.readthedocs.io/en/stable/installed_packages.html#installed-packages).

**Comment by CosmicTiger** [comment]
Hello everyone. I would like to know if there's any continuation regarding this. I often time has this issue from the VSCode Linting and if is possible I would like to help and contribute in solving this issue if you would let me too after a brief explanation on how the project works. 
![image](https://github.com/elastic/elasticsearch-dsl-py/assets/30613501/4ea02f05-9dce-43dc-84ce-d384e0240ac0)

**Comment by pquentin** [comment]
Hello! As the new maintainer, I am in favor of adding types, but do not want one huge pull request. Instead, it should be done incrementally, as described in https://sethmlarson.dev/tests-arent-enough-case-study-after-adding-types-to-urllib3. I will be happy to review small pull requests, adding types to small files first. Thanks!

**Comment by miguelgrinberg** [comment]
This is going to be out with the 8.15 release.
