### ISSUE TITLE
How to specify script.max_size_in_bytes?

### ISSUE THREAD

**Issue by stugots** [elastic/elasticsearch-dsl-py#1537]
On https://www.elastic.co/guide/en/elasticsearch/reference/current/scripts-and-search-speed.html is this note:

<img width="703" alt="Screen Shot 2021-10-03 at 11 28 36 AM" src="https://user-images.githubusercontent.com/231148/135766766-229d3cb4-629d-4905-9dc0-e01e42eb2269.png">

I have a script that will sometimes be over the limit.  Overriding `max_size_in_bytes` is easier than writing a script engine so that's what I want to try first.

I can't get this to work!  I've tried every permutation I can think of and the value is either ignored or generates an error.

For example,
```
return (
    query.query(
        Q(
            "script",
            script={
                "lang": "painless",
                "source": f"""
                 // We don't bother checking if the profile_id field is present.  It must be.
                 return {target["exclusion"]}.contains(doc["profile_id"].getValue().intValue());
                 """,
                "max_size_in_bytes": 100000
            },
        )
    )
 ```
results in:
```
elasticsearch.exceptions.RequestError: RequestError(400, 'x_content_parse_exception', '[1:655316] [script] unknown field [max_size_in_bytes]')
```

I can't find any usage examples of this dynamic property on the web...

Is `script.max_size_in_bytes` supported by this package?  Can anyone give me a pointer as to how to set it?

**Comment by sethmlarson** [comment]
That is an Elasticsearch setting being referenced, not anything that you can set client-side. Try setting within your Elasticsearch configuration or as a [transient cluster setting](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-update-settings.html)

**Comment by stugots** [comment]
@sethmlarson Thank you!  Gosh I feel a little silly.  :-)
