### ISSUE TITLE
Lower case values

### ISSUE THREAD

**Issue by emilian** [elastic/elasticsearch-dsl-py#154]
The values that I am storing in ES are upper case, but they returned as lower case after querying using this library. For example, I have a field named "origin", and I am storing "USA" as the value.

I am using Postman to get the document from ES and the values are in upper case.

After doing something like this: `response.aggregations.to_dict()` the values are lower case. 

Is Python doing this, or is from the library? Or am I looking in the wrong place altogether?

**Comment by HonzaKral** [comment]
You are looking in the wrong place. This happens in elasticsearch when you have a string field with default analyzer (which is what's happening unless you specify anything else).

For fields like this - where you want to run aggregations, you need to specify their mapping (0) to include the option `"index": "not_analyzed"`. In the python dsl that would be `String(index='not_analyzed')`. If you want to also search on that field, you should define the field to be both analyzed and not analyzed using multi-fields (1):

    class MyDoc(DocType):
        origin = String(fields={'raw': String(index='not_analyzed')})

Then you can search with `origin` and aggregate/sort via `origin.raw`.

Hope this helps.

0 - http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html
1 - http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-core-types.html#_multi_fields_3

**Comment by HonzaKral** [comment]
This is a mapping issue not related to the library, closing the ticket.
