### ISSUE TITLE
Issue with ES >= v7.15.0: TypeError: search() got multiple values for keyword argument 'size'

### ISSUE THREAD

**Issue by jgb** [elastic/elasticsearch-dsl-py#1541]
Hello,

I'm upgrading ES from v7.14.2 to v7.15.1 and I'm getting an error on code that used to work fine:

```
resp = client.search(
            scroll=scroll, size=size, request_timeout=request_timeout, **search_kwargs
        )
E       TypeError: search() got multiple values for keyword argument 'size'

/usr/local/lib/python3.8/dist-packages/elasticsearch/helpers/actions.py:571: TypeError
```

I'm doing a search.scan() without any extra parameters, and the search itself has from=0 and size=0.
If I remove the pagination entirely, it works.
Any idea what might be going on?
Downgrading ES to v7.14.2 solves the issue.
I've checked recent bug reports on elasticsearch and elasticsearch-dsl but nothing similar shows up.
The changelog of elasticsearch itself also doesn't give any clues.

Greetings,

Jan

**Comment by hvdklauw** [comment]
Yeah, it seems everything broke the elasticsearch 7.14 package doesn't even seem to support 7.14 let alone 7.15 (seems that someone doesn't understand versioning)

**Comment by jgb** [comment]
This turned out to be a bug in elasticsearch and not elasticsearch-dsl.
Closing.

Reference: https://github.com/elastic/elasticsearch-py/issues/1766
