### ISSUE TITLE
All queries hanging

### ISSUE THREAD

**Issue by wtroisey** [elastic/elasticsearch-dsl-py#1548]
Hi,

I'm using elasticsearch_dsl to query a remote node hosing ~80GB (soon to be much more) of 8 indices. Elasticsearch_DSL used to work a treat and I'm having issues debugging the issue server-side.

Client system:

- Linux Mint 19.1
- Python 3.6.9
- elasticsearch-dsl 7.3.0

A trimmed down version of my code is below.

```python
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search

client = Elasticsearch('http://192.168...:9200')
s = Search(client).params(request_timeout=3600)[0:10]

s = s.query('match', data='test')

s = s.highlight_options(order='score')
s = s.highlight('data', fragment_size=60, pre_tags=["<strong>"], post_tags=["</strong>"])

results = s.execute()
print(len(results))
```

The `s.execute()` line blocks until I get the error `elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at ...>: Failed to establish a new connection: [Errno 110] Connection timed out)`.

Normally I'd assume it's a problem with the server's processing speed, however I've tested queries using ElasticVue (app.elasticvue.com) and I get a successful response within a few seconds.

I appreciate any help in advance, is this a known issue with Elasticsearch?

**Comment by sethmlarson** [comment]
That error is definitely coming from the connection layer, not sure what is causing the issue. You might look at the Elasticsearch log when you try to connect to see if there are any clues.

**Comment by wtroisey** [comment]
Closing issue, solution: don't be an idiot. Windows firewall was blocking all remote connections, create rule to allow port 9200 through. Thanks for the help
