### ISSUE TITLE
how to apply "terminate_after" 

### ISSUE THREAD

**Issue by grimmer0125** [elastic/elasticsearch-dsl-py#1549]
`terminate_after` is introduced in https://www.elastic.co/guide/en/elasticsearch/reference/7.13/search-search.html. 

Below shows that `elasticsearch` client can append this parameter in its API, but I can not find out how to let `elasticsearch-dsl` has `terminate_after` effect. 
```
res = es.search(index="test-index", body={"match_all": {}}, terminate_after=100)
```

library versions:
```
elasticsearch = "7.13.4"
elasticsearch-dsl = "^7.4.0"
```

**Comment by Telomeraz** [comment]
@grimmer0125 You should use `.extra(terminate_after=100)` after query:

`Search(index="your_index").query("your_query").extra(terminate_after=100)`

ref: https://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#extra-properties-and-parameters

**Comment by sethmlarson** [comment]
Thanks for answering.
