### ISSUE TITLE
ElasticSearch incompatibility with Sphinx 4.2.0

### ISSUE THREAD

**Issue by FreddieDev** [elastic/elasticsearch-dsl-py#1552]
Hi all,

**My Python project uses:**
* elasticsearch (7.14.1)
* elasticsearch-dsl (7.4.0)
* Sphinx to auto-generated documentation.

Issues started when we updated Sphinx from 3.0.4 to 4.2.0.

**Example:**
Usage of Elastic's Nested object (`from elasticsearch_dsl import Nested`), results in the Sphinx error:
`TypeError: unhashable type: 'Nested'`

The usage is as follows:
```python
class CustomerPackage(InnerDoc):
    """A CustomerPackage Object."""

    @property
    def id(self):
        """Unique GUID for the CustomerPackage."""
        return self.meta.id

    type: Text = Text(analyzer="snowball")
    """ CustomerPackage Type. """

    description: Text = Text(analyzer="snowball")
    """ CustomerPackage Description. """

    lost: bool = Boolean()
    """ Determines if the CustomerPackage was lost in transmission."""

    package_content: Nested(PackageContent) = Nested(PackageContent, multi=False)
    """ Content involved in the message. """
```

If there are further details I can provide, please let me know.
Hoping someone else has ran into this too, in case there's an easy fix.

Many thanks

**Comment by FreddieDev** [comment]
Hi all, I've created a mockup repo that can reproduce the bug:
https://gitlab.com/fchessell/sphinx-bug-demo

I hope this helps

**Comment by sethmlarson** [comment]
Unfortunately I don't think there's much we can do here unless the Sphinx issue you opened comes back to us. Thanks for making us aware of this, going to close for now.
