### ISSUE TITLE
Problem with creating index with proper mapping by using init() method of the Document.

### ISSUE THREAD

**Issue by smbatyan1729** [elastic/elasticsearch-dsl-py#1555]
I have a problem with creating an index with proper mapping. 
I used to use the DSL library to define my mapping. Afterward, I used the `init()` method written in some `setup()` function that is located in the same file as the Document. 
The documentation implies that the `init()` method will create an index and it does, but the problem is that the mapping is empty. 🤔 

Examples:
1) **same_file.py**
```
class Foo(Document):
    first_name = Text(fields={"keyword": Keyword()}, required=True)
    last_name = Text(fields={"keyword": Keyword()}, required=True)
    role = Nested(Role)

    class Index:
        name = 'foo'

def setup():
    Foo.init()
```
In this case, an Index has been created but the mapping is empty.

2) 
**file_1.py**
```
class Foo(Document):
    first_name = Text(fields={"keyword": Keyword()}, required=True)
    last_name = Text(fields={"keyword": Keyword()}, required=True)
    role = Nested(Role)

    class Index:
        name = 'foo'
```

**file_2.py**
```
from file_1 import Foo

def setup():
    Foo.init()
```
In this case, everything works as expected.

I want to know is this an expected behavior or not?

**Comment by Telomeraz** [comment]
@smbatyan1729  This is not expected behavior. I am using the last version of the package (7.4.0) and cannot reproduce it. Where do you run foo function? Can you share more information please?

**Comment by smbatyan1729** [comment]
@Telomeraz I created a new project and checked one more time. Seems it is working for the new project. 
Sorry for the inconvenience and thank you for the response 🙏 
Will close the issue.
