### ISSUE TITLE
Add support for "combined_fields" query

### ISSUE THREAD

**Issue by vipulg13** [elastic/elasticsearch-dsl-py#1556]
Dear team,

could you please consider adding support to the "combind_fields" query? I could see a similar request is raised in #1512, and a PR #1534  for adding the functionality is still open.

Thanks in advance!

**Comment by vipulg13** [comment]
is there any tentative date for merging the PR #1557 into the Master? @Telomeraz

**Comment by Telomeraz** [comment]
@sethmlarson knows it.
