### ISSUE TITLE
no method to call es.update directly without a doc (wanted for scripted updates)

### ISSUE THREAD

**Issue by haynesgt** [elastic/elasticsearch-dsl-py#1559]
Using elasticsearch_dsl==7.4.0

If I want to update a document by id using a script I need to do

```
doc = MyDocument()
doc.meta.id = my_id
doc.update(script=my_script)
```

but the new doc creation is redundant. It would make more sense if there were a static method e.g.

```
MyDocument._index.update(id=my_id, script=my_script)
```

**Comment by miguelgrinberg** [comment]
I would suggest using the low-level client directly for this.
