### ISSUE TITLE
No way to specify script language in Document.update

### ISSUE THREAD

**Issue by haynesgt** [elastic/elasticsearch-dsl-py#1560]
elasticsearch_dsl==7.4.0

The script param is assumed to be a string here:

https://github.com/elastic/elasticsearch-dsl-py/blob/c089a40ce6566de8a1fb5943501d2e6bfc4c06c7/elasticsearch_dsl/document.py#L391

but there is no way to set the language of the script.

It would be more intuitive if it set `body["script"] = script` if the script param were a dict.

**Comment by sethmlarson** [comment]
That'd be a nice addition, would you be able to open a PR with the feature and test(s)?

**Comment by haynesgt** [comment]
ok

**Comment by haynesgt** [comment]
@sethmlarson could you review the pr?
