### ISSUE TITLE
```dis_max``` query type is missing

### ISSUE THREAD

**Issue by moghadas76** [elastic/elasticsearch-dsl-py#1565]
Based on the [document ](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-dis-max-query.html) this type is not supported.

**Comment by Telomeraz** [comment]
It is supported by elasticsearch-dsl-py. See: [elasticsearch_dsl.query.DisMax](https://github.com/elastic/elasticsearch-dsl-py/blob/477eb084d162ce46fb6437ee056076cfc8574fb8/elasticsearch_dsl/query.py#L271)

Can you share the error you got? @moghadas76
