### ISSUE TITLE
When will there be a release for 8.0.0?

### ISSUE THREAD

**Issue by duyongan** [elastic/elasticsearch-dsl-py#1569]
[Ann  vector search]  is attractive.
I have tried es-py 8.0,but I am used to use dsl-py.
when can this project release 8.0.0

**Comment by sethmlarson** [comment]
There's a lot of work that needs to go into an 8.0.0 release of elasticsearch-dsl. For now you can use the `knn_search` API directly on the `Elasticsearch` instance.

**Comment by allisonsuarez** [comment]
Can we get a release with the current code? @sethmlarson I am trying to use the combined_fields query which was recently introduced

**Comment by allisonsuarez** [comment]
^ @Telomeraz

**Comment by redbaron4** [comment]
Seeing as ES-8x is now pretty stable, it would be great to have a DSL-8.x release. We have jobs that rely on DSL and we are not sure if existing DSL-7.4 will be able to talk to ES-8.x. So our plans to update ES to 8.x are dependent on their being a DSL-8.x. Can we use DLS-7.4 safely with upgraded Elasticsearch?

**Comment by Telomeraz** [comment]
I want to volunteer for the works that need to be done for an 8.0.0 release of elasticsearch-dsl. I just need some guidance about what works needs to be done. @sethmlarson

**Comment by jonaslb-bg** [comment]
I don't think transitioning to ES8 should be too hard, I think in pretty much all places that `es.some.api_call(kwarg="something", body=self.to_dict())` can simply be replaced with `es.some.api_call(kwarg="something", **self.to_dict())` and then that should be it?

The part that might require some more code change is transitioning the tests codebase. It looks like this project is importing `elasticsearch.helpers.test`, which has been deleted from `elasticsearch`, so something else entirely needs to be done there.

**Comment by pedroyzkrak** [comment]
I also need the MultiTerms aggregation that was recently included :(

**Comment by gbarsky** [comment]
I would also like to know if there is any progress on having elastcisearch-dsl compatible with ES 8.x.x ?

**Comment by nis267** [comment]
Someone knows an alternative for the elasticsearch-dsl-py package for the 8.x versions?

**Comment by MRuecklCC** [comment]
@pedroyzkrak I worked around the missing `MultiTerms` by simply defining the following in my own scope:

```python
from elasticsearch_dsl.aggs import Bucket
    class MultiTerms(Bucket):  # noqa
        name = "multi_terms"
```
It seems, the meta-classes in the `Bucket` class hierarchy takes care of the rest.
Afterwards I was able to add aggregations as follows:

```python
 search.aggs.bucket(
   "material_type_and_collection",
   {
      "multi_terms": {
          "size": 50000,
          ...
      }
   }
)
```

**Comment by sethmlarson** [comment]
Sorry folks that there hasn't been any update on official 8.x support. I can't make guarantees about when it will come, but it is something that is in our mind. We're currently training our new Python client maintainer and so she is focused on mostly the Elasticsearch Python client currently.

If you'd like to use the elasticsearch-dsl library with an 8.0+ cluster you can configure the client to use [7.x compatibility mode](https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/migration.html#migration-compat-mode) and should work seamlessly with the 7.x version of elasticsearch-dsl.

**Comment by WildDogOne** [comment]
I want to chime in on this issue too, I just install the latest version of elasticsearch-dsl and after that upgrade to the latest version of elasticsearch
example:
pip3 install elasticsearch-dsl --upgrade
pip3 install elasticsearch>8 --upgrade

so far everything I have done works perfectly, but I won't pretend that I did a full feature test

**Comment by PlugaruT** [comment]
Any way to not force the `elasticsearch>=7.0.0,<8.0.0` [here](https://github.com/elastic/elasticsearch-dsl-py/blob/master/setup.py#L32)? 
Since we are using both `elasticsearch` package and we want to upgrade to v8+, we can't do it because versions are not compatible. I am planning to enable compatibility mode after the update, but with this hard limitation, we can't really build Docker images in a reliable way.

**Comment by redbaron4** [comment]
@PlugaruT You can clone the source, edit the file and change version to anything unreleased (7.4.1 or 7.5 or even 7.9.9). Then build the python package and use it directly (maybe even upload it to a **local** PyPI repo within organization). We are using this workaround as a stop-gap.

**Comment by jgb** [comment]
Hello,

any news on this topic? We're on elasticsearch v8.5.3 by now, it would be very much appreciated to get elasticsearch-dsl-py compatible again. It's blocking an ES upgrade from v7 to v8 for us, and I can imagine we're not alone.
At this point it's starting to look a bit abandoned?

jgb

**Comment by phoerious** [comment]
It does indeed look abandoned. Which is strange, since according to the docs, it is the recommended go-to API if you don't want to mess with the low-level client. Funnily, this is still true for the 8.5 docs: https://www.elastic.co/guide/en/elasticsearch/client/python-api/8.5/overview.html#_elasticsearch_dsl

**Comment by ColeDCrawford** [comment]
Over a year later, nothing ...

**Comment by mcepl** [comment]
That’s what I call a dead parrot.

**Comment by WildDogOne** [comment]
well the original statements still hold true, it works, just it's not supported ;)
But I agree, it should really be updated, no idea why this is so dead

**Comment by atlasstrategic** [comment]
This library was the main reason why I moved from AWS elasticsearch to Elastic's own cloud service (after Amazon started OpenSearch). Really would like to continue with it.

In the meantime, Amazon created [opensearch-dsl-py](https://github.com/opensearch-project/opensearch-dsl-py), however they have deprecated it…
> The OpenSearch high-level Python client (opensearch-dsl-py) will be deprecated after version 2.1.0. We recommend switching to the Python client (opensearch-py), which now includes the functionality of opensearch-dsl-py.

**Comment by hatdropper1977** [comment]
I love the DSL - what can I do to help the team get 8.X.X support?

**Comment by jgb** [comment]
@sethmlarson still no news on this topic? Is this library abandoned or will it still get an official release for v8?

**Comment by j-adamczyk** [comment]
@sethmlarson any news on this? If this library is indeed deprecated, or there is no capability to officially support this, maybe select and pass this to other maintainers. This is literally in your docs as an official go-to way for Python + Elasticsearch, and does not work over a year after release of Elasticsearch 8.0.

**Comment by MartinAkram** [comment]
@sethmlarson I know you've been pinged a lot, so I apologize, but any word (yay or nay) about whether or not the DSL library will get support for ES8 would be great. Even if the answer is "no, we're not updating it", that would still be helpful to know because it would be a definitive answer for us about whether or not we should start rewriting existing DSL code without the DSL. Thank you

**Comment by jgb** [comment]
There was a relevant update from @ezimuel in https://github.com/elastic/elasticsearch-dsl-py/issues/1652

**Comment by jgb** [comment]
And 1 month after stating that this library is still supported and that work will continue, still not a single commit was made.
Sigh.

**Comment by jgb** [comment]
@sethmlarson  still no update? Is this the type of relationship that the company elasticsearch wants to have with their users?

**Comment by WildDogOne** [comment]
@jgb I can only re-iterate that the 7.x release does work for 8.x
But yes, it would be nice to have this officially supported

**Comment by mlec1** [comment]
In the [last commit](https://github.com/elastic/elasticsearch-dsl-py/commit/56832d816ac01c08aba89d84f35b3ca404f5cd7e), they implemented the support for Elastic 8 finally 🎉🎉

Thank you @pquentin

**Comment by MartinAkram** [comment]
LET'S GOOOOOOOOOO!

**Comment by pquentin** [comment]
Hello everyone! I'm a new maintainer for Python clients at Elastic, working with @JoshMock, @ezimuel and others. I would like to sincerely apologize for the delay and lack of communication as the team was overworked for the past months.

As some of you have noticed, I've been working with @JoshMock on Elasticsearch 8.x support, and I have just uploaded the result *as a pre-release* on PyPI: https://pypi.org/project/elasticsearch-dsl/8.9.0a1/. Can you please try it out using `pip install --pre elasticsearch-dsl` and report the bugs you find? If nothing too critical is found, I'll publish the final 8.9.0 release next week. Thank you!

PS: I know there is a big backlog of pull requests, but I'm not ready to go through it yet, sorry.

**Comment by mcepl** [comment]
Works for me with [elasticsearch 8.9.0](https://build.opensuse.org/package/show/devel:languages:python/python-elasticsearch) and [elasticsearch-dsl 8.9.0a1](https://build.opensuse.org/package/show/devel:languages:python/python-elasticsearch-dsl) as openSUSE packages.

**Comment by pquentin** [comment]
elasticsearch-dsl-py 8.9.0 is out! https://pypi.org/project/elasticsearch-dsl/. Please report any bug you find in new issues.

**Comment by lmontopo** [comment]
any chance this will be packaged as `elasticsearch8-dsl` at some point soon (so i can install it with other versions)?

**Comment by pquentin** [comment]
@lmontopo Sure, I opened https://github.com/elastic/elasticsearch-dsl-py/issues/1677 to track this.
