### ISSUE TITLE
elasticsearch.exceptions.ConnectionError: ConnectionError(timeout() got an unexpected keyword argument 'loop')

### ISSUE THREAD

**Issue by zkailinzhang** [elastic/elasticsearch-dsl-py#1573]
File "/home/miniconda3/envs/py37/lib/python3.7/site-packages/elasticsearch_async/connection.py", line 111, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(timeout() got an unexpected keyword argument 'loop') caused by: TypeError(timeout() got an unexpected keyword argument 'loop')
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f95d4dd5dd0>

**Comment by sethmlarson** [comment]
Can you run `python -m pip freeze` and post the output? I suspect you have a version of aiohttp installed that isn't being tested?
