### ISSUE TITLE
Overcome "Legacy index templates are deprecated" warning

### ISSUE THREAD

**Issue by neurino** [elastic/elasticsearch-dsl-py#1576]
I updated the Elasticsearch Service to v. 7.17.0 to fix any Log4j related risks and I started receiving this warning:

> Legacy index templates are deprecated in favor of composable templates

I can't find where I borrowed the following code that I'm using since I adopted Elasticsearch, nevertheless I can't find any reference on how to manage composable templates using `elasticsearch-dsl-py`

Any clue?

```
class IndexTemplate(Document):
    kind = Keyword()
    urlsafe = Keyword(ignore_above=512)
    
    class Index:
        #this will match all new indexes with name matching the wildcard
        name = f"{INDEX_PREFIX}*"

#save as index template
index_template = IndexTemplate._index.as_template('xyz', order=0)
index_template.save(using=es)
```

**Comment by martinsvoboda** [comment]
I think elasticsearch-dsl-py doesn't have support for composable index templates. Meawhile you can create composable template index manually like this:

```python
from elasticsearch_dsl import IndexTemplate
from elasticsearch_dsl.connections import connections

def save_index_template_as_composable(template: IndexTemplate, using=None):
    es = connections.get_connection(using or template._index._using)

    template_body = template.to_dict()
    index_patterns = template_body.pop("index_patterns")
    order = template_body.pop("order", None)

    d = {
        "template": template_body,
        "index_patterns": index_patterns,
        "composed_of": [],
    }
    if order is not None:
        d["order"] = order

    return es.indices.put_index_template(name=template._template_name, body=d)

# save as index template
index_template = IndexTemplate._index.as_template('xyz', order=0)
# index_template.save(using=es)
save_index_template_as_composable(index_template, using=es)


```

**Comment by neurino** [comment]
Thank you Martin, I'm going to try this. 

One question: where has my `INDEX_PREFIX*` gone? I _do_ use prefixes to separate data.

Should I do something like this?

    from elasticsearch_dsl import Document, Keyword, IndexTemplate
    from elasticsearch_dsl.connections import connections

    class XYZIndexTemplate(Document):
        kind = Keyword()
        urlsafe = Keyword(ignore_above=512)
        
        class Index:
            #this will match all new indexes with name matching the wildcard
            name = f"{INDEX_PREFIX}*"

    def save_index_template_as_composable(template: IndexTemplate, using=None):
        es = connections.get_connection(using or template._index._using)

        template_body = template.to_dict()
        index_patterns = template_body.pop("index_patterns")
        order = template_body.pop("order", None)

        d = {
            "template": template_body,
            "index_patterns": index_patterns,
            "composed_of": [],
        }
        if order is not None:
            d["order"] = order

        return es.indices.put_index_template(name=template._template_name, body=d)

    #save as index template
    xyz_index_template = XYZIndexTemplate._index.as_template('xyz', order=0)
    #index_template.save(using=es)
    save_index_template_as_composable(xyz_index_template, using=es)

**Comment by martinsvoboda** [comment]
This is working example:

```python
from elasticsearch_dsl import IndexTemplate, Document, field
from elasticsearch_dsl.connections import connections

INDEX_PREFIX = "my_prefix_"

class MyDocument(Document):
    kind = field.Keyword()
    urlsafe = field.Keyword(ignore_above=512)

    class Index:
        # this will match all new indexes with name matching the wildcard
        name = f"{INDEX_PREFIX}*"


def save_index_template_as_composable(template: IndexTemplate, using=None):
    es = connections.get_connection(using or template._index._using)

    template_body = template.to_dict()
    index_patterns = template_body.pop("index_patterns")
    order = template_body.pop("order", None)

    d = {
        "template": template_body,
        "index_patterns": index_patterns,
        "composed_of": [],
    }
    if order is not None:
        d["priority"] = order

    return es.indices.put_index_template(name=template._template_name, body=d)

# save as index template
es = connections.get_connection()
index_template = MyDocument._index.as_template('xyz', order=2)
save_index_template_as_composable(index_template, using=es)

# Check result:
# http://localhost:9200/_cat/templates?v
# http://localhost:9200/_index_template/xyz
```


**Where has my INDEX_PREFIX gone? I do use prefixes to separate data.**


Checkout implementation of:
* Index.as_template: https://github.com/elastic/elasticsearch-dsl-py/blob/477eb084d162ce46fb6437ee056076cfc8574fb8/elasticsearch_dsl/index.py#L77
* TemplateIndex.__init__ https://github.com/elastic/elasticsearch-dsl-py/blob/477eb084d162ce46fb6437ee056076cfc8574fb8/elasticsearch_dsl/index.py#L28
* TemplateIndex.to_dict https://github.com/elastic/elasticsearch-dsl-py/blob/477eb084d162ce46fb6437ee056076cfc8574fb8/elasticsearch_dsl/index.py#L45

INDEX_PREFIX* is passed internally in Index.as_template or you can override it with pattern parameter.

**Comment by neurino** [comment]
Thank you Martin,

I used your code and warnings are gone :)

I got one last warning:

`ElasticsearchWarning: index template [xyz] has index patterns [my_prefix_*] matching patterns from existing older templates [xyz] with patterns (xyz => [my_prefix_*]); this template [xyz] will take precedence during new index creation`

which I resolved deleting the old `xyz` in the UI under Stack Management > Index Management > Legacy index template

I hope I did it right
