### ISSUE TITLE
KeyError exception when call Mapping.from_es() using index alias

### ISSUE THREAD

**Issue by wataru-chocola** [elastic/elasticsearch-dsl-py#158]
version: elasticsearch-dsl-py 0.0.4

I called `Mapping.from_es()` with index alias,

```
$ curl -XGET 'http://localhost:9200/test/_alias/'
{"test.v1":{"aliases":{"test":{}}}}
```
```
m = elasticsearch_dsl.Mapping.from_es('test', 'my_type')
```

and got errors.

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    mapping = elasticsearch_dsl.Mapping.from_es('test', 'my_type')
  File "/home/myacc/.venv/local/lib/python2.7/site-packages/elasticsearch_dsl/mapping.py", line 32, in from_es
    m.update_from_es(index, using)
  File "/home/myacc/.venv/local/lib/python2.7/site-packages/elasticsearch_dsl/mapping.py", line 73, in update_from_es
    raw = raw[index]['mappings'][self.doc_type]
KeyError: 'test'
```

This is because 1st level key of response object is index name, instead of alias.

```
$ curl -XGET 'http://localhost:9200/test/_mapping/' | jq .
{
  "test.v1": {
    "mappings": {
      "my_type": {
        "properties": {
          "name": {
            "index": "not_analyzed",
            "type": "string"
          }
        },
        "_all": {
          "enabled": false
        },

```

Do you planned to support index alias?

Regards

**Comment by HonzaKral** [comment]
Hi,
I totally want to support aliases, just not sure how exactly - my goal was to switch to something smarter than just using strings for index names etc (like the `Index` object we already have), that way this could be separated into that object.

This however seems like it would be solvable even without that so I might just fix it before the redesign.

Thanks for reporting this!
