### ISSUE TITLE
Using the scan method: how to add preserve_order=True?

### ISSUE THREAD

**Issue by njoannin** [elastic/elasticsearch-dsl-py#159]
I need to scan through all the documents in a DocType, while preserving the order in which they were added to it.

I logically turned to the ```scan```
 method, but that does not preserve the order.
The elasticsearch-py ```
scan```
 helper method can take a ```preserve_order``` argument. But I can't figure out how to use it with elasticsearch-dsl-py.

Is it possible?

**Comment by HonzaKral** [comment]
You can do it by specifying params method, anything passed there will be used as a kwargs when calling the underlying method (`client.search` or, in this case,  `helpers.scan`):

    s = Search().params(preserve_order=True)
    for d in s.scan(): print(d)

hope this helps.

**Comment by njoannin** [comment]
I missed that one... Thanks!

**Comment by jaisharma639** [comment]
@HonzaKral what if i want the sorting to happen based on a particular field, is there a way to do it ?
Say the scan method returns 500 documents each having a field with date value stored in it. I want the documents to be returned in ascending order of that date field value.

**Comment by HonzaKral** [comment]
@jaisharma639 regular sorting should work for you then: `Search().sort('my_field').param(preserve_order=True).scan()`

**Comment by jaisharma639** [comment]
Thanks for the quick reply. I tried it out and it worked. It definitely should be included in the documentation http://elasticsearch-py.readthedocs.io/en/master/helpers.html#scan.

Also wondering if preserve_order is mandatory to be used with the sort parameter? What happens if i just use sort alone? I tried it out and it returns documents in random order.

**Comment by HonzaKral** [comment]
Yes, without `preserve_order` it is sorted by `_doc` (see [0]) which is much more optimal. If you want to actually sort the search as reflected in its body then you need to pass in the `preserve_sort` parameter - otherwise sort gets overwritten as the documentation for that parameter suggests.

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html#search-request-scroll

**Comment by zhanwenchen** [comment]
This worked for me. My use case is 1. Output all hits and 2. do a `value_counts` (like that in pandas) of hits on a keyword field (my_doc_type).

```python
from elasticsearch_dsl import A
from my_own_es_dsl_doc_wrapper import MyDocument # MyDocument inherits from elasticsearch_dsl.Document


DOC_TYPE_FIELD_NAME = 'my_doc_type'

agg = A('terms', field=DOC_TYPE_FIELD_NAME)
application_search.aggs.bucket(DOC_TYPE_FIELD_NAME, agg)

response = application_search.execute()

flattened_buckets = {entry['key']: entry['doc_count'] for entry in response.aggs.my_doc_type.buckets}

print('There are {} my_doc_type_1 and {} my_doc_type_2 docs'.format(flattened_buckets['my_doc_type_1'], flattened_buckets['my_doc_type_2']))

print('Here are all the hits:', list(application_search.params(preserve_order=True).scan()))
```

**Comment by zhanwenchen** [comment]
This worked for me (but I'm not sure if this is clumsy or an anti-pattern). My use case is 1. Output all hits and 2. do a `value_counts` (like that in pandas) of hits on a keyword field (my_doc_type).

```python
from elasticsearch_dsl import A
from my_own_es_dsl_doc_wrapper import MyDocument # MyDocument inherits from elasticsearch_dsl.Document

DOC_TYPE_FIELD_NAME = 'my_doc_type'

my_document_search_object = MyDocument.search()

agg = A('terms', field=DOC_TYPE_FIELD_NAME)
my_document_search_object.aggs.bucket(DOC_TYPE_FIELD_NAME, agg)

response = my_document_search_object.execute()

flattened_buckets = {entry['key']: entry['doc_count'] for entry in response.aggs.my_doc_type.buckets}

print('There are {} my_doc_type_1 and {} my_doc_type_2 docs'.format(flattened_buckets['my_doc_type_1'], flattened_buckets['my_doc_type_2']))

print('Here are all the hits:', list(my_document_search_object.params(preserve_order=True).scan()))
```
