### ISSUE TITLE
Many filters in aggs

### ISSUE THREAD

**Issue by zergx1** [elastic/elasticsearch-dsl-py#161]
Hi,

I want to achive something like that

        ...
        "aggs": {
            "countries": {
                "terms": {
                    "field": "country",
                    "size": 0,
                    },
                "aggs": {
                    "extra": {
                        "filter": {
                            "and": [
                                {"term": {"status": "1"}},
                                {"term": {"_type": "type"}},
                                {"term": {"extra_status": "G"}}
                            ]
                        },
                   }
               }
     } ....

I was trying using F() & F() but it didn't work for me.

    a = s.aggs.bucket("countries", "terms", field='country')
    b = a.bucket("extra", Filter(F('term', status="1)) )

Above code works for 1 filter but I don't know how to extend it to include also _type & extra_status filters. Can you help me?

Best regards

**Comment by HonzaKral** [comment]
The code should look like:

    f = F('term', status="1") & F("term", _type="type") & F("term", extra_status="G")
    a = s.aggs.bucket("countries", "terms", field='country')
    b = a.bucket("extra", "filter", f)

This should do the trick (or you can use the `Filter(f)` of course). Note that this will produce a `bool` filter instead of an `and` filter, that is as it should be since `bool` filter will be MUCH more effective here.

Hope this helps

**Comment by zergx1** [comment]
Thank you for response. I also tried to solve this in such way but without success. When I try to run your snippet i get

TypeError: bucket() takes exactly 3 arguments (4 given)

I tried this on 0.4 and 0.5dev versions
Best regards and thank you

**Comment by apandita** [comment]
Hey ,

Can you send a sample script that you are trying?
Can tell you what might be wrong.

On Thu, May 14, 2015 at 3:21 PM, zergx1 <notifications@github.com> wrote:

> Thank you for response. I also tried to solve this in such way but without
> success. When I try to run your snippet i get
>
> TypeError: bucket() takes exactly 3 arguments (4 given)
>
> I tried this on 0.4 and 0.5dev versions
> Best regards and thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch-dsl-py/issues/161#issuecomment-101988510>
> .
>



-- 
Warm Regards!
Amit Pandita
+91-9650308350

**Comment by zergx1** [comment]
My script looks almost the same as example given by HonzaKral

from elasticsearch_dsl import Search, F, A
from utils import get_es_instance

es = get_es_instance() # get es client
s = Search(using=es, index="es")
f = F('term', status="1") & F("term", _type="type") & F("term", extra_status="G")
a = s.aggs.bucket("countries", "terms", field='country')
b = a.bucket("extra", "filter", f)

Best regards and thank you

**Comment by apandita** [comment]
What is the error that you see ?
Script looks alright to me

On Thu, May 14, 2015 at 5:29 PM, zergx1 <notifications@github.com> wrote:

> My script looks almost the same as example given by HonzaKral
>
> from elasticsearch_dsl import Search, F, A
> from utils import get_es_instance
>
> es = get_es_instance() # get es client
> s = Search(using=es, index="es")
> f = F('term', status="1") & F("term", _type="type") & F("term",
> extra_status="G")
> a = s.aggs.bucket("countries", "terms", field='country')
> b = a.bucket("extra", "filter", f)
>
> Best regards and thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch-dsl-py/issues/161#issuecomment-102012602>
> .
>



-- 
Warm Regards!
Amit Pandita
+91-9650308350

**Comment by zergx1** [comment]
Traceback (most recent call last):
      File "script.py", line 8, in <module>
        b = a.bucket("extra", "filter", f)
    TypeError: bucket() takes exactly 3 arguments (4 given)

**Comment by HonzaKral** [comment]
My bad - the `bucket` method was not ready to accept the filter as a positional parameter, should be fixed now.

**Comment by zergx1** [comment]
Great, it's working now. Thanks
