### ISSUE TITLE
Recommended upgrade path

### ISSUE THREAD

**Issue by Yevs** [elastic/elasticsearch-dsl-py#1614]
Just wondering is there a way to do a zero-downtime migration of Elasticserach form v6 to v7 using this `elasticsearch-dsl`? 

The problem I am facing is that I want the existing codebase to support both v6 and v7 versions of the elasticsearch. By having this I can have a backup cluster running v6 while upgrading the main cluster to v7. 

Issue raises that `elasticsearch_dsl` v6 does not seems to work with Elastichsearch v7.0 or v7.1. It raises `mapper_parsing_exception` error when doin `MyDocument.init()`

**Comment by sethmlarson** [comment]
You can use `elasticsearch6-dsl` and `elasticsearch7-dsl` packages together and target different indices.
