### ISSUE TITLE
Feature Request: Pass parameters to FacetedSearch

### ISSUE THREAD

**Issue by MichZipp** [elastic/elasticsearch-dsl-py#1627]
The Search object allows us to pass parameters such as the "request_timeout".
However, we cannot pass parameters to the FacetedSearch. Therefore, large requests will time out quickly.

We could easily integrate this feature by adding the following lines:

```
class FacetedSearch(object):
    ...
    params = None
    ...

   def search(self):
        s = Search(doc_type=self.doc_types, index=self.index, using=self.using).params(**self.params)
        return s.response_class(FacetedResponse)
   ...
```

I'm happy to do the changes and submit a pull request.

**Comment by miguelgrinberg** [comment]
Implemented in #1500, closing.
