### ISSUE TITLE
`script_fields` via DSL rather than raw JSON?

### ISSUE THREAD

**Issue by daviddyball** [elastic/elasticsearch-dsl-py#163]
Hi All,

I'm currently using `script_fields` to return some calculated values as well as the source, but the only way I've found to do it so far is to break the search object down using Search().to_dict(), add in the custom `script_fields` k/v's and then re-create the search object with Search().from_dict(). 

```
....
def add_script_fields(searcher):
    _d = searcher.to_dict()
    _d['script_fields'] = {
        ...
        ...
    }
    searcher.from_dict(_d)
```

The issue with this is that I'm losing the meta-data previously set on the search object (e.g. `obj._doc_type` and `obj._index` are no longer set on the search object). I can manually re-assign the `searcher._index` and `searcher._doc_type` values and it seems to work, but it feels like a workaround rather than a solution.

I've looked at the code for the DSL library, but can't see anything specifically mentioning `script_fields` or it's usage. Is it currently supported in the DSL library?

Thanks,
David

**Comment by daviddyball** [comment]
Just spotted the `update_from_dict()` method, which does what I need. Apologies for the spam.

**Comment by HonzaKral** [comment]
I don't consider this a spam, I think we should have a more direct way of doing this, a separate method to specify script fields. Thanks for bringing it up!
