### ISSUE TITLE
When i connection ES through elasticsearch-dsl raise some error

### ISSUE THREAD

**Issue by fan9704** [elastic/elasticsearch-dsl-py#1640]
when I commit my django code to GitHub 
GitHub Action Raise some Error log

![image](https://user-images.githubusercontent.com/76801598/212733884-a0bd3ef0-0c60-44b9-bc1a-f2a89037f235.png)

[GitHub Action Pipeline log](https://github.com/fan9704/ES2/actions/runs/3932509097/jobs/6725160800)
[My Django Repository Link](https://github.com/fan9704/ES2)

When i was in localhost or connection to my remote Elastic Search Server it didn,t show any wrong message but when i push it to GitHub Action it raise some error messages!!

This is my computer Terminal Message
When i am testing anything is Ok and Pass
![image](https://user-images.githubusercontent.com/76801598/212734420-a32431da-8429-4e27-910e-37b0636def88.png)

Can you find where i was wrong Thanks!!

**Comment by miguelgrinberg** [comment]
Pleaes reopen If you still need help trobleshooting this. The error that you reported does not clearly indicate what is failing. If this is a failure to connect to an Elasticsearch instance, then my guess is that the GitHub actions test environment does not have access to the instance that you have available when you run the tests locally.

**Comment by fan9704** [comment]
Yes @miguelgrinberg you are right because in my pipeline I setup a progress that will auto start a elasticsearch container,but it seems like elasticsearch haven't setup complete then do other progress 

Cause elastcisearch-dsl cannot connect to elasticsearch
