### ISSUE TITLE
Unable to serialize GeoShape

### ISSUE THREAD

**Issue by andreimanu** [elastic/elasticsearch-dsl-py#1644]
So I created a mapping as such
```
shape_mapping = {
    "mappings": {
        "properties": {
            "nombre": {
                "type": "text"
            },
            "direccion": {
                "type": "geo_shape"
            }
        }
    }
}

```
An index as such
`client.indices.create(index='shapemapping', body=shape_mapping)`

A class as such

```
class Poligono(Document):
    nombre = Text()
    direccion = GeoShape()

    class Index:
        name = "shapemapping"

    def save(self, **kwargs):
        self.direccion = GeoShape(type="polygon", coordinates=self.direccion)
        return super().save(**kwargs)
```

Tho when I try to do

```
testpoligono = classes.Poligono()
punto1 = [41.371038600000, -5.916473000000]
punto2 = [41.529508500000, -5.790015600000]
punto3 = [41.558593500000, -5.801502200000]
testpoligono.direccion = [punto1, punto2, punto3, punto1]

response = testpoligono.save()
print(response)
```

I get an error saying

TypeError: Unable to serialize GeoShape(coordinates=...., type='polygon') (type: <class 'elasticsearch_dsl.field.GeoShape'>)

I tried to change the field to a dict, but that makes it not write said field. 

I have the exact same with a GeoPoint instead of a GeoShape and it works perfectly, however I can't get GeoShape to work.

I also tried doing 

`testpoligono.direccion = GeoShape(type="polygon", coordinates=[punto1, punto2, punto3, punto1])` instead of overwriting it in save(), still get the same error

Also if I try to json_dumps it I get 
Object of type GeoShape is not JSON serializable

Thanks in advance!

**Comment by miguelgrinberg** [comment]
The correct way to assign the `GeoShape` field is:

```python
testpoligono.direccion = {"type": "polygon", "coordinates": [[punto1, punto2, punto3, punto1]]}
```

Use a dictionary instead of the `GeoType` class, and also make `coordinates` a list of lists, as required by the polygon type.
