### ISSUE TITLE
How to get list of indexes in a ES instance

### ISSUE THREAD

**Issue by Formartha** [elastic/elasticsearch-dsl-py#1645]
Hello,

What is the correct approach for getting all the indexes in a cluster and transforming the response to json using to_dict() method.

Thanks,
Mor

**Comment by miguelgrinberg** [comment]
There are a few ways to do this. For example, you can use the elasticsearch client:

```
indices = client.indices.get(index='*')
```

The returned value is a dictionary. The keys in this dict are your indices.
