### ISSUE TITLE
How to use the Range or Match classes queries

### ISSUE THREAD

**Issue by oren0e** [elastic/elasticsearch-dsl-py#1646]
I did not find a full example of how to use these (`from elasticsearch_dsl.query import Match, Range`) together with the `Search` object.
In the documentation this is what I've found:
```python
from elasticsearch_dsl.query import MultiMatch, Match

# {"multi_match": {"query": "python django", "fields": ["title", "body"]}}
MultiMatch(query='python django', fields=['title', 'body'])

# {"match": {"title": {"query": "web framework", "type": "phrase"}}}
Match(title={"query": "web framework", "type": "phrase"})
```
First of all, how do I use that with `Search`? What is `title` in here? my own field name? 

Can someone put here a full example from the moment you import Search to the "getting the results" part that's done with `execute()`?

Thanks.

**Comment by miguelgrinberg** [comment]
These classes are lightweight wrappers around Query DSL clauses. You can add them to a `Search()` object through the `query()` method:

```python
s = Search().query(MultiMatch(query='python django', fields=['title', 'body']))
print(s.to_dict())
```

which would print:

```
{'query': {'multi_match': {'query': 'python django', 'fields': ['title', 'body']}}}
```
