### ISSUE TITLE
Raise an error when Elasticsearch returns an error response

### ISSUE THREAD

**Issue by udalrich** [elastic/elasticsearch-dsl-py#1648]
I was attempting to perform a query which was failing because my credentials where invalid.  `search.count()` returned 0, and `search.scan()` returned an empty iterator.

This should raise an error, or provide some way to check if there is an error.

If this already exists, then it needs to be documented better.

**Comment by miguelgrinberg** [comment]
I cannot reproduce this. When I create a connection with an invalid API key and try to run a query I get the following exception thrown:

```
elasticsearch.AuthenticationException: AuthenticationException(401, 'security_exception', 'unable to authenticate with provided credentials and anonymous access is not allowed for this request')
```
