### ISSUE TITLE
Is there a way to copy Query or Filter (DslBase)?

### ISSUE THREAD

**Issue by pcompassion** [elastic/elasticsearch-dsl-py#165]
I'd like to do two similar queries and it would be great to be able to copy & modify 

oh I can just use copy.deepcopy(). fine to use it right?

**Comment by HonzaKral** [comment]
If deepcopy works then great, haven't tested it, you should always be able to do:

  q2 = Q(q1.to_dict())

but deepcopy is probably more performant.
