### ISSUE TITLE
Support status

### ISSUE THREAD

**Issue by honzakral** [elastic/elasticsearch-dsl-py#1652]
What is the status of this library? It still gets >100k downloads per day (0) but hasn't been actively maintained for years. Are there any plans to fix that and dedicate some time to update it?

If not would @elastic be open to moving the repository into my account so I can do some maintenance as I am now starting to use it in production again?

0 - https://pypistats.org/packages/elasticsearch-dsl

**Comment by ezimuel** [comment]
Hi @honzakral  you right, we didn't put too much love in this library :disappointed: but we decided to continue to support this project and we'll allocate time on this. We recognize that is project is still popular and used by many people and we will try to support as much we can.
First goal is to review all the PRs that we have, there are lot of features ready to be merged!
Of course, your expertise on this code base can help a lot, you are more than welcome continuing to contribute to this project.
Thanks for your collaboration and help!

**Comment by brainix** [comment]
I’m updating and maintaining my own private fork. But I’d love Elastic prioritize this library again. This library is brilliant.

**Comment by jgb** [comment]
@ezimuel happy to hear, if possible please consider it a priority to make this library compatible with elasticsearch v8

**Comment by jgb** [comment]
Hello @ezimuel it's been 3 weeks now but nothing has moved so far. Could we start with making the library compatible with ESv8? If we wait much longer, ESv9 might be out ;-)

**Comment by jgb** [comment]
@ezimuel 6 weeks further, and still no update? Is this the type of relationship that the company elasticsearch wants to have with their users?

**Comment by pquentin** [comment]
Hello, https://pypi.org/project/elasticsearch-dsl/8.9.0/ is out, and as the new maintainer I do intend to continue supporting this library going forward. Sorry for the lack of communication since July and thank you for your patience.

**Comment by honzakral** [comment]
Thank you, @pquentin ! Looking forwards to more updates :)
