### ISSUE TITLE
Optimization Doubt

### ISSUE THREAD

**Issue by raviteja1766** [elastic/elasticsearch-dsl-py#1658]
from elasticsearch_dsl import Search
search_obj = Search()

statement 1: search.execute()
statement 2: hit_objs = search[: search.count()]

Are the above 2 statements when executed consecutively, do they hit database twice or only once ?

**Comment by miguelgrinberg** [comment]
The `count()` in the second statement will use the results that were cached by the `execute()` call, so there would a single query out to the database in this case.

But note that `hit_objs` would be a `Search()` instance using the code as given in your example. I think the correct code would be:

```python
response = search.execute()
hit_objs = response[0:search.count()]
```
