### ISSUE TITLE
Blank Q objects should be handled

### ISSUE THREAD

**Issue by mdj2** [elastic/elasticsearch-dsl-py#166]
Consider a case where you want to query by name and/or age. To compose the query, it would be nice to do something like:
```python
q = Q()
if data.get("name"):
    q = q & Q("multi_match"...)
if data.get("age"):
    q = q & Q("range"...)
```

Right now, that will give you a `TypeError: Q() missing 1 required positional argument: 'name_or_query'`.

**Comment by mdj2** [comment]
I think a possible workaround is to use `q = Q("bool")` for a blank Q object.

**Comment by HonzaKral** [comment]
There is a "neutral" `Query` type which is `match_all`, perhaps that would make more sense. I will make it work for `F` and `Q` shortcuts, good idea!

**Comment by cyr0930** [comment]
Doesn't `match_all` work only for & operation?
`Q("bool")` works fine for both & and | for me.
