### ISSUE TITLE
AttrList.__iter__ must return iterator

### ISSUE THREAD

**Issue by kputland** [elastic/elasticsearch-dsl-py#167]
```python
    def __iter__(self):
        return iter(map(_wrap, self._l_))
```

**Comment by HonzaKral** [comment]
`AttrList.__iter__` does indeed return an iterator - it returns an iterative `map` implementation - `itertools.imap` in python 2 and the built-in map in python 3

**Comment by kputland** [comment]
It didn't work for me 
```python
>>> def _wrap(x):
...     return x
... 
>>> class Foo:
...     def __init__(self):
...             self._l_ = ['a','b','c']
...     def __iter__(self):
...             return map(_wrap, self._l_)
... 
>>> f = Foo()
>>> for x in f:
...     print x
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __iter__ returned non-iterator of type 'list'
>>> 
```

however... returning a generator expression

```python
return ( _wrap(x) for x in self._l_)
```

Is a more memory efficient iterator than the iter(map()) and works for me

```python
>>> class Foo:
...     def __init__(self):
...             self._l_ = ['a','b','c']
...     def __iter__(self):
...             return ( _wrap(x) for x in self._l_ )
... 
>>> f = Foo()
>>> for x in f:
...     print x
... 
a
b
c
>>> 
```

**Comment by HonzaKral** [comment]
Are you using the bultin `map`? Then it won't work in python 2. But that is not what this library is using - see https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/utils.py#L4

**Comment by kputland** [comment]
Ah.. I didn't see the import from six.
I was repurposing those two classes into another project where I'm dealing with xml and using xmltodict.
