### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by sla-te** [elastic/elasticsearch-dsl-py#1672]
Thank you for upgrading the lib to support v8.x.

Maybe this is a good time to ask for officially adding async support according to https://elasticsearch-py.readthedocs.io/en/v8.9.0/async.html, as it is clearly a feature, that will be used by a lot of users (and already has quite a history of requests about it).

I found https://github.com/elastic/elasticsearch-dsl-py/pull/1435 which was closed in favor of https://github.com/elastic/elasticsearch-dsl-py/pull/1480, which is apparently already 2 years old.

That all being said, we have been using the following "hack", to achieve async support in the past (using v7.4.1):
```python
import asyncio

from elasticsearch import AsyncElasticsearch
from elasticsearch_dsl import Search

config = {...: ...}
indexname = ...
es = AsyncElasticsearch(**config)


async def do_es_async_work():
    s = Search(index=indexname).filter(...).filter(...)
    r = await s.execute().to_dict()
    return r

print(asyncio.run(do_es_async_work()))
```

On trying it with the newly released version (v.8.9.0), this now sadly throws: 
```
RuntimeWarning: coroutine 'AsyncElasticsearch.search' was never awaited
```

Upon looking at diffs between v7.4.1 and v.8.9.0, I was able to identify the root of the problem at https://github.com/elastic/elasticsearch-dsl-py/blob/3073976e94929a3c39bd87a5753b5d4031ec6725/elasticsearch_dsl/search.py#L710

It seems, that wrapping the response of the call to `es.search` in an object, now rendered this hack to fail, as body would only exist **after** awaiting `es.search,` if `AsyncElasticsearch` is used as connection. - Now the problem coming up with the new structure is, that I do not see a way to create a new "hack" to achieve passing through the async call through to `AsyncElasticsearch` directly, without starting to use e.g. `asyncio.run_in_executor`, which would cause a terrible overhead, as every async call would open a new thread, which kind of destroys the advantage of using async in this scenario if I understand this correctly.

**Comment by pquentin** [comment]
Thank you for trying the new version and thank you for the heads up about async. I'm not yet ready to work on full async support, but what do you think about this totally unsupported hack?

```python
import asyncio

from elasticsearch import AsyncElasticsearch
from elasticsearch_dsl import Search, connections


config = {...: ...}
indexname = ...
es = AsyncElasticsearch(**config)


class AsyncSearch(Search):
    async def execute_async(self, ignore_cache=False):
        if ignore_cache or not hasattr(self, "_response"):
            es = connections.get_connection(self._using)

            async_response = await es.search(
                index=self._index, body=self.to_dict(), **self._params
            )
            self._response = self._response_class(self, async_response)
        return self._response


async def do_es_async_work():
    s = AsyncSearch(using=es, index=indexname)
    r = (await s.execute_async()).to_dict()
    return r


print(asyncio.run(do_es_async_work()))
```

**Comment by pquentin** [comment]
Interesting. Can you please show me how you are using this today, with async and sync examples?

**Comment by pquentin** [comment]
I have been thinking about this quite a lot because it could help with the design of the async support and using `body` when adding support for Elasticsearch 8 was not an obvious decision, and I'm considering returning the full `ObjectApiResponse` object that behaves like a dict in the next version.

That said, another totally unsupported hack with the current version is:


```python3
import asyncio

from elasticsearch import AsyncElasticsearch, Elasticsearch
from elasticsearch_dsl import Search, connections


config = {...: ...}
indexname = ...
async_es = AsyncElasticsearch(**config)
es = Elasticsearch(**config)


class AsyncSearch(Search):
    async def execute(self, ignore_cache=False):
        if ignore_cache or not hasattr(self, "_response"):
            es = connections.get_connection(self._using)

            if isinstance(es, AsyncElasticsearch):
                response = await es.search(
                    index=self._index, body=self.to_dict(), **self._params
                )
            else:
                response = es.search(
                    index=self._index, body=self.to_dict(), **self._params
                )
            self._response = self._response_class(self, response.body)
        return self._response


async def do_work(using):
    s = AsyncSearch(using=using, index=indexname)
    r = (await s.execute()).to_dict()
    print(r["hits"]["total"])


# async
asyncio.run(do_work(using=async_es))

# sync
def run_secretly_sync_async_fn(async_fn, *args, **kwargs):
    coro = async_fn(*args, **kwargs)
    try:
        coro.send(None)
    except StopIteration as exc:
        return exc.value
    else:
        raise RuntimeError("you lied, this async function is not secretly synchronous")


run_secretly_sync_async_fn(do_work, using=es)
```

It uses two tricks:

- one to await or not depending on the Elasticsearch client instance,
- one to run async functions like `do_work` or `execute` in a sync context, taking advantage of the fact that they are "secretly synchronous" ([source](https://github.com/python-trio/hip/issues/1#issuecomment-322028457))

**Comment by miguelgrinberg** [comment]
Also #1355 #1624

**Comment by miguelgrinberg** [comment]
Done in #1714, will be part of the 8.13 release.
