### ISSUE TITLE
How to add an analyser in AttrList string?

### ISSUE THREAD

**Issue by CarMoreno** [elastic/elasticsearch-dsl-py#1675]
Hi,
Thank you for this great library. I am wondering if it is possible to add a custom analyzer in an `AttrList` field. Seems Elasticsearch [supports that](https://stackoverflow.com/questions/43530610/how-to-do-a-mapping-of-array-of-strings-in-elasticsearch). 

So I am looking for something like:

```python
class MyDocument(Document):
    my_list = AttrList([], analyzer=super_analyzer)
```

**Comment by pquentin** [comment]
Thank you for your interest. As a new maintainer, I'm not sure I understand why you're using an `AttrList` here. Would something like this suit your needs?

```python3
import json

from elasticsearch import Elasticsearch
from elasticsearch_dsl import Document, connections, field

connections.create_connection(hosts="...")


class MyDocument(Document):
    my_list = field.Text(multi=True, analyzer="snowball")

    class Index:
        name = "my-doc-index"


my_doc = MyDocument(my_list=["I learned to sing.", "something else"])
my_doc.save(refresh=True)
print(my_doc.search().query("match", my_list="I learn, singing!").execute())
# <Response: [MyDocument(index='my-doc-index', id='hCwarIoBGg0tldGw8iqw')]>
```

**Comment by CarMoreno** [comment]
Hi, thank you for the reply.
Your approach works for me, I modified it a bit though:

```python
class MyDocument(Document):
    my_list = Keyword(fields={
        'my_list_english': Text(analyzer='my_english_analyzer')
    })
```
So, I have two different versions of `my_list` (`keyword` and `text`) and I can analyze them separately. I am using ES v7.5
