### ISSUE TITLE
How to set up persisting documents with indices that apply ILM policy.

### ISSUE THREAD

**Issue by k0286** [elastic/elasticsearch-dsl-py#1698]
Hi, 

I read the documents and source code, but I still don't know how to set up persisting documents with indices, which is applied to the ILM policy.
The index with ILM policy means that It will automate rollover to new index with an increment index names.

According to ES's tutorial, there are two aliases are needed: the alias point to the latest index for creating documents and the alias point to all the indices for querying document.

I'm not sure if is possible with `elasticsearch-dsl` or not.

**Comment by pquentin** [comment]
Hello! The DSL client does not have any helpers from ILM policies. You will have to use the [ILM APIs](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management-api.html) directly [using the Python Elasticsearch client](https://elasticsearch-py.readthedocs.io/en/v8.12.0/api/index-lifecycle-management.html). Thanks.
