### ISSUE TITLE
how to set doc_type dynamically?

### ISSUE THREAD

**Issue by knoguchi** [elastic/elasticsearch-dsl-py#170]
I have model classes like this.   I would like `save()` to save PostModel object to `posts` doc type, and TagModel to `tags` doc type.   Is there any way to do this?

```
class BaseModel(DocType):
    created_at = Date()
    updated_at = Date()

class PostModel(BaseModel):
    title = String()

class TagModel(BaseModel):
    name = String()
```

**Comment by HonzaKral** [comment]
This should happen automatically - each `DocType` should be saved to it's document type in elasticsearch.

If you need to override the default name `tag_model` and `post_model` just define the doc type name:

    class PostModel(BaseModel):
        ....
        class Meta:
            doc_type = 'posts'

If this is not what you need can you please add some more details? Thanks!

**Comment by HonzaKral** [comment]
Closing this since there has been no reaction. Feel free to reopen if the previous comment didn't answer your question.

**Comment by OskarPersson** [comment]
Is it possible to set the doc_type name at creation of a document? For example, let's say I want the `doc_type` for a `PostModel` document to not be `posts` for some document.

Something like `PostModel(name="foo", _doc_type=other")`

**Comment by HonzaKral** [comment]
No, it is not @OskarPersson. Could you please share what is the use case for such functionality? Since types are going away in `6.0` anyway I am hesitant to implement anything around that. Thanks!

**Comment by OskarPersson** [comment]
I have a UI where I want the user to be able to write the type. Maybe a simple field is better suited for that?

**Comment by HonzaKral** [comment]
Yes, I would say a field, and maybe some associated methods, is a better way to handle this. Thanks!
