### ISSUE TITLE
How to add a mapping on the Document class

### ISSUE THREAD

**Issue by pulse-mind** [elastic/elasticsearch-dsl-py#1700]
I have a Document class like that : 
```
@registry.register_document
class MyDataDocument(Document):    
    data_json = fields.ObjectField()
    
    def prepare_data_json(self, instance):
        return instance.data_json    
        
    class Index:
        name = "mydata"
        settings = {"number_of_shards": 1, "number_of_replicas": 0}



    class Django:
        model = MyData
        fields = [
            "data_name",            
        ]

```
But for some reason in the JSON I have data_json.form.content = '2024-24'  but elastic defined this field as Date. So I get an exception during the indexing. 
I wanted to define a specific mapping for this and my idea was to add a class Meta into my MyDataDocument, something like this : 
```
class Meta:
        mapping = {
            "properties": {
                "data_json": {
                    "properties": {
                        "form": {
                            "properties": {
                                "content": {
                                      "type": "text",
                                       "fields": {
                                              "keyword": {
                                                  "type": "keyword",
                                                  "ignore_above": 256
                                               }                                    
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
```
But it does not work like this. Is it possible to define it in the Document Class ?

**Comment by pquentin** [comment]
Hello! If you're using Django Elasticsearch DSL, have you considered modeling your field as a [Django date](https://docs.djangoproject.com/en/5.0/ref/models/fields/#datefield)? https://django-elasticsearch-dsl.readthedocs.io/en/latest/fields.html#field-mapping mentions that the Django Elasticsearch DSL can map from Django fields to Elasticsearch mappings, and allows you to overwrite the mappings too. This seems appropriate for your goals.

In any case, as mentioned in #1699 please report this to the Django Elasticsearch DSL project instead. I'm happy to help further if you have an issue that is specific elasticsearch-dsl-py, but that does not seem to be the case here.
