### ISSUE TITLE
[Question] How to make a search on the "raw" (not_analyzed) field?

### ISSUE THREAD

**Issue by njoannin** [elastic/elasticsearch-dsl-py#172]
I've been scratching my head over this one for a couple of days now... It is probably simple and obvious, but I'm failing to see it :(

If a field is created as such:

```
class User(DocType):
    name = String(fields={"raw": String(index="not_analyzed")
```

I can do the following:

```
s = User.search().query("match", name="my name").execute()
```

Which will search the analyzed field, finding anything with "my" or "name" in it...

But how do I search the ```raw``` field to only find "my name"?

**Comment by HonzaKral** [comment]
`Search().filter('terms', name__raw='my name')` should work

**Comment by njoannin** [comment]
@HonzaKral  Thank you very much!
