### ISSUE TITLE
Batch indexing and index buffers

### ISSUE THREAD

**Issue by jmizgajski** [elastic/elasticsearch-dsl-py#173]
Hi there,

Some background:

- I was using elasticutils in a high performance environment and noticed problems with high indexing loads - each document save would cause a separate indexing request which would slow down the cluster
- I've built an extension to elasticutils to map django models to elasticsearch documents, and enable batch indexing for index recreation and redis buffers + celery workers to leverage batch indexing requests from day to day operations (if you get 100 documents/s there is huge gain by buffering 1s worth of requests - without practical slowdown in document availability). It is pretty much plug and play.
- elasticutils is dead and I hope to switch to elasticsearch-dsl-py to avoid supporting abandon-ware and to keep up with new releases of Elasticsearch

Questions:

- is such a feature (batch creation, buffering) on the roadmap for elasticsearch-dsl-py?
- would you like me to add it to the official repo or should I rather start a new repo that uses elasticsearch-py?

**Comment by HonzaKral** [comment]
Hi, thanks for the questions.

Currently there is a simple way to perform batch indexing operation from `DocType` objects:

    from elasticsearch.helper import streaming_bulk
    from elasticsearch_dsl.connections import connections

    for response in streaming_bulk(connections.get_connection(), (d.to_dict(True) for d in MY_DOCS)):
        pass

this will use the `_bulk` API of elasticsearch (via the helpers in elasticsearch-py). We can definitely make this easier by, for example, providing a class method that would wrap this in a better API or introduce a set of elasticsearch-dsl specific helpers.

What do you think?

**Comment by jmizgajski** [comment]
Hi Honza,

There were similar provisions in elasticutils that I used. However this does not solve the buffer problem for the end developer - they would have to implement it themselves. Also I used map-reduce on celery to distribute ingestion (the creation of document from external sources such as MySQL) on multiple workers.

From the end developer perspective I was thinking something like .save_async() that would serialize to json/pickle to redis and then be picked up in batch and inserted using bulk streaming in a celery worker + a neat way to plug a django model to a document and have all models indexed in map reduce. I also had a neat way to plug post_save signals to documents so they would reindex themselves on model changes.

To be honest this looks like 2 APIs:
 - one for buffering documents/indexing large collections using a cluster of workers and a MQ.
- one for nicely integrating with django models and existing django applications

**Comment by HonzaKral** [comment]
Ah, I see what you mean. I don't think this is in scope of this library.

It's use case is fairly limited (most people want the documents to save immediately or have explicit batches to index). And has requirements that would tie us down a lot (rq/celery, ...).

What I want to do instead, for the django integration, is make use of the proposed tasks API that will be in django to allow people to depend on something async without having to chose celery or rq (PR here: https://github.com/django/django/pull/4763). Once that's in we can do the batching as next step.

Until then I am afraid I have to recommend you to create a separate library/gist for this feature. If you do end up implementing it publicly, please leave a link here for other people to follow.

Thanks!

**Comment by jmizgajski** [comment]
Hi Honza,

While I would disagree this is an uncommon use case (I'd say most enterprise clients that buy support and us python would love it if implemented correctly) I accept your argument. 

I will probably implement it on a separate repo then. 

Alternatively we could try to do it the celery way first and then provide pluggable backends if there is demand. 

I would see this functionality as a mixin class that should not clutter the library.

**Comment by HonzaKral** [comment]
Great, thank you!

I will close this ticket for now, feel free to add the link to it, it would be appreciated.

**Comment by csinchok** [comment]
@jmizgajski We've been working on a small library to connect elasticsearch-dsl-py with Django, if you're interested in maybe taking a look at that: https://github.com/theonion/djes.

(sorry for hijacking the thread)

**Comment by jmizgajski** [comment]
no worries, It's good that you mentioned it. Maybe we can collaborate.

**Comment by dchaplinsky** [comment]
@HonzaKral, thanks for that snippet. A helper would be good.

Just small correction, in your snippet you should use ```from elasticsearch.helpers import streaming_bulk```  not ```from elasticsearch.helper import streaming_bulk```
