### ISSUE TITLE
Need example: And Filter

### ISSUE THREAD

**Issue by Charlemagne3** [elastic/elasticsearch-dsl-py#175]
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-and-filter.html

I have been trying to figure out how to compose an "And Filter" using this library, but I can't find anything in the documentation or examples of how this would be done.  

The filter I am trying to compose is a bit complicated, and part of it involves a bool filter with nested and filters.  I am trying to start with the innermost filter first, the "and filter", but there really isn't much to go off of here, and I am not entirely certain that it is supported.  

If my terminology isn't clear, this is the final structure of the piece I am building: 

```
"filter": {
	"bool": {
		"must": [
			{
				"nested": {
					"filter": {
						"and": [
							{
								"term": {
									"profile.questionid": "1"
								}
							}, 
							{
								"terms": {
									"execution": "or", 
									"profile.answer": ["1", "2"]
								}
							}
						]
					}, 
					"path": "profile"
				}
			}, 
			{
				"nested": {
					"filter": {
						"and": [
							{
								"term": {
									"profile.questionid": "2"
								}
							}, 
							{
								"terms": {
									"execution": "or", 
									"profile.answer": ["1"]
								}
							}
						]
					}, 
					"path": "profile"
				}
			}
		]
	}
}
```

**Comment by HonzaKral** [comment]
Hi,

the most direct way is to create the objects manually where you have full control:


    Bool(
      must=[
        Nested(
          filter=And(
            filters=[
              Term(profile__questionid='1'),
              Terms(execution='or', profile__answer=['1', '2'])
            ]
          ),
          path='profile'
        ),
        Nested(
          filter=And(
            filters=[
              Term(profile__questionid='2'),
              Terms(execution='or', profile__answer=['1'])
            ]
          ),
          path='profile')
      ]
    )

The easier way, however is to just let the DSL help with the composition:

    f = F('nested', filter=F('term', ...) & F('terms', ...), path='profile')
    f &= F('nested', filter=..., path=...)

This will result in `bool` queries being used even inside of the nested instead of `and`. That is by design (and you'd have to explicitly create the `and` filters if you wish those lke in the previous example) since `bool` filter is more efficient with `term`/`terms` filters (see https://www.elastic.co/blog/all-about-elasticsearch-filter-bitsets).

Hope this helps.

**Comment by Charlemagne3** [comment]
Thanks, that was very helpful in seeing how the DSL works.

**Comment by HonzaKral** [comment]
Great.

Also, if you want to know how I came to that solution I just (well, after I fixed two bugs - https://github.com/elastic/elasticsearch-dsl-py/commit/ab99a82906baf3e81bcf793e2a9440ede4bd2a7a and https://github.com/elastic/elasticsearch-dsl-py/commit/d677bd749b03452ae30d64a42618accac7806933) did:

    print(repr(F(YOUR_DICT_HERE)))
