### ISSUE TITLE
Subclassing DocTypes doesn't work properly

### ISSUE THREAD

**Issue by hakanw** [elastic/elasticsearch-dsl-py#178]
I expected this to work, but it seems not to:

```python
class MyDoc(DocType):
  class Meta:
    index='hello'

class MyDocTest(MyDoc):
  class Meta:
    index='test'
```

`MyDocTest` still hits the 'hello' index when you use it.

**Comment by HonzaKral** [comment]
I am sorry I cannot replicate this, I wrote a test to verify that this works, could you please check the test (https://github.com/elastic/elasticsearch-dsl-py/commit/508354d2d2030ae4225ead945a4d6e6850b65f8b) to see if I am doing something different?

Thanks!
