### ISSUE TITLE
 Inconsistent handling of empty lists in Document partial updates.

### ISSUE THREAD

**Issue by albertisfu** [elastic/elasticsearch-dsl-py#1819]
Hi! At work we are currently developing an API that relies on Elasticsearch responses. Within our document mapping, we have defined multi-value fields, which we aim to represent as empty arrays (**`[]`**) in the API response when these fields are empty. When initially indexing the document, it successfully store empty lists into ES as **`[]`** by passing these fields with **`skip_empty=False`**.

However, we are encountering an issue with partial updates. After updating a field to become empty, it is stored as **`None`** instead of **`[]`**, even though we are passing the field values as **`[]`**. 

The root cause appears to be within the current implementation of the **`Document.update`** method for partial document updates. This method prepares data for Elasticsearch by invoking the [**`to_dict`**](https://github.com/elastic/elasticsearch-dsl-py/blob/3e880fd4c18b61874884b3e9a4040204f8a9f507/elasticsearch_dsl/_sync/document.py#L296) method, which, by default, ignores empty fields. Consequently, empty lists are treated as **`None`** and updated accordingly.

**Proposed Fix:**
To address this issue, I propose modifying the **`update`** method to accept **`skip_empty=False`** and passing this parameter to the **`to_dict`** method. This adjustment will ensure that empty lists are included in the update payload as empty lists instead of being interpreted as **`None`**.

**Steps to Reproduce:**

1. Save a document with multi-value fields.
2. Perform a partial update using the **`Document.update`** method, passing multi-value fields as empty lists **`[]`**.
3. Verify that the empty lists are updated as **`None`** instead of remaining as empty lists.

I am willing to contribute to fixing this issue if you believe it should be fixed in this way.

**Comment by miguelgrinberg** [comment]
I was able to reproduce this easily. I think update() should also use `to_dict(skip_empty=False)`, I don't see why you would send an empty value to update but would like it to be skipped. Working on a fix.

**Comment by albertisfu** [comment]
You're right; there is no reason to pass `skip_empty=True` on an update. The default option, `False`, is correct.

Thank you!
