### ISSUE TITLE
Getting DocType from search result

### ISSUE THREAD

**Issue by k4nar** [elastic/elasticsearch-dsl-py#183]
When doing a multi-type search, is there any way to retrieve an instance of the DocType, or at least the class, from a `Result` object? There is `Result.meta.doc_type`, but this is a string.

**Comment by HonzaKral** [comment]
It depends on how you are creating the `Search` object. Ideally you'd use a `DocType.search` or `Index.search` methods, that way all the results will return wrapped in the appropriate `DocType` class.

**Comment by k4nar** [comment]
By "multi-type search" I was meaning that I'm doing a search cross types and indices.

**Comment by HonzaKral** [comment]
Yes, but how are you specifying it? You should do:

    s  = Search(doc_type=[MyDoc, MyOtherDoc, SomeThirdDocType, ...], index=['index1', 'index2'])

And then all the results will be correctly wrapped in `MyDoc` etc.

**Comment by k4nar** [comment]
Oh ok, that's great! Didn't thought of that, thanks.
