### ISSUE TITLE
Partial update of a field

### ISSUE THREAD

**Issue by andreif** [elastic/elasticsearch-dsl-py#184]
Hi, I am currently doing the following and wonder if it's the only way to update only one field in an indexed document:

```py
class MyDocType(DocType):
    def update(self, **fields):
        m = self._doc_type
        return es.update(index=m.index, doc_type=m.name, 
                         id=self._id, body={'doc': fields})

class MyDoc(MyDocType, DocType):
    field_a = String()
    field_b = Integer()

# ...

doc.update(field_a=new_value)
```

Is there a better way? Thanks!

**Comment by HonzaKral** [comment]
Hi, no, currently there is no better way.

btw for this to work consistently with the rest of the library you should also set the fields on the object locally and increment it's version according to what you got back from the `es.update` - https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/document.py#L224-L227

hope this helps

**Comment by andreif** [comment]
@HonzaKral Awesome, thanks for so quick reply!

**Comment by HonzaKral** [comment]
Actually there are a bit more edge cases where this gets more complex (`_parent`, `_routing`, ...) so I will create a generic `update()` method on the `DocType`. Stay tuned

**Comment by andreif** [comment]
Ah, nice! Thanks again!

**Comment by andreif** [comment]
@HonzaKral Do you think the following would be sufficient for some simple cases:

```py
    def update(self, **fields):
        m = self._doc_type
        meta = es.update(index=m.index, doc_type=m.name, id=self._id,
                         body={'doc': fields})
        if self.meta.version < meta.get('_version', 0):
            for k in META_FIELDS:
                if '_' + k in meta:
                    setattr(self.meta, k, meta['_' + k])
            for k, v in fields.items():
                if hasattr(self, k):
                    setattr(self, k, v)
```

**Comment by HonzaKral** [comment]
You really shouldn't need the if there (`if self.meta.version...`) and also not the `if hasattr(self, k)` because that would prevent this method from adding new fields.

**Comment by andreif** [comment]
Ah, I see. Was trying to get prepared for unexpected result, but it seems wrong to do it there...

**Comment by HonzaKral** [comment]
@andreif thanks for the inspiration, you can now see the `update` method in https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/document.py#L205-L226

**Comment by andreif** [comment]
Wow, things move really fast here! Great job! 

Any plans for the next release? :wink:

**Comment by andreif** [comment]
Hm, just tried it but got `TypeError: update() got an unexpected keyword argument 'score'`.

I have updated the if statement with `k not in ['index', 'score']` locally and it seems to work, but there may be more edges.

**Comment by andreif** [comment]
Well, I've just opened #185 but did not expect the CLA, so I'm closing it. 
It's more efficient if you change it yourself :smile:

**Comment by andreif** [comment]
:+1:
