### ISSUE TITLE
Enable Direct Access to `ConstantKeyword` from `elasticsearch_dsl `Module

### ISSUE THREAD

**Issue by alirezaazadi** [elastic/elasticsearch-dsl-py#1842]
It has been requested for the `ConstantKeyword` support in this issue: [Support for constant_keyword #1373](https://github.com/elastic/elasticsearch-dsl-py/issues/1373)

The field has been added, but it's only available through this path: `﻿from elasticsearch_dsl.field import ConstantKeyword`.
I wonder whether it's possible to make it accessible through ﻿`from elasticsearch_dsl import ConstantKeyword` like the rest of the fields? If the answer is positive, I would be happy to create a PR and apply this small change :)

**Comment by miguelgrinberg** [comment]
Yes, this makes sense, let's do it.
