### ISSUE TITLE
Fix version specifier syntax in dependency string

### ISSUE THREAD

**Issue by diracleo** [elastic/elasticsearch-dsl-py#1848]
According to https://github.com/pypa/pip/issues/12063, pip version 24.1 enforces deprecation of the syntax used in specifying dependency, described on https://pypi.org/project/elasticsearch-dsl/ when using previous versions of elasticsearch:

> Compatibility
> The library is compatible with all Elasticsearch versions since 2.x but you have to use a matching major version:
> 
> For Elasticsearch 8.0 and later, use the major version 8 (8.x.y) of the library.
> 
> For Elasticsearch 7.0 and later, use the major version 7 (7.x.y) of the library.
> 
> For Elasticsearch 6.0 and later, use the major version 6 (6.x.y) of the library.
> 
> For Elasticsearch 5.0 and later, use the major version 5 (5.x.y) of the library.
> 
> For Elasticsearch 2.0 and later, use the major version 2 (2.x.y) of the library.
> 
> The recommended way to set your requirements in your setup.py or requirements.txt is:
> 
> # Elasticsearch 8.x
> elasticsearch-dsl>=8.0.0,<9.0.0
> 
> # Elasticsearch 7.x
> elasticsearch-dsl>=7.0.0,<8.0.0
> 
> # Elasticsearch 6.x
> elasticsearch-dsl>=6.0.0,<7.0.0
> 
> # Elasticsearch 5.x
> elasticsearch-dsl>=5.0.0,<6.0.0
> 
> # Elasticsearch 2.x
> elasticsearch-dsl>=2.0.0,<3.0.0

The impact is that when using pip 24.1, installation of this library fails using a requirements.txt or setup.py that uses the deprecated version specifier described in the instructions.

**Comment by miguelgrinberg** [comment]
I don't see any issues installing this package with pip 24.1. What is it specifically that needs to be updated?

**Comment by diracleo** [comment]
The issue occurs when specifying compatibility for previous version of elasticsearch in requirements.txt or setup.py. I updated the quoted portion of this issue's description to indicate that

**Comment by miguelgrinberg** [comment]
I'm sorry but I need more details. Can you please show me an actual failure instead of quoting our own docs? I don't see what's incompatible.

This installs just fine:

```
elasticsearch-dsl>=8.0.0,<9.0.0
```

**Comment by diracleo** [comment]
Here's the initial warning:

```
DEPRECATION: django-elasticsearch-dsl 7.2.2 has a non-standard dependency specifier elasticsearch-dsl>=7.2.0<8.0.0. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of django-elasticsearch-dsl or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
```

Here's the actual error:

```
pip._vendor.packaging.requirements.InvalidRequirement: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    elasticsearch-dsl (>=7.2.0<8.0.0)
                      ~~~~~~~~^
```

**Comment by miguelgrinberg** [comment]
@diracleo you need to pass this on to the `django-elasticsearch-dsl` project. They have this problem, not this package.

**Comment by pquentin** [comment]
Closing as it's not an elasticsearch-dsl-py issue. Thanks!
