### ISSUE TITLE
Is there any way to dynamiclly construct multi aggregations?

### ISSUE THREAD

**Issue by kamelzcs** [elastic/elasticsearch-dsl-py#188]
I want to construct a top-level multi aggregation query as below:

```
{
  "aggs": {
    "per_country": {
      "terms": {
        "field": "country_url.untouched"
      }
    },
    "per_name": {
      "terms": {
        "field": "name.untouched"
      }
    }
  }
}
```
----

I want to construct them dynamically, as the aggregation may have more kinds.

    field_name_tuple = (('country_url.untouched', 'per_country), ('name.untouched', 'per_name'))

```
    s = Search().aggs
    for field, name in field_name_tuple:
      s = s.metric(name, 'terms', field=field)

```

With no luck `AttributeError: 'Search' object has no attribute 'metric'`

**Comment by HonzaKral** [comment]
Hi, thanks for the report, this is indeed a bug where `metric` on top level `aggs` object doesn't return properly for chaining.

In the menatime you can work around it by not assigning back to `s`:

**Comment by kamelzcs** [comment]
Does it mean there is no need to do `s= s.aggs.bucket(name, 'terms', field=field)` in order to construct a top-level multi aggregation?

Just need to use the below several times, then it is auto glued?

```
for field, name in field_name_tuple:
    s.aggs.bucket(name, 'terms', field=field)
```

**Comment by HonzaKral** [comment]
yes, absolutely.

This is an artifact of how `.aggs` and its chaining is implemented - it is unfortunately inconsistent with the other methods.

**Comment by kamelzcs** [comment]
It is kind of counterintuitive in my view. :(
Thanks for your info and great DSL anyway. :+1: 

The chain way is more intuitive in my view.
