### ISSUE TITLE
[QUESTION] Querying a list of fields with wildcards?

### ISSUE THREAD

**Issue by njoannin** [elastic/elasticsearch-dsl-py#190]
Hello,

I can't figure out how to search a list of specific fields with a wildcard query, e.g.

```
q = Q(("wildcard", query=term.lower(), fields=["field1", "field2", "field3"])
```

How should I go about for this?

**Comment by HonzaKral** [comment]
Hi,

unfortunately the `wildcard` query doesn't allow search across multiple fields. Possible solution is to either use a different query that does allow that (`multi_match`, `query_string`, ...) or use a `bool` query combining the queries for each field:

    q = Q("wildcard", field1=term.lower()) |  Q("wildcard", field2=term.lower()) |  Q("wildcard", field3=term.lower())

Another alternative is to use Copy to Field mechanism (https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-core-types.html#copy-to) to copy values (at index-time) from all the fields to another field that you would then use for this query.

Hope this helps.

**Comment by njoannin** [comment]
@HonzaKral Thanks for the quick reply.

Indeed, in my searches for an answer to the question, I kind of figured that it wasn't possible.
But I hadn't found the option of using the bool query to combine them all.
I'll probably go that way then!

Cheers!
