### ISSUE TITLE
Terms query errors when passing the boost parameter

### ISSUE THREAD

**Issue by Thijsvandepoll** [elastic/elasticsearch-dsl-py#1905]
When I upgraded to the latest version of the Elasticsearch-DSL library, I found a bug that you cannot pass the boost parameter anymore, because it tries to parse everything as a list. This is an example that fails:

```
query.Terms(title=["Something"], boost=2)
```

Hope the problem is clear.

**Comment by miguelgrinberg** [comment]
Thanks, yes, this has been reported already in https://github.com/elastic/elasticsearch-dsl-py/pull/1904. We will publish a fix soon.
