### ISSUE TITLE
Document.get() documentation is misleading - not found does not return None

### ISSUE THREAD

**Issue by lunalucadou** [elastic/elasticsearch-dsl-py#1908]
The [documentation for Document.get()](https://elasticsearch-dsl.readthedocs.io/en/latest/api.html#elasticsearch_dsl.Document.get) says the return type is `Optional[Self]`, and [the code](https://github.com/elastic/elasticsearch-dsl-py/blob/main/elasticsearch_dsl/_sync/document.py#L125) reads like the assumption is a document not being found can be handled without catching exceptions:

```python
        if not doc.get("found", False):
            return None
```

However, when a document is not found, rather than return None, an `elasticsearch.NotFoundError` exception is raised, necessitating the use of an exception handler in my code:

```python
        try:
            return FooDoc.get(id=params.id, index='foo-index')
        except NotFoundError:
            return None
```

It would be nice if `Document.get()` did return None if not found, but if that's not possible, the documentation should reflect the actual behavior.

**Comment by miguelgrinberg** [comment]
Thanks for the report. The type hint is incorrect here, the `get()` method is supposed to raise an exception when the item is not found and it had worked in that way for a long time, at least as far back as the 7.x releases. The if statement that returns `None` in this method is never going to be true, so we'll remove that as well.

**Comment by miguelgrinberg** [comment]
The type hint is actually accurate. I missed that the Elasticsearch client can be configured to ignore 404 errors:

```python
client = client.options(ignore_status=404)
```

And then when using a client configured in this way the `get()` method will return `None` for items that are not found.
