### ISSUE TITLE
How to update nested docs ?

### ISSUE THREAD

**Issue by parthaaptuz** [elastic/elasticsearch-dsl-py#191]
Hi, 

Let say, 

class Post(DocType):
    title = String()
    created_at = Date()
    published = Boolean()
    category = String(
        analyzer=html_strip,
        fields={'raw': String(index='not_analyzed')}
    )

    comments = Nested(
        properties={
            'author': String(fields={'raw': String(index='not_analyzed')}),
            'content': String(analyzer='snowball'),
            'created_at': Date()
        }
    )

I would like to update the nested comments of specified comment. How to do this

**Comment by HonzaKral** [comment]
Hmm, looks like I typed my response and didn't hit send or my response disappeared. The answer is that with nested all changes need to be done on the master document (`Post` in this case) so:

    post = Post.get(id=42)
    # modify post.comments in any way
    post.comments.append(...)
    # save the changes
    post.save()
