### ISSUE TITLE
Terms lookup feature no longer supported due to recent release

### ISSUE THREAD

**Issue by bptarpley** [elastic/elasticsearch-dsl-py#1920]
A recent release appears to have broken the ability to perform a "terms lookup" query which is a special subset of terms query which allows you to specify the index, id, and field so you can limit terms to those found in a specific document in another index:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html#query-dsl-terms-lookup

I used to be able to create a "terms lookup" query like so:

```
Q('terms', **{'_id': {
    'index': 'my-other-index',
    'id': 'my-document-id',
    'path': 'my-field'
}})
```

Now, however, the query generated flattens the dictionary into a list of keys, so that what actually gets built is this:

```
"terms": {
    "_id": [
        "index",
        "id",
        "path"
    ]
}
```

This seems to be an unintended side-effect of a recent release. Please advise.

**Comment by bptarpley** [comment]
I can confirm that reverting back to version 8.15.0 allows the query to be generated appropriately, i.e.:

```
"terms": {
    "_id": {
        "index": "my-other-index",
        "id": "my-document-id",
        "path": "my-field"
    }
}
```

**Comment by miguelgrinberg** [comment]
Yes, this is another regression introduced by #1887. There are lots of variations that were not considered. I have addressed a couple already, but missed the passing of a dict as an argument.
