### ISSUE TITLE
Support for `stored_fields` queries

### ISSUE THREAD

**Issue by seagrine** [elastic/elasticsearch-dsl-py#1934]
When I tried to construct a`stored_fields` query I found that this library does not have an API for it. Are there any workarounds available? Are there plans to add support for `stored_fields` queries?

**Comment by seagrine** [comment]
Actually maybe I can use `SearchBase.extra({"stored_fields": [...]})`

**Comment by miguelgrinberg** [comment]
That's correct, you can use `extra()` to add anything you need to the search request.
