### ISSUE TITLE
Question about how to insert object type 

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#194]
Hello,

I would like to construct a estructure similar to this:

dn:{ 
   dc : ["afda" ,"asd"]
   ou : ["a","B"]
}

for example. I was thinking about to use object type in elasticsearch and in the definition of my class in use define dn like this:

from elasticsearch_dsl import DocType, String, Date,Object

class customer(DocType):
name = String()
 dn = Object(
        properties={
            'dc': String(),
            'ou': String()
        }
    )

But after I want to use the methods of append  like:

c= customer()
c.dn.dc.append("my new element in the array")

But I am unable to do it and in:

c.name.append("a")

yes.

Could you give me a solution?

Thanks in advance.

Juan

**Comment by HonzaKral** [comment]
If you want to be able to just call `append` you need to specify the field as `multi=True`:

    class Customer(DocType):
        address = Object(properties={'city': String(multi=True)})
    
    c = Customer()
    c.address.city.append('new york')

Hope this helps.

**Comment by juandasgandaras** [comment]
Ok ,thanks  this is exactly I was looking for

**Comment by HonzaKral** [comment]
Great, closing the issue then.
