### ISSUE TITLE
Error when I do many DocType save

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#195]
Hi,

Nowadays I have a class defined like:

class customer(DocType): 
    updated_at = Date()
    oid = Sring()

    class Meta:
        index = 'carallada'
        id = ""

    def save(self, ** kwargs):
        self.meta.id = self.oid
        self.updated_at = datetime.now()
        return super(customer,self).save(** kwargs)

But now if i define:

c= customer()

and I modify and I do so many 

c.save()

I have this error:
TransportError: TransportError(500, u'RemoteTransportException[[Perun][inet[/10.8.5.15:9301]][indices:data/write/index]]; nested: IndexFailedEngineException[[carallada][4] Index failed for [customer#oid:customer:13]]; nested: FileNotFoundException[/home/jdiazg/elasticsearch/data/juan/nodes/1/indices/carallada/4/index/_5.fdt (Too many open files)]; ')

And the health of my elaticserach cluster is green. 

Could you give me an idea, please? 

Thanks in advance and sorry by the inconvenience

**Comment by HonzaKral** [comment]
Hi, this is an error in your elasticsearch cluster. My guess would be that your `ulimit` doesn't allow for enough file descriptors. This should help you to verify your current settings: https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html#file-descriptors

Hope this helps

**Comment by juandasgandaras** [comment]
Thanks for your quick response.

**Comment by juandasgandaras** [comment]
It´s working correctly. We can close the issue then. 

Thank´s I am very grateful. And sorry for the inconvenience
