### ISSUE TITLE
Restricting Document scan on particular index(es) only

### ISSUE THREAD

**Issue by wanthalf** [elastic/elasticsearch-dsl-py#1950]
When I create `s = Document.search()`, restrict it to particular index(es) only `s = s.index(myindex)` and create a scan `s = s.scan()`, I get results from all indexes defined within the Document's Index class, not just in `myindex`. Is this a feature or a bug? How can I restrict the scan to particular index(es) only?

**Comment by miguelgrinberg** [comment]
Are you using `Document.search()` literally? That isn't an intended use of the `search()` method, the idea is that you define your own document class and then call `search()` on your document class to initiate a search of just the index where these documents are stored.

If you are starting from a generic search just create an instance of the `Search` or `AsyncSearch` classes and set your index. Let me know if this solves the problem, and if not, please share the exact code you are using after applying these guidelines.

**Comment by wanthalf** [comment]
Hopefully I can reduce it correctly in this way:

```python
class MyDocument(Document)

    class Index:
        name =  "myindex-*"

s = MyDocument.search()
s = s.index('myindex-1')
scan = s.scan()
```

The `scan` seems to return results from all `myindex-*` indexes, not just from `myindex-1`. The `s`-search seems to be restricted correctly to `mynidex-1` only.

**Comment by wanthalf** [comment]
Replacing `scan()` with `iterate()` seems to solve the problem, but the speed of retrieval is ca. 150x slower. That makes it unusable for a dataset with 160 million documents.

**Comment by miguelgrinberg** [comment]
You are still starting from a search instance associated with a document. Do you need to do that? The correct way to do a search when you want to provide the index(es) is to start from a `Search` object:

```python
s = Search()
s = s.index('myindex-1')
scan = s.scan()
```

The way you are doing it causes the index that is associated with the document class to be included in the search.

**Comment by wanthalf** [comment]
OK. So I cannot retrieve documents (as `Document` inheriting objects) from just one particular index using `scan`, but I can do that using the `search`? So, the `scan()` does not really turn the complete search into the scan. Anyway, any `sort` is discarded as well, which is probably rather understandable for a scan.

I suppose I should use just the lower level `elasticsearch-py` instead of `elasticsearch-dsl`, like I do other places, since the Document serialization is a radical performance bottleneck in any batch processing too. It just feels pity that I have already implemented most logic on the `Document` level and cannot use it in the end anyway.
