### ISSUE TITLE
Is there any instruction or tutorial on Function Score available? 

### ISSUE THREAD

**Issue by vnnw** [elastic/elasticsearch-dsl-py#197]
I try to customize the result score by using Function Score. But I could only use the pattern below like:

s = Search().using(client).index('idx').query("match", body="my input keywords")
s.query = Q('function_score', query=s.query, field_value_factor={'field': ['num_1', 'num_2']})
response = s.execute()

My question is how I can use a more flexible way to modify the finale score with some math function?

**Comment by HonzaKral** [comment]
Have a look at the official docs for `function_score` (0). It should then be obvious how to translate that to the DSL, for more examples of that see the tests (1).

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html
1 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_query.py#L231-L239

**Comment by vnnw** [comment]
Thanks for the rapid reply and useful info.
I hope that there will be more example ans use cases available in the docs in the near future.

**Comment by vnnw** [comment]
I tried to rewrite the code as below, but got a RequestError [status:400]
 when running it

  s = Search().using(client).index('ad-rtb').query("match", body="my input keywords") \
    .query(Q('function_score', functions=[query.SF('script_score', script="doc['num_1'] * doc['num_1'] * _score")]))

Would you be kind to provide an proper example?

**Comment by vnnw** [comment]
Sorry, it seems that I forget to enable Dynamic Scripting in the cluster's setting.

I am still trying out other query functions, like geo distance filter. I haven't seen anything about it yet.

**Comment by HonzaKral** [comment]
If you know how to write the raw query (or read that in the official docs) then there should be a clear way to translate it to DSL - all keys from the json object (dictionary) become kwargs to the `Q` or `query` calls:

    {'match': {'field': 'value}} # Q('match', field='value')
    {'filtered': {'query': {'match': {'f': 42}}, 'filter': {'term': {'tag': 24}}}} # Q('filtered', query={'match': {'f': 42}}, filter={'term': {'tag': 24})

You can take some more shortcuts when the arguments also represent some DSL objects like queries or filters, for example the filtered query can be also written: `Q('filtered', query=Q('match', f=42), filter=F('term', tag=24))`

I am also fully aware that the documentation is lacking (to put it very generously), I will try and focus on it more.

Hope this helps.

**Comment by HonzaKral** [comment]
closing this issue, there are examples in tests and here and we will hopefully add more as we continue to improve the docs.
