### ISSUE TITLE
error to use elasticsearch_dsl with meta parent

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#198]
Hi, 

I have done this description of a class, that I want it will be child from other class inside of elastcisearch:

connections.create_connection(hosts = [cluster])

class lic_server(DocType):

    "owner  ==>  oid:customer:3"
    "type  ==>  licsrv"
    "id  ==>  oid:asset:5"
    "description  ==>  lic06.gompute.net"

    name = String(index='not_analyzed')
    id = String(index='not_analyzed')

    updated_at = Date()

    class Meta:
        index = 'carallada'
        all = MetaField(enabled=False)
        parent = MetaField(type='customer')
        id = ''

    def save(self, ** kwargs):
        self.meta.id = self.id
        self.updated_at = datetime.now()
        return super(lic_server,self).save(** kwargs)

But now when I try to do the object and I define the child object I have an errror:

lic = lic_server(name='juan',id='juan.id')

lic
 {'id': 'juan.id', 'name': 'juan'}

 lic.meta.parent(parent:'oid:customer:17')

and my error is:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-bc2100665a95> in <module>()
----> 1 lic.meta.parent(parent='oid:customer:17')

/home/jdiazg/anaconda/lib/python2.7/site-packages/elasticsearch_dsl-0.0.5.dev0-py2.7.egg/elasticsearch_dsl/utils.pyc in __getattr__(self, attr_name)
    110         except KeyError:
    111             raise AttributeError(
--> 112                 '%r object has no attribute %r' % (self.__class__.__name__, attr_name))
    113
    114     def __delattr__(self, attr_name):

AttributeError: 'ResultMeta' object has no attribute 'parent'

and I have in elasticsearch inside of the same index 'carallada' the definited customer with id= 'oid:customer:17'

{
            "_index": "carallada",
            "_type": "customer",
            "_id": "oid:customer:17",
            "_score": 1,
            "_source": {
               "dn": {
                  "ou": [
                     "17",
                     "customers"
                  ],
                  "dc": [
                     "om",
                     "net"
                  ]
               },
               "oid": "oid:customer:17",
               "name": "My name",
               "updated_at": "2015-07-10T09:56:52.639829"
            }
         }

Could somebody tell me something or give me an advice?

Thanks in advance

**Comment by HonzaKral** [comment]
`lic.meta.parent = 'oid:customer:17'` should do the trick. `meta` is a dictionary (a hash) containing the metadata, it doesn't have any methods, just assign the attributes you want it to have, like `parent`.

**Comment by juandasgandaras** [comment]
Yes but now if define in this way:
lic.meta.parent = 'oid:customer:17'

the problem come when I do the lic.save()

and it appears:
 
  RequestError: TransportError(400, u"ElasticsearchIllegalArgumentException[Can't specify parent if no parent field has been configured]")


Although in Elasticsearch exist the input with type customer and id oid:customer:17 and they are of the same class than my lic_server:

{
"_index": "carallada",
"_type": "customer",
"_id": "oid:customer:17",
"_score": 1,
"_source": {
"dn": {
"ou": [
"17",
"customers"
],
"dc": [
"om",
"net"
]
},
"oid": "oid:customer:17",
"name": "My name",
"updated_at": "2015-07-10T09:56:52.639829"
}
}

**Comment by HonzaKral** [comment]
You haven't defined parent/child relationship in your mappings.

How do you create your mappings or your index?

**Comment by juandasgandaras** [comment]
I define in the class of the object with the Doctype class from elasticsearch-dls in this way:

The parent class is:
-----------------------------------------------------------------------------------------------------------------
class Parent(DocType):
    name = String(index='not_analyzed')
    updated_at = Date()

    class Meta:
        index = 'my_index'
        id = ''

    def save(self, ** kwargs):
        self.updated_at = datetime.now()
        return super(customer,self).save(** kwargs)

-----------------------------------------------------------------------------------------------------------------

And the child class is:

class Child (DocType):
    name = String(index='not_analyzed')
    id = String(index='not_analyzed')
    updated_at = Date()


class Meta:
     index = 'my_index'
    parent = MetaField(type='Parent')            <<<==============
    id = ''

def save(self, ** kwargs):
        self.meta.id = self.id
        self.updated_at = datetime.now()
        return super(lic_server,self).save(** kwargs)

**Comment by HonzaKral** [comment]
Ah, so what you miss is actually sending these definitions to elasticsearch to create the index and set the mappings. Recommended way of doing that is to create and `Index` object and use it to create the actual index in elasticsearch:

    # create the index object
    index = Index('my_index')
    # associate the document types with it
    index.doc_type(Parent)
    index.doc_type(Child)
    # create it in elasticsearch
    index.create()

This needs to happen *before* you index any data into elasticsearch.

**Comment by juandasgandaras** [comment]
I have done this but  I have the same problem again:

  # create the index object
  index = Index('my_index')
  # associate the document types with it
  index.doc_type(Parent)
  index.doc_type(Child)
  # create it in elasticsearch
  index.create()

 I do the index of parent class and I test  that is well done, Afer I do the index of child class

  l= Child()
  l.name='my_name_test'
  l.id= 'aaa'
  l.meta.parent = 'oid:customer:17'
  l.save()

And my Error is:


RequestError: TransportError(400, u"ElasticsearchIllegalArgumentException[Can't specify parent if no parent field has been configured]")

In the mapping I can see the next:

   "mis_cositas": {
      "mappings": {
         "lic_server": {
            "properties": {
               "id": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "name": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "updated_at": {
                  "type": "date",
                  "format": "dateOptionalTime"
               }
            }
         },
         "customer": {
            "properties": {
               "description": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "dn": {
                  "properties": {
                     "dc": {
                        "type": "string"
                     },
                     "ou": {
                        "type": "string"
                     }
                  }
               },
               "name": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "oid": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "updated_at": {
                  "type": "date",
                  "format": "dateOptionalTime"
               }
            }
         }
      }
   }
}

customer it would be the parent class and lic it would be the child class and in the lic class  I defined so:

class lic_server(DocType):

    name = String(index='not_analyzed')
    id = String(index='not_analyzed')

    updated_at = Date()


    class Meta:
        id = ''
        parent = MetaField(type='customer')


    def save(self, ** kwargs):
        self.meta.id = self.id
        self.updated_at = datetime.now()
        return super(lic_server,self).save(** kwargs)

**Comment by HonzaKral** [comment]
For some reason the mapping didn't get saved - did you get any error message when creating the index? Did you make sure the index didn't exist before you tried to create it?

Oh, you also need to specify the name of the document type in lower case when specifying the `parent` `MetaField` - `parent`, not `Parent`.

You can see a working example in:
https://github.com/HonzaKral/es-django-example/blob/master/qa/search.py (doc type definitions)
https://github.com/HonzaKral/es-django-example/blob/master/qa/management/commands/index_data.py#L19 (code creating the index)

**Comment by juandasgandaras** [comment]
Ok, it is working using:

# create the index object
index = Index('my_index')
# associate the document types with it
index.doc_type(Parent)
index.doc_type(Child)
# create it in elasticsearch
index.create()

and without especify the Index in the meta of each class ().

Thanks for your help again it is so grateful to reply me so quickly. I don´t know how to be grateful for this. 

And sorry by the inconvenience.

**Comment by HonzaKral** [comment]
Happy to help

**Comment by juandasgandaras** [comment]
Hi,

I am obtaning the same error when I get an id from an index:

 TransportError(400, u'RoutingMissingException[routing is required for [gompute]/[lic_server]/[oid:asset:1]]')

Although I have definited in the mapping thre relation between parent and child and furthermore when insert in elasticsearch I don´t have any problem but when I want to do a get I have this error for example:

l_created = lic_server(name = i["description"].encode('utf-8'),id =i["id"].encode('utf-8'))
l_created.meta.parent = i["owner"].encode('utf-8')
l_created.save()

I have not an error 

But if I want to to do the get the introduced element before:

l_obtained = lic_server.get(id =i["id"].encode('utf-8') ,index=index_gompute,ignore=404)

I obtain this error:


 TransportError(400, u'RoutingMissingException[routing is required for [gompute]/[lic_server]/[oid:asset:1]]')

**Comment by juandasgandaras** [comment]
and in the mapping it is definited to the Parent and the Child:

"gompute": {
"mappings": {
"lic_server": {
"_parent": {
"type": "customer"
},

...

"gompute": {
"mappings": {
"customer": {
"properties": {
"description": {
"type": "string",
"index": "not_analyze
