### ISSUE TITLE
problem to save a doctype and the doctype has a field like as String(index='not_analyzed', multi=True)

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#201]
Hi

Nowadays I have a problemm, I would like to use the DocType class and one of its parameters save as a list of strings, so I defined this:

class application(DocType):

    short_name = String(index='not_analyzed')
    lic_servers = String(index='not_analyzed', multi=True)

    updated_at = Date()

    class Meta:
        id = ''

    def save(self, ** kwargs):
        self.meta.id = self.short_name
        self.updated_at = datetime.now()
        return super(application,self).save(** kwargs)

It was to save in elastic searc a document in this form:

 api = application.get(id=my_ID,index=my_index,ignore=404)

  if api == None:
       api = application(short_name = m)

api.lic_servers.append('lic_server_0')

res = api.save()

But I have the problemm that when I have more than one lic_server in this way for example:

api.lic_servers
=>['lic_server1' , 'lic_server2', 'lic_server3', ...... 'lic_serverN']

I have the problem to save because:

res = api.save()

And res = FALSE.

Could somebody tell me something about this?

Thanks in advance.

**Comment by vnnw** [comment]
From my knowledge, you don't have to specify "multi=True" when define an array field.
Defining the field like normal as below will be OK:
  lic_servers = String(index='not_analyzed')

When indexing docs, you just pass the string list, ES will know it is a multi-value field, that means you don't have to append the element one by one manually.

After indexing work is finished, the data will be something like below:

     "_source": {
          "lic_servers ": [ "lic_server_0",  "lic_server_1", … ],
    "short_name": "short_name",

Correct me if I am wrong.

**Comment by juandasgandaras** [comment]
Yes I am agrree, but the problem is that  I want to update in diferent times with different licservers and the problem appears when I do 

lic_server.save()

that gives me a False instead of a True

**Comment by vnnw** [comment]
Yes, I agree with you.
There are some response messages appear confusing.
But the index should have been updated if nothing else is going wrong.

**Comment by njoannin** [comment]
@vnnw The point of ```multi=True``` is to be able to use the ```append``` method to a field, even if that field does not yet exist in that instance.

So, for instance:

```
>>> class Test(DocType):
...    name = String()
...    name_list = String(multi=True)
... 
>>> t = Test(_id=1)
>>> t.name.append("my_name)
  File "<stdin>", line 1
    t.name.append("my_name)
                          ^
SyntaxError: EOL while scanning string literal
>>> t.name_list.append("my_first")
```

So, specifying ```multi=True``` has a purpose (although I have just noticed an problem with it, but that will be for another issue).

@juandasgandaras The ```save``` method should return the value of the ```created``` field in the response from Elasticsearch. If you save a document with an id that already exists in your index, then it will return ```False```. If the document does not exist in that index, then it should return ```True```.

Might this simply be that you are updating your document and not creating a new one?

**Comment by vnnw** [comment]
@njoannin Thank you fore the clarification.

**Comment by juandasgandaras** [comment]
@njoannin  Thanks for your aclarations, they are very useful

**Comment by HonzaKral** [comment]
Yes, the return value of the `save` method has just that significance. I am a little worried that people misunderstand the reason for the different return values, do you have any suggestions on how to make things better?

We can remove the return value altogether or actually return the whole reply from elasticsearch as `AttrDict`. Or maybe just the model instance or its `meta`?

Any feedback would be appreciated.

**Comment by njoannin** [comment]
@HonzaKral 
Most of the time, I don't need the returned info. But sometimes, it could be useful to check the ```_version``` or ```created``` values. So, I would prefer it to return nothing by default, but having the option of it returning the whole reply.

**Comment by HonzaKral** [comment]
Thanks for the reply!
The `version` is set on the document itself so just checking `doc.meta.version` should do the trick. Only the `created` flag isn't stored anywhere, that was my original reasoning for returning that.

**Comment by njoannin** [comment]
Ah, yes, so, I guess the only useful thing to return (still as an option, IMO) would be the creation status.

**Comment by juandasgandaras** [comment]
In my opinion I think it would be apreciated that return three things:

Error if cannot save by any reason or something.
Ok and in this case to be able to distinguish two different cases:
            - If it was created 
            - If it was updated to a new version.

Thanks for your work.

**Comment by HonzaKral** [comment]
Well, if it cannot be saved you'd get an exception so we are coming back to just the created/updated. I will leave it as is for now.

Thanks!

**Comment by njoannin** [comment]
@HonzaKral Just out of curiosity, do you usually use the ```.save()``` returned value?

**Comment by HonzaKral** [comment]
not really, no. Though it is useful sometimes when working in interactive mode (ipython) to see what's going on.

**Comment by njoannin** [comment]
Then, what do you do with the returned value?

Currently, I assign it to a variable that I don't use, which I find kind of annoying.
I don't want it littering my output...

**Comment by HonzaKral** [comment]
I don't do anything with it, just look to see if it is as expected. In actual code I just ignore the value and not assign it anywhere.

**Comment by njoannin** [comment]
OK, thanks for taking the time to answer ;)
