### ISSUE TITLE
how can spcify unix time using Date from elasticsearch_dsl

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#203]
Hi, 

I have this:

 class Test(DocType):
       ...:     name = String()
       ...:     date = Date()

How can I save time unix in date and in a future to can do operations with this field like a date normal.

Because now if I do this:
c= Test()
c.date = 143513598

I obtain this error:

 ('Could not parse date from the value (1435135980000)', AttributeError("'int' object has no attribute 'read'",)

Any idea?

Thanks in advance.

**Comment by njoannin** [comment]
@juandasgandaras 

You need to give it a ```datetime``` object.
That is, you need to convert your timestamp:

```
import datetime 
c = Test()
c.date = datetime.datetime.fromtimestamp(143512598)
```

Hope this helps!

**Comment by juandasgandaras** [comment]
Ok Thanks, I am very grateful.

**Comment by HonzaKral** [comment]
Thanks @njoannin for the response, closing this issue.
