### ISSUE TITLE
How to disable the field-length norms in the mapping?

### ISSUE THREAD

**Issue by vnnw** [elastic/elasticsearch-dsl-py#204]
I want to define a mapping which disables the field-length norms when calculating relevance score.
But I cannot find a way to define it with es-dsl-py after searching the document and repository.

Anyone be kind to provide an example?

The mapping will be something like below from https://www.elastic.co/guide/en/elasticsearch/guide/current/scoring-theory.html#field-norm

    PUT /my_index 
        {
          "mappings": {
            "doc": {
              "properties": {
                "text": {
                  "type": "string",
                  "norms": { "enabled": false } 
                }
              }
            }
         }
      }

**Comment by HonzaKral** [comment]
from elasticsearch_dsl import DocType, String
    class Doc(DocType):
        text = String(norms={'enabled': False})

Should do the trick. To get the mappings into elasticsearch use the Index object:

    from elasticsearch_dsl import Index
    i = Index('my_index')
    i.doc_type(Doc)
    i.create()

Hope this helps

**Comment by vnnw** [comment]
Thank you for being so kind, @HonzaKral !
