### ISSUE TITLE
Date field to respect format

### ISSUE THREAD

**Issue by geeknam** [elastic/elasticsearch-dsl-py#206]
My doc type has `shipping_date = Date(format='date')`

However, the result returned is a python `datetime` object.

**Comment by sinistersnare** [comment]
Seems this is already in issue #94.

**Comment by HonzaKral** [comment]
Closing this in favor of #94 

This is a complex problem to support all available formats and I doubt we can solve it well.

@geeknam I understand that `date` would be better, but `datetime` is a subclass of `date` so it shouldn't matter much. Do you have a use case where there is a difference? thanks!
