### ISSUE TITLE
Possible to override DocType's init so that .get() can run on Tornado's run_on_executor?

### ISSUE THREAD

**Issue by brizzbane** [elastic/elasticsearch-dsl-py#207]
trying to do something like the following:

:

class EmailDomain(DocType):

    def __init__(self, meta=None, **kwargs):
        self.executor = ThreadPoolExecutor(max_workers=4)
        self.io_loop = ioloop.IOLoop.current()

        super(DocType, self).__init__(**kwargs)

    class Meta:
        index = 'emaildb_domains'

    @concurrent.run_on_executor
    def save(self, ** kwargs):
        return super(EmailDomain, self).save(** kwargs)

but get the following error:

 File "build/bdist.linux-x86_64/egg/elasticsearch_dsl/document.py", line 111, in __getattr__
    return super(DocType, self).__getattr__(name)
  File "build/bdist.linux-x86_64/egg/elasticsearch_dsl/utils.py", line 414, in __getattr__
    return super(ObjectBase, self).__getattr__(name)

I looked at the source for doctype, and copied what was in init, and added executor, and io_loop, but still got the same error.  if I want to do this, will I basically just need to make my own doctype class? (instead of trying to override).

[edit]  just realized in the example I put on .save..  but issue remains.

as a workaround, right now just doing:

    @concurrent.run_on_executor
    def async_doc_get(self, doc, id):

        return doc.get(id=id)

    @concurrent.run_on_executor
    def async_doc_save(self, doc):

        return doc.save()

maybe this is better way to do it anyways?

**Comment by HonzaKral** [comment]
All attributes need to start with underscore, otherwise they'll be treated as fields.

Hope this helps, please excuse brevity, sent from phone

**Comment by brizzbane** [comment]
awesome, thanks!
