### ISSUE TITLE
Allow additional arguments to the `Search.from_dict` function

### ISSUE THREAD

**Issue by djt5019** [elastic/elasticsearch-dsl-py#211]
Currently, the `Search.from_dict` function only takes a single dictionary and creates a new `Search` object which does not have any knowledge of the client connection, the indicies, etc.  This leads to code similar to the following:

```python
client = Elasticsearch()
s = Search.from_dict({'query': 'blah'})
s._using = client
s._index = ['index1', 'index2']
print(s.execute())
```

The `Search.from_dict` function should allow additional positional and keyword params which it just passes down to the `Search` constructor.  It's a simple fix, I'll have a PR shortly.

**Comment by HonzaKral** [comment]
You don't need to be using the protected attributes, your example should instead be written as:

    client = Elasticsearch()
    s = Search.from_dict({'query': 'blah'})
    s = s.using(client).index('index1', 'index2')

There is a public api for setting the client and index so there is no need to duplicate that in `from_dict`.

**Comment by leoliuxd** [comment]
Thank you.
