### ISSUE TITLE
Mistake in Multiple clusters

### ISSUE THREAD

**Issue by dangmocrang** [elastic/elasticsearch-dsl-py#214]
connections.add_connection('qa', hosts=['esqa1.example.com'], sniff_on_start=True) is wrong

**Comment by neuroid** [comment]
Perhaps this should be a call to `create_connection()` instead.

**Comment by dangmocrang** [comment]
it only work when use with syntax:
connections.add_connection('qa', 'abc.example.com')

but when called: connections.get_connection('qa') it returns just the string 'abc.example.com'
