### ISSUE TITLE
[QUESTION] analyzer to dict while setting up index

### ISSUE THREAD

**Issue by mieciu** [elastic/elasticsearch-dsl-py#216]
Hey,

First of all, congrats on making this DSL -> it's really well engineered and just pleasurable to use!!

I was playing with it today, and I discovered such a behaviour:
```
>>> bug_analyzer = analyzer('bug_analyzer', tokenizer=tokenizer('default_nGram', 'nGram'))
>>> my_index.settings(analysis=bug_analyzer)
<elasticsearch_dsl.index.Index object at 0x7f7e0ae0d190>
>>> my_index.create()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  ...
  File "/app/.heroku/python/lib/python2.7/site-packages/elasticsearch/serializer.py", line 47, in dumps
    raise SerializationError(data, e)
SerializationError: ({'settings': {'analysis': CustomAnalyzer(tokenizer=NGramTokenizer())}}, TypeError("Unable to serialize CustomAnalyzer(tokenizer=NGramTokenizer()) (type: <class 'elasticsearch_dsl.analysis.CustomAnalyzer'>)",))
>>> my_index.settings(analysis=bug_analyzer.to_dict()
Display all 191 possibilities? (y or n)

>>> my_index.settings(analysis=bug_analyzer.to_dict())
<elasticsearch_dsl.index.Index object at 0x7f7e0ae0d190>
>>> my_index.create()
```

My question is, was it intended to explicitly use that `to_dict()` method? As from high level DSL I'd expect
`my_index.settings(analysis=bug_analyze)` to just work, even with passing several analysers (as a list/tuple/....).

I'd really like to make a PR with this analyzer serialisation, but perhaps it is some deeper sense  in preventing from having such an interface?

**Comment by HonzaKral** [comment]
The proper way to use a custom analyzer is to just attach it to a field and then, when you create the index it will get created automatically:

See https://github.com/HonzaKral/es-django-example/blob/master/qa/search.py#L11-L42 for definition and https://github.com/HonzaKral/es-django-example/blob/master/qa/management/commands/index_data.py#L20 where it actually gets sent to elasticsearch.

Hope this helps.

**Comment by mieciu** [comment]
Actually that looks really cool - thanks!!
