### ISSUE TITLE
 TransportError(400, u'RoutingMissingException[routing is required for

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#219]
Hi,
This is related to the issue: https://github.com/elastic/elasticsearch-dsl-py/issues/198.

I am obtaning the next  error when I get an id from an index:

TransportError(400, u'RoutingMissingException[routing is required for [gompute]/[lic_server]/[oid:asset:1]]')

Although I have definited in the mapping thre relation between parent and child and furthermore when insert in elasticsearch I don´t have any problem but when I want to do a get I have this error for example:

l_created = lic_server(name = i["description"].encode('utf-8'),id =i["id"].encode('utf-8'))
l_created.meta.parent = i["owner"].encode('utf-8')
l_created.save()

I have not an error

But if I want to to do the get the introduced element before:

l_obtained = lic_server.get(id =i["id"].encode('utf-8') ,index=index_gompute,ignore=404)

I obtain this error:

TransportError(400, u'RoutingMissingException[routing is required for [gompute]/[lic_server]/[oid:asset:1]]')

Thanks in advance.

**Comment by juandasgandaras** [comment]
and in the mapping it is definited to the Parent and the Child:

"gompute": {
      "mappings": {
         "lic_server": {
            "_parent": {
               "type": "customer"
            },


...

"gompute": {
      "mappings": {
         "customer": {
            "properties": {
               "description": {
                  "type": "string",
                  "index": "not_analyze

**Comment by juandasgandaras** [comment]
I have just solucionated this problemm with this:

 l_obtained = lic_server.get(id=i['id'], parent=i['owner'] ,index=index_gompute,ignore=404)

I specified the Parent inside the get.

Thanks

**Comment by HonzaKral** [comment]
Yes, if you are using parent child relationship you need to specify parent when running `get` or `save`.

You can override the `save` method to extract the value form the document or you can just set the `.meta.parent` field manually if you don't want to pass it into the `save` method every time.

**Comment by rlam3** [comment]
For those who are having an issue with this too:

parent = ID of the parent object document

**Comment by AdrianSzymczak** [comment]
Hi, I think that suggested here solution stopped working. 

I'm using: ES. 5.4.3, elasticsearch 5.4.0 and elasticsearch-dsl 5.3.0
Executing code below results in following mappings:

> {"call":{"mappings":{"post":{"_parent":{"type":"user"},"_routing":{"required":true},"properties":{"content":{"type":"integer"}}},"user":{"properties":{"user":{"type":"integer"},"username":{"type":"long"}}}}}}

`call = Index(settings.ELASTICSEARCH_CALL_INDEX, using=elasticsearch)
call.settings()

call.settings(
    number_of_shards=settings.ELASTICSEARCH_NUM_SHARDS,
    number_of_replicas=settings.ELASTICSEARCH_NUM_REPLICAS
)

@call.doc_type
class User(DocType):
    user = Integer()
    class Meta:
        doc_type = 'user'
        index = 'call'

@call.doc_type
class Post(DocType):
    content = Integer()
    class Meta:
        doc_type = 'post'
        index = 'call'
        parent = MetaField(type='user')

call.doc_type(User)
call.doc_type(Post)
call.create()`

However on save which is performed with following code I see error

> {"error":{"root_cause":[{"type":"routing_missing_exception","reason":"routing is required for [call]/[post]/[1]","index_uuid":"_na_","index":"call"}],"type":"routing_missing_exception","reason":"routing is required for [call]/[post]/[1]","index_uuid":"_na_","index":"call"},"status":400}

`User(username=1, _id=1).save()
p  = Post(content=1, _id=1, _parent=1,  parent=1, _routing=1, routing=1)
p.meta.parent = 1
p.meta.routing = 1
p.save(parent=1, routing=1, id=1)`

I've tried version with and without routing, parent, prefixing with _ or not etc. Everything results in the same result - any help will be appreciated
