### ISSUE TITLE
How to change the Root Object proprieties ?

### ISSUE THREAD

**Issue by k4nar** [elastic/elasticsearch-dsl-py#220]
Hi,
I would like to use [`dynamic_templates`](https://www.elastic.co/guide/en/elasticsearch/reference/1.5/mapping-root-object-type.html#_dynamic_templates) on a `DocType`, but I don't understand where I should set it. Should it be in the `Meta` ?

**Comment by HonzaKral** [comment]
This is a duplicate of https://github.com/elastic/elasticsearch-dsl-py/issues/208

thanks for the report.
