### ISSUE TITLE
Unable to Serialize..  working with large documents.  Making 'partial document' copies, replacing in DocType list[start:end]

### ISSUE THREAD

**Issue by brizzbane** [elastic/elasticsearch-dsl-py#221]
I'm working with many large documents at the same time.   Instead of keeping the document in memory, I am making copies of 'part' of the document, and working my way through the copy before querying elasticsearch again when the partial document is exhausted.

I'm trying to save the processed document back into elasticsearch, but am getting  the error, 'unable to serialize user'.

user is like so {'username':'blahblah'}, which is in users.users_list.

To find where to replace the index im doing:

start_index = next(index for (index, d) in enumerate(users.users_list) if d['username'] == member_dict['partial_doc']['users']['users_list'][0]['username'])
end_index = len(member_dict['partial_doc']['users']['users_list'])

member_doc.users.users_list[start_index:end_index] = member_dict['partial_doc']['users']['users_list']

when working with the actual document, I had no issues w/serialization, so wondering if this is something I'm doing wrong, or if you can't do what I'm trying to do .

should this be working? :\ .  Really appreciate the help.

**Comment by brizzbane** [comment]
guessing since no response, issue w/me.  closing unless I can show otherwise.

**Comment by HonzaKral** [comment]
This is long without reply because I haven't had the time to respond properly and study it. frankly I have some trouble understanding what it is you wish to do, could you provide some code and some examples?

Thanks!

**Comment by brizzbane** [comment]
actually think there might be something going on.  going down to a single entry:

member_doc.users.users_list[1] = member_dict['partial_doc']['users']['users_list'][1],
and it fails to serialize, but in python I can do:

if member_doc.users.users_list[1] ==  member_dict['partial_doc']['users']['users_list'][1]:
    print 'True'

--and it prints true..

**Comment by brizzbane** [comment]
OK to explain further, I have many documents in database, and they all contain 'users_lists'.  But the documents are large--anywhere between 1mb-36mb (its email files for a single domain).  When working w/many domains at a time, I can exceed the memory of the machine, and the python process gets killed.

So instead of loading hundreds of thousands--millions of users per TLD, im making 'partial' document copies of the userslist, like so:

partial_doc = deepcopy(domain_doc['users']['users_list'][start_index:end_index)

start_index, end_index is by 'batch size', and I keep track of where I am w/db_index..

and latest comment, am just trying with a 'single' user, and its failing to serialize.

here is an example user:

[{u'username': u'001', u'last_delivered': u'1970-01-01T00:00:00', u'bounce_code': 0, u'bounce_datetime': u'1970-01-01T00:00:00', u'repl': u'', u'sent_count': 0}]

whats odd is, i can say test = [{u'username': u'001', u'last_delivered': u'1970-01-01T00:00:00', u'bounce_code': 0, u'bounce_datetime': u'1970-01-01T00:00:00', u'repl': u'', u'sent_count': 0}]

and replace in doctype by refencing 'test', but if that exact same value is a copy, like so:

emaildomain_doc['users']['users_list'][1] = domain_dict['partial_doc']['users']['users_list'][1]

it doesn't work.  (emaildomain_doc['users']['users_list'][1] = test does work).

and python 'sees' it as being equal too..

**Comment by brizzbane** [comment]
I will work on putting together end to end example right now.

**Comment by HonzaKral** [comment]
Failing to serialize when? What are you trying to do that requires serialization?

Also have you considered just using parent/child relationship to store those as individual documents? Might make your life a lot simpler.

**Comment by brizzbane** [comment]
I haven't considered that no..When I started indexing thousands and thousands of documents for individual users tho figured that prob wasn't the 'way' to do it.  just made an end to end example, and it works, so maybe I'm wrong again.

I think my problem probably comes from this now that I see the 'copy' isn't the problem:

        partial_doc = {'users':{'rejected_count':int(emaildomain_doc.users.rejected_count),
                                'user_count':int(emaildomain_doc.users.user_count),
                                'bounce_count':int(emaildomain_doc.users.bounce_count),
                                'deliverable_count':int(emaildomain_doc.users.deliverable_count),
                                'users_list':list(emaildomain_doc.users.users_list[current_index:new_index])}}

        domain_dict['partial_doc'] = deepcopy(partial_doc)

**Comment by HonzaKral** [comment]
I still don't understand and cannot replicate the issue. Could you paste the traceback somewhere?

Also why are you using deepcopy? If you concern is to save memory making a copy of everything you have seems counterproductive.

**Comment by brizzbane** [comment]
continued messing with it, here it is, stripped down.  (hadn't messed w/my code involving issue since I posted, so took me a bit to strip it down to be reproducible)

https://gist.github.com/brizzbane/56dc3043d8ca0f0ec177

--the copy is of 'usernames', instead of the entire domain.  so hotmail might have username 'honzakral', 'brizzbane', etc.  instead of every single username a-z...

when usernames are done being processed--I re-query, and make a copy.

**Comment by HonzaKral** [comment]
So the issue is that you assigned AttrDict instances instead of dict. That is something that should be supported so this is a bug I will fix.

Thanks for the report and your patience in walking me though it.

**Comment by brizzbane** [comment]
ok..  so in the meantime, what would be a workaround?

tried the following, https://gist.github.com/brizzbane/7369f539929b1fa239ef, but its also not working  (don't really understand the problem).

**Comment by brizzbane** [comment]
so is it possible there is something more going on?  I tried replacing everywhere to reference the dict, as so:

https://gist.github.com/brizzbane/49d39f2e301ff91b556b

but still having issues.  sorry for pestering about this.  It's an issue thats key component to this particular project that I'm working on, and have been unable to move forward w/it.

**Comment by HonzaKral** [comment]
Finally managed to track down a reasonable solution, which is to introduce our own serializer that is aware of `AttrList`/`AttrDict`

Sorry it took so long

**Comment by bgroff** [comment]
No worries, thanks for the clarification and the documentation update.
