### ISSUE TITLE
Adding Custom Analyzers to `_all` correctly

### ISSUE THREAD

**Issue by daviddyball** [elastic/elasticsearch-dsl-py#222]
Hi,

With the following Document, I am finding it impossible to add the correct search/index analyzers to the `_all` field for auto-complete searching without first including them as either an `index_analyzer` or `search_analyzer` on a field other than `_all`.

Here is my mapping code:

```
my_index_analyzer = analyzer(
    'my_search_analyzer',
    filter=['standard', 'lowercase', 'asciifolding', ngram_filter],
    tokenizer='standard'
)

my_search_analyzer = analyzer(
    'my_search_analyzer',
    filter=['standard', 'lowercase', 'asciifolding'],
    tokenizer='standard'
)

class MyDoc(DocType):
    class Meta:
        all = MetaField(
            search_analyzer='my_search_analyzer',
            index_analyzer='my_index_analyzer'
        )
    name = String(include_in_all=True)
```

It works if I change my Doc mapping to this:

```
class MyDoc(DocType):
    class Meta:
        all = MetaField(
            search_analyzer='my_search_analyzer',
            index_analyzer='my_index_analyzer',
        )
    name = String(
        include_in_all=True,
        index_analyzer=my_index_analyzer,
        search_analyzer=my_search_analyzer
    )
```
But I don't want the `name` field to use the index/search analyzers, I only want that on `_all`.

Any help is appreciated. Once I know how it's done I'll submit a PR to add it to the documentation if anyone would find that useful.

Cheers

**Comment by HonzaKral** [comment]
Hi, thanks for the report - this is a bug where `_all` field is being ignored in `Mapping._collect_analysis` which currently only look on normal fields and ignore the meta fields.

**Comment by daviddyball** [comment]
@HonzaKral thanks for the response. Is there any workaround for the time being until the bug is patched? I'm currently experimenting with creating the index explicitly and specifying analysis settings in there, but that's proving a bigger change than I had anticipated.

**Comment by daviddyball** [comment]
Actually, I figured out a temporary solution. I just created a field like so:

```
class MyDoc(DocType):
    _dummy = String(index_analyzer=my_index_analyzer, search_analyzer=my_search_analyzer)
    class Meta:
        all = MetaField(
            index_analyzer=my_index_analyzer,
            search_analyzer=my_search_analyzer
        )
```
