### ISSUE TITLE
New PyPi Release (0.0.5)?

### ISSUE THREAD

**Issue by daviddyball** [elastic/elasticsearch-dsl-py#224]
You kindly closed #222 with commit id d730ba0c001c78cf9db998285e29fc946aa2fc45 which is brilliant and I was wondering if there is a new PyPi release planned in the near future? 

Our team prefers not to build form specific commit-ids where possible, but if the next release is still a way off we'll do that.

Thanks again for closing #222.

**Comment by k4nar** [comment]
I would be happy with a release too. Quite a few things have changed since 0.0.4.

**Comment by wkiser** [comment]
+1 to wanting a new release

**Comment by DavidMuller** [comment]
A new release would be great, thanks for this package!

**Comment by amirrustam** [comment]
+1. Definitely enough things have changed to grant a new release. For example the `script_fields` method of the `Search` class is currently not in 0.0.4, even though it is fairly common in search queries.

**Comment by HonzaKral** [comment]
I am sorry, this has been long overdue - done in b5f2554dd35a0147b2fa09ef2c0c115d8f79512b
