### ISSUE TITLE
elastisearch_dsl parents and childs not appears not to be in the same shard

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#226]
Hi, 

I was working with the elasticsearch_dsl and I want to implement the parent/child relationship inside elasticsearch and I defined the parent as:

class Parent(DocType):

    name = String(index='not_analyzed')
    id = String(index='not_analyzed')

    updated_at = Date()

    class Meta:
        id = ''"

And the child as:

class Child(DocType):
   name = String(index='not_analyzed')
   timestamp = Date()

    class Meta:
        parent = MetaField(type='parent')

First I index all parent documents and finally, I index the child documents like:

e = child(name = "the_name", timestamp = datetime.fromtimestamp(the_timestamp)) 
e.meta.parent = id_of_my_parent
e.save()

I have 5 parents:

GET my_index/parent_type/_count

The result is:
{
   "count": 5,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   }
}

GET my_index/child_type/_count
the result is:
{
   "count": 214063,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   }
}

When I search by the has_parent in elasticsearch like this:

GET my_index/child_type/_search
{
  "query": {
    "has_parent": {
      "parent_type": "the_parent_type",
      "query": {
        "term": {
          "id": "id_parent"
          }
        }
      }
    }
  }
}

doesn´t works.

But if I ask in this way:

GET my_index/child_type/_search
{
  "query": {
      "term" : { "child_type._parent" : "parent_id" }
      }
}

 It works correctly. 

I was thinking about the main reason is that they are not in the same shard so I cannot search by the first method.

Please could somebody giveme an advice?

Thanks in advance.

**Comment by HonzaKral** [comment]
What is the mapping that you see in elasticsearch? How do you create your mappings?

Thanks

**Comment by juandasgandaras** [comment]
I think that I have just solved, the problemm I think it was that the parent class it was child from another class and when I was saving this I did not specify the meta routing parameter like:

i= My_class()

work with i 
and finally 

i.meta.parent= parent_id
i.meta.routing= grand_parent_id

In the mapping of My class I have the next definition:

class My_class(DocType):

    name_my_class = String(index='not_analyzed')
    ....
    updated_at = Date()


    class Meta:
        parent = MetaField(type='parent_type')

**Comment by juandasgandaras** [comment]
Thanks

**Comment by HonzaKral** [comment]
Ah, yes, that is unfortunately something you have to specify yourself.

Closing the ticket.
