### ISSUE TITLE
DocTypeMeta object got multiple values for keyword argument 'meta'

### ISSUE THREAD

**Issue by jasisz** [elastic/elasticsearch-dsl-py#229]
This error occurs when the object in index has field named `meta`.
When the method `from_es` of the `DocType` is called we got `meta` key twice in the call to the class constructor and TypeError exception is raised.

**Comment by HonzaKral** [comment]
Yes, that is unfortunately true - the `meta` name is reserved for internal use. As a workaround you may want to override `from_es` and `to_dict` to rename the field but I'd recommend renaming the field in es itself

**Comment by HonzaKral** [comment]
Closing since this is just a limitation of the library.
