### ISSUE TITLE
[Question] Search result and document version?

### ISSUE THREAD

**Issue by njoannin** [elastic/elasticsearch-dsl-py#230]
I am quite confused about how search results work when it comes to the version of the found document.

Question: how is the search results aware of the document version?

If I have ```MyDocs```, and I search it:

```
>>> results = MyDocs.search()
>>> results[0].meta.to_dict()
{'index': 'my_index', 'doc_type': 'my_docs', 'score': 1.0, 'id': 'test'}
```

Now, if I get that doc, just to check:

```
>>> doc = MyDocs.get("test")
>>> doc.meta.to_dict()
{'found': True, 'doc_type': 'my_docs', 'id': 'test', 'index': 'my_index', 'version': 2}
```

Now, if I change something to the search result and save it:

```
>>> results[0].changed = True
>>> results[0].save()
False
>>>results[0].meta.to_dict()
{'index': 'my_index', 'doc_type': 'my_docs', 'score': 1.0, 'id': 'test', 'version': 3}
```

I'm guessing that at some point, either when the document is changed or saved, the document is actually retrieved with ```MyDocs.get("test")```. But I can't figure out where...

Honza (or anybody who knows), could you please enlighten me?

**Comment by HonzaKral** [comment]
`search` doesn't return version, but when you call `save` it does return a new version of the document and we update the `meta` to reflect that.

So if you have either retrieved the document via `get` or called a `save` the version will be set.

Hope this helps

**Comment by njoannin** [comment]
Nope, that's not quite what I'm asking...

Working on the results "hit", since there is no version, how does the ```hit.save()``` know what the current version is?

Or, are you telling me that when a document is saved without including the version parameter, it will automatically simply increment the current version of the document that has that ```_id``` in the index?

**Comment by HonzaKral** [comment]
Yes, exactly - `hit.save()` doesn't know it so it will just end up incrementing the version in the index.

**Comment by njoannin** [comment]
OK, so that implies that if there is some lag between the search operation and the save operation, and some other process updates the same document, there will be NO version conflict error...

I hadn't understood that subtlety...

**Comment by HonzaKral** [comment]
Yes, it is also true if the document is in es but refresh hasn't occurred yet - then search will return an older version that get would have.

**Comment by njoannin** [comment]
Thanks for the clarifications! Much appreciated :)
