### ISSUE TITLE
Unable to use 'no_stem' filter in analyzer

### ISSUE THREAD

**Issue by artursmet** [elastic/elasticsearch-dsl-py#233]
I can't use following construction in my analyzer definition:
`analyzer('name', tokenizer='edgeNGram', filter=['standard', 'no_stem'])`

According to documentation, it should be possible:
https://www.elastic.co/guide/en/elasticsearch/guide/current/controlling-stemming.html#preventing-stemming

I think that there is a little bug - missing `no_stem` string in TOKEN_FILTERS definition - https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/analysis.py#L61

**Comment by HonzaKral** [comment]
`no_stem` filter in that example is a custom filter, not a built in one. To replicate that example you'd have to do:

    from elasticsearch_dsl.analysis import analyzer, token_filter
    
    no_stem = token_filter('no_stem', type='keyword_marker', keywords=['skies'])
    
    my_english = analyzer('my_english',
        tokenizer='standard',
        filter=['lowercase', no_stem, 'porter_stem']
    )

Hope this helps.
