### ISSUE TITLE
How do I dedup documents?

### ISSUE THREAD

**Issue by viksit** [elastic/elasticsearch-dsl-py#235]
I'm trying to use something like this in order to dedup all documents returned whose name is the same,
```
s = s.highlight_options(...)
s.aggs.bucket("dedup", "terms", field="name")\
              .metric("dedup_docs", "top_hits", size=1)
res = s.execute()
```

I get answers back as the following,

```
 b = res.aggregations.dedup.buckets
for i in b:
        print i.dedup_docs.hits.hits[0].get("_source").get("name")
```

but I still see duplicates here. Not entirely sure whats going on since I haven't used this feature with raw elasticsearch before. Ideas?

Thanks!

**Comment by HonzaKral** [comment]
I cannot replicate this behavior, it works fine for me. Could you please make sure that `name` is a `not_analyzed` field in your mappings?

Thanks

**Comment by HonzaKral** [comment]
This works for me so I assume it is a fault with mappings. PLease feel free to reopen if it is not so.

Thanks
