### ISSUE TITLE
About mutli index of search

### ISSUE THREAD

**Issue by h3idan** [elastic/elasticsearch-dsl-py#236]
![image](https://cloud.githubusercontent.com/assets/2220393/9158817/b4932fae-3f4f-11e5-9469-5d5052802b30.png)

Why do this use *index?  Parameter index is list that's more convenient when intput parameter

**Comment by HonzaKral** [comment]
I feel like: `s = s.index('index1', 'index2')` is much more convenient than having to specify extra characters (`s = s.index(['index1', 'index2'])`) and it doesn't detract from anything - if you have indices in a list just pass them in using the `*` operator: `s = s.index(*my_index_list)`.

**Comment by h3idan** [comment]
thx @HonzaKral
