### ISSUE TITLE
Typo in Persistence docs

### ISSUE THREAD

**Issue by dchaplinsky** [elastic/elasticsearch-dsl-py#239]
https://github.com/elastic/elasticsearch-dsl-py/blob/master/docs/persistence.rst

```from elasticsearch_dsl import DocType, String, Date, Nested, Boolean, analysis```
should read as
```from elasticsearch_dsl import DocType, String, Date, Nested, Boolean, analyzer```

**Comment by HonzaKral** [comment]
Thanks for the report!
