### ISSUE TITLE
How to implement a count like _count in elasticsearch with elasticsearch_dsl over python

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#241]
How I can do a query to count all parameters from an index accoding to a specific query. I want to say I do not know do this query with elastichsearch_dsl:

GET my_index/my_type/_count
{
"query": {
"match_all": {}
}
}

for example we have as result this:

{
"count": 2472,
"_shards": {
"total": 5,
"successful": 5,
"failed": 0
}
}

Thanks in advance

**Comment by HonzaKral** [comment]
there is a `count` method to do this, it returns the number of matching docs:

    from elasticsearch_dsl import Search
    s = Seacrh(index='my_index', doc_type='my_type')
    s = s.query(...)
    print(s.count())

Hope this helps.
