### ISSUE TITLE
Getting results from different index

### ISSUE THREAD

**Issue by mochawich** [elastic/elasticsearch-dsl-py#246]
I have two DocType's: ShoutIndex and LocationIndex. Sometimes doing a query like:

```python

ShoutIndex.search().execute()
```
would result in:

```
<Response: [<Result(shoutit_api_prod_location/location_index/551ed422-1789-4ebb-9b2c-a6cb0395db4f): {u'city': u'Dubai', u'country': u'AE', u'source': u'GoogleLo...}>, <Result(shoutit_api_prod_location/location_index/9803418f-5dfa-45e5-9f34-5b709aff9c4e): {u'city': u'Dubai', u'country': u'AE', u'source': u'GoogleLo...}>, <Result(shoutit_api_prod_location/location_index/8d318d43-a642-4d7f-8a75-9314833da4c5): {u'city': u'Dubai', u'country': u'AE', u'source': u'GoogleLo...}>, <Result(shoutit_api_prod_locatio...
```

The type of returned results is Result class not ShoutIndex, the results are coming from location index and obviously they did map to a ShoutIndex. The same happens when querying the LocationIndex it sometimes returns results from ShoutIndex. This scenario is I would say very rare, but it for sure exists. The number of searches a day would be around 10k out of them some 20 have the mentioned issue.

Please advise me if there is something wrong I did, possibly in defining the DocTypes.

```python
class ShoutIndex(DocType):
    type = String(index='not_analyzed')
    title = String(analyzer='snowball', fields={'raw': String(index='not_analyzed')})
    text = String(analyzer='snowball')
    tags_count = Integer()
    tags = String(index='not_analyzed')
    category = String(index='not_analyzed')
    country = String(index='not_analyzed')
    postal_code = String(index='not_analyzed')
    state = String(index='not_analyzed')
    city = String(index='not_analyzed')
    latitude = Double()
    longitude = Double()
    price = Double()
    uid = String(index='not_analyzed')
    username = String(index='not_analyzed')
    date_published = Date()

    class Meta:
        index = settings.ENV


# initiate the index if not initiated
try:
    ShoutIndex.init()
except RequestError:
    pass
except ConnectionTimeout:
    error_logger.warn("ES Server is down.", exc_info=True)
```

and 

```python
class LocationIndex(DocType):
    source = String(index='not_analyzed')
    location = GeoPoint()
    country = String(index='not_analyzed')
    postal_code = String(index='not_analyzed')
    state = String(index='not_analyzed')
    city = String(index='not_analyzed')
    address = String(index='not_analyzed')

    class Meta:
        index = settings.ENV + '_location'


# initiate the index if not initiated
try:
    LocationIndex.init()
except RequestError:
    pass
except ConnectionTimeout:
    error_logger.warn("ES Server is down.", exc_info=True)

```

**Comment by HonzaKral** [comment]
It looks like you are initiating the search from `ShoutIndex` and getting results of the type `LocationIndex` therefore they don't match and you don't get the proper wrapping.

The matching of es type <-> `DocType` subclass is done via the doc type name in elasticsearch, it must match the `DocType`s name - you can find that by looking at `ShoutIndex._doc_type.name`

**Comment by mochawich** [comment]
About the matching I know but how come results come from different index if the search was initiated by a ShoutIndex class?
What makes it complicated is that the same search call succeeds about 99.9% of the time.

**Comment by HonzaKral** [comment]
It really depends how you index data into elasticsearch. You have defined `LocationIndex` and `ShoutIndex` as pointing to differend indices by default (`settings.ENV` VS `settings.ENV + '_location'`) but that doesn't necessarily mean that those types of documents only exist in these indices.

To find out what is your distribution it is easies to run a search like this:

    s = Search(index=settings.ENV)
    s.aggs.bucket('doc_types', 'terms', field='_type')

and then examine the results:

    result = s.execute()
    print('In index %s there are following types:' % settings.ENV)
    for b in result.aggregations.doc_types.buckets:
        print(b.key, b.doc_count)

This should give you an overview of what kind of documents you can find in your indices. (just run the same per index)

Hope this helps

**Comment by mochawich** [comment]
Thank you for the help, I really appreciate it. I ran the given lines and got these results:
For Shout
```
In index ENV there are following types:
(u'shout_index', 208659)
```
and for Location:
```
In index ENV_location there are following types:
(u'location_index', 62267)
```

I am running ES on a 4GB Ram server, that is dedicated only for ES service. I never touched the default configuration since first installed it. Yesterday I changed the heapsize to 2GB as recommended by Elasticsearch. For first time and even with +15000 queries on both indexes my logs recorded 0 errors. Beside the results from different index, I used to also get ConnectionTimeout and SerializationError (this one is very rare). 

As you can see, the number of indexed Shouts is +200k, so possibly the default configurations (256mb / 1gb) for min / max memory usage was causing ES to act weird.

**Comment by HonzaKral** [comment]
I am not sure what is happening, but the results from the first example clearly shows results from index `shoutit_api_prod_location` so I am not sure what happened there.

Could you please also run:

    print(ShoutIndex._doc_type.index)
    s = ShoutIndex.search()
    print(s._index)

then, if it's still not clear what's going on try configure logging for elasticsearch to see the actual requests being sent to ES:

    import logging
    logging.basicConfig(level=logging.DEBUG)
    #execute your search here

Thanks!

**Comment by mochawich** [comment]
Sorry for my late reply but I upgraded to ES 1.7 and waited to see if the bug will ever occur again. As checking the logs always resulted in corrected queries. Since the upgrade I stopped seeing these errors. I will report if any but I guess I can close the issue for now.
