### ISSUE TITLE
Enable storing payloads in Completion field

### ISSUE THREAD

**Issue by martinzugnoni** [elastic/elasticsearch-dsl-py#249]
Sorry guys, I'm not sure if I'm not using it in the correct way or it's just not supported. I would like to use a `Completion` field but enabling the storing of payloads.

Setting the completion field like this:
```
brand = Object(
    properties={
      'id': String(index='not_analyzed'),
      'name': String(),
      'suggest': Completion()
    }
)
```
is converted into this mapping:
```
"suggest": {
    "type": "completion",
    "analyzer": "simple",
    "payloads": false,
    "preserve_separators": true,
    "preserve_position_increments": true,
    "max_input_length": 50
}
```

What I would need to do is change somehow the field definition to set `"payloads": true` in the mapping.

Thanks!

**Comment by HonzaKral** [comment]
It should be enough to just say `Completion(payloads=True)` in your brand.suggest field.

**Comment by martinzugnoni** [comment]
I'm sure I've tried that before and didn't work, but tried it again and it's working now :). Probably did something wrong before. Thanks man.

Closing this ticket...
