### ISSUE TITLE
"Proper" way to handle defaults & validation of fields

### ISSUE THREAD

**Issue by andybarilla** [elastic/elasticsearch-dsl-py#252]
Given a class like below, is there a better way to handle default values or validation of a field.

I found the 'clean' function which can handle validation at the document level which will work for the allowed values validation in the example but the field.clean() will throw an error for the timestamp first.

Also, is there an abbreviated way to check if a field is there other than ```if hasattr(self, 'status') and self.status is not None:```

```python
DEFAULT_STATUSES = ('ok', 'bad', 'meh')

class MyClass(DocType):
    timestamp = Date(required=True)
    status = String(required=True)

    if hasattr(self, 'status') and self.status is not None:
        if self.status not in ALLOWED_STATUSES:
            raise AttributeError(
                'status %s not in enumerated set' % self.status)

    def save(self, **kwargs):
        if not hasattr(self, 'timestamp') or self.timestamp is None:
            self.timestamp = datetime.utcnow()
        return super(MyClass, self).save(**kwargs)

    class Meta:
        index = 'myindex'
```

**Comment by HonzaKral** [comment]
I just pushed an example of how this could be done in c751ab10cef4f4dd89a54aaa6f55402a7a7cca6a (see the test in that commit).

To test the presence of value you can now do simply `if not self.timestamp:` check in your `save` method. For the `status` check you can also just do (in your `clean` method or in a custom field's `clean`): `if self.status not in ALLOWED_STATUSES: raise ValidationError(...)`

Hope this helps.
