### ISSUE TITLE
Parent/Child Relationship Questions

### ISSUE THREAD

**Issue by andybarilla** [elastic/elasticsearch-dsl-py#253]
I have an existing ES mapping that looks something like this:

```javascript
{
  "my_index" : {
    "aliases" : { },
    "mappings" : {
      "my_parent" : {
        "properties" : {
          "description" : {
            "type" : "string"
          },
          "my_child" : {
            "properties" : {
              "category" : {
                "type" : "string"
              },
              "name" : {
                "type" : "string",
                "fields" : {
                  "untouched" : {
                    "type" : "string",
                    "index" : "not_analyzed"
                  }
                }
              }
            }
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "creation_date" : "1441741753592",
        "uuid" : "jrNdJiZwTv-ZD9nbiwGPyg",
        "number_of_replicas" : "1",
        "number_of_shards" : "5",
        "version" : {
          "created" : "1070199"
        }
      }
    },
    "warmers" : { }
  }
}
```

And I would like to migrate the homegrown model objects that we're currently using to this library's persistent objects.

I'm not sure how to create my objects because other code needs to create the MyChild and MyParent objects independently and also have initialization parameters like so:

```python
c = MyChild('child name', 'child category')
c.name = 'changed child name'

p = MyParent()
p.name = 'parent name'
p.my_child = c
p.save()
```

Note that the objects are not nested and are a 1:1 relationship. This is related to a previous question I had, https://github.com/elastic/elasticsearch-dsl-py/issues/160, but that doesn't fulfill my other needs of being able to create the child object independently of the parent.

Is there a way for the elasticsearch-dsl objects to handle this? 

Here's the code I was working with:

```python
from elasticsearch_dsl import *


class MyChild(InnerObjectWrapper):
    # def __init__(self, name, category):
    #     self.category = category
    #     self.name = name

    def clean(self):
        # we're also going to have do some verification here
        pass


class MyParent(DocType):
    description = String()
    my_child = Object(
        doc_class=MyChild,
        properties={
            'category': String(),
            'name': String(fields={'untouched': String(index='not_analyzed')})
        }
    )

# This works
p1 = MyParent()
p1.name = 'parent #1 name'
p1.my_child.category = 'child category'
p1.my_child.name = 'child #1 name'

# This doesn't
c2 = MyChild('child name', 'child category')
c2.name = 'changed child name'

p2 = MyParent()
p2.name = 'parent name'
p2.my_child = c2
p2.save()
```

**Comment by HonzaKral** [comment]
The inner objects need to be instantiated with a pointer to the fields mapping so it's non-trivial to do it yourself. What you can do instead is:

    p2 = MyParent(my_child={'category': 'child category', 'name': 'child name'})

or just assign the dictionary to the field:

    p2 = MyParent()
    p2.my_child = {'category': '...', 'name': '...'}

Hope this helps.

**Comment by andybarilla** [comment]
Thanks

I still need the MyChild object so here's how I'm getting around this in my case. Note the one thing that doesn't work is modifying the data in the wrapper doesn't update the MyChild object but it doesn't apply in my case.

```python
from elasticsearch_dsl import *
from elasticsearch_dsl.connections import connections


class MyChild(dict):
    def __init__(self, name, category):
        dict.__init__(self, {'category': category, 'name': name})

    def __getattr__(self, item):
        if item in self.keys():
            return self[item]

    def __setattr__(self, key, value):
        self[key] = value
        

class MyChildWrapper(InnerObjectWrapper):
    def clean(self):
        self.name = self.name.lower()


class MyParent(DocType):
    description = String()
    my_child = Object(
        doc_class=MyChildWrapper,
        properties={
            'category': String(),
            'name': String(fields={'untouched': String(index='not_analyzed')})
        }
    )

    class Meta:
        index = 'my_index'

connections.create_connection(hosts=['127.0.0.1'])

c2 = MyChild('CHILD NAME', 'child category')

p2 = MyParent()
p2.name = 'parent name'
p2.my_child = c2
p2.save()

# The wrapper doesn't update the source data
print(p2.my_child.name)
print(c2.name)
```

**Comment by HonzaKral** [comment]
But you always get back the `MyChild` object, even with the two approaches I showed. Just accessing `p2.my_child` will get you a valid `MyChild` instance. You can just get it empty or use the dict in `__init__` to seed it with data. Is that no enough? Why do you need the instance of `MyChild` outside of the parent?

**Comment by andybarilla** [comment]
It's because of a poor ES store that I inherited. In my real world case, MyChild is actually the parent record and is not normalized. There are numerous celery tasks that get passed the MyChild record which is then assigned to MyParent.

**Comment by HonzaKral** [comment]
Ah, what I would suggest then is getting the `MyChild` from an empty `MyParent` and working with that. It is not ideal, but it should work in your situation:

  my_child = Parent().my_child
