### ISSUE TITLE
ConnectionTimeout caused by - ReadTimeoutError using the get method from DocType

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#256]
Hi, 

Nowadays I have an elasticsearch cluster and the health of this cluster is correct: 

epoch     timestamp cluster status node.total node.data shards pri relo init unassign 
1441960748 10:39:08  juan    green           5         4    400 200    0    0        0 

And in the same node where I have the master elasticsearch node I am doing the data injection and I am taking data from elasticsearch. 

Sometimes when I am using elasticsearch-dsl-py in  with the next instruction:

taked_job = job().get(id=mimir_job["id"],parent= mimir_job["user"].encode('utf-8'),routing= mimir_job["customer"].encode('utf-8'),index=index_gompute,ignore=404)

This is giving me this error:

ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'bc10-05', port=9200): Read timed out. (read timeout=40))

And I am not able to understand it because this programm is running in the same node where the elasticsearch master node resides and the  my cluster node health is good like we could test initially.

First of all  I modified the connection definition increasing the time out but this appears not to be the solution:

connections.create_connection(hosts = [cluster],timeout=40)

Please could somebody tell something about this. 

Thanks in advance.

**Comment by HonzaKral** [comment]
Can you, from the same host, run `curl http://bc10-05:9200` ? It looks like there might be something wrong with your name resolution.

**Comment by juandasgandaras** [comment]
Yes, I have not problem doing this:

  curl http://bc10-05:9200

and the request is: 
  {
    "status" : 200,
    "name" : "Libra",
    "cluster_name" : "juan",
    "version" : {
      "number" : "1.4.4",
      "build_hash" : "c88f77ffc81301dfa9dfd81ca2232f09588bd512",
      "build_timestamp" : "2015-02-19T13:05:36Z",
      "build_snapshot" : false,
      "lucene_version" : "4.10.3"
    },
    "tagline" : "You Know, for Search"
  }


I checked again the cluster health and I get:

  epoch      timestamp cluster status node.total node.data shards pri relo init unassign 
  1442212471 08:34:31  juan    green           5         4    420 210    0    0        0 

and the  distribution nodes is:

  host    ip         heap.percent ram.percent load node.role master name                   
  bc10-03 10.8.5.13            19          27 0.00 d         m      Gypsy Moth             
  bc10-05 10.8.5.15            17          17 0.09 d         m      Jon Spectre            
  l8a     10.8.0.231           14                  c         -      logstash-l8a-5920-4018 
  bc10-05 10.8.5.15            20          17 0.09 d         *      Libra                  
  bc10-03 10.8.5.13            13          27 0.00 d         m      Arachne

**Comment by juandasgandaras** [comment]
I was thinking about to use a structure like this:

while attempts < Number of reintents :
    try:
        get (my element)
        .....  
        break
    except e:
        attempts += 1
        print "Elasticsearch Error Error %d: %s" % (e.args[0], e.args[1])

and define my connection like:

connections.create_connection(hosts = [cluster],timeout=10)

instead of 40 s timeout.

**Comment by HonzaKral** [comment]
The retry logic you are describing is already part of `elasticsearch-py` which is used by this library.

unfortunately I cannot replicate the problem - it looks just like a network issue where the connection is simply timing out and it is being correctly reported.

**Comment by juandasgandaras** [comment]
Yes, but I cannot understand why. 

I think that it is not a network problemm  but may it could be a congestion problemm ??

**Comment by HonzaKral** [comment]
It is a timeout occurring on the network. It could be that the network is unresponsive or the server (in that case, however, curl wouldn't work either).

Either way this is outside of the python client and there is nothing we can do. We already provide the ability to set timeout and number of retries. I'd suggest you configure the client to connect to multiple nodes to minimize the problems either directly or using the sniffing mechanism (http://elasticsearch-py.readthedocs.org/en/master/index.html#sniffing)

**Comment by juandasgandaras** [comment]
Thanks for your help it´s so grateful.

**Comment by juandasgandaras** [comment]
One question more, nowdays I have this configuration 
connections.create_connection(hosts = [cluster],timeout=10,sniff_on_start=True, sniff_on_connection_fail=True, sniffer_timeout=60,sniff_timeout=10)

I think that this configuration it is enough but sometimes this fails and I do not know. The fail is:

ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'10.8.5.13', port=9200): Read timed out. (read timeout=10))

But I think that it is no posible because the injection is done  in the same place that in the elasticsearch cluster and the fail talk about another node in the cluster. 

I was thinking if the problem would be related with the parent/child relation, because in this case I am saving a structure that it would be a grand child for example:

customer  ====>  linux_user   ====>  job

And the customer it is the parent linux user and the linux user  is the parent job. The number of job instances it is so big and it is updated every 20 seconds approximately.

**Comment by HonzaKral** [comment]
This problem has nothing to do with your data or how you use elasticsearch, it is a simple network timeout. It is caused when the client cannot connect to ip `10.8.5.13`. This IP address was mostly likely introduced via sniffing when the client, at the begininning, asked the cluster for a list of nodes and then started load balancing across those.

Everything I see here is correct, only your network is timing out.

**Comment by juandasgandaras** [comment]
Thanks a lot. 

But then the solution maybe it would be to increase the time out to avoid this problemms or to play with the values of timeout, sniff_on_start, sniff_on_connection_fail, sniffer_timeout and sniff_timeout until I have not this type the of problemms because when I do:

  curl http://bc10-05:9200

I have not connection problems. 

Thanks for your help

**Comment by HonzaKral** [comment]
The connection issues can be intermittent so if curl works doesn't guarantee that it works all the time. 

Increasing the timeout should help, but in the end that's probably not what you want - your application waiting for such a long time for the response.

Also this timeout is for `10.8.5.13` and not `bc10-05` hostname.

**Comment by juandasgandaras** [comment]
Another question about this fail. 

If I have this configuration:

 `es = Elasticsearch(cluster,timeout=10,sniff_on_start=True, sniff_on_connection_fail=True, sniffer_timeout=60,sniff_timeout=10,max_retries=10)`

where cluster is defined in this form:

`cluster = ['bc10-03:9200','bc10-05:9200','bc10-07:9200']`

and then why does this error:

`ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'bc10-05', port=9200): Read timed out. (read timeout=40))
`
if there are more host to connect??

Thanks in advance

**Comment by abdullayev96** [comment]
hi how are you all i have a big problem 
HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /news (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028DB0054F10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
