### ISSUE TITLE
Nested Object not in ES causing error

### ISSUE THREAD

**Issue by andybarilla** [elastic/elasticsearch-dsl-py#258]
I have a DocType with an Object like so:

```python
class MyObject(DocType):
    nested_thing = Object(properties={'id: Long(), 'name: String()})
```

If I retrieve legacy data in which the value of the object is 'null' then I get the following error

```python
  File "/home/abarilla/.virtualenvs/iocdb/local/lib/python2.7/site-packages/elasticsearch_dsl/field.py", line 156, in _to_python
    return self._doc_class(self.properties, **data)
TypeError: type object argument after ** must be a mapping, not NoneType
```

I'm thinking that if data is None then None should be returned, or an empty object.

**Comment by HonzaKral** [comment]
Could I please ask you to try this on `master`? We have recently changed how we treat objects and empty values.

Thanks!

**Comment by andybarilla** [comment]
Nope. Same error.

**Comment by HonzaKral** [comment]
Thanks for the verification, should be fixed.

**Comment by andybarilla** [comment]
That does it. Thanks
