### ISSUE TITLE
make highlights available in Respose

### ISSUE THREAD

**Issue by eyurtsev** [elastic/elasticsearch-dsl-py#259]
Sorry if I am mistaken, but I think that 'highlights' are unavailable in the response object.

```
s = Search(using=client, index="blah") \
  .query("match", field1="some value") \ 
    .highlight('field1',  fragment_size=10)

response = s.execute()
```
I can't seem to access highlights in the response object.

**Comment by HonzaKral** [comment]
Thi highlights will be available in `hit.meta.highlights`, so all together:

    for hit in response:
        for fragment hit.meta.highlight.field1:
            print(fragment)

I will add a not to the docs.

**Comment by HonzaKral** [comment]
Done in 0a11a9c1a7f44422603ae252c1096967e2ad2558

Thanks for raising the issue!

**Comment by eyurtsev** [comment]
Thanks! It works! 

Here's why I wasn't able to find it:

```
print response[0].meta
```
returns

```
{u'index': u'edgar', 'doc_type': u'10k', u'score': 0.1299311...}
```

And 'meta' doesn't have keys().

**Comment by HonzaKral** [comment]
You can always call `to_dict()` to get the raw dictionary and look there. I didn't want to include `keys` and other methods that would limit the namespace.

What should actually work also is `dir(meta)` and also autocompletion in ipython and the likes.
