### ISSUE TITLE
Corrupted distfile

### ISSUE THREAD

**Issue by dlangille** [elastic/elasticsearch-dsl-py#260]
I'm finding a corrupted distfile.

If I grab http://codeload.github.com/elastic/elasticsearch-dsl-py/tar.gz/0.0.7?dummy=/elastic-elasticsearch-dsl-py-0.0.7_GH0.tar.gz and look at elasticsearch_dsl/__init__.py the first line start with 7rom, and it should be: from

The same issue is evident in https://github.com/elastic/elasticsearch-dsl-py/archive/0.0.7.tar.gz & https://github.com/elastic/elasticsearch-dsl-py/archive/0.0.7.zip

e.g:

```shell
$ head -1 __init__.py 
7rom .query import Q
```

To reproduce:

```shell
mkdir tmp
cd tmp
wget "https://codeload.github.com/elastic/elasticsearch-dsl-py/tar.gz/0.0.7?dummy=/elastic-elasticsearch-dsl-py-0.0.7_GH0.tar.gz"
gunzip 0.0.7\?dummy\=%2Felastic-elasticsearch-dsl-py-0.0.7_GH0.tar.gz
tar -xf 0.0.7\?dummy\=%2Felastic-elasticsearch-dsl-py-0.0.7_GH0.tar
cd elasticsearch-dsl-py-0.0.7/
head -1 __init__.py
```

**Comment by dlangille** [comment]
It appears the problem was fixed post release: https://github.com/elastic/elasticsearch-dsl-py/commit/1b7bac315d9c20ff44090ce1ac78ac5423c89629

Please, can we have a working distfile?

**Comment by HonzaKral** [comment]
Sorry about this, the `0.0.7` release was corrupted, please use the latest pypi release. It is the same code-wise.

Thanks!
