### ISSUE TITLE
tokenizer filters options

### ISSUE THREAD

**Issue by nahuelange** [elastic/elasticsearch-dsl-py#263]
Hi,
I couldn't find in the documentation how to pass parameters to the filters of my tokenizer, like for specific language stopwords or snowball.
It should be great to have it in documentation (and tell me how :-))

**Comment by HonzaKral** [comment]
If you want to add options to a token filter you need to essentially create your own to use:

    from elasticsearch_dsl import token_filter, analyzer
    my_stop = token_filter('my_stop', 'stop', stopwords=['a', 'b'])
    my_analyzer = analyzer('my_analyzer', tokenizer='keyword', filter=[my_stop])

It works exactly the same as tokenizers which are mentioned in the docs. I will update the docs to make it more explicit.
