### ISSUE TITLE
Boolean type doesn't exist in DocType class

### ISSUE THREAD

**Issue by AnderUstarroz** [elastic/elasticsearch-dsl-py#265]
I was trying to implement something similar to [the DocType example](http://elasticsearch-dsl.readthedocs.org/en/latest/persistence.html#doctype) from the documentation. But the boolean type  retrieves an error when trying to import (it does not exist).

```python
from elasticsearch_dsl import Boolean

class Post(DocType):
    title = String()
    created_at = Date()
    published = Boolean()
    ...
```
Error: **Unresolved reference 'Boolean'**

**Comment by njoannin** [comment]
Hi @AnderUstarroz 

Do you actually get that error when running your code? Or is it something you get in your editor? For instance PyCharm does that, but it doesn't mean that it isn't there... The code will run without a problem.

If it is when running your code that you get this error, could you post the whole stack so we have more information to work with?

**Comment by AnderUstarroz** [comment]
You're right Pycharm is complaining but the import actually works, thanks. 

Actually maybe you can put some light in this other matter... I couldn't find anywhere in the documentation **how tokens can be customized in the DocType** wrapper. For instance many people may want to setup the [Stop token](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/analysis-stop-tokenfilter.html) for using different stopwords languages,  like `'_french_'`, `'_german_'`, ETC.  
This is not implemented?

**Comment by njoannin** [comment]
@AnderUstarroz I suggest that you close this issue and open another one with your new question. It is important to keep questions separate.

I haven't worked with tokens so I cannot answer this question. But I am sure others will be able to help.
