### ISSUE TITLE
Persistence Issue?

### ISSUE THREAD

**Issue by jredd** [elastic/elasticsearch-dsl-py#267]
Been looking through the documentation and I'm probably blind. Is there an kind of methodology of dealing with wanting all fields for the model to be saved to ES even if you didn't specifically set that field? So that if a field is empty it defaults to None or something like that? If that isn't really possible how should I go about dealing with issues of when I query a document and I ask for an attribute thats part of the model but not part of that particular doc? It currently errors out with an attribute error but I'd prefer to not have to litter my code with try except statements just to deal with this issue...

**Comment by HonzaKral** [comment]
Sorry for the delay. There is currently no automatic way of saving the empty values into elasticsearch, but there is a way to have a field return an empty value when accessed. It should be enabled by default:

  
    from elasticsearch_dsl import DocType, String

    class A(DocType):
        s = String()
        
    a = A()
    a.s
    
Is this what you wanted?

**Comment by jredd** [comment]
I guess I should explain a little. I'm working with an older dataset and we are updating it and dropping some fields from use while adding some new ones. I have a situation where some fields will exist while there is a chance that some wont. Is there method to have the object add a field as an attribute even if it doesn't exist in that particular doc but it's part of the model itself. 

So say I have the field is_active and it's a boolean value. The old documents do not have this field but any new ones coming in will. Now eventually I wont have to worry about this since the old docs will fall off from use in the system when they expire so it's a time thing of fixing something that eventually wont be there. Is there some way to have it just add the attribute for the documents that are missing the field so I don't have to litter my code full of try excepts dealing with the attribute error thats currently the default. Right now if I have a list and it's setup with String(multi=True) even if the field doesn't exist but I call on the attribute I get back an empty list. Is there a way to get that for the other fields as well?

**Comment by HonzaKral** [comment]
I am afraid I don't understand what you mean, could you perhaps provide a code snippet demonstrating the behavior you would like to see?

Currently it is actually behaving as I understand is what you are asking for, if you have a field defined and it is not on the document you will get an empty value (`''` for `String`, `None` for the other fields and `[]` for fields with `multi=True`):

		from elasticsearch_dsl import DocType, String, Boolean

		class A(DocType):                                     
				s = String()
				b = Boolean()
		a = A()
		assert a.b is None


Could it also be that you are just using an old version?

**Comment by jredd** [comment]
I need to apologize. I was working on version 0.0.4 once I updated those issues went away!

**Comment by jredd** [comment]
I am curious though, before updating I could save a None value to a field and it would post to the doc. Why does it no longer do that? We have other applications (and languages) interfacing with ES and not being able to set a field to None is an issue for us... If I also set a field that had a value to None, dsl will also remove it from the doc... This will break other applications within our system.

**Comment by HonzaKral** [comment]
I am sorry, this is the current limitation of the library - when a field has a value of `None`, it is considered empty. The reasoning for that is that if you don't have a field and you access it (like you requested earlier, and many other people use it), you get back `None`. If you were also able to store `None` values, there would be no way to differentiate whether the field is there and is `None` or if it's missing.

Since it is a fairly rare use case, for people wanting to store `null`s in elasticsearch, we opted to just not allow that. You can always override the `to_dict` method of your documents to provide a different serialization logic. If there is something in that method that you'd like refactored for easier extending, please let me know.

For now I am closing this issue.
