### ISSUE TITLE
0.0.7 tag doesn't work

### ISSUE THREAD

**Issue by willkg** [elastic/elasticsearch-dsl-py#268]
The most recent version of elasticsearch-dsl is 0.0.8, but there's no tag for that in the repository. I suspect that the 0.0.8 version on pypi is the 0.0.7 tag, but with a build fix.

However, the 0.0.7 tag doesn't work. The first line of `elasticsearch_dsl/__init__.py` is:

```
7rom .query import Q
```

That kicks up a `SyntaxError`.

Further, in that file is `VERSION = (0, 0, 6)`.

My questions are two-fold:

1. Do the 0.0.7 and 0.0.8 releases on pypi come from the 0.0.7 tag in the repository?
2. If so, how is that possible? and If not, what's the actual commit(s) for those versions?

**Comment by willkg** [comment]
Seems like 1b7bac31 should be tagged with 0.0.8. That fixes the `7rom` thing and has the right `VERSION`.

**Comment by HonzaKral** [comment]
Yes, @willkg is right, I just pushed the tag, sorry for the inconvenience!

**Comment by willkg** [comment]
No worries! Thank you so much!
