### ISSUE TITLE
Analyzers only created at index level

### ISSUE THREAD

**Issue by AnderUstarroz** [elastic/elasticsearch-dsl-py#270]
According the [documentation](https://www.elastic.co/guide/en/elasticsearch/guide/current/_controlling_analysis.html#_default_analyzers) we should be able to create analyzers at field, type or index level. Looks like **elasticsearch-dsl** is just able to create them at index level, this behavior was completely unexpected. Let me explain better, when  I'm defining a DocType like the following:

```python
from elasticsearch_dsl import DocType, String, Analyzer, token_filter


class User(DocType):
    class Meta:
        index = 'test_index'

    name = String(required=True, analyzer=analyzer(
                'german_analyzer',
                tokenizer="standard",
                filter=["standard",
                        "lowercase",
                        token_filter('german_snowball',
                                     type='snowball',
                                     language='German'),
                        token_filter('german_excluded_words',
                                     type='stop',
                                     stopwords='_german_')
                ]))

user = User(name= 'Jaime Williams')
user.meta.id = 1
user.save()

```
After running this code what I am actually expecting is the **german_analyzer** being created at the field level. Type "**user**" is created into the "**test_index**" and the document containing '*Jaime Williams*' as well, but the analyzer was not created at all.  Nonetheless if I create the index and type at the same time using the **Ingex()** class:
```python
from elasticsearch_dsl import Index


test_index = Index('test_index' )
test_index.doc_type(User)
test_index.delete(ignore=404)
test_index.create()
```
It worked! but the analyzer was created only at the Index level. It can be seen at [http://localhost:9200/test_index/_settings](http://localhost:9200/test_index/_settings).  This library is great, but this approach is quite limited and the result completely unexpected.

**Comment by njoannin** [comment]
You need to initialize the class before indexing anything:

```
class User(DocType):
    class Meta:
        index = 'test_index'

    name = String(required=True, analyzer=analyzer(
                'german_analyzer',
                tokenizer="standard",
                filter=["standard",
                        "lowercase",
                        token_filter('german_snowball',
                                     type='snowball',
                                     language='German'),
                        token_filter('german_excluded_words',
                                     type='stop',
                                     stopwords='_german_')
                ]))
```

Then you do:

```
User.init()
```

And then you do:

```
user = User(name= 'Jaime Williams')
user.meta.id = 1
user.save()
```

If I'm not mistaken, that should do it.

**Comment by AnderUstarroz** [comment]
You are right again! oh god,  I wasted so many hours... In the [persistence section of the documentation](http://elasticsearch-dsl.readthedocs.org/en/latest/persistence.html) this is not even mentioned.
