### ISSUE TITLE
results.to_dict() ignores nested documents

### ISSUE THREAD

**Issue by Schwankenson** [elastic/elasticsearch-dsl-py#271]
When I call execute() on a search object and convert the Result object with to_dict() to a dictionary, then the nested docs of the queried documents in _source are not in the dict.

When I do this on a DocType derived object instance, than it`s the same. Is this by design? How do I get the nested parts of the document as dict without hacky conversion functions?

**Comment by HonzaKral** [comment]
I cannot seem to replicate this issue, I tried also in 23023ced14e0831ed15d40ae26425f73a8535738 but without success, could you post in some example code of what you are doing please?

Thanks!

**Comment by andybarilla** [comment]
I had the same problem with nested docs. The issue, if I remember correctly, was with how I defined them.

Originally I had something like this:
```python
    def get_sub_type():
        return Object(properties={'name'}, String())

    class MainObject(DocType):
        document = get_sub_type()

    class AnotherMainObject(DocType):
        document = get_sub_type()
```

That didn't work when I loaded an object from a search and tried to access the property like this: objinstance.document.name however objinstance.document['name']

Since I only had that sub type in two objects I just canned the function and defined the sub object directly in the object instead.

```python
    class MainObject(DocType):
        document = Object(properties={'name'}, String())

    class AnotherMainObject(DocType):
        document = Object(properties={'name'}, String())
```

Not sure if it's the same problem or not and excuse and syntax errors in the pseudo code.

**Comment by HonzaKral** [comment]
I cannot seem to replicate your issues, when I do:

    from elasticsearch_dsl import Object, DocType, String
		class MyType(DocType):
				author = Object(properties={'name': String()})

        class Meta:
            index = 'i'

    MyType.init()
		mt = MyType()
		mt.author.name = 'Me!'
    mt.save()

Everything works just fine:

		mt.author.name # 'Me!'
		mt.to_dict() # {'author': {'name': 'Me!'}}

    hit = MyType.search.execute()[0]
		hit.author.name # 'Me!'
		hit.to_dict() # {'author': {'name': 'Me!'}}

With `Nested` it works exactly the same, except the `author` field is a list by default.

Could you please provide a code snippet that replicates your issues?

Thanks!

**Comment by Schwankenson** [comment]
Sorry for the delay:

I did something like:

	class StatisticsBase(DocType):
	    public_ip = String(index='not_analyzed')
	    ip = String(index='not_analyzed')
	    tokens = Nested(
	        properties={
	            'slug': String(index='not_analyzed'),
	            'status': String(index='not_analyzed'),
	            'position': Integer(),
	        }
	    )

	    def save(self, **kwargs):
	        self._doc_type.init(self.meta.index)
	        return super(DocType, self).save(**kwargs)     

	class StatisticsClick(StatisticsBase):
	    url = String(index='not_analyzed')
	    position_in_results = Integer()

	class StatisticsSearch(StatisticsBase):
	    start = Integer()
	    count = Integer()    

This example did not work until I added the save function to StatisticsBase, because the mapping was bot applied. And with the not applied mapping, I did not get the nested fields.

But maybe it is not supported to inherit new classes from DocType?

**Comment by HonzaKral** [comment]
Just defining the type won't create the mapping in ES, you need to explicitly ask for it, Either by calling `MyDocType.init()` or by creating an `Index` object and calling `create` on it - http://elasticsearch-dsl.readthedocs.org/en/latest/persistence.html#index
