### ISSUE TITLE
Meta fields missing in mapping

### ISSUE THREAD

**Issue by 0x64746b** [elastic/elasticsearch-dsl-py#275]
Hi guys,

due to https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/mapping.py#L90 meta fields like [`dynamic`](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-dynamic-mapping.html) are missing when getting a `Mapping.from_es()`.

Is this the intended behaviour?
Thx!

**Comment by HonzaKral** [comment]
That wasn't the expected behavior, thanks for the report!
