### ISSUE TITLE
Are there plans to support bulk indexing?

### ISSUE THREAD

**Issue by asyncee** [elastic/elasticsearch-dsl-py#277]
Hello, are there any plans to support bulk indexing/updating of persisted objects?

Also, which approach more preferable when you need to do some bulk documents indexing? Are there  best practices?

**Comment by HonzaKral** [comment]
yes, definitely. Currently the best practice is to use the helpers from `elasticsearch-py`:

    from elasticsearch.helpers import streaming_bulk

    for ok, info in streaming_bulk(es, (d.to_dict(True) for d in DOCUMENTS)):
        print("Document with id %s indexed." % info['index']['_id'])

In the future I might abstract this into a classmethod on `DocType` or something similar.

Hope this helps.

**Comment by asyncee** [comment]
Thank you! I will write my own indexing layer based on this solution. Closing.
