### ISSUE TITLE
iterating over Search (without .execute()) will eat all your memory

### ISSUE THREAD

**Issue by starenka** [elastic/elasticsearch-dsl-py#279]
I suppose this a `ProgrammingError`, nevertheless I think this should be fixed. Basically if you try to iterate over a `Search` object which wasn't executed, it will (I think) stuck in an infinite loop and it's trying to eat all you memory, lunch and then sets your fridge one fire. Take this example:

    from elasticsearch import Elasticsearch
    from elasticsearch_dsl import Search

    c = Elasticsearch()

    c.indices.create(index='my-index', ignore=400)

    c.index(index="my-index", doc_type="test-type", id=42, body={"any": "data", }, refresh=True)
    c.index(index="my-index", doc_type="test-type", id=43, body={"any": "body", }, refresh=True)
    c.index(index="my-index", doc_type="test-type", id=44, body={"any": "time", }, refresh=True)
    c.index(index="my-index", doc_type="test-type", id=45, body={"any": "how", }, refresh=True)
    c.index(index="my-index", doc_type="test-type", id=46, body={"any": "where", }, refresh=True)

    qry = Search(using=c, index='my-index').filter('term', any='time')
    q1 = qry.execute()

    assert len(q1) == 1

    for i, one in enumerate(qry, 1):
        print i, one

running this, you will get:

    (tmp-96bb94e953698a92)starenka /prac/python/elasticsearch-dsl-py master at aae0edf? % /usr/bin/time -v python leak.py
    1 <elasticsearch_dsl.search.Search object at 0x7fcba07f1490>
    2 <elasticsearch_dsl.search.Search object at 0x7fcba07f16d0>
    3 <elasticsearch_dsl.search.Search object at 0x7fcba07f1810>
    4 <elasticsearch_dsl.search.Search object at 0x7fcba07f1950>
    ....
    1360 <elasticsearch_dsl.search.Search object at 0x7fcba05a0990>
    1361 <elasticsearch_dsl.search.Search object at 0x7fcba05a0850>
    1362 <elastics^C
    Traceback (most recent call last):
      File "leak.py", line 24, in <module>
        print i, one
    KeyboardInterrupt
    Command exited with non-zero status 1
            Command being timed: "python leak.py"
            User time (seconds): 0.18
            System time (seconds): 0.02
            Percent of CPU this job got: 16%
            Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.29
            Average shared text size (kbytes): 0
            Average unshared data size (kbytes): 0
            Average stack size (kbytes): 0
            Average total size (kbytes): 0
            Maximum resident set size (kbytes): 17072
            Average resident set size (kbytes): 0
            Major (requiring I/O) page faults: 0
            Minor (reclaiming a frame) page faults: 4870
            Voluntary context switches: 62
            Involuntary context switches: 1881
            Swaps: 0
            File system inputs: 0
            File system outputs: 0
            Socket messages sent: 0
            Socket messages received: 0
            Signals delivered: 0
            Page size (bytes): 4096
            Exit status: 1
  
On my 6 years+ old laptop with 8GB ram, you can end up swapped to death before you even realized what you have done. Can we raise an exception on such usage (f.e. it is already done while negative indexing is used)? I'm sorry for not providing neither patch or test right now. Cheers

**Comment by HonzaKral** [comment]
Sorry about your fridge.

The problem is with `__getitem__` which we use to implement pagination. Iterating over an object with it implementing will try passing in indices. In this case it will result in Search endlessly cloning itself.

Possible solution is to use different method for pagination, implementing `__iter__` which would silently execute or which would raise an exception.

Unless there are compelling reasons fornother behavior I lean towards the last solution...

**Comment by starenka** [comment]
That is what I was thinking . I was looking into `__getitem__`, but couldn't come up with a good enough solution which would detect the query wasn't executed yet (and raise). Also it seemed to me a bad place to check it. Honestly I was looking for `__iter__` at the `Search` object at first and then forgot about it after diving into `__getattr__`. 

I understand this is my fault, but one is so used to such behavior using other APIs (Django f.e.)...

**Comment by marcinn** [comment]
My proposal is to execute search when trying to iterate over Search object, same as Django`s QuerySet is reading database: https://github.com/django/django/blob/master/django/db/models/query.py#L243 

Only when Search is empty the result should be also empty or should raise an exception.

Iterating over Search same as on QuerySet would be very handy.

**Comment by HonzaKral** [comment]
Djngo queryset is very different in that it doesn't have any other result but the individual records to iterate over. A Search request can return many other things (total count, aggregations, suggestions, ...). If `__iter__` were to execute search, would we strip these out (same way we do when doing count), ignore or have the response then be cached? If cached (seems most sensible) then how do we then manage the cache? When is it invalidated?

**Comment by marcinn** [comment]
Maybe `__iter__` should be a shortcut for `iter(self.execute())` (Response is iterable, AFAIK).
Result from `execute()` can be cached in Search (`self`) instance. This should work until every query change will instantiate new Search object (clone).

**Comment by marcinn** [comment]
As a continuation I've tried simple workaround by using my IterableSearch class inherited from Search:

```
class IterableSearch(Search):
    def __iter__(self):
        try:
            return iter(self._cached_result)
        except AttributeError:
            self._cached_result = self.execute()
            return iter(self._cached_result)
```

It seems to be working, but it requires good testing. The caching, for example, is used only when calling `__iter__`. Maybe should be implemented in `execute()`?

```
class IterableSearch(Search):
    def __iter__(self):
        return iter(self.execute())

    def execute(self):
        try:
            return iter(self._cached_result)
        except AttributeError:
            self._cached_result = super(IterableSearch, self).execute()
            return iter(self._cached_result)
```

Currently I don't know about any side effects of caching, but as I said above - it requires some testing.

**Comment by HonzaKral** [comment]
My only concern here is that right now it is possible to have a search object, keep it around and call `.execute` on it repeatedly to get updated results. Naturally that's not a huge problem and can probably be solved by documentation, possibly also an option to skip the cache when calling `execute`..

**Comment by willkg** [comment]
Maybe put the iterable functionality into a mixin that someone could use to create an iterable search easily? Has there been other behaviors that we didn't want to put in `Search` that might be good for mixins, too?

**Comment by marcinn** [comment]
There will be another problem in places where `Search` is instantiated, i.e. in `Index.search`. Maybe these factories should be configureable with some `search_class` property, which defaults to `Search`. In the other side this can generate a property overriding horror-story ;) It depends how many factories are.

**Comment by HonzaKral** [comment]
I don't think a mixin is a way to go here - it wouldn't solve the original problem. I think we can just implement this on the default `Search` class, essentially what @marcinn posted here.

Thanks for the discussion and patience, this has been a long time in the todo list - since #10

**Comment by starenka** [comment]
Cheers!
