### ISSUE TITLE
Is there possibility to remove AttrDict-like magic wrappers?

### ISSUE THREAD

**Issue by marcinn** [elastic/elasticsearch-dsl-py#283]
I see strange behaviour:

```
from elasticsearch_dsl.utils import AttrDict

class MyObject(AttrDict):
    def test(self):
        self._d_ = 'something'
````

And test `_d_` replacement:

```
In [11]: obj = MyObject({'a': 1, 'b': 2})
In [12]: obj._d_
Out[12]: {'a': 1, 'b': 2}

In [13]: obj.test()

In [14]: obj._d_
Out[14]: {'_d_': 'something', 'a': 1, 'b': 2}
```

The `_d_` property is not overridden, but `something` is added as a new property.
This is very strange.

**Comment by HonzaKral** [comment]
Sure, just call the `to_dict()` method on those and you will get the raw dict. Can you provide a use case where you need this?

Thanks!

**Comment by marcinn** [comment]
Yes, I know I can get raw dict. But I can't modify internal state of AttrDict. When trying to replace `_d_` object, the value from simple assignment `self._d_ = "value"` is treated as new property of old `_d_`, not replacement of `_d_` property. Even `setattr` does not work. This is "strange" from Python language perspective.

I'm implementing cleaning data from keys which were not defined in DocType. I can workaround this by mutating original `_d_` object by using `del` keyword.

Also accessing some information from Mapping is quite hard, because `mapping.to_dict()` returns a dictionary prepared for ElasticSearch API, where I need to read `keys()` of that mapping:

```
 In [8]: doc._doc_type.mapping.to_dict()
Out[8]: 
{'my_doc_type': {'properties': {'default_picture': {'type': 'string'},
   'description_html': {'type': 'string'},
   'id': {'type': 'integer'},
   'name': {'type': 'string'},
   'price': {'type': 'float'}}}
```

Finally I've found a proper access sequence: `doc._doc_type.mapping.properties.properties.to_dict().keys()`.  But please note that `doc._doc_type.mapping.to_dict()` gives same result as `doc._doc_type.mapping.properties.to_dict()`, which is another case of confusion.

That's why I think that Attr* wrappers makes less or more confusion. According to Zen Of Python (PEP20) I would like to suggest simplyfing some things and make them more clear.

**Comment by HonzaKral** [comment]
So you are trying to clean data. Why can't you do that through the `AttrDict` - it supports iteration just like `dict` and you shouldn't need to modify the dict in place. Though if you do, you can get the raw dict by calling `to_dict` and then modify that - `AttrDict` is just a wrapper and it's `to_dict` just returns the underlying dictionary, it doesn't copy it.

As for the field access, what would be the desired API? Just get a list/dict of fields?

**Comment by marcinn** [comment]
> So you are trying to clean data. Why can't you do that through the AttrDict - it supports iteration just like dict and you shouldn't need to modify the dict in place. 

I've created class which extends DocType and override clean(), and I wasn't able to change its internal state by replacing internal dict (`_d_`) because of `__setitem__` magic. I can iterate over AttrDict and delete specified keys, but assigning properties to AttrDict class is impossible. Everything, any assignment, goes into internal `_d_` dictionary.

Please also note that mapping any key to object property can result with no possibility of accessing specified data. Just look at this example:

```python
]: obj = AttrDict({'del': True})
]: obj.del
obj.del
      ^
SyntaxError: invalid syntax
```
 
The "reserved" keywords list may be long. I had an issue, where I've been sending json data to fellow`s service written in .NET. He is using a library which maps keys to object properties. After some tests he aksed me to rename several keys due to syntax errors on his side... It's sometimes fun, but mostly not...

That's why when I'm working on data transfer objects, I'm trying to use dedicated types/structures. A simple `dict` is enough to do job well.

When I'm thinking about transfer objects with well-know structure or any objects holding properties (like meta/properties/etc), I'm going tu use native namedtuples or to use dedicated plain/pure classes (object type) with properties defined explicite. I'm using classes when some additional methods are required.
 
But what can I suggest in general? The less magic, the better...

Kind Regards,
Marcin.

**Comment by HonzaKral** [comment]
I am fully aware of the limitations of the approach. Another example would be fields with characters not permitted by python (like `@timestamp` used by logstash). But note that even with the words like `del` you can make it work by using the dict syntax like you are doing, so the only thing you are denied is the convenience of attribute approach. By definition there is no way around this.

I am still unsure why the current approach is limiting in any way to what you are trying to do. You have described several solutions you have tried, but not the problem itself, could you please describe that?

Thanks!

**Comment by marcinn** [comment]
> I am still unsure why the current approach is limiting in any way to what you are trying to do. You have described several solutions you have tried, but not the problem itself.

Let's separate two things. I can access what I need and I can modify AttrDict to do my cleaning with solutions described before. This is first.

But second is about convention used in AttrDict and similar classes, which may be "buggy" in some cases. As a Python programmer, not only ES/ES-dsl "user", I see some kind of anti-patterns )maybe anti-patterns, I don't know all). And my intention is to do software good/better/stable/simpler - name as you wish. :) According to PEP20: "simple is better than complex" and "explicit is better than implicit". This is more about how you write Python apps than about some problem to solve. 
 
I can agree that attribute access is sexy ;) and I was doing similar wrappers over dicts years ago, but it does not work for every case. And please note that I had some trouble with AttrDict, and that trouble was a result of The Magic applied behind the scenes. This is an origin of this issue, or more precisely - the question. So when you decide to drop magic, I can do some nasty-magic-removal-patch with pull request :)

Cheers!
Marcin

**Comment by marcinn** [comment]
Heh... I thought that we met at PyConPL 2009, but I was in 2010. So maybe next time... ;)

**Comment by HonzaKral** [comment]
I will gladly drop any magic as long as we can still have attribute access (even for fields that are not defined) and automatic (de)serialization of `Object`, `Nested` and `Date` fields. What we can do here is to skip the 'magic' for protected attributes (with leading underscores) in the case of `DocType`, that would probably eliminate much of the pain.

I do agree that magic is to be avoided, but in this case it is necessary, it is even the point of this library - to provide convenience. If you want the safe and explicit way, there is always `elasticsearch-py`. I would argue that the code written with the dsl is much simpler than any using the low-level client. I hold to the belief that it is the purpose of libraries, frameworks and other tools to make things easier for developers. In this case it means perhaps doing some magic so that the application code can be simple and explicit.

It is the same for other tools out there that they use (what some may call) anti-patterns to enable clean code for the users. Take a look at django models for example.

**Comment by marcinn** [comment]
> What we can do here is to skip the 'magic' for protected attributes (with leading underscores) in the case of DocType, that would probably eliminate much of the pain.

I think that is a minimum what should be done here. Accessing "protected" attrs without magic will give more control over objects provided by ES-DSL. So +1 :)

> I will gladly drop any magic as long as we can still have attribute access (even for fields that are not defined) 

Well, you're probably talking about all classes that inherits from AttrDict, especially about DocType. When you wrote about django models I got your point of view, I think. 

Yes, django models mapping is also limited, but models have static schema and model properties (field values) are pure attributes of the object, collected via getattr while saving. No magic here, AFAIK.

> I do agree that magic is to be avoided, but in this case it is necessary, it is even the point of this library - to provide convenience.

Probably I don't know all use cases. That's why I didn't know that is necessary.  I thought that was included for some simplifications only. 

> I hold to the belief that it is the purpose of libraries, frameworks and other tools to make things easier for developers. 

I asked question and wrote my thoughts from a library developer perspective, not regular user of ES-DSL, after some problems with manipulating DocType internally. 

Thanks for clarification and patience! 

Cheers,
Marcin

**Comment by HonzaKral** [comment]
> Yes, django models mapping is also limited, but models have static schema and model properties (field values) are pure attributes of the object, collected via getattr while saving. No magic here, AFAIK.

This is actually not the case, the fields are descriptors assigned to the class by a metaclass upon its definition; yet in the cass definition you see Field objects being assigned to those names. A lot of "magic" there actually, but it is invisible to the user, which is exactly the point.

I will consider adding the option to allow underscored attributes on `DocType` I am not entirely sold on the idea because there is no reason for the limitation and fields in elasticsearch documents can easily start with underscores.

In the mean time I am closing this issue, thanks for the discussion!

**Comment by marcinn** [comment]
> yet in the cass definition you see Field objects being assigned to those names. A lot of "magic" there actually, but it is invisible to the user, which is exactly the point.

I know how it works, I think. Field definition resides in meta, but field values ale bound to object (model) as a primitive values or object instances. 

Metaclass programming is not magic, IMO. But changing language semantics is.

Thanks for discussion, too!
