### ISSUE TITLE
django - elasticsearch question

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#284]
Could I use this library to work over a django project? or I would need to use other libraries like 
http://elasticutils.readthedocs.org/en/latest/django.html to work with django and elasticsearch at the same time?

Thanks in advance

**Comment by artursmet** [comment]
This library can be used with django. There is an example: https://github.com/HonzaKral/es-django-example
You don't need any third party librares like elasticutils

**Comment by juandasgandaras** [comment]
ok thanks because I was thinking about to use haystack or third party libraries and rewrite all code

**Comment by nostalgiaz** [comment]
@artursmet this bug is closed, isn't it?

**Comment by juandasgandaras** [comment]
yes
