### ISSUE TITLE
Search not wrapping results into objects

### ISSUE THREAD

**Issue by wanthalf** [elastic/elasticsearch-dsl-py#285]
I cannot get results of search wrapped as the persistent object types. I tried both MyClass.search() and Search().doc_type(MyClass) as well as both iterating over the response and response.hits, but I only get strings or AttrDict objects. What am I doing wrong?

**Comment by HonzaKral** [comment]
I cannot say without a code example and some information. Namely what is the name of the type in elasticsearch, does it match the name of the DocType?

**Comment by wanthalf** [comment]
Problem found: modified class init did expect another input format than the actual document in its current form. So, the problem actually seems to be that there was no Exception raised to tell let me know (as finally happened when I tried MyClass.get(...)!), elasticsearch-dsl just quietly gave up the object conversion - I suppose this is on purpose for other circumstances where it may be desirable...?

**Comment by HonzaKral** [comment]
Again, without code it is absolutely impossible to answer any of your questions. How did you modify the class?

**Comment by wanthalf** [comment]
OK. I had to change attribute 'attr' from a basic dict field (key: value) to nested field with {'name': key, 'value': value}. Because of compatibility with other scripts I added this into MyClass.init():

        # if 'attrs' in kwargs:
        #     attrs = []
        #     for k, v in kwargs['attrs'].items():
        #         attrs.append({'name': k, 'value': v})
        #     kwargs['attrs'] = attrs

It was backwards compatible, but failed on re-creation from internal data. I suppose I could also solve this by testing whether the input 'attrs' are a list or a dict, and so the init() would be compatible with both input formats.

But still - should the user not be warned at least, that the creation of the object failed?

**Comment by HonzaKral** [comment]
Can you please post the entire code of the method? Also what do you mean it "failed" n recreation? This should have thrown an exception, didn't it?

**Comment by wanthalf** [comment]
No exception. I get exception from Object.get(), but not from Object.search().execute().

Tak jo:
```
attr_field = Nested(
    properties={
        'name': field.String(index='not_analyzed'),
        'value': field.String(index='not_analyzed')
    }
)

class CType(DocType):
    attrs = attr_field

    def __init__(self, **kwargs):
        if 'attrs' in kwargs:
            attrs = []
            for k, v in kwargs['attrs'].items():
                attrs.append({'name': k, 'value': v})
            kwargs['attrs'] = attrs
        super().__init__(**kwargs)
```

In this configuration I get no exception from Search:

```
>>> s = CType.search()
>>> s = s.filter('nested', path='attrs', filter={"bool":{"must":[{"term":{"attrs.name":"word"}},{"term":{"attrs.value":"-"}}]}})
>>> r = s.execute()
>>> type(r.hits[0]).__name__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/elasticsearch_dsl/utils.py", line 115, in __getitem__
    return _wrap(self._d_[key])
KeyError: 0
>>> for i in r:
...  print(type(i).__name__)
... 
str
str
str
```

When removing the quoted block from the init(), the results are as expected:

```
>>> s = CType.search()
>>> s = s.filter('nested', path='attrs', filter={"bool":{"must":[{"term":{"attrs.name":"word"}},{"term":{"attrs.value":"-"}}]}})
>>> r = s.execute()
>>> type(r.hits[0]).__name__
'CType'
>>> for i in r:
...  print(type(i).__name__)
... 
CType
```

Moje chyba, samozřejmě, ale trvalo mi, než jsem na to přišel, že si to nemůžu takhle dovolit.
Každopádně moc díky za tenhle skvělý balíček!

**Comment by HonzaKral** [comment]
This is a problem with the `hits` property on `Response` class. Since it's a property and `AttributeError` raised while accessing it (in this case cause by trying to access `items` on list by your `__init__`) will trigger `Response.__getattr__` which will in turn just return the contents of the `hits` key of the raw response.

I think the correct solution would be to try and catch `AttributeError` in the property and re-raise it as `TypeError` or don't try and do the wrapping in the property (lazily) and instead do it in `Response.__init__`. This will mean some extra overhead for people not interested in search results. I am ok with that since I don't see a use case for it (just set size to 0 if you don't want results back).

What do you think?

**Comment by wanthalf** [comment]
Honestly, I cannot really follow the internal processes that far at the moment. But you decide. For me the conclusion is just that the DocType init method must accept the document source, which makes perfect sense.

BTW, can we expect adaptation to the new ES 2.0 API changes soon? (e.g. merge of query and filters, aso. - I know, it's tiring...)
