### ISSUE TITLE
find a bug in elasticsearch-dsl.pdf

### ISSUE THREAD

**Issue by Qinwenchao** [elastic/elasticsearch-dsl-py#288]
https://media.readthedocs.org/pdf/elasticsearch-dsl/latest/elasticsearch-dsl.pdf
page:5

article = Article(id=42, title='Hello world!', tags=['test'])
article.body = ''' looong text '''
article.published_from = datetime.datetime.now()
article.save()

article = Article.get(id=42)   
print(article.is_published())

raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, u'{"_index":"blog","_type":"article","_id":"43","found":false}')

i modified the code as below:

article = Article(_id=42, title='Hello world!', tags=['test'])
article.body = ''' looong text '''
article.published_from = datetime.datetime.now()
article.save()

article = Article.get(id=42)   
print(article.is_published())

and the problem solved.

**Comment by HonzaKral** [comment]
Thank you for the report!
