### ISSUE TITLE
Query on range of date return fixed number of result output then using kibana

### ISSUE THREAD

**Issue by Vikran** [elastic/elasticsearch-dsl-py#289]
Hello Honza, 

I am really hoping if you could help me understand whats going wrong.
I have with "lucene_version" : "4.10.4" with Kiabana 4.

I am ingesting logs and data in ES:
From Kiabana interface 24 hours query looks like following where i am querying for "batchspoiled" 
discover?_g=(time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'item_query:"batchspoiled.weather"')),sort:!('@timestamp',desc))

In script i am using :-
s= Search(using=es).filter('term', item_query="batchspoiled.weather").filter('range' ,  **{'@timestamp': {'gte': 'now-24h' , 'lt': 'now'}})

with Kibana i get 6000+ hits while with script i only get 10.

{
  "_index": "logstash-2015.11.08",
  "_type": "batch",
  "_id": "AVDlvFZkpyVaEtKIxLkV",
  "_score": null,
  "_source": {
    "message": "batchspoiled because of reason# weather",
    "@version": "1",
    "@timestamp": "2015-11-08T06:15:36.399Z",
    "type": "batch",
    "file": "/batch/log/batches.log",
    "item_q": "(batchspoiled.weather)",
    "item_query": "batchspoiled.weather",
  }

Regards,
Vik

**Comment by HonzaKral** [comment]
By default all searches from elasticsearch will only return top 10 results. If you want more, just specify the size:

    s = Search(using=es).filter(....)
    s = s[0:1000]

Alternatively, if you want to return all the documents, use the `scan` method:

    for doc in s.scan():
        print(s)

Hope this helps.

**Comment by Vikran** [comment]
Hey Honza,

1st thanks for the module its time saver and super useful. considering i hate writing json queries.
2nd i really appreciate you responding so quick that too on sunday :)

Appreciate your help.

Cheers,
