### ISSUE TITLE
Date fields not be deserialized in search Result objects?

### ISSUE THREAD

**Issue by tdenmark** [elastic/elasticsearch-dsl-py#292]
Hi --

Say we have a simple mapping with a Date in it:

```
from elasticsearch_dsl import Date
from elasticsearch_dsl import DocType
from elasticsearch_dsl import String

class MyDocType(DocType):
    class Meta:
        doc_type = 'my_doc_type'
        index = 'my_index'
    my_date = Date()

MyDocType.init()
```

Then i create a document of that type in that index:

```
import datetime

MyDocType(my_date=datetime.datetime.now()).save()
```

When i query via the DocType code path the datetime is correctly deserialized to a datetime:

```
>>> MyDocType.get(id='AVDtqKAKpe1kU9rnpSPl').my_date
datetime.datetime(2015, 11, 9, 11, 11, 2, 665947)
```

However, when i query via the Search code path the datetime is deserialized as a string rather than a datetime:

```
>>> Search().filter('term', _id='AVDtqKAKpe1kU9rnpSPl').execute()[0].my_date
u'2015-11-09T11:11:02.665947'
```

Is there a reason for this?  Shouldn't that "my_date" attribute of the Result object be a datetime?

Thanks!

**Comment by HonzaKral** [comment]
When you are doing a search and you want to return `DocType` instances, you need to ask for it, we don't keep any registry of existing `DocType` subclasses:

    Search().doc_type(MyDocType).execute()[0].my_data

should do the trick. Alternatively if you are only using a single `DocType` you can do `MyDocType.search().execute()`

Hope this helps

**Comment by tdenmark** [comment]
Thanks for the tip.  When I distilled my actual code down to the simplified sample code above I neglected to narrow the search down to the doc type in question -- sorry!

The way I had been specifying doc_type still does not work;  however, the second approach you suggest above does work.  If you invoke the sample code above with the following two kinds of doc_type specifications, see how the first still doesn't deserialize to a datetime, but the second does:

```
>>> Search().doc_type('my_doc_type').filter('term', _id='AVDyUcBGpe1kU9rnpSP1').execute()[0].my_date
u'2015-11-10T08:54:15.365566'
>>> MyDocType.search().filter('term', _id='AVDyUcBGpe1kU9rnpSP1').execute()[0].my_date
datetime.datetime(2015, 11, 10, 8, 54, 15, 365566)
>>>
```

I'll switch our code to use the latter, but figured I'd report back that the former doesn't seem to be deserializing correctly.

Thanks for all your work on elasticsearch-dsl!  We're in the process of migrating from Haystack to this project and are excited that you're actively engaged.

**Comment by HonzaKral** [comment]
This is by design - in the first case we have no information about the mapping so we don't know what fields to deserialize into datetime. That is one of the reasons why you should be using the `DocType`. You can use it also in the same way you'd use the string: `Search().doc_type(MyDocType).filter('term', _id='AVDyUcBGpe1kU9rnpSP1').execute()`

**Comment by tdenmark** [comment]
ah, okay.  got it.  make sense.  thanks for the tip and for the explanation.
