### ISSUE TITLE
[Question] Custom Token Filter

### ISSUE THREAD

**Issue by jonathan-ku** [elastic/elasticsearch-dsl-py#294]
Some elasticsearch plugin requires a use of custom token filter. Is it supported?

Will adding the plug-in name to the TOKEN_FILTERS set be a good/safe workaround?

**Comment by HonzaKral** [comment]
I am afraid I don't understand the question - you want to use a token filter supplied by a plugin? Then the easiest way is to just use a string with its name and everything will work.

**Comment by jonathan-ku** [comment]
In the setting, I need to setup the custom token filter. 
```
"filter": {
    "custom_filter": {
        "type": "custom_filter",
        "other_param": "val"
    }
}
```
When I tried ```token_filter('customer_filter')``` I got the following error 
```UnknownDslObject: DSL class 'custom' does not exist in token_filter.```

**Comment by HonzaKral** [comment]
Ah, in that case you need to create your own `TokenFilter` subclass:

    class MyCustomTokenFilter(TokenFilter):
        name = 'custom_filter'

and then you's be able to either use it directly or create derived filters by calling `token_filter('custom_filter', other_param='val')`

**Comment by jonathan-ku** [comment]
ok, i got it now. 
I have to pass in the type for token_filter too by using ```token_filter('custom_filter_name', type='custom_filter', other_param='val')```
