### ISSUE TITLE
talking to _suggest endpoint?

### ISSUE THREAD

**Issue by pcompassion** [elastic/elasticsearch-dsl-py#295]
elasticsearch doc talks about 

```The suggest request part is either defined alongside the query part in a _search request or via the REST _suggest endpoint.```

I'm trying to implement autocomplete and what I want is the `_suggest` endpoint.
Yet I was unable to find how to talk to the endpoint using elasticsearch-dsl-py.

If I'm mistaken, please let me know.

**Comment by HonzaKral** [comment]
Hi, this is currently not possible. I am trying to implement it now and am deciding between two possible interfaces - either we have a separate `Suggest` class with its `.execute` method. Alternatively we can just add a much simple `run_suggest` method on the existing `Search` object which would just run the suggestions and ignore the rest of the `Search`.

What do you think is better? The second approach has an advantage that, in the future, filtered suggestions might be available so it would be a natural progression of the API.
