### ISSUE TITLE
Suggest field mapping confuguration

### ISSUE THREAD

**Issue by jungornti** [elastic/elasticsearch-dsl-py#296]
Hello, i can do following with curl, but not in the code:

curl -X PUT localhost:9200/music
curl -X PUT localhost:9200/music/song/_mapping -d '{
  "song" : {
        "properties" : {
            "name" : { "type" : "string" },
            "suggest" : { "type" : "completion",
                          "analyzer" : "simple",
                          "search_analyzer" : "simple",
                          "payloads" : true
            }
        }
    }
}'

How can i specify "suggest" parameters for a field mapping?

**Comment by HonzaKral** [comment]
Yes, there is a `Completion` field:

    class MyType(DocType):
        suggest = Completion(analyzer='simple', payloads=True)

Hope this helps.

**Comment by jungornti** [comment]
Thank you. Closing.
