### ISSUE TITLE
minimum_should_match for 'match' query?

### ISSUE THREAD

**Issue by johnraz** [elastic/elasticsearch-dsl-py#300]
Hi again,

I tried hard to reproduce the example here: https://www.elastic.co/guide/en/elasticsearch/guide/current/match-multi-word.html#match-precision

But I cannot find a way to make it work...

This is what I have so far:

```
ArticleDoc.search().query(
    Q('bool',
         must=[es_Q(Match(query=query_str, field='all_text', minimum_should_match='25%'))],
         should=[es_Q('match_phrase', all_text=query_str)],
         minimum_should_match=0
    )

)
```

NB: the `minimum_should_match` applied to the `bool` is working as expected.

**Comment by HonzaKral** [comment]
you need to use `Q('match', all_text={'query': query_str, 'minimum_should_match': '25%'})` - just stay true to the json example, just turn all top-level keys into keyword arguments.

**Comment by johnraz** [comment]
Awesome, I knew I was missing a huge spot :-)

Thanks a lot !
