### ISSUE TITLE
How to select specific fields in search query

### ISSUE THREAD

**Issue by vi3k6i5** [elastic/elasticsearch-dsl-py#302]
Support is there on Elasticsearch https://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-request-fields.html

how to do the same with elasticsearch-dsl-py ??

**Comment by korkmaz** [comment]
@vi3k6i5 
```python 
from elasticsearch_dsl import search
search.Search().fields(['fielda', 'fieldb'])

search.Search().partial_fields(foo={
        'include': ['foo.bar.*'],
        'exclude': ['foo.one']
    })
```
https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_search.py#L352
https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_search.py#L393

**Comment by vi3k6i5** [comment]
Thanks man. It's not there in the documentation any where. We should add it i guess ?

**Comment by apandita** [comment]
Its there, look at this doc

http://elasticsearch-dsl.readthedocs.org/en/latest/

and search for this text:

"# fields that should be searched"



On Thu, Nov 19, 2015 at 2:38 PM, Vikash Singh <notifications@github.com>
wrote:

> Thanks man. It's not there in the documentation any where. We should add
> it i guess ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch-dsl-py/issues/302#issuecomment-157995630>
> .
>



-- 
Warm Regards!
Amit Pandita
+91-9650308350

**Comment by vi3k6i5** [comment]
@apandita no its not there. The issue i raised is not how to search in a particular field. It's rather how do i specify which fields to be returned in from elasticsearch-dsl. That piece is missing from the documentation.

**Comment by vi3k6i5** [comment]
@korkmaz @apandita : One question off this topic. I want elasticsearch-dsl to track_score. 
Basically this feature: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_track_scores
Any idea how to do that?
PS: let me know if i should be opening another issue for it.
Thanks :)

**Comment by apandita** [comment]
@Vikash When you pass an array of fields to the search, the result will
always be only those specific fields.

The link i pointed out was not really a direct reference but like a hint to
pick up how to filter fields.

On Thu, Nov 19, 2015 at 2:58 PM, Vikash Singh <notifications@github.com>
wrote:

> @korkmaz <https://github.com/korkmaz> @apandita
> <https://github.com/apandita> : One question off this topic. I want
> elasticsearch-dsl to track_score.
> Basically this feature:
> https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_track_scores
> Any idea how to do that?
> PS: let me know if i should be opening another issue for it.
> Thanks :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch-dsl-py/issues/302#issuecomment-158000700>
> .
>



-- 
Warm Regards!
Amit Pandita
+91-9650308350

**Comment by vi3k6i5** [comment]
@apandita : This is what is missing in the document:
search.Search().fields(['fielda', 'fieldb'])
That fields calls. its no where there. I Feel it should be added to the documentation. Let me know how i can help so this gets added to the documentation.
Thanks :)

**Comment by apandita** [comment]
@honza is the right guy to take a call on this :)


On Thu, Nov 19, 2015 at 3:06 PM, Vikash Singh <notifications@github.com>
wrote:

> @apandita <https://github.com/apandita> : This is what is missing in the
> document:
> search.Search().fields(['fielda', 'fieldb'])
> That fields calls. its no where there. I Feel it should be added to the
> documentation. Let me know how i can help so this gets added to the
> documentation.
> Thanks :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch-dsl-py/issues/302#issuecomment-158003609>
> .
>



-- 
Warm Regards!
Amit Pandita
+91-9650308350

**Comment by honza** [comment]
@apandita You got the wrong Honza :) cc @HonzaKral

**Comment by HonzaKral** [comment]
Thanks for bringing this up, I added a section in the docs.

**Comment by vi3k6i5** [comment]
@HonzaKral can you please share your commit id or merge id or some link. So i can directly see the changes you made (What changes you made and where exactly). I want to understand how you guys maintain documents so i can help as well :)

**Comment by HonzaKral** [comment]
The commit is tagged with this issue so you can see the link above, it's https://github.com/elastic/elasticsearch-dsl-py/commit/fab2f6bf4d665d776afcc47c8f796d51bbab78e8

Any help would be greatly appreciated!

**Comment by koorukuroo** [comment]
It was changed to `.source`
