### ISSUE TITLE
version 0.0.9 broke append method with multi=True

### ISSUE THREAD

**Issue by lesuspect** [elastic/elasticsearch-dsl-py#303]
This was working with 0.0.8 but not anymore with 0.0.9
```
from elasticsearch_dsl import DocType, String

class PipelineResult(DocType):

    tasks = String(multi=True)

    class Meta:
        index = 'pipeline_result'

    def log(self, task_id):
        self.tasks.append(task_id)
        self.save()

PipelineResult.init()
r = PipelineResult()
r.save()

r.log('123')
r.log('456')
r.log('789')

print r.to_dict()
```

**Comment by HonzaKral** [comment]
Thanks for the report, if you could just refrain from using such language it would be appreciated. There is no need for it.

**Comment by lesuspect** [comment]
Sorry about my badmouth!

**Comment by HonzaKral** [comment]
I understand the frustration, fix has been pushed along with a test for this, thanks again for the report

**Comment by lesuspect** [comment]
No real frustration here... just sticking to 0.0.8 meanwhile. Thanks!
