### ISSUE TITLE
ES Connection failure:  'module' object has no attribute 'create_connection'

### ISSUE THREAD

**Issue by xros** [elastic/elasticsearch-dsl-py#305]
I tried to use a dsl client to create a connection to ElasticSearch

And error came out

> es_session = connections.create_connection('connection1', hosts=[options.es_host], sniff_on_start=True, timeout=20)
> AttributeError: 'module' object has no attribute 'create_connection'

In the source codes, it did has an attribute named 'create_connection'. And I can use this module in iPython console. But not in my script. This is so weird. 

At here https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/connections.py#L60

Someone can fix it?

**Comment by HonzaKral** [comment]
It looks like you have the wrong import - it needs to be:

    from elasticsearch_dsl.connections import connections

**Comment by xros** [comment]
@HonzaKral thanks mate! It happens. I just found it. And it's all good now.
