### ISSUE TITLE
Need example for setting up routing using Meta class

### ISSUE THREAD

**Issue by marknv** [elastic/elasticsearch-dsl-py#308]
Hello, I can't find any example online of how to set up routing using elasticsearch-dsl-py. Given the example from [the official blog](https://www.elastic.co/blog/customizing-your-document-routing):
```bash
$ curl -XPUT 'http://localhost:9200/store/order/_mapping' -d '
{
   "order":{
      "_routing":{
         "required":true,
         "path":"customerID"
      }
   }
}'
```
How should I write it in python es-dsl?
```python
class Order(DocType):
    # some fileds
    class Meta:
        index = "store"
        # how to set up routing here? Do i say:
        _routing={'required': True, 'path': 'customerID'}
```

**Comment by HonzaKral** [comment]
the easiest way is to say:
 
    class Meta:
        routing = MetaField(required=True, path='customerID')

`MetaField` can be imported directly from `elasticsearch_dsl`:

    from elasticsearch_dsl import MetaField

Hope this helps

**Comment by marknv** [comment]
Thanks, that helps!

**Comment by martyzz1** [comment]
Would be useful to improve the docs on this... it took me some time to "guess" the syntax and then a precise google search https://www.google.com/search?q=%22routing+%3D+MetaField%22+elasticsearch&oq=%22routing+%3D+MetaField%22+elasticsearch&aqs=chrome..69i57.4975j0j4&sourceid=chrome&ie=UTF-8

Brings up this solitary result...

:) it would probably save people a lot. of time, if your. above suggestion appeared in the docs.
