### ISSUE TITLE
How to rescore a search?

### ISSUE THREAD

**Issue by lnabergall** [elastic/elasticsearch-dsl-py#311]
Is [rescoring](https://www.elastic.co/guide/en/elasticsearch/guide/current/_improving_performance.html#rescore-api) on searches supported? Something like:

```
Search().query("match", title="my title").rescore(window_size=50, ...)
```

**Comment by HonzaKral** [comment]
Currently it is not supported. You can however inject it yourself for now as a work around:

    s = Search()
    s = s.query(...)

    s.extra(rescore={'window_size': 50, "query": {"rescore_query": Q(...)}})

**Comment by lnabergall** [comment]
I see, thanks.

**Comment by FlorianWilhelm** [comment]
+1, would really love to see that in elasticsearch_dsl

**Comment by sethmlarson** [comment]
Rescoring is supported via `.extra()`
