### ISSUE TITLE
would be convenient if result class support count() for pagination

### ISSUE THREAD

**Issue by pcompassion** [elastic/elasticsearch-dsl-py#312]
I'm trying to get total count of result for pagination, and it seems not be supported atm.

`response._d_['hits']['total']`

**Comment by njoannin** [comment]
The search object has a count method: 

```
>>> s = MyDoc.search()
>>> count = s.count()
```

The results you get from executing the search will depend on what you ask for: by default it will only return up to 10 results. If you need more, or want to paginate, then you need to specify it:

If you want all the results at once:
```
>>> results = s[0: count].execute()
``` 

If you only need the 90th to the 100th (or is that the 99th? I forget...) result:
```
>>> results = s[90:100].execute()
```

Hope this helps!

**Comment by pcompassion** [comment]
Thanks, It helps a lot.

Btw, django paginator for instance takes list(able?) objects and paginate it,

So atm, I have to give Paginator a `Search` instance which supports slicing when instantiating a paginator.

Then when I need to actually get the object list, I need to execute the search and assign the result as in..

```
        if isinstance(self.page.object_list, Search):
            res = self.page.object_list.execute()
            hits = res.hits
            self.page.object_list = hits
        return list(self.page)
```

I can live with this, but just reporting the slight inconvenience.

**Comment by HonzaKral** [comment]
There is no need to do anything, django paginator works directly with the `Search` object:

    from elasticsearch_dsl import Search
    from django.core.paginator import Paginator

    s = Search()
    p = Paginator(s, 2)

    print(p.count)
    print(p.num_pages)

    for h in p.page(1).object_list:
        print(h)

Can you please verify, and if it's not the case reopen the issue?

Thanks!

**Comment by zahir-koradia** [comment]
@HonzaKral  I tried your approach.
``
p.page(1).object_list
``
is a search object and iterating through it also results in getting search objects. However,
``
p.page(1).object_list.execute():
``
works as desired. Please let me know if you need more information.

Thanks.

**Comment by HonzaKral** [comment]
Ah, have you tried master? The changes needed for this to work were introduced in 1d41adf

Sorry about the confusion. Release coming up soon

**Comment by zahir-koradia** [comment]
Ah, okay. Thanks for the clarification.

**Comment by pcompassion** [comment]
Thanks for the clarification!
