### ISSUE TITLE
from elasticsearch_dsl can't import MultiSearch

### ISSUE THREAD

**Issue by duobei** [elastic/elasticsearch-dsl-py#313]
In http://elasticsearch-dsl.readthedocs.org/en/latest/search_dsl.html, there is a code example about MultiSearch. But, from elasticsearch_dsl can't import MultiSearch.

Should the doc be updated?

**Comment by HonzaKral** [comment]
The docs reflect the situation in master, where this works. Once the new version is released to pypi it will be fine. In the mean time please use the docs for the stable version of the library where this paragraph is missing: http://elasticsearch-dsl.readthedocs.org/en/stable/search_dsl.html

Thanks for the report
