### ISSUE TITLE
GeoShape queries

### ISSUE THREAD

**Issue by zahir-koradia** [elastic/elasticsearch-dsl-py#316]
What is the cleanest way of doing GeoShape queries? So far I have
```
d = {
    'shape': {
        'type': 'point',
        'coordinates': [4, 52]
    }
}
s = Search().filter('geo_shape', field_name = d)
s.execute()
```
The dictionary has a lot of text one could move out to boiler plate. I was wondering if something like this has already been built or is being planned to be built.

**Comment by HonzaKral** [comment]
There is currently no better way unfortunately.

As of 508448e however, we do serialize any object that has a `to_dict` method. This should enable you to create your own `Point` class that will serialize correctly:

    class Shape(object):
        ...

    class Point(Shape):
        def __init__(self, x, y):
            self.x, self.y = x, y

        def to_dict(self):
            return {"shape": {"type": "point", "coordinates": [self.x, self.y]}}

Then you can write:

    s = Search().filter('geo_shape', location=Point(123, 456))

It is obviously not ideal to require all users to do things like this to get convenience. Ideally we would have a set of helpers like these as aprt of the library, it has just not yet come up.

Hope this helps.

**Comment by alexshires** [comment]
Hi, 

resurrecting the issue to keep the discussion in one place - has there been any work on this?

Regards,

Alex
