### ISSUE TITLE
dynamic_templates mapping fail 

### ISSUE THREAD

**Issue by ppiccolo** [elastic/elasticsearch-dsl-py#319]
Hi to all,

the following code fail to create index :
```python
dt = [
    {
        "template_1": {
            "match": "*",
            "match_mapping_type": "string",
            "mapping": {
                "type": "string",
                "index": "not_analyzed",
                "doc_values": True
            }
        }
    }
]

class BaseDocument(DocType):
    class Meta:
        dynamic = MetaField('strict')
        dynamic_templates = MetaField(dt)
```

with the following exception :

Caused by: org.elasticsearch.index.mapper.MapperParsingException: Root type mapping not empty after parsing! Remaining fields:   [_dynamic_template : [...........

bug is in the mapping.py at :

```python
META_FIELDS = frozenset((
    'dynamic', 'transform', 'dynamic_date_formats', 'date_detection',
    'numeric_detection', 'dynamic_templates'
))
```

you miss a comma (,) at the end of the frozenset 

change to :
```python
META_FIELDS = frozenset((
    'dynamic', 'transform', 'dynamic_date_formats', 'date_detection',
    'numeric_detection', 'dynamic_templates',
))
```

hope this help 

bye

**Comment by HonzaKral** [comment]
Thanks for the report, unfortunately I cannot replicate it. The code you supplied works for me just fine. Also the proposed change is a no-op in python.

Could you please provide more information as to what are you doing and what (and when) exactly goes wrong? Thanks!

**Comment by HonzaKral** [comment]
Closing this since I cannot replicate it and there has been no infomation for 12 days. Feel free to reopen with more information.

Thanks!
