### ISSUE TITLE
UnknownDslObject for geo_bounding_box

### ISSUE THREAD

**Issue by liran90** [elastic/elasticsearch-dsl-py#321]
When I am trying to send a query including a geo_bounding_box element I get this exception:
"elasticsearch_dsl.exceptions.UnknownDslObject
UnknownDslObject: DSL class `geo_bounding_box` does not exist in query."

when I delete this part of query it works well, needless to say - both queries(with or without the geo_bounding_box) were tested and works with curl, sending to the same ES server the code tries to send

I was migrating from elasticsearch-py and using Search.from_dict

**Comment by HonzaKral** [comment]
Thanks for the report. In the `2.0` branch the query is indeed missing. If you are, however, using Elasticsearch 1.x and any released version of `elasticsearch-dsl` then you must use the `geo_bounding_box` as a filter, not a query:

    s = Search()
    s = s.filter('geo_bounding_box', ...)

Hope this helps.

**Comment by liran90** [comment]
We are using Elasticsearch 2.1 unfortunately
I guess for a temporary solution I can use the underlying layer of elasticsearch-py for the geo_bounding_box query and it should work ?

**Comment by HonzaKral** [comment]
Yes, you can always drop down to the low level client or, if you are comfortable running off a branch, use the `2.0` branch where I just pushed a fix as 256e7e440ff6acf3f9e94ed798607998d54923ec

If you don't want to run off a branch you can create the query yourself by simply defining:

    class GeoBoundingBox(Query):
        name = 'geo_bounding_box'

and after this it should become availible.

**Comment by liran90** [comment]
thanks !
