### ISSUE TITLE
Space splitting strings

### ISSUE THREAD

**Issue by sm0k** [elastic/elasticsearch-dsl-py#326]
Hello, cant figure out why using piece of this code:

`s = Search(using=client, index="logstash-2016.01.21") \`
 `   .filter("term", event_type="alert") \`
`    .filter("term", ** {'alert.signature': 'SURICATA ICMPv6 unknown type'})`
`pp.pprint(s.to_dict())`

Space seams to split the strings:

Debug:
`{   'query': {   'filtered': {   'filter': {   'bool': {   'must': [   {   'term': {   'event_type': 'alert'}},`
`                                                                       {   'term': {   'alert.signature': 'SURICATA '`
`                                                                                                          'ICMPv6 '`
`                                                                                                          'unknown '`
`                                                                                                          'type'}}]}},`
`                                 'query': {'match_all': {}}}}}`

Am I wrong?

**Comment by HonzaKral** [comment]
Hi,

the string is not split, when you paste your debug example into python it is exactly what you would expect it to be. May I ask how you got the debug part? Thanks

btw you can use `.filter('term', alert__signature='SURICATA ICMPv6 unknown type')` for better readability

**Comment by sm0k** [comment]
Hi, thanks for your answer
debug is made simply using pp.pprint(s.to_dict()) .

I understand, but, the results are false:

Sample using .filter('term', alert__signature='SURICATA ICMPv6 unknown type')

Debug:
`{   'query': {   'filtered': {   'filter': {   'bool': {   'must': [   {   'term': {   'event_type': 'alert'}},
                                                                       {   'term': {   'alert.signature': 'SURICATA '
                                                                                                          'ICMPv6 '
                                                                                                          'unknown '
                                                                                                          'type'}}]}},
                                 'query': {'match_all': {}}}}}`


> 0 results

Sample using .query("match", alert__signature='SURICATA ICMPv6 unknown type')

Debug:
`{   'query': {   'filtered': {   'filter': {'term': {'event_type': 'alert'}},
                                 'query': {   'match': {   'alert.signature': 'SURICATA '
                                                                              'ICMPv6 '
                                                                              'unknown '
                                                                              'type'}}}}}`

> 3458 results

**Comment by HonzaKral** [comment]
well `match` query and `term` filter do very different things - when you do a match query elasticsearch is looking for an analyzed version of the text. On the other hand `term` filter looks for an exact match. Since by default all fields are analyzed at index time the term filter will not match, that is expected.

What is your desired behavior?

**Comment by sm0k** [comment]
Well, I'm a bit new to ELK. I now understand the differences between match and term and the analysis process made by elasticsearch, thank you. I have to setup my search in a different way I guess, using signature_id instead of signature, for example. 

Thank you for your help!

**Comment by HonzaKral** [comment]
Happy to help

**Comment by Allan-Nava** [comment]
How can I fix the problem with words with spaces? I need to search like query "a b" inside a specific field
