### ISSUE TITLE
defining custom analyzers

### ISSUE THREAD

**Issue by pkphlam** [elastic/elasticsearch-dsl-py#327]
Hi,

What is the proper way to define a custom analyzer for an index using elasticsearch_dsl?

I'm trying to run:

```
doc_analyzer = analyzer('doc_analyzer', tokenizer='standard', filter=['lowercase', 'stemmer'])
m = Mapping('bills')
m.field('Title', String(analyzer='doc_analyzer'))
m.save('index_bills')
```

and am getting the error:

```
RequestError: TransportError(400, 'mapper_parsing_exception', 'analyzer [doc_analyzer] not found for field [Title]')
```

Do I need to define the analyzer through settings somehow first? Thanks!

**Comment by HonzaKral** [comment]
Hi, all you have to do is pass in the actual analyzer, not just the name: 

    doc_analyzer = analyzer('doc_analyzer', tokenizer='standard', filter=['lowercase', 'stemmer'])
    m = Mapping('bills')
    m.field('Title', String(analyzer=doc_analyzer)) # note the missing quotes
    m.save('index_bills')

btw I would recommend using a `DocType` instead of `Mapping` directly

Hope this helps
