### ISSUE TITLE
Possible wrong version in elasticsearch-dsl documentation and data types in examples?

### ISSUE THREAD

**Issue by iwnijao** [elastic/elasticsearch-dsl-py#329]
Hello all.

I'm starting with elasticsearch-dsl in python but I can't find elasticsearch-dsl version 2.0. According to elasticsearch-dsl documentation I should use a matching major version:

# Elasticsearch 2.x
elasticsearch-dsl>=2.0.0,<3.0.0.

I was trying to test some documentation example but I couldn't find Integer datatype (Persistence Example from https://pypi.python.org/pypi/elasticsearch-dsl)

I'm using Elasticsearch 2.1.1 and I had installed elasticsearch 2.2.0 package, pip install elasticsearch_dsl downgrade elasticsearch package to <2.0.0,>=1.0.0 version.

Any help?

**Comment by alexgarel** [comment]
Same question here, is elasticsearch-dsl only compatible with ES 1.x yet ?

**Comment by dbzm** [comment]
The documentation is extremely misleading.  As @iwnijao mentions is tells us to use `elasticsearch-dsl>=2.0.0,<3.0.0`, but it seems that only the branch names follow the major version.  The PyPi releases are versioned 0.0.[1-11], with different `elasticsearch` version requirements for each.

Obviously, it'd be ideal if it worked with any version of `elasticsearch`, and if there was interest in pursuing that I'd be more than happy to help out, but if the approach is a like-versioned package (`1.x` and `2.x`) that should be reflected in the PyPi versioning as well.

**Comment by HonzaKral** [comment]
You are absolutely right, I was being optimistic when I wrote that, assuming I will have time to release `2.0` soon.

Currently `2.0` is a future release that will be spun off `master`. The existing releases are mostly compatible with Elasticsearch 2.0 - it doesn't support some of its features like pipeline aggregations and can in some cases generate invalid queries.

**Comment by jaddison** [comment]
... so, 2 questions:

1) is the 2.0.0 release imminent?
2) is it 'safe' to use the `master` branch in the meantime?

**Comment by HonzaKral** [comment]
2.0.0 has just been released. Thank you for your patience!
