### ISSUE TITLE
selected value is kept after a new search without filters

### ISSUE THREAD

**Issue by AdrianRibao** [elastic/elasticsearch-dsl-py#330]
When filtering a faceted search the results return a triplet like this: `(facet_name, count, selected)` with the value selected set properly if the search has been filtered by that facet.

After performing a new search without filtering by that facet, the `selected` value is kept to the old one, but all of them should be `False`

The `is_filtered(self, key)` method is checking if the key is set in `filter_values`

```
def __init__(self, **kwargs):
    self.filter_values = ()
    self._params = kwargs
```

but is never removed. Probably `filter_values` should be cleaned for each search.

**Comment by HonzaKral** [comment]
Can you please share the code how you are doing the search and performing new search? Thanks!

**Comment by HonzaKral** [comment]
Oh, I see what's going on. An embarrassing bug, thanks for reporting it!

**Comment by AdrianRibao** [comment]
That was fast! Thank you!

**Comment by HonzaKral** [comment]
It is also released as `0.0.11`, thanks again for the report!

**Comment by AdrianRibao** [comment]
I've already upgraded my requirements and I'm using it, thanks to you for the project.

I'm moving to elasticsearch-dsl and leaving haystacksearch for django. So I'll be using it a lot from now on.

What method do you recommend for testing it and sending PR? I guess that installing it in editable mode (https://pip.pypa.io/en/stable/reference/pip_install/?highlight=editable#editable-installs) is the way to go right?

For tests, are we are supposed to have a local installation of Elasticsearch?

**Comment by HonzaKral** [comment]
> What method do you recommend for testing it and sending PR? I guess that installing it in editable mode (https://pip.pypa.io/en/stable/reference/pip_install/?highlight=editable#editable-installs) is the way to go right?

probably, or just clone the repo and run the tests via `python setup.py test`, that should take care of installing the dependencies etc. For more options run the `run_tests.py` script in the test directory. The tests use `py.test` and support all the options (see `run_tests.py --help`)

> For tests, are we are supposed to have a local installation of Elasticsearch?

Yes, you should, but there are a lot of unit tests that can run without running elasticsearch instance (the tests requiring es will be skipped).

Also PRs will be tested automatically using Travis CI - https://travis-ci.org/elastic/elasticsearch-dsl-py/pull_requests

Finally, if you are using it with Django you can check out the example project - https://github.com/HonzaKral/es-django-example to see some best practices (please ignore the templates for now, html is not my strong point :) )
