### ISSUE TITLE
cumulative_sum aggregation does not exist?

### ISSUE THREAD

**Issue by alejoar** [elastic/elasticsearch-dsl-py#335]
I'm trying to make a date histogram with a cumulative sum aggergation.

This is one of my many tries:
```
ESUser.search().aggs.metric('by_day', 'date_histogram', field='member_since', interval='day').pipeline('test', 'cumulative_sum', buckets_path='by_day')
```

This raises AttributeError: 'Search' object has no attribute 'pipeline'

Another thing I tried:
```
ESUser.search().aggs.metric('by_day', 'date_histogram', field='member_since', interval='day').aggs.pipeline('test', 'cumulative_sum', buckets_path='by_day')
```

Which raises AttributeError: 'AggsProxy' object has no attribute 'pipeline'

Finally:
```
from elasticsearch_dsl import A
A('cumulative_sum', buckets_path='by_day')
```
raises UnknownDslObject: DSL class `cumulative_sum` does not exist in agg.

I'm using version 0.0.11.

Any help will be appreciated, thanks.

**Comment by alejoar** [comment]
Ok so I just realized the problem is that pipeline aggregations are not included in the latest release 0.0.11, although they are included in the documentation.

Is there a simple way to update from this repo or something? or is there a new release comming soon? I could really use these aggregations!

**Comment by alejoar** [comment]
Still stuck with this a day later.

I'd also appreciate if anyone knows  a way to do it with the current version. I've been trying with from_dict methods to no avail.

**Comment by HonzaKral** [comment]
Release is coming soon, just essentially waiting for some feedback on #325 since that is a big backwards incompatible change. Otherwise I would higly recommend that you run from master for the time being, nothing about this should change before the release.

I apologize for the inconvenience

**Comment by alejoar** [comment]
Thank you @HonzaKral.

For the time being, running for master is a bit of an inconvenience since we have several servers automated with fabric. On local I already started doing some tests with master and preparing for the migration.

As a suggestion, it would be cool to be able to target dev versions with pip.

**Comment by alejoar** [comment]
Hi @HonzaKral.

Thanks for the version bump!

I'm still having trouble trying to achieve my query. Can you please check it out?

```
s = ESUser.search()
s.aggs.bucket('by_day', 'date_histogram', field='member_since', interval='day').pipeline('test', 'cumulative_sum', buckets_path='by_day')
```

Basically I have a mapping for users with a "member_since" field. I want to build a graph with both number of users registered by interval (in the example above, by day) and an increasing cumulative sum that would show the total number of registered users at each interval.

When trying the code above I'm getting `No aggregation found for path [by_day]`

s.to_dict() shows:
```
{
	'query': {
		'match_all': {}
	},
	'aggs': {
		'by_day': {
			'date_histogram': {
				'field': 'member_since',
				'interval': 'day'
			},
			'aggs': {
				'test': {
					'cumulative_sum': {
						'buckets_path': 'by_day'
					}
				}
			}
		}
	}
}
```

which looks fine to me afaik, but still doesn't work. Any help appreciated!

**Comment by alejoar** [comment]
Ok I finally solved it. This is how it is done fora per-month basis, if anyone's wondering:

```
s = ESUser.search()
s.aggs.bucket('by_month', 'date_histogram', field='member_since', interval='month').metric('count', 'cardinality', field='user_id', precision_threshold=40000).pipeline('total_sign_ups', 'cumulative_sum', buckets_path='count')
```

Which returns something like this (aggregations field):
```
{
	u 'by_month': {
		u 'buckets': [{
			u 'count': {
				u 'value': 1600
			}, u 'total_sign_ups': {
				u 'value': 1600.0
			}, u 'key_as_string': u '2015-02-01T00:00:00.000Z', u 'key': 1422748800000, u 'doc_count': 1600
		}, {
			u 'count': {
				u 'value': 5664
			}, u 'total_sign_ups': {
				u 'value': 7264.0
			}, u 'key_as_string': u '2015-03-01T00:00:00.000Z', u 'key': 1425168000000, u 'doc_count': 5664
		}, {
			u 'count': {
				u 'value': 5377
			}, u 'total_sign_ups': {
				u 'value': 12641.0
			}, u 'key_as_string': u '2015-04-01T00:00:00.000Z', u 'key': 1427846400000, u 'doc_count': 5378
		}, {
			u 'count': {
				u 'value': 5716
			}, u 'total_sign_ups': {
				u 'value': 18357.0
			}, u 'key_as_string': u '2015-05-01T00:00:00.000Z', u 'key': 1430438400000, u 'doc_count': 5718
		}, {
			u 'count': {
				u 'value': 5452
			}, u 'total_sign_ups': {
				u 'value': 23809.0
			}, u 'key_as_string': u '2015-06-01T00:00:00.000Z', u 'key': 1433116800000, u 'doc_count': 5452
		}, {
			u 'count': {
				u 'value': 5464
			}, u 'total_sign_ups': {
				u 'value': 29273.0
			}, u 'key_as_string': u '2015-07-01T00:00:00.000Z', u 'key': 1435708800000, u 'doc_count': 5464
		}, {
			u 'count': {
				u 'value': 5624
			}, u 'total_sign_ups': {
				u 'value': 34897.0
			}, u 'key_as_string': u '2015-08-01T00:00:00.000Z', u 'key': 1438387200000, u 'doc_count': 5625
		}, {
			u 'count': {
				u 'value': 5412
			}, u 'total_sign_ups': {
				u 'value': 40309.0
			}, u 'key_as_string': u '2015-09-01T00:00:00.000Z', u 'key': 1441065600000, u 'doc_count': 5412
		}, {
			u 'count': {
				u 'value': 5649
			}, u 'total_sign_ups': {
				u 'value': 45958.0
			}, u 'key_as_string': u '2015-10-01T00:00:00.000Z', u 'key': 1443657600000, u 'doc_count': 5650
		}, {
			u 'count': {
				u 'value': 5504
			}, u 'total_sign_ups': {
				u 'value': 51462.0
			}, u 'key_as_string': u '2015-11-01T00:00:00.000Z', u 'key': 1446336000000, u 'doc_count': 5504
		}, {
			u 'count': {
				u 'value': 5623
			}, u 'total_sign_ups': {
				u 'value': 57085.0
			}, u 'key_as_string': u '2015-12-01T00:00:00.000Z', u 'key': 1448928000000, u 'doc_count': 5623
		}, {
			u 'count': {
				u 'value': 5655
			}, u 'total_sign_ups': {
				u 'value': 62740.0
			}, u 'key_as_string': u '2016-01-01T00:00:00.000Z', u 'key': 1451606400000, u 'doc_count': 5656
		}, {
			u 'count': {
				u 'value': 3503
			}, u 'total_sign_ups': {
				u 'value': 66243.0
			}, u 'key_as_string': u '2016-02-01T00:00:00.000Z', u 'key': 1454284800000, u 'doc_count': 3503
		}]
	}
}
``` 

If a per-day basis is needed, it looks like this:
```
s = ESUser.search()
s.aggs.bucket('by_day', 'date_histogram', field='member_since', interval='day').metric('count', 'cardinality', field='user_id', precision_threshold=40000).pipeline('total_sign_ups', 'cumulative_sum', buckets_path='count')
```
