### ISSUE TITLE
How to create a boosting query

### ISSUE THREAD

**Issue by vi3k6i5** [elastic/elasticsearch-dsl-py#336]
I was going through the documentation but i was not able to find and documentation regarding how to build a boosting query:

i was able to construct it till here:

```
Q('boosting', positive=Q("multi_match", query="hola", fields=["name", "family_name"], type="most_fields"),
              negative=F("missing", field="uid"))

```
But the negative part is not working. Anyone has any clue how to do this?

Another problem is how to have array of positive / negative boosters.

**Comment by levylll** [comment]
Excuse me, I just want to use the ‘boost’ parameter in my query buffer. Do you know how to use it? Thank you!

**Comment by HonzaKral** [comment]
@vi3k6i5 an array of boosters isn't supported in the boosting query. Also, could you elaborate on what you mean by the query not working?

For more flexibility I would also recommend you take a look at the function score query which is much more powerful.

@levylll I am afraid I do not understand your question either, would you have an example of what you're trying to achieve?

Thanks!

**Comment by levylll** [comment]
@HonzaKral 
how could I add the parameter 'boost' in query?
            "query": {
                "bool": {
                    "should": [
                        {
                            "multi_match": {
                                "query": "%s",
                                "fields": [
                                    "product_name",
                                    "short_name"
                                ],
                                "boost": 2
                            }
                        },
                        {
                            "match": {
                                "product_pinyin": {
                                    "query": "%s",
                                    "boost": 1
                                }
                            }
                        }
                    ]
                }
            },
Thank you very much~!

**Comment by HonzaKral** [comment]
The dsl just converts the keyword arguments to keys in the json body, that's all it does.

```
s = Search()

s.query(
  Q(
    "multi_match",
    query="...",
    fields=['product_name', "short_name"],
    boost=2
  ) | Q(
    'match',
    product_pinyin={'query': '...', 'boost': 1}
  )
)
```

Hope this helps

**Comment by HonzaKral** [comment]
There is no reaction for over a week so I will assume the last comment resolved this issue, please reopen if you need additional info.
Thanks!

**Comment by levylll** [comment]
Oh,it’s very sorry that I found your email was isolated by my mailbox. Thank you for your consideration. 
Now I use the json format to solve my problem. If I get into troubles when I add your api in my system, I would ask you for help.
Thanks again!
Wish you best!
