### ISSUE TITLE
Completion suggester not working as intended?

### ISSUE THREAD

**Issue by rtkaleta** [elastic/elasticsearch-dsl-py#344]
Hello,

Reading [latest release docs](https://media.readthedocs.org/pdf/elasticsearch-dsl/latest/elasticsearch-dsl.pdf) it appears the library should support completion suggesters. 

So I tried the following:
```python
from datetime import datetime
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Completion, DocType, Integer, Search


class Restaurant(DocType):
    id = Integer()
    name_suggest = Completion(payloads=True)

    class Meta:
        doc_type = 'restaurant'

    def save(self, **kwargs):
        self.updated_at = datetime.now()
        return super(Restaurant, self).save(**kwargs)


```

When I write code like:
```python
if __name__ == '__main__':
    conn = Elasticsearch()
    index_name = 'test_name_autocomplete'

    for i in xrange(10):
        name = 'r_{0}'.format(i)
        payload = {
            'id': i,
            'name': name,
            'other': 'extra_data'
        }
        r = Restaurant(id=i, name_suggest={
            'input': name,
            'payload': payload
        })
        r.save(index=index_name, using=conn)

```
the index mapping thus generated is like:
```JSON
{
  "test_name_autocomplete" : {
    "aliases" : { },
    "mappings" : {
      "restaurant" : {
        "properties" : {
          "id" : {
            "type" : "long"
          },
          "name_suggest" : {
            "properties" : {
              "input" : {
                "type" : "string"
              },
              "payload" : {
                "properties" : {
                  "id" : {
                    "type" : "long"
                  },
                  "name" : {
                    "type" : "string"
                  },
                  "other" : {
                    "type" : "string"
                  }
                }
              }
            }
          },
          "updated_at" : {
            "type" : "date",
            "format" : "dateOptionalTime"
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "creation_date" : "1456160869086",
        "number_of_shards" : "5",
        "number_of_replicas" : "1",
        "version" : {
          "created" : "1070399"
        },
        "uuid" : "Wq1U_LZnREeLOIzptYuw6w"
      }
    },
    "warmers" : { }
  }
}
```
and we begin to see a problem: the `name_suggest` field is not of the desired `completion` type.

Indeed, when I then do:
```
s = Restaurant.search(using=conn, index=index_name).suggest('name_suggestions', 'r', completion={'field': 'name_suggest'})
suggestions = s.execute_suggest()
```
the last line fails with `ElasticsearchException[Field [name_suggest] is not a completion suggest field]`

Am I doing something wrong?

I am running `elasticsearch-dsl==0.0.11`, `elasticsearch==1.9.0`, Python v2.7.10 and Elasticsearch v1.7.3.

**Comment by HonzaKral** [comment]
You need to create the mappings explicitly either using the `Index` object (0) or just calling `Restaurant.init()` before indexing any data.

0 - http://elasticsearch-dsl.readthedocs.org/en/latest/persistence.html#index

**Comment by rtkaleta** [comment]
Thanks for the quick response! 

Indeed, what is missed is the first sentence [here](http://elasticsearch-dsl.readthedocs.org/en/latest/persistence.html#document-life-cycle). I have previously only used simple `string`/`long` etc field types and upon seeing the index mapping automatically created with the right type whenever I `save`ed a `DocType` I assumed the class handled this for me. I guess Elasticsearch itself was using some kind of default mapping.

Your suggestion solves the problem, and the docs clearly state how to solve the problem, so I am going to close this issue with no further action.
