### ISSUE TITLE
Can't seem to combine queries with filters in a bool query

### ISSUE THREAD

**Issue by davidemerritt** [elastic/elasticsearch-dsl-py#345]
To my understanding, in the current implementation, you cannot mix filters and queries within one filter context bool (or query context bool). Given this example:
```
 "query": {
        "filtered": {
            "filter":   {
                "bool": {
                    "must":  [{
                        "term":  { "folder": "inbox" }},
                        "query": { 
                            "match": { "email": "urgent business proposal" }
                        }]
                    }
                }
            }
        }
    }
```
(mildly modified from https://www.elastic.co/guide/en/elasticsearch/guide/current/_combining_queries_with_filters.html)

Based on this, there shouldn't be any reason the client can't understand:
```
from elasticsearch_dsl import Q, F
query = F("bool", should=[Q("match", email="urgent bp"), F("term", folder="inbox")])
```

I am happy to work on extending this functionality if I'm not missing something, or perhaps I just don't realize how to implement this?

Thanks for taking a look at this.

**Comment by HonzaKral** [comment]
Assuming you are working with pre 2.0 release the code to generate the query you are after is:
```
s = Search()
s = s.filter("term", folder="inbox)
s = s.filter("query", query=Q('match', email='urgent bp'))
```

Hope this helps.

**Comment by davidemerritt** [comment]
Thanks very much, I completely missed that I have to wrap my query Q's in a filter("query", query=Q) when mixing them in a bool.
