### ISSUE TITLE
import filter raises ImportError in 2.0.0

### ISSUE THREAD

**Issue by alexgarel** [elastic/elasticsearch-dsl-py#346]
From a fresh install with python3.4:

```
>>> from elasticsearch_dsl import filter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/test_py_dsl/lib/python3.4/site-packages/elasticsearch_dsl/filter.py", line 1, in <module>
    from .utils import DslBase, BoolMixin, _make_dsl_class
ImportError: cannot import name 'BoolMixin'
```

In filter.py  the Bool class use a mixin which is not present in the code anymore.

**Comment by alexgarel** [comment]
Ok, filter is deprecated.

That said, it seems the elasticsearch_dsl-2.0.0-py2.py3-none-any.whl file present on pypi as the filter.py file inside while it should not.

**Comment by HonzaKral** [comment]
Yes, filter has been removed since filters have been removed in elasticsearch 2.0.

Thanks for the info that `filter.py` is still present, that definitely shouldn't be the case, it was my error when building the wheel, will fix it with next release.

**Comment by jabad3hut** [comment]
https://pypi.python.org/pypi/elasticsearch-dsl needs example needs updated to remove the filter and illustrate how to accomplish the filter now that it's deprecated

**Comment by dylanninin** [comment]
Thanks, the filter is deprecated.

**Comment by gdestuynder** [comment]
when you currently try to use filter it basically sees it as a query field so it looks like it works, but then does not because it places inside query>bool (which ES versions that support filter will reject).
Doh.
