### ISSUE TITLE
How to change multi_match query type?

### ISSUE THREAD

**Issue by lexicalunit** [elastic/elasticsearch-dsl-py#353]
There are a number of different `multi_match` query types documented here: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-multi-match-query.html

Such as `best_fields` (default), `most_fields`, `cross_fields`, `phrase`, and `phrase_prefix`.

In the documentation and examples I see code like the following:

```
MultiMatch(query='python django', fields=['title', 'body'])

Q("multi_match", query='python django', fields=['title', 'body'])

s = s.query("multi_match", query='python django', fields=['title', 'body'])
```

How would we specify `type` for these queries? Is it as simple as:

```
MultiMatch(query='python django', type='cross_fields', fields=['title', 'body'])

Q("multi_match", query='python django', type='cross_fields', fields=['title', 'body'])

s = s.query("multi_match", query='python django', type='cross_fields', fields=['title', 'body'])
```

For `cross_fields`, for example?

**Comment by HonzaKral** [comment]
Yes, it is exactly as simple - all kwargs passed to the query just get turned to keys in the dict/json body.

**Comment by lexicalunit** [comment]
Sweet! Thanks :+1:
