### ISSUE TITLE
Different behaviour when using .fields([...])

### ISSUE THREAD

**Issue by johncollaros** [elastic/elasticsearch-dsl-py#355]
When not limiting fields in a search, the results returned are the values. Example returned value: abcde 

When using .fields(['field1']) with a query, the results are the values, wrapped in quotes and brackets: ['abcde']

This doesn't seem to be consistent behaviour.

Could you confirm if this is a defect?

**Comment by HonzaKral** [comment]
this is unfortunately a side effect of how elasticsearch stores the data. Since it doesn't know whether the original document had a single or multiple values it opts for the safe option of always returning a list. If you want instead fields extracted from your document consider using source filtering (once either #352 or #349 are merged that is).

**Comment by johncollaros** [comment]
This is not the case when  using CURL from the CLI.
Using JQ to extract the fields from the JSON, the [ ] are not placed around the data returned.

The elastic_dsl can certainly do it when you don't specify the fields in the query, but if you do, the result is different.

I'll give you an example (some details redacted)

'''
# Not specifying fields in the query
s = Search(using=client, index="logs-index-*") \
    .filter("term", MethodName="somevalue") \
    .filter('range',**{"@timestamp": {"gte": "2016-01-01T00:00:00","lte": "2016-01-31T23:59:59","time_zone": "+11:00"}}) \
    .query("query_string", default_field="MessageText", query="a query")

for hit in s.execute():
	print(hit.LogDate)

2016-01-04
2016-01-04
2016-01-04
2016-01-04
2016-01-04
2016-01-04
2016-01-04
2016-01-04
2016-01-04
2016-01-04

# Specifying fields in the query
s2 = Search(using=client, index="logs-index-*") \
    .fields(['LogDate', 'LogTime', 'MessageText']) \
    .filter("term", MethodName="somevalue") \
    .filter('range',**{"@timestamp": {"gte": "2016-01-01T00:00:00","lte": "2016-01-31T23:59:59","time_zone": "+11:00"}}) \
    .query("query_string", default_field="MessageText", query="a query")

for hit in s2.execute():
	print(hit.LogDate)
	
['2016-01-04']
['2016-01-04']
['2016-01-04']
['2016-01-04']
['2016-01-04']
['2016-01-04']
['2016-01-04']
['2016-01-04']
['2016-01-04']
['2016-01-04']
'''

**Comment by HonzaKral** [comment]
It should be the same as `curl`, if you do the same operation:
```
curl localhost:9200/logs-index-*/_search?fields=LogDate
```

will also return a list for the `LogDate` field.

**Comment by johncollaros** [comment]
My apologies, the removal of the brackets is the due to the magic of JQ.

**Comment by HonzaKral** [comment]
No worries, I am closing the issue since thi is just the default ES behavior.
