### ISSUE TITLE
Nested with empty multi field is broken after calling to_dict

### ISSUE THREAD

**Issue by mcs07** [elastic/elasticsearch-dsl-py#359]
If I have a Nested field that contains a property with `multi=True`, I'm finding that calling `to_dict` on parent is changing some state of the inner object so that the empty values are no longer available as empty lists.

As an example:

    class BlogPost(DocType):
        categories = Nested(properties={'level': Integer(), 'value': String(multi=True)})

Then I find:

    >>> b = BlogPost(categories=[{'level': 1}])
    >>> b.categories
    [{'level': 1}]
    >>> b.categories[0].value
    []
    >>> b.to_dict()
    {'categories': [{'level': 1}]}
    >>> b.categories[0].value
    AttributeError: 'AttrDict' object has no attribute 'value'

Is this a bug or am I doing something wrong here?

**Comment by HonzaKral** [comment]
This is definitely a bug, thanks for the report!
