### ISSUE TITLE
Is possible to set meta _id field in save model method?

### ISSUE THREAD

**Issue by aktywnitu** [elastic/elasticsearch-dsl-py#360]
I would like to have this code as method of model class?
Is possible? Now I am doing it during initialization.

**Comment by HonzaKral** [comment]
It is absolutely possible to set the `id` in the save method, just set it before calling `super`:
```
class MyDoc(DocType):
    ...
    def save(self, **kwargs):
        self.meta.id = 42
        return super(MyDoc, self).save(**kwargs)
```
