### ISSUE TITLE
Format for Date()

### ISSUE THREAD

**Issue by dco5** [elastic/elasticsearch-dsl-py#365]
Hello,

Is there a way to specify the format for Date()? I am trying to do it for a models.TimeField, so I was thinking of using the basic_time_no_millis format. So I tried 
Date(format='basic_time_no_millis') but I get an error : 

unsupported parameters:  [format : basic_time]')

Thanks!

**Comment by HonzaKral** [comment]
Hi,
can you please provide an example of where this occurs? I just tried:
```
from elasticsearch_dsl import DocType, Date
class MD(DocType):
    d = Date(format='basic_time_no_millis')
    class Meta:
         index = 'i'
MD.init()
```
and it created the proper mappings in ES.

**Comment by dco5** [comment]
Is working now, the problem was that I was put this code

class SearchConfig(AppConfig):
    name = 'wrw.apps.search'
    verbose_name = 'Search'

    def ready(self):
        connections.configure(**settings.ES_CONNECTIONS)
         try:
             Event._doc_type.refresh()
        except NotFoundError:
             pass

And it would not let the mappings update. Everytime  I tried to change the mappings in the DocType it would throw an error. So I commented Event._doc_type.refresh() and updated the mappings and is not throwing an error anymore.

Thanks.

**Comment by HonzaKral** [comment]
yes, the `refresh` will not override the fields already defined in your `DocType` so this should work fine if the `Event` mappings weren't yet in elasticsearch or if they were created from the `Event` class.

Closing the issue.
