### ISSUE TITLE
Help to understand query building

### ISSUE THREAD

**Issue by andurin** [elastic/elasticsearch-dsl-py#368]
Hi,

```
client = Elasticsearch(hosts='https://host/es/', index="observables-*")
s = Search().using(client).query("match", observable="something")
print s.to_dict()
```
resulting to:
```{'query': {'match': {'observable': 'something'}}}```

So far, so good and I can iterate late through result docs.
But if I try to use it this way:
```
client = Elasticsearch(hosts='https://host/es/', index="observables-*")
s = Search().using(client)
s.query("match", observable="something")
print s.to_dict()
```
Result:
```{'query': {'match_all': {}}}```
The query will fire of course but doesn't reflect my expectations.

Using:
```elasticsearch (1.9.0)
elasticsearch-dsl (0.0.11)```
(Bound to ES 1.4.x)

Any suggestions how to build up the query without re-define Search object every time my query params will change?

Regards,
Hendrik

**Comment by HonzaKral** [comment]
Hi,
the `query` method return an altered copy of the `Search` object. Proper way is to do:
```
s = s.query('match', ...)
```

Hope this helps.

**Comment by andurin** [comment]
Hi,

Fast and right answer.
Many thanks!
