### ISSUE TITLE
Different behavior with scan() after a chained query than before.

### ISSUE THREAD

**Issue by boydjohnson** [elastic/elasticsearch-dsl-py#371]
So here is my code

    client = Elasticsearch()
    search = Search().using(client)
    search = search.filter('term', event=4)
    total_number_of_users = search.execute().hits.total
    for i, s in enumerate(search.scan()):
         print(i)
    users = search.query('match_phrase_prefix', text='Dave')
    for i, u in enumerate(users.scan())
        print(i)

So the first print prints out 600 some users, while the second print always prints out 10. I thought scan was able to access all records and that the Search() object is chainable. Can anyone offer advice on why the above code doesn't work as expected.

**Comment by HonzaKral** [comment]
`scan` accesses all records that the search matches on. the difference between the first and second loop in your code is that you have added a query, thus limiting the results to only those matching `Dave` in their `text` field.

**Comment by boydjohnson** [comment]
Thanks for you quick reply.
It just seems strange that it is exactly 10 and I have more than 10 Daves in Elasticsearch. Also if I do 'Dav' instead of 'Dave' I get 10 as well.

**Comment by njoannin** [comment]
@boydjohnson Could you tell us the result of ```users.count()```?

**Comment by boydjohnson** [comment]
Sorry, my fault. users.count() does happen to be 10. I ran it with text='D' and got a count of 239 and scan() produced all of the items. Feel free to close the issue.
