### ISSUE TITLE
Equality check on documents behaves unexpectedly

### ISSUE THREAD

**Issue by 0x64746b** [elastic/elasticsearch-dsl-py#373]
```
In [1]: from elasticsearch_dsl import DocType, String

In [2]: class Author(DocType):
    name = String()
   ...:     

In [3]: a = Author(name='George Orwell')

In [4]: b = Author(name='George Orwell')

In [5]: a == b
Out[5]: True

In [6]: a != b
Out[6]: True
```

Am I holding it wrong?
dtk

**Comment by HonzaKral** [comment]
No, you are not - it's just that we have defined `__eq__` but not `__ne__`, my bad.

**Comment by 0x64746b** [comment]
Np, I had stumbled across https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/utils.py#L235 and just expected it to work, but never checked the mro ;)

Thx.
