### ISSUE TITLE
How to reindex a result?

### ISSUE THREAD

**Issue by kputland** [elastic/elasticsearch-dsl-py#375]
How do I index a result to another index?
I need to add some new information to the document and then index it for another purpose to another index. How do I save it or reconstitute the original document so that I can yield it to elasticsearch.helpers.streaming_bulk?

```
>>> elasticsearch.__version__
(1, 9, 0)
>>> elasticsearch_dsl.__version__
(0, 0, 11)
```

```
import elasticsearch
from elasticsearch_dsl import Search
es = elasticsearch.Elasticsearch(['my.es.host'])
result = Search().filter('term', somefield='someterm').index('someindex').using(es).execute()
for hit in result.hits:
    hit.newdata = ['something I need to add']
    hit.meta.index = 'newindex'
    #
    # How do I put this document into a new index?
    #hit.save()
    #
```

**Comment by HonzaKral** [comment]
Hi, `save` method on `DocType` (0) takes keyword arguments and one of them is `index` so you you can just say `hit.save(index='some-other-index')` any time. If you wish to avoid the `DocType` classes for some reason then you need to call the `es.index` API manually and just pass it `hit.to_dict()` as the `body`.

Hope this helps.

0 - http://elasticsearch-dsl.readthedocs.org/en/latest/persistence.html#doctype

**Comment by kputland** [comment]
I think the issue is that I'm not seeing DocType and it's type Result. It doesn't have a save method, and to_dict doesn't maintain the document _id and I need the _id to match in the new index.
```
>>> result = search.using(es).execute()
>>> hit = result.hits[0]
>>> type(hit)
<class 'elasticsearch_dsl.result.Result'>
>>> hasattr(hit,'save')
False
```

**Comment by HonzaKral** [comment]
You are not using the `DocType` - you don't define it anywhere and you don't create your own document classes so you just get the generic `Result`.

If you want to use `DocType`, just define your class and use if when searching as in the linked example - http://elasticsearch-dsl.readthedocs.org/en/latest/persistence.html#search

Otherwise you would need to do `es.index(index='new-index', doc_type=hit.meta.doc_type, id=hit.meta.id, body=hit.to_dict())`

**Comment by kputland** [comment]
So `hits[0].to_dict()` is `raw['hits']['hits'][0]['_source']` and something like this should work then...
```
def docgen(hits, data):
    for hit in hits:
        hit.newdata = hit.newdata + [data] if hasattr(hit, 'newdata') else [data]
        yield {'_index':'newindex', '_type':'mydoctype', '_id':hit.meta.id, '_source':hit.to_dict()}

elasticsearch.helpers.streaming_bulk(es, docgen(hits, something_to_add), chunk_size=CHUNKSIZE)
```
