### ISSUE TITLE
minimum_should_match doesn't work inside 'bool' query def

### ISSUE THREAD

**Issue by dblado** [elastic/elasticsearch-dsl-py#382]
Per the docs, specifying minimum_should_match in the Q ('bool',...) didn't work for me.:
```
q = Q('bool',
    must=[Q('match', title='python')],
    should=[Q(...), Q(...)],
    minimum_should_match=1
)
s = Search().query(q)
```
Specifying it before executing the query like this did.
```
q = Q('bool',
    must=[Q('match', title='python')],
    should=[Q(...), Q(...)]
)
s = Search().query(q)
s.query.minimum_should_match = 2
```

using:
elasticsearch==2.3.0
elasticsearch-dsl==2.0.0

**Comment by HonzaKral** [comment]
I cannot replicate this issue, could you please try:
```
from elasticsearch_dsl import Q, Search
q = Q('bool', must=[Q('match', title='python')], minimum_should_match=42)
s = Search().query(q)
print(s.to_dict())
```
In my case it correctly outputs:
```
{'query': {'bool': {'must': [{'match': {'title': 'python'}}], 'minimum_should_match': 42}}}
```

Thanks!

**Comment by dblado** [comment]
Ah, yes...works w/out a filter. This however:
```
q = Q('bool', must=[Q('match', title='python')], minimum_should_match=42)
s = Search()
s = s.filter('term', published=True)
s = s.query(q)
print(s.to_dict())
```
produces:
```
{'query': {'bool': {'filter': [{'term': {'published': True}}], 'must': [{'match': {'title': 'python'}}]}}}
```

**Comment by HonzaKral** [comment]
Ah, yes, you are correct. It's due to the (arguably weird) way `bool` queries are combined. Will have to fix this. Thanks for the report!

**Comment by HonzaKral** [comment]
This should be fixed as of cccb972, could you please verify?

I removed the special treatment we had for `bool` queries that made little sense in retrospect.

Thanks!

**Comment by NLSVTN** [comment]
I am getting the same error with 
elasticsearch 6.2.0 
elasticsearch-dsl 6.1.0

**Comment by HonzaKral** [comment]
@NLSVTN Can you please elaborate? What error are you getting and what is the code that produces the error?
Thank you!

**Comment by NLSVTN** [comment]
The error is the following:

RequestError: TransportError(400, u'parsing_exception', u'[terms] query does not support [minimum_should_match]')

I am just creating 'Q('terms', codingGeneIds=gene_ids, minimum_should_match=1)' and then feeding it into the 'filter' function. I read that it is anyway deprecated and by default is equal to 1, so I removed it from the query and it started to work. I am not completely sure that the query is correct though: I am trying to get all the documents that have at least one value of an array in an array property (codingGeneIds):

https://stackoverflow.com/questions/28001632/filter-items-which-array-contains-any-of-given-values

At the same time, what if I need minimum_should_match = 2? I would not know how to achieve that.

**Comment by HonzaKral** [comment]
`minimum_should_match` is a parameter for a `bool` query, not `terms`. This is not a problem with the library, just an invalid parameter to a query.
