### ISSUE TITLE
Looking for a way to structure nested or relational data in elastic search

### ISSUE THREAD

**Issue by rlam3** [elastic/elasticsearch-dsl-py#383]
I'm looking for a way to structure nested or relational data in elastic search.

Ex. A cluster of chain restaurants that are separated by regions. But these regions group together locations/addresses is what I had in mind. However this would mean I would have to update the entire document when locations are added or deleted. 

I read the following guides and think the best way is to index location/address and then add the name of the restaurant chain to the index document. I'm looking to do a query search one string if possible. 

```
q = 'chipotle san francisco'
s = Search(using=client, index="restaurants").filter("term",name=q)
r = s.execute()

for h in r:
  print h # this would be listing all chipotle restaurants in san francisco area. 
```

However, the documentation provided here does not say how to persist data with nests or relational data here. What would be the better way to index this sort of structure? I'm not sure if elastic search can do joining like RMDBS. (e.g postgresql) Please advise.

Thanks! 

Reference:

https://www.elastic.co/blog/managing-relations-inside-elasticsearch
http://stackoverflow.com/questions/23403149/elasticsearch-relationship-mappings-one-to-one-and-one-to-many
http://voormedia.com/blog/2014/06/four-ways-to-index-relational-data-in-elasticsearch

**Comment by rlam3** [comment]
As of current I'm looking into parent child relationships... but How do we fetch the parent that is associated with the child? I've been trying to use has_parent and has_child but it keeps giving me the following error of my query class as non existent. What does this mean?

```
UnknownDslObject: DSL class `XXX` does not exist in query.
```
How should I be querying the for parent from child?

Thanks!

**Comment by HonzaKral** [comment]
I would definitely recommend parent/child for this, the way to do this would be:
```
from elasticsearch_dsl import DocType, String, MetaField, Index, Q
i = Index('i')
@i.doc_type
class Chain(DocType):
    title = String()

@i.doc_type
class Restaurant(DocType):
    location = String()
    class Meta:
        parent = MetaField(type='chain')
i.create()
```
Then you can query the `Restaurant` type and add conditions on the `Chain` by using the `has_parent` query. If you then specify `inner_hits` parameter to the `has_parent` query the parent chain document will also be returned:

```
Chain(_id='starbucks', title='Starbucks').save()
Restaurant(_id='sf_sb', _parent='starbucks', location='sf').save()
s = Restaurant.search().query('has_parent', type='chain', inner_hits={}, query=Q('match', title='starbucks'))
```
Then each hit will have a `.meta.inner_hits` attribute containing the parent.

Hope this helps.

**Comment by HonzaKral** [comment]
You can do exactly the same for `has_child` when querying `Chain`, then `inner_hits` will contain a list of children matching

**Comment by rlam3** [comment]
@HonzaKral Thanks for your response. Because I'm hoping to use a one query instead of two from the user input. Ex. 'starbucks san francisco'. I want it to return back me the restaurants and prioritize the ones in san fran before other ones. 

Would you still use recommending using parent child relationship? 

I was looking at multi_match and thinking of indexing all restaurants with the chain name and do multi_match... but I'm not sure if this is best practice. Please advise.. Thanks!

**Comment by HonzaKral** [comment]
You can easily combine a `has_(parent|child)` query with other queries using any logic you wish - both required, one required and other optional or just both optional and just boosting the document's score (see `bool` query which can do all of this).

It is really up to you and the choice whether to use parent/child or denormalization doesn't much affect the outcome.

**Comment by rlam3** [comment]
@HonzaKral ok i think i get what you are saying now... 

My next question is because your query is searching the at the child level and it is returning the child with the meta.parent info. 

How do I also specify the query to search at the child level with searching the parent too. Meaning I want to use the same string query 'starbucks san francisco' at the child level location string. What would the syntax look like?

```
s = Restaurant.search().query( # Child level looking for parent that can match terms from query string
  'has_parent',
  type='chain',
  inner_hits={},
   query=Q(
    'multi_match',
    query='starbucks san francisco',
    fields=[
      'name',    ]
  )
)
```

q1 = Search at Restaurant level level for parent that has matching string
q2 = Search at Restaurant level for location that has matching string
Would doing like Restaurant.search().query(q1).query(q2) be the correct way?

**Comment by HonzaKral** [comment]
You can call `.query` multiple times:
```
s = Restaurant.search()
s = s.query('has_parent', type='chain', inner_hits={}, query=Q('match', title='starbucks san francisco'))
s = s.query('match', location='starbucks san francisco')
```
This will make sure all those queries are required, if you want an *or* logic, just create the queries separately and use the `|` operator:
```
chain_q = Q('has_parent', type='chain', inner_hits={}, query=Q('match', title='starbucks san francisco'))
restaurant_q = Q('match', location='starbucks san francisco')
s = Restaurant.search().query(chain_q | restaurant_q)
```

**Comment by rlam3** [comment]
Awesome this looks closer to what I'm trying to do... 

Now is there a way to reorder by responses based on the score of my inner_hits? Or boost my outer hits scores with my inner hit scores? Ex. I have starbucks in every city... But I'm looking for 'starbucks san francisco' not 'starbucks san mateo', but 'san mateo can be included under 'san francisco'

Thanks a bunch!

**Comment by HonzaKral** [comment]
> Now is there a way to reorder by responses based on the score of my inner_hits? 

yes, both `has_parent` and `has_child` queries have scoring capabilities. See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-has-parent-query.html#_scoring_capabilities_2 for details

> does the order of which the query is placed affect the outcome?

no, all the queries are just  combined together into one `bool` query that is then executed.

Hoep this helps

**Comment by rlam3** [comment]
@HonzaKral where do I adjust the scoring with elasticsearch-dsl? It isn't discussed in the readthedocs... 

Could you please point out how elasticsearch-dsl how to interface scoring with elasticsearch? Thanks!

**Comment by HonzaKral** [comment]
@rlam3 simpluy pass a `score_mode` parameter to the `has_parent` or `has_child` query:
```
s = Search()
s = s.query('has_child', score_mode='avg', type='child_type', query=Q('match', title='python'))
```

**Comment by rlam3** [comment]
@HonzaKral So score_mode gives higher score the matching the parent... Is there a way to sort children based on the parent scores? Thanks!

**Comment by HonzaKral** [comment]
Yes, use a `has_parent` query which will query the children and then you can use it's `score_mode` parameter to influence how the parent score will influence the child's
