### ISSUE TITLE
Aggregation Metadata support missing

### ISSUE THREAD

**Issue by ragnarok56** [elastic/elasticsearch-dsl-py#384]
I've been unable to construct aggregations with meta data, as described in the ES documentation https://www.elastic.co/guide/en/elasticsearch/reference/current/agg-metadata.html.  I would expect to be able to supply the meta data when defining the aggregation

`A('terms', field='field_name', meta={'label': 'Field Name'})`

to_dict returns

`{'terms': {'meta': {'label': 'Field Name'}, 'field': 'field_name'}}`

which is invalid for an es query, it should look like:

`{'terms': {'field': 'field_name'}, 'meta': {'label': 'Field Name'}}`

**Comment by HonzaKral** [comment]
fixed via 5d7574f
