### ISSUE TITLE
Support for Fields Parameter in Suggest?

### ISSUE THREAD

**Issue by twegner** [elastic/elasticsearch-dsl-py#385]
Search has the parameter fields – A comma-separated list of fields to return as part of a hit.  Any thought on a equivalent capability for suggest?

**Comment by HonzaKral** [comment]
I am not sure I understand what you are asking for - the ES suggesters have no such capability so we cannot support it. Or is there something I am missing?
Thanks!

**Comment by twegner** [comment]
I thought I had seen it in the code but may have been mistaken.  I'll take another look in the next 24hrs and provide an update.

**Comment by twegner** [comment]
Closing, will handle this in the application.
