### ISSUE TITLE
About  DSL  use

### ISSUE THREAD

**Issue by shejianmin** [elastic/elasticsearch-dsl-py#387]
`elasticsearch` version is `1.4.2`
`elasticsearch_dsl_py` version is `0.0.11` 
how to achieve this query with DSL，hope to get your help。
`{
    "query": {
        "term": {
            "book_id": 1001096
        }
    }, 
    "from": 0, 
    "size": 0, 
    "aggs": {
        "genders": {
            "terms": {
                "size": 6, 
                "field": "keywords", 
                "order": {
                    "pv_1": "desc", 
                    "uv": "desc"
                }
            }, 
            "aggs": {
                "pv": {
                    "sum": {
                        "field": "score_feemax_7"
                    }
                }, 
                "uv": {
                    "sum": {
                        "field": "visit_pv"
                    }
                }
            }
        }
    }
}`

**Comment by HonzaKral** [comment]
```
s = Search()
s = s.query("term", book_id=1001096) # should probably be .filter instead, it will be faster
s = s[0:0]
s.aggs.bucket('genders', 'terms', field='keywords', size=6, order=[{"pv_1": "desc"}, {"uv": "desc"}]) # order needs to be a list!
s.aggs['genders'].metric('pv', 'sum', field='score_feemax_7')
s.aggs['genders'].metric('uv', 'sum', field='visit_pv')
```
Hope this helps
