### ISSUE TITLE
How about remove facet related func

### ISSUE THREAD

**Issue by rmrf** [elastic/elasticsearch-dsl-py#389]
Just 1 cent suggestion, how about remove Facet related function(and words), which ES already replaced Facet with Aggregation totally in the future.

**Comment by HonzaKral** [comment]
The facets mentioned are only in `FacetedSearch` which is a technical term (https://en.wikipedia.org/wiki/Faceted_search). It of course uses aggregations under the covers.

Most users of elasticsearch and elasticsearch dsl actually haven't used pre 1.0 versions of elasticsearch so I believe the potential for confusion isn't that big.

**Comment by rmrf** [comment]
OK, didn't realize it's a tech term,  now I see.
