### ISSUE TITLE
UnicodeEncodeError raised while repr an instance of DslBase in python 2

### ISSUE THREAD

**Issue by xq5he** [elastic/elasticsearch-dsl-py#393]
`In [4]: from __future__ import unicode_literals

In [5]: q = Q({'match_phrase': {'姓名': 'h'}})

In [6]: repr(q)
\---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-6-b5d77c5b5f27> in <module>()
----> 1 repr(q)

UnicodeEncodeError: 'ascii' codec can't encode characters in position 12-13: ordinal not in range(128)`

**Comment by xq5he** [comment]
The return value of __repr__ must be a string object in python 2.
For [DslBase.\__repr\__](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/utils.py#L232) returns a unicode, python tries to encode it with 'ascii'. This step fails while there are non-ascii characters there.

**Comment by HonzaKral** [comment]
When doing `from __future__ import unicode_literals` the you are not using `str` but `unicode`. When you have your default encoding set in your system to `ascii` there is then no way for the library to correctly (de)serialize the unicode string you passed in into str.

If you use non-ascii characters you need to set your encodings properly unfortunately.
