### ISSUE TITLE
Rename error

### ISSUE THREAD

**Issue by Alexis-benoist** [elastic/elasticsearch-dsl-py#394]
I found a KeyError in the code which is not very explicit. The following testing code shows the problem.

``` python
from elasticsearch import Elasticsearch
from elasticsearch_dsl import MultiSearch, Search
from os import getenv

ELASTIC_URL = getenv('ELASTIC_URL', 'http://localhost')
ELASTIC_PORT = int(getenv('ELASTIC_PORT', 9200))
es = Elasticsearch(hosts=ELASTIC_URL, port=ELASTIC_PORT)

ms = MultiSearch(using=es)
s = Search(using=es, index='index_which_does_not_exists')
ms = ms.add(s)
responses = ms.execute()
print list(responses)
```

I suggest the following modification at [result](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/result.py#L43) replace 

``` python 
h = self._d_['hits']
```
by 

``` python 
try:
    h = self._d_['hits']
except KeyError:
   raise ElasticsearchException
```

What do you think?

**Comment by levylll** [comment]
Excuse me, I use the MultiSearch, but it return the error 'AttributeError: 'Response' object has no attribute 'meta''
Could you help me?

**Comment by HonzaKral** [comment]
you should always check if the result in the response was successful, we should do the same in `__repr__` and have `hits` return empty probably in that case, or throw some exception - the `KeyError` might actually make sense (well, if we wrap it in `AttributeError`) since a failed search doesn't have hits.

**Comment by HonzaKral** [comment]
We changed the behavior of `MultiSearch` to raise an exception when one of the searches fail. To suppress this behavior just say `raise_on_error=False` and the missing searches will be replaced with `None`.

Hope this helps
