### ISSUE TITLE
'source' in Search()

### ISSUE THREAD

**Issue by nickmaccarthy** [elastic/elasticsearch-dsl-py#396]
In the 1.x and master branches, the Search() class in 'search.py', had a method called source() which allowed to modify the _source directly in the query.  The documentation for 1.x showed something similar to:
```
s = Search()
s = s.source(include=['@timestamp', 'fieldname1', 'fieldname2'])

```

https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L401

That method no longer seems to be valid in the 2.x branch.  I have tested manually by adding the '_source' directly in an CURL request to my 2.2.0 cluster and it works fine so it appears that functionality works in ES.  I know you have stated you develop this DSL in tandem with ES releases so is '_source' being deprecated in an upcoming version of ES, and or why is this method no longer there in the 2.x branch?

Thank you in advance!

**Comment by HonzaKral** [comment]
The releases of the DSL are not synchronized with elasticsearch releases so this has not yet been released. A release should come soon though.

Sorry for the inconvenience

**Comment by vaibhav-jain** [comment]
@HonzaKral Any update on this. Filter by Search().source() seems to make no difference using latest release.

**Comment by PritishC** [comment]
For those having issues using `source()`, you can use this workaround. For example, if we want only the "id" field in our hits -:

```
es_search = Search(...)
es_search = es_search.extra(_source={"includes": ["id"]})
res = es_search.execute()
```
