### ISSUE TITLE
Elasticsearch compatibility

### ISSUE THREAD

**Issue by jzbahrai** [elastic/elasticsearch-dsl-py#399]
This is both a design request and an issue ( I could also be making wrong assumptions so let me know)

ES 2.0 - removed the index analyzer and only uses analyzers, search_analyzers
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html 
"Previously, index_analyzer and search_analyzer could be set separately, while the analyzer setting would set both. The index_analyzer setting has been removed in favour of just using the analyzer setting." 

I am currently using the latest version of the dsl and ES2.3

name = dsl.String(index='not_analyzed') allows for an index_analyzer to get mapped in the mappings

Shouldn't this be replaced with 'analyzer'?
Unfortunately, name = dsl.String(analyzer='not_analyzed'), which would be compatible to the changes in ES2.0  doesn't work to map a field.

Should the design of elasticsearch-dsl be changed to remove index analyzers?

Thanks!

**Comment by HonzaKral** [comment]
`index='not_analyzed'` is a completely different setting saying that the entire analysis should be skipped. Saying `analyzed='not_analyzed'` is a completely different behavior - it just says to use the `not_analyzed` analyzer (which is, by default, not present so it will result in error).

In `elasticsearch-dsl` you can use either of the options - `analyzer`, `index_analyzer` and `search_analyzer`. I agree that this can be confusing so I will remove the `index_analyzer` option.

Thanks for the report.
