### ISSUE TITLE
not_analyzed field mapping not working.

### ISSUE THREAD

**Issue by theactiveactor** [elastic/elasticsearch-dsl-py#401]
I tried the following (taken from sample code). But when I manually check the ES mapping, the field is not marked as "not_analyzed".

Tried this:
username = String(fields={'raw': String(index='not_analyzed')})

And this:
username = String(index="not_analyzed")

**Comment by njoannin** [comment]
@theactiveactor Did you initialize (```MyDocType.init()```) your DocType before indexing anything?

**Comment by theactiveactor** [comment]
Thanks for the quick response. When I invoked init(), I received this error:
"ValueError: Empty value passed for a required argument 'index'."

**Comment by njoannin** [comment]
@theactiveactor Could you post a full example of your code? I.e. the full class of your doc_type and what you do with it to get the error?

**Comment by theactiveactor** [comment]
NVM, I needed to set the index parameter in index. Now it works. Thanks!

**Comment by njoannin** [comment]
OK, cool. Feel free to close the issue if all is good!
