### ISSUE TITLE
How can I set 'number_of_shards' for indexes using something like persistence?

### ISSUE THREAD

**Issue by alejoar** [elastic/elasticsearch-dsl-py#404]
I am currently using persistence for my mappings and what I really need to do is change the amount of shards in a specific index from 5 to 2 or 1. 

Is there some way to define this using something like persistence for mappings, but for indexes?

Also, if my indexes are already set to use 5 shards (by default), is it possible to reduce the amount?

I tried this:

```
from elasticsearch_dsl import Index
Index('my-index-name', using='my_es_server').settings(number_of_shards=1).create()
```

but raises `RequestError: TransportError(400, u'index_already_exists_exception', u'already exists')`

Any help appreciated

**Comment by HonzaKral** [comment]
Unfortunately elasticsearch doesn't allow changing the number of shards once an index has been created. You can change other settings but not the number of shards. To do that you need to create a new index and reindex the data. Elasticsearch's aliases can help make this transparent for the application/users (0).

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html
