### ISSUE TITLE
Link to the elasticsearch-py docs in the configuration section

### ISSUE THREAD

**Issue by edmorley** [elastic/elasticsearch-dsl-py#405]
At the moment the [configuration section](http://elasticsearch-dsl.readthedocs.io/en/latest/configuration.html) says:
```
Default connection
------------------

To define a default connection that will be used globally, use the
``connections`` module and the ``create_connection`` method:

.. code:: python

    from elasticsearch_dsl.connections import connections

    connections.create_connection(hosts=['localhost'], timeout=20)

Any keyword arguments (``hosts`` and ``timeout`` in our example) will be passed
to the ``Elasticsearch`` class.
```

From this it wasn't immediately clear:
* That the `Elasticsearch` class mentioned was actually from the `elasticsearch-py` package and not this one
* What the other options were for the connection (eg for auth)
* Most importantly: That the default settings are insecure, since SSL certificates are not verified (see https://elasticsearch-py.readthedocs.io/en/master/#ssl-and-authentication)

In the end, it was only through code inspection of elasticsearch-dsl-py and then manually googling for the elasticsearch-py repo (since there isn't a link to it from the repo readme or read the docs) that led me to:
https://elasticsearch-py.readthedocs.io/en/master/#ssl-and-authentication
https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch

I think it would be good to:
* make all mentions of elasticsearch-py in the docs/readme link to https://github.com/elastic/elasticsearch-py
* add a "for more details on connection options, see <elasticsearch-py docs page X>" to the configuration docs
* ideally also add a warning about not verifying certificates directly to the configuration page, in case people get set up without having read the elasticsearch-py docs first. (Not verifying certs by default is a **massive** footgun on the part of elasticsearch-py IMO, but that's a battle to fight another day.)

I'll try to open a PR if I get a moment, but if someone wants to beat me to it, then by all means :-)

**Comment by edmorley** [comment]
Many thanks :-)

I wonder if it's also worth doing this part:

> ideally also add a warning about not verifying certificates directly to the configuration page, in case people get set up without having read the elasticsearch-py docs first. (Not verifying certs by default is a massive footgun on the part of elasticsearch-py IMO, but that's a battle to fight another day.)

**Comment by HonzaKral** [comment]
@edmorley I am still trying to figure out what to do with `elasticsearch-py`, whether to change the default to be secure (and require the user to specify the certificates or install `certifi`) in which case this would be superfluous.

If we end up not going that route I agree that we should strengthen the wording around the need to look at `elasticsearch-py`'s limitations and configuration options.

Thanks for bringing this up, it is important.
