### ISSUE TITLE
Keeping database connection open

### ISSUE THREAD

**Issue by aktywnitu** [elastic/elasticsearch-dsl-py#406]
Hi,
I would like to index many documents to ES database.
I do it in a loop:

```
for post in posts:
    p = Post(title=post.title, published=True)
    p.meta.id = post.id
    p.save()
```

Is connection to db keeped during a loop? I would like make indexing more fast.

**Comment by brainix** [comment]
Hi, @aktywnitu.

You can do bulk indexing.  The way that I do this is by falling back to `elasticsearch-py` and using the [helper functions](http://elasticsearch-py.readthedocs.io/en/master/helpers.html).  For your example, you can generate bulk [index actions](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) like so:

```
import contextlib
import functools

import elasticsearch

es = elasticsearch.Elasticsearch()

@contextlib.contextmanager
def tune_for_bulk_index(index_name):
    put_settings = functools.partial(es.indices.put_settings, index=index_name, ignore=400)
    bodies = {
        'tuned_for_index': {'index': {'number_of_replicas': 0, 'refresh_interval': -1}},
        'tuned_for_search': {'index': {'number_of_replicas': 1, 'refresh_interval': '30s'}},
    }
    put_settings(bodies['tuned_for_index']
    try:
        yield
    finally:
        put_settings(bodies['tuned_for_search'])
        es.indices.refresh(index=index_name)

def index_actions(index_name, posts):
    for post in posts:
        action = {'_index': index_name, '_type': post.__class__._doc_type.name', '_id': post.id}
        action.update(post)
        yield action

def bulk_index(index_name, posts):
    with tune_for_bulk_index(index_name):
        results = elasticsearch.helpers.parallel_bulk(es, index_actions())
        sum(1 for _ in results)
```

Good luck!

**Comment by HonzaKral** [comment]
Hi,

it is exactly as @brainix said - use the `bulk` helper. Note that you can even use `to_dict(True)` to just serialize the document (including the metadata like doc type, id and index name) as described in #403.

The connection to elasticsearch is persistent and doesn't reopen the connection every time.
