### ISSUE TITLE
Custom analyzer not being created

### ISSUE THREAD

**Issue by KevinBrolly** [elastic/elasticsearch-dsl-py#410]
Hello, I am trying to use Index, DocType and analyzer to create index items with a custom synonym analyzer at index time.  I am doing something almost exactly the same as the suggestion here - https://github.com/elastic/elasticsearch-dsl-py/issues/337#issuecomment-183754002

My code is like this:

```
synonym_analyzer = analyzer(
    'synonym_analyzer',
    tokenizer='standard',
    filter=['lowercase', token_filter('synonym_filter', 'synonym', synonyms=['example,test'])]
)

class Service(DocType):
    id = String()
    name = String()
    categories = Nested(
        properties={
            'id': Integer),
            'name': String(analyzer=synonym_analyzer),
        }
    )

search_index = Index('search_index')
search_index.doc_type(Service)

search_index.create()

```

When I check at /search_index/?pretty to see if the analyzer is in the settings it is not there, and the categories name field mapping does not mention the analyzer.

Also when I try the analyze endpoint (/search_index/_analyze?analyzer=synonym_analyzer&text=test) it fails with "reason":"failed to find analyzer [synonym_analyzer]" so it is clear the analyzer is not being created, but I am not sure what it is I am doing wrong.

**Comment by brainix** [comment]
Hello!

You need to explicitly put your analyzers/filters on your new index.  I've written my own helper functions:

```
import contextlib
from elasticsearch import Elasticsearch

es = Elasticsearch()

@contextlib.contextmanager
def close_and_reopen_index(index_name):
    es.indices.refresh(index=index_name)
    es.indices.close(index_name)
    try:
        yield
    finally:
        es.indices.open(index_name)
        es.indices.refresh(index=index_name)

def put_analyzers_and_filters(index_name, analyzers, filters):
    body = {
        'analysis': {
            'analyzer': {a._name: a.get_definition() for a in analyzers},
            'filter': {f._name: f.get_definition() for f in filters},
        },
    }
    with close_and_reopen_index(index_name):
        es.indices.put_settings(body, index=index_name, ignore=400)
```

I hope that that helps, good luck!
