### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by boompig** [elastic/elasticsearch-dsl-py#411]
[This page on readthedocs](http://elasticsearch-dsl.readthedocs.io/en/latest/) only provides examples. Where is the documentation: a list of methods for the Search object, for example, what parameters they take, etc?

**Comment by HonzaKral** [comment]
Currently that documentation is in the docstrings of those methods and classes. In the future I would like to also render that as part of the docs.

**Comment by mattjmcnaughton** [comment]
@HonzaKral I took a shot at implementing this (see the attached pr).

Happy New Year!
