### ISSUE TITLE
Distribute elasticsearch-dsl-py 1.x and elasticsearch-dsl-py 2.0 separately

### ISSUE THREAD

**Issue by alexex** [elastic/elasticsearch-dsl-py#412]
Currently elasticsearch-dsl is distributed on python as one package with different versions, which means that it is impossible to have both elasticsearch 1.x and 2.0 installed at the same time, although it might make very much sense for the same application to talk to different versions of elasticsearch.

From what I have gathered in my research it is more or less impossible to get multiple versions of the same project using pip or some similar version. So what I want to propose is the following:

Instead of having one package with two versions two packages should be maintained on the package index, elasticsearch-dsl and elasticsearch-dsl2, which would enable people to use both versions at the same time.

I'd be very interested in hearing your opinions on the matter!

**Comment by HonzaKral** [comment]
I understand the issue, but there are currently no plans to do anything like this. The percentage of people running multiple versions of elasticsearch while using the dsl is not that big and, in most cases, one version of the dsl can actually talk to multiple es versions, as long as you make sure you are using compatible queries etc. The same goes for `elasticsearch-py` which is also currently not distributed in versioned package.

I will close this issue for now, if more people would be interested in this feature we can reopen the discussion later.
