### ISSUE TITLE
count call on query object doesnt pass in params to es client

### ISSUE THREAD

**Issue by akgoel-mo** [elastic/elasticsearch-dsl-py#420]
https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L605

Steps to reproduce:
1. Create DSL query
2. Call - `query.using(esClient).index(index_name).doc_type(doc_type).params(request_timeout=timeout, ignore_unavailable=True)`
3. Call this for an index that doesnt exist
4. Instead of getting count as 0, I am getting an exception for index not found

**Comment by brainix** [comment]
I believe that this is expected behavior.  Maybe you could wrap your count in a try/except like so?

```
try:
    count = ...
except NotFoundError:
    count = 0
```

**Comment by HonzaKral** [comment]
thanks for the report!
