### ISSUE TITLE
DSL appears to be dismissing quotes for phrase

### ISSUE THREAD

**Issue by znorris** [elastic/elasticsearch-dsl-py#421]
I have a search that returns 918 results:
```
{
    "query": {
        "query_string" : {
            "query": "\"my search phrase\" OR FOO",
            "fields": ["description","name"]
        }
    }
}
```

I'm trying to represent this as a query in the DSL but it's ignoring my quotes, returning 95,596 results.
```
q = query.Q("multi_match", query='"my search phrase" OR FOO', fields=['description', 'name'])
```
I've attempted the DSL query in other ways, with escape chars, etc. but nothing appears to make a difference. Is there some way I can represent this or is the library misbehaving?

**Comment by HonzaKral** [comment]
Those queries are really not the same - one is `query_string` where the other one is `multi_match`. To achieve the same query, use `q = query.Q("query_string", query='"my search phrase" OR FOO', fields=['description', 'name'])` instead.
