### ISSUE TITLE
date vs timestamps

### ISSUE THREAD

**Issue by wesyoung** [elastic/elasticsearch-dsl-py#422]
i was testing out the Date() class in fields and it seems a bit limiting when trying to capture timestamps down to milliseconds, am i missing something in the doc or would something like this work ok? (the way python dateutil is being used appears to be limiting).

https://github.com/elastic/elasticsearch-dsl-py/compare/master...wesyoung:master

open to suggestions, wanted to see if i was interpreting the issue properly before submitting a PR.

**Comment by HonzaKral** [comment]
The `Date` field has microsecond precision so it should be fine, see the tests tha use that: https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_integration/test_document.py#L57-L70

is there anything that didn't work for you when using `Date` field?

**Comment by wesyoung** [comment]
i'll have to go back and re-test, i think the parser.parse() within Date() was only returning the epoch for the date, and while i could patch it to "be smart" about the timestamps it's parsing (arrow is moderately better at this), i wasn't sure if that had other implications in other areas of the app...

**Comment by HonzaKral** [comment]
Looks good to me, but if there is something else that doesn't work with `dateutil` that `arrow` does better I would be interested to know and we can definitely switch
```
>>> from dateutil import parser
>>> parser.parse('2014-05-02T13:47:19.123456')
datetime.datetime(2014, 5, 2, 13, 47, 19, 123456)
```

Thanks for taking the time to look into this, I have to admit I only did the minimal testing to make sure everything works fine for the expected outputs but haven't delved into any depths.

**Comment by wesyoung** [comment]
ok, i think i figured out what's going on. you're right, it parses correctly, the issue comes into play if you do something like:

```
return [x['_source'].__dict__ for x in rv.hits.hits]
```

instead of just

```
return [x['_source'] for x in rv.hits.hits]
```

for some reason, the serialization of anything looking like a date-time goes straight to epoch. which is what i was seeing. but could be cause i was trying to make things too complicated too. not clear if this is in any of the get-setters or down the stack a bit. either way, appears to work. appreciate the insights... 👍

**Comment by HonzaKral** [comment]
It looks like you are trying too hard - if you just iterate over the results you can access the fields directly, no need for all the brackets, quotes and `_source`:
```
for hit in rv:
    print(rv.date_field)
```

**Comment by wesyoung** [comment]
story of my life. thats why i figured i'd ask first... i was trying to do something a little different than the snippet i posted, but that was before diving into the source a little too [trying to get things working].

anywho, appreciated, keep up the good work! :)
