### ISSUE TITLE
2.0.1 or 2.1.0 to PyPI

### ISSUE THREAD

**Issue by g3rd** [elastic/elasticsearch-dsl-py#424]
Hello,

Looks like the last time that _elasticsearch_dsl_ went to _pypi_ was in Feb. Is there a date when the next version will be pushed?

Really excited to use the new methods, namely `mget`, on the DocType class.

Thanks!

**Comment by HonzaKral** [comment]
Thank you fot the nudge, I have been putting it off for no good reason. `2.1.0` is now public - https://pypi.python.org/pypi/elasticsearch-dsl
