### ISSUE TITLE
geo_bounding_box filtering docs/examples

### ISSUE THREAD

**Issue by 2trc** [elastic/elasticsearch-dsl-py#427]
Hi,
I couldn't find any documentation or sample codes on how to run "[geo_bounding_box](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-bounding-box-query.html)" filtering with elasticsearch-dsl-py.

Intuitively I thought something as follows would work but it didn't:

```
s = Search(using=client)
top_left = {"lon": 50, "lat": 20}
bottom_right = {"lon": 60, "lat": 10}
s.filter("geo_bounding_box", location= {"top_left": top_left, "bottom_right": bottom_right})
```

**Comment by HonzaKral** [comment]
This should work, you just need to keep in mind that any call to `filter` will return a modified **copy** of the `Search` object so you need to do `s = s.filter(...)`.

Hope this helps

**Comment by 2trc** [comment]
@HonzaKral awesome, it works and I should have thought that. thanks for the fast and useful response!
