### ISSUE TITLE
Completion Class missing from elasticsearch-dsl-Package

### ISSUE THREAD

**Issue by guguncube** [elastic/elasticsearch-dsl-py#430]
The Completion class referenced in the documentation does not exist anywhere

See below:
https://github.com/elastic/elasticsearch-dsl-py/blob/bebd1d5f1a3c15f37f5bda976036a44418d36d6a/docs/persistence.rst

class Post(DocType):
125	        title = String()
126	        title_suggest = Completion(payloads=True)
127	        created_at = Date()
…

How can this be fixed?
from xxxx?? import Completion

**Comment by HonzaKral** [comment]
it is `from elasticsearch_dsl import Completion`. Added it to the docs, thanks for the report!

**Comment by KhasanovBI** [comment]
But there is no `Completion` class in repository.

**Comment by HonzaKral** [comment]
A lot of the dsl classes (queries, fields, aggregations) are automatically generated at import time.
