### ISSUE TITLE
How to choose between development or production environment in a Doctype class

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#434]
Hi, 

I have this Doctype class to work with persistence in my project. 

```
#developtment is a boolean variable.

from config import cluster,cluster_test, development
from elasticsearch import Elasticsearch
from elasticsearch.helpers import scan

if development:
    # We change to cluster from development
    es = Elasticsearch(cluster_test)
    connections.create_connection(hosts = cluster_test)

else:
    es = Elasticsearch(cluster)
    connections.create_connection(hosts = cluster)
    

class MyExampleClass(DocType):
    
    MyString = String(index='not_analyzed')
    AnotherParameter = String(index='not_analyzed')
    timestamp = Date()
    updated_at = Date()
    

```

There is another way to declare this class to connect this class to production or development environment without modify the development variable in the configuration file and passing development as a paremeter to this class.

Thanks in advance.

Best regards

**Comment by juandasgandaras** [comment]
yes it is true but to work with this variable:

` es = Elasticsearch(cluster)`

inside my class. 

Thanks in advance

**Comment by HonzaKral** [comment]
You can always get the client by calling: `connections.get_connection('dev')` (or `connections.get_connection()` for default)

**Comment by juandasgandaras** [comment]
ok, thanks for your help !!

**Comment by HonzaKral** [comment]
Happy to help. Note that you really shouldn't need access to the `Elasticsearch` instance for the most common operations - all the dsl methods support `using` kwarg which you can just pass the alias (`dev` in this case) as a string.
