### ISSUE TITLE
Bug with Q and Or operation

### ISSUE THREAD

**Issue by suvorovalexander** [elastic/elasticsearch-dsl-py#435]
for num in range(5):
  query = (query | Q('match', num=num)
queryset = queryset.query(query)

will construct 
{'query': {'bool': {'should': [{'bool': {'should': [{'bool': {'should': [{'bool': {'should': {'match': {'num': '0'}}, {'match': {'num': '1'}}}}, {'match': {'num': '2'}}]}}, {'match': {'num': '3'}}]}}, {'match': {'num': '4'}}]}}}

While it should do something like
{'query': {'bool': {'should': {'match': {'num': '0'}}, {'match': {'num': '1'}}, {'match': {'num': '2'}}, {'match': {'num': '3'}}, {'match': {'num': '4'}}}}}

**Comment by HonzaKral** [comment]
I am sorry, could you provide concrete examples? Neither of the dictionaries you have provided represent a valid query. Thanks!

as a side node your query would be much better as `Q('terms', num=list(range(5)))`.

**Comment by HonzaKral** [comment]
Ah, I see what you meant. I pushed a change as 6cf0c624a0f3897825ff622090d90e6d8d7c9ca4 that changes the behavior. Note that even the query that you see is functionally the same, it is just a less elegant expression.
