### ISSUE TITLE
How to add "type": long when creating a mapping?

### ISSUE THREAD

**Issue by azhard4int** [elastic/elasticsearch-dsl-py#437]
Hi,

Trying to create the long type for the objects as "from elasticsearch_dsl import Long/Boolean" seems to be gone?

Is there any way, we can create those type of objects?

**Comment by HonzaKral** [comment]
What version of `elasticsearch-dsl` are you using? I can still do `from elasticsearch_dsl import Long` just fine.

Thanks!

**Comment by azhard4int** [comment]
@HonzaKral, version 2.1.0

**Comment by azhard4int** [comment]
@HonzaKral , saw your another post about dynamically import of Long/Integer. It works like a charm but IDE was giving import error.
