### ISSUE TITLE
What is the proper way to declare connection in Django?

### ISSUE THREAD

**Issue by AbdullaM5** [elastic/elasticsearch-dsl-py#439]
What place in the code is suitable to declare a connection? I do it in
```
# django_project/django_project/__init__.py
from elasticsearch_dsl.connections import connections

connections.create_connection()
```

**Comment by HonzaKral** [comment]
I prefer to initialize connections in `AppCnfig.ready` (https://github.com/HonzaKral/es-django-example/blob/master/qa/apps.py#L14) but it can also be done directly in `settings.py`.
