### ISSUE TITLE
Deprecation of search_type = scan in Elasticsearch 5.0

### ISSUE THREAD

**Issue by ferrarimarco** [elastic/elasticsearch-dsl-py#440]
Hi.

Elasticsearch 5.0 dropped support for search_type = scan (see [here](https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_search_changes.html#_literal_search_type_scan_literal_removed)).

This breaks the Search.scan() feature.

**Comment by HonzaKral** [comment]
This has already been addressed in `elasticsearch-py` master (which will become the `5.0` release) that this method uses. If you want to use it now please feel free to use the master version of `elasticsearch-py`. Thanks!

https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/helpers/__init__.py#L274-L278
