### ISSUE TITLE
FacetedSearch def query() Overwrite fails with [match] query parsed in simplified form

### ISSUE THREAD

**Issue by vmogilev** [elastic/elasticsearch-dsl-py#446]
I am trying to Overwrites def query() in FacetedSearch from `multi_match` to `match_phrase`:

    class WorklogSearch(FacetedSearch):

        index = [settings.ES_INDEX, ]

        # "tables" that should be searched
        doc_types = ['worklog', ]

        # fields that should be searched
        fields = ['pwa_note', ]

        facets = {
            'portal': TermsFacet(field='pa_code'),
            'client': TermsFacet(field='pca_code'),
            'category': TermsFacet(field='cca_code')
        }

        def query(self, search, query):
            """Overwrites query type from `multi_match` to `match_phrase`"""
            if query:
                return search.query('match_phrase', fields=self.fields, query=query)
            return search

and then call it as follows:

    query_string = request.GET.get('q', None)
    s = WorklogSearch(query_string, {'portal': 'hj'})

it fails with the following error message:

elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', "[match] query parsed in simplified form, with direct field name, but included more options than just the field name, possibly use its 'options' form, with 'query' element?")

    additional_info
    {'error': {'failed_shards': [{'index': 'soloist',
                                  'node': 'nSbVmtndQOCAzyod3fFWNQ',
                                  'reason': {'col': 44,
                                             'index': 'soloist',
                                             'line': 1,
                                             'reason': '[match] query parsed in '
                                                       'simplified form, with '
                                                       'direct field name, but '
                                                       'included more options than '
                                                       'just the field name, '
                                                       "possibly use its 'options' "
                                                       "form, with 'query' "
                                                       'element?',
                                             'type': 'query_parsing_exception'},
                                  'shard': 0}],

What am I missing?

Thank you!

**Comment by HonzaKral** [comment]
Hi @vmogilev,

the problem is with the query itself - `match_phrase` query doesn't allow the `fields` parameter. I believe what you want instead is `multi_match` with `type="phrase"` (0):
```
return search.query('multi_match', fields=self.fields, query=query, type='phrase')
```
Hope this helps,
Honza

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#type-phrase

**Comment by vmogilev** [comment]
Awesome!  That's exactly what I was looking for.  Thank you Honza
