### ISSUE TITLE
Bool query minimum_should_match param get lost when chaining queries

### ISSUE THREAD

**Issue by mlubimow** [elastic/elasticsearch-dsl-py#447]
In situation like this:

```
s = Search()
q1 = Bool(must=[...])
q2 = Bool(should=[...], minimum_should_match=1)

s = s.query(q1).query(q2)
```

Final query will be

`Bool(must=[...], should=[...])`

and minimum_should_match param will be lost (its because of implementation in query.py, 92). 

I think that it would be better to check if this param (or should itself) already exist, if it does, it would be reasonable to display warning about param override, if it doesn't, it would be good to just leave it as it is.

What do you think?

**Comment by HonzaKral** [comment]
This is definitely a bug, we should respect the semantics of the query which means keeping the `minimum_should_match` in the resulting query. Thanks for the report!

**Comment by mlubimow** [comment]
Hey @HonzaKral , thank you for the response.

I was thinking about it and I think that this logic of "merging" two bools into one seems to be not always convenient, its not only about minimum_should_match param. Where it seems to be fine to merge musts and must_nots, it may be not correct for shoulds.

Lets say user have two queries:

```
q1 = Bool(
    should=[
        Match(first_name=John),
        Match(last_name=Doe)
    ],
    minimum_should_match=1
)
q2 = Bool(
    should=[
        Term(city=Birmingham),
        Term(county=West Midlands)
    ],
    minimum_should_match=1
)
```

and chain them? I suppose chaining should work like AND'ing, so personally I would expect that:

`s = Search().query(q1).query(q2)`

Should create:

`Bool(must=[q1, q2])`

Instead of:

```
Bool(
    should=[
        Match(first_name=John),
        Match(last_name=Doe),
        Term(city=Birmingham),
        Term(county=West Midlands)
    ],
    minimum_should_match=1
)
```

I understand that its an implementation detail, but I think that current behaviour may be confusing.

**Comment by HonzaKral** [comment]
Actually that part should be fixed already, in master (to be released soon I hope ;) ) it behaves correctly and the result is:
```
Bool(
  minimum_should_match=1,
  must=[
    Bool(
      minimum_should_match=1,
      should=[Term(city='Birmingham'), Term(county='West Midlands')]
    )
  ],
  should=[
    Match(first_name='John'), Match(last_name='Doe')
  ]
)
```

**Comment by mlubimow** [comment]
You mean in your local master, do you ;)

Master gives me for this example:

```
{
    'query': {
        'bool': {
            'minimum_should_match': 2,
            'should': [
                {'match': {'first_name': 'John'}},
                {'match': {'last_name': 'Doe'}},
                {'term': {'city': 'Birmingham'}},
                {'term': {'county': 'West Midlands'}},
            ],
        },
    },
}
```

**Comment by HonzaKral** [comment]
Ran this again just to be sure and it is indeed fixed in master, just not yet released to PyPI.

I think the behavior of `&` (which is used for consecutive `.query` calls) should be fixed now for bool queries even with `minimum_should_match` in master (6949eab659324cd7b913e038c8b6fe5ae0921a64).

Closing the ticket for now, please feel free to reopen with an example of what still needs to be fixed, I am sure we forgot something.

Thanks!

**Comment by mlubimow** [comment]
Not really, its not __and__ but __add__ from line 92, which is still unchanged.

**Comment by HonzaKral** [comment]
my apologies, you are of course correct, that is a major oversight on my part
