### ISSUE TITLE
How to set all fields in Object to be not analyzed?

### ISSUE THREAD

**Issue by variable** [elastic/elasticsearch-dsl-py#449]
See below code, I have data field that has dynamic field mapping, it works fine, but any fields(properties) inside data objects are analyzed by default, how do I go about making them not analyzed without specifying every single inner fields?

```
class ESImportEvent(DocType):
    feed_id = Integer()
    import_job_id = Integer()
    import_group_id = Integer()
    executor_config_id = Integer()
    state = String(index='not_analyzed')
    feed_name = String(index='not_analyzed')
    data = Object()
```

I tried: data = Object(index='not_analyzed') and it's throwing error:
```
RequestError: TransportError(400, u'mapper_parsing_exception', u'Mapping definition for [data] has unsupported parameters:  [index : not_analyzed]')
```

**Comment by brainix** [comment]
Hi, @variable.  (Cool GitHub username, by the way!)

I believe that you have to specify `index='not_analyzed'` on the individual fields.  I also believe that this is good design, as ["explicit is better than implicit."](https://www.python.org/dev/peps/pep-0020/)

Just my personal thoughts.

**Comment by variable** [comment]
Hey @brainix, while it's a cool name, but I get notified whenever someone mentions about "variable", and I think it's the most common thing to say in the programming world...

Anyway, the problem is the data structure is arbitrary...

**Comment by brainix** [comment]
Hi, @variable.  I don't exactly agree that the data structure is arbitrary.  It's definitely worth controlling how each individual field is indexed (or not) within an `Object`.  And I think that it can start to become confusing if there's a way to set indexing behavior at the top `Object` level, then override it on the individual field level.

I definitely understand your use case, and I get that this is repetition (which we programmers prefer to avoid).  But in this case, my opinion is that it's better that there be one (and preferably only one) right way to do it.  Then again, I'm not responsible for the design of `elasticsearch-dsl-py`.  I'm just a fan and a user!

**Comment by variable** [comment]
I have changed it to be string based now, since "data" comes from external sources.

**Comment by HonzaKral** [comment]
I am with @brainix - you don't want to have an arbitrary data structure completely out of your control. If you just want to save some typing and want to specify the mappings dynamically, you can via dynamic mappings:
```
class ESImportEvent(DocType):
    ...
    data = Object()

    class Meta:
        dynamic_templates = MetaField([
            {
                "data": {
                    "path_match": "data.*",
                    "match_mapping_type": "string",
                    "mapping": String(index="not_analyzed")
                }
            }
        ])
```
