### ISSUE TITLE
elasticsearch-dsl-py 2.1.0 query always return  []

### ISSUE THREAD

**Issue by johnnymaker** [elastic/elasticsearch-dsl-py#452]
"Query" does not work in elasticsearch-dsl-py version 2.1.0.
For the example, result of execution code "Model.search()" will be correct, but when we use "Model.search().query('term', title='test')" we have not objects in response, though  objects with title's point are in the index.
When we execute "execute().hits" we have a blank.
Plugins "Marvel" and "KOPF" has been used in tests for this requests. 
When using "kopf" If change the type for query  from "GET" to "POST" it will work correctly.
I have not find in "dsl" a way to change the type of query.
"Query" has worked true in elasticsearch-dsl-py version 2.0.

**Comment by HonzaKral** [comment]
Could you please verify what query is being sent to elasticsearch by calling `to_dict` on the `Search` object before you'd call `execute` on it?

Alternatively also try changing the type of query you use from `term` to `match` - `term` query does an exact lookup so if `title` is an analyzed field it likely won't match as expected.

Thanks!

**Comment by HonzaKral** [comment]
Closing this I cannot replicate and there is no additional information. Please feel free to reopen with additional details. Thank you!
