### ISSUE TITLE
query.Match(key=value) seems to take argument key literally

### ISSUE THREAD

**Issue by kiran-ms** [elastic/elasticsearch-dsl-py#456]
Not sure if this is an issue, but found this behavior while I was using this library.
I'm using the apis, query.Match(key=value), where key and value hold the values 'correlation_id' and '1234' respectively. The method seems to be literally taking the 'key' rather than the value it is holding. 
As in the call is getting translated as 

{'query': {'bool': {'must': [{'match': {'key': '123'}}, {'match': {'key': 'abcd'}}]}}}

but not

{'query': {'bool': {'must': [{'match': {'correlation_id': '123'}}, {'match': {'incident_id': 'abcd'}}]}}}

If I replace the key with say, A, i.e. query.Match(A=value), the call seems to be getting translated as
{'query': {'bool': {'must': [{'match': {'A': '123'}}, {'match': {'A': 'abcd'}}]}}}

Is this the expected behavior? If so, can you let me know what is the workaround for this? Or if any alternative available.

Kindly let me know if I need to provide any further information

Thanks,
Kiran

**Comment by njoannin** [comment]
Hi Kiran,

I believe that is the intended behaviour.

I think (but am not sure) that when you want to pass in variable, you should do so like this:

```
query.Match({key: value})
```

Hope this helps!

**Comment by kiran-ms** [comment]
Thank you, let me try this and see if this helps

**Comment by HonzaKral** [comment]
it needs to be `query.Match(**{key: value})` for this to work.

**Comment by njoannin** [comment]
Ah, I thought I might be missing something. Sorry for the mistake!

**Comment by kiran-ms** [comment]
Thank you, this works.
