### ISSUE TITLE
Support non-standard QueryParser's: Suppress UnknownDslObject?

### ISSUE THREAD

**Issue by lgalke** [elastic/elasticsearch-dsl-py#457]
Hey,

First of all, this is a great project and I really enjoyed creating complex queries with this package.
But then, I developed an elasticsearch plugin which provides a subclassed QueryParser, and thus, introducing a new keyword for queries. (such as "bool" or "match", lets call it "semantic")
I was hoping to be able to invoke this queryparser by passing the raw JSON into the query as suggested in the documentation:

`Q({"semantic": {"field1" : querystring}})`

But then, unfortunately an `elasticsearch_dsl.exceptions.UnknownDslObject` exception  is raised.
Undoubtedly, this is usually the desired behaviour. But i miss the feature of somehow indicating that i know what I am doing. Maybe by passing an additional parameter such as "ignorecheck=True" to the Q(...) constructor.

Did I miss any feature which already provides a solution?

**Comment by HonzaKral** [comment]
Hi,

I am very happy that `elasticsearch-dsl` works for you :)

I am afraid that adding custom queries from various lugins wouldn't be maintainable for this library, but nothing is stopping you from adding your own DSL classes:
```
>>> from elasticsearch_dsl import query, Q, Search
>>> 
>>> class SemanticQuery(query.Query):
...     name = 'semantic'
>>> 
>>> Q('semantic', field1='querystring')
SemanticQuery(field1='querystring')
>>> 
>>> s = Search().query('semantic', field1='querystring')
>>> s.to_dict()
{'query': {'semantic': {'field1': 'querystring'}}}
```

Hope this helps.

**Comment by lgalke** [comment]
Thanks, that is exactly the solution I was looking for.
