### ISSUE TITLE
Set analyzers on index

### ISSUE THREAD

**Issue by baldwmic** [elastic/elasticsearch-dsl-py#459]
I'm not sure I understand how to set an analyzer on the index.

The [documentation shows](https://github.com/elastic/elasticsearch-dsl-py/blob/master/docs/persistence.rst#index) the following:

```
blogs = Index('blogs')

blog.analyzer(html_strip)
```

Shouldn't it be this instead:

```
blogs = Index('blogs')

blogs.analyzer(html_strip)
```

?

I've read through the [ElasticSearch guide](https://www.elastic.co/guide/en/elasticsearch/guide/2.x/index.html) and [these docs](http://elasticsearch-dsl.readthedocs.io/en/latest/), but something is just not quite clicking.

**Comment by baldwmic** [comment]
With the following code:
```
from elasticsearch_dsl import Index, analyzer

entities = Index('entities')

entity_analyzer = analyzer('entity_analyzer',
    tokenizer="standard"
)

entities.analyzer(entity_analyzer)
```
I get the following error:
```
AttributeError: 'Index' object has no attribute 'analyzer'
```

Which confuses me, because I can see the class `Index` has the attribute `analyzer` defined on it [here](https://github.com/elastic/elasticsearch-dsl-py/blob/3ebb486363b2c94172b81668e41fdb2411e5a022/elasticsearch_dsl/index.py#L41)

**Comment by oldcai** [comment]
I've tried to use index.settings method to set the analyzer and succeed.

That analyzer method seems didn't changed anything on es server.

**Comment by HonzaKral** [comment]
the `analyzer` method works in master where it adds the necessary analysis definition to the index settings. Note that index still needs to be created via `create` method otherwise those changes won't be reflected in elasticsearch.

**Comment by HonzaKral** [comment]
relevant test - https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_index.py#L101
