### ISSUE TITLE
Support profile api

### ISSUE THREAD

**Issue by david206** [elastic/elasticsearch-dsl-py#461]
Details of the profile api on [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-profile.html).

We need the ability to add to a query using dsl-py the profile flag, probably something similar to [extra properties and parameters](http://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html?highlight=explain#extra-properties-and-parameters) . In addition, the response should hold the profile result.

**Comment by HonzaKral** [comment]
I understand the use case, but it is also supported by the `extra` method and doesn't require it's own API:
```
s = Search().query(...)
s = s.extra(profile=True)
response = s.execute()

for shard in response.profile.shards:
    print(shard.id)
    for search in shard.searches:
        for query in search.query:
            print(query.query_type, query.lucene, query.time)
```

Currently I don't see the need to support this API in a more explicit way. Or is there anything in particular you are missing?

Thank you!

**Comment by david206** [comment]
Cool,
Maybe this kind of example should be on the docs? I am not sure it is trivial.

Thanks
