### ISSUE TITLE
Couldn't find a way adding min_score to query body

### ISSUE THREAD

**Issue by oldcai** [elastic/elasticsearch-dsl-py#462]
```
GET /_search
{
    "min_score": 0.5,
    "query" : {
        "term" : { "user" : "kimchy" }
    }
}
```
Documents are here: [min_score](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/search-request-min-score.html)

I found that neither `q = Q('query_string', query=str_query, min_score=4.0)` nor `Search().query(q, min_score=4.0)` would work.

And, if it isn't going to be supported by elasticsearch-dsl, is there any way to filter result by score?

**Comment by HonzaKral** [comment]
the `min_score` is a top-level argument in the `body`, to inject your keys into the body you can use the `extra` method. so in this case: `s = Search().query().extra(min_score=4.0)`

Hope this helps

**Comment by ipsbrittainm** [comment]
This doesn't work when doing a count() as the extra data is ignored, meaning the search() produces a different number or results to that given by the count.
