### ISSUE TITLE
Support version 5

### ISSUE THREAD

**Issue by hvdklauw** [elastic/elasticsearch-dsl-py#463]
I know ES 5 is still in alpha, but from what I understand there won't be a lot of new features that will be added to to it.

I saw elasticsearch-py is supporting 5 in development, so I was wondering if you have a roadmap for elasticsearch-dsl-py.

The reason I ask is that we currently have a haystack setup (ES 1.7) that's just not cutting it for what we want to do with elastic, so we want to upgrade. Now we are in no means in a rush, but having looked at what's available I think elasticsearch-py + elasticsearch-dsl-py would be a good way to go.

To so some long term planning it would be nice to know if you have a timeline in mind.

**Comment by benjaminrigaud** [comment]
I'll give it a try with the 5.0.0-beta1 and see what goes wrong.

**Comment by HonzaKral** [comment]
There is now a branch `5.x` that is compatible with elasticsearch 5.0.0. Any testing would be much appreciated!

**Comment by benjaminrigaud** [comment]
So far so good (for basic features)

**Comment by BongoEADGC6** [comment]
Seems to be very slow in comparison to 2.4

**Comment by HonzaKral** [comment]
@BongoEADGC6 can you specify what operations are slow? Also if you could try the same with `curl` - do you see same slowdown or if python significantly slower?

Thanks!

**Comment by HonzaKral** [comment]
`5.0.0` has just been released. Thank you very much for the feedback, please let me know if there is anything broken :)

**Comment by BongoEADGC6** [comment]
@HonzaKral I apologize for not getting back you in time. It seems like it is my server that has been causing problems and not your library. Thanks for your concern.
