### ISSUE TITLE
can not get the geo type when using fields

### ISSUE THREAD

**Issue by levylll** [elastic/elasticsearch-dsl-py#464]
when the 'location' is the geo type ,such as 
  location: {
    lat: 0.6958537843244914,
    lon: 2.033639161387014
  },
if I search my es with the query
  { "fields": ["product_name", "location"], "size": 10}
I just get the respose with 
        "fields": {
          "product_name": [
            "阿呆测试商品详情页 V4 到店类商品标题 v"
          ]
        }
where is the 'location' fields???

**Comment by HonzaKral** [comment]
Sorry for the delay, for geo fields it is much better to use source filtering which actually works just fine. The missing `location` field was caused by the fact that internally it was represented as two fields on the document which is unsupported in the `fields` parameter.
