### ISSUE TITLE
dsl usage problem

### ISSUE THREAD

**Issue by ernestoarbitrio** [elastic/elasticsearch-dsl-py#465]
I'm trying to translate this 
`'{
        "query": {
                "filtered": {
                        "query": {
                                "query_string": {
                                        "query": "My string"
                                }
                        }                  
                }
        },
        "fields": [
                "virtual"
        ]
}'
`
but when i write

`s = Search(using=client, index="my_index").filter("match", virtual="My string")`

i've no results instead of the standard approach!

Do you have any suggestion?

Thanks

**Comment by njoannin** [comment]
If you are using `.filter`, I presume you are still on ES v1.x

I think that you should use `term` with filtering:

```
s = Search(using=client, index="my_index").filter("term", virtual="My string")
```

Hope this helps!

**Comment by ernestoarbitrio** [comment]
Ah thank you, but the problem wasn't the ES version and si the "term" statement, but i had to search a partial string so i must use "wildcard" instead of term or match!
