### ISSUE TITLE
using pipe to denote the "should" boolean operator nests instead of building a flat list

### ISSUE THREAD

**Issue by vahana** [elastic/elasticsearch-dsl-py#468]
`In [11]: q = Q('bool')
    ...: for each in range(5):
    ...:     q = q | Q('match', val=each)
    ...:

In [12]: q.to_dict()
Out[12]:
{'bool': {'should': [{'bool': {'should': [{'bool': {'should': [{'bool': {'should': [{'bool': {'should': [{'bool': {}},
               {'match': {'val': 0}}]}},
            {'match': {'val': 1}}]}},
         {'match': {'val': 2}}]}},
      {'match': {'val': 3}}]}},
   {'match': {'val': 4}}]}}
`

instead it should be a flat list of matches

**Comment by HonzaKral** [comment]
This has been fixed in master:
```
In [1]: from elasticsearch_dsl import Q
In [2]: q = Q('bool')
In [3]: for x in range(5):
   ...:     q |= Q('match', f=x)
In [4]: q
Out[4]: Bool(should=[Match(f=0), Match(f=1), Match(f=2), Match(f=3), Match(f=4)])
```

Thank you for the report!
