### ISSUE TITLE
Another Nested Field Question

### ISSUE THREAD

**Issue by Archetype90** [elastic/elasticsearch-dsl-py#475]
Hello,

I am so sorry to ask what I feel is a duplicate question, but I have tried the solution that was outlined here:

https://github.com/elastic/elasticsearch-dsl-py/issues/445

But I did not have any luck. A sample of the data I am trying to query (copied from Kibana) can be seen here:

```
"_id": "AVe9xTCMArDL6rID92QL",
  "_score": null,
  "_source": {
    "message": "message goes here",
    "@version": "1",
    "@timestamp": "2016-10-13T11:19:42.760Z",
    "path": "/test/path/here",
    "host": "node1",
    "type": "log",
    "ts": "112438512375",
    "uid": "Ci232358fJSFIUfk2"
     ..........
     ..........
    }
}
```

My query can be seen here: 

```
s = Search(using=client, index="logstash-*") \
        .query("nested", path="_source", query=Q("match", _source__proto= "udp"))
```

I have tried this query with "source" "_source", removing source entirely to just query proto, etc. None of them will work. The one above, which I expected would work and copied from the example in the thread above, produces the following error: 

> elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', '[nested] failed to find nested object under path [_source]')

Again, I am sorry for the likely duplicate and I appreciate any help that you can provide.

**Comment by andreyrusanov** [comment]
@Archetype90 what was the reason of the issue?

**Comment by Archetype90** [comment]
@andreyrusanov Oh gosh, this was months ago - I should have posted the resolution! I believe my confusion was thinking that I needed to access the proto field with _source, but the result actually returned everything inside of source, and it was not a nested query at all (so just proto="udp").
