### ISSUE TITLE
Passing global parameter to aggregation. 

### ISSUE THREAD

**Issue by GayathriKaliyamoorthy** [elastic/elasticsearch-dsl-py#476]
Is there a way to add global options, as given in this [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-global-aggregation.html) through API. I am not able to figure out a way to add global option to aggregations from doc. Any help would be much appreciated.

**Comment by HonzaKral** [comment]
You can always use the name of the aggregation. To reproduce the first example would mean doing:
```
s = Search().query('match', title='shirt')
s.aggs.bucket('all_products', 'global').metric('avg_price', 'avg', field='price')
```

Hope this helps
