### ISSUE TITLE
Repackage lib to 2.4.1 with latest commits

### ISSUE THREAD

**Issue by SamuelRamond** [elastic/elasticsearch-dsl-py#478]
Hi,
Can you make a release + pypy with the last version of the code. We use this https://github.com/elastic/elasticsearch-dsl-py/commit/4b4487d0659ac8f2cf0e6499009ce696fca35684 in production for a few day it work well (see: https://github.com/elastic/elasticsearch-dsl-py/issues/402) 

Thank for your support :+1:

**Comment by vincentfretin** [comment]
Yes, please make a new release that include the fix
https://github.com/elastic/elasticsearch-dsl-py/commit/6cf0c624a0f3897825ff622090d90e6d8d7c9ca4#diff-990c7e0b85c1d53b28956b1d80edf253R109
I encountered the problem with version 2.4.0 and after an hour of searching what was wrong, I found this commit.

**Comment by HonzaKral** [comment]
Released as `2.2.0`, sorry it took so long!
