### ISSUE TITLE
queryes in a doctype with a scan search

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#483]
I was interested in to made a search over a Doctype object in with a query but I am not able to do it.

I tryed this:

```
s = MyDoctypeClass.search()
s.query("bool", must_not = [{"term": {"state": {"value": "final_state"}}}])
s.fields(['id_class', 'state'])

 txt = [h.id_class[0] for h in s.params(size=100).scan()]

```

The query that I was interested to use for my search was:

```
_search
{
    "query": {
        "bool": {
            "must_not": [
               {"term": {
                  "state": {
                     "value": "final_state"
                  }
               }}
            ]
        }
    },"fields": [
       'id_class', 'state'
    ]

```

And I want to use a scan search. Could somebody tell me something about this?? 

Thanks in advance

**Comment by HonzaKral** [comment]
`.query` returns a copy of the search object, it doesn't mutate it in place, you need to do:
`s = s.query(...)`. Same with other methods.

Hope this helps

**Comment by juandasgandaras** [comment]
Ok, it works perfectly!! 

Thanks for your quick help and your job with this library. It´s so functional. 

If ever you come to Galicia, I will invite to drink something.

Regards,

Juan
