### ISSUE TITLE
Getting most recent

### ISSUE THREAD

**Issue by matdrapeau** [elastic/elasticsearch-dsl-py#484]
I am trying to get the most recent item in a query but using any of those methods:

```
modelX.search().query()[:1]
modelX.search().query().params(size=1)
modelX.search().query().extra(size=1)
```

I get all items of the index.

Also, is there a way to get all the most recent items aggregated based on a field

**Comment by HonzaKral** [comment]
In order to get the latest document you need to sort by a field containing the date and then the call using `[:1]` should succeed:
```
s = modelX.search().sort('-DATE_FIELD')[:-1]
print(s.execute().hits[0], 'is the latest document')
```

Hope this helps
