### ISSUE TITLE
Add a delete to Search objects

### ISSUE THREAD

**Issue by alexgarel** [elastic/elasticsearch-dsl-py#490]
elasticsearch has a https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.delete_by_query method.

It could be nice to have a delete method on Search object that execute a delete_by_query using this search.

**Comment by mattjmcnaughton** [comment]
@HonzaKral @alexgarel Is there interest in this feature? If so, I'm happy to take a stab at submitting a pr to add it!

**Comment by HonzaKral** [comment]
A PR would be most welcome! Thank you!

**Comment by mattjmcnaughton** [comment]
Sounds like a plan!

**Comment by mattjmcnaughton** [comment]
Looks like this can be closed based on https://github.com/elastic/elasticsearch-dsl-py/commit/1a9092429ac582c0cf33f8d6287a20266be063cd - is that correct?

**Comment by alexgarel** [comment]
I agree this can be closed,  thanks.
