### ISSUE TITLE
Error when indexing id as UUIDField() in Django.

### ISSUE THREAD

**Issue by ashraful-robin** [elastic/elasticsearch-dsl-py#492]
In my model -- `id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)`

When I am trying to index it, then the error on the image. Without id indexing is perfectly done. Any solution for that ??

![elasticsearch-dsl-error](https://cloud.githubusercontent.com/assets/11586533/19959640/6393cdca-a1d2-11e6-9578-68f0d4311739.png)

**Comment by HonzaKral** [comment]
What is the mapping of the `id` field in elasticsearch? It looks like it's mapped to a numeric value so it is having trouble parsing the uuid.

**Comment by ashraful-robin** [comment]
I have used like that, Anything wrong?
`id = String(index='not_analyzed',  multi=True)`

**Comment by HonzaKral** [comment]
no, this looks good, can you share the whole code? Can you also verify that the mappings were indeed applied into elasticsearch?
Thanks

**Comment by ashraful-robin** [comment]
@HonzaKral  Please forget about my code. I can't share please.
Can you please tell me what I need to do exactly to support uuid in elasticsearch index? Thanks 
Any example please ??

**Comment by HonzaKral** [comment]
what you shared so far is ok, which leads me to believe that the mappings you have defined have not been transferred into elasticsearch properly. My guess is that you had some numerical ids which lead elasticsearch to map the id field as a numeric field and now it cannot parse the uuid. You need to look at the mapping as they exist in elasticsearch

**Comment by ashraful-robin** [comment]
@HonzaKral I have followed exactly same that you example was. 
[es-django-example](https://github.com/HonzaKral/es-django-example)
I really don't understand where you are doing mappings? And how I'll make a support for uuid. Thanks

**Comment by HonzaKral** [comment]
this is the line that creates the mappings in that case - https://github.com/HonzaKral/es-django-example/blob/master/qa/management/commands/index_data.py#L20

First you need to verify if that is indeed the problem by looking at the mappings directly in elasticsearch - `es.indices.get_mappings(index="mmq", doc_type="instrument")`

**Comment by ashraful-robin** [comment]
@HonzaKral Thanks for your kindness. It was mapping problem. It's Solved :+1:
