### ISSUE TITLE
Convert date/datetime strings to Python date/datetime

### ISSUE THREAD

**Issue by robhudson** [elastic/elasticsearch-dsl-py#5]
One of the nice things from elasticutils was automatic conversion of date/datetime strings in responses to Python date/datetime objects. What are you thoughts on adding something like that here?

Here's the code from elasticutils:
https://github.com/mozilla/elasticutils/blob/master/elasticutils/__init__.py#L423-L437

Something like this could be done at `getattr` time in `AttrDict`, updating the `_d` object on the fly on first access.

**Comment by barseghyanartur** [comment]
@HonzaKral:

```python
from dateutil import parser
parser.parse(obj)
```

And we get date or datetime object.

**Comment by HonzaKral** [comment]
@barseghyanartur: this is already done for you when you define your mapping in python via the `DocType` class
