### ISSUE TITLE
Dynamically creating many fields?

### ISSUE THREAD

**Issue by mikkel14** [elastic/elasticsearch-dsl-py#507]
Let's pretend I have 20 different scores I want to define mappings for. If I kept up the trend of the below code, creating an `Exam` object would mean passing many, many strings into its constructor.

```
class Exam(es.DocType):
    participant_id = es.String(index='not_analyzed')

    raw_score = es.Float()

    writing_score = es.Float()

    mastery_score = es.Float()

    adjusted_score = es.Float()
```

Is there a more graceful way to do this? In ES I would use a dynamic mapping, but I'm unsure of how to use this for this library.

**Comment by HonzaKral** [comment]
You can always just use dynamic mapping here as well, or you can generate these fields programatically by modifying the mapping object:
```
class Exam(DocType):
    pass

for score in ('raw', 'writing', '...'):
    Exam._doc_type.mapping.field('%s_score' % score, Float())
```

Hope this helps

**Comment by mikkel14** [comment]
Wonderful, thanks a lot!
