### ISSUE TITLE
Query boosting gives error

### ISSUE THREAD

**Issue by Tjorriemorrie** [elastic/elasticsearch-dsl-py#508]
error:
`2016-11-10 20:12:05,132 - DEBUG   - [base.py:log_request_fail] < {"error":{"root_cause":[{"type":"query_parsing_exception","reason":"[match] query parsed in simplified form, with direct field name, but included more options than just the field name, possibly use its 'options' form, with 'query' element?","index":"handhq","line":1,"col":77}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"handhq","node":"DkR6caf2SIKIsISg6cMxEQ","reason":{"type":"query_parsing_exception","reason":"[match] query parsed in simplified form, with direct field name, but included more options than just the field name, possibly use its 'options' form, with 'query' element?","index":"handhq","line":1,"col":77}}]},"status":400}`

Query:
```
                sea = sea.query('bool', should=[Q('match', player=p['name'], boost=10)])
                sea = sea.query('bool', should=[Q('match', vs=vs, boost=5)])
                sea = sea.query('bool', should=[Q('match', phase=phase, boost=2)])
                sea = sea.query('bool', should=[Q('match', site='handhq', boost=1)])
                sea = sea.query('bool', must=[
                    ~Q('match', action='gg') &
                    ~Q('match', action='sb') &
                    ~Q('match', action='bb')])
```

What I'm looking for is [query-time boosting](https://www.elastic.co/guide/en/elasticsearch/guide/current/query-time-boosting.html) but you don't have anything in your docs about it. Love your work nonetheless.

**Comment by HonzaKral** [comment]
your `match` queries must copy the format accepted by elasticsearch. If you want to specify any parameters you need to do:
```
{"match": {"player": {"query": p['name'], "boost": 10}}}
```
which translates into
```
Q('match', player={"query": p['name'], "boost": 10})
```

Hope this helps
