### ISSUE TITLE
anonymous filters aggregation support

### ISSUE THREAD

**Issue by addrians** [elastic/elasticsearch-dsl-py#509]
Hi,
I found no support for anonymous filters aggregation like in the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-filters-aggregation.html#_anonymous_filters).
Reading the [source code](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/aggs.py#L134) and [test suite](https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_aggs.py#L167) I could not figure out what to change from a dict argument to a list.
Thank you

**Comment by HonzaKral** [comment]
You are correct, currently there is no support for anonymous filter aggregations and due to limitation of our tooling (the way parameters for queries are defined) it probably won't be implemented in the near future. I am sorry for the inconvenience.
