### ISSUE TITLE
ImportError: cannot import name 'String'

### ISSUE THREAD

**Issue by shashank-ezdiagno** [elastic/elasticsearch-dsl-py#515]
version : 5.0.0

from elasticsearch_dsl import String
ImportError: cannot import name 'String'

Was there a reason to remove the string field. I can see it in 2.x version.

**Comment by shashank-ezdiagno** [comment]
Okay I can see in the changelog that String is deprecated.
 Can String be simply replaced by Text?
Don't understand the concept of Keyword.

**Comment by HonzaKral** [comment]
Yes, `string` type has been deprecated in elasticsearch. Use `Text` for string that you want to search over and `Keyword` for strings that you want to sort on, do exact matched and aggregate on. You can also do both using multi-fields (1)

Hope this helps

1 - https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html#multi-fields
