### ISSUE TITLE
Search.count with post_filter throws error

### ISSUE THREAD

**Issue by hvdklauw** [elastic/elasticsearch-dsl-py#518]
Seems the check in Search.to_dict for the if count needs to be before it adds the post_filter.

In this case the post_filter is on a aggs.bucket which doesn't get added.

**Comment by HonzaKral** [comment]
Thanks for the report. The question is whether we exclude the `post_filter` when doing `count` or throw a special exception. If we exclude it it might be confusing to people. What do you think?

**Comment by hvdklauw** [comment]
My expectation was that it would simply exclude the post_filter for the count.

The whole point of the dsl is that you can add things to the query set, throwing an error at that point puts you in a unrecoverable situation.

Sure it might be unexpected that it throws away the post filter, but I it already throws away some other things from the query.

**Comment by HonzaKral** [comment]
You are right, thanks for raising this issue, fix has been pushed to master.

**Comment by hvdklauw** [comment]
Thanks! Cleaning up for the new year? ;-)

**Comment by yanyumiao** [comment]
I found the same problem with es v5.0.2, it give "request does not support [post_filter]", how to save this ?

**Comment by hvdklauw** [comment]
Did you also upgrade the elasticsearch-dsl package?

**Comment by yanyumiao** [comment]
@hvdklauw 
no I doesn't use python, I use http rest API
es v2.3.3 _count _search both support post_filter
but only _search support post_filter in es v5.0.2
