### ISSUE TITLE
elasticsearch_dsl 5.0.0 doesnt seem to have String Fieldtype anymore !?

### ISSUE THREAD

**Issue by pythononwheels** [elastic/elasticsearch-dsl-py#519]
When I try to import  `String` from elasticsearch_dsl
 
I get the error:

`    from elasticsearch_dsl import DocType, String, Date, Nested, Boolean, \
ImportError: cannot import name 'String'`

if i print a `sorted(dir(elasticsearch_dsl))` there is no `String` as well.

There is a `Text` field(type), though.

I was testing the [persistence example from here:](https://elasticsearch-dsl.readthedocs.io/en/latest/)

**Comment by pythononwheels** [comment]
ok, I see that the documentation on the github README is updated but the not the one on readthedocs latests ... 

So there is no String anymore.

**Comment by HonzaKral** [comment]
I just added it back to `field.py` because it still is a valid field type for elasticsearch `5.0.0`. It is, however, deprecated and should not be used in new code, use `Text` and `Keyword` (for not analyzed strings) instead.

Thank you
