### ISSUE TITLE
1.x multi-field string field inside object isn't mapped

### ISSUE THREAD

**Issue by jbasko** [elastic/elasticsearch-dsl-py#521]
In 1.x branch, there is a bug in `Mapping.to_dict()` or somewhere below it that doesn't *serialize* mappings of object properties correctly.

When you map the doc type below, it won't have `address1.raw` or `address2.raw` mapped.

    class Location(DocType):
        # ... other things skipped ...
    
        address = Object(fields={
            'address1': Object(analyzer=queryable_analyzer, fields={
                'raw': String(index='not_analyzed'),
            }),
            'address2': String(analyzer=queryable_analyzer, fields={
                'raw': String(index='not_analyzed'),
            }),
        })

`address` field is mapped (when you inspect ES after creating the mapping) with this:

    "address": {
        "type": "object"
    },

To work around this, I created `class AddressObject` and implemented `to_dict()` which returns correct mapping:

    class AddressObject(Object):
        def to_dict(self):
            return {
                'properties': {
                    'address1': {
                        'type': 'string',
                        'analyzer': 'queryable_analyzer',
                        'fields': {
                            'raw': {
                                'type': 'string',
                                'index': 'not_analyzed',
                            }
                        }
                    },
                    'address2': {
                        'type': 'string',
                        'analyzer': 'queryable_analyzer',
                        'fields': {
                            'raw': {
                                'type': 'string',
                                'index': 'not_analyzed',
                            }
                        }
                    },
                }
            }

**Comment by HonzaKral** [comment]
The key you need to set for inner fields of an `Object` field is `properties`, not `fields` - just like in the dict. Same as the `Nested` field. Also it looks like `address1` in your example should be `String`, not `Object`.

Hope this helps

**Comment by jbasko** [comment]
Thanks @HonzaKral !

The `address1`: Object was a leftover of me trying different things, but the `properties` for `Object` solved it.
