### ISSUE TITLE
support for multiple sessions

### ISSUE THREAD

**Issue by pipoun** [elastic/elasticsearch-dsl-py#523]
I was looking for a simple way to handle multiples "sessions" at the same time, while using a common mapping. i.e. I need to store a list of pairs (index, connection/using) and use the same `DocType` classes. Consequently it's not possible to use the `_doc_type.index` and `_doc_type._using` attributes.

Regarding the search command, it would be possible to store a corresponding list of `Search(using=..., index=...)` objects but for other classmethods or methods such as `DocType.get`, `DocType.save` there's nothing.

If I look into sqlalchemy these commands are methods of a `Session` object (add, query, delete, ...). Of course there are other concepts involved with a transactional db.

As we are dealing with both classmethods and methods, maybe some kind of interface for DocType could be used?

A naive implementation :
```py
class Session(object):

    def __init__(self, using=None, index=None):
        self.using = using
        self.index = index

    def init(self, doc_type):
        # init signature is inverted ``init(cls, index=None, using=None)``
        doc_type.init(using=self.using, index=self.index)

    def search(self, doc_type):
        return doc_type.search(self.using, self.index)

    def get(self, doc_type, id, **kwargs):
        return doc_type.get(id, self.using, self.index, **kwargs)

    def delete(self, doc_type, **kwargs):
        doc_type.delete(self.using, self.index, **kwargs)

    def update(self, doc_type, **fields):
        doc_type.update(self, self.using, self.index, **fields)

    def save(self, doc_type, validate=True, **kwargs):
        return doc_type.save(self.using, self.index, validate, **kwargs)
```

usage :
```py
connections.configure(using1={'hosts': hosts1}, using2={'hosts': hosts2})
session1 = Session('using1', 'index1')
session2 = Session('using2', 'index2')

results = session1.search(MyDocType).filter(F(...)).execute()
for result in results:
    session2.save(result)

```

**Comment by HonzaKral** [comment]
Thank you for the issue, this is something I wanted the `Index` class to solve originally but I am not sure it goes far enough for your use case. What you can do currently is to use it for search:
```
i = Index('my-index', using='cluster-a')
i.search()
```

What we can do on top of it I think is:
* keeping track of the connection where a document came from (we already track the `index`)
* add some more methods to the `Index` class (like `get`) to make this easier
* Maybe even allow access to `DocType` classes through the `Index` object (`i["type_name"].get()` ?)

What do you think?

**Comment by pipoun** [comment]
Thanks for the quick reply, and the propositions, I had a look at the `Index` class and its indeed quite close of the `Session` described earlier.
Unfortunately I don't see clearly which modifications could be made:

* keeping track of requested documents, we still need to wrap the function to query a document. There's the save workflow to.

* add more methods like `get` will probably imply a modification in the `search` method, to accept a `doc_type` parameter, in order to have the same interface between those methods.
  * not sure the new `search` / `get` / `init` / `delete` / `update` / `save` methods would have the same semantic as Index `refresh` / `open` / `close` / ... perhaps we would loose consistency
  * the `doc_type` param should either be a string, a `DocType` subclass or a `DocType` subclass object : isn't it not advised to have too many possible types ?

* the dict-like interface is nice, but I think it's would be easier as an api - in some cases - to use directly the `DocType` class or object instead of a string

```py
i = Index('my-index', using='cluster-a')
user = User(name='alice')
i[User._doc_type.name].save(user)  # long, and accessing a "protected" object
i[User].save(user)  # some redundancy
i[user].save()  # shorter

user2 = i[User._doc_type.name].get('bob')  # long, and accessing a "protected" object
user2 = i[User].get('bob')
```
And for `DocType` classmethod like `search` or `get`, how the index and using could be added temporally ?

**Comment by HonzaKral** [comment]
Hi @pipoun, thanks again for the feedback and the discussion. Unfortunately, at this time, we cannot support said functionality as we do not believe it would be within the target scope of our library. There is a clear way of doing this (by passing `index=` and `using=` explicitly to relevant methods) and python solutions (just use a variable/method to specify those values?) to make it easier. It is also a functionality that is highly specific to a small subset of use cases that use multiple clusters and/or indices for the same `DocType`.
