### ISSUE TITLE
elasticsearch_dsl.exceptions.IllegalOperation: You cannot update analysis configuration on an open index...

### ISSUE THREAD

**Issue by richardasaurus** [elastic/elasticsearch-dsl-py#526]
I'm attempting to add a custom analyzer to a doctype:

```python
ANALYSER = analyzer(
    'my_analyzer',
    tokenizer=tokenizer('trigram', 'nGram', min_gram=6, max_gram=50),
    filter=["snowball"],
    char_filter=["html_strip"]
)


class ThingIndex(DocType):
    thing_id = String(analyzer=ANALYSER)

    class Meta:
        index = 'myindex'

def setup_mappings():
    ThingIndex.init()
```

If i delete my index with:

`curl -XDELETE http://localhost:9200/myindex`

then call `setup_mappings()`

I get the following error:

```
elasticsearch_dsl.exceptions.IllegalOperation: You cannot update analysis configuration on an open index, you need to close index myindex first.
```

What's the reason for this? And how do I get the custom analyzer working if I cannot this way?

Thanks in advance

`elasticsearch-dsl==2.1.0`

**Comment by shredding** [comment]
@richardasaurus I'm getting the same error, can u elaborate on why you closed it?

**Comment by richardasaurus** [comment]
@shredding it's not really an error

you need to close the index before updating mappings:

```
ThingIndex.close()
ThingIndex.init()
ThingIndex.open()
```
