### ISSUE TITLE
Update doesn't support modifying attrs directly on DocType.   DSL - 5.0.0 with ES 5.x, py3.5

### ISSUE THREAD

**Issue by ibigpapa** [elastic/elasticsearch-dsl-py#527]
**Behavior:**
  
Updating DocType doesn't appear to actually update the document.  I can call save but it will return   False.  The side effect is it does update in ES.

**Expected:**   
    
Update function to modify entry in Elasticsearch.

**Example:**

```python
from elasticsearch_dsl import DocType, Keyword
from elasticsearch_dsl.connections import connections

connections.create_connection(hosts=['localhost'])

class TestUpdate(DocType):
    testfield = Keyword(required=True)
    class Meta:
        index = 'testing'

TestUpdate.init()
t = TestUpdate(testfield='testing')
print(t.testfield)
>>> testing
t.save()
>>> True

t.testfield = 'bob'
t.update()
print(t.testfield)
>>> bob

t2 = TestUpdate.get(t.meta.id)
print(t2.testfield)
>>> testing

t.save()
>>> False
print(t.testfield)
>>> bob

t3 = TestUpdate.get(t.meta.id)
print(t3.testfield)
>>> bob

connections.get_connection().info()
>>> {'cluster_name': 'elasticsearch', 'tagline': 'You Know, for Search', 'cluster_uuid': 'gJHFlWyZQOWJ9bkSCRST9A', 'name': 'LDj-s4L', 'version': {'build_snapshot': False, 'number': '5.0.1', 'build_hash': '080bb47', 'build_date': '2016-11-11T22:08:49.812Z', 'lucene_version': '6.2.1'}}


import elasticsearch_dsl
print(elasticsearch_dsl.__version__)
>>> (5, 0, 0)

import sys
print(sys.version)
>>> '3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]'
```

**Comment by ibigpapa** [comment]
Update from original post.  I started to dive through the code to look into fixing it.  What i found was the update function expects the fields you want to update to be present as arguments.

I was expecting to be able to update the object by setting the attributes directly, and calling update without arguments.

not sure best solution to go forward with the behavior.  

1. Determine fields changed on instance, then merge those fields, then merge **kwargs (could be a compatibility issue if someone used this expecting it to overwrite any changes made to the instance.)
2. If **kwargs blank, determine fields changed on instance and update them.  if **kwargs has fields keep existing functionality/logic in place.
3. Make attributes read-only for instances from ES forcing error when attempting to write making it clear to use the update function. (I'm not in favor)

**Comment by HonzaKral** [comment]
I think the proper solution here would be for `update` to raise an exception when used without `fields` to avoid people getting confused.

Determining which fields changed on an instance is an expensive proposition (would require us to either keep the original around or fetch it when `update` is called) and wouldn't make much sense - at that point it's easier to just call `save` and it would have the same impact. The only benefit would be not transferring all the data over the wire.
