### ISSUE TITLE
Ability to configure request_cache on the Search class

### ISSUE THREAD

**Issue by benjaminrigaud** [elastic/elasticsearch-dsl-py#531]
It looks like a nice addition to be able to configure request_cache per query

http://elasticsearch-py.readthedocs.io/en/master/api.html?highlight=request_cache

**Comment by HonzaKral** [comment]
for any parameters that can be passed to https://www.theatlantic.com/please-support-us/?next=https://www.theatlantic.com/photo/2016/12/carry-me-ohio/507539/#seen you can use the `params` method:
```
s = Search()
s = s.params(request_cache=True)
```

Hope this helps.

**Comment by benjaminrigaud** [comment]
Thank you @HonzaKral : I missed that one, I was using update_from_dict.
Sorry for the disturbance.
