### ISSUE TITLE
[feature request] add def sort in faceted_search

### ISSUE THREAD

**Issue by arthurlogilab** [elastic/elasticsearch-dsl-py#532]
It would be useful to have a configurable sort on faceted searches. 

Right now I'm getting the desired result by overriding in query : 

```
from elasticsearch_dsl import FacetedSearch
class SortedFacetedSearch(FacetedSearch):
    def query(self, search, query):
        # XXX using query because there is no sort in faceted_search 
        search = super(SortedFacetedSearch, self).query(search, query)
        return search.sort('-sort_date')
```

but this is pretty hackish. Having a class attribute like fields could also be nice in this case.

**Comment by HonzaKral** [comment]
Thanks for the idea, I implemented it and also added an option to pass in simple sorting via `__init__`. Hope this helps

**Comment by wimglenn** [comment]
@HonzaKral   There's some problems with this implementation, which I've addressed in https://github.com/elastic/elasticsearch-dsl-py/issues/574
