### ISSUE TITLE
Update Documentation for String deprecation

### ISSUE THREAD

**Issue by clenk** [elastic/elasticsearch-dsl-py#534]
As explained in #515 and [the 5.0 changelog](https://github.com/elastic/elasticsearch-dsl-py/commit/032ddf71f6e47bbcfbeb0ab1e57ffca83c6f1d7f), String has been deprecated in favor of Text and Keyword. However, the documentation still refers to String and should be updated.

Specifically, I was running into errors following the Persistence examples in index.rst and persistence.rst.

**Comment by mattjmcnaughton** [comment]
I'll submit a pr to fix this - thanks for filing an issue!
