### ISSUE TITLE
Remove `String` from `field.py`

### ISSUE THREAD

**Issue by mattjmcnaughton** [elastic/elasticsearch-dsl-py#537]
My understanding is that `String` has been deprecated in favor of `Text` and `Keyword` in 5.0.0. However, the `String` class still exists in `elasticsearch_dsl/field.py`. As best I can tell, no other part of the code uses it, and [this pr](https://github.com/elastic/elasticsearch-dsl-py/pull/536) removes all mentions from the documentation.

I'll attach a pr in case its helpful. It's also entirely possible that I'm missing a reason why its important to keep it around, in which case feel free to close my pr.

**Comment by HonzaKral** [comment]
string is still valid type in elasticsearch so it should remain, to be removed in `6.0`. Thanks for raising the issue!
