### ISSUE TITLE
Support for Binary fields?

### ISSUE THREAD

**Issue by zetasyanthis** [elastic/elasticsearch-dsl-py#539]
Is support for Binary fields planned at any point, or somewhere I'm missing?

**Comment by Tjorriemorrie** [comment]
There is a `Boolean` doctype, so it is supported. And you should be able to just pass normal boolean values for the query: ` {'query': True, 'boost': 2}`

**Comment by zetasyanthis** [comment]
I was looking for the Binary data type, not Boolean. :P

https://www.elastic.co/guide/en/elasticsearch/reference/current/binary.html.

**Comment by mattjmcnaughton** [comment]
I'm happy to take a look at implementing this - am I correct that this would require implementing `_serialize` and `_deserialize` to convert from `base64` to `string` and back?

**Comment by mattjmcnaughton** [comment]
Nevermind, I think that `base64.b64encode` still results in a `str`, so we don't need to do anything special in terms of serializing and deserializing. I made a pr to support this change.

**Comment by HonzaKral** [comment]
Currently there is no plan to support binary fields as we cannot make their support consistent with the rest of the library and we feel they bring nothing to the table.

If you need to use binary fields there is also nothing stopping you from defining the field yourself in application code. Simply include:
```
class Binary(Field):
    name = 'binary'
```
And you can use it in your `DocType` classes.

Thank you and sorry for the delay!
