### ISSUE TITLE
Text(multi=True) not allowing me to save or write and errors when calling .append

### ISSUE THREAD

**Issue by ibigpapa** [elastic/elasticsearch-dsl-py#540]
Using Python 3.5

```python 
class Test(DocType):
  class Meta:
    index="testing"
  
  test_field = Text(multi=True)

  def save(self, **kwargs):
    self.test_field = ["a", "b","c"]
    super().save(**kwargs)

a = Test()
a.save()
```

If i break on line for super self object doesn't show any value for test_field.  It will write a document to the index but it will not have the test_field.

I've also tried to append like the documenation lists http://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html in the note section:

> passing in multi=True into the constructor (m.field('tags', String(index='not_analyzed', multi=True))). Then the value of the field, even if the field hasn’t been set, will be an empty list enabling you to write doc.tags.append('search').

```python 
class Test(DocType):
  class Meta:
    index="testing"
  
  test_field = Text(multi=True)

  def save(self, **kwargs):
    for elm in ["a","b","c"]:
    self.test_field.append(elm)
    super().save(**kwargs)

a = Test()
a.save()
>> "'tuple' object has no attribute 'append'"
```

**Comment by HonzaKral** [comment]
Could you please provide more information or a test case as I am having trouble replicating this. It works just fine for me:
```
>>> class DT(DocType):
...     t = Text(multi=True)
...     class Meta:
...         index = 'test-index'
...     def save(self, **kwargs):
...         self.t.append('a')
...         super().save(**kwargs)
>>> dt = DT()
>>> dt.save()
>>> dt.t
['a']
>>> DT.search().execute()[0].t
['a']
```

Thank you!

**Comment by HonzaKral** [comment]
I am closing this issue since i cannot replicate it, please feel free to reopen with new information. Thanks!
