### ISSUE TITLE
Yet another nested query problem

### ISSUE THREAD

**Issue by andreyrusanov** [elastic/elasticsearch-dsl-py#542]
Hi, I have following doctype:

```python
class Item(DocType):
    meta = Nested(
      doc_class=MetaData
)
```

I do a query on this doctype:
```python
Item.search().query('nested', path='meta', query=Q("match", `meta__code=meta_code))
```

But I got an error:
`elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', '[nested] failed to find nested object under path [meta]')`

I can fix it if I manually upload mapping to ES but I don't really want(for some reasons) to do it and what it to work based on elasticsearch-dsl doctypes. 

Thanks!

**Comment by HonzaKral** [comment]
Hi,
it looks like you haven't uploaded the mapping using `elasticsearch-dsl` to do that call `Item.init()` or use the `Index` object (0).

Hope this helps

0 - http://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#index

**Comment by andreyrusanov** [comment]
Hi Honza, 
Thank you, it resolved the problem!
