### ISSUE TITLE
Bug : Instantiating document with meta doesn't change _doc_type.index

### ISSUE THREAD

**Issue by jzbahrai** [elastic/elasticsearch-dsl-py#547]
When you instantiate a document with a an index field, it should change the doc_type.index too.
This should happen regardless if the class meta is defined. I am using the 2.0 library.

```
class Post(DocType):
    title = Text()
    title_suggest = Completion(payloads=True)
    created_at = Date()
    published = Boolean()
    category = Text(
        analyzer=html_strip,
        fields={'raw': Keyword()}
    )

    comments = Nested(
        doc_class=Comment,
        properties={
            'author': Text(fields={'raw': Keyword()}),
            'content': Text(analyzer='snowball'),
            'created_at': Date()
        }
    )

    class Meta:
        index = 'blog'
```

```
In ipython
In [2]: Post(meta={'_index':'products'})
Out[2]: {}

In [3]: print _2.meta.index
products

In [4]: _2._doc_type.index
Out[4]: blog

```

I think that's an error in implementation and both the meta.index and _doc_type.index should return the same thing

**Comment by HonzaKral** [comment]
the `_doc_type` is a class attribute and therefore cannot, and should not, be overridden from an instance. Is there any particular reason why you'd want it to change?

If you wish to get the index of a document, regardless of origin, you can use the `_get_index` helper method that will look for instance-level override and fall back to `._doc_type.index`.

Hope this helps

**Comment by jzbahrai** [comment]
The reason I wanted this is because I was using the elasticsearch.bulk.helpers and I wrote it as a class method. Even though I am using the instance with a new index, it looks for the _doc_type.index instead. 
```
   @classmethod
   def bulk_store(self, op_type, iterator):
        actions = (
            {
                '_op_type': op_type,
                '_index': self._doc_type.index,
                '_type': self._doc_type.name,
                '_id': doc['id'],
                '_source': {'doc': doc.to_dict(), 'doc_as_upsert': True}
            }
            for doc in iterator
        )
        result = elasticsearch.helpers.bulk(
            self._doc_type.using, actions, stats_only=True, chunk_size=1000
        )
```

I just found it confusing when the instance can refer to two different indices even though meta means to overwrite that. I understand the logic between not mixing the class and the instance though.

**Comment by HonzaKral** [comment]
If you wish to use the bulk helpers use `doc.to_dict(include_meta=True)` which will correctly include the proper index.
