### ISSUE TITLE
I want both script_fields result and source fieds

### ISSUE THREAD

**Issue by levylll** [elastic/elasticsearch-dsl-py#548]
I use script_fields to calculate the geo distance, but other source fields are not included in the response. I know "fields": [ "_source" ] could solve this problem. While fields are not supported in 5.0. What should I do?

**Comment by HonzaKral** [comment]
In 5.0 source filtering is recommended over stored (doc value) fields so `s = Search().source(True).script_fields(my_field='42')` should do the trick.

**Comment by HonzaKral** [comment]
Just released as `5.1.0` @levylll

**Comment by levylll** [comment]
@HonzaKral Thank your very much! :)
