### ISSUE TITLE
on .scan(): hit dict's _source is not handled correctly in non-Hit instances?

### ISSUE THREAD

**Issue by AndreCimander** [elastic/elasticsearch-dsl-py#549]
The current master seems to be mishandling the results from a scan search query. The scan hit-dict will be thrown into the DocType constructor as the meta parameter, resulting in a DocType result object without content.

A check within the DocType.__init__ if the meta dictionary contains a _source key fixes the problem. 
```
    if meta.get('_source'):
        kwargs.update(meta.get('_source'))
```

**Comment by HonzaKral** [comment]
Thanks for the catch, I added a test and a fix
