### ISSUE TITLE
support for parent_id query? :)

### ISSUE THREAD

**Issue by AndreCimander** [elastic/elasticsearch-dsl-py#550]
Hey,

could we get native support for the parent_id query? https://www.elastic.co/guide/en/elasticsearch/reference/5.x/query-dsl-parent-id-query.html

I couldn't dig deep enough to get a clear understanding, but just adding 
```
class HasParent(Query):
    name = 'parent_id'
    _params_def = {'query': {'type': 'query'}}
```
in the query.py should be enough? (I'll test it later today or tomorrow, as soon as our current firefighting mode is complete)

**Comment by HonzaKral** [comment]
actually just:
```
class ParentId(Query):
    name = 'parent_id'
```
should do the trick. You can even just add it in your code. I will push the code to the library when I get a chance.

Thanks for the report!

**Comment by mattjmcnaughton** [comment]
Submitted a pr with the fix in case it saves you a minute or two of him, @HonzaKral ! But if its easier for you to make the change, no pressure at all to use the pr.
