### ISSUE TITLE
TypeError: count() got an unexpected keyword argument 'size'

### ISSUE THREAD

**Issue by pmourlanne** [elastic/elasticsearch-dsl-py#551]
I'm having an issue with elasticsearch_dsl 5.0.0. Here's the code to reproduce the issue:

```
search = Search(using=my_client, index=my_index)
search = search.params(size=0)
print search.count()
```

This used to work in 1.X, but it does not work anymore. In 5.0.0, I get a TypeError: `TypeError: count() got an unexpected keyword argument 'size'`.

Am I doing something I'm not supposed to? Should I make a different call to set the search's size to 0?

**Comment by pmourlanne** [comment]
I got it working using the following:

```
search = Search(using=my_client, index=my_index)
search.update_from_dict({'size': 0})
print search.count()
```

I'm still surprised the `params` call did not work though :/

**Comment by HonzaKral** [comment]
Everything that is passed to `params` will be used as an argument when calling the API.

For pagination you also shouldn't use `size` as a parameter but instead in the body which would be accomplished by slicing on the search object - `s = s[0:0]`. In that case count will work as expected.

Hope this helps.

**Comment by pmourlanne** [comment]
I only wanted to set the size at 0 to be sure not to have any hits (I only care about aggregations and don't want to have cache miss because of the hits). Hence the slicing for pagination didn't appear to be fixing my issue.

But it does, thanks :>
