### ISSUE TITLE
count() got an unexpected keyword argument 'search_type'

### ISSUE THREAD

**Issue by Robitx** [elastic/elasticsearch-dsl-py#555]
Hey,
I've used the following function for a long time:

```
    def getCount(self, index=None, query="*", doc_type=None):
        index = index if index else self.indexes
        doc_type = doc_type if doc_type else self.doc_type

        s = Search(using=self.es, index=index, doc_type=doc_type)
        s = s.query(self.queryParser(query))
        s = s.params(search_type="count")
        return s.count()

```
but now after update of python packages I'm getting this trace..
```
    return s.count()
  File "/usr/lib/python3.6/site-packages/elasticsearch_dsl/search.py", line 569, in count
    **self._params
  File "/usr/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 71, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: count() got an unexpected keyword argument 'search_type'
```

Thanks for help.

**Comment by Robitx** [comment]
OK seems like
`        # s = s.params(search_type="count")
`
is no longer needed.

**Comment by mattjmcnaughton** [comment]
If its helpful at all, I think `search_type=count` was removed in ElasticSearch 5.0 - here's the [Changelog entry](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_search_changes.html). I'm guessing that updating the python packages updated you to using 5.0 version of elasticsearch-dsl.

**Comment by HonzaKral** [comment]
Hi,
the `search_type=count` parameter was never needed (or indeed used) by elasticsearch. It is just that elasticsearch `5.0` implemented strict parameter parsing and is now actively rejecting unknown parameters.

The `count` method on `Search` always used the dedicated `_count` API (0) which already uses the proper search type.

Hope this helps,
Honza

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html
