### ISSUE TITLE
Can't get hits.total when using filter_path

### ISSUE THREAD

**Issue by jminuscula** [elastic/elasticsearch-dsl-py#559]
I'm using filter_path to filter the response on my aggregations, but I'm also interested in knowing the total number of hits for the query. For that, I'm adding `hits.total` to the filter_path list parameter.

The result object looks as expected:
```
ipdb> dir(result)
['aggregations', 'hits']
```

However, when I try to access the field in the result object, a KeyError exception is raised:
```
ipdb> result.hits
*** KeyError: 'hits'
```

Although if I inspect the result object, I see the total is there:
```
ipdb> result.__dict__['_d_']['hits']
{'total': 207}
```

Is there a way I can access this path? Thanks!

**Comment by jminuscula** [comment]
if I add `hits` to filter_path the total is indeed accessible, but defeats the purpose of using it in the first place.

**Comment by HonzaKral** [comment]
Unfortunately there is no way to guarantee correct behavior if you alter the response body through the use of `filter_path`.

If you are not interested in your hits, just want to see their total number just request `size: 0` in your request. That will not only save time on the transfer but also allow elasticsearch to optimize your query and run it much more efficently. To do that just slis the `Search` object: `s = s[0:0]`.

Hope this helps.

**Comment by jminuscula** [comment]
@HonzaKral thanks for your response! I think that may not cut it, though.

I am not interested in the hits, only the aggregations and the number of documents that match the query. I'm using `filter_path` to get rid of a lot of intermediary aggregations.

Filter path is the only way I've found to limit the transfer to just the required aggregations. I guess I could do a count query with the same filters?

Thanks!

**Comment by HonzaKral** [comment]
When you specify `size: 0` you still get the number of hits that matched the query.

**Comment by jminuscula** [comment]
@HonzaKral I'll look into it, thanks!

**Comment by jzbahrai** [comment]
Hey where did you add the filter_path to the request body? This says to add it in https://github.com/elastic/elasticsearch-py/blob/fc251751302da1b43a7789a402b03d87492c1227/docs/api.rst, but I can't do it to the dsl.Search object. Can you point me to where you would do it for the dsl? Thanks! @jminuscula

**Comment by jminuscula** [comment]
@jzbahrai sure, you should add it to the search object params:

```
Search(
            using=ElasticSearch(...),
            index='my_index',
            doc_type='document',
        ).params(
            filter_path=['hits.total', 'aggregations.my_aggregation', 'aggregations.myagg2.doc_count'] 
        )
```
