### ISSUE TITLE
How to use subclass of Search on DocType document

### ISSUE THREAD

**Issue by mojeto** [elastic/elasticsearch-dsl-py#564]
Hi,

I think a DocType is similar to a django Model and then the Search is similar to django QuerySet (in a way of usage).
Do I understand it right? 

So I think about extending Search object with some useful methods.
(Similar how I would do it with django QuerySet)

A small example:
```

from elasticsearch_dsl import DocType, field
from elasticsearch_dsl import Search


class ProductSearch(Search):

    def is_active_on(self, date=None):
        date = date or 'now'
        return self.filter('range', starts_at={'lte': date}).filter(
            'range', ends_at={'gte': date}
        )


class Product(DocType):

    starts_at = field.Date()
    ends_at = field.Date()


    # my current implementation to make it works
    search_class = ProductSearch

    @classmethod
    def search(cls, using=None, index=None):
        return cls.search_class(
            using=using or cls._doc_type.using,
            index=index or cls._doc_type.index,
            doc_type={cls._doc_type.name: cls.from_es},
        )

# usage
# Product.search().is_active_on('2017-02-01')
```

To achieve it I have to overwrite `def search(...`
The `search` method changed between 1.x and 5.x version of elasticsearch_dsl which makes my example future incompatible. 

Can we change search method to allow to choose specific Search subclass? 

Or Is there a better way to achieve similar functionality? 

Cheers

**Comment by HonzaKral** [comment]
The difference between `Search` and `QuerySet` is that `QuerySet` is typically `Model`-specific whereas `Search` can be querying multiple indices and types at the same time.

Your solution makes sense if you don't want to use multiple document types at the same time. Another option might be to have a `search_for_active_on` method directly on `Product` that would just call `self.search()` and apply the filter. Or you could have a class method on `Product` that will accept a `Search` object and apply the filter...

I don't think there is a preferred solution as most of it depends on specific details for each case. Maybe it is time we introduce something like a `Manager` (to keep up with the Django comparisons)?

**Comment by mojeto** [comment]
Hi,
I have no plan to search multiple document types in my use case (for now).
The main reason to inherited from `Search` for me is to chain method calls. like:
```
Product.search().is_active_on('2017-02-01').in_category('travel')
```
I'm keen to create _a specific manager/search method on Product class_ like:
```
Product.product_search().is_active_on('2017-02-01').in_category('travel')
```
but in this case some helper method/function to help me create an instance of `ProductSearch` bounded to Product document would be helpful. 

What do you think?

**Comment by mojeto** [comment]
Ok, I have found two possible solutions 
1. Add search class as a parameter of search method 
```
@add_metaclass(DocTypeMeta)
class DocType(ObjectBase):
    """
    Model-like class for persisting documents in elasticsearch.
    """

    @classmethod
    def search(cls, using=None, index=None, search_class=Search):
        """
        Create an :class:`~elasticsearch_dsl.Search` instance that will search
        over this ``DocType``.
        """
        return search_class(
            using=using or cls._doc_type.using,
            index=index or cls._doc_type.index,
            doc_type=[cls]
        )
```
2. add search class as a attribute of DocType 
```
@add_metaclass(DocTypeMeta)
class DocType(ObjectBase):
    """
    Model-like class for persisting documents in elasticsearch.
    """

    _search_class = Search

    @classmethod
    def search_class(cls, search_cls):
        cls._search_class = search_cls

    @classmethod
    def search(cls, using=None, index=None):
        """
        Create an :class:`~elasticsearch_dsl.Search` instance that will search
        over this ``DocType``.
        """
        return cls._search_class(
            using=using or cls._doc_type.using,
            index=index or cls._doc_type.index,
            doc_type=[cls]
        )
```
@HonzaKral which method do you prefer more? 
Shall you consider to backport this feature into legacy version (2.x and 1.x) as well?

**Comment by HonzaKral** [comment]
Hi @mojeto, I think this is code that can comfortably live outside of the main library in your application code - if you need a custom `search` method I would recommend that you create one as you specify in example `1.`. Thanks for the feedback!
