### ISSUE TITLE
Conveniences classes from 2.x missing in 5.x

### ISSUE THREAD

**Issue by zahir-koradia** [elastic/elasticsearch-dsl-py#566]
Is there any reason for dropping many convenience classes for filters (and may be others) in elasticsearch-dsl 5.x?

If it is only about having someone port them then I could work on it.

**Comment by brainix** [comment]
I could be wrong, but I think it's because from a user's point of view, filters *are* queries now? Recent releases of Elasticsearch can determine context - and treat queries as filters within a filter context.

**Comment by HonzaKral** [comment]
Exactly as @brainix is correct - filters were removed in elasticsearch 5 so we removed that distinction from the library as well to maintain the mapping of the library's functionality and classes to the underlying DSL.

Hope this helps
