### ISSUE TITLE
ImportError: No module named 'elasticsearch.helpers'

### ISSUE THREAD

**Issue by apiszcz** [elastic/elasticsearch-dsl-py#567]
It seems search.py requires helpers not in my path? they exist in elasticsearchpy/helpers

(Pdb) from elasticsearchpy import Elasticsearch
(Pdb) import elasticsearch_dsl
*** ImportError: No module named 'elasticsearch.helpers'
(Pdb) from elasticsearch_dsl import DocType
*** ImportError: No module named 'elasticsearch.helpers'

**Comment by mattjmcnaughton** [comment]
Just going on a hunch here, so my apologies if this isn't helpful.

Is there any chance that you renamed, or didn't install, the [elasticsearch-py](https://github.com/elastic/elasticsearch-py) library? The documentation for [elasticsearch-py](https://github.com/elastic/elasticsearch-py) shows the import as `from elasticsearch import Elasticsearch`?

The fact that `from elasticsearchpy import Elasticsearch` succeeded while importing `elasticsearch.helpers` failed makes me think that somehow the `elasticsearch` module got renamed to `elasticsearcypy`.

**Comment by apiszcz** [comment]
That is correct! Thank you.

**Comment by HonzaKral** [comment]
Thank you, @mattjmcnaughton, for the help! Closing the issue.
