### ISSUE TITLE
Updating from 1.x to 2.x with Faceted Search

### ISSUE THREAD

**Issue by alexkahn** [elastic/elasticsearch-dsl-py#573]
I'm in the process of updating from 1.x to 2.x and wanted to contribute something (not necessary for most I'd venture) to those who might face a similar issue.

We use a lot of aggregations and some of them are based on Booleans.

I ran into this issue where the new representations were making downstream code work incorrectly because what looks like bare numbers are going down the wire.

So for those of you who would rather work with strings, here is a subclass of the TermsFacet that worked for us.

```py
class BooleanFacet(TermsFacet):
    """
    Specialized terms facet for using strings as values.
    """
    def get_value(self, bucket):
        return bucket['key_as_string']
```

Meta:
  I wanted to file this as an issue since it doesn't seem appropriate for the core of the library - if that isn't the case, I'd be happy to furnish a PR to add this into docs or the library itself.

**Comment by HonzaKral** [comment]
This has actually been fixed in 4b09ccd as part of #583 - not `TermsFacet` on `Boolean` fields properly return python `bool` types - `True` or `False`.

But this might be useful for people looking for string representation, thank you for submitting it!

**Comment by alexkahn** [comment]
I'm sort of stuck in ES 2.4 (for now) - is this commit going to be released on the 2.x branch? Is there any active development going on there?

**Comment by HonzaKral** [comment]
Hi, this will not be backported to `2.x` since it used the aggregation deserialization mechanism that was only introduced in `5.0`. For `2.x` you have to still do the deserialization manually.

Sorry for the inconvenience

**Comment by alexkahn** [comment]
It's no inconvenience - just incentive to get on to 5.x.

Also, thanks to you and the other collaborators for putting together this excellent library - it's nice to not need haystack anymore (not a knock on them, just want to be able to fully utilize elastic) and do it in a pythonic way.
