### ISSUE TITLE
0 hits from FacetedSearch when not specifying doc_types

### ISSUE THREAD

**Issue by gregpinero** [elastic/elasticsearch-dsl-py#581]
I'm trying something simple to see if I can get it working:  (I'm on 5.1)

```
class DogSearch(FacetedSearch):
    fields = ['fleas']
    facets = {
        'fleas': TermsFacet(field='fleas'),
    }
    index = [settings.ASSOCIATIONS_INDEX_NAME]

rs = DogSearch()
response = rs.execute()
```

But I'm getting 0 hits when I know there are lots of results.

Here's what it's generating when I run it:

`{"query": {"match_all": {}}, "aggs": {"_filter_fleas": {"filter": {"match_all": {}}, "aggs": {"fleas": {"terms": {"field": "fleas"}}}}}, "highlight": {"fields": {"fleas": {}}}}`

`{"took":3,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]},"aggregations":{"_filter_fleas":{"doc_count":0,"fleas":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[]}}}}`

Could something be going wrong in the query, or am I just using this wrong?

**Comment by HonzaKral** [comment]
What happens if you the query manually?
```
s = Search(index=settings.ASSOCIATIONS_INDEX_NAME)
print(s.count())
```

It really looks like there are no documents in your index since the query is empty (just a `match_all`) and returns no hits.

Thanks

**Comment by gregpinero** [comment]
I get results from that.

```
(Pdb) Search(index=settings.ASSOCIATIONS_INDEX_NAME).count()
INFO 2017-02-07 16:55:12 EST requests.packages.urllib3.connectionpool connectionpool.py:242 123145310715904 - Resetting dropped connection: ...
DEBUG 2017-02-07 16:55:13 EST requests.packages.urllib3.connectionpool connectionpool.py:387 123145310715904 - "GET /associations/_count HTTP/1.1" 200 64
INFO 2017-02-07 16:55:13 EST elasticsearch base.py:80 123145310715904 - GET https://search-...:443/associations/_count [status:200 request:0.991s]
DEBUG 2017-02-07 16:55:13 EST elasticsearch base.py:82 123145310715904 - > {"query": {"match_all": {}}}
DEBUG 2017-02-07 16:55:13 EST elasticsearch base.py:83 123145310715904 - < {"count":200000,"_shards":{"total":5,"successful":5,"failed":0}}
200000
```

**Comment by gregpinero** [comment]
Could it be that the aggs section needs a "global": {}?

**Comment by HonzaKral** [comment]
No, the problem is not with aggregations, but with the actual hits. the query you sent should be the same I had you run manually so there is absolutely no reason for it to have different results. There is something weird in your environment. What happens if you run the json generated from the faceted search manually via `curl` or `console` in kibana?

**Comment by OskarPersson** [comment]
I have the same problem, no results when using a `FacetedSearch`. Copying the json from `.build_search()` and running it through `curl` returns the expected results.

I'm running 

```
Version: 5.6.3
Build: 1a2f265/2017-10-06T20:33:39.012Z
JVM: 1.8.0_60
OS: macOS 10.13.1
```

**Comment by HonzaKral** [comment]
@OskarPersson thanks for the report, could you please share the code you are using?

**Comment by OskarPersson** [comment]
I start of by creating an index with two documents:

```
$ curl -XPOST 'localhost:9200/items/external?pretty&pretty' -H 'Content-Type: application/json' -d '{"name": "foo"}'
$ curl -XPOST 'localhost:9200/items/external?pretty&pretty' -H 'Content-Type: application/json' -d '{"name": "bar"}'
```

I've setup the following `FacetedSearch`:

```
from elasticsearch_dsl import FacetedSearch

class ItemSearch(FacetedSearch):
    index = 'items'
    fields = ['name']
```

To test it I run this:

```
Python shell history and tab completion are enabled.
Python 2.7.13 (default, Apr 11 2017, 22:20:50)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.41)] on darwin

>>> from mymodule import ItemSearch
>>> ItemSearch('foo').execute()
<Response: []>
```

**Comment by HonzaKral** [comment]
I see, the problem is that we default to `doc_types = ["_all"]` which no longer works on elasticsearch 5.x, my bad, sorry about that!

As a quick workaround please set `doc_types = ['external']` on your `ItemSearch`.

**Comment by OskarPersson** [comment]
Oh okay, is there an alternative I can use to target all types without manually listing them?

**Comment by HonzaKral** [comment]
use `None` for `doc_types` then, I will change it to be the default
