### ISSUE TITLE
Index.clone() does not copy Index._analysis

### ISSUE THREAD

**Issue by nazarewk** [elastic/elasticsearch-dsl-py#582]
I am not sure if it's intended or not but `Index.clone()` does not copy `_analysis` attribute.

**Comment by HonzaKral** [comment]
that is definitely a bug and should be fixed, thank you for the report, much appreciated!

**Comment by mattjmcnaughton** [comment]
Happy to take a stab at this one @HonzaKral if it takes something off your plate! No worries if not though. Whatever is best for you!

**Comment by HonzaKral** [comment]
As always, PRs are most welcome @mattjmcnaughton! Feel free to submit anything, I will make reviewing it a priority.

Thank you!

**Comment by mattjmcnaughton** [comment]
Sweet, made a pr - thanks @HonzaKral !

**Comment by HonzaKral** [comment]
Thanks for the PR!
