### ISSUE TITLE
Automatic indexing when object created

### ISSUE THREAD

**Issue by yarnball** [elastic/elasticsearch-dsl-py#584]
Hi,

Great work on this project.

I am having trouble with automatically indexing newly created objects with `groupby`.

Every time a new model is created, it should index it.

However, it only indexes the "title" value. It does not index the "tag".

So, I created a manual function `manual_index`. When I run that, the "tag" value does get added to the index. However this process has to be manually triggered.

How can I get the "tag" value to save every time a new object is created?

***Search.py***

```
class TaskIndex(DocType):
    title = String()
    class Meta:
        index = 'task-index'

def manual_index():
    TaskIndex.init()
    es = Elasticsearch()
    bulk(client=es, actions=(b.indexing() for b in models.Task.objects.all().iterator()))
```

**Models.py**

```
from itertools import groupby

class Tag(models.Model):
    name = models.CharField("Name", max_length=5000, blank=True)
    taglevel = models.IntegerField("Tag level", null=True, blank=True)

class Item(models.Model):
    title = models.CharField("Title", max_length=10000, blank=True)
    tag = models.ManyToManyField('Tag', blank=True)

    def get_grouped_tags(self):
        tag = self.tag.order_by('taglevel')
        grouped_tags = {
            tag_level: [
                { 'name': tag_of_level.name, 'taglevel': tag_of_level.taglevel, }
                for tag_of_level in tags_of_level
            ] for tag_level, tags_of_level
            in groupby(tag, lambda tag: tag.taglevel)
        }
        return grouped_tags

    def indexing(self):
        obj = TaskIndex(
            meta={'id': self.id},
            title=self.title,
            tag=self.get_grouped_tags()
        obj.save()
        return obj.to_dict(include_meta=True)
```

**Comment by HonzaKral** [comment]
Hi, there are several issues here, first of all you are saving everything twice - once inside `indexing` (by calling `.save()`) and then in `manual_index`.

The code in `manual_index` is way more efficient and definitely should be around for reindexing the whole dataset. For individual model creation you can just use the `indexing` method almost as is and use django's `signal` framework. Just modify the `indexing` method to return the `TaskIndex` object (without calling `.save()` on it!) and add the equivalent of the following code into your `models.py`: 
https://github.com/HonzaKral/es-django-example/blob/master/qa/models.py#L128-L137

In your code you will just use `indexing` instead of mine `to_search`.

Hope this helps,
Honza

**Comment by HonzaKral** [comment]
Oh, sorry, I overlooked your comment about the `tag` object. The issue there is that, on Django side, the `indexing` is triggered before the many to many data is saved. There are several ways around that, safest is to also use the `m2m_changed` signal - https://docs.djangoproject.com/en/1.10/ref/signals/#m2m-changed

**Comment by yarnball** [comment]
Hi @HonzaKral thanks.

I am not seeing it save twice, but I want to take your advice and fix it.

But I'm still not following. I tried doing as you recommended in the your first comment. But the below code tells me `manual_index takes no arguments (7 given)`.


**Search.py**
```
class TaskIndex(DocType):
    title = String()
    class Meta:
        index = 'task-index'

def manual_index():
    TaskIndex.init()
    es = Elasticsearch()
    bulk(client=es, actions=(b.indexing() for b in models.Task.objects.all().iterator()))
```


**Models.py**
```

...

    def get_grouped_tags(self):
        tag = self.tag.order_by('taglevel')
        grouped_tags = {
            tag_level: [
                { 'name': tag_of_level.name, 'taglevel': tag_of_level.taglevel, }
                for tag_of_level in tags_of_level
            ] for tag_level, tags_of_level
            in groupby(tag, lambda tag: tag.taglevel)
        }
        return grouped_tags

    def indexing(self):
        obj = manual_index(
            meta={'id': self.id},
            title=self.title,
            tag=self.get_grouped_tags()
        obj
        return obj.to_dict(include_meta=True)
```



I am trying to use the m2m_changed signal, and read through the docs. 


```
from django.db.models.signals import m2m_changed

class Tag(models.Model):
    name = models.CharField("Name", max_length=5000, blank=True)
    taglevel = models.IntegerField("Tag level", null=True, blank=True)

class Item(models.Model):
    title = models.CharField("Title", max_length=10000, blank=True)
    tag = models.ManyToManyField('Tag', blank=True)

    def get_grouped_tags(sender, **kwargs):
        tag = self.tag.order_by('taglevel')
        grouped_tags = {
            tag_level: [
                { 'name': tag_of_level.name, 'taglevel': tag_of_level.taglevel, }
                for tag_of_level in tags_of_level
            ] for tag_level, tags_of_level
            in groupby(tag, lambda tag: tag.taglevel)
        }
        return grouped_tags
        pass
m2m_changed.connect(tag_changed, sender=Item.tag.through)

**Comment by HonzaKral** [comment]
Please have a look at the example project.

This is your `indexing` method - note that it is returning the `TagIndex` object and not it's `to_dict` representation:
https://github.com/HonzaKral/es-django-example/blob/master/qa/models.py#L98-L100

This is how you connect signals - create 2 functions like these and attach the signals with `sender=Item`:
https://github.com/HonzaKral/es-django-example/blob/master/qa/models.py#L128-L137

This should work fine for you, then you can also add:
```
m2m_changed.connect(update_search, sender=Item)
```
to make sure the `Item` gets reindexed when the tag assignments change.

That is all you should need.

This will, however, break your `manual_index` function that need to be updated to include the `to_dict` call (note that I'd also recommend not using a custom Elasticsearch connection, but rely on the DSL to supply it):
```
from elasticsearch_dsl.connections import connections
def manual_index():
    TaskIndex.init()
    es = connections.get_connection()
    bulk(client=es, actions=(b.indexing().to_dict(include_meta=True) for b in models.Task.objects.all().iterator()))
```

Let

**Comment by yarnball** [comment]
Thanks but I am still not having success. I have attempted to follow. I get an `AttributeError: 'dict' object has no attribute 'to_dict'` for the following. 

But I do not feel I'm implemented what you said correctly as I do not understand fully.

```
class TaskIndex(DocType):
    title = String()
    class Meta:
        index = 'task-index'

def manual_index():
    TaskIndex.init()
    es = connections.get_connection()
    bulk(client=es, actions=(b.indexing().to_dict(include_meta=True) for b in models.Item.objects.all().iterator()))
```



```

class Tag(models.Model):
    name = models.CharField("Name", max_length=5000, blank=True)
    taglevel = models.IntegerField("Tag level", null=True, blank=True)

class Item(models.Model):
    title = models.CharField("Title", max_length=10000, blank=True)
    tag = models.ManyToManyField('Tag', blank=True)

    def get_grouped_tags(sender, **kwargs):
        tag = self.tag.order_by('taglevel')
        grouped_tags = {
            tag_level: [
                { 'name': tag_of_level.name, 'taglevel': tag_of_level.taglevel, }
                for tag_of_level in tags_of_level
            ] for tag_level, tags_of_level
            in groupby(tag, lambda tag: tag.taglevel)
        }
        return grouped_tags
        pass
        m2m_changed.connect(get_grouped_tags, sender=Item.tag.through)

def update_search(instance, **kwargs):
    instance.to_search().save()

def remove_from_search(instance, **kwargs):
    instance.to_search().delete()

post_save.connect(update_search, sender=Item)
post_save.connect(update_search, sender=Tag)
pre_delete.connect(remove_from_search, sender=Item)
pre_delete.connect(remove_from_search, sender=Tag)
```

**Comment by yarnball** [comment]
I have also made this attempt, but it tells me `'super' object has no attribute 'to_search'`.

I am unsure if I'm implementing it correctly.


```
from django.db.models.signals import m2m_changed, post_save, pre_delete

class Tag(models.Model):
    name = models.CharField("Name", max_length=5000, blank=True)
    taglevel = models.IntegerField("Tag level", null=True, blank=True)

class Item(models.Model):
    title = models.CharField("Title", max_length=10000, blank=True)
    tag = models.ManyToManyField('Tag', blank=True)

    @receiver(m2m_changed)
    def get_grouped_tags(sender, **kwargs):
        tag = self.tag.order_by('taglevel')
        grouped_tags = {
            tag_level: [
                { 'name': tag_of_level.name, 'taglevel': tag_of_level.taglevel, }
                for tag_of_level in tags_of_level
            ] for tag_level, tags_of_level
            in groupby(tag, lambda tag: tag.taglevel)
        }
        return grouped_tags

def to_search(self):
        d = super(Item, self).to_search()
        return TagDoc(meta={'id': d.pop('_id'), 'parent': self.name_id}, **d)

def update_search(instance, **kwargs):
    instance.to_search().save()

def remove_from_search(instance, **kwargs):
    instance.to_search().delete()

post_save.connect(update_search, sender=Item)
post_save.connect(update_search, sender=Tag)
pre_delete.connect(remove_from_search, sender=Item)
pre_delete.connect(remove_from_search, sender=Tag)
m2m_changed.connect(update_search, sender=Item)
```

**Comment by HonzaKral** [comment]
This is what your `to_search` method needs to be, all you have to do is remove the `save` and `to_dict` calls from your original `indexing` method:
```
    def indexing(self):
        return TaskIndex(
            meta={'id': self.id},
            title=self.title,
            tag=self.get_grouped_tags())
```
then the rest should work. The call to `super` was there purely because of my models in the example application.

I am also closing this issue since this is more of a django/python problem and not an issue for this library. Please feel free to contact me directly if you run into any further trouble.
