### ISSUE TITLE
Idiomatic way to run individual tests when developing

### ISSUE THREAD

**Issue by mattjmcnaughton** [elastic/elasticsearch-dsl-py#586]
My understanding is that `python setup.py test` can be used to run the entire test suite.

But is there a preferred way to only run the tests from a single file or even a single test? I would assume that it would be `pytest test_file.py`, but if that's the case, I'm not sure how to install the `tests_require` dependencies from [setup.py](https://github.com/elastic/elasticsearch-dsl-py/blob/master/setup.py#L19), other than installing them manually through `pip`? Perhaps its something I'm doing funny with my virtual environment, but the test dependencies do not remain accessible after running `python setup.py test`.

After I learn it, I'm happy to add whatever the preferred method is to `README.rst` if that would be helpful.

Thanks for your help!

**Comment by HonzaKral** [comment]
Hi, in 7fa25040d9ec8e62be2c6775d68a3fca9fd79afc I added `extras` to `setup.py` - now you can do `pip install -e .[develop]` to install all the dependencies, including the ones needed for tests.

Then you can run `pytest` directly or use the script in the test directory (which essentially just runs `pytest`).

Hope this helps

**Comment by mattjmcnaughton** [comment]
Oh wonderful, thank you! I'll add a pr to add this to the README. If you think that's a good idea, than great. If not, no worries - feel free to close this issue.
