### ISSUE TITLE
Completion field type is presented in documents but it's not in code version 2.2.0 !

### ISSUE THREAD

**Issue by erfantahriri** [elastic/elasticsearch-dsl-py#588]

**Comment by HonzaKral** [comment]
It works fine for me: `from elasticsearch_dsl import Completion`, what exactly isn't working for you?

**Comment by erfantahriri** [comment]
It's my code that pycharm can't find Completion. Error on run
ArtistIndex.init(index='test_index') is:
RequestError: TransportError(400, u'illegal_argument_exception', u'mapper
[name_fa_suggest] of different type, current_type [string], merged_type
[completion]')

my elastic search-dsl version is definitely 2.2.0

**Comment by HonzaKral** [comment]
On Mon, Feb 13, 2017 at 11:53 AM, Erfan Tahriri <notifications@github.com>
wrote:

> It's my code that pycharm can't find Completion.


that is the problem with IDEs and dynamic languages, they cannot work 100%.
Also why I migrated away from dynamic class generation for 5.x



> Error on run
> ArtistIndex.init(index='test_index') is:
> RequestError: TransportError(400, u'illegal_argument_exception', u'mapper
> [name_fa_suggest] of different type, current_type [string], merged_type
> [completion]')
>

looks like you have a conflict in your mappings, this is unrelated to the
python library and is a problem with your configuration. It looks like you
have a field called name_fa_suggest mapped to string already in your index
which means you cannot change it. The only way to do it is to delete the
index.

**Comment by erfantahriri** [comment]
You are right. It;s work. Thank you for your considiration.
