### ISSUE TITLE
Specifying sort order for top_hits

### ISSUE THREAD

**Issue by anatekar** [elastic/elasticsearch-dsl-py#590]
Is there a way we could specify the sort order in top_hits aggregation.
Currently I use the following api:

s.aggs.metric('Marks_max','top_hits',size = 1, _source = ["Name","Subject.Marks"],
                      sort = 'Subject.Marks')

where s is my Search object. 

The query works fine however the sorting ordering applied is "asc". I would like to know if we can specify the sort order for top_hits aggregation as in above case.

-A.N

**Comment by mattjmcnaughton** [comment]
Thanks for the question!

Does it work to do use the `'-'` prefix to support sorting in `desc` order? I'm suggesting this based on the [sorting documentation](http://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#sorting). So for example, your query would be:
```
s.aggs.metric('Marks_max','top_hits',size = 1, _source = ["Name","Subject.Marks"], sort = '-Subject.Marks')
```

Hope that helps!

**Comment by HonzaKral** [comment]
Right now `-` is not supported outside of `Search.sort`. To specify an alternative sorting order for `top_hits` you need to specify the full sort definition: `sort=[{"Subject.Marjs": {"order": "desc"}}]`

**Comment by anatekar** [comment]
Thanks. That worked.
