### ISSUE TITLE
get() takes at least 2 arguments

### ISSUE THREAD

**Issue by fe7ch** [elastic/elasticsearch-dsl-py#592]
Hello,

I'm trying to make a basic communication with elasticsearch. I have an index with custom document type.

First, I initialize the index:

```
from elasticsearch_dsl import Search, Index
from elasticsearch_dsl.connections import connections
...
        connections.create_connection(hosts=['myhost'])
        index = Index('myindex')
        if not index.exists():
            index.settings(number_of_shards=1, number_of_replicas=0)
            index.doc_type(MyDoc)
            index.create()
```
Then I try to get a document with specific id:

`r = MyDoc.get(_id='some_string', ignore=404)`

But it results in exception:

```
    r = MyDoc.get(_id=h, ignore=404)
TypeError: get() takes at least 2 arguments (1 given)
```

I can't understand what does it expect ?

Your documentation has an example with such call (id and ignore as parameters) in Persistence chapter.

**Comment by HonzaKral** [comment]
the `id` argument to `get` is without the leading underscore - not `_id` but just `id`. Easiest is to just use it as a positional argument: `r = MyDoc.get(h, ignore=404)`

Hope this helps

**Comment by fe7ch** [comment]
Thanks for the advice, but it didn't help..

If I use `r = MyDoc.get(h, ignore=404)`, then I get 
```
    raise ValueError("Empty value passed for a required argument.")
ValueError: Empty value passed for a required argument.
```

**Comment by HonzaKral** [comment]
It looks like either `h` is empty or `MyDoc` doesn't have an `index` associated with it.

In your code you only associate the `MyDoc` class with the `Index` if it doesn't exist - so when it exists it won't work.

**Comment by fe7ch** [comment]
>You should be calling index.doc_type(MyDoc) every time.

Thanks a lot. Now it works.
