### ISSUE TITLE
How to add meta field to aggregation?

### ISSUE THREAD

**Issue by Alkalit** [elastic/elasticsearch-dsl-py#598]
According to official documentation I can add `meta` field to my aggregation

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html#_structuring_aggregations

But when I'm trying:
```
# from
# https://www.elastic.co/guide/en/elasticsearch/reference/current/agg-metadata.html#agg-metadata
client = Search(using=haystack_connections['default'].get_backend().conn, index='haystack', doc_type='modelresult')

var = {
  "size": 0,
  "aggs": {
    "titles": {
      "terms": {
        "field": "title"
      },
      "meta": {
        "color": "blue"
      }
    }
  }
}

searcher = client.update_from_dict(var)
```

 it raises an error:
`ValueError: A() can only accept dict with an aggregation ({"terms": {...}}). Instead it got ({'terms': {'field': 'title'}, '_meta': {'color': 'blue'}})`

**Comment by HonzaKral** [comment]
This has been fixed in 5bcb9ba84d72f46294728b5a66c6b02b0bc6dbb3
