### ISSUE TITLE
Using DocType with index alias breaks init()

### ISSUE THREAD

**Issue by candale** [elastic/elasticsearch-dsl-py#600]
Consider this code (with elasticsearch-dsl==5.1.0)

```python
from elasticsearch_dsl import Index, DocType, Text, analyzer, tokenizer
from elasticsearch_dsl.connections import connections


connections.create_connection()
es = connections.get_connection()

index = Index('cool_index')
index.aliases(cool_index_alias={})
index.create()

simple_analyzer = analyzer(
    'simple_analyzer',
    type='custom',
    char_filter=['html_strip'],
    tokenizer=tokenizer('whitespace'),
    filter='lowercase'
)

class AwesomeType(DocType):
    text = Text(analyzer=simple_analyzer)

    class Meta:
        index = 'cool_index_alias'


AwesomeType.init()
```

So what happens here is that I have a DocType that uses as index an alias name. When calling `init()` on `AwesomeType` it tries to save the mapping and reaches [here](https://github.com/elastic/elasticsearch-dsl-py/blob/2.x/elasticsearch_dsl/mapping.py#L72) where it tries to figure out if the index is closed or not, but because the index name is an alias, it won't find the name under the `indices` key, thus throwing a `KeyError`.

As far as I understand this is supported by the ES API because this works:

```python

from elasticsearch import Elasticsearch


es = Elasticsearch()

es.indices.create(
    index='cool_index',
    body={
        'settings': {
            'analysis': {
                'analyzer': {
                    'simple_analyzer': {
                        'type': 'custom',
                        'tokenizer': 'whitespace',
                        'filter': ['lowercase'],
                        'char_filter': ['html_strip']
                    }
                }
            }
        }
    }
)
es.indices.put_alias(index='cool_index', name='cool_index_alias')

es.indices.put_mapping(
    index='cool_index_alias',
    doc_type='awesome_type',
    body={
        "properties": {
            "text": {
                "type": "text",
                "analyzer": "simple_analyzer"
            }
        }
    }
)
```

My proposed solution, if I'm not mistaken and this is indeed a problem, is to figure out if the index name is an alias and, if so, get the names of the indices for which it is an alias. Then the 'is closed' check can be made on those names.

**Comment by candale** [comment]
Anyone, any opinions on this?

**Comment by HonzaKral** [comment]
Typically you have different code that handles your schema/migrations/index creation, easiest way to it with `elasticsearch-dsl` is:
```
from elasticsearch_dsl import Index, DocType, Text, analyzer, tokenizer
from elasticsearch_dsl.connections import connections


connections.create_connection()
es = connections.get_connection()

simple_analyzer = analyzer(
    'simple_analyzer',
    type='custom',
    char_filter=['html_strip'],
    tokenizer=tokenizer('whitespace'),
    filter='lowercase'
)

class AwesomeType(DocType):
    text = Text(analyzer=simple_analyzer)

    class Meta:
        index = 'cool_index_alias'


index = Index('cool_index')
index.aliases(cool_index_alias={})
index.doc_type(AwesomeType)
index.create()
```

That will properly create the index including the alias definition and the mappings.

**Comment by candale** [comment]
Consider, though, that you have an existing index and want to add a new mapping to it. As far as I can tell, `Index` does not offer an API for doing this so you have to stick to the doc type.

What you propose is a different way of reaching the same result. Either way, I believe that `DocType.init` should work with the use case given above, using an index alias because the ES API allows it.

**Comment by HonzaKral** [comment]
That is why `DocType.init` takes an `index` parameter so you can send it to a different index.

I am sorry, but adding mappings to an alias would be very confusing in elasticsearch and couldn't be fully supported. Mappings live in an index and the dsl cannot abstract away from it. If there is anything we can do to make it simpler please let me know, but everything you ask for is currently possible with the `Index` objects and `index` parameters that are accepted as overrides in most methods.
