### ISSUE TITLE
How can I use delete_by_query?

### ISSUE THREAD

**Issue by aayushiku** [elastic/elasticsearch-dsl-py#604]
I want to delete a particular document based on Id from the index. While exploring I found that delete_by_query had been deprecated but is now back in versions 5.1 and so on. Can someone please guide me on how and where can I find it in the library. I am using elastic search version 5.1.2

**Comment by HonzaKral** [comment]
Hi @aayushiku, if you want to delete a document based on `id` you don't need to use `delete_by_query` but can use the `delete` API (0) directly. You can either use the low level client (`elasticsearch-py`) or, if you are using `DocType` classes (1) you can do `MyDoc(_id=THE_DOC_ID).delete()` which might be easier.

Hope this helps,

0 - http://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.delete
1 - http://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#doctype

**Comment by gitanupam** [comment]
Hi @HonzaKral, I have been trying this out for sometime but it doesn't work for me and hence prompted me to look if its an open issue (looks like it isn't, though)

**Comment by gitanupam** [comment]
**Update:** 

The following worked after hit-and-trial (not sure why though since the docs don't mandate explicitly mentioning index, but maybe I got it wrong)

`OrgIndex.get(id=self.pk, index="org_index").delete()`
