### ISSUE TITLE
Multiline score_script fails with "was expecting one of <EOF>"

### ISSUE THREAD

**Issue by vladimirnani** [elastic/elasticsearch-dsl-py#605]
Hello. 
Im trying to execute this query:

```
boosted = Q(
    'function_score',
    query=q,
    functions=[SF('script_score', script="return _score;")],
    score_mode='sum'
)
```
Having following exception when using multiline score script

> {"type":"script_exception","reason":"Failed to compile inline script [return _score;] using lang [expression]","caused_by":{"type":"script_exception","reason":"Failed to parse expression: return _score;","caused_by":{"type":"parse_exception","reason":"parse_exception: unexpected token '_score' on line (1) position (7) was expecting one of \<EOF\>"}}}}}]},"status":400}

**Comment by HonzaKral** [comment]
This exact query works fine for me. Can you please specify what version of elasticsearch you are running? Thanks!

**Comment by HonzaKral** [comment]
Closing this due to lack of information, please feel free to reopen with additional information.
