### ISSUE TITLE
Getting offsets from highlight result

### ISSUE THREAD

**Issue by enod** [elastic/elasticsearch-dsl-py#606]
Hi there,

From the result of highlighting
 
```
response = s.execute()

for hit in response:

    for fragment in hit.meta.highlight.title:

        print(fragment)
```

is it possible to get other fields of the document? For example fragment like following: 

> Looking forward to bringing the party together," <em>Trump</em> said on Twitter.

I want to extract belonging document ID, title, offset etc.

**Comment by HonzaKral** [comment]
Yes, the `hit` object still contains all the relevant fields like `hit.title` etc
