### ISSUE TITLE
Cloning search object

### ISSUE THREAD

**Issue by zahir-koradia** [elastic/elasticsearch-dsl-py#607]
I can do Search()._clone() but I am hesitant to access internal methods. If it is acceptable, I can send a PR to expose the method. Please let me know.

**Comment by HonzaKral** [comment]
My question is why would you wish to clone the Search object as that shouldn't be needed in most cases.

**Comment by zahir-koradia** [comment]
I have a wide variety of filters and a very small subset are relevant (depending on the query). I use aggs to get limits for those filters. The way my code is organized I fetch limits for each filter separately. Something like
```Python
for f in filters:
    s = search._clone().aggs.metric('name', {})
    results = s.execute()
```

I would like to preserve the original search object to make sure I can run the search without having the aggregations run. I also dont want previous aggs to run everytime next aggs in the loop are run. I realize that chaining all aggs together would be faster, but that would require a fair amount or refactoring. Does that make sense?

**Comment by nguyening** [comment]
My use case for this is I'd like to construct the Search with Query in a different function (that takes user input) and query for multiple aggregations (that depend on the result of each other). My use case looks vaguely like this:

```
from elasticsearch import Elasticsearch
from elasticsearch_dsl import A, Q, Search


FUDGE_FACTOR = 1.10
NUM_PARTITIONS = 10


def _fetch_data(search):
    cardinality_search = search._clone()
    cardinality_search = search.aggs.bucket('distinct_ids', A('cardinality', field='id'))

    response = cardinality_search.execute()
    cardinality = response.aggregations.distinct_ids.value
    partition_size = math.ceil(cardinality * FUDGE_FACTOR)

    results = []

    for partition in range(NUM_PARTITIONS):
        real_search = search._clone()
        real_search.aggs.bucket('by_id', A('terms', field='id', include={'num_partitions': NUM_PARTITIONS, 'partition': partition}, size=partition_size))
        response = real_search.execute()
        results.append(response.to_dict())


def main(**kwargs):
    es = Elasticsearch()
    query = Q(**kwargs)
    search = Search(using=es).query(query)

    result = _fetch_data(search)
    print result
```

**Comment by HonzaKral** [comment]
I implemented `__copy__` so you can use python's standard `copy.copy` function to obtain copies of a `Search` object.

**Comment by G-K-Patel** [comment]
Hi HonzaKral, 

Do you think copy.copy should suffice, or copy.deepcopy might be needed in edge cases ? 

I don't have any working example that fails with copy.copy. But my feeling is that, copy.copy (shallow copy) is not good for nested dict, and I think there are some nested parameters in the Search class (although I am not the expert ). 

Thank you for your time.

**Comment by NLSVTN** [comment]
For me **copy** fails (elasticsearch-dsl - **6.4.0**), please, see: [](https://stackoverflow.com/questions/66068786/cant-copy-search-in-elasticsearch-dsl)

Was **__copy__** added in **6.4.0**?
