### ISSUE TITLE
Paging not working when use "query_string"

### ISSUE THREAD

**Issue by montenegrodr** [elastic/elasticsearch-dsl-py#611]
Assuming my query is:
```
my_query = 'name:Dave'
```
The following script works fine. I got the 20th to 30th docs.
```
s = Search(....)
s = s.query('match', name='Dave')
r = s[20:30].execute()
```
But when I use query_string, the paging does not work. It returns always the top-10 results, no matter which slicing values I use. 
```
s = Search(....)
s = s.query(Q('query_string', query='name:Dave'))  # tried without Q as well
r = s[20:30].execute()                             # this returns top-10 results
```

I've checked  `from`/`size` params stored in `s` and they are well assigned `(from=20, size=10)`. But it seems they are completely ignored when I use `query_string`.

**Comment by montenegrodr** [comment]
Debugging bit more, I found that for the first request (not using `query_string`) the request body is:

```
{
  "query": {
    "match": {
      "name": "Dave"
    }
  },
  "from": 20,
  "size": 10
}
```

And for the second snippet, the body is:

```
{
  "query": {
    "query_string": {
      "query": {
        "query_string": {
          "query": "name:Dave"
        }
      }
    }
  },
  "from": 20,
  "size": 10
}
```

Apparently, the [to_dict()](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L540) function is duplicating the `query_string` statement. ES isn't handling this format...

**Comment by HonzaKral** [comment]
I am having trouble replicating your issue:
```
>>> from elasticsearch_dsl import Search, Q
>>> s = Search()
>>> s = s.query(Q('query_string', query='name:Honza'))
>>> s.to_dict()
{'query': {'query_string': {'query': 'name:Honza'}}}
```
could you please specify what version of `elasticsearch-dsl` you are using? Thank you!

**Comment by montenegrodr** [comment]
Thanks for your reply. The bug was in my side. Sorry.
