### ISSUE TITLE
 fix error on aggregation over nested field 

### ISSUE THREAD

**Issue by erebus1** [elastic/elasticsearch-dsl-py#612]
I can't reopen this issue: #571 
So create a new one

**Comment by HonzaKral** [comment]
Apologies for missing the comments on the PR, it should be fixed now.

**Comment by erebus1** [comment]
@HonzaKral thanks, it fixed problem
Can you clarify, when you plan new release?

**Comment by HonzaKral** [comment]
I hope I will get to it this week. Again apologies for the delays, I cannot dedicate as much time to it as I would prefer.

**Comment by erebus1** [comment]
No problem, we've closed this problem by forking lib, but looking forward for official release!
Thanks for your fix!
