### ISSUE TITLE
Nested object not persisted as type nested?

### ISSUE THREAD

**Issue by danqing** [elastic/elasticsearch-dsl-py#613]
Hello,

I have the following DSL object (v2.2) that I'd like to persist:

```py
import elasticsearch_dsl as dsl

class Parent(dsl.DocType):
    child = dsl.Nested(
        properties={
            'content': dsl.String(),
            'language': dsl.String(),
        }
    )
```

I'd expect that the following is created:

```json
"child" : {
  "type" : "nested",
  "properties" : {
    "content" : {
      "type" : "string"
    },
    "language" : {
      "type" : "string"
    }
  }
}
```

However, the `"type" : "nested"` part was absent, indicating that an `object` type, not a `nested` type, was created for the child.

This is a problem for me, so I went ahead and created the above index manually. However, now I cannot save via DSL:

```
RequestError: TransportError(400, u'illegal_argument_exception', u'[indices:data/write/index[p]]')
```

Is there anything I missed?

Thanks!

**Comment by HonzaKral** [comment]
When was the `type: nested` [art missing? Did you properly create the index by calling `Parent.init()`?

**Comment by HonzaKral** [comment]
Closing this due to lack of followup, please feel free to reopen with more information!
