### ISSUE TITLE
Date range filter returns no entries if lte and gte are the same value

### ISSUE THREAD

**Issue by gladsonvm** [elastic/elasticsearch-dsl-py#616]
While trying to perform aggregations/filtering using date range filter, timestamp is not taken into consideration. What I have done is as below.

`>>>d1=datetime.datetime.strptime('2015-01-05','%Y-%m-%d')`
`>>>d2=datetime.datetime.strptime('2015-01-05','%Y-%m-%d')`
`>>>search_query = Search().using(client).index(index).doc_type(doc_type).query('match', myfield=7).filter('range', created={'gte':d1, 'lte':d2})`
`>>>resp=search_query.execute()`
`>>>resp`
`>>> <Response: []>`

But if I change d2

`d2=datetime.datetime.strptime('2015-01-05 23:59:59.999999','%Y-%m-%d %H:%M:%S.%f')` 

and then execute search_query with the same parameters, response will contain results. So I think this can be resolved by adding a time stamp to lte value of date range filters.

**Comment by m0uneer** [comment]
I have the same problem

**Comment by HonzaKral** [comment]
Hi @gladsonvm, elasticsearch doesn't have dates, only datetimes so your query is interpreted as looking for documents on `2015-01-05 00:00:00` *exactly*. To look for all documents from that day please use:
`.filter('range', created={'gte': date(2015, 1, 5), 'lt': date(2015, 1, 6)})`

Hope this helps
