### ISSUE TITLE
Search After

### ISSUE THREAD

**Issue by GuillaumeCisco** [elastic/elasticsearch-dsl-py#617]
Hello,
I encountered an issue with pagination and sorting with elasticsearch.
According to the doc, sorting with pagination can be done with a maximum number of 10 000 objects:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html

To solve this issue, elasticsearch created the `search_after` field: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html

Is it possible to achieve this easily with elasticsearch dsl ?

Thank you,

**Comment by HonzaKral** [comment]
Hi, you can use the `extra` method to spexify any additional keys you want present in the body. In this case it would be: `s = s.extra(search_after=[....])`

Hope this helps

**Comment by GuillaumeCisco** [comment]
Thank you @HonzaKral it helps :)
I was using `to_dict` and `from_dict` to update my query.

I think the doc should be updated to be more efficient, with examples.

**Comment by HonzaKral** [comment]
I added a little line to explain the `extra` method a bit better I hope.
