### ISSUE TITLE
Routing elastic search via another URL for filtering

### ISSUE THREAD

**Issue by yarnball** [elastic/elasticsearch-dsl-py#618]
Hi,

I'm using Django. How would I route my ElasticSearch URL to go via Django so that Django can filter the query?

**Comment by HonzaKral** [comment]
Hi, I am sorry but I don't understand your question. `elasticsearch-dsl` is just a python library for accessing data stored in Elasticsearch - it has no knowledge of Django nor does it require any special treatment or approach from django's side.

Use the `Search` object as you would a Django `QuerySet`.
