### ISSUE TITLE
version meta for hits

### ISSUE THREAD

**Issue by cockcrow** [elastic/elasticsearch-dsl-py#620]
I'm using `elasticsearch-dsl-py` and `elasticseach-py` for python. And recently, I'd like to use `elasticsearch-dsl-py` for query docs from elasticsearch and then update them in distributed cluster. Then  I want to use `version` meta for concurrency control.

Currently, it seems that I could pass `version=True` to [`Search.to_dict()`](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L530-L569) method.

Is there a handy way to fetch version meta from hits? Or would it be pretty to support the feature?

Looking forward to response.

**Comment by HonzaKral** [comment]
The `version` meta field is available as `.meta.version` and can be set via the same path. It is also automatically passed through, when available, and using the `.update` method on `DocType`.

Also note that you don't have to rely on `to_dict` but can use `s = s.extra(version=True)` which will have the same effect.

Hope this helps.
