### ISSUE TITLE
Allow override of DocType.meta.doc_type

### ISSUE THREAD

**Issue by mrname** [elastic/elasticsearch-dsl-py#631]
It is possible that this functionality already exists somewhere else and I am missing it, but I am using the DocType class to model a document. I would like to be able to save this object with an arbitrary document type, much the same way that "index" and "using" can be overwritten:

https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/document.py#L23

The purpose here is that I have a document that uses a field from the payload to determine it's document type, so I want to calculate it on the fly before I save it.

Please advise if there is a better way to do this with the DSL. If not, I am happy to make a pull request unless there is a compelling reason to disallow override of this attribute.

Thanks!

**Comment by HonzaKral** [comment]
Hi @mrname, this is unfortunately not possible. We will also not be adding this since doc types are going away in elasticsearch 6.x.

Currently the only way to handle it is to have multiple (sub)classes and do the differentiation in python.
