### ISSUE TITLE
Add parameter to allow specification of query field name as string

### ISSUE THREAD

**Issue by thigg** [elastic/elasticsearch-dsl-py#632]
If I want to produce a query like this:

    "query": {
        "term" : { "doc.content" : "searchterm" } 
    }

I would have to do this:
 
    Q("term" doc.content="searchterm")

But this is no valid python.

**Comment by thigg** [comment]
Oh, it seems to be actually possible with:

     Q("term",**{"doc.content":searchterm})

Maybe the documentation could mention this.

**Comment by HonzaKral** [comment]
The documentation mentions that in http://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#queries

You can also do `Q('term', doc__content="searchterm")` which the documentation doesn't mention and that's a bug.

Thanks for bringing this up!

**Comment by thigg** [comment]
@HonzaKral Is this mentioned now in the docs?
