### ISSUE TITLE
DocType - How do I setup the index.mapping.nested_fields.limit?

### ISSUE THREAD

**Issue by nommack** [elastic/elasticsearch-dsl-py#638]
Hi, this is my first post here.
I've tried to find an answer to this but no luck so far.

I'm using DocType for a deep nested JSON but when I try to run my script (python) it gives me the following error:
"Failed to parse mapping [xxxx] limit of nested fields [50] has been exceeded"

How can I setup the number of nested fields using elasticsearch-dsl.py?

Thank you very much for all.
Kind reagards

**Comment by HonzaKral** [comment]
This is an index-level setting so you need to use the `Index` object to manage those:
```
i = Index('my-index')
i.settings(**{"index.mapping.nested_fields.limit": 100})
@i.doc_type
class MyDocType(DocType):
    ....

i.create()
```

Sorry for the delay!
