### ISSUE TITLE
No scaled_float datatype in mapping

### ISSUE THREAD

**Issue by TonyRehley** [elastic/elasticsearch-dsl-py#644]
and possibility to define  "scaling_factor".

**Comment by WisdomPill** [comment]
from elasticsearch_dsl import DocType, Field
    from elasticsearch_dsl.connections import connections
    
    connections.configure(default={'hosts': 'localhost'})
    
    
    class ScaledFloat(Field):
        name = 'scaled_float'
    
    
    class Test(DocType):
        scale_float_field = ScaledFloat(scaling_factor=100)
    
        class Meta:
            index = 'test'
    
    Test.init(index='test')
