### ISSUE TITLE
_refresh api

### ISSUE THREAD

**Issue by echo1248** [elastic/elasticsearch-dsl-py#652]
there is refresh method for dealing index.refresh_interval ? such as (https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-refresh.html)

**Comment by HonzaKral** [comment]
`index.refresh_interval` is an index-level setting and as such can be used from the `Index` object - either when creating you can specify settings by calling the `settings` method:
```
i = Index('my-index')
i.settings(index={'refresh_interval': -1})
# add mappings/DocTypes to i, add other settings etc here
i.create()
```

Or, when an index is already created by either modifying the settings and calling `.save()` (which might be a bit tricky if you don't have your code completely synced up with the index in elasticsearch) or by calling the `put_settings` method:
```
i = Index('my-index')
i.put_settings(body={'index.refresh_interval': -1})
```

Hope this helps

**Comment by echo1248** [comment]
Elasticsearch automatically refreshes shards that have changed every index.refresh_interval which defaults to **one second**. but i want to update immediate. can any way to do?

**Comment by HonzaKral** [comment]
@echo1248 absolutely, just call `i.refresh()` in our example or use the low-level API to call the `refresh` API directly:
```python
from elasticsearch_dsl.connections import connections
es = connections.get_connection()
es.indices.refresh(index='my-index')
```

**Comment by littlehome-eugene** [comment]
can we use `refresh=wait_for` parameter ? https://stackoverflow.com/a/40678914/433570

**Comment by HonzaKral** [comment]
@littlehome-eugene, absolutely, when calling `save()` you can pass in any kwargs which will get passed to the underlying index API so you can do: `doc.save(refresh='wait_for')`.

**Comment by sebasromano** [comment]
@HonzaKral dumb question, i'm using bulk operations and i need to know if refrest='wait_for' ensures me that after the operation the documents are available for a search. I'm having an issue where it's taking a second after the operation to get the document ready. I have 2 replicas and 3 shards. I also tried with wait_for_active_shards but i continue having this problem.

**Comment by sebasromano** [comment]
I think this part of the documentation answers me: 

> Only the shards that receive the bulk request will be affected by refresh. Imagine a _bulk?refresh=wait_for request with three documents in it that happen to be routed to different shards in an index with five shards. The request will only wait for those three shards to refresh. The other two shards that make up the index do not participate in the _bulk request at all.
