### ISSUE TITLE
suggest mapping, query and _suggest end point deprecated

### ISSUE THREAD

**Issue by murdav** [elastic/elasticsearch-dsl-py#653]
Hello,

I would need to implement:

```
POST users/_search?pretty
{
    "suggest": {
        "title-suggest" : {
            "prefix" : "mar", 
            "completion" : {
                "field" : "suggest"
            }
        }
    }
}
```
e.g. looking for mar: marcus, markus, marc, marinella and so on.

Now, `_suggest endpoint has been deprecated in favour of using suggest in search `(https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html). 

The DSL doc says: "If you only wish to run the suggestion part of the search (via the _suggest endpoint) you can do so via execute_suggest:"

Hence, how can I do such query?

Thanks,

D

**Comment by HonzaKral** [comment]
Just calling `execute` should do it which will send the request to the standard `_search` endpoint.

We should probably clean that up and make it explicit in the documentation. Thanks for raising the issue!

**Comment by HonzaKral** [comment]
Closing this as the separate suggest endpoint has been removed in `6.0`

**Comment by peterbe** [comment]
Docs still need to be updated. 
https://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#suggestions
