### ISSUE TITLE
customize analyzers to perform search with and without hyphen

### ISSUE THREAD

**Issue by helmersl** [elastic/elasticsearch-dsl-py#658]
Hi,

I would like to perform a search where the search for "long-term" should match "long-term", "long term" and "longterm". At the moment, I'm using the standard analyzer for each field.
I tried to translate this analyzer: https://discuss.elastic.co/t/searching-with-combinations-of-space-and-with-and-without-hypens/37119
with the elasticsearch_dsl module:
```
my_analyzer = analyzer('my_analyzer',
    tokenizer="whitespace",
    filter=["lowercase", {"word_delim": {"type": "word_delimiter"},
               "catenate_words": True,
               "generate_word_parts": False,
               "generate_number_parts": False}]
)
```
and after connecting to my index with the Index instance, I tried to add the analyzer:
```
i = Index("indexname", elasticsearch_connection)
i.analyzer(my_analyzer)
```
but when I test it, I don't get the desired output:

```
i.analyze(text="long-term")
```
returns
```
{'tokens': [{'end_offset': 4,
   'position': 0,
   'start_offset': 0,
   'token': 'long',
   'type': '<ALPHANUM>'},
  {'end_offset': 9,
   'position': 1,
   'start_offset': 5,
   'token': 'term',
   'type': '<ALPHANUM>'}]}
```
Thanks in advance for any help or for clarifying how to add an analyzer to an index using the elasticsearch_dsl API.

Lea

**Comment by HonzaKral** [comment]
When you call `analyzer` method on `Index` it doesn't actually save the analyzer definition in elasticsearch, just in memory. To do that you need to call `.save()` on the `Index` object.

Also when you are using the `analyze` API it will use the `standard` analyzer by default, unless you specify different analyzer. So it should be `i.analyze(text="long-term", analyzer="my_analyzer").

Hope this helps.
