### ISSUE TITLE
"@" sign in password breaks authentication

### ISSUE THREAD

**Issue by ccurvey** [elastic/elasticsearch-dsl-py#659]
try this:

1) Using Kibana, create a superuser named "foobar" in elastic, with the password "p@ssword"

2) Try this little script

```
    import elasticsearch_dsl
    from elasticsearch_dsl.connections import create_connection

    class MyArticle(elasticsearch_dsl.DocType):
        DOC_TYPE = 'my_article'
        id = elasticsearch_dsl.String()

    connections.create_connection(hosts=["http://localhost:9200"], http_auth=("foobar:p@ssword"))
    MyArticle.init()

```
You'll get a 401 error

3) Now go back to Kibana, change the password to "password" and edit the script to use the new password.  it will work.

**Comment by HonzaKral** [comment]
I am sorry but I cannot replicate this situation, it works just fine for me after I change the password via `curl` (`curl -XPUT -u elastic localhost:9200/_xpack/security/user/elastic/_password -d '{"password" : "p@ssword"}'`) or kibana:
```
from elasticsearch_dsl.connections import connections
connections.create_connection(hosts=['localhost:9200'], http_auth='elastic:p@ssword')
from elasticsearch_dsl import Search
Search().count()
```

Could you please provide more information, including the exact exception and anything else that might be relevant like the respective versions of the library, `elasticsearch-py` and elasticsearch?

Thanks!

**Comment by HonzaKral** [comment]
Closinng this issue as I cannot replicate it. Please feel to reopen with additional information
