### ISSUE TITLE
term_vectors

### ISSUE THREAD

**Issue by eamonnmag** [elastic/elasticsearch-dsl-py#664]
Is there a nice way to get back _termvectors using DSL?

e.g. to replace this
```
GET /index/doc_type/ID/_termvectors?fields=text
{
    "term_statistics" : true,
    "field_statistics" : false,
    "positions": false,
    "offsets": false,
    "payloads":false,  
    "filter" : {
      "min_term_freq" : 2
    }
}
```

Or even better, directly in the search results.

**Comment by brainix** [comment]
Hi, @eamonnmag!

AFAIK, there's no way to get term vectors back with search results.  However, if you have a list of document IDs, you can fetch term vectors for all of those IDs using [es.mtermvectors()](http://elasticsearch-py.readthedocs.io/en/master/api.html?highlight=mtermvectors#elasticsearch.Elasticsearch.mtermvectors).

Good luck!
Raj

**Comment by HonzaKral** [comment]
Hi, exactly as @brainix said - the `dsl` only covers the most common use cases, for something like this, which I'd consider advanced functionality, please use the underlying `elasticsearch-py` library.

If you want to integrate this nicely with the `DocType` class you can create a subclass that adds this API as a method:

```
from elasticsearch_dsl import DocType
from elasticsearch_dsl.connections import connections

class TermVectorDocType(DocType):
    def termvectors(self, *fields, **kwargs):
        es = connections.get_connection(self._doc_type.using)
        return es.termvectors(
            index=self._get_index(),
            doc_type=self._doc_type.name,
            id=self.meta.id,
            fields=fields,
            **kwargs
        )
```

Hope this helps
