### ISSUE TITLE
Bool queries not combined correctly

### ISSUE THREAD

**Issue by bruceduhamel** [elastic/elasticsearch-dsl-py#667]
I believe I have found an issue with how elasticquery-dsl combines these queries.

I'm combining searches using the following pattern:
``
search = search.query(self.get_query_by_name())
search = search.query(self.get_query_by_phone())
``

Phone number and name are searched using a similar Bool query:

``
Bool(should=[Match**{"summary.name": {"query": "some name here"}}], must=[Nested(path="children", query=Bool(should=[Match(**{"children.name": "some name here")]))])
``

The documents look something like the following, where children is defined as a nested type:

``
{"summary": {"name": "alf", "phone": "+15555551234"}, "children": [{"name": "bob", "phone": ""}]}
``
I expected the resulting query to look something like:

``
Bool(must=[Match(children.name), Match(children.phone)], should=[Match(summary.phone), Match(summary.name)]
``

While there are surely other ways to get the same behavior, the resulting query ended up being something else entirely:

``
Bool(must=[Match(children.name), Match(children.phone), Bool(should=[Match(summary.phone)])], should=[Match(summary.name)]
``

Based on the documentation, I'd expect these queries to be combined using AND logic, but it seems to have merged them in an odd way.
http://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#query-combination

I'm relatively new to elastic search, so please advise me if my assumptions are incorrect.

I'm running:
Python 2.7.12 x64 
Ubuntu 16.04
elasticsearch 5.3.0
elasticsearch-dsl 5.3.0
search cluster version 5.1

**Comment by HonzaKral** [comment]
This is ok, albeit The result of combining queries like yours (with a single query in both `must` and `should`) can be written down multiple ways - while the one you mention as expected is the most elegant it is not the only way.

Qhen you have a query `q` (`Bool(must=[Match(f=1)], should=[Match(f=2)])`) and combine it with a similar query (like with itself), you get:
`Bool(minimum_should_match=0, must=[Match(f=1), Match(f=1), Bool(minimum_should_match=0, should=[Match(f=2)])], should=[Match(f=2)])`

which is equivalent - of the 4 `match` queries the ones with `f=1` are required whereas `f=2` are optional. Just as in your shorthand.

I added, however, some special casing in 3746b71c051545e9cb5182784030bdf52e8469e7 so that we can produce nicer queries.

Thanks for the report!

**Comment by bruceduhamel** [comment]
Thank you for your quick response!

I appologize for not being more clear, but the results from the query I expected and the results from the actual query I described above were not the same, this is the real issue at hand, not the format of the query.

For example:

``
Combine: 

Bool(must=[A], should=[B])
and
Bool(must=[C], should=[D])

Yields:
Bool(must=[A, B, C], should=[D])

Which is not the same logic as what I expect:
Bool(must=[A, C], should=[B, D])

In other terms, my expectation is (A&C) | (B&D) but the generated query is (A&B&C) | (D).

**Comment by HonzaKral** [comment]
can you please post actual code that it produces? Because when I tried it as mentioned I got correct result, if not 100% efficient.

Thanks!

**Comment by bruceduhamel** [comment]
Here is the actual query produced:

``
{
  "sort": [
    {
      "_score": {
        "order": "desc"
      }
    },
    {
      "muns": {
        "order": "desc"
      }
    }
  ],
  "query": {
    "bool": {
      "minimum_should_match": 0,
      "must": [
        {
          "nested": {
            "query": {
              "bool": {
                "should": [
                  {
                    "match": {
                      "signatures.entity_name": "Staples"
                    }
                  },
                  {
                    "match": {
                      "signatures.dba_name": "Staples"
                    }
                  }
                ]
              }
            },
            "score_mode": "max",
            "inner_hits": null,
            "path": "signatures"
          }
        },
        {
          "nested": {
            "query": {
              "bool": {
                "should": [
                  {
                    "prefix": {
                      "signatures.phone_number": "+1"
                    }
                  }
                ]
              }
            },
            "score_mode": "max",
            "inner_hits": null,
            "path": "signatures"
          }
        },
        {
          "bool": {
            "minimum_should_match": 0,
            "should": [
              {
                "prefix": {
                  "summary.phone_number": {
                    "boost": 2,
                    "value": "+1"
                  }
                }
              }
            ]
          }
        }
      ],
      "should": [
        {
          "match": {
            "summary.entity_name": {
              "query": "Staples",
              "boost": 2
            }
          }
        }
      ]
    }
  },
  "from": 0,
  "size": 10
}
``

**Comment by HonzaKral** [comment]
Yes, that is the same as I reproduced. Note the `minimum_should_match: 0` option - that essentially renders the query in the `should` clause as optional - the bool query will match even if the should doesn't.

Note also that the query you describe as your expectation (`Bool(must=[A, C], should=[B, D])`) is NOT what you describe later (`(A&C) | (B&D)`) - it is instead (`A&C` and `B` and `D` are optional - if they don't match a document that document will still be part of the query, if they do it will just have a higher score).

**Comment by bruceduhamel** [comment]
I understand your comment and agree that my previous example attempting to describe what I was trying to accomplish using boolean logic is as you said, A&D with B and D optional since they are in the should clause. 

The actual query produced above is not yielding this search logic. 
This query results in 0 hits against the following data:

``
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 4,
    "max_score": 1,
    "hits": [
      {
        "_index": "itest",
        "_type": "entity",
        "_id": "2",
        "_score": 1,
        "_source": {
          "signatures": [
            {
              "phone_number": "+1555",
              "entity_name": "-"
            }
          ]
        }
      },
      {
        "_index": "itest",
        "_type": "entity",
        "_id": "4",
        "_score": 1,
        "_source": {
          "signatures": [
            {
              "phone_number": "+1555",
              "entity_name": "Staples"
            }
          ]
        }
      },
      {
        "_index": "itest",
        "_type": "entity",
        "_id": "1",
        "_score": 1,
        "_source": {
          "signatures": [
            {
              "phone_number": "-",
              "entity_name": "-"
            }
          ]
        }
      },
      {
        "_index": "itest",
        "_type": "entity",
        "_id": "3",
        "_score": 1,
        "_source": {
          "signatures": [
            {
              "phone_number": "-",
              "entity_name": "Staples"
            }
          ]
        }
      }
    ]
  }
}
``

I believe the problem is that the portion searching against summary.phone_number is included in the Must clause of the parent Bool query. I understand that this snippet:

``
        {
          "bool": {
            "minimum_should_match": 0,
            "should": [
              {
                "prefix": {
                  "summary.phone_number": {
                    "boost": 2,
                    "value": "+1"
                  }
                }
              }
            ]
          }
        }
``

to mean the query will return documents whether or not they have a matching prefix for summary.phone_number, but if they do match, boost the relevance score. However, since this Bool query has only one should clause, according to the Elastic docs, it becomes equivalent to a Must.

``
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html
 If the bool query is a filter context or has neither must or filter then at least one of the should queries must match a document for it to match the bool query. This behavior may be explicitly controlled by settings the minimum_should_match parameter.
``

The doc for minimum_should_match goes on to explain:
``
If the calculations based on the specification determine that no optional clauses are needed, the usual rules about BooleanQueries still apply at search time (a BooleanQuery containing no required clauses must still match at least one optional clause)
``

If this portion of the query is moved from the Must clause of the parent Bool to the Should clause, the results work as expected, I get back the 1 document that has a matching value in signatures.phone_number AND signatures.entity_name.

Here is the complete 'correct' query:

``

GET itest/_search
{
  "sort": [
    {
      "_score": {
        "order": "desc"
      }
    },
    {
      "muns": {
        "order": "desc"
      }
    }
  ],
  "query": {
    "bool": {
      "minimum_should_match": 0,
      "must": [
        {
          "nested": {
            "query": {
              "bool": {
                "should": [
                  {
                    "match": {
                      "signatures.entity_name": "Staples"
                    }
                  },
                  {
                    "match": {
                      "signatures.dba_name": "Staples"
                    }
                  }
                ]
              }
            },
            "score_mode": "max",
            "inner_hits": null,
            "path": "signatures"
          }
        },
        {
          "nested": {
            "query": {
              "bool": {
                "should": [
                  {
                    "prefix": {
                      "signatures.phone_number": "+1"
                    }
                  }
                ]
              }
            },
            "score_mode": "max",
            "inner_hits": null,
            "path": "signatures"
          }
        }
      ],
      "should": [
        {
          "match": {
            "summary.entity_name": {
              "query": "Staples",
              "boost": 2
            }
          }
        },
        {
          "bool": {
            "minimum_should_match": 0,
            "should": [
              {
                "prefix": {
                  "summary.phone_number": {
                    "boost": 2,
                    "value": "+1"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  },
  "from": 0,
  "size": 10
}
``

And the execution results

``
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": null,
    "hits": [
      {
        "_index": "itest",
        "_type": "entity",
        "_id": "4",
        "_score": 1.287682,
        "_source": {
          "signatures": [
            {
              "phone_number": "+1555",
              "entity_name": "Staples"
            }
          ]
        },
        "sort": [
          1.287682,
          null
        ]
      }
    ]
  }
}
``

I again applogize for not being clear enough, but I believe the minimum_should_match option does not render the should clause optional when set to 0 as you described and this is likely the root cause of the behavior.

**Comment by HonzaKral** [comment]
as you quote from the docs: `This behavior may be explicitly controlled by settings the minimum_should_match parameter.` which is exactly what we do there by setting it to 0.

But you are right that it doesn't work when the bool query contains only one clause. Thanks for catching that!

This case was fixed by the commit I pushed earlier and I will do another pass over the logic.
