### ISSUE TITLE
normalizer property of keyword fields?

### ISSUE THREAD

**Issue by billykern** [elastic/elasticsearch-dsl-py#669]
it seems that it is not possible to use the [`normalizer` property](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/normalizer.html) in a manner analogous to `analyzer` as below. is there a better way to configure doc types with the normalizer property on keyword fields? if not, would this be something worth updating the library to support?

```python
from elasticsearch_dsl import analyzer, DocType, Keyword, normalizer, Text

html_strip = analyzer('html_strip',
    tokenizer="standard",
    filter=["standard", "lowercase", "stop", "snowball"],
    char_filter=["html_strip"]
)

lowercase = normalizer('my_analyzer',
    filter=['lowercase']
)

class Post(DocType):

    category = Text(
        analyzer=html_strip,
        fields={'raw': Keyword()}
    )
    style = Keyword(normalizer=lowercase)
```

i think it would be helpful since one could still rely on calling `DocType.init()` to add necessary entries to the `analysis` portion of the index settings.

it looks like this would be possible with relatively straightforward update to `Mapping._collect_analysis()` as well as a new `Normalizer` class or two in `analysis.py`...

if this makes sense and would be useful, i would be happy to attempt a PR

**Comment by HonzaKral** [comment]
This would make perfect sense and if you attempted a PR I would be very happy to give you any feedback! Let me know if there is anything in particular I can help with!

**Comment by spreeker** [comment]
Am i correct this is not released yet?

**Comment by HonzaKral** [comment]
@spreeker thank you for the ping, just release as `5.4.0`
