### ISSUE TITLE
Add support for range mapping fields

### ISSUE THREAD

**Issue by dgouldin** [elastic/elasticsearch-dsl-py#671]
Elasticsearch supports range mapping field types (https://www.elastic.co/guide/en/elasticsearch/reference/current/range.html), but I don't see them implemented in the DSL. I'm particularly interested in a `DateRange` field.

**Comment by mnm364** [comment]
Bump. Would be willing to put some time into implementing this if given the go-ahead from whomever it may concern.

**Comment by HonzaKral** [comment]
fixed in 8047f45
