### ISSUE TITLE
can you give a princeple of how will the query be translate into body?

### ISSUE THREAD

**Issue by yunfan** [elastic/elasticsearch-dsl-py#672]
your library is great and saved lots of my time
but unfortunately those saved times were all costs on finding(or guessing) the corresponding query

the document is short which i could understand that you cant cover all the cases
that's why i ask you gusy to give a princeple of the translating rules

**Comment by WisdomPill** [comment]
If you want to check your query you can use the to_dict() function and it will give you the body of the query

**Comment by yunfan** [comment]
no its just a result, i need to guess which arguments will affects the final query, actually currently i am just using to_dict to help guessing, but if you gave the rules, isnt things easier ?

**Comment by brainix** [comment]
I agree with @WisdomPill.  @yunfan - what do you mean by, "It's just a result?"  A quick code example would also help.

**Comment by yunfan** [comment]
@brainix actually i need to know the translating rules before i use `.to_dict()`, right?  otherwise how can i write a correct query in dsl style? since you dont have that examples

**Comment by HonzaKral** [comment]
@yunfan all keyword arguments to a query will directly translate into keys in the resulting `dict` (and, as a result, the final `json` sent to elasticsearch). The only exception is the expansion of `__` to `.` to allow circumvention of python keyword limitations.

This is mentioned in the documentation - http://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#queries but clearly it is not very clear, I apologize. Do you have any suggestions on how to improve it?

Thank you for raising this issue!

**Comment by yunfan** [comment]
@HonzaKral thanks for points me that, that rule you mentioned could be easilly understand by the existing examples. but there are some rules not mentioned,  and not that understandable easily, for eg, i'd learnt that to express `A|(B&C)`  i cant just use  `query=A|(B&C)` , instead i use  `query=Q('bool', should=[A, B&C])` (dont know if there are better one), i think what the documents not covered is details like this

and i suggest to have an independ sections on translating rules in the document

sorry for my poor english

**Comment by HonzaKral** [comment]
> eg, i'd learnt that to express `A|(B&C)` i cant just use `query=A|(B&C)` , instead i use `query=Q('bool', should=[A, B&C])`

This is very weird to me as in my tests those both lead to the same results:
```python
>>> from elasticsearch_dsl import Q
>>> a, b, c = Q('match', f='a'), Q('match', f='b'), Q('match', f='c')
>>> a|(b&c)
Bool(should=[Bool(must=[Match(f='b'), Match(f='c')]), Match(f='a')])
```

**Comment by yunfan** [comment]
sorry the right example shoule be  `(a|b)&c`

```
from elasticsearch_dsl import Q                                                                                                                                                                                    
a, b, c = Q('match', f='a'), Q('match', f='b'), Q('match', f='c')                                                                                                                                                  
                                                                                                                                                                                                                   
print ((a|b)&c).to_dict()                                                                                                                                                                                          
                                                                                                                                                                                                                   
print Q('bool', should=[(a|b), c]).to_dict()
```
the output
```
{'bool': {'minimum_should_match': 1, 'should': [{'match': {'f': 'a'}}, {'match': {'f': 'b'}}], 'must': [{'match': {'f': 'c'}}]}}
{'bool': {'should': [{'bool': {'should': [{'match': {'f': 'a'}}, {'match': {'f': 'b'}}]}}, {'match': {'f': 'c'}}]}}
```

**Comment by HonzaKral** [comment]
I am sorry but I still don't understand. those two examples that you give are different and mean different things:
` ((a|b)&c)` means one of `a` or `b` and `c` which is exactly what the resulting query says as well.
