### ISSUE TITLE
Combining Search objects

### ISSUE THREAD

**Issue by cgm1123** [elastic/elasticsearch-dsl-py#677]
I'm utilizing the search dsl library to combined the query structures of multiple rendered search templates (dynamically defined at run-time), similar to the below code. E.g. to use a search template to search "within" the results of another search template.

Is there a better or more appropriate way, that I'm missing, to combine the queries?

```python3
s1 = Search(...).update_from_dict(es.render_search_template(...)['template_output'])
s2 = Search(...).update_from_dict(es.render_search_template(...)['template_output'])

s1.query._proxied &= s2.query._proxied

results = s1.execute()
```

**Comment by HonzaKral** [comment]
Hi, I think a cleaner solution would be to just use the `query` part of the search body explicitly:
```python
# create an empty search...
s = Search()
# .. and apply the rendered queries
s = s.query(es.render_search_template(...)['template_output']['query'])
s = s.query(es.render_search_template(...)['template_output']['query'])
```

That is a more explicit approach and isn't susceptible to some weird behavior that your approach might be - for example aggregations would be applied from the first template but not the second etc.

**Comment by cgm1123** [comment]
@HonzaKral that makes a lot more sense. Thank you!
