### ISSUE TITLE
Elasticsearch dsl deleting error

### ISSUE THREAD

**Issue by osolop** [elastic/elasticsearch-dsl-py#684]
I have a problem with deleting items using elasticsearch-dsl. When i trying to filter my data it goes easily and something like this works great.
`def searchId(fileId):
s = Search().filter('term', fileId=fileId)
response=s.execute()
return response`
Scanning works also :
`def scanning():
s = Search()
for hit in s.scan():
    if hit.domain == 'Messages':
        print(str(hit.fileId) + " : " + str(hit.domain))`
But when i wanna to delete items : 
`def deleteId(fileId):
s = Search().query('match', fileId=fileId)
response = s.delete()
return "Done"`
I got an error :
`    Traceback (most recent call last):
  File "", line 1, in 
  File "/home/o.solop/DataSearchEngine/datasearch/elasticapp/search.py", line 96, in deleteId
    response = s.delete()
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/search.py", line 660, in delete
    **self._params
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 887, in delete_by_query
    raise ValueError("Empty value passed for a required argument.")
ValueError: Empty value passed for a required argument.`
My versions:
`elasticsearch (5.4.0)
elasticsearch-dsl (5.3.0)`
`Python 2.7.12`

**Comment by tylerjharden** [comment]
You're missing an index in the Search constructor. You will need to do something along the lines of `Search(index=my_index_name)` whereas you currently do `Search()`. This is due to the fact that under the hood, elasticsearch-dsl uses the delete_by_query API, as indicated in your error message, which needs to know which index to perform the delete against.

**Comment by osolop** [comment]
@tylerjharden, you are my hero. Thank you so much. It was that kind of really stupid error.
