### ISSUE TITLE
Is it a good idea to add mapping of a doctype before saving it?

### ISSUE THREAD

**Issue by WisdomPill** [elastic/elasticsearch-dsl-py#686]
Is it a good idea to add mapping of a doctype before saving it? Because if it is I don't see why we should be using .init() method before saving a Doctype object. In this case my suggestion is to add an automatic .init() before saving it in the DocType class like the following ideally in line 405 of elasticsearch_dsl/document.py

```python
self.init(using=using, index=index)
```

@HonzaKral what do you think about it?

**Comment by carltongibson** [comment]
[From the docs](http://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#document-life-cycle): 

> Before you first use the Post document type, you need to create the mappings in Elasticsearch. For that you can either use the Index object or create the mappings directly by calling the init class method

**Comment by WisdomPill** [comment]
@carltongibson I see what you're saying but in my case I have an index for each day, and calling the init method every time is kind of stressfull since I have to remember wherever i save a document to call it.

Is there any way to create a template with elasticsearch_dsl?

**Comment by carltongibson** [comment]
@WisdomPill Well there's [`clone`](http://elasticsearch-dsl.readthedocs.io/en/latest/api.html#elasticsearch_dsl.Index.clone) but you'd still have to do this daily. (Although is that really that hard?)

**Comment by HonzaKral** [comment]
Hi @WisdomPill, currently there is no direct support for index templates, but it shouldn't be too hard (famous last words) and it makes perfect sense as the next addition.

In the meantime you can do it semi manually by taking the output of `Index.to_dict()` and storing it as a template by using the `indices.put_template` method of `elasticsearch-py`

**Comment by HonzaKral** [comment]
Closing in favor of #690

**Comment by HonzaKral** [comment]
For `IndexTemplate` implementation you can check fb830eb - any and all feedback is welcome!
