### ISSUE TITLE
Permission to add type stubs for elasticsearch_dsl to typeshed

### ISSUE THREAD

**Issue by rowillia** [elastic/elasticsearch-dsl-py#688]
Howdy,

I'd like to add stubs for elasticsearch_dsl to https://github.com/python/typeshed, a repository used to store PEP 484 type signatures for the python stdlib and popular third party libraries. As per PEP 484, permission is required from the library owner before merging type signatures into typeshed - https://www.python.org/dev/peps/pep-0484/#the-typeshed-repo

Thanks, let me know if you have any questions.  I'll do the first iteration on the types and I'm happy to keep it up to date.

**Comment by HonzaKral** [comment]
Hi @rowillia,
if you need an official permission, you have it.

Thank you very much for doing this, feel free to ping me with any questions you might have!
