### ISSUE TITLE
TypeError: search() got an unexpected keyword argument 'body'

### ISSUE THREAD

**Issue by verbergar** [elastic/elasticsearch-dsl-py#691]
Hi everyone,

I have the following error when I trust to get the query's results:

>   _File "C:\Python27\lib\site-packages\elasticsearch_dsl\search.py", line 606, in execute
>     **self._params
>   TypeError: search() got an unexpected keyword argument 'body'__

The code is as follow:
_

> s = Search(using=client, index="id_index") \
>       .query("query_string", query="*", analyze_wildcard="True")   \
>       .filter("term", sn="DF414874Q") \
>       s.aggs.bucket('by_src_ip', 'terms', field='src_ip', order='desc', size='10')
>       response = s.execute()

_

The created query is as follow (I check it through **"print s.to_dict()"**):

![image](https://user-images.githubusercontent.com/6664472/27867242-6b81125e-6199-11e7-9c14-a97ef6e71094.png)

The version of elasticsearch_dsl is 5.3.0 and elasticsearch's version is 5.4.0

Could anyone help me? 

Thanks in advance

**Comment by HonzaKral** [comment]
I am sorry, but I cannot replicate this - can you please also check what is the version of the `elasticsearch-py` library? Also what do you have stored in `client`?

Thanks!

note that you also have an error in your query - `terms` aggregation's `order` doesn't support a string like this, if you want the buckets to be sorted in descending order by the number of documents they contain just remove the `order="desc"` parameter - that is the default behavior.

**Comment by verbergar** [comment]
The version of the elasticsearch library is 5.4.0.

You're right, I have just correct that error, thanks! But, if I would like insert the order with other parameter, How could I do it?
![image](https://user-images.githubusercontent.com/6664472/27872160-1d7480be-61a8-11e7-8c82-405e67a8dffa.png)

**Comment by HonzaKral** [comment]
The way to do what you ask is to do:
```
s.aggs.bucket('by_src_ip', 'terms', field='src_ip', size=10, order={'_count': 'asc`})
```

Hope this helps!
