### ISSUE TITLE
Query Indices no_match_query field should accept "none" and "all"

### ISSUE THREAD

**Issue by Nibor62** [elastic/elasticsearch-dsl-py#693]
Hi,

As written in ES docs, the "no_match_query" indices field should accept both "none" and "all" value which is currently not the case, forcing dirty workarounds when you want a match_none here.

**Comment by HonzaKral** [comment]
Hi @Nibor62, sorry for the delay. You are correct in us not supporting this parameter. However, since the `indices` query is deprecated, and there is no easy fix, we will not be adding these options. Please use a query on the `_index` field instead.

Thanks for the report!
