### ISSUE TITLE
pip 5.3 package contains elasticsearch_dsl/result.py

### ISSUE THREAD

**Issue by aniobash** [elastic/elasticsearch-dsl-py#694]
Hello,

There is a module result.py in the pip 5.3 package which is missing in master and tag 5.3. The file contains Response, ResultMeta and Result classes.

**Comment by HonzaKral** [comment]
Thank you for the ticket, the `wheel` indeed has this extra file. It doesn't hurt anything but it definitely shouldn't be there, I will be more careful when building the package next time!
