### ISSUE TITLE
How to convert range query

### ISSUE THREAD

**Issue by sayco5842** [elastic/elasticsearch-dsl-py#696]
hello 
elasticsearch -5.4.2
elastcsearch-py -5.4.0
elastcsearch-dsl -5.3.0

I want this query

`{
  "query": {
    "bool": {
      "minimum_number_should_match": 1,
      "should": [
        {
          "range": {
            "search_score": {
              "gt": 0
            }
          }
        },
        {
          "range": {
            "hidden_score": {
              "gt": 0
            }
          }
        }
      ]
    }
  }
}`

How to convert to elasticsearch-dsl

**Comment by sayco5842** [comment]
search_score_range = Range(**{'search_score': {'gt': 0}})
search_hidden_range = Range(**{'hidden_score': {'gt': 0}})
bool_query = Bool(should=[search_score_range,search_hidden_range],minimum_number_should_match=1)

**Comment by WisdomPill** [comment]
from elasticsearch_dsl import Q
    from elasticsearch_dsl.query import Range, Bool
    from elasticsearch_dsl.search import Search
    
    s = Search().query(Bool(should=[Q(Range(search_score={'gt': 0})),
                                    Q(Range(hidden_score={'gt': 0}))],
                            minimum_score_should_match=1))
    
    print(s.to_dict())

**Comment by HonzaKral** [comment]
Thanks @WisdomPill, that is absolutely correct.

For completeness you can also do:
```
from elasticsearch_dsl import Q
s = Search().query(Q('range', search_score={'gt': 0}) | Q('range', hidden_score={'gt': 0}))
```

where you use `Q('range', ...)` instead of `Range(...)` or `Q(Range(...))` and also the `|` operator to express `OR` functionality.
