### ISSUE TITLE
sort by Text/String field problem

### ISSUE THREAD

**Issue by pkisztelinski** [elastic/elasticsearch-dsl-py#697]
Hi. I have problem with `.sort()` method. For example I have Index with Text() field:

```
FILTER = token_filter(
    'FILTER', 'edge_ngram', min_gram=3, max_gram=40)
ANALYZER = analyzer(
    'ANALYZER', tokenizer='standard', type='custom', filter=[
        'standard', 'lowercase', 'stop', 'asciifolding',FILTER])

class Article(DocType):
    title = Text(analyzer=ANALYZER)
    body = Text(analyzer='snowball')
    tags = Keyword()

search = Article.search().sort('title')
search.execute()
```

when I try to execute search query with sort I get an error:
```
elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'Fielddata is disabled on text fields by default. Set fielddata=true on [title] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.')
```

How can I sort by `title` field in this case?

**Comment by WisdomPill** [comment]
You can't sort on text field unless you enable fielddata in your mapping...
You should use keyword instead if you want to sort.
Here's the official guide on the main Text and Keyword differences https://www.elastic.co/blog/strings-are-dead-long-live-strings

**Comment by HonzaKral** [comment]
Adding for completeness: https://stackoverflow.com/questions/45220352/elasticsearch-dsl-py-sorting-by-text-field
