### ISSUE TITLE
Different Hit Totals from Postman vs. DSL 

### ISSUE THREAD

**Issue by Archetype90** [elastic/elasticsearch-dsl-py#698]
I am doing some fairly simple aggregations using the DSL. When verifying the results using Postman, I noticed that I was getting inconsistent hits.total from Postman and the DSL. 

**DSL QUERY**
```
    s = Search(using=client, index="logstash-*").query("match", type__raw="bro-conn_log")
    
    start_date =  '2016-12-17T10:48:00-05:00'
    end_date = '2017-07-20T10:48:00-05:00'
    if start_date is not None and end_date is not None:
        s = s.query('range', **{'@timestamp': {'gte' start_date:, 'lt': end_date }})

    s.aggs.metric('total_packets_sent', 'sum', field='orig_pkts')
    s.aggs.metric('total_packets_received', 'sum', field='resp_pkts')

    response = s.execute()
    print("Total Response Hits: %s" % response.hits.total)
    return response
```
**DSL QUERY RESULTS**
> Total Response Hits: 386659

**POSTMAN QUERY**

```
{
    "size": 0,
    "query": {
    	"bool": {
    		"must" : [
    		{
		       "match": {
		            "type": {
		              "query": "bro-conn_log",
		              "type": "phrase"
		            }
		        }
	    	},
    		{
		    	"range" : {
		        	"@timestamp" : {
		            	"gte": "2016-12-17T10:48:00-05:00", 
		            	"lte": "2017-07-20T10:48:00-05:00"
		        	}
		    	}
    		}]
    	}
    },
    "aggs": {
        "packets_received": {
          "sum": {
            "field": "resp_pkts"
          }
        },
        "packets_sent" : {
          "sum" : {
            "field" : "orig_pkts"
          }
    	}
    }
}
```

**POSTMAN RESULTS**

```
{
    "took": 163,
    "timed_out": false,
    "num_reduce_phases": 4,
    "_shards": {
        "total": 1955,
        "successful": 1955,
        "failed": 0
    },
    "hits": {
        "total": 1001717,
        "max_score": 0,
        "hits": []
    },
    "aggregations": {
        "packets_sent": {
            "value": 14983662
        },
        "packets_received": {
            "value": 9705348
        }
    }
}
```

As you can see I am getting almost 700,000 more results from an identical Postman query. My assumption is that I have inconsistencies between the two queries, but no amount of simplifying and editing can get me the same results.

**Comment by HonzaKral** [comment]
In the `dsl` you are matching `type.raw` whereas in postman you are matching just `type`.

Please take the output of `s.to_dict()` if you want apples to apples comparison.

**Comment by Archetype90** [comment]
That was a silly mistake. Thank you for the s.to_dict() feedback - that is great advice. 

Postman had the correct result above. There are ~1 million records that should match my query (according to Kibana). 

Changing the `dsl` to `type` results in all records being returned, ~6 million records. 

Changing postman and the dsl to `type` results in the 386k records being returned that I was seeing above, but that is not including all records.

According to the index mapping `type` is searchable and `type.raw` is searchable and can be aggregated.

**Comment by Archetype90** [comment]
To reiterate in one sentence -

My results are different in postman and the dsl when using the `type` field in both. 

Postman = 1,000,000 results (expected)
DSL = 6,000,000 results (not expected)

**Comment by HonzaKral** [comment]
The `type` field is being analyzed, my guess is all your types contain one of `bro`, `con`, or `log` because that's what the search query will be split into as well as the text. Also you are using `type: phrase` in postman - you are comparing completely different query types. Please do the comparison on the json level using `to_json`
