### ISSUE TITLE
Narrowing filtering facets/aggregations

### ISSUE THREAD

**Issue by barseghyanartur** [elastic/elasticsearch-dsl-py#699]
From [docs](https://elasticsearch-dsl.readthedocs.io/en/latest/faceted_search.html#faceted-search).

I have defined a ``RangeFacet``:

```python
RangeFacet(field="comment_count", ranges=[("few", (None, 2)), ("lots", (2, None))])
```

How can I narrow it further to show only "few"?

**Comment by HonzaKral** [comment]
All you have to specify is `filters={'name_of_range_facet': 'few'}` when instantiating the `FacetedSearch` subclass. see https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_integration/test_faceted_search.py#L132 for example

Hope this helps
