### ISSUE TITLE
How to use boost_mode 

### ISSUE THREAD

**Issue by ijharulislam** [elastic/elasticsearch-dsl-py#702]
How to use "boost_mode": "replace" in DSL? Is it possible to use it with SF, if so, how to do it?

**Comment by HonzaKral** [comment]
Just passing `boost_mode='replace'` to `.query()` or `Q()` should do thr trick:

```python
from elasticsearch_dsl import Search, SF
s = Search().query('function_score', boost_mode='replace', functions=[SF('random_score')])
```

**Comment by ijharulislam** [comment]
Thanks. It is working.
