### ISSUE TITLE
if the filed has sub filed, how could i made the query?

### ISSUE THREAD

**Issue by tonyxyl** [elastic/elasticsearch-dsl-py#706]
my english is poor, thank you for reading.

the mappings like this:
```
{
  "mappings": {
    "article": {
      "properties": {
        "title": {
          "store": true,
          "type": "text",
          "analyzer": "ik_smart",
          "search_analyzer": "ik_smart",
          "term_vector": "with_positions_offsets",
          "boost": 4,
          "fields": {
            "raw": {
              "type": "keyword"
            }
          }
        }
    }
}
```

i code like this:

`s = Search().query('match', title.raw='just a test')`

which throws a SyntaxError `keywrod can't be an expression`,

help me out this.

**Comment by tonyxyl** [comment]
ping @HonzaKral

**Comment by HonzaKral** [comment]
Happy to hear that. For the record you can use `__` instead of `.` in the keyword: 
`s = Search().query('match', title__raw='just a test')`
