### ISSUE TITLE
keyed buckets in range aggregation not accessible through response object

### ISSUE THREAD

**Issue by kputland** [elastic/elasticsearch-dsl-py#708]
`
AttributeError: 'list' object has no attribute 'CURRENT'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /Users/karl/github/utils/cdr/src/fraud_es.py(1585)regression_detector()
-> if dates.CURRENT.doc_count > minutes:
(Pdb) type(dates)
<type 'list'>
(Pdb) dates[0]
u'PAST'
(Pdb) l
1580 	                user_search = hit_search_base \
1581 	                    .filter('term', **{'@fields.basic_userId.raw':user.key}) \
1582 	                    .filter('range', **{"@timestamp": {"gte": f_dt_utc(ldt-dtd(minutes=minutes)), "lt": f_dt_utc(ldt)}})
1583 	                dates = user.DATES.buckets
1584 	                logger.debug('regression_detector: dates: {}'.format(dates))
1585 ->	                if dates.CURRENT.doc_count > minutes:
1586 	                    # average call length of a human is two minutes.
1587 	                    # assume that a user making more than one call every minutes
1588 	                    # is fishy
1589 	                    searches.append((user_search, 'user: too many calls in current period'))
1590 	                #
(Pdb) type(user)
<class 'elasticsearch_dsl.response.aggs.Bucket'>
(Pdb) user.to_dict()
{u'DATES': {u'buckets': {u'PAST': {u'to': 1501860697477.0, u'to_as_string': u'2017-08-04T15:31:37.477Z', u'doc_count': 1552}, u'CURRENT': {u'to': 1501864297477.0, u'from_as_string': u'2017-08-04T15:31:37.477Z', u'from': 1501860697477.0, u'to_as_string': u'2017-08-04T16:31:37.477Z', u'doc_count': 0}, u'PAST_12HOURS': {u'to': 1501864297477.0, u'from_as_string': u'2017-08-04T04:31:37.477Z', u'from': 1501821097477.0, u'to_as_string': u'2017-08-04T16:31:37.477Z', u'doc_count': 31}, u'PAST_24HOURS': {u'to': 1501864297477.0, u'from_as_string': u'2017-08-03T16:31:37.477Z', u'from': 1501777897477.0, u'to_as_string': u'2017-08-04T16:31:37.477Z', u'doc_count': 416}}}, u'DESTINATIONS': {u'buckets': [{u'key': u'+15559591221', u'doc_count': 1023}, {u'key': u'+15559590081', u'doc_count': 490}, {u'key': u'15555280009', u'doc_count': 2}, {u'key': u'15559299096', u'doc_count': 2}, {u'key': u'15559351191', u'doc_count': 2}, {u'key': u'15559594118', u'doc_count': 2}, {u'key': u'15559611212', u'doc_count': 2}, {u'key': u'15559613445', u'doc_count': 2}], u'sum_other_doc_count': 0, u'doc_count_error_upper_bound': 0}, u'key': u'xxxxxxuseridxxxxxx', u'doc_count': 1552}
(Pdb) user.DATES.buckets.PAST
*** AttributeError: 'list' object has no attribute 'PAST'
(Pdb) user.DATES
{u'buckets': {u'PAST': {u'to': 1501860697477.0, u'to_as_stri...}
(Pdb) user.DATES.buckets
[u'PAST', u'CURRENT', u'PAST_12HOURS', u'PAST_24HOURS']
(Pdb) user.DATES.buckets[0]
u'PAST'
(Pdb) user.DATES.buckets
[u'PAST', u'CURRENT', u'PAST_12HOURS', u'PAST_24HOURS']
(Pdb) elasticsearch_dsl
<module 'elasticsearch_dsl' from '/Users/karl/virtualenv/utils-es5/lib/python2.7/site-packages/elasticsearch_dsl/__init__.pyc'>
(Pdb) elasticsearch_dsl.__version__
(5, 2, 0)
(Pdb) exit
`

**Comment by kputland** [comment]
Seems like it may be fixed in 5.3

**Comment by HonzaKral** [comment]
It was fixed indeed, thanks for the report!
