### ISSUE TITLE
Save document should return True on update

### ISSUE THREAD

**Issue by roubaeli** [elastic/elasticsearch-dsl-py#714]
As mentioned in docs `update` method should only be used for partial update, for full update `save` method should be used, but `save` method checks only a created field of ES response so it returns `False` on a successful full update of a document.

An example of ES response that causes the problem:
`{"_index":"indexnam","_type":"typename","_id":"randomid","_version":3,"result":"updated","_shards":{"total":2,"successful":1,"failed":0},"created":false}`

Elasticsearch version (docker-elk):
```
"version" : {
    "number" : "5.4.2",
    "build_hash" : "929b078",
    "build_date" : "2017-06-15T02:29:28.122Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.1"
  }
```
Library version: `5.3.0`

**Comment by HonzaKral** [comment]
This is expected behavior - the return value of `save` is `True` if the document was created and `False` if it has not as mentioned in the docs(0). If something went wrong it would have thrown an exception.

Hope this helps

0 - http://elasticsearch-dsl.readthedocs.io/en/latest/api.html#elasticsearch_dsl.DocType.save

**Comment by roubaeli** [comment]
Yes I've seen that, in the code though it says:
```
# return True/False if the document has been created/updated
return meta['created']
```

If this is an expected behavior can you please give me any advice as to how check a successful full update of a document?

**Comment by HonzaKral** [comment]
If there is no exception it means it was successful, no need to check for anything.

Sorry for the confusion, by that sentence I meant `return True` if document was created and `return False` if updated.

**Comment by roubaeli** [comment]
Ok, I still think it could return True even on a successful update but I will work with the exception. Thank you for your help.

**Comment by HonzaKral** [comment]
Thanks for the feedback, I appreciate it. I know this part is confusing to people (and for very good reason).
