### ISSUE TITLE
Not Compatible with new version of elasticsearch

### ISSUE THREAD

**Issue by mohammadahadi27** [elastic/elasticsearch-dsl-py#717]
Today i installed last version of elasticsearch and i wanted to use this library but if found a problem.
in last versions of elasticsearch the get mapping with a special type was like this:
 http://192.168.31.37:9200/swift-metadata/_mapping/object

but now we should omit underline before mapping and this is not handled yet.

**Comment by HonzaKral** [comment]
Could you please specify the exact version of `elasticsearch`, `elasticsearch-dsl` and `elasticsearch-py` you are using? Thanks!

**Comment by mohammadahadi27** [comment]
thanks,my problem soveld.i was using bad version of elasticsearch
