### ISSUE TITLE
`parent` attribute in `Meta` class of DocType is not supported

### ISSUE THREAD

**Issue by mamikonyana** [elastic/elasticsearch-dsl-py#72]
Even though the documentation says that you could have an attribute named parent in the `Meta` class inside a DocType subclass. The code doesn't support that

Example:
If I want to construct the following mappings
```
    "mappings" : {
      "blog" : {
        "properties" : {
          "description" : {
            "type" : "string",
            "analyzer" : "caseinsensitive_analyzer"
          },
      },
      "post" : {
        "_parent" : {
          "type" : "blog"
        },
        "_routing" : {
          "required" : true
        },
        "properties" : { }
      }
```

From the documentation it seems like you should be able to do:
```
class Blog(DocType):
  description = String()

  class Meta:
    index = 'my_index'

class Post(DocType):
  class Meta:
    index = 'my_index'
    parent = 'blog'

```
but this will result in the following mappings
```
    "mappings" : {
      "blog" : {
        "properties" : {
          "description" : {
            "type" : "string",
            "analyzer" : "caseinsensitive_analyzer"
          },
      },
      "post" : {
        "properties" : { }
      }
```

Instead you have to find a workaround and do the following to create the desired mapping.
```
class Blog(DocType):
  description = String()

  class Meta:
    index = 'my_index'

class Post(DocType):
  class Meta:
    index = 'my_index'
    mapping = Mapping('post')
    mapping.meta('_parent', type='blog')
```

**Comment by HonzaKral** [comment]
I am curious where in the documentation did you find the mention that you should be able to just say `parent = "blog"`. That is not the case and the documentation needs to be clearer about that. I am sorry it misled you.

The solution you labeled as a workaround is currently the only solution and it is the recommended way. I experimented with other ways to map meta fields, but none of them *felt* natural (no objective reasons). Settings things like parent type is easy enough as you describe it, but with more complicated stuff like defining `_all` with analyzers etc it would imho get out of hand:

    class Post(DocType):
        class Meta:
            all = {'enabled': False}
            routing = {'required': True, 'path': 'post.author.id'}

That is why I opted for the more explicit approach:

    class Post(DocType):
        class Meta:
            mapping = Mapping('post')
            mapping.meta('_all', enabled=False)
            mapping.meta('_routing', required=True, path='post.author.id')


Does this make sense? I am definitely open to suggestions, or if people think that this wouldn't be an issue I would love to hear that too.

**Comment by mamikonyana** [comment]
I guess it's not said in the documentation explicitly, but I expected it from the design of the Meta class.. And the reference to setting parent through meta attribute of a DocType instance threw me off (in https://github.com/elasticsearch/elasticsearch-dsl-py/blob/master/docs/persistence.rst), also DOC_META_FIELD had parent in it too (https://github.com/elasticsearch/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/document.py#L12).

What you are describing makes sense. Imho it would have been perfect if one wouldn't need to create a Mapping instance if dealing with DocType's. I'm actually not sure which one of the two snippets I'd prefer.   What if you make meta be a stand alone function and do something like this in order to make sure correct parameters are passed.
```
class Post(DocType):
    class Meta:
        all = meta(enabled=False)
        routing = meta(required=True, path='post.author.id')
```
This is just a suggestion. It will avoid creating a Mapping, and needing to reuse the same literal 'post'

**Comment by HonzaKral** [comment]
Thank you @mamikonyana for your help designing this, I opted for `MetaField` instead of `meta`, but it should work.
