### ISSUE TITLE
Is there any way to use filter inside TermsFacet ?

### ISSUE THREAD

**Issue by fellipeh** [elastic/elasticsearch-dsl-py#720]
I try to look in documentation, but TermsFacet  has no much info.. I have these inside my class:

```
    doc_types = [DocumentIndex, ]
    index = settings.DATA_ES_INDEX_NAME
    facets = {
        'datasets': TermsFacet(field='dataset'),
        'datatype': TermsFacet(field='datatype'),
    }
```

wich dataset facet has `count`  but I need to filter these count using some permission of my user...

can I do that? How?

**Comment by HonzaKral** [comment]
To do that just override the `search` method, call `super().search()` and then modify the output to add any potential filters you might be looking for like the example at [0].

If you want to filter out only the one facet then I am afraid you will have to create your own facet subclass that will wrap the `TermsFacet` and add a filter to its aggregation.

0 - http://elasticsearch-dsl.readthedocs.io/en/latest/faceted_search.html#example
