### ISSUE TITLE
Nested boolean logic fails

### ISSUE THREAD

**Issue by owsd** [elastic/elasticsearch-dsl-py#723]
If I use boolean logic to group AND and OR operations together, I get an unexpected result:
```
>>> Q('term', topic='foo') & (Q('term', subtopic='bar') | Q('term', subtopic='bar2'))
Bool(minimum_should_match=1, must=[Term(topic='foo')], should=[Term(subtopic='bar'), Term(subtopic='bar2')])
```

What I would expect is that the `should` is actually nested within the `must`.  What the above query is returning is "must match at least one of topic=foo OR subtopic=bar or subtopic=bar2.

Nesting with a forced bool/must makes it work correctly:
```
>>> Q('term', topic='foo') & Q('bool', must=(Q('term', subtopic='bar') | Q('term', subtopic='bar2')))
Bool(must=[Bool(should=[Term(subtopic='bar'), Term(subtopic='bar2')]), Term(topic='foo')])
```

**Comment by owsd** [comment]
Alternatively, seems like you could solve by using `minimum_should_match=1` for top-level OR, and `minimum_should_match=N` for N queries ANDed together (in this case `minimum_should_match=2`).

**Comment by HonzaKral** [comment]
The query is correct as it does indeed specify `minimum_should_match=1` as you can see in your example. What that means is that one of the queries in the `should` list has to match on top of the query in `must` which must always match. Do you observe different behavior?

Thanks!

**Comment by owsd** [comment]
Cool thanks for explaining that, verified it is working.
