### ISSUE TITLE
Can't get desired return size when using MultiSearch 

### ISSUE THREAD

**Issue by gestapolur** [elastic/elasticsearch-dsl-py#729]
When I set a return size on a `Search` object and add it into `MultiSearch`, it seems not working correctly:

```python

from elasticsearch_dsl import MultiSearch, Search
from elasticsearch import Elasticsearch

es = Elasticsearch()
ms = MultiSearch(using=es)
s = Search(using=es, index='test', doc_type='test').params(size=0)

ms = ms.add(s)
print(len(ms.execute()[0].hits.hits))
print(len(s.execute().hits.hits))
```
Suppose there were enough data in index `test`, the output should be:

```bash
10
0
```

Seems the size setting is useless on `MultiSearch`, and I after checked the query body it generated I just found that it put `size` in `index`:

```python
import json
print(json.dumps(ms.to_dict(), ensure_ascii=False))
>>> [{"index": ["test"], "type": ["test"], "size": 0}, {"query": {"match_all": {}}}]
```
And according to the [document](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html), `size` should put in the `query`. And after I did this modify and use `msearch` to query, it works correctly:

```python
body = [{"index": ["test"], "type": ["test"]}, {"query": {"match_all": {}}, "size": 0}]
resp = es.msearch(body=body)
print(resp['responses'])
>>> {'took': 0, 'timed_out': False, '_shards': {'total': 5, 'successful': 5, 'failed': 0}, 'hits': {'total': 2448, 'max_score': 0.0, 'hits': []}, 'status': 200}
```

Maybe there is something wrong when `MultiSearch` generating a `msearch` query body?

**Comment by HonzaKral** [comment]
It puts the `size` with rest of the query parameters as you asked for by using the `params` method. If you want to put the `size` in the body please use the documented way of setting it by either using the `extra` method or python slicing: `s = s[0:0]`

Hope this helps!

http://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#pagination
