### ISSUE TITLE
meta data not added to object when instantiated...

### ISSUE THREAD

**Issue by njoannin** [elastic/elasticsearch-dsl-py#73]
Is this the wanted behavior?

```
>>> a=Article(_id=3, title="Test")
>>> a.to_dict()
{'title': 'Test'}
>>> a.meta.to_dict()
{'id': 3}
```

The index metadata will only be added when the object is saved (or more probably when the object is updated after saving).

However, this prevents us from accessing this data directly before the object is saved.

As it is now, we have to call e.g.:

```
>>> a._doc_type.index
'blog'
```

Personally, I wouldn't mind having it accessible through ```a._index```
 before it is saved.
(Also, it would be nice that the doc_type metadata also be added to the meta field, but that's just my wishful thinking!)
What are your thoughts on this?

Using elasticsearch-dsl-py version 0.0.4 beta

**Comment by HonzaKral** [comment]
Ah, I see. This definitely makes sense - it would mean seeding the `ResultMeta` with defaults on creation (or overriding its `__getitem__` which I would like to avoid).

I explicitly avoid setting `doc_type` in the meta because that should always be constant and shouldn't be overridable. In python the doc type information is represented by the class being used so this information shouldn't be needed (and therefore duplication of it should be avoided). What use case do you have for `doc_type` in meta? Maybe I am missing something.

Thanks!

**Comment by njoannin** [comment]
Well, I'm trying to keep track of all the events that occur. Each updating of a document being an event.
In that process, I use the doc_type name.

Currently, I access it with ``` <object>._doc_type.name```  before the document is saved.

About setting doc_type in the meta, after a document is saved, or simply retrieved from es, it is actually available in the meta (although I haven't tried modifying it).
```
>>> a.meta.to_dict()
{'index': 'blog', 'version': 1, 'doc_type': 'article', 'found': True, 'id': '42'}
```

Regarding the doc_type being represented by the class being used: it is currently possible to set it (and therefore override that behavior) in the Meta class of the _doc_type class with  ```doc_type = "whatevername"```...

Personally, I like the class name to be singular, but the doc_type name to be plural, e.g. class name "Article" but doc_type name "articles".

Is the possibility to set a custom doc_type name going to change in the future?

**Comment by njoannin** [comment]
Just a note: after saving a document, the meta.doc_type attribute is not added.

```
>>> a=Article(_id=33, title="blablabla", body="bla")
>>> a.save()
True
>>> a.meta.to_dict()
{'index': 'blog', 'version': 1, 'id': '33'}
```

However, when I get this object, right after creating it, the meta.doc_type attribute is added to the object, and is accessible:

```
>>> a=Article.get(id=33)
>>> a.meta.to_dict()
{'index': 'blog', 'version': 1, 'doc_type': 'article', 'found': True, 'id': '33'}
>>> a.meta.doc_type
'article'
```

**Comment by HonzaKral** [comment]
Thanks for your patience, `index` is now seeded into `.meta` if it's set on `_doc_type`.

**Comment by njoannin** [comment]
Cool, thanks!
