### ISSUE TITLE
Automatic deployment

### ISSUE THREAD

**Issue by lauxley** [elastic/elasticsearch-dsl-py#731]
Hello,
I am trying to improve a script that is used during deployment to **automatically** create/update indexes and mappings, but I am encountering the following issue:
`MyDocType.init()` systematically complains about `IllegalOperation: You cannot update analysis configuration on an open index, you need to close index my_index first.` whether i actually change or not an analyzer. The old approach was to systematically close the index, call ```indices.put_settings``` to (eventually) change the default analyzer, ```MyDocType.init()``` and finally reopen the index.
Of course this approach is not efficient at all, and since closing/opening seems to be very slow we end up getting timeouts in the meantime.
I also tried to compare the analyzers/mappings before closing the index but since Elasticsearch make some changes to it on its end, the comparison never evaluates to True ...

How do you tackle this problem ?

**Comment by HonzaKral** [comment]
The way to tackle this is really to only create the index if it doesn't exist in your code. The easiest way to do that is to use the `Index` object which has a `save` and an `exists` methods.
