### ISSUE TITLE
aggregation not returning empty buckets

### ISSUE THREAD

**Issue by lahloug** [elastic/elasticsearch-dsl-py#734]
I want to plot the result of a date_histogram aggregations. As such; I need the aggregation to return all the dates, even those where the aggregated results is 0. Here is my query:

```
from elasticsearch_dsl import Search
from elasticsearch import Elasticsearch
from elasticsearch_dsl.connections import connections



connections.create_connection(hosts=['localhost'])
es_client = Elasticsearch()
delete_index(es_client, index_name) 
inject_sample_concept(es_client)
inject_sample_article(es_client)
cnx = Search().index(index_name).doc_type(type_name)
cnx = cnx[:100]
cnx.aggs.bucket('dates', 'date_histogram', field="published_from",
interval='day', min_doc_count=0)
cnx.aggs["dates"].metric("sum fields", "sum", field=field_name)
cnx.execute().aggregations._d_['dates']['buckets']

```

and the result is :

```
Out[73]: 
[{'doc_count': 17,
  'key': 1470009600000,
  'key_as_string': '2016-08-01T00:00:00.000Z',
  'sum fields': {'value': 1.0}}]

```

The problem is I have 5 others days that are not showing because their sum field_value is 0...
EDIT : if I executed the last line apart  I get the desired results :

```
Out[3]: 
[{'bar': {'value': 1.0},
  'doc_count': 21,
  'key': 1470009600000,
  'key_as_string': '2016-08-01T00:00:00.000Z'},
 {'bar': {'value': 0.0},
  'doc_count': 1,
  'key': 1470096000000,
  'key_as_string': '2016-08-02T00:00:00.000Z'},
 {'bar': {'value': 0.0},
  'doc_count': 1,
  'key': 1470182400000,
  'key_as_string': '2016-08-03T00:00:00.000Z'},
 {'bar': {'value': 0.0},
  'doc_count': 1,
  'key': 1470268800000,
  'key_as_string': '2016-08-04T00:00:00.000Z'},
 {'bar': {'value': 0.0},
  'doc_count': 1,
  'key': 1470355200000,
  'key_as_string': '2016-08-05T00:00:00.000Z'}]
```
Is there some kind of delay the aggs needs ?

**Comment by HonzaKral** [comment]
@lahloug are you calling `refresh` on the index? By default documents are available for search only after 1 second. The way around it is to call the `refresh` API (0).

I will close this issue since that seems to be the culprit, if that is not the case please feel free to reopen the issue and share the code you are using to create the documents in elasticsearch.

Thanks!

0 - https://www.elastic.co/guide/en/elasticsearch/reference/5.6/indices-refresh.html
