### ISSUE TITLE
How to set timestamp in meta?

### ISSUE THREAD

**Issue by syncml** [elastic/elasticsearch-dsl-py#738]
Elasticsearch Version=5.5.2
```
class A(DocType):

      ......
      class Meta:
        timestamp = MetaField(enabled=True, store=True)
```

throw this exception:
`
elasticsearch.exceptions.RequestError: TransportError(400, u'illegal_argument_exception', u'[_timestamp] is removed in 5.0. As a replacement, you can use an ingest pipeline to add a field with the current timestamp to your documents.')

`

**Comment by HonzaKral** [comment]
Hi, as the exception suggests `_timestamp` is no longer supported in elasticsearch 5.x
