### ISSUE TITLE
Mapping for field [suggest] not found despite having given mapping in index

### ISSUE THREAD

**Issue by riemannzeta1191** [elastic/elasticsearch-dsl-py#740]
I am trying to create suggestion index for every row of a certain table.My code is as follows:-

def bulk_indexing_autocomplete():
    mapping = '''
        {
        "mappings": {
            "user_search" : {
                "properties" : {
                    "suggest" : {
                        "type" : "completion",
                    },
                    "name" : {
                        "type": "text"
                    },
                    "username" : {
                        "type": "text"
                    },
                    "id" : {
                        "type" : "long"
                    },
                    "company" : {
                        "type" : "text"
                    },    
                    "position" : {
                        "type" : "text"
                    }

                }
            }
        }
    }'''
    AutocompleteSearchIndex.init(index="autoidx")
    es = Elasticsearch(hosts=[elasticsearch_url],timeout = 30,retry_on_timeout=True)
    es.indices.create(index='autoidx', ignore=400,body=mapping)
    bulk(client=es, actions=(b.auto_indexing() for b in UserSearch.objects.all().iterator()),refresh=True)
    print("hello")
    u = UserSearch.objects.all()
    for elm in u:
        id = elm.user_id
        body = {"doc": {"suggest": {"input": [elm.name, elm.username, elm.company, elm.company_address]}}}

        es.update("autoidx", "user_search", id, body=body, refresh=True,_source =True)
        print("bye")

post this I get a response where i do not find the suggest field.Plz help
Thanks in advance

**Comment by HonzaKral** [comment]
What do you mean you get a response without the `suggest` field? How are you asking for the document, can you please share that code? Thanks!

**Comment by HonzaKral** [comment]
closing this due to lack of information, please feel free to reopen with additional data.
