### ISSUE TITLE
How to apply custom analyzer for query?

### ISSUE THREAD

**Issue by caoyuan** [elastic/elasticsearch-dsl-py#741]
I have customized an analyzer named "my_analyzer", and would like to apply it to query. I'm currently doing it in the following way
```
my_analyzer = analyzer('my_analyzer',
    tokenizer=tokenizer('trigram', 'nGram', min_gram=3, max_gram=3),
    filter=['lowercase']
)
s = Search(using=es, index="test-index")
    .query("multi_match", query='query words', fuzziness="AUTO", fields=['author', 'text'], analyzer='my_analyzer')
```
But obviously it doesn't work, and yields the following error:
```
TransportError(400, u'search_phase_execution_exception', u'[multi_match] analyzer [my_analyzer] not found')
```
So what is be the right way of applying a custom analyzer to the query function?

**Comment by HonzaKral** [comment]
When using an analyzer in a query, it needs to be defined on that index. It looks like in this case it is not so. You need to add it to the index before creating it. If you are using `Index` objects to manage your indices those have an `analyzer` method that will allow you to add custom analyzers.

**Comment by bingimar** [comment]
@HonzaKral can you supply an example?
