### ISSUE TITLE
Term query not working with nested mapping

### ISSUE THREAD

**Issue by aayushiku** [elastic/elasticsearch-dsl-py#743]
I am trying to do a term query on a field in nested mapping. But it doesnt return any result. However, instead if I run a match query, it returns me the result.

This is my document

class Student(DocType):
    student_id = Integer()
    student_name = Text(fields={ 'raw': Text(index='not_analyzed'), 'name': Text()}, norms=False)
    marks = Nested(properties={"subject_name": Text(index='not_analyzed')})
    
my query is as follows : 

term_query = Q('term', marks__subject_name="English")
search = search.query("nested", path="marks", query=term_query, inner_hits={})

Can somebody tell me what am I doing wrong here?

**Comment by HonzaKral** [comment]
It looks like you are using the `index="not_analyzed"` option for `Text` which is no longer supported. Trye changing that to `"subject_name": Keyword()` instead and then it should work.
