### ISSUE TITLE
Can't filter by date.

### ISSUE THREAD

**Issue by anil9841284912** [elastic/elasticsearch-dsl-py#744]
Hi, I am trying to run the elasticsearch query from python using elasticsearch_dsl.
Till now, I am able to connect to the Elasticsearch server and populate some fields.
There are following fields on my index samplelogs: longDate, machinename, errormsg.
Actually, I am trying to alert to slack whenever the errormessage shows "Sys error".
For that I need to pull the records by date (from and to). I have longDate field with values in the format
"2017-10-04 09:37:42.4699". 
I am not able to filter it exactly neither by errormsg nor by longDate.

Here is what I have done till now. 

from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
ca_cert = 'C:\ca.crt'
try:
  client = Elasticsearch( ['10.*.*.1', '10.*.*.2'], http_auth=(uname', 'pwd'),  port=9200, use_ssl=True,
      verify_certs=True, ca_certs=ca_cert,
  )
  print "Connected" + '\n', client.info()
except Exception as ex:
  print "Error:", ex

s = Search(using=client, index="samplelogs").query("match", errormsg='sys')
s.filter("range", longDate={"gte": "2017-10-01", "lte": "2017-10-03"})
response = s.execute()
for hit in response:
    print(hit.meta.score, hit.longDate, hit.errormsg, hit.longDate)

Thank you,
John

**Comment by HonzaKral** [comment]
This should work just fine though I would recommend using a `datetime.datetime` instance instead of just a string. That should take care of any potential issues.
