### ISSUE TITLE
 How  to use "using=client" in Faceted Search

### ISSUE THREAD

**Issue by syncml** [elastic/elasticsearch-dsl-py#747]
How  to use "using=client" in Faceted Search
just like ：

```
s = Search(using=client, index="my-index") 
    .filter("term", category="search") 
    .query("match", title="python")   
    .exclude("match", description="beta")
```

**Comment by fxdgear** [comment]
@syncml can you please expand on your question. 

Can you please show me how you created `client`?

**Comment by HonzaKral** [comment]
Thanks for the issue @syncml!

**Comment by syncml** [comment]
@HonzaKral 
Thanks！
I use elasticsearch with this plugin https://github.com/chiangf/Flask-Elasticsearch

a search instance like this

```
from flask import Flask
from flask.ext.elasticsearch import FlaskElasticsearch

app = Flask(__name__)
es = FlaskElasticsearch(app)
s = DemoModel.search(using=es)
s = s.filter(.....)
```

**Comment by HonzaKral** [comment]
@syncml I think it would be easier to modify/expand `FlaskElasticsearch` to be able to also register that es client with the `elasticsearch_dsl.connections` so you can just use the dsl without passing the cliend explicitly:
```python
from elasticsearch_dsl.connections import connections
connections.add_connection('default', es)

# no need to specify using= now
print(DemoModel.search().count())
```

**Comment by syncml** [comment]
@HonzaKral 
Thank you !!!
it works now.
:)
