### ISSUE TITLE
Datetimes dropping miliseconds

### ISSUE THREAD

**Issue by waffleking32** [elastic/elasticsearch-dsl-py#750]
The problems causes dates like '1970-01-01T00:17:47.045Z' in ElasticSearch to end up as a datetime like
datetime.datetime(1970, 1, 1, 0, 17, 47)                                                                                        

My expectation is that this value should produce a datetime like
datetime.datetime(1970, 1, 1, 0, 17, 47, 45000)

https://github.com/elastic/elasticsearch-dsl-py/blob/269fef7fa12333f7622c3694df75a1b296d87ae2/elasticsearch_dsl/field.py#L221

This is caused by integer division on the line referenced above. Changing this line to divide by 1000.0 fixes the issue.

**Comment by mattjmcnaughton** [comment]
Submitted a quick pr - hope thats helpful :) Thanks for reporting the issue!

**Comment by marcosox** [comment]
It would be useful to add an attribute to specify if the timestamp is in seconds or milliseconds, as currently when passing directly an epoch timestamp it gets divided when it shouldn't be. It is also not quite clear from the docs.
