### ISSUE TITLE
Sort/Orderd by a list of id (meta)

### ISSUE THREAD

**Issue by robertomorati** [elastic/elasticsearch-dsl-py#751]
Hi @HonzaKral  

How are you?
Is it possible to sort the data based on a list of ids using the _id meta?  What is the best approach to this?  I need to do this in the search. I will use pagination in the response/result...

> {
>         "_index" : "pcusers-index",
>         "_type" : "user_index",
>         "_id" : "471606a6-7ab7-40ef-8950-c5c5b8c1d260",
>         "_score" : 1.0,
>         "_source" : {
>           "full_name" : "Parlene Caldas",
>           "username" : "parlene.caldas"
>         }
>       },
>       {
>         "_index" : "pcusers-index",
>         "_type" : "user_index",
>         "_id" : "4716127f-87b0-46ab-8b33-19043ec3499b",
>         "_score" : 1.0,
>         "_source" : {
>           "full_name" : "Gismenia Richelly",
>           "username" : "gismeniarichelly"
>         }
>       },
>       {
>         "_index" : "pcusers-index",
>         "_type" : user_index",
>         "_id" : "471613de-f3f0-44e7-aff1-e50ca3fe92ec",
>         "_score" : 1.0,
>         "_source" : {
>           "full_name" : "Marcos Zambeli Galbim",
>           "username" : "marcos.zambeli.galbim"
>         }
>       },
>          s = Search(index='pcusers-index').query('query_string', query='*' + data_search + '*', fields=['username', 'full_name'],  default_operator="or")[10:20] //pagination

Thanks,
Have a nice week
Roberto Morati

**Comment by HonzaKral** [comment]
I am sorry, but I am not quite sure what it is you want to accomplish here.

You have a list of IDs and you want to retrieve documents in the order of those IDs? Or you want to use the documents' `_id` field as a sort key?

thanks

**Comment by robertomorati** [comment]
@HonzaKral  
I have a list of IDs (415).
I need to do a search based in a keyword (user and username) and sort the result based on list of IDs (8 million user indexed)


Thanks.

**Comment by HonzaKral** [comment]
Thanks for the clarification. There are 2 ways to do it:

1. pass in the list of `_id` values to a script in function score that will assign score to documents based on the `_id` position in the list.

1. retrieve all documents and sort them in python:

```python
for h in sorted(response.hits, key=lambda h: IDS.index(h.meta.id)):
    print(h.meta.id)
```

If the list of IDs is manageable (less than thousands) I would suggest method 2. as it is much easier to test and manage.

Hope this helps

**Comment by robertomorati** [comment]
@HonzaKral, 


Thanks :). I'll see the first one to learn....

Have a nice week,

**Comment by HonzaKral** [comment]
Cool, this is the link to the docs for the `script_score` (0), the idea is to pass in (in `params` to the script) the mapping from `_id` to `order` and then use that as score (replace the original score).

0 -  https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-script-score
