### ISSUE TITLE
Dict query to DSL

### ISSUE THREAD

**Issue by adityosnrost** [elastic/elasticsearch-dsl-py#753]
Hi,

I would like to transform the old way of query to dsl query. I have something like this:

`"should": [{
			"multi_match": {
				"query": "albert",
				"operator": "or",
				"boost": 3,
				"fields": ["title^4", "content^3", "interest^1", "subtitle^2"]
			}
		}, {
			"multi_match": {
				"query": "einstein",
				"operator": "or",
				"boost": 3,
				"fields": ["title^4", "content^3", "interest^1", "subtitle^2"]
			}
		}, {
			"multi_match": {
				"query": "science",
				"operator": "or",
				"boost": 3,
				"fields": ["title^4", "content^3", "interest^1", "subtitle^2"]
			}
		}, . . . `

How can I use this query with .query() ?

Thanks

**Comment by WisdomPill** [comment]
You can easily define any inner structure like a dictionary as DslBase assigns every **kwarg item to the object as if it is a normal field. An example for your query might be like the following.

```python
import json

from elasticsearch_dsl.query import Bool, MultiMatch
from elasticsearch_dsl.search import Search

s = Search()
s.query = Bool(should=[MultiMatch(query='albert', operator='or', boost=3,
                                  fields=["title^4", "content^3", "interest^1", "subtitle^2"])
                       ])

print(json.dumps(s.to_dict(), indent=4))

```

**Comment by HonzaKral** [comment]
You can always construct an entire `Search` object using the raw body that you would have otherwise passed to the `.search()` method of `elasticsearch-py`:
`s = Search.from_dict(old_body_as_dict)`

Also every time you specify a query (in the `query` method of `Search` or in `Q()`) you can also use the raw dict of that query:
```python
s = Search()
s = s.query({"bool": {"should": [...]}})
```

Hope this helps!
