### ISSUE TITLE
Inconsistent wrapping of AttrDict on top_hits hits

### ISSUE THREAD

**Issue by jezeniel** [elastic/elasticsearch-dsl-py#754]
This might be related or should have been resolved in #386.

There is an inconsistency when accesing the `top_hits` hits of a bucket when slicing. Summary of replication below:
```python
# ...
search.aggs.bucket('report', 'terms', field='mac_address')
search.aggs['report'].metric(
    'extra_info', 'top_hits', size=1,
    _source={'includes': ['name']}
)
```

The snippet below returns `<class 'elasticsearch_dsl.utils.AttrDict'>` for every item:
```python
response = search.execute()
for item in response.aggregations.report.buckets[:]:  # with slice
    print(type(item.extra_info.hits.hits[0]))
```

Then the snippet below returns `<class 'dict'>`:
```python
response = search.execute()
for item in response.aggregations.report.buckets:  # no slice
    print(type(item.extra_info.hits.hits[0]))
```

**Comment by HonzaKral** [comment]
Thanks for the report, it is now fixed.

For the record you should use just `item.extra_info.hits[0]` which will give you instance of `Hit` instead of just `AttrDict`

Hope this helps
