### ISSUE TITLE
Can't run match query on fields with dashes

### ISSUE THREAD

**Issue by wcollins-ebsco** [elastic/elasticsearch-dsl-py#755]
Match queries on fields containing dashes always return 0 hits.

I'm using Python3.6.2,  elasticsearch-5.4.0, elasticsearch_dsl-5.3

Fields from example record :
"uncategorized": false,
"soft-delete": false,

#the field exists
s = Search(using=client, index='myindex').filter('exists', field='soft-delete')
>>> response = s.execute()
>>> print(response.hits.total)
1185

#0 hits soft_delete=False
>>> s = Search(using=client, index='myindex').query("match", soft_delete=False)
>>> response = s.execute()
>>> print(response.hits.total)
0

#0 hits  soft_delete=True
>>> s = Search(using=client, index='myindex').query("match", soft_delete=True)
>>> response = s.execute()
>>> print(response.hits.total)
0

#fields without dash work
>>> s = Search(using=client, index='myindex').query("match", uncategorized=False)
>>> response = s.execute()
>>> print(response.hits.total)
745

**Comment by njoannin** [comment]
@wcollins-ebsco I am a little confused about something (probably out of my own ignorance): if your field is called "soft-delete", why do you have "soft_delete" as the field you try to match?

Also, could you provide the mapping of your index?

**Comment by wcollins-ebsco** [comment]
s = Search(using=client, index='myindex').query("match", soft-delete=False)
is a syntax error (the dash is interpreted as a minus)

The mapping for the two fields in my example are:
"soft-delete": {
        "type": "boolean"
      },
"uncategorized": {
        "type": "boolean"
      }

**Comment by WisdomPill** [comment]
You can do it in a dirty way, passing the query as a dictionary in the **params argument like the following.

```python
import json

from elasticsearch_dsl.query import Match
from elasticsearch_dsl.search import Search

s = Search()
s.query = Match(**{'soft-delete': True})

print(json.dumps(s.to_dict(), indent=4))
```

**Comment by HonzaKral** [comment]
Thanks @WisdomPill, just for completeness you can always also just use the raw `dict`, to sum up all the ways:
```python
s = Search().query('match', **{'soft-delete': True})
s2 = Search().query({'match': {'soft-delete': True}})
s3 = Search().query(Match(**{'soft-delete': True}))
```
