### ISSUE TITLE
Can't use query with null value

### ISSUE THREAD

**Issue by interconnection-kayes** [elastic/elasticsearch-dsl-py#757]
Hi, I would like to find the result of which object an specific value is null.

Q('match', test__pk= None )
It shows TransportError(400, u'parsing_exception', u'No text specified for text query') 

how can i solve it?

**Comment by HonzaKral** [comment]
If you wish to looks for a `null`/`None` value please use a negation of the `exists` query: `~Q('exists', field='test.pk')`.

The reason for that is that `null`/`None` values don't get stored in the index so the engine treats them as missing.

Hope this helps,
Honza
