### ISSUE TITLE
How to use the Attachment field with the Ingest Attachment Plugin 

### ISSUE THREAD

**Issue by StevenMapes** [elastic/elasticsearch-dsl-py#760]
I'm having trouble trying to use the  [Ingest Attachment Processor Plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/current/ingest-attachment.html#ingest-attachment) with ElasticSearch  (5.5 on AWS, 5.6 local).

I'm using [Persistence](http://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html) and have my class set-up like this

```
import base64
from elasticsearch_dsl.field import Attachment, Text
from elasticsearch_dsl import DocType, analyzer

lower_keyword = analyzer('keyword', tokenizer="keyword", filter=["lowercase"])

class ExampleIndex(DocType):
    class Meta:
        index = 'example'
        doc_type = 'Example'

    id = Text()
    name = Text(analyzer=lower_keyword)
    my_file = Attachment()


def index_doc(a_file):
    try:
        i = Index('example')
        i.doc_type(ExampleIndex)
        i.create()
    except Exception:
        pass
    indices = ExampleIndex()
    try:
        s = indices.search()
        r = s.query('match', name=a_file.name).execute()
        if r.success():
            for h in r:
                indices = ExampleIndex.get(id=h.meta.id)
                break
    except NotFoundError:
        pass
    except Exception:
        logger.exception("Something went wrong")
        raise

    # Populate the document   
    indices.name = a_file.name
    with open(a_file.path_to_file, 'rb') as f:
            contents = f.read()
        indices.my_file = base64.ncodebytes(contents).decode("utf-8")

    indices.save()
```
The document is a PDF but I receive the following error on save and was wondering if anyone can help point out where I am going wrong.

>   File "/home/steve/.../lib/python3.6/site-packages/elasticsearch/serializer.py", line 34, in default
    raise TypeError("Unable to serialize %r (type: %s)" % (data, type(data)))

**Comment by WisdomPill** [comment]
Well, let's start with the fact that you're not using the same field that you declared in the mapping.
You declared my_file but your putting the file in the cv field.

I have two questions for you.
1 - Did you put the mapping?
2 - Did you enable the attachment plugin in elasticsearch?
Personally I never used elasticsearch on aws so I don't know where the menu to enable plugins is.
It should be in the configuration like Elastic Cloud for instance.

After that you should write an ingest pipeline that handles the ingestion of your document.
There's a small tutorial on how to use the ingest pipeline in the official documentation (https://www.elastic.co/guide/en/elasticsearch/plugins/current/ingest-attachment.html).
I would start by setting up the development environment first.

Hope it helps.

**Comment by StevenMapes** [comment]
Sorry about the my_file - cv issue, that was a typo when I typed up the details here.

To answer your questions.

1) If you are referring to the "Document Life Cycle" then yes this is done within the index_doc function
```
try:
        i = Index('example')
        i.doc_type(ExampleIndex)
        i.create()
    except Exception:
        pass
```
This creates the index prior to any documents being stored.

2) AWS Elastic Search comes with the plugin enabled out of the box along with various others, [see here](http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-plugins.html).

I have a development environment, that's the non-AWS version running 5.6 (AWS ES runs 5.5). The ingest plugin has been installed and indexing and searching works for everything I need other than attachments.

I also have tika installed (app and server) as I use that for other projects and have been using it directly at the CLI level for a few years.

Regarding the pipline, the only mention of it that I can find within the elasticsearch-dsl docs is relating to the [search-dsl](http://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html?highlight=pipeline). Has it not been wrapped so I need to go back to the low-level client?

**Comment by StevenMapes** [comment]
I have it working now, the answer was indeed to use the low-level client to create the Pipeline using the IngestClient but ensuring that the Pipeline is created first, then the Index and finally the documents.

Below is a working example for future reference

```
import base64
from uuid import uuid4
from elasticsearch.client.ingest import IngestClient
from elasticsearch.exceptions import NotFoundError
from elasticsearch_dsl import analyzer, DocType, Index
from elasticsearch_dsl.connections import connections
from elasticsearch_dsl.field import Attachment, Text


# Establish a connection
host = '127.0.0.1'
port = 9200
es = connections.create_connection(host=host, port=port)

# Some custom analyzers
html_strip = analyzer('html_strip', tokenizer="standard", filter=["standard", "lowercase", "stop", "snowball"],
                      char_filter=["html_strip"])
lower_keyword = analyzer('keyword', tokenizer="keyword", filter=["lowercase"])


class ExampleIndex(DocType):
    class Meta:
        index = 'example'
        doc_type = 'Example'

    id = Text()
    uuid = Text()
    name = Text()
    town = Text(analyzer=lower_keyword)
    my_file = Attachment(analyzer=html_strip)


def save_document(doc):
    """

    :param obj doc: Example object containing values to save
    :return:
    """
    try:
        # Create the Pipeline BEFORE creating the index
        p = IngestClient(es)
        p.put_pipeline(id='myattachment', body={
            'description': "Extract attachment information",
            'processors': [
                {
                    "attachment": {
                        "field": "my_file"
                    }
                }
            ]
        })

        # Create the index. An exception will be raise if it already exists
        i = Index('example')
        i.doc_type(ExampleIndex)
        i.create()
    except Exception:
        # todo - should be restricted to the expected Exception subclasses
        pass

    indices = ExampleIndex()
    try:
        s = indices.search()
        r = s.query('match', uuid=doc.uuid).execute()
        if r.success():
            for h in r:
                indices = ExampleIndex.get(id=h.meta.id)
                break
    except NotFoundError:
        # New record
        pass
    except Exception:
        print("Unexpected error")
        raise

    # Now set the doc properties
    indices.uuid = doc.uuid
    indices.name = doc.name
    indices.town = doc.town
    if doc.my_file:
        with open(doc.my_file, 'rb') as f:
            contents = f.read()
        indices.my_file = base64.b64encode(contents).decode("ascii")

    # Save the index, using the Attachment pipeline if a file was attached
    return indices.save(pipeline="myattachment") if indices.my_file else indices.save()


class MyObj(object):
    uuid = uuid4()
    name = ''
    town = ''
    my_file = ''

    def __init__(self, name, town, file):
        self.name = name
        self.town = town
        self.my_file = file


me = MyObj("Steve", "London", '/home/steve/Documents/test.txt')

res = save_document(me)
```
