### ISSUE TITLE
Search.from_dict() returns KeyError: 'query'

### ISSUE THREAD

**Issue by WindyOrgUK** [elastic/elasticsearch-dsl-py#762]
Hello,

I just started playing with / learning  elasticsearch-dsl and took a shortcut and tried using Search.from_dict()

I have a dict. query body that works just fine with Elasticsearch python client
but it makes Search.from_dict() to throw an error

The query body:

q = {"size": 10,
  "sort": [
    {
      "@timestamp": {
        "order": "desc",
        "unmapped_type": "boolean"
      }
    }
  ],
  "query": {
    "filtered": {
      "query": {
        "query_string": {
          "analyze_wildcard": True,
          "lowercase_expanded_terms": False,
          "query": "*"
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "query": {
                "match": {
                  "@the_policy": {
                    "query": "xxxxxxxxxxxxxxxxxxxx",
                    "type": "phrase"
                  }
                }
              }
            },
            {
              "range": {
                "@timestamp": {
                  "gte": "2017-06-17 00:00:00",
                  "lte": "2017-06-17 07:28:09",
                  "format": "yyyy-MM-dd HH:mm:ss"
                }
              }
            }
          ],
          "must_not": []
        }
      }
    }
  }
}

result = Search.from_dict(q)

=============================================

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/elasticsearch_dsl/utils.py", line 212, in get_dsl_class
    return cls._classes[name]
KeyError: 'query'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/PycharmProjects/Peter_Tools/Elasticsearch/1_DSL_Test_1.py", line 71, in <module>
    result = Search.from_dict(q)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch_dsl/search.py", line 286, in from_dict
    s.update_from_dict(d)
...
...

Am i missing something obvious here ?

I am using elasticsearch-dsl  v2.2.0 

Kind regards
Peter

**Comment by WindyOrgUK** [comment]
Hi again

It seems to be the first "query" string that causes it.
Just changing the "query" to "quer" makes the Search.from_dict(q) to complete.

Regards
Peter

**Comment by HonzaKral** [comment]
The `bool` query in `filter` is malformed - instead of `{'query': {'match': {'@the_policy': {'query': 'xxxxxxxxxxxxxxxxxxxx', 'type': 'phrase'}}}}`
it should be just `{'match': {'@the_policy': {'query': 'xxxxxxxxxxxxxxxxxxxx', 'type': 'phrase'}}}`

**Comment by WindyOrgUK** [comment]
My bad,
Thank you.

Regards
Peter
