### ISSUE TITLE
Decimal field

### ISSUE THREAD

**Issue by losintikfos** [elastic/elasticsearch-dsl-py#763]
Is it possible to store amount decimal value using DSL field?

example:

```
    # Unit Price field.
    price = field.Decimal(
        min_value=0,
        precision=3,  # decimal places
        rounding=decimal.ROUND_DOWN,  # towards zeros
    )
```

**Comment by WisdomPill** [comment]
I suggest to use a long storing price as cents intead of dollars, as elasticsearch has no decimal type and will round your supposedly decimal numbers.

There's the scaled float type that does this out of the box. The documentation for it is at the following link -> https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html

Hope it helps.

**Comment by losintikfos** [comment]
@WisdomPill I am using the DSL to map map the objects will use day `Double` will be the closest to achieve this?

**Comment by WisdomPill** [comment]
No double is only a float with double the memory aka precision.
Even double rounds the numbers, try with scaled_float, that internally uses a long so you don't lose precision, but with fixed precision obviously. You just have to specify the scaling factor.
Like the following.

```python
from elasticsearch_dsl import DocType, Field, Keyword
from elasticsearch_dsl.connections import connections

connections.configure(default={'hosts': 'localhost'})


class ScaledFloat(Field):
    name = 'scaled_float'


class Sneaker(DocType):
    price = ScaledFloat(scaling_factor=100)
    name = Keyword()
    manufacturer = Keyword()

    class Meta:
        index = 'sneakers'


Sneaker.init()

shoe = Sneaker(name='Air Max', manufacturer='Nike', price=123.456)
shoe.save()

shoe = Sneaker(name='Stan Smith', manufacturer='Adidas', price=321.654)
shoe.save()
```

**Comment by fxdgear** [comment]
As suggested by @WisdomPill you should store your price in cents as opposed to dollars. 

Also the `scaled_float` has been added as of 8047f45b767d6e0dc0bbec74ba3c436d36982be0
