### ISSUE TITLE
support about _anonymous_filters  aggregations

### ISSUE THREAD

**Issue by anhzhi** [elastic/elasticsearch-dsl-py#764]
according to https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-bucket-filters-aggregation.html#_anonymous_filters

aggregations of _anonymous_filters should be supported in  https://github.com/elastic/elasticsearch-dsl-py/blob/acb44ce3de72d1fbeebc0394c5de3b2580ff1db3/elasticsearch_dsl/aggs.py#L143

please help to support this feature.

**Comment by WisdomPill** [comment]
Hi @anhzhi.
It already works, if you pass a dictionary to Filters filters parameter.
Here's an example like the anon filter aggregation that is showcased in the link you posted.

```python
import json

from elasticsearch_dsl.aggs import Filters
from elasticsearch_dsl.query import Term

agg = Filters(filters={
    'warnings': Term(body='warning'),
    'errors': Term(body='error')
})

print(json.dumps(agg.to_dict(), indent=4))
```

By the way I'm using elasticsearch-dsl-py 5.3.0, which version are you using?

**Comment by HonzaKral** [comment]
Hi @anhzhi, this is currently not possible and won't be supported in the near future. Is the named filter support insufficient for you? You can always pass in a `dict` using numbers as keys and thus getting the same result. Thanks for understanding!

**Comment by anhzhi** [comment]
@WisdomPill  @HonzaKral   
OK.  Your suggestions works as well. Thanks a lot.
