### ISSUE TITLE
Auth headers

### ISSUE THREAD

**Issue by mjnasir** [elastic/elasticsearch-dsl-py#770]
Hi, 
I have placed Ngnix server as reverse proxy for authentication of elasticseach. How Can i add auth headers to the connections?

**Comment by HonzaKral** [comment]
Hi, to use it just pass `http_auth='user:secret'` when instantiating your `Elasticsearch` instance by any method (see [0] for a list of options). If you need to adjust the raw headers, pass in `headers={'any': 'header'}`.

Hope this helps!

0 - http://elasticsearch-dsl.readthedocs.io/en/latest/configuration.html
