### ISSUE TITLE
Sorting strings with numbers naturally

### ISSUE THREAD

**Issue by OskarPersson** [elastic/elasticsearch-dsl-py#773]
How can I sort on keyword fields naturally?

If I have a set of documents with the field set to these strings:

```
foobar, foo3, foo10, foo128
```

the sorted result will be

```
foo10, foo128, foo3, foobar
```

but I need it to be

```
foo3, foo10, foo128, foobar
```

Is this currently possible?

**Comment by HonzaKral** [comment]
Hi, this is not possible out of the box. To do this you'd have to implement a `normalizer` (0) that would produce an output with the proper collation.

Another option, definitely preferred, would be to split such a field into two - one `keyword` and one `integer` and then sort on both which will produce the desired results...

Hope this helps!

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/normalizer.html
