### ISSUE TITLE
Qureying data on float data type returns field error

### ISSUE THREAD

**Issue by dhruvmarwha** [elastic/elasticsearch-dsl-py#774]
I am trying to sort results from my elasticsearch data with the help of a mapping called price which is of float type but while executing this query,i get a fieldtype error.

```
import requests
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search

es=Elasticsearch(['http://35.195.90.250:9200'])

searcing=Search(using=es,index='route-v1').sort('-price').execute()

for something in searcing.scan():
    #print(something.from.name)
    print(something.price)
    print(something.to.name)
```

This is the error-"elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', "Can't load fielddata on [price] because fielddata is unsupported on fields of type [float]. Use doc values instead.")"

Mapping Sample-{
"_index": "route-v1",
"_type": "route",
"_id": "6501",
"_version": 1,
"_score": 1,
"_source": {
"hops": 0,
"from": {
"country_code": "LK",
"sub_type": "recommended",
"geo": {
"lat": 6.278,
"lon": 80.0366
},
"type": "destination",
"continent_code": "AS",
"name": "Balapitiya, Sri Lanka",
"location_id": "1475671"
},
"distance": 1142,
"price_source": "",
"time": 2490,
"route_type": "drive",
"time_source": "",
"score": 10,
"to": {
"country_code": "IN",
"sub_type": "recommended",
"geo": {
"lat": 10.816667,
"lon": 78.683333
},
"type": "destination",
"continent_code": "destination",
"name": "Tiruchirappalli, Tamil Nadu, India",
"location_id": "25875"
},
"hops_source": "",
"price": 14846,
"score_source": ""
}
}

**Comment by HonzaKral** [comment]
This is an issue with your mappings in elasticsearch - you have both doc_values and fielddata disabled meaning that elasticsearch cannot access the raw values for this field. `float` fields should have `doc_values` enabled by default so I suspect something in your system disabled the option. `fielddata` is disabled by default.

Could you please check what your mappings are?

Thanks!

**Comment by dhruvmarwha** [comment]
I will check the specifications of my mappings and let you know.

**Comment by HonzaKral** [comment]
Closing issue since it is not related to the library. Please feel free to reopen with additional information
