### ISSUE TITLE
how to do 'suggest': {'input': .. } ?

### ISSUE THREAD

**Issue by littlehome-eugene** [elastic/elasticsearch-dsl-py#780]
I'm using elasticsearch 2

I used to have the following in a mapping 

```
'suggest': {
  'input': obj.search_suggest_input
}
```
I'm not sure how to create the field and insert the data for the field either with `elasticsearch-dsl`

**Comment by HonzaKral** [comment]
What are you using to define your mappings? If you are using a `DocType` class simply define a `suggest` field which will be an instance of `Completion`, see the `title_suggest` example in (0). Then you can pass in `{"input": ...}` as a value to that field.

Hope this helps

0 - http://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#doctype
