### ISSUE TITLE
[bug]Date fields parse to a local date without timezone information

### ISSUE THREAD

**Issue by okke-formsma** [elastic/elasticsearch-dsl-py#781]
Hi,

Dates parsed by elasticsearch-dsl do not have the right unix timestamp, because they are UTC times that are interpreted as local times.

Elasticsearch stores dates without timezone information, and these should be interpreted as UTC (see https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html). 

Unfortunately, `dateutil.parser.parse` which is used by the `Date._deserialize` function, interprets the date received from elasticsearch as a local date!

Example:
```python
In [26]: dateutil.parser.parse('2016-01-22 15:43:08.957').timestamp()
Out[26]: 1453473788.957 
```

This timestamp (1453473788) does not correspond to 2016-01-22 15:43:08.957 UTC, but to local time (UTC+1). You can verify the correct UTC date on http://www.convert-unix-time.com/?t=1453473788 or by using utcfromtimestamp():

```python
In [27]: datetime.datetime.utcfromtimestamp(dateutil.parser.parse('2016-01-22 15:43:08.957').timestamp())
Out[27]: datetime.datetime(2016, 1, 22, 14, 43, 8, 957000)
```

**Comment by HonzaKral** [comment]
Hi Okke,

thank you for raising this issue! I am honestly not 100% sure how to proceed here. On one hand you are absolutely correct - elasticsearch will interpret the datetimes as being in UTC.

On the other hand this would be a major breaking change forcing all users to always use timezone-aware datetimes throughout their code.

Given that we already respect the timezone, if provided, I am leaning towards leaving current behavior to play nice with others - people using timezone-aware timestamps will have the tz info preserved in elasticsearch and properly deserialized and people not concerned with timezones will not have to change their entire code base.

Alternatively we could also make this a parameter on the `Date` field whether to do the conversion.

What do you think?
Thanks!

**Comment by okke-formsma** [comment]
Hi Honza,

thanks for your swift response. I'll try the workaround of inserting timezone aware datetimes into elastic instead of the naive ones tomorrow, that would be a viable workaround for me.

A flag on the date field would be great. That would also warn people who're reading the docs about the behavior.

Thanks :)

**Comment by HonzaKral** [comment]
Added in bbd69976083bc1838e53fef69c2f1c7489c81da8

Thanks for the suggestion, hope this helps!
