### ISSUE TITLE
Append Processor?

### ISSUE THREAD

**Issue by Archetype90** [elastic/elasticsearch-dsl-py#783]
I was wondering if the functionality described here:

https://www.elastic.co/guide/en/elasticsearch/reference/5.6/append-processor.html

Is built into this library? I could not find any examples. Certainly I could query the record, append to the record, and re-save it, but this seemed like a more efficient solution.

**Comment by HonzaKral** [comment]
Currently there is no support for building ingest pipelines in the `dsl` library. You have to use the underlying `elasticsearch-py` to create it directly. Sorry for the inconvenience.
