### ISSUE TITLE
Document.get(id=id, ignore=404) problem

### ISSUE THREAD

**Issue by FilimonovAP81** [elastic/elasticsearch-dsl-py#786]
Hi all.

Strange situation have happened last time. I received such error message:  
File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/document.py", line 181, in get
    if not doc['found']:
KeyError: 'found'

then I try to use Document.get(id=id, ignore=404)

**Comment by HonzaKral** [comment]
Thank you for the report!
