### ISSUE TITLE
Update API - scripted update

### ISSUE THREAD

**Issue by radoslawroszkowiak** [elastic/elasticsearch-dsl-py#787]
Hi,
I've been playing around recently a bit with script updates (https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docs-update.html#_scripted_updates) and I wonder - does elasticsearch_dsl support this feature in any "elegant" way?

It seems that not really, but it's quite possible that I am missing something.
If so can you enlighten me how to use it?
If not, do you plan to implement this feature (or are you opened to PRs)?

I think the a convenient usage would be something like

```
object = MyDocType()
object.update(
    _script={  # this excludes the possiblity of naming fields as "_script". Not sure if it would be an issue.
        "inline": "ctx._source.tags.add(params.tag)",
        "lang": "painless",
        "params" : {
            "tag" : "blue"
        }
    }
)
```
or maybe a dedicated method `scripted_update`?

Thank you for any info or feedback on the subject. And thanks for the nice lib!

**Comment by vinntreus** [comment]
I'm after something similar, but want to provide a query as well. E.g. Set field1=x when field2=y.

How about wrapping update_by_query in DocType, would that solve both of our problems?

This is how I have done it in my subclasses of DocType:

```
class MyDoc(DocType):
    def update_by_query(self, body=None, params=None):
        index = self._get_index()
        doc_type = self._doc_type.name
        conn = self._get_connection()
        conn.update_by_query(index, doc_type=[doc_type], body=body, params=params)
```

But would be even more nice if one could chain the query methods :-)
