### ISSUE TITLE
Calling my_mapping.properties raises AttributeError

### ISSUE THREAD

**Issue by njoannin** [elastic/elasticsearch-dsl-py#79]
I fetched a mapping from es.
When wanting to look at my_mapping.properties, I got the following error:

```
>>> type(my_mapping.properties)
<class 'elasticsearch_dsl.mapping.Properties'>
>>> my_mapping.properties
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/my_python/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/utils.py", line 205, in __repr__
  File "/path/to/my_python/flask/lib/python3.3/site-packages/elasticsearch_dsl-0.0.4.dev0-py3.3.egg/elasticsearch_dsl/utils.py", line 240, in __getattr__
AttributeError: 'Properties' object has no attribute '_type_shortcut'
```

Is this the expected behaviour?

My intention was to look into individual field mappings. But so far, I can't figure out how to do so... Is there a way to do so?

Also, the ```
my_mapping.properties.to_dict()```
 gives the same result as ```
my_mapping.to_dict()```. Is that intended to be so?

Using elasticsearch-dsl-py version 0.0.4 beta

**Comment by HonzaKral** [comment]
Thanks for the report. this is my fault in a bad `repr` implementation. In the mean time you can access the individual field mappings via the get item interface:

    for field in my_mapping:
        print(field, my_mapping[field].to_dict())

**Comment by njoannin** [comment]
Glad it's useful!
Cheers,
Nicolas



Nicolas Joannin, Ph.D.
Independent research scientist
For hire on a per project basis

**Comment by HonzaKral** [comment]
Oh, also it's normal that `my_mapping.to_dict() == my_mapping.properties.to_dict()`. It can be different though if you define any mappings for metadata fields like `_all`, `_parent` etc.

**Comment by njoannin** [comment]
OK, thanks for the info!
