### ISSUE TITLE
KeyError: 'created'  return meta['created']

### ISSUE THREAD

**Issue by Penguin7z** [elastic/elasticsearch-dsl-py#793]
Hi I am using `elasticsearch-dsl-py` in my project with the version `5.4.0`. I got `key error` in `document.py line 437` for there is no key in meta. I saw it has been updated in master branch to be code `return meta["result"] == "created"`.
So when can I got the next release version.
Thanks.

**Comment by taxtgg** [comment]
What is the version of elasticsearch-py and elasticsearch? I had same issue, but noticed I was using es6. After installing version 5.6, error went away.

**Comment by Penguin7z** [comment]
Currently I inherited the class `DocType` and override the methods `save` to  and change the last line to be `return meta.get('result', '') == 'created'`

**Comment by HonzaKral** [comment]
Thank you for the report, `6.0` support is coming, currently implemented in master, to be released soon.

**Comment by Fahminajjar** [comment]
I have version `6.2.1` and I'm still facing this problem!

**Comment by shivam05011996** [comment]
This is problem has been solved, by checking the key {'created':True} from elasticsearch. Should give a PR?
