### ISSUE TITLE
How to get results in parallel from Elasticsearch?

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#794]
I need to get a long list of registers from Elasticsearc with elasticsearch.py or elasticsearch-dsl.py.

For a small results works fine but for example if I want retrieve a long result from Elasticsearch (more than 2000 registers) it is so slow and takes a long time.

I am using somthing like this:

    s = es.search()
    s = s.query(my_query)
    s = s.source()

    res = [h.id for h in s.params(size=100).scan()] 
I was thinking about to use a Pool from from multiprocessing library, but doesn´t work correctly and Elasticsearch doesn´t retrieve a complete result and at the end I don´t have all the registers that I retrive in the query to Elasticsearch.

Could somebody tell me something about this? Thanks in advance

**Comment by HonzaKral** [comment]
What you can do is use the `slice` support in `scan` and call those from a `Pool` where each process would be retrieving its own slice, in each process then do:
```python
s = s.extra(slice={'id': PROCESS_ID, 'max': NUM_OF_PROCESSES})
res = [h.id for h in s.scan()]
```

note that if you are only interested in the `id` field you can use `_source` filtering (0) to avoid retrieving the full document body from elasticsearch.

Hope this helps!

0 - http://elasticsearch-dsl.readthedocs.io/en/latest/api.html#elasticsearch_dsl.Search.source

**Comment by juandasgandaras** [comment]
Thanks for your help!!!!!!!
