### ISSUE TITLE
Filters examples use terms instead of term

### ISSUE THREAD

**Issue by bharath-elastic** [elastic/elasticsearch-dsl-py#797]
Filters examples used in [https://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#filters](url) uses "terms" instead of "term". For example

`s = s.filter('terms', tags=['search', 'python'])`
should be
`s = s.filter('term', tags=['search', 'python'])`
and
`s = s.query('bool', filter=[Q('terms', tags=['search', 'python'])])`
should be
`s = s.query('bool', filter=[Q('term', tags=['search', 'python'])])`

**Comment by HonzaKral** [comment]
When giving multiple values then `terms` (0) is the query you want to use. `term` query only supports a single value.

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html

**Comment by bharath-elastic** [comment]
D'oh!

**Comment by Faham** [comment]
It was so hard to figure find this page and figure out about 'terms', wish this page was ranked higher when googling "elasticsearch dsl filter list"

**Comment by HonzaKral** [comment]
@Faham Thanks for the feedback, generally speaking you should not have to worry about the library and just go based on the official documentation - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html as all of the elasticsearch queries are supported and we didn't really see value in duplicating (poorly) the original documentation.

Is there anything we can do to make that easier for people to see?

Thanks!
