### ISSUE TITLE
Aggregations and filtering on nested documents

### ISSUE THREAD

**Issue by aayushiku** [elastic/elasticsearch-dsl-py#798]
I have a nested document structure as below.

`{
       'name' : 'Tom',
       'report' : [
                  {
                          'subject': 'English',
                          'marks': 90
                    },
                   {
                           'subject' : 'Math',
                            'marks' : 92
                    }
    ]},
{
       'name' : 'Harry',
       'report' : [
                  {
                          'subject': 'English',
                          'marks': 78
                    },
                   {
                           'subject' : 'Science',
                            'marks' : 89
                    }
    ]}`
Please note that 'report' is a nested object.

What I want are the following

1. Given a subject eg, Math, I want all the people who have Math as a subject.
2. Max and min marks in math in the entire class.

Issue is I have been able to do step 1, but on getting inner hits, I get all the nested objects and not just those that match. For eg, on searching math, I'll get object 1, with inner hits giving objects for both 'English' and 'Math'. Now on doing aggregation, I get the min and max value calculated over all nested objects and not just matched objects.

**Comment by HonzaKral** [comment]
for 1. you will always get returned the entire document, but if you specify `inner_hits` then you will be able to *also* (on top of the `report` field on the document) access `hit.meta.inner_hits...` where just the matching nested docs will be present.

for 2. you need to have a `nested` aggregation, inside of that a `filter` aggregation to limit the dataset to only math reports and then your `min`/`max` aggs: `s.aggs.bucket('reports', 'nested', path='reports').bucket('math_reports', 'filter', filter=Q('term', reports__subject='Math')).metric('mark_stats', 'stats', field='reports.mark')`

Hope this helps

**Comment by aayushiku** [comment]
Thanks @HonzaKral 

However, I am facing one more issue, I want to have the min and max of total marks. for eg., filter on math and english, sum the marks and get minimum and maximum from all docs.
Is this possible?

**Comment by HonzaKral** [comment]
@aayushiku aboslutely, it depends how you nest the aggregations inside each other - you can always add any aggregations on the level next to the `math_reports` `filter` aggregation. To do that you can just add another line:
```
s.aggs['reports'].metric('mark_stats', 'stats', field='reports.mark')
```

This will give you the stats for marks across all documents. You can have both of those aggregations in a single`Search` request to calculate all of these things at once.

**Comment by aayushiku** [comment]
@HonzaKral The problem is that I need to first sum over all nested docs within a single document and then run stats over it. 

I tried doing: 
search.aggs.bucket('marks', 'nested', path='report').bucket(
            'report_marks', 'filter', filter=Q('term', reports__subject='Math'))).bucket('report_sum', 'sum', field='report.marks').metric('marks_stats', 'stats', field='report.marks)

But sadly, this doesn't work. It gives error that 'Sum object has no attribute metric'.

**Comment by HonzaKral** [comment]
`sum` is a `metric` aggregation, not a `bucket` one - it doesn't return any bucket of documents so you cannot run any aggregation inside it. Also aggregations work across documents, not within a single document so you might have to first use a `terms` aggregation on some unique field like `_id` to create a separate bucket per document and nest all your other aggregations inside of that, if that's what you want. Just note that it might get very expensive for large number of documents. Also it doesn't really correlate to what you said at the beginning that you want to accomplish so I am super confused.

Could you please paste somewhere a few documents and the desired outcome of the query? Thanks!

**Comment by aayushiku** [comment]
Okay, to be more clear.

Here is a list of documents in my index
`{ 'name' : 'Tom', 'report' : [ { 'subject': 'English', 'marks': 90 }, { 'subject' : 'Math', 'marks' : 92 }, {'subject': 'Science', 'marks': 85} ]}, { 'name' : 'Harry', 'report' : [ { 'subject': 'English', 'marks': 78 }, { 'subject' : 'Science', 'marks' : 89 }, {'subject':'Math', 'marks':82} ]}, {'name' : 'Stan', 'report' : [ { 'subject': 'English', 'marks': 86 }, { 'subject' : 'Science', 'marks' : 90 }, {'subject':'Math', 'marks':92} ]}
`

Now I want the total marks (marks in English + marks in Math + marks in Science) of each person, and min and max of the total marks.

On top of it there could be a filter, say get total marks in Math and Science and min and max of this score.

@HonzaKral

**Comment by HonzaKral** [comment]
```python
s = Search(index='...')
# set size to 0 to not return any hits, just aggs
s = s[:0]
# optionally limit the people
s = s.query('match' name='Tom')

# add global marks stats to my search
s.aggs.bucket('reports', 'nested', path='report').metric('global_mark_stats', 'stats', field='report.marks')

# add per-person stats:
# split documents by _id into buckets of 1
s.aggs.bucket('people', 'terms', field='_id')\
    # we want the nested docs, so we need nested agg
    .bucket('reports', 'nested', path='report')\
    # optionally add a filters for subjects
    .bucket('subjects', 'filters', filters={'math': Q("term", report__subject__keyword="Math"), 'English': Q(...)})
    # perform the stats agg on the marks to get results
    .metric('per_person_mark_stats', 'stats', field='report.marks')
```

hope this helps!

**Comment by aayushiku** [comment]
@HonzaKral  I tried the above piece of code. Unfortunately, it gives me an error saying 

'Term' object has no attribute 'iteritems'
