### ISSUE TITLE
Create an examples directory with documentation and tests

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch-dsl-py#801]
We need a comprehensive set of examples demonstrating some more advanced concepts. Examples should have:
  * `README.rst` that would be linked from the docs
  * unified way to set up so that users can install the example and poke around
  * `requirements.txt` (or equivalent), if needed, listing dependencies
  * tests that will be run from the test suite making sure the examples keep working

Possible example ideas:

- [ ] tiny example with just some configuration options to serve as a template for other
- [ ] full-text search focused example with custom analyzers, auto complete
- [ ] time based index group including index management (possibly using `curator`?)
- [x] parent/child example (including custom `_doc_type.matches`
- [x] example migration (using `_reindex` API), replaces #293 
- [ ] ....

Any additional ideas welcome!

**Comment by WisdomPill** [comment]
I would also add, some examples on how to integrate elasticsearc_dsl_py to famous python web frameworks, like django and flask.
When I had to integrate the dsl library in my django project it was really messy.

**Comment by HonzaKral** [comment]
@WisdomPill good call, for now we have https://github.com/HonzaKral/es-django-example but that is in serious need of upgrading

**Comment by 3lnc** [comment]
2 cents from me: maybe we should expand docstrings on methods/classes, including some simple examples there.

This is not replacement of example project by any means.

**Comment by HonzaKral** [comment]
@3lnc Absolutely! I will try to do this as I go through the code but feel free to submit any PRs, especially for things exposed via the `api` docs page (and maybe we can add more stuff there as well).

**Comment by HonzaKral** [comment]
Parent child example added in #865, as yet untested, any feedback (especially on format!) more than welcome!

I gave up on automated tests and tie-in to documentation for now as I have no idea how to do it well (ideas welcome!) and it was holding us back.

**Comment by HonzaKral** [comment]
Example with migration code has been added to #865 as well

**Comment by HonzaKral** [comment]
Some examples have been added in the `examples` directory so I will close the issue and we will track any need for specific examples as separate issues.
