### ISSUE TITLE
How to specify `preference`?

### ISSUE THREAD

**Issue by eye8** [elastic/elasticsearch-dsl-py#813]
I am using Elasticsearch v.5.6 where I encountered the bouncing results problem. Whereas I am aware this problem can be avoided by using the `preference` parameter with the query, I don't seem to find `preference` supported in `elasticsearch-dsl-py`. Can you please clarify if this is supported or not, and how to use it if it's supported? Thank you.

**Comment by HonzaKral** [comment]
the way to supply any query params to `Search` is to use the `params` method so `s = s.params(preference='_local')` should do the trick.

Hope this helps!

**Comment by eye8** [comment]
Yes this indeed resolved my problem. Thank you @HonzaKral !
