### ISSUE TITLE
Results from FacetedSearch only contains script fields

### ISSUE THREAD

**Issue by OskarPersson** [elastic/elasticsearch-dsl-py#814]
In my custom `FacetedSearch` class I've overridden the `search` method to include a [`ScriptField`](http://elasticsearch-dsl.readthedocs.io/en/latest/api.html?highlight=script%20field#elasticsearch_dsl.Search.script_fields) in the results:

```
class MySearch(FacetedSearch):
    ...

    def search(self):
        s = super(MySearch, self).search()

        return s.script_fields(
            new_field={
                'script': {
                    'source': "(doc.containsKey('archive')) ? doc['archive'].value : doc['_id'].value",
                }
            }
        )
```

Now my response only contains `new_field` for each hit, how do I mix this with all other "regular" fields defined in the `DocType`?

**Comment by HonzaKral** [comment]
This is a property of `elasticsearch` itself where is you ask for a `script_field` it will not return `_source` by default. To fix that just add `s = s.source(True)` to your code.

Hope this helps!
