### ISSUE TITLE
Bool queries with different minimum_should_match values are combined incorrectly

### ISSUE THREAD

**Issue by bigbear-jrib** [elastic/elasticsearch-dsl-py#819]
Combining two queries with different minimum_should_match values seem to result in one of the minimum_should_match values getting lost.

Example:
```
>>> q1 = query.Q('bool', minimum_should_match=2, should=[query.Q('term', field='aa1'), query.Q('term', field='aa2'), query.Q('term', field='aa3'), query.Q('term', field='aa4')])
>>> q2 = query.Q('bool', minimum_should_match=3, should=[query.Q('term', field='bb1'), query.Q('term', field='bb2'), query.Q('term', field='bb3'), query.Q('term', field='bb4')])
>>> q1 | q2
Bool(minimum_should_match=2, should=[Term(field='aa1'), Term(field='aa2'), Term(field='aa3'), Term(field='aa4'), Term(field='bb1'), Term(field='bb2'), Term(field='bb3'), Term(field='bb4')])
```

I would expect instead for a new `Bool(q1, q2)` object to be created so that differing `minimum_should_match` values are preserved.

I noticed the "TODO" in the code at https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/query.py#L98, so I suspect maybe more intricate behavior is expected.  For example, ideally, `Bools` with equal `minimum_should_match` values should be combined.

Proposed fix and tests illustrating the issue at:
bigbear-jrib/elasticsearch-dsl-py@aedda6366b0f72101969c3f71059e0e498d86c03

**Comment by HonzaKral** [comment]
Thank you for the report. I see that you have already worked out a solution which looks good, would you mind submitting a PR? Thanks!
