### ISSUE TITLE
Can't change max_result_window

### ISSUE THREAD

**Issue by arielpontes** [elastic/elasticsearch-dsl-py#822]
Can't change `max_result_window` for an index with `settings` or `put_settings`.

```
> foo = Index('foo')
> foo.exists()
True
> foo.settings(max_result_window=100)
> foo.get_settings()
{...}
```

`max_result_window` is not there.

```
> foo = Index('foo')
> foo.exists()
True
> foo.put_settings(max_result_window=100)
*** TypeError: put_settings() got an unexpected keyword argument 'max_result_window'
```

How can I change it?

**Comment by HonzaKral** [comment]
Just calling `settings` on an `Index` object doesn't do a `put_settings` call to elasticsearch, it just modifies the `Index` object's state. Typically it is used to define the desired settings before using `Index.save()` to create/update an index.

Also `put_settings` accepts the same parameters as the underlying API (0) so you need to specify a `body` parameter.

Hope this helps!

0 - https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.client.IndicesClient.put_settings
