### ISSUE TITLE
Dynamically add fields in existing documents

### ISSUE THREAD

**Issue by briandestura** [elastic/elasticsearch-dsl-py#832]
Hi,

It seems Elasticsearch-DSL does not support dynamically adding new fields in existing documents of any documents created after a specific DocumentType has been created. Is this a planned feature? I think its pretty important as Elasticsearch can be used as a NoSQL datastore.

**Comment by WisdomPill** [comment]
Please, be more specific, I find it very hard to believe that what you want to do is not possible.
Explain what are you trying to do and your use case. If you want you could also post some code, I would be glad to help you

**Comment by HonzaKral** [comment]
You can always have fields on your documents that you haven't defined in the `DocType` subclass and the standard dynamic mapping (0) rules will be used in elasticsearch. To make the `DocType` subclass aware of such dynamically created fields all you have to do is call the `.refresh()` method on the class's `_doc_type` attribute: `MyDocType._doc_type.refresh()` (as mentioned in (1))

You can also always edit the `DocType` and call the `.init()` classmethod during your migration steps:

```
>>> from elasticsearch_dsl import connections, DocType, Keyword
>>> es = connections.create_connection()
>>> class MyDT(DocType):
...     f1 = Keyword()
...     class Meta:
...         index = 'i'
>>> MyDT.init()
>>> class MyDT(DocType):
...     f1 = Keyword()
...     f2 = Keyword()
...     class Meta:
...         index = 'i'
>>> MyDT.init()
>>> es.indices.get(index='i')['i']['mappings']['doc']
{'properties': {'f1': {'type': 'keyword'}, 'f2': {'type': 'keyword'}}}
```

Hope this helps!

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html
1 - http://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#document-life-cycle

**Comment by briandestura** [comment]
Awesome. I missed refresh() in the documentation. Thank you @HonzaKral.

**Comment by wizztjh** [comment]
Hi @HonzaKral, I notice the ```MyDocType._doc_type.refresh()``` is not working anymore. It is ```MyDocType._index.refresh() now?```
