### ISSUE TITLE
document id not added to HitMeta

### ISSUE THREAD

**Issue by rholloway** [elastic/elasticsearch-dsl-py#833]
I've hit an issue that is unexpected to me and am not sure if I'm doing it wrong or if it's a bug.

I have a class that overrides __init__ on doc type and handles some logic. When I'm querying for hits either using .get or .search, all results and objects come back how I think they should, but the meta.id field is missing.

A (maybe overly simplified) example:

```
class MyClass(DocType):
  my_id = Keyword()
  some_field = Boolean()

  class Meta:
    index = "my-index"

  def __init__(self, meta=None, **kwargs):
    super(MyClass, self).__init__(**kwargs)
    some_field = True
    self.more_custom_validation()

  def more_custom_validation(self):
    pass

  def save(self, **kwargs):
    self.my_id = str(uuid.uuid1()
    self.meta.id = self.my_id
    return super(MyClass, self).save(**kwargs)
```

```
> a = MyClass()
> a.some_field . # True, works
> a.save()
> a.meta.id  # a.meta.id == a.my_id, works
> b = MyClass.get(a.meta.id)
> b.meta # {'index': 'my-index'} . <-- note id isn't available here
> b.update(some_field=False) . # cannot do without manually setting b.meta.id
```

**Comment by HonzaKral** [comment]
You are not passing the `meta` to `super(MyClass, self).__init__` so it gets dropped, you need to pass through all the atributes: `super(MyClass, self).__init__(meta=meta, **kwargs)`

Hope this helps!

**Comment by rholloway** [comment]
Wow. That was the fastest response I've ever received, it's almost like a poor customer service rep that just auto closes all tickets.

The difference is you actually addressed the problem and it worked. You might just be a robot, but I'm not sure anymore. Congratulations, you just passed the turing test. I like it. Thanks!

**Comment by HonzaKral** [comment]
does.not.compute....

Always happy to help :)

**Comment by xdandyx** [comment]
> 

Recently, i come across another situation: 

```python
class BaseDoc(Document):
    def to_dict(self):
        dc=super(BaseDoc,self).to_dict()
        dc['id']=self.meta.id
        return dc
class MyDoc(BaseDoc):
    pass

doc=MyDoc()
doc.save()
print(doc.to_dict()) # AttributeError: 'HitMeta' object has no attribute 'id'
print(doc.meta.id) # this works

```

why meta can't be inherited ?

**Comment by xdandyx** [comment]
> You are not passing the `meta` to `super(MyClass, self).__init__` so it gets dropped, you need to pass through all the atributes: `super(MyClass, self).__init__(meta=meta, **kwargs)`
> 
> Hope this helps!



> You are not passing the `meta` to `super(MyClass, self).__init__` so it gets dropped, you need to pass through all the atributes: `super(MyClass, self).__init__(meta=meta, **kwargs)`
> 
> Hope this helps!

Recently, i encountered another situation: 

```python
class BaseDoc(Document):
    def to_dict(self):
        dc=super(BaseDoc,self).to_dict()
        dc['id']=self.meta.id
        return dc
class MyDoc(BaseDoc):
    xx=Text()
    class Index:
        name="test"

doc=MyDoc()
doc.save()
print(doc.to_dict()) # AttributeError: 'HitMeta' object has no attribute 'id'
print(doc.meta.id) # this works

```

why meta can't be inherited ?
