### ISSUE TITLE
facetedsearch doesn't accept filter, why?

### ISSUE THREAD

**Issue by fellipeh** [elastic/elasticsearch-dsl-py#836]
I create one FacetedSearch, and I need to pass some filter, works fine on the FacetedSearch results, but the `facets` doens't accept these filters.

How can I pass my search filter to facets ?

using lastest version.

regards

**Comment by HonzaKral** [comment]
I am sorry but this is not giving us enough information to debug the issue. Could you please provide a sample code that doesn't work for you and describe the desired result? Thank you!

**Comment by HonzaKral** [comment]
closing this issue as there is no way to reproduce it or verify, please feel free to reopen with additional information

**Comment by fellipeh** [comment]
Sorry for the delay,  so I have these code:

```
 doc_types = [DocumentIndex, ]
    index = settings.DATA_ES_INDEX_NAME
    facets = {
        'datasets': TermsFacet(field='dataset'),
        'datatype': TermsFacet(field='datatype'),
    }
```

My main problem is: I pass some filter on overrided `search()` for example.. filter to bring only with date.. 

The results area fine, but.. my facets, when I go to see `count` properties I see all records without filter...

I`m using ES 5.6

I need these, because on my front-end I use that to paginate, and I get some errors because shows me I have 5000 record but I have only 30 record using the filter.

Thanks
