### ISSUE TITLE
Korean Query example between Unicode and UTF-8

### ISSUE THREAD

**Issue by elastic7327** [elastic/elasticsearch-dsl-py#838]
Hello. 
I'm trying to make a `south-korean language searcher` using `elasticsearch-dsl-py`!!

When typing query text using `python3`, my local environment (OSX) now accepts strings as Unicode .. And it's a bit `slow`
But I heard that Elastic Search dsl It fits best with  `utf-8`
Is this true? 
Should I downgrade to Python 2.7? from python3.6.x ...

      `     q_string = "안녕하세요" # Say Hello! by Korean :P `
            response = es.search(
                    index=index,
                    doc_type="test",
                    body={
                        "from": _current_pos,
                        "size": _size,
                        "query": {
                            "match": {
                                "contents": {
                                    "query": q_string,   # <---- this is unicode...python3 
                                    "operator": "and",
                                    "analyzer": "standard",
                                    },
                            }
                        },

                        "aggs": {
                            "aggs_code" : {
                                "terms" : {
                                    "field" : "comp_code.keyword",
                                   }
                                },
                        },
                       }
                    )
`

**Comment by HonzaKral** [comment]
Hi,

Unicode (regardless of encoding) will work with both python 2.7 and python 3, I would totally recommend sticking with python3 as it makes the distinction between `unicode` and `str` go away and many headaches when dealing with non ascii characters go away with it.

The example you show should work just fine, in `elasticsearch-dsl` you could rewrite it as:
```python
from elasticsearch_dsl import Search
s = Search(index=index, doc_type="test")
s = s[_current_pos:_current_pos+_size]

# btw you shouldn't be using standard analyzer for Korean as it is ill suited for it, you probably want
# s = s.query('match', contents=q_string)
# and have the analyzer on the contents field set to korean
s = s.query('match', contents={"query": q_string, "operator": "and", "analyzer": "standard"})
s.aggs('aggs_code', 'terms', field='comp_code.keyword')
```

Hope this helps!
