### ISSUE TITLE
support sort.field

### ISSUE THREAD

**Issue by golankopi** [elastic/elasticsearch-dsl-py#839]
elastic new feature of sort field - https://www.elastic.co/guide/en/elasticsearch/reference/6.1/index-modules-index-sorting.html

is not supported, since it's require a setting to be added with the mapping (and not before or after)

for now, if I want to create my doc - `DocType.init()`
it calls the `self.mapping.save` which only creates the index without other parameters (such as settings)

**Comment by HonzaKral** [comment]
Using the `Index` (0) object this is already possible, in #800 we are also merging `DocType` and `Index` so this should be resolved there.
0 - http://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#index
