### ISSUE TITLE
Only 5 shards being queried

### ISSUE THREAD

**Issue by nitin302** [elastic/elasticsearch-dsl-py#842]
i'm using the 5.4.0 version with a simple date range filter,

s = Search(using=es, index= "xxxx") \
        .query() \
        .filter("range", created_on={"lt": "now-1y/d"})
response = s.execute()
print response._shards

The number of shards seems to be only 5, which is wrong.

However, directly running the query from Kibana Dev tools console results the proper shard count i.e 39.

Is there anything i'm missing?

**Comment by HonzaKral** [comment]
Hi, I don't think there is anything missing and I cannot replicate the issue, could you please post the exact code you are running as well as the code from the console?

Thanks!

**Comment by nitin302** [comment]
Kibana console: for the same index and ES cluster.

GET _search
{
    "query": {
        "range" : {
            "created_on" : {
                "lt" :  "now-1y/d"
            }
        }
    }
}


This returns,

{"took": 8,
  "timed_out": false,
  "_shards": {
    "total": 39,
    "successful": 39,
    "failed": 0
  },
  "hits": {
    "total": 123275,
    "max_score": 1,
    "hits": [....<json truncated>

However,
The code with python is same as what I posted before and is run on the same ES cluster for the same index which returns below shard info,
{u'successful': 5, u'failed': 0, u'total': 5}

The total hits count is : 2853 (which is much low compared to console query)

Since, both the queries are ideally the same, I'm confused as to what the issue is!

**Comment by HonzaKral** [comment]
In Kibana you are not specifying which `index` to query so it is querying all of them, in python you are limiting the search to just a single index which has 5 shards.
