### ISSUE TITLE
Indexing a large dataset

### ISSUE THREAD

**Issue by SudharchithSonty** [elastic/elasticsearch-dsl-py#843]
Hello, I am trying to index a large dataset(close to 1 M) using elasticsearch-dsl. However, when I use the .save() method, it seems to be stuck in a loop and doesn't index anything. I tried putting my data into a dist and index it using the helpers.bulk() function but that returns an error saying Object has no attribute copy. This is the code I'm using.

    class A(DocType):
        name = Text()
        age = Long()
        birthday = Text()

        class Meta:
            index = 'abc'

        def save(self, **kwargs):
           return super(Domain, self).save(**kwargs)
    #list =[]
    A.init()
    with open(file) as f:
        reader = csv.reader(f)
        for row in reader:
            abc = A( name=row[1], age=row[2], birthday=row[0])
            abc.save()
 OR
 # same loop as above
           list.append(abc)
     helpers.bulk(es, list, index='abc')

Any help with this is greatly appredciated

**Comment by HonzaKral** [comment]
You definitely want to be using `bulk` but you have to keep in mind that it is a low-level API that works with `dict`s and not `DocType` objects, proper way to do this would be:
```python
def docs_for_load():
    with open(file) as f:
        reader = csv.reader(f)
        for row in reader:
            yield A( name=row[1], age=row[2], birthday=row[0]).to_dict(True)
helpers.bulk(es, docs_for_load())
```

Hope this helps!

**Comment by SudharchithSonty** [comment]
Thank you. That works perfectly. I have one additional question. If I change the age (update it once a year), it will treat it as a new object and create a new document in the index. Is there a way I can overwrite the existing documents and not create a new one?

**Comment by HonzaKral** [comment]
just make sure each document has a unique `_id`, that way it will be overwritten: `A(_id=42)`

**Comment by SudharchithSonty** [comment]
Thank you. That's perfect

**Comment by SudharchithSonty** [comment]
Hello, One more question suppose I have a syntax like this 
    class MyType(DocType):
    name = Text()
    ranks = Nested(
        properties={
            'date': Date(),
            'rank': Long(),
        }
    )

    class Meta:
        index = 'sample'

    def save(self, **kwargs):
        return super(MyType, self).save(**kwargs)

How do I assign to a nested field by using the above function?

**Comment by HonzaKral** [comment]
just appending/assigning to the list should work, see examples in the tests:

https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_document.py#L217
https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_document.py#L312

Note that I would recommend to define a `Rank` class (extending `InnerDoc`) and just use that:
```python
class Rank(InnerDoc):
  date = Date()
  rank = Long()

class MyType(DocType):
  ranks = Nested(Rank)

mt = MyType()
mt.ranks.append(Rank(date=datetime.now(), rank=42))
```

hope this helps!

**Comment by SudharchithSonty** [comment]
I am unable to import InnerDoc. So that is why I haven't tried that. Is it specific to a version of elasticsearch?

**Comment by HonzaKral** [comment]
It is there for `6.1.0`

**Comment by SudharchithSonty** [comment]
Allright. I am using a much older version. Is there a way around it w/o using InnerDoc?

**Comment by HonzaKral** [comment]
Sure, just use `dict`s as seen on the link I sent - https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_document.py#L312

**Comment by SudharchithSonty** [comment]
Will do. This has been incredibly helpful. Thank you so much
