### ISSUE TITLE
Creating _default_ mapping

### ISSUE THREAD

**Issue by damntourists** [elastic/elasticsearch-dsl-py#845]
This is more of a support question than an actual issue. 

I'm curious if there is a way to create a `_default_` mapping for versions of elasticsearch-dsl-5x and below? I'm attempting to migrate some of our old legacy mappings (from 1x and earlier) which contained `_default_` mappings with `dynamic_templates` defined that get applied to all doctypes, however, I'm not finding a way to do this in elasticsearch-dsl-0.0.11 or 5.4.0. 

For now, I've been creating dynamic_templates using MetaField objects that get defined in a `class BaseDocType(DocType)` document which other classes will wrap like `class MyDoc(BaseDocType)`.  Perhaps I should I treat the `_default_` mapping entry as it's own `DocType`?

I understand that `_default_` is deprecated in 6x and beyond. Is there a method to do similar in later versions?

**Comment by damntourists** [comment]
It appears that creating a `class _default_(DocType)` with my MetaFields defined, then adding it to my `Index` instance using `index.doc_type(_default_)` is doing what I expect. I'm curious if this would be the correct way to achieve what I'm trying to do or if there is a preferred way?

**Comment by HonzaKral** [comment]
Hi, you can always specify your own `doc_type` name in `class Meta`:
```python
class Default(DocType):
    my_field = Text()
    class Meta:
        doc_type = '_default_'
```

and then use `Index` (0) object to register it, and all the other types, with elasticsearch.

Hope this helps!

0 - http://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#index

**Comment by damntourists** [comment]
Perfect! Thank you, @HonzaKral!
