### ISSUE TITLE
How can I disable _source stored?

### ISSUE THREAD

**Issue by checkking** [elastic/elasticsearch-dsl-py#846]
Hi, I want to disable _source storing in the index. I know I must to change mapping, but how? any one can help? thanks~
Is there any examples?

**Comment by HonzaKral** [comment]
in your `DocType` class you can specify a `MetaField` in the `class Meta`:

```python
class MyDoc(DocType):
    class Meta:
        source = MetaField(enabled=false)
```

Hope this helps!
