### ISSUE TITLE
Feature request: secure document creation in the absence of meta.version

### ISSUE THREAD

**Issue by njoannin** [elastic/elasticsearch-dsl-py#85]
Currently, there is a risk of over-writing an existing document if a new object is saved with the same id.

```
>>> test_user = TestUser(_id=1, email="test@email.com")
>>> test_user.save()
True
>>> other_user = TestUser(_id=1, email="other@email.com")
>>> other_user.save()
False
>>> other_user.meta.to_dict()
{'id': '1', 'version': 2, 'index': 'testing'}
>>> check_user = TestUser.get(1)
>>> check_user.to_dict()
{'email': 'other@email.com'}
>>> check_user.meta.to_dict()
{'id': '1', 'doc_type': 'test_users', 'index': 'testing', 'version': 2, 'found': True}
```

My suggestion is to make a save operation automatically add the argument ```op_type='create'```
 in the case where the document has no ```
meta.version```.

Would that be reasonable?

**Comment by HonzaKral** [comment]
I don't think this would behave as people expect - in most systems out there, this is exactly what happens. We could definitely expose (well, make our exposing it more explicit and document it) the op_type parameter but I really believe this should stay as is.

**Comment by njoannin** [comment]
If that is how most people expect it to be, then indeed it should not change. 

Personally, I find it counter intuitive, since anything with a version will fail to index, I'd expect that an absence of a version number would imply a creation, raising an error if it already exists. But that's probably just me... 
As it is now, the only "warning" one would have, if a document is accidentally overwritten, is that the save will return "False", but by then, it is too late.

I'll just make sure to add the op_type when necessary.

**Comment by njoannin** [comment]
I think there is nothing to add to this discussion, so I am closing it now.
