### ISSUE TITLE
facetedsearch doesn't accept filter...

### ISSUE THREAD

**Issue by fellipeh** [elastic/elasticsearch-dsl-py#850]
so I have these code:

```
 doc_types = [DocumentIndex, ]
    index = settings.DATA_ES_INDEX_NAME
    facets = {
        'datasets': TermsFacet(field='dataset'),
        'datatype': TermsFacet(field='datatype'),
    }
```

My main problem is: I pass some filter on overrided `search()` for example filter to bring only with same date.. 

The results area fine, but.. my facets, when I go to see `count` properties I see all records without filter...

I`m using ES 5.6

I need these, because on my front-end I use that to paginate, and I get some errors because shows me I have 5000 record but I have only 30 record using the filter.

As I pass the page, using pagination I can't see all the results on response from search.execute() only the records that's belong to the page.. for example.. 15 records.. 

Thanks

**Comment by HonzaKral** [comment]
I am afraid I don't understand exactly what you are doing, can you please share the code you are using to make this happen? Thank you!

**Comment by HonzaKral** [comment]
Closing this issue as we have no information and no way to reproduce, please feel free to reopen the issue with additional information
