### ISSUE TITLE
[Idea/Contribution proposition] Doctype migration/full-reindex?

### ISSUE THREAD

**Issue by David-Guillot** [elastic/elasticsearch-dsl-py#851]
Hello,

In some use cases ElasticSearch is the document-oriented mirror of another database (e.g. in an RDBMS). In such use cases, when the source database changes its schema, you may need to fully re-index your data in ES (e.g. in order to integrate new fields to existing documents).

Technically, a way to achieve that is to leverage [ES index aliases](https://www.elastic.co/guide/en/elasticsearch/guide/current/index-aliases.html) capabilities by working on concrete indices which names are timestamped, and an alias that is switched from a concrete index to another. With such mechanism it's possible to fully index a document base to a fresh new index and switch the alias when it's done.

It happens i have, in a private project, implemented such an idea, and i would just have to make it a bit more generic to contribute it to this library. The only question is: do you maintainers think this lib (and especially the `DocType` class) would be the right place for such a feature?

If so, you'll have a PR quite soon ;)

**Comment by David-Guillot** [comment]
Ah, and... maybe there is already a feature that i don't know about that would match my need... If so, please inform me and document it ;)

**Comment by HonzaKral** [comment]
That would be a great contribution. I don't think it needs to live in the actual code, but an example in the documentation or in a separate folder (see #801) would be super useful to many!

Also check out the `meta-index` branch where we are working on #800 which should make working with aliases etc simpler.

**Comment by HonzaKral** [comment]
See #865
