### ISSUE TITLE
Object-type field retuning garbage sub-fields

### ISSUE THREAD

**Issue by ArnonMarcus** [elastic/elasticsearch-dsl-py#857]
I have an 'Object' type field with some keyword sub-fields.
Occasionally, a returned value for that object-field end-up having some sub-fields like: 'f_exc__t_exc'.
My guess is that when there's a connection-error or something, it gets miss-handled because of some procedural-logic,  which ends-up with the object with this field in it (it does not exist in the database, and looks like some exception-related thing)

**Comment by HonzaKral** [comment]
I am sorry, but I am unable to replicate this. Could you please provide some additional details? Does the document have those fields also when you retrieve it directly via the low level client?

Thanks!

**Comment by ArnonMarcus** [comment]
You probably wont be able to replicate this, unless you try to emulate some connection failure (assuming that's the cause, which is what I currently assume). The field does not exist in the database, when that happens it only appears in the dsl-object (one representing the object-type field containing the dynamic sub-fields).
And I wasn't able to reproduce it either, and the problem appears occasionally and immediately goes away - which is what makes me suspect a connection-issue as the scenario, with the garbage-field materialising only for the duration of that connection-issue for the results of the request issued during that time, and my suspition is that it materializes as a consequence of a client-side bug in the way such a connection-issue is handled/misshandled.
So, any attempt to reproduce it with the lower-level api, while if successful would provide more visibility into what's going on, is unlikely to be able to be reproduced...

Alternatively, this could be a server-side bug, in which case the server would just return a result containing that garbage-sub-field, and all client-side apis are working properly reflecting it... But I was not able to find anything about that on the elasticsearch side of the fence...

**Comment by HonzaKral** [comment]
I am sorry, but I have to close this ticket as I cannot replicate the problem and there appears to be no code path that would make it possible - any connection error results in an exception which is not caught anywhere in the dsl. Please feel free to reopen with additional information
