### ISSUE TITLE
Error in docs: using Nested in mappings.

### ISSUE THREAD

**Issue by dchaplinsky** [elastic/elasticsearch-dsl-py#86]
Hello.
I'm using 0.0.4dev and this example doesn't work for me:
```
# you can also create a field manually
comment = Nested().field('author', 'string').field('created_at', 'date')

# and attach it to the mapping
m.field('comments', comment)
```
AttributeError: 'Nested' object has no attribute 'field'

I've switched to alternative like this:
```
        mapping = Mapping('declarations')
        mapping.field("general", 'object')
        mapping["general"].property('full_name', 'completion')
```

**Comment by NorthStar** [comment]
Is this supposed to be property instead of field?

>comment = field.Nested().property('author', 'string').property('created_at', 'date')

**Comment by HonzaKral** [comment]
Ah, thanks for pointing out the inconsistency, it will now always be `field` on both `Mapping` and `Nested`
