### ISSUE TITLE
Allow change mapping through DocType

### ISSUE THREAD

**Issue by eromoe** [elastic/elasticsearch-dsl-py#860]
Hello,

I think it would be usually to add some filed to a doc at development, would be good to have a built-in way to do something like  https://www.elastic.co/blog/changing-mapping-with-zero-downtime

May be named as  `DocType.reindex`

**Comment by HonzaKral** [comment]
Hi, I agree it would be great to have this as an example. I am not sure it's worth a separate functionality but we will see once we do the example.

I am closing this issue as we track all the examples we want as #801, this is on the list.
