### ISSUE TITLE
Example for how to persist using the Join field?

### ISSUE THREAD

**Issue by therefromhere** [elastic/elasticsearch-dsl-py#868]
I'm confused as to how the Join field is supposed to be used - especially given the apparent restriction that Joins must be on the same index, but in ES6 only one doc type is allowed per index?  Does this mean Joins can only be to the same doc type, or do I have my wires crossed?

A documentation example of persistence (and search) using the Join field would be really useful.

**Comment by HonzaKral** [comment]
Hi, there is a complex example in the works in #865 - https://github.com/elastic/elasticsearch-dsl-py/pull/865/files#diff-caba059a7c2e8c265658722732b4a88b which highlights how you can do some of the things with parent/child and the join field. Any and all feedback is welcome, please let us know if the example was helpful!

Thank you


> Joins must be on the same index, but in ES6 only one doc type is allowed per index? Does this mean Joins can only be to the same doc type, or do I have my wires crossed?

yes, the relation needs to be within the same document type as far as elasticsearch is concerned but we can differentiate the objects in python by defining `Meta.matches` which allows us to use different `DocType` class for different documents that have the same index and type in elasticsearch.
