### ISSUE TITLE
Parent-Child `matches() missing 1 required positional argument: 'hit'` while searching for childs

### ISSUE THREAD

**Issue by amih90** [elastic/elasticsearch-dsl-py#872]
I am trying to implement one-to-many relationship and found the parent-child example very useful.
i've managed to create an index with relationships and query for childs via POST, but when I use the elasticsearch-dsl to query for childs i get exception:

> Traceback (most recent call last):
>   File "/Users/amihollander/Eclipse/WorkspaceMain/common-scripts/pykycommon/pykycommon/connectors/es/mappers/parent_child.py", line 187, in <module>
>     for hit in response.hits:
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/elasticsearch_dsl/response/__init__.py", line 47, in hits
>     hits = AttrList(map(self._search._get_result, h['hits']))
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/elasticsearch_dsl/utils.py", line 33, in __init__
>     l = list(l)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/elasticsearch_dsl/search.py", line 197, in _get_result
>     if hasattr(doc_type, '_doc_type') and doc_type._doc_type.matches(hit):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/elasticsearch_dsl/document.py", line 92, in matches
>     return self._matches(hit)
> TypeError: matches() missing 1 required positional argument: 'hit'

my main is as follow:

```
    q = Question(title="a")
    q.save()
    q.add_answer(user=User(id=1), content="b")
    # question and answer persisted successfully

    q_a = Question.get(id="snwtlWIB6PbAhWyR8Ieh")
    # question return successfully
    response = q_a.search_answers().execute()
    # response hits in debug result with TypeError

    for hit in response.hits:
        print(hit)
```

while `hit` in debug is:
<img width="1345" alt="screen shot 2018-04-05 at 12 58 51" src="https://user-images.githubusercontent.com/11722828/38359513-3e86583a-38d1-11e8-928a-68c832606203.png">

and doc_type:
<img width="1361" alt="screen shot 2018-04-05 at 12 59 12" src="https://user-images.githubusercontent.com/11722828/38359536-53558254-38d1-11e8-884d-a16c87704cef.png">

seems like I am missing the declaration of `match(self, hit)`... but I have the same classes as the example

**UPDATE**:
Changing the Meta.matches methods to `@staticmethod` resolve the issue, but the objects still returns as `Hit`

**Comment by zivori** [comment]
Fixed for me by modifing this change in the examples:

```
def search_answers(self):

       # search only our index
       #s = self.search(index=self.meta.index)
       s = Search(index=self.meta.index)
       ...
```

( in https://github.com/elastic/elasticsearch-dsl-py/blob/4fe777c88513bc39514337295f297c7cd20081aa/examples/parent_child.py 
cc: @HonzaKral )

**Comment by amih90** [comment]
@HonzaKral your changes in the PR already fix that issue.
