### ISSUE TITLE
Aggregations not influenced by certain filtering options

### ISSUE THREAD

**Issue by barseghyanartur** [elastic/elasticsearch-dsl-py#873]
I need o define an aggregation - a single bucket (let's say ``field="document_type"``) of all the documents (``blog_entry``, ``page``, ``news_item``) within the search execution context. 

This main results (``hits``) context should be filtered on the chosen field (``document_type``), but aggregations should not be influenced by filtering on the same field (``document_type``).

So, if I filter on ``document_type="news_item"`` I want to still see aggregations on ``document_type`` as if the filter wasn't applied.

**Comment by HonzaKral** [comment]
> So, if I filter on document_type="news_item" I want to still see aggregations on document_type as if the filter wasn't applied.

if you want this behavior then you need to use `Search.post_filter` to add that filter. See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-post-filter.html for more details.

Thanks!
