### ISSUE TITLE
[ES6] scroll and sorting

### ISSUE THREAD

**Issue by eadmaster** [elastic/elasticsearch-dsl-py#878]
Is it possible to iterate over **sorted** search results with a scroll?

According to the [docs the scroll query has a sort parameter](https://www.elastic.co/guide/en/elasticsearch/guide/current/scroll.html), but i don't see how to set it with elasticsearch-dsl-py.

I'd like to sort my docs according to a `timestamp` field.

**Comment by HonzaKral** [comment]
By default the underlying `scan` helper (0) overrides the `sort` attribute of the search to make the `scan` more effective. If you do not wish that behavior you need to specify `preserve_order=True`:
```
s = Search()
for doc in s.params(preserve_order=True).scan():
    print(doc)
```

Hope this helps!

0 - http://elasticsearch-py.readthedocs.io/en/master/helpers.html#scan

**Comment by eadmaster** [comment]
About the `preserve_order` parameter the docs says:

> Note that this can be an extremely expensive operation and can easily lead to unpredictable results, use with caution.

The "unpredictable results" part scares me off a bit, what do you mean?
