### ISSUE TITLE
How to write query using elasticsearch-dsl to bring all objects

### ISSUE THREAD

**Issue by siddharthk-hashedin** [elastic/elasticsearch-dsl-py#882]
I tried doing 
MyDocument.search().query().using(client).execute() 
but its showing only 6 objects instead i have 6726 objects indexed.

**Comment by HonzaKral** [comment]
To get all the items please use the `.scan()` method instead of `execute()`.

Hope this helps!

**Comment by siddharthk-hashedin** [comment]
yup it worked! thanks
