### ISSUE TITLE
Indexing JSON data instead of models

### ISSUE THREAD

**Issue by siddharthk-hashedin** [elastic/elasticsearch-dsl-py#883]
I am using Document(DocType) to create index directly from models.
But my models are bit complicated.
Like for example, consider following scenario:
``` X is a model which I want to index, it is having a foreign key to Z model also X has an integer field and Y is another model which has a foreign key field to X.  ``` 
Now, X has about 70,000 records
What I want to do is:

1. get all queryset in form of json with specific values linked with objects in Y and Z.
2. Integer field in X is to be converted in string representation for eg: status is a integer field in X so,
      status: 1 => 'ON'
      status: 2 => 'inProgress'
      status: 3 => 'off'
     final search should include these strings not integers so, that users can search from strings ('like all 
     values of X where status is 'ON' ')

First, of all kindly help me on how to achieve above things.
Secondly, If I create a JSON or a dictionary which stores all required values of X in a format which is usable to end client(or user). Instead of indexing models how can I index this data directly, will it be a right solution? 
Can I mention on my signals to update and call this JSON conversion function whenever something changes with any of the model?

**Comment by HonzaKral** [comment]
Hi, I deal with it by defining a `to_search` method on my models which are then responsible for other related models - for example https://github.com/HonzaKral/es-django-example/blob/master/qa/models.py#L81-L99

To index the documents you can just use `.save()` method on the resulting `DocType` instance or `bulk` helper from `elasticsearch-py`: https://github.com/HonzaKral/es-django-example/blob/master/qa/management/commands/index_data.py#L29-L38

Hope this helps!
