### ISSUE TITLE
How to make auto-completion like search-as-you-type query?

### ISSUE THREAD

**Issue by siddharthk-hashedin** [elastic/elasticsearch-dsl-py#887]
My usecase is to search from documents as a person types in search box.
As person types, the values listed in table below in multiple fields should change accordingly.
I am using,
```
Q({"multi_match": {"query": str(search_param),
                                        "fields": ['field1', 'field2', 'field3', 'field4',
                                                   'field5', 'field6'],
                                        "type": 'phrase_prefix'}},
                       )
```
to complete this task.
I am using,
```` 
html_strip = analyzer('html_strip', tokenizer="standard", filter=["standard", "lowercase", "stop", "snowball"],
                      char_filter=["html_strip"]) 
````
for field1 and 
```
keyword
```
analyzer for rest of the fields.
Search is working fine but sometimes search results are not ordered properly and in many cases it shows ambiguous results what can I do to increase efficiency of search?
Is there any other query or analyzer that will suite more appropriately to my use case?

**Comment by HonzaKral** [comment]
To do search-as-you-type suggestions you should be using the `completion suggester` (0) which is exposed via the `suggest` method on `Search` (1).

Hope this helps!

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html
1 - http://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#suggestions
