### ISSUE TITLE
Version specific releases on PyPI

### ISSUE THREAD

**Issue by dan-blanchard** [elastic/elasticsearch-dsl-py#898]
For those of stuck dealing with code that needs to talk to two different version of ES, it would be really great if just like how you have `elasticsearch1` on PyPI, you also had `elasticsearch-dsl1` that relied on `elasticsearch1` (and the same for the other older versions). Currently, `elasticsearch-dsl` relies on `elasticsearch` directly (regardless of which version you pick), which makes things tricky if you want to use the DSL with an older version of ES while also using the latest `elasticsearch` to talk to an ES 6 cluster.

**Comment by HonzaKral** [comment]
Hi @dan-blanchard,

while I do understand the issue you are trying to solve I am afraid we don't have the bandwidth to support multiple version. What I would recommend you do it use the latest `elasticsearch-dsl` and pass in an instance of `Elasticsearch` class from whichever `elasticsearchX` version you need.

You can do that by passing the instance directly as `using=` kwarg or by using `add_connection` in `elasticsearch_dsl.connections` which allows you to pass in an instance.

Then just rely on your tests to catch any incompatibilities, there shouldn't be any structural ones.

Hope this helps!

**Comment by dan-blanchard** [comment]
Thanks for the tip @HonzaKral, I didn't realize there wouldn't be any structural incompatibilities we'd run into.
