### ISSUE TITLE
Object field doesn't support parameter Enabled

### ISSUE THREAD

**Issue by vinayan3** [elastic/elasticsearch-dsl-py#905]
I set `enabled=False` on an object. It's not being take into consideration.

I have a hack for it locally.
```
class ObjectFieldWithEnabled(fields.Object):
  def to_dict(self):
    if 'enabled' in self._params and not self._params['enabled']:
      return {
        'type': self.name,
        'enabled': False
      }
    return super(ObjectFieldWithEnabled, self).to_dict()
```

**Comment by HonzaKral** [comment]
fixed by 2fd76081633fded8e2713c3959ded87ed940af94

**Comment by mr-bjerre** [comment]
Is there any reason that you can't set `enabled=False` for a `Text` field?

**Comment by HonzaKral** [comment]
@mr-bjerre the reason is that the `text` type in elasticsearch itself doesn't allow that (0). If you wish to have a text field that will not be indexed please just pass in `index=False`: `Text(index=False)`


0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/text.html#text-params
