### ISSUE TITLE
MultiSearch global index setting is not being used in requests

### ISSUE THREAD

**Issue by dchaplinsky** [elastic/elasticsearch-dsl-py#906]
Hi Honza.

I'm using `elasticsearch==5.5.2` and  `elasticsearch-dsl==5.4.0`
It seems to me, that when I'm trying to use MultiSearch example from docs, it doesn't set the index/mapping in subqueries.

I'm doing
`ms = MultiSearch(index=ADDRESSES_INDEX)`
and then 
`ms = ms.add(Search().query(...))`

But when I do ms.to_dict the first row is always `{}`.

In the to_dict method of MultiSearch I can see:
```python

    def to_dict(self):
        out = []
        for s in self._searches:
            meta = {}
            if s._index:
                meta['index'] = s._index
            if s._doc_type:
                meta['type'] = s._doc_type
            meta.update(s._params)

            out.append(meta)
            out.append(s.to_dict())

        return out
```

so, meta is being overridden with `s._params`. The thing is, `_params` is always an empty dict.

**Comment by HonzaKral** [comment]
This is correct behavior as you are not setting the `index` at the Search you are adding to the `MultiSearch`. The `index` you specify should result inyou hitting `ADDRESSES_INDEX/_msearch` endpoint whic should set the `index` to `ADDRESSES_INDEX` as default on the elasticsearch layer. It is not meant to alter the body though.

Hope this helps!
