### ISSUE TITLE
Attribute

### ISSUE THREAD

**Issue by fernando-mc** [elastic/elasticsearch-dsl-py#913]
I'm working on a simple API that queries elasticsearch with the Python DSL and returns JSON. I'm noticing that when I try to turn data from a search into JSON I get an issue:
```
s = Search(using=es_client)
s = s.filter(. . .) # some filter
s = s.query('multi_match', query='some text', fields=['field1', 'field2'])
result = s.execute()['hits']['hits']
json.dumps(result)
```
Object of type 'AttrList' is not JSON serializable

Any suggestions for how to effectively coerce the results to JSON? I expected this to be a bit easier. When I try to coerce the AttrList to JSON then I get the same error with AttrDict:
`Object of type 'AttrDict' is not JSON serializable`

 Is the only resolution here to manually iterate over all the values and coerce them to a normal list or dict? 

I noticed https://github.com/elastic/elasticsearch-dsl-py/issues/748 mentions this error but I wasn't clear if it applied to this or not.

**Comment by fernando-mc** [comment]
I just ended up forcing all of the AttrDict to dict and AttrList to lists. Is there a convenience function for this?

**Comment by okke-formsma** [comment]
You can use the `to_dict()` method to make the AttrDict/AttrLists into python primitives which can be transformed to json.

If you don't need the objects, you can also use 'raw' elasticsearch-py queries which return python primitives directly.

**Comment by fernando-mc** [comment]
@okke-formsma Fair enough. I ended up coercing the data with `list()` and `to_dict()` but given that searching for the data using the python DSL and then returning JSON is a pretty common use case I guess I thought there would be an easier solution. 

I didn't want to write the 'raw' queries because constructing them was more difficult.

Maybe I'm just using the tool wrong and I have a weird use case but it might be worth looking at implementing a helper function to coerce the data to JSON-serializable attributes.

**Comment by kandziu** [comment]
Hello @fernando-mc, I think that the better solution is **marshalling** and If you are using flask or django fremeworks for your API you can find ease extensions for this.

**Comment by fernando-mc** [comment]
@kandziu Sounds good! I'll take a look at some best practices here and give that a shot. Since there's a few other options here I'll go ahead and close this.

**Comment by zhanwenchen** [comment]
I wrote (modified) the `swagger-codegen` `BaseModel` to treat an `AttrList` the same way it does a list:

```python
def to_dict(self):
        """Returns the model properties as a dict

        :rtype: dict
        """
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, (list, AttrList)):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        return result
```

**Comment by Schwankenson** [comment]
My solution: I created an own serializer field:

    class DictFieldFromEsJsonField(serializers.DictField):
        
        def to_representation(self, value):
            return super().to_representation(value.to_dict())
