### ISSUE TITLE
Are scripted aggregations possible with buckets?

### ISSUE THREAD

**Issue by rschwiebert** [elastic/elasticsearch-dsl-py#914]
I have an aggregation that runs with a scripted field like this:

`Search(using=client, index='my_index').aggs.metric(
        "total", "sum", script = {
            'source': "<some math goes here>",
            'params': {'window_start': window_start,
                       'window_end': window_end}
        }
    )`

This appears to work fine.  The .aggs attribute contains the total amount.

Now I want to split the result up by bucket over an 'entity' field in the hits.
Based on the docs at https://elasticsearch-dsl.readthedocs.io/en/6.1.0/search_dsl.html (right above "You can access an existing bucket by its name:"), it looks like the output of bucket should be able to be followed up by .metric like this, to be applied to each bucket:

`Search(using=client, index='my_index').aggs.bucket('entity_total', 'terms', field='entity').metric(
        "total", "sum", script = {
            'source': "<some math goes here>",
            'params': {'window_start': window_start,
                       'window_end': window_end}
        }
    )`

When I do that, the aggs attribute contains 'entity_total' with a Sum object on the right. What am I supposed to do with that? Why am I not seeing bucket results keyed by entity? I've read this up down and sideways and I can't make heads or tails of this interface.

**Comment by rschwiebert** [comment]
Feeling better since this morning since I got it working with an elasticsearch request of this form:

```{
    "size": 0,
    "aggs" : {
        "entity_total" : {
            "terms" : {
                "field" : "entity"
            },
            "aggs": {
                "total": {
                    "sum": {
                        "script": {
                            "source": "<some math goes here>",
                            "params": {"window_start": 0,
                                       "window_end": 9999999999}
                        }
                    }
                }
            }
        }
    }
}```

I gather that it's possible to submit the json request directly, but, I'm still curious how/if this can be done with your api.  Thanks!

**Comment by HonzaKral** [comment]
You should be able to do this directly - just think of what the json should look like and then convert the json keys to keyword args:
```
s = Search()
s.aggs.bucket('entity_total', 'terms', field='entity')\
    .metric('total', 'sum', script={'source': '...', 'params': {...}}
```

Hope this helps!
