### ISSUE TITLE
how can we convert filters applied in aggregation to dsl

### ISSUE THREAD

**Issue by PankajWorks** [elastic/elasticsearch-dsl-py#918]
I am planning to use elasticsearch-dsl-py to fetch information from elastic storage. I have a nested aggregation query part of which is 
`"aggs": {"builds": {"filters": {"filters": [{"match":{"STACK_BUILD":"ABCD"} }]}} `
How can i convert it to a dsl specific syntax?

**Comment by HonzaKral** [comment]
this would be:
```python
s = Search()
s.aggs.bucket('builds', 'filters', filters={'abcd': Q('match', STACK_BUILD='ABCD')})
```

unfortunately we don't allow a list of `filters` in the `filters` aggregation so you need to use named groups.

Hope this helps!
