### ISSUE TITLE
Is it possible to use function_score?

### ISSUE THREAD

**Issue by pcompassion** [elastic/elasticsearch-dsl-py#92]
Not sure how to do `function_score` reading the docs.

Is it possible at the moment?

**Comment by 314l5926** [comment]
I did it like this, and it seems to work 

    function_score_query = Q(
        'function_score',
        functions=[
            dict(gauss={
                'date_created': {
                    'origin': utc_today(),
                    'scale': "7d"
                }}
            ),
            dict(
                filter=F(
                    'bool',
                    must=must_filters,
                    should=should_filters
                ),
                weight=1.5
            )
        ],
        boost_mode='multiply',
        score_mode='multiply',
        query=mlt_query,
    )

**Comment by HonzaKral** [comment]
Yes, you can use just a dict or you can use the `SF` shortcuts (0)

    Q('function_score', functions=[SF('gauss', filter=F(...), date_created={...})])

0 - https://github.com/elasticsearch/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_query.py#L220-L223

**Comment by pcompassion** [comment]
thanks I'll try!

**Comment by pcompassion** [comment]
Can you construct  `Q('function_score' ..)` then add  `query` or `filter` to it?
