### ISSUE TITLE
Can't use field named "connection"

### ISSUE THREAD

**Issue by aspir** [elastic/elasticsearch-dsl-py#922]
If I have a field named "connection" in my index and I try to query the document using elasticsearch-dsl I get an error. here is the code example:
```
from elasticsearch_dsl.utils.document import DocType
from elasticsearch_dsl import connections
connections.create_connection(hosts=["localhost:9200"])
x=DocType.get(id="my_id", index="my_index")
```

my exception is 'AttributeError: can't set attribute', because 'connection' already exists in the Document class.

**Comment by HonzaKral** [comment]
Hi, this has been removed as part of #840 which should be merged soon, hope that helps!
