### ISSUE TITLE
TypeError: search() got an unexpected keyword argument 'index'

### ISSUE THREAD

**Issue by hrdxwandg** [elastic/elasticsearch-dsl-py#923]
when i run the code,get the error:TypeError: search() got an unexpected keyword argument 'index'

searcher = Search().using(es).index("music").query("match", lyrics="往事成")
print(searcher.to_dict())
response = searcher.execute()

the version is as follows:
elasticsearch==6.2.0
elasticsearch-dsl==6.1.0

How can i modify?
thanks

**Comment by hrdxwandg** [comment]
fixed,closed

**Comment by ncopiy** [comment]
@hrdxwandg how you've fixed it?

**Comment by hrdxwandg** [comment]
@ncopiy sorry, several months passed, I have forgot how to fix it. Maybe It is a small bug about configuration, I can not help you

**Comment by ncopiy** [comment]
@hrdxwandg okay :( nevertheless thank you.
