### ISSUE TITLE
Trouble filtering on date

### ISSUE THREAD

**Issue by admitstack** [elastic/elasticsearch-dsl-py#932]
I have an index called private_data, with documents such as exact.date, name, etc. The data type in exact.date is date. 

My code right now is
`s = Search(using=client, index = ['private_data']).source(['exact.date']).query("match",date= (datetime.date.today()))`

The problem is the format of the exact.date documents is for example 2018-07-02T06:55:55.569Z, whereas datetime is in the format month-day-year. Is datetime still the best option to use in this scenario?

**Comment by HonzaKral** [comment]
Yes, the `datetime` will be automatically serialized to the same format using the `isoformat` method so this should work fine. Note, however, that this is doing an exact match down to a milisecond, if that is not what you can use the `range` filter.

Hope this helps!

**Comment by admitstack** [comment]
Why doesn't my current query return any results though? Because it's searching for a particular day, and the data representing that particular day should be returned, even if the data goes more specific with its use of milliseconds.

**Comment by HonzaKral** [comment]
Because you are doing an exact match against the `date` value (== number of miliseconds since the epoch) so only the *exact* same date, down to a milisecond, would match. If you want the whole day you need to use the `range` query/filter:

```python
s = s.filter('range', date={'gte': date.today(), 'lt': date.today() + timedelta(days=1)})
```

**Comment by admitstack** [comment]
Oh OK I get the logic behind that, but I do that I get a traceback error :(

**Comment by HonzaKral** [comment]
I cannot help you if you don't share the traceback. Could it be that I omitted the imports from my example? `from datetime import date, timedelta`

**Comment by admitstack** [comment]
I did the imports. The traceback is below:

`Traceback (most recent call last):
  File "datetest.py", line 32, in <module>
    response = s.execute()
  File "/Library/Python/2.7/site-packages/elasticsearch_dsl/search.py", line 679, in execute
    **self._params
  File "/Library/Python/2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Library/Python/2.7/site-packages/elasticsearch/client/__init__.py", line 655, in search
    doc_type, '_search'), params=params, body=body)
  File "/Library/Python/2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/Library/Python/2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 185, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Library/Python/2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError`

**Comment by HonzaKral** [comment]
and what is the actual error? this is just a traceback. You can always get more info from the exception by catching it and inspecting its `.info` attribute. That should give you all the information on what went wrong in elasticsearch, probably a problem with the mappings.

**Comment by johnsiano** [comment]
You mentioned "match" does an exact match. But I thought since this individual was using query, then the queried results receive a matching score. And score implies that the match doesn't necessarily have to be exact.

**Comment by HonzaKral** [comment]
@johnsiano `match` will always choose the appropriate way to match a field and since `date` is stored as a number, there can be no partial match so it requires an exact match. Same applies to `keyword` fields etc.

Scoring typically only makes sense for `text` fields.
