### ISSUE TITLE
ValidationException when loading django fixture in 6.2.1

### ISSUE THREAD

**Issue by travislbrundage** [elastic/elasticsearch-dsl-py#933]
Something in the recent update in `6.2.1` has given me some trouble with loading my default Django users from fixtures. Pushing back to `6.2.0` works fine, although I'm wondering what is causing this to break since nothing between these two versions looks related. I can see something is modified with `DocType` which is my only clue, but I'm not catching why it would cause this problem.

So in my Django project, I have a custom `Profile` which inherits from `AbstractUser` and adds some fields - just `CharFields` and `TextFields`. 
I load some default users upon bringing up the Django instance via fixtures. I've changed some of the strings here, but the format remains the same. Example fixtures: https://gist.github.com/travislbrundage/1f0b6cdc2f45d9e05923d0d59c8fc409

I have an app that creates a `ProfileIndex` inheriting `elasticsearch_dsl`'s `DocType`. In my custom `Profile` model, I have an `indexing()` function which passes the data that I want to appear in the elasticsearch index. I have a signal which post `Profile.save()` calls `Profile.indexing()`. `.indexing()` sanitizes the data and creates a new `ProfileIndex` object with this data. Finally it calls `.save()` on the new `ProfileIndex` object. Previously, this used to work. However, now it fails at the very end of this process when calling `.save()` on the new `ProfileIndex` object.

Not sure it's relevant, but in `ProfileIndex` I have:
```
class Meta:
    index = 'profile-index'
```

Upon the failing `ProfileIndex.save()` (which should be equivalent to `DocType.save()`), the error reads:
```
File "/usr/local/lib/python2.7/site-packages/elasticsearch_dsl/document.py", line 394, in save
     index=self._get_index(index),
File "/usr/local/lib/python2.7/site-packages/elasticsearch_dsl/document.py", line 138, in _get_index
     raise ValidationException('You cannot write to a wildcard index.')
elasticsearch_dsl.exceptions.ValidationException: Problem installing fixture '/code/mydjangoapp/core/fixtures/default_users.json': You cannot write to a wildcard index.
```
What I'm most confused about is the reported error - what does it mean "cannot write to a wildcard index"? I assume it's calling `ProfileIndex` a "wildcard index", but I don't understand what changed between `6.2.0` -> `6.2.1` that makes this happen.

Any idea where I'm going wrong? Should I not be using `DocType`?

**Comment by HonzaKral** [comment]
You need to have:
```python
class Index:
    name = 'profile-index'
```

instead of your `class Meta`. Otherwise the index name defaults to `*` which would produce the error you are seeing. This is definitely a change intraduced in `6.2.0` though so not sure what's going on there.

apologies for the problems.

**Comment by travislbrundage** [comment]
Weird that I'm getting it to work in `6.2.0` but not `6.2.1`, but thank you for clarifying! I'll update my code.

Cheers!
