### ISSUE TITLE
format aware Date fields

### ISSUE THREAD

**Issue by perrierism** [elastic/elasticsearch-dsl-py#94]
In field.py there is this note to add format awareness:
```
class Date(Field):
    ...
    def _to_python(self, data):
        ...
        try:
            # TODO: add format awareness
            return parser.parse(data)
        except (TypeError, ValueError):
            raise #XXX
```

Do you have any thoughts on how you want this implemented? I may give it a shot and submit a pull request.

I think I currently need that or a workaround. I have  DocType like:

```
class DocWithTs(DocType):
    ts = Date(format = 'date_hour_minute_second_millis')
```
The format property is correct on the index after init(), so the server will not like the one-size-fits-all datetime string being sent by elasticsearch-dsl-py for that field:

```
In [0]: DocWithTs(ts=datetime.now()).save()

Out [0]: RequestError: TransportError(400, 'MapperParsingException[failed to parse [ts]]; nested: MapperParsingException[failed to parse date field [2015-03-10T01:23:31.956624], tried both date format [date_hour_minute_second_millis], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "2015-03-10T01:23:31.956624" is malformed at "624"]; ')
```

```
In [0]: DocWithTs(ts=datetime.now().strftime('%Y-%m-%dT%H:%M:%S.%f')[:-3]).save()
#or
In [0]: DocWithTs(ts=datetime.now().strftime("2015-03-10T01:31:46.053").save()

Out [0]: RequestError: TransportError(400, 'MapperParsingException[failed to parse [ts]]; nested: MapperParsingException[failed to parse date field [2015-03-10T01:31:46.053000], tried both date format [date_hour_minute_second_millis], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "2015-03-10T01:31:46.053000" is malformed at "000"];
```

**Comment by HonzaKral** [comment]
The problem with the format awareness is that we would have to provide parsers and formatters for all possible date formats in elasticsearch (0). Since it allows for custom date formats based on Joda (1) it is a major effort.

0 - http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html
1 - http://joda-time.sourceforge.net/api-release/org/joda/time/format/DateTimeFormat.html

**Comment by sadovnychyi** [comment]
It looks like I cannot save the document with Date field since it's not being converted into the string. (to_dict method is missing). Is there are any workaround? 

```
TransportError(400, u'MapperParsingException[failed to parse [filing_date]]; nested: MapperParsingException[failed to parse date field [2012-12-07T00:00:00], tried both date format [basic_date], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "2012-12-07T00:00:00" is malformed at "-12-07T00:00:00"]; ')
```

**Comment by HonzaKral** [comment]
@sadovnychyi what is your mapping for this example? The data being sent to elasticsearch should work unless you have customized your date format. That is, unfortunately, not supported atm.

**Comment by HonzaKral** [comment]
I don't think can or should happen. Closing the issue.
