### ISSUE TITLE
Always return a list of element is "multi=True" in Field

### ISSUE THREAD

**Issue by PPACI** [elastic/elasticsearch-dsl-py#943]
Hi everyone.
I have a use case where i want to get list of certain field. 
My field is declared as follow :
`foo= dsl.Float(multi=True)`

But according to the Field class : https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/field.py#L72

I will get a list only is there is no data or more than one data. But exactly one data will lead in a float.

I could make a PR to check in `deserialize()` if `self._multi` is set and return a list in necessary. 
What do you think about this change ?

**Comment by HonzaKral** [comment]
Hi, what do you mean exactly by:

> But exactly one data will lead in a float.

If you mean that if you set `d.foo = 4.2` then I wouldn't like to get a list back. If you manually set the field to a single value it is your decision and I don't believe the library should get in the middle of that. Same as when you don't specify `multi=True` you can still assign a list manually.

Does that make sense?

Thanks!

**Comment by PPACI** [comment]
If there is exactly one data stored in ES.
if i do the following : 
```python
d = Bar.get(...)
print(type(d.to_dict()["foo"]))
```
will it print list or float ? Reading the code, it seems that it will lead in float

**Comment by HonzaKral** [comment]
yes, it won't change the document and wrap a value in a list. What would then happen is that running `.save()` would actually change the document in elasticsearch and I don't think that we want that.

At some point the user needs to know what their data looks like. You can always define your own method to hide the inconsistencies if needed.

What we could do, if you think it would be worth it, would be to introduce another parameter (or maybe different value for `multi` like `"force"`) that would cause this behavior optionally.

**Comment by PPACI** [comment]
Yeah, you're right, it would change the document on the first .save().

As we are really using this feature already (as overriding .to_dict()), and as it would permit user to choice, I really like the `multi="force"` option. 

Would you like me to implement this as a PR ?

**Comment by HonzaKral** [comment]
I am honestly not 100% sold on the idea yet as it seems a bit magical, but we can try it. I believe that thing like this shouldn't be hidden from the user.

What I can also recommend, at least in the mean time, to do this in `__init__` where you can just see if `foo` is in `kwargs` as a float, then wrap it in `list` before passing it through to `super()` or creating your own field that does this by sublcassing the `CustomField` class.

**Comment by HonzaKral** [comment]
After much deliberation I have to close this at this point as this can lead to unexpected results. It is also easy to implement a workaround in the shape of a python method on your model that will just wrap any value in list if needed.
