### ISSUE TITLE
Querying based on index alias name

### ISSUE THREAD

**Issue by admitstack** [elastic/elasticsearch-dsl-py#944]
I know how to query based on indices, however what if my index has an alias? When I look up aliases in the context of es-dsl, it references connections, not indices.

**Comment by HonzaKral** [comment]
Any time you use an index name in elasticsearch-dsl you can also use an alias. For a more concrete example you can look at the example (0) using an alias instead of index.

Hope this helps!

0 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/alias_migration.py
