### ISSUE TITLE
**SOLVED** 

### ISSUE THREAD

**Issue by admitstack** [elastic/elasticsearch-dsl-py#945]
My code is displayed below.

```
client = Elasticsearch(url, http_auth = (username, password), verify_certs = False, read_timeout=50, terminate_after=25000)

examplename = 'GEOS.fp.asm.inst1_2d_smp_Nx.20180508_1700.V01.nc4'
s = Search(using = client, index = [set_index]).source(['metadata.Filename'])\
    .query('match', Filename={examplename})

total = s.count()

```
The error message is: `elasticsearch.exceptions.SerializationError: ({'query': {'match': {'Filename': set(['GEOS.fp.asm.inst1_2d_smp_Nx.20180508_1700.V01.nc4'])}}}, TypeError("Unable to serialize set(['GEOS.fp.asm.inst1_2d_smp_Nx.20180508_1700.V01.nc4']) (type: <type 'set'>)",))`

In general, I don't need my search term to match the whole document. So for example if the document is named GEOS.fp.asm.inst1_2d_smp_Nx.20180508_1700.V01.nc4, I want that document to be returned if I query for 20180508.

**Comment by HonzaKral** [comment]
`set` is unfortunately not supported in json, use a `list` or a single value instead.
