### ISSUE TITLE
How to return only exact matches

### ISSUE THREAD

**Issue by johnsiano** [elastic/elasticsearch-dsl-py#946]
```

s = Search(using = client, index = set_index).source(['metadata.Filename'])\
.query('match', Filename=(date))

total = s.count()

return total
```
I want to find the total number of instances where '20180511' appears in metadata.Filename in a particular index.

This query is returning a higher number of hits than I would have expected. The data format in metadata.Filename is GEOSCATCAT20180507_12+20180511_0900.V01.nc4. My date variable is in the format '20180511'. 

I think the problem is match queries do the thing with scores, where they might return a hit even if it's not an exact match. I was wondering if you had any insight regarding this issue.

**Comment by HonzaKral** [comment]
I am sorry, but I don't understand what do you mean. Your data is not an exact match to your `date` variable so exact matching won't help. Also please describe how the field is mapped and what unexpected documents you are getting back. Thanks!

**Comment by johnsiano** [comment]
I agree the data is not en exact match, which is why I'm confused that my total is not 0. 

Here is the mapping:  u'Filename': {u'norms': {u'enabled': False}, u'fields': {u'raw': {u'ignore_above': 256, u'index': u'not_analyzed', u'type': u'string'}}, u'type': u'string'},

**Comment by HonzaKral** [comment]
`Filename` is type `string` (which would be type `text` in elasticsearch 6) which means it gets *analyzed* before indexed. To see what is actually happening have a look at the `_analyze` API:
```python
client.indices.analyze(body={'text': 'GEOSCATCAT20180507_12+20180511_0900.V01.nc4'})
```

to see what's actually being stored in the index. `match` query, when run against an analyzed string field, will then do the same to the query text and try to look up the results in the index.

Hope this helps!

**Comment by johnsiano** [comment]
So I used the _analyze API, and got a return in the form: `{u'tokens': [{u'end_offset': 6, u'token': u'text', u'type': u'<ALPHANUM>', u'start_offset': 2, u'position': 1}, {u'end_offset': 36, u'token': u'geos.fp.asm.inst1_2d_smp_nx', u'type': u'<ALPHANUM>', u'start_offset': 9, u'position': 2}, {u'end_offset': 50, u'token': u'20180420_2100', u'type': u'<NUM>', u'start_offset': 37, u'position': 3}, {u'end_offset': 54, u'token': u'v01', u'type': u'<ALPHANUM>', u'start_offset': 51, u'position': 4}, {u'end_offset': 58, u'token': u'nc4', u'type': u'<ALPHANUM>', u'start_offset': 55, u'position': 5}]}`

How would this affect my querying though, as in if I'm looking for strings in the format '20180511' how should I query based on the results of _analyze? And also I'm still confused as to how my total was not 0.

**Comment by HonzaKral** [comment]
Look at the analyze API output for the documents that did match and for the query that you are sending and you should see some tokens that are the same, that is how `match` works.

I am sorry but none of your questions are related to the python library nor are they issues so, if you have any further question, please consider asking them in the forums at discuss.elastic.co

Thank you!

**Comment by ypkkhatri** [comment]
Hi,

I am facing same issue, in my doc there is an id field which string and I'm using to store uuid and I want to retrieve doc by that uuid and I'm using below code:
```
s = Search(index="MyIndex", doc_type="MyIndexDoc").query("match", id="b32b5e50-221f-4f03-a81c-ab951192c74e")
value = s.count()
# value -> more than 1 records
```
But result is more that one records, why? How can I can get only 1 record or if there is no id exist then it should be empty result or throws an error

Please help

**Comment by HonzaKral** [comment]
@ypkkhatri sounds like you should be using that field as the `_id` of the document at which point you can just do `MyDocument.get(id="UUID VALUE")` - that is much quicker and elasticsearch will guarantee the uniqueness.

The query that you supplied should also result in exact matches only, are you sure you have your mappings defined correctly in elasticsearch? Looks like you have not created the index properly by calling `MyDocument.init()`.

**Comment by ypkkhatri** [comment]
@HonzaKral Thank you so much for your quick reply, I'm not using `_id` which is generated by elasticsearch, I have my own field `id` which is showing in `_source` I want to apply filter on it

**Comment by HonzaKral** [comment]
@ypkkhatri I am sorry, I cannot help you if you don't answer my questions - it looks like you didn't create your index properly and you have your `id` field mapped as `text` in elasticsearch as you haven't correctly created your index.

Given that this is not an issue with the python library but rather a question about usage of elasticsearch itself please use the appropriate place and ask your question at https://discuss.elastic.co/

If you indeed find an issue with this library please do not hesitate and open a new issue.

Thank you.

**Comment by ypkkhatri** [comment]
@HonzaKral I have answered your question and I also told you that I'm not using `_id` field, I have my own `id` field which is appear in `_source` where I'm storing `uuid` in that, my `id` field type is `keyword` so I have used `id__keyword` which resolved my issue. but if the field is not keyword then its do not match with exact value

Thank anyway
