### ISSUE TITLE
Find the shot field in nested field with python

### ISSUE THREAD

**Issue by hrdxwandg** [elastic/elasticsearch-dsl-py#948]
I want to find the match field in a nested field.

the nested field is comprise of two fields as follows:
"text":{
"song":text
"lyrics":text
}

when i use nested query, the score_mode is set to type max. So i want to get the max score from field song or lyrics. And I want to get which field the max score come from.

How can I realize it with python library such as elasticsearch_dsl. inner_hits or others? please give an example for me.

thanks ahead

**Comment by HonzaKral** [comment]
Can you please provide the code that you are using now and provide more information on what is the expetced behavior?

This library is very straightforward in that it maps keyword arguments to keys in the resulting json representing the query. so if your `nested` query would have `"inner_hits": {}` in its json you can easily just add `inner_hits={}` to the arguments when calling the `Q` shortcut or the `query` method of the `Search` object.

**Comment by hrdxwandg** [comment]
thanks for your reply. this is my function code for generate a nested query by parameter kwargs:
`def get_multi_nested_query(kwargs):
    if "text" in kwargs.keys():
        value = kwargs["text"]

        should_list = list()
        should_list.append(Q("match", **{"text.lyric": value}))
        should_list.append(Q("match", **{"text.song_norm": value}))

        query = Q("nested",
                  path="text",
                  score_mode="max",
                  query=Q("bool", should=should_list, minimum_should_match=1),
                  inner_hits={})

        del kwargs["text"]
        return query

    return None`

the business I expect is as follow:
when I get the value from the param text, I want search on the field song_norm and lyrics. and get the score from the max mode. besides, I also want to know which field the max score come from. the lyrics and the song_norm are multi value field. So I choose the nested query method. because the multi value field actually flatten the array of values to a long single value.

**Comment by hrdxwandg** [comment]
@HonzaKral 

I use the code above and get a error like the issue: #863 

the version is elasticsearch-dsl==6.1.0

**Comment by hrdxwandg** [comment]
OK. I update the version to 6.2.1, and the error disappear.
But How can I get the matched field which the max score comes from?

**Comment by HonzaKral** [comment]
To get the information about which field matches there is no direct way. There are some indirect ways, however:

* `highlighting` (0, 1) to get back the highlighted hits
* named queries (2) to annotate the hit with the queries that matched
* configure the different queries using `function_score` to return different values based on the field that matches. This one is a bit extreme in its complexity.

btw if you decide for highlighting you can greatly simplify your code by using `multi_match`:
 
```python
    def get_multi_nested_query(kwargs):
        if "text" not in kwargs:
            return
        return Q('nested',
            inner_hits={}, 
            path='text', 
            query=Q('multi_match', 
                query=kwargs.pop('text'), 
                fields=['text.lyric', 'text.song_norm']))
```

Hope this helps!

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html
1 - http://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#highlighting
2 - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-named-queries-and-filters.html#search-request-named-queries-and-filters

**Comment by hrdxwandg** [comment]
@HonzaKral  
thanks very much. I also want to combine the the nested query and multi match query together. But do not know how to implement with code. I will have a try. 

thanks again for your reply.

**Comment by HonzaKral** [comment]
if you want to combine queries you can always use the python operators like `|` (or) and `&` (and). Of course you can use the `bool` query directly too like you are doing to have more control

**Comment by hrdxwandg** [comment]
@HonzaKral 
Hi, I meet another problem, And search for your help, thanks ahead.

I want to use more than one nested query with inner_hits concurrently. I want get the hit field for two queries q1 and q2 concurrentyly. How can I use nested query with inner_hits.for example:
query q1 search on fields text.lyric and text.song_norm, the previous above discussions can solve which field the query hit.
I also want to know which field the query q2 hit when q2 search on fields text.album and text.singer. the behavior like q1.

Can I concurrently do the search in only one time. I do not want to search twice times.

**Comment by HonzaKral** [comment]
Of course, just add two queries to the search, you might want to specify a `name` option when calling the `inner_hits` (`inner_hits={"name": "lyrics_matched"}` for example)so that you can differentiate the two sets of documents in the output (see 0 for details)

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html#_options

**Comment by hrdxwandg** [comment]
thanks very much. 
I just have a try, But I find the final score is the sum of q1 and q2 
May I get the max score from q1 and q2？

**Comment by hrdxwandg** [comment]
[query.txt](https://github.com/elastic/elasticsearch-dsl-py/files/2293376/query.txt)

this is my query dsl

**Comment by hrdxwandg** [comment]
@HonzaKral 

[query.txt](https://github.com/elastic/elasticsearch-dsl-py/files/2293382/query.txt)

this is my query dsl. thanks

**Comment by HonzaKral** [comment]
You might want to look into `function_score` to control exactly how queries are combined or use a `dis_max` query instead of `bool` to combine the two queries.

I am sorry, @hrdxwandg, but these are questions that are not related to this library and neither are issues. please use the forum at https://discuss.elastic.co/ to ask generic elasticsearch questions. Thank you!

**Comment by hrdxwandg** [comment]
@HonzaKral  
I am very grateful to you for your advice.
