### ISSUE TITLE
How do I execute parallel searches?

### ISSUE THREAD

**Issue by dennisch-11** [elastic/elasticsearch-dsl-py#949]
I have a class that that creates several reports in csv e.g. `factory.create_project_status`, `factory.create_detailed_summary`, etc.

Some of methods take longer to complete so I was thinking of executing all methods in parallel. My `factory` class takes in an Elasticsearch connection instance and the target index e.g.:

    es_client = es_connection.connect()
    target_index = 'my-index-*'

    factory = Factory(
        es_client,
        target_index,
    )

When I start my process i.e. `Process(target=factory.create_project_status).start()` I get `TypeError: can't pickle _ssl._SSLSocket objects`. If I call `connect()` from within `create_project_status` I get `TypeError: can't pickle thread.lock objects`. I've tried several solutions related to multiprocessing but none have worked for me.

How do I execute a search within a Process?

**Comment by okke-formsma** [comment]
The problem is that the connection object can not be pickled. This is the way current 'state' is passed to the subprocess you're creating. 

You should create the connection within the function you're calling, that way the connection object does not need to be pickled. 

Also see https://stackoverflow.com/questions/8804830/python-multiprocessing-pickling-error

**Comment by okke-formsma** [comment]
Have you tried not sharing the connection object at all, and only creating the es_connection from within each Process?

**Comment by HonzaKral** [comment]
Indeed, as @okke-formsma said, you need to create a new connection in every process. I recommend passing along the `kwargs` used to construct such connection.

Hope this helps!

**Comment by dennisch-11** [comment]
@okke-formsma That did the trick, thanks!
