### ISSUE TITLE
InnerDoc data gets removed

### ISSUE THREAD

**Issue by kanhais** [elastic/elasticsearch-dsl-py#951]
I have a mapping defined as following.

   ``` 
class LocationDocument(InnerDoc):
      city = Text(fields={'keyword': Keyword()})
      state = Text(fields={'keyword': Keyword()})
      country = Text(fields={'keyword': Keyword()})
      city_verbose_name = Text(fields={'keyword': Keyword()})
      city_verbose_short_name = Text(fields={'keyword': Keyword()})
      state_verbose_short_name = Text(fields={'keyword': Keyword()})
      verbose_name = Text(fields={'keyword': Keyword()})
      verbose_short_name = Text(fields={'keyword': Keyword()})
      coordinates = GeoPoint()

class AddressDocument(InnerDoc): 
     line1 = Text(fields={'keyword': Keyword()}),
     line2 = Text(fields={'keyword': Keyword()}),
     zip_code = Text(fields={'keyword': Keyword()})
     privacy = Integer(fields={'keyword': Keyword()})
     location = Object(LocationDocument)

class UserProfileDocument(DocType):
        addresses = Object(
        properties={
            'home': Object(AddressDocument),
            'office': Object(AddressDocument)
        } )
```

When I add home/office address first time, everything works fine but when I update the document line1 and line2 from address gets removed.

I did some debugging and found that it is getting removed when **from_es** method returns doc from documents.py method.

I am using 6.1.0 version of elastic search dsl.

**Comment by HonzaKral** [comment]
Thank you for the report, could you please verify for me that this is still an issue in `6.2.1`? If you cannot upgrde to `6.2.1` can you please share the code that leads to the situation you describe? I am having trouble reproduce it.

**Comment by kanhais** [comment]
Figured out the issue, it was not an dsl issue, I had comma after line1 and line2 and elastic search dsl was not creating mapping for those two fields, removed comma and everything worked.
Sorry for the inconvenience.
