### ISSUE TITLE
[Question] Using query & aggregration

### ISSUE THREAD

**Issue by Sykomaniac** [elastic/elasticsearch-dsl-py#952]
Not sure if this is the most appropriate place to raise a question - apologies if not. I have the following basic python code (see below) that:

- Executes a query against Elastic
- Adds to that query an aggregate to get the buckets for the release label

```
  query = Search(using=client, index=index) \
    .query('bool', filter=[Q("match", **{ "kubernetes__labels__session_id.keyword": id })]) \
    .query('bool', filter=[Q("match", **{ "kubernetes__container_name": "sysbench" })]) \
    .query('bool', filter=[Q("match", **{ "kubernetes__labels__type": "cpu" })]) \
    .query("multi_match", query='"total number of events"', fields=['log'])

  a = A('terms', field='kubernetes.labels.release.keyword')
  query.aggs.bucket('releases', a)

  responses = query.execute()
```

When I run this I can see that I get a total of 10 things that match my query. However, the aggregate returns the full number of possible results for the release label from Elastic.

```
GET http://172.18.0.2:9200/logstash-2018.07.16/_search [status:200 request:0.014s]
Number of responses: 10
Bucket:
{'doc_count_error_upper_bound': 0, 'sum_other_doc_count': 0, 'buckets': [{'key': 'sysbench-1', 'doc_count': 1976}, {'key': 'sysbench-2', 'doc_count': 1169}, {'key': 'sysbench-3', 'doc_count': 1115}, {'key': 'sysbench-4', 'doc_count': 288}]}
```
What I wanted was the ability to aggregate the results of my query i.e. of the 10 responses returned 9 of them are labelled sysbench-2 and 1 is labelled sysbench-3.

Is this possible? If so how :) thanks!

**Comment by HonzaKral** [comment]
@Sykomaniac there are different ways to do it, the best would be to set `size: 0` for the top level query (by slicing `query = query[:0]`) and then include a `top_hits` aggregation under the `releases` agg.

Note btw that when using `__` to replace dots you don't have to use `**{}` syntax, also there is a shortcut for filtering.

Overall the code would look like:

```python
query = Search(...).filter('match', kubernetes__labels__session_id__keyword=id).filter(...)\
  .query('multi_match', ...)
query.aggs.bucket('releases', 'terms', field=...).metric('hits', 'top_hits', size=10)
```
hope this helps!
