### ISSUE TITLE
Elastic search query  find exact match of values in the list from regexp input parameter

### ISSUE THREAD

**Issue by nikitagupta55** [elastic/elasticsearch-dsl-py#958]
My data looks like below:

  ```
{
    "name": "name1",
    "name_gr": ["gr1","gr2"]
  },
  {
    "name": "name2",
    "name_gr": ["gr1","gr2"]
  },
  {
    "name": "name3",
    "name_gr": ["gr2","gr3"]
  },
  {
    "name": "name4",
    "name_gr": ["gr1","gr2","gr3","gr4"]
  },
  {
    "name": "name4",
    "name_gr": ["gr4","gr5"]
  }
```
Now, i am trying to write elastic search query using `elasticsearch_dsl` python module by importing `Q` from it.

My input query will be some regex on `"name_gr"`. For eg: `"name_gr": "gr[12]"`. So, in this case I want all the names which has both "gr1" and "gr2" in their list of "name_gr".

So, the result for ->

Example 1 : `"name_gr": "gr[12]" will be :`

  ```
{
    "name": "name1",
    "name_gr": ["gr1","gr2"]
  },
  {
    "name": "name2",
    "name_gr": ["gr1","gr2"]
  },
  {
    "name": "name4",
    "name_gr": ["gr1","gr2","gr3","gr4"]
  }
```
because, gr1 and gr2 both are present in name1, name2 and name4.

Example 2: `"name_gr": "gr.*"` will be :

  ```
{
    "name": "name4",
    "name_gr": ["gr1","gr2","gr3","gr4"]
  }
```
because, all the gr's (gr1,gr2,gr3,gr4) are present in name4 only.

I tried writing my query like below:

```
must = [{'match':{'regexp': {'name_gr': 'gr[12]'}}}]
result = Q('bool', must = must)
```
But it gives name3 also in result, which is invalid as both gr1 and gr2 are not present in it. Please help. I am stuck in this from few days now.

Thanks.

**Comment by HonzaKral** [comment]
You are using a match query in your example where you want to be using regexp instead. To do this just use:
```python
s = Search().query('regexp', name_gr='gr[12]')
s.execute()
```

Hope this helps!

**Comment by nikitagupta55** [comment]
@HonzaKral - My query looks like this : `Q('regexp', name_gr='gr[12]')` . The problem is in the final result `name3` is also coming. It should not come as` name_gr` list of name3 contains only `gr2 not gr1`.

**Comment by HonzaKral** [comment]
regular expression `gr[12]`  also matches on `gr2` so `name3` is a valid hit.

If you want only names that have `gr1` and `gr2` you need to specify it not with a regex but with a list using a `terms` query (assuming the field is mapped as `keyword`: `Q('terms', name_gr=['gr1', 'gr2'])`

**Comment by nikitagupta55** [comment]
@HonzaKral , I also found 'terms' as a solution to this in the elastic search documentation. But my problem is in this :`Q('terms', name_gr=['gr1', 'gr2'])` ; i want something like, if i give `gr[12]` as input, is there any way, i can put this as : `Q('terms', name_gr=[{regexp : gr[12] }])`, so that list name_gr=['gr1', 'gr2'] is formed dynamically to make this thing to work.

In short, I want this: `Q('terms', name_gr=[{regexp : gr[12] }])` to be resolved as `Q('terms', name_gr=['gr1', 'gr2'])`

**Comment by HonzaKral** [comment]
That is not possible with elasticsearch, you would have to do two different queries. There is no simple way to know what are all the combinations matching a regular expression. What you need is to somehow find all the combinations and then use:
`Q('terms', name_gr=['gr1', 'gr2'])` if you want OR or `Q('term', name_gr='gr1') & Q('term', name_gr='gr2')` if you want AND logic

**Comment by nikitagupta55** [comment]
Yes right. I was thinking to do this in 2 parts:
1.)  write a query which gives me a list like : `list -> ['gr1', 'gr2']`
2.) do what you said : `Q('terms', name_gr=list)`

But how do i get the list, that's a problem. List is based on regex `gr[12]` and will return all those items that exists in my elastic search data.

**Comment by HonzaKral** [comment]
for the first part just run the `regexp` query and collect all the values that come back either from the documents or using a `terms` aggregation which will give you the unique values that are present in your dataset:
```python
s = Search()[:0]
s.aggs.bucket('name_gr', 'terms', field='name_gr')
name_gr_list = [b.key for b in s.execute().aggregations.name_gr.buckets]
```

**Comment by nikitagupta55** [comment]
I am executing my queries this way:

```
qs = Q('terms', name_gr=['gr1', 'gr2'])

# I have some different thing to set up my connection like below and this is how i exceute my query and get the results.

result = obj.conn.search(index = obj._index, doc_type = obj._type, size = 100, body = {'query' : qs.to_dict()})
```

Now, can you tell where should i actually write the thing you said. Please.

**Comment by HonzaKral** [comment]
You need to use the `Search` object to actually execute the query like I showed you twice here already. i am very sorry but I do not have the bandwidth to help you further, and since these are not issues with the library I encourage you to please read the documentation and, if still stuck, ask your questions at https://discuss.elastic.co/

thank you!
