### ISSUE TITLE
Runtime error with f = ~F(...) | ~F(...)

### ISSUE THREAD

**Issue by njoannin** [elastic/elasticsearch-dsl-py#96]
I got a ```
RuntimeError: maximum recursion depth exceeded while calling a Python object```
 when trying to combine two "must not" filters.

```
f = ~F(...) | ~F(...)```
 results in the runtime error.

I'm guessing it shouldn't do that, right?

Workaround: ```
f = ~(F(...) | F(...))```
 is OK.

**Comment by HonzaKral** [comment]
This is definitely a bug, thatnks for reporting it.

Just to mention the workaround you posted will do something different, it should be:

    f = ~(F(...) & F(...))

see http://en.wikipedia.org/wiki/De_Morgan's_laws

**Comment by njoannin** [comment]
@HonzaKral  Thanks for the link!
