### ISSUE TITLE
Elasticsearch DSL delete-by-query with a range query on a timestamp field(earlier we used ttl in es 1.5)

### ISSUE THREAD

**Issue by manojchandrabss** [elastic/elasticsearch-dsl-py#961]
Hi Team,

we are using Aws managed ES, we need to delete query which is 24 hours older or not updated. we are using below script, but not working as expected.

scenerio:

our es will be updated with latest data every 6 hours, old data which is not updated in 24 hours should be removed from es everyday. we are using below script. please guide us with perfect solution.

**from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search

s = Search(using=es).filter('term', response=404).filter('range', timestamp={'gte': 'now-1d/d' , 'lt': 'now/d'})
response = s.delete()**

Regards,
manoj.

**Comment by HonzaKral** [comment]
Hi @manojchandrabss,

actually the best solution is to create a new index every six hours and use `curator` (0) to always make sure you only have 4 indices. Deleting a whole index is much much more efficient than trying to delete a subset of documents.

Hope this helps!

0 - https://www.elastic.co/guide/en/elasticsearch/client/curator/current/about.html

**Comment by manojchandrabss** [comment]
we have large sets of catalogs, sometime 10millions indexes, creating new index every 6 hours is resource efficient, we need to update the latest data to existing indices, and indices which are not updated atleast for 24 hours should be removed. i looked into currater with age filters. 

filtertype: age
   source: creation_date
   direction: older
   unit: days
   unit_count: 1

how can i remove after finding the indices which are 1 day old
