### ISSUE TITLE
Multiple values/sources for composite aggregations

### ISSUE THREAD

**Issue by howespt** [elastic/elasticsearch-dsl-py#963]
Currently the implementation for composite aggregations is limited to a single field due to a bug. The Composite class:

https://github.com/elastic/elasticsearch-dsl-py/blob/e9c548ce940a9782619258e4bb65a482d807ef16/elasticsearch_dsl/aggs.py#L215

The sources type has a value `'hash': True` whereas in practice for multiple aggregated fields one actually need to pass a [list of hashes](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search-aggregations-bucket-composite-aggregation.html#_mixing_different_values_source).

This list of hashes seems (in my incredibly short experience of elasticsearch) like an uncommon pattern. I have a fix locally by introducing sources as a `list` - see (https://github.com/howespt/elasticsearch-dsl-py/commit/3d854a8533b547ca840f5fd30431ed1f90a84d70)

**Comment by HonzaKral** [comment]
Thank you for the report, this is a bug for sure and I will have a look at it asap.

**Comment by jerry-cruz** [comment]
I encountered the same issue. I made the changes mentioned above and it fixed the issue. @howespt are you planning on submitting a pull request?

**Comment by TeodorIvanov** [comment]
I have the same issue as well. Hope for an update soon.

**Comment by davkap92** [comment]
Hi, think I may be running into the same issue,
I applied @howespt fix but now i get 'AttributeError: 'str' object has no attribute 'iteritems'

for reference my call is:
<code>
            A({
                'terms': {
                    'script':
                    "doc['price'] + '' + doc['make'] + '' +doc['model'] + doc['province'] + doc['mileage']",
                    'min_doc_count':
                    2,
                }
            })
</code>

And if I use the original code then I get ' unknown field [min_doc_count], parser not found'
So seems to be something to do with the array, not sure if my problem is linked? If not I'll create a new issue

Thanks!

**Comment by davkap92** [comment]
I think I also do...

**Comment by HonzaKral** [comment]
Thank you for your patience, a fix has just been pushed, release coming soon.
