### ISSUE TITLE
Representing Objects in a persistent class

### ISSUE THREAD

**Issue by ChaosCA** [elastic/elasticsearch-dsl-py#966]
Hey, this is more of a question.

Take the example given here: https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html

How would this be represented in a Python class? I don't see any docs on it but I see that you do have a `Object` field in the `fields.py` file.

I'm just not sure how to nest `name` for example, into `manager` via this API. Would you just expect having `name` as a child class that inherits from `manager`? That way the object response could be accessed as `es_object.manager.name.first`?

Thank you.

**Comment by ChaosCA** [comment]
By reading the source I was able to understand the use of InnerDoc.
Thank you.

I'll leave this open for you to close, just wanted to note that the only mention of InnerDoc is within an example of Persistence but it's using the Nested property. Wasn't aware I could use it with the Object field.

**Comment by HonzaKral** [comment]
Thanks! There are also some examples of `Object` you can find in the `examples` directory: https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/parent_child.py#L52
