### ISSUE TITLE
Persistence Example / Documentation - Missing Information about Document.init()

### ISSUE THREAD

**Issue by ccaspers** [elastic/elasticsearch-dsl-py#971]
The persistence example found on https://elasticsearch-dsl.readthedocs.io/en/latest/#persistence-example explains how to use the Document class and initialize an index by calling the derived class' init() method.

When init() gets called twice (e.g. after restart of an application), an exception is raised because mappings have already been created. It would be helpful to show how to check if an index already exists. Is this the intended way to do it?

````python
    from elasticsearch_dsl.connections import connections
    es = connections.create_connection(hosts=['localhost'])
    # ...
    class Article(Document):
        class Index:
            name = 'blog'
    # ...
    if not es.indices.exists(index='blog'):
        Article.init()
````

**Comment by HonzaKral** [comment]
You can do `Article._index.exists()` but really this should be handled in a different manner as some sort of separate process - you wouldn't have code in Django's `models.py` for example to create the tables, you instead rely on a separate process to do it. We should document that it is the same case here.

**Comment by ccaspers** [comment]
@HonzaKral thanks for your reply, that was what I was looking for. I don't intend to mix index creation and model usage, but I wanted to be able to create a script to setup my indices that doesn't just raise exceptions during model-initialization when it is executed more than once.
