### ISSUE TITLE
No way to set query parameters when constructing search query with Search?

### ISSUE THREAD

**Issue by Moulde** [elastic/elasticsearch-dsl-py#977]
I am searching across multiple indices, and currently if no indices exists, i just get an empty Response, but i would like to catch the error that no indices exists.

I can only really find a reference to that flag in the elasticsearch-py project.
https://github.com/elastic/elasticsearch-py/blob/3f2b1b925ac343500b2de0e75dd2e6fca4277631/elasticsearch/client/__init__.py#L550

I'm using the Search method from this project to construct searches.

    from elasticsearch_dsl import Search
    ..
    Search(using=self.client, index=index)

Is there no way to set the 'allow_no_indices' flag?

EDIT:
Yes there is :)
https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L124

    s = Search()
    s = s.params(routing='user-1', preference='local')

**Comment by HonzaKral** [comment]
thank you for adding the answer to your question, @Moulde!
