### ISSUE TITLE
Scroll over a multiget

### ISSUE THREAD

**Issue by ChaosCA** [elastic/elasticsearch-dsl-py#978]
Is it possible to use the [scan](https://elasticsearch-dsl.readthedocs.io/en/5.4.0/api.html?highlight=scan#elasticsearch_dsl.Search.scan) API over a multiget search?

The result of my multiget might be >10,000 entries, I'm not sure if it will return all of them at once(preferable).

Example:
```python
            entries = Tweets.mget(ids, missing='skip')
            self.processed = {tweet.user: tweet for tweet in entries.scan()}
            # Won't work because the 'entries' is a list
```

Thank you :)

**Comment by HonzaKral** [comment]
the `scan` API (and helper) is only there for the search API. For multiget I am afraid you will have to do it yourself in python to slice the IDs and split it into multiple requests.
