### ISSUE TITLE
Resolving conflicts with `retry_on_conflict`

### ISSUE THREAD

**Issue by amih90** [elastic/elasticsearch-dsl-py#979]
I have lots of conflict issues and I am not sure how to handle it.

for example: 

> error=[TransportError(409, 'version_conflict_engine_exception', '[doc][custom_id0]: version conflict, current version [2] is different than the one provided [1]')]]

>error=[TransportError(409, 'version_conflict_engine_exception', '[doc][custom_id1]: version conflict, current version [9] is different than the one provided [8]')]]

I've tried to do partial update by calling `update()`, every time I wanted to update a field, but its continue happening.

When I looked for the exception I found `retry_on_conflict` parameter on elasticsearch that should help deal with it, but couldn't figure out how to provide it while updating, i've tried:
- self.update(_retry_on_conflict=5, **kwargs)
- self.update(retry_on_conflict=5, **kwargs)

both of them didn't worked, it just added new field to the document.
how I can configure the retry?

another option I thought is to update the object with another version: `self.meta.version += 1`

but I am not sure it solved my problem.

**Comment by HonzaKral** [comment]
Right now unfortunately that is not possible, I added the code for it so it will come with the next release. thank you for the report!
