### ISSUE TITLE
Support for wildcards in searches?

### ISSUE THREAD

**Issue by njoannin** [elastic/elasticsearch-dsl-py#98]
Is there support for wildcard searches (* and ?) in elasticsearch-dsl-py?

If not (yet, I hope :), what would be the workaround?

**Comment by HonzaKral** [comment]
Hi, there is support - just create the wildcard query:


    >>> from elasticsearch_dsl import Search
    >>> s = Search().query('wildcard', user='kim*')

**Comment by njoannin** [comment]
Cool! Sorry for the useless issue!

**Comment by BrockenCodeMe** [comment]
But how to wildcard search in filter fields
