### ISSUE TITLE
Querying a simple match on a document

### ISSUE THREAD

**Issue by rubimazaki** [elastic/elasticsearch-dsl-py#980]
Say I have a document defined as follows:

```
class Article(Document):
    source_id = Integer()
    guid = Keyword()
    title = Text(analyzer='standard')
    summary = Text(analyzer='standard', term_vector='yes')

```

And I want to search for it using simple match query: guid='some_value', I would expect the following simple code to do the job:

`results = Document.search(Article).query('match', guid=guid).execute()`
Then: using results as dict.

Yet using the latest and greatest version of elasticsearch_dsl I get the following exception:

`"search() got an unexpected keyword argument 'doc_type'"`

Why? It's the Document.Search() implementation that adds that argument!

I must complain that the elasticsearch-dsl won't help too much for newbies! In one part of the docs it says to use "Document.search(Article)" while in the other it is said to use Search(using=elasticsearch).index.. ... Ignoring the Document derived API. And, this is very confusing, and really unintuitive. I mean... There are multiple examples for much more complex scenarios, yet in nowhere in the docs it is explained how to do that simple search (with the document derived object. not using the general search(using ...) method).

It seems that the most native way to query would be using the object oriented method: using the Document derived object, and not specifying: 
1. The index 
2. The document type and 
3. The elasticsearch instance - shouldn't that be configured upon initialization?

So, question is: Is the right way (or do I imagine?) exists? Is it work in progress? And why do I get the exception above?

Thanks

**Comment by HonzaKral** [comment]
Just use `Article.search().query('match', guid=guid)`

>  In one part of the docs it says to use "Document.search(Article)" 

can you please point me to where this is said? That is definitely not the valid API and I cannot find it anywhere in the docs myself, thanks!

>  There are multiple examples for much more complex scenarios, yet in nowhere in the docs it is explained how to do that simple search (with the document derived object. not using the general search(using ...) method).

There is an example in the `Document` documentation, what is missing from that one? http://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#search

The proper API (`Article.search()`) doesn't require you to specify index, document type, nor connection as long as the default connection is properly configured as per http://elasticsearch-dsl.readthedocs.io/en/latest/configuration.html#default-connection


Hope this helps!

**Comment by rubimazaki** [comment]
First, the docs do specify that you must provide index+using as variables. It is not specified anywhere that it will use the defaults.
regarding the weird syntax - I think I concluded the  Document.search(Article).query() ... by myself by the sources... Holy stupid :) But it was after trying to use the docs.
So, if I do `Article.search().query('match', guid=guid)` would I still need to use Response.scan() on it or will I have the results ready?

Thanks for being patient :)

**Comment by HonzaKral** [comment]
The `Document.search` documentation example specifically mentions: `the search is already limited to the index and doc_type of our document`. As for the `using` that is documented right in the first paragraph in http://elasticsearch-dsl.readthedocs.io/en/latest/configuration.html#configuration

>  So, if I do Article.search().query('match', guid=guid) would I still need to use Response.scan() on it or will I have the results ready?

`Response` doesn't have a `scan` method, that is a method on `Search`, as documented in http://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#pagination and it is only to be used if you want to export all your documents. If you just want to retrieve them you can just iterate over the `Search` object directly just as shown in the first example in the documentation.

You can also iterate on the `Response` object.

**Comment by rubimazaki** [comment]
I think that what was confusing is that you need to call .execute() on the query, which IS explained, but maybe because there is no one complete line in the example, I missed that out... and got a Search object and not a Response one. So, for the sake of clarity: to do a simple match search use:

`results = Article.search().query('match', guid=guid).execute()`

Thanks
