### ISSUE TITLE
python3  script is deleting full indices

### ISSUE THREAD

**Issue by manojchandrabss** [elastic/elasticsearch-dsl-py#981]
Hi Team,

i want my python 3 script to delete documents in indices which are older than 1day. But my script is deleting complete indices.

 index_list = curator.IndexList(es)
   
    # Filters by age, anything with a time stamp older than 30 days in the index name.
    #index_list.filter_by_age(source='name', direction='older', timestring='%Y.%m.%d', unit='minutes', unit_count=30)

    # Filters by naming prefix.
    # index_list.filter_by_regex(kind='prefix', value='my-logs-2017')

    # Filters by age, anything created more than one month ago.
    #index_list.filter_by_age(source='creation_date', direction='older', unit='minutes', unit_count=7)
       # Delete all indices in the filtered list.
    curator.DeleteIndices(index_list).do_action()

  I want to delete documents in Elasticsearch indices which are 1 day old

**Comment by HonzaKral** [comment]
Hi, thank you for the report, unfortunately it is in the wrong repo as you seem to be looking for https://github.com/elastic/curator
