### ISSUE TITLE
Multi index search in parent_child example

### ISSUE THREAD

**Issue by amih90** [elastic/elasticsearch-dsl-py#983]
As I understand parent-child relationship forces you to use 1 shard only. Hence, in order to be scalable and persist a lot of data, I must use many indices with one shard and search in all the indices for a document.

`parent_child.py` example show how to use `class Index` and set `name=ALIAS`. 
when searching for a Question while using `Question.search`, `cls._index.search` uses `index=_name` while I was expecting that index will be set to `PATTERN` so I will get results from multiple indices, and it works! 
but I cannot run `setup()` with `index=_name` cause I get 

> elasticsearch_dsl.exceptions.ValidationException: You cannot write to a wildcard index.

I though passing index into the `cls._index.search`  so index.py search method will search for multiple indices but the method doesn't receive `index` as argument.

how I can stick to the parent_child example but search for multiple indices while searching for a Question? with Question.search()

**Comment by HonzaKral** [comment]
The index you use for parent/child data doesn't have to have a single shard - the limitation is only that a parent and all its children need to be in a single shard which elasticsearch will do automatically.

If you still want to use multiple indices you can set the `class Index: name` to a wildcard but then you just need to make sure you specify `index="concrete_index"` when doing any write operation (whether it is `init` or `save`).

Hope this helps!
