### ISSUE TITLE
Add `test` (or maybe `analyze`) method to `Analyzer` class

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch-dsl-py#984]
This will allow for super simple testing of analyzers.

Inspired by https://interactive-elastic.herokuapp.com/, thanks @gtalarico!

**Comment by sinscary** [comment]
@HonzaKral Can i work on this?

**Comment by HonzaKral** [comment]
@sinscary absolutely, that would be amazing!

Let me know if there is anything I can do to help!
