### ISSUE TITLE
lookahead Regexp doesnt work in ES dsl query

### ISSUE THREAD

**Issue by nikitagupta55** [elastic/elasticsearch-dsl-py#986]
The mapping of my Elastic search looks like below:

```
{
  "settings": {
    "index": {
      "number_of_shards": "5",
      "number_of_replicas": "1"
    }
  },
  "mappings": {
    "node": {
      "properties": {
        "field1": {
          "type": "keyword"
        },
        "field2": {
          "type": "keyword"
        },
        "query": {
          "properties": {
            "regexp": {
              "properties": {
                "field1": {
                  "type": "keyword"
                },
                "field2": {
                  "type": "keyword"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Problem is :** 
I am forming ES queries using elasticsearch_dsl Q(). It works perfectly fine in most of the cases when my query contains any complex regexp. But it totally fails if it contains regexp character `'!'` in it. It doesn't give any result when the search term contains `'!'` in it.

For eg:

1.) `Q('regexp', field1 = "^[a-z]{3}.b.*")` (works perfectly)
2.) `Q('regexp', field1 = "^f04.*")` (works perfectly)
3.)` Q('regexp', field1 = "f00.*")` (works perfectly)
4.) `Q('regexp', field1 = "f04baz?")` (works perfectly)

Fails in below case:
5.) `Q('regexp', field1 = "f04((?!z).)*")` (Fails with no results at all)

I tried adding "analyzer":"keyword" along with "type":"keyword" as above in the fields, but in that case nothing works.

In the browser i tried to check how analyzer:keyword will work on the input on the case it fails:

`http://localhost:9210/search/_analyze?analyzer=keyword&text=f04((?!z).)*`

Seems to look fine here with result:

```
{
  "tokens": [
    {
      "token": "f04((?!z).)*",
      "start_offset": 0,
      "end_offset": 12,
      "type": "word",
      "position": 0
    }
  ]
}
```

I'm running my queries like below:

```
search_obj = Search(using = _conn, index = _index, doc_type = _type).query(Q('regexp', field1 = "f04baz?"))
count = search_obj.count()
response = search_obj[0:count].execute()
logger.debug("total nodes(hits):" + " " + str(response.hits.total))

```

PLease help, its really a annoying problem as all the regex characters work fine in all the queries except !.

Also, how do i check what analyzer is currently applied with above setting in my mappings?

**Comment by nikitagupta55** [comment]
i just tried to do something like this `^(f04ba)[^z]+?$` instead of this `f04((?!z).)*` to avoid answers with z; and it did work. Does this thing gives you any hint that why `!` in the regexp query doesn't give any results?

**Comment by HonzaKral** [comment]
I see no issue trying to look for `!` in a `keyword` field using a `regexp` query:

```python
from elasticsearch_dsl import connections, Document, Keyword
class T(Document):
    kw = Keyword()

    class Index:
        name = 'i'
T.init()
T(kw='Hello!').save()
T._index.refresh()
T.search().query('regexp', kw='.*!').count()
```

What is it that your query is trying to do? To me it seems like you don't have an issue with looking for the `!` character, but instead with a lookahead...

**Comment by nikitagupta55** [comment]
@HonzaKral Yes, i figured that this is an issue with lookahead not working in ES and referred this https://stackoverflow.com/questions/51783196/negative-lookahead-regexp-doesnt-work-in-es-dsl-query/51812949?noredirect=1#comment90612707_51812949 and solved.

**Comment by HonzaKral** [comment]
thank you for the followup, closing the issue.
