### ISSUE TITLE
AttrList AttrDict  Inheritance

### ISSUE THREAD

**Issue by vc1** [elastic/elasticsearch-dsl-py#987]
AttrList inherits from list, AttrDict inherits from dict, Would it be better? Can be serialized using json.dumps.

https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/utils.py#L30

**Comment by HonzaKral** [comment]
It would severely limit the namespace available inside the object for example `update` or `get` would be unavailable. That is why we decided for composition instead.

Hope this helps!

**Comment by HonzaKral** [comment]
Also note that we have a custom `serializer` in (0) that we use when `create_connection` is being used (which is the recommended way to use the library) so the serialization will work just fine.


0 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/serializer.py
