### ISSUE TITLE
Reverse-engineer models from mappings?

### ISSUE THREAD

**Issue by rschwiebert** [elastic/elasticsearch-dsl-py#990]
In Django it is possible to take an existing database and generate the code for the schema with a single command.

Is there anything like that (or planned like that) for this? That is, grabbing the mappings from an existing elasticsearch, and then dumping generated code for models?  (I haven't found anything so far.)

Thanks

**Comment by HonzaKral** [comment]
There is no support for dumping/generating the code, but you can always define a `Document` and then do `MyDocument._index.load_mappings()` to update the `Mapping` object on the `Index` to include the fields defined in elasticsearch. You can then easily dump them by doing:
```python
for f in MyDocument._index._mapping:
    print(f'    {f} =  {repr(T._index._mapping[f])}')
```

Hope this helps!
