### ISSUE TITLE
no improvements for custom analyzer for synonyms

### ISSUE THREAD

**Issue by betajulian** [elastic/elasticsearch-dsl-py#992]
Hi there, I am facing difficulty having improvements in the elasticsearch results with regard to synonym searches...
For example, I wish to create a list of synonyms for example "fullstack" and "full-stack" or "engineer" and "developer" such that these term or term-pairs are interchangeable when I am using the metasearch function.

I have tried to follow the suggestions provided in a previous thread https://github.com/elastic/elasticsearch-dsl-py/issues/989
however, still no luck.

Basically the steps I took were...

```
# this is same as:
es_client.indices.analyze(index='resume', body={'analyzer': 'my_analyzer', 'text': 'hello world'})
```
it got this error
```
elasticsearch.exceptions.RequestError: TransportError(400, u'illegal_argument_exception', u'[MHyjrDP][127.0.0.1:9300][indices:admin/analyze[s]]')
```
even though when I printed the output for es_client, I got
```
('ES_CLIENT: ', <Elasticsearch([{u'host': 'localhost', u'port': 9200}])>)
```
so I am not sure why one showed port 9200 and another showed 9300

Regardless, when I tried to change it slightly to ignore the 400 error
```
es_client.indices.analyze(index='resume', body={'analyzer': 'my_analyzer', 'text': 'hello world', ignore=400})
```
I did not get any errors BUT the search results simply did not improve.

My synonym token filter and analyzer looks like this
```
synonym_tokenfilter = token_filter(
    'synonym_tokenfilter',
    'synonym',
    synonyms=[
        'fullstack, full-stack',
        'frontend, front-end',
        'developer, engineer',
        'science, scientist'
    ],
)

my_analyzer = analyzer(
    "my_analyzer",
    tokenizer=tokenizer("trigram", "nGram", min_gram=3, max_gram=7),
    filter=[
        'standard',
        'lowercase',
        'stop',
        synonym_tokenfilter,
        'snowball',
    ]
)
```

I realised that my class is also a bit different as I am using django-rest-elasticsearch that incidentally also does not allow me to use ElasticSearch 6...

```
class ResumeIndex(DocType):
    created = Date()
    resume_data = Text(
        analyzer=my_analyzer, fields={"raw": Keyword(ignore_above=10000)}
    )
    user_slug = Text()
    slug = Text()

    class Meta:
        index = "resume"
```
I also have tried to do this
```
# we need to make sure the index is created first
ResumeIndex.init()
```
but it got this error
```
File ".../bouncer/ht_bouncer/resumes/documents.py", line 89, in <module>
    ResumeIndex.init()
  File ".../bouncer/bouncer1/lib/python2.7/site-packages/elasticsearch_dsl/document.py", line 150, in init
    cls._doc_type.init(index, using)
  File ".../bouncer/bouncer1/lib/python2.7/site-packages/elasticsearch_dsl/document.py", line 97, in init
    self.mapping.save(index or self.index, using=using or self.using)
  File ".../bouncer/bouncer1/lib/python2.7/site-packages/elasticsearch_dsl/mapping.py", line 79, in save
    return index.save()
  File ".../bouncer/bouncer1/lib/python2.7/site-packages/elasticsearch_dsl/index.py", line 218, in save
    if not self.exists():
  File ".../bouncer/bouncer1/lib/python2.7/site-packages/elasticsearch_dsl/index.py", line 323, in exists
    return self.connection.indices.exists(index=self._name, **kwargs)
  File ".../bouncer/bouncer1/lib/python2.7/site-packages/elasticsearch_dsl/index.py", line 41, in _get_connection
    return connections.get_connection(self._using)
  File ".../bouncer/bouncer1/lib/python2.7/site-packages/elasticsearch_dsl/connections.py", line 94, in get_connection
    raise KeyError('There is no connection with alias %r.' % alias)
KeyError: "There is no connection with alias 'default'."
```
However, I was told by the predecessor who worked on the project before me that the index had already been created and once you created it one time you do not have to repeat the process anymore.

I am not sure if that is the reason... and I am not sure where I am missing yet... do you have any advice on this? Would be great if you have any insights to share. Thanks!

Note I use:
```
# elasticsearch integration
django-filter==1.1.0
django-rest-elasticsearch==0.3.3
elasticsearch==5.5.3
elasticsearch-dsl==5.4.0
```

**Comment by HonzaKral** [comment]
This is just `elasticsearch-dsl` complaining that it doesn't have proper configuration. To configure the `'default'` connection just use:
```python
from elasticsearch_dsl import connections
connections.create_connection(hosts=...)
```

What way you never have to specify `using=` argument and it will always use the default connection. You can read more about this at file:///home/honza/work/elastic/elasticsearch-dsl-py/docs/_build/html/configuration.html#configuration
