### ISSUE TITLE
How to lock the document for updating the document?

### ISSUE THREAD

**Issue by nipungarg59** [elastic/elasticsearch-dsl-py#998]
Please have a look at this stackoverflow [link](https://stackoverflow.com/questions/52018229/how-to-lock-a-document-while-updating-elasticsearch)

**Comment by HonzaKral** [comment]
The proper way to avoid concurrency issues with elasticsearch is not locking but instead using the `version` metadata ([0]). To do that simply make sure that the document contains the proper version in its `.meta` dictionary. this is done by default if the document has been retrieved using the `get` API or when specifying `.extra(version=True)` on the `Search` object ([1]).

Also please do not just refer to an outside source for your questions as we cannot guarantee the link and also it means that this issue will be of no use to anyone trying to search for the same issue. Thank you!

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_parameters_2
1 - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-version.html
