### ISSUE TITLE
AttributeError: '%r object has no attribute %r' %

### ISSUE THREAD

**Issue by dirvin04** [elastic/elasticsearch-dsl-py#999]
Background: I am running a pyspark job across a cluster using the code below.  This is ultimately the error that results. Any ideas?

Traceback (most recent call last):
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 177, in main
    process()
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 172, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/opt/dcat2-spark/scripts_and_jobs/spark_jobs/flight_status.py", line 89, in get_flight_status_times
  File "/opt/anaconda3/lib/python3.6/site-packages/elasticsearch_dsl/utils.py", line 116, in __getattr__
    '%r object has no attribute %r' % (self.__class__.__name__, attr_name))

Traceback (most recent call last):
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 177, in main
    process()
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 172, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/opt/dcat2-spark/scripts_and_jobs/spark_jobs/flight_status.py", line 89, in get_flight_status_times
  File "/opt/anaconda3/lib/python3.6/site-packages/elasticsearch_dsl/utils.py", line 116, in __getattr__
    '%r object has no attribute %r' % (self.__class__.__name__, attr_name))
AttributeError: 'AggResponse' object has no attribute 'value_as_string'

Code below: 

` # Establish Elasticsearch Client

     46     #client = connections.connections.create_connection(hosts=HOSTS, http_auth=es_auth, timeout=120, max_retries=5)
     47     client = Elasticsearch(hosts=HOSTS, http_auth=es_auth, maxsize=1000, timeout=60, max_retries=5)
     48     search = Search(using=client, index=FDPS_INDEX)
     49
     50     # Build filters to query for Flight Data messages with a code of DH, FH or CL for a given gufi
     51     match_gufi_filter = Q('bool', filter=[Q('term', gufi__keyword=gufi)])
     52     message_type_filter = Q('bool', filter=[Q('terms', message_type__keyword=['FH', 'DH', 'CL'])])
     53
     54     # Return the specified fields sorted by timestamp in ascending order
     55     results = search.query(match_gufi_filter).query(message_type_filter) \
     56         .sort('timestamp').params(size=100)\
     57         .source(fields=['timestamp', 'message_type', 'flight_status']) \
     58         .execute()
     59
     60     if not results:
     61         print("===================GUFI=======================")
     62         return (-1)
     63
     64     for message in results:
     65         if not departure_time and message.message_type == "DH":
     66             departure_time = message.timestamp
     67
     68         if not first_active_time and message.message_type == "FH" and message.flight_status == "ACTIVE":
     69             first_active_time = message.timestamp
     70
     71         if not complete_time and message.message_type == "CL" and message.flight_status == "COMPLETED":
     72             complete_time = message.timestamp
     73
     74     # Set first_active_time and complete_time if not populated
     75     if (not departure_time and not first_active_time) or not complete_time:
     76
     77         # Query for the min and max timestamps when the flight_status = "active"
     78         flight_status_filter = Q('bool', filter=[Q('terms', flight_status=['active'])])
     79         max_timestamp = A("max", field="timestamp")
     80         min_timestamp = A("min", field="timestamp")
     81
     82         search2 = Search(using=client, index=FDPS_INDEX)
     83         results = search2.query(match_gufi_filter).query(flight_status_filter) \
     84             .aggs.metric("max_active", max_timestamp) \
     85             .aggs.metric("min_active", min_timestamp) \
     86             .params(size=0).execute()
     87
     88         if not first_active_time:
     89             first_active_time = results.aggregations.min_active.value_as_string
`

**Comment by HonzaKral** [comment]
problem is on line `89` where `value_as_string` cannot be found. Can you look through the raw data (`results.to_dict()`) to check if the key is present inside `aggregations.min_active`?

Thanks!

**Comment by HonzaKral** [comment]
closing since we have no information, please feel free to reopen with additional details.

**Comment by takaomag** [comment]
In case that a document does not have the field `timestamp` or null as `timestamp`, min metrics aggregation returns null `value` and no `value_as_string`.
So, line 89 should be,
```
first_active_time = results.aggregations.min_active.value_as_string if results.aggregations.min_active.value else ''
```
